### ISSUE TITLE
Recursive error, maybe problem is in maxDeep of serialize list

### ISSUE THREAD

**Issue by alandasilvaferreira** [mbdavid/LiteDB#1]
Hello, first congratulations face, its design is amazing, really enjoyed and would like to help, for now I'll post this problem, I took a look at the source, but did not have time to try to solve it. It seems that the depth of serialization counter is not counting correctly when serializes lists.

Excuse my English, I am Brazilian and I used google translate.

**Comment by mbdavid** [comment]
Hi Alan, can you post a class example? Class serialize is a external lib - fastBinaryJson, bug can be there. If you prefer, can send in portuguese too.

**Comment by alandasilvaferreira** [comment]
Cara desculpa, nem reparei que voce era brasileiro tb haha.
Mas é o seguinte, eu estou usando o LiteDB como repositório para os meus pequenos projetos, ha tempos venho procurando um NoSQL simples como este, eu até tentei fazer um mas sem tempo fica complicado principalmente a indexação, mas vamos ao caso, eu estou usando com C# com um modelos de objetos "estático" e referencia cruzada

    public class Apartment {
        public string Number { get; set; }
        **public List<Person> Persons { get; set; }**
    }

    public class Person{
        public string Name { get; set; }
        **public Apartment Apartment { get; set; }**
    }

Repare que uma pessoa está dentro de um apartamento e um apartamento tem n pessoas, 
ai ele entra em recursão infinita.

**Comment by mbdavid** [comment]
Alan, entendi seu problema, mas acho que na verdade tem a ver com uma questão de concepção de um banco orientado a documentos (e não objetos).
O ideal é que tu utilize a referencia entre os documentos com o _id de referencia, e faça o "join" durante a busca. Considerando que as tuas duas classes são entidades (ou seja, terá uma coleção para cada uma):

```
public class Apartment {
    [BsonId]
    public string Number { get; set; }
    
    [BsonIgnore]
    public List<Person> Persons { get; set; } // Do not serialize this
}

public class Person{
    [BsonId]
    public int Id { get; set; }
    public string Name { get; set; }
    public string ApartmentNumber { get; set; }
    
    [BsonIgnore]
    public Apartment Apartment { get; set; } // Do not serialize this
}

// To seach
var apartments = db.GetCollection<Apartment>("Apartment");
var people = db.GetCollection<Person>("Person");

// To load an apartament with a List<Person> reference
var apt = apartments
            .Include(x => x.Persons = people.Find(p => p.ApartmentNumber == x.ApartmentNumber).ToList())
            .FindById("123");
            
// To load a people with Apartment reference
var person = people
                .Include(x => x.Apartment = apartments.FindById(x.ApartmentNumber))
                .FindById(456);
```

Perceba que, mesmo tendo os objetos referenciados, eu não os serializo (`BsonIgnore`). Na hora da busca é que monto a referencia. Na persistencia teriamos documentos assim:

```           
apartament1 = { _id: "123" }

person1 = { _id: 456, Name: "John", ApartmentNumber: "123" }
person2 = { _id: 457, Name: "Doe", ApartmentNumber: "123" }
```

Outra questão que vale lembrar é que nem todas as classes devem ser persistidas em coleções separadas. O exemplo classico é a "NotaFiscal" e "NotaFiscal_Item". Neste caso, deve existir apenas a referencia de Itens na NotaFiscal e todo o objeto (NotaFiscal) deve estar numa coleção (persistindo sim a NotaFiscalItem).

**Comment by alandasilvaferreira** [comment]
Exato, esse era essa a resposta que eu queria, muito obrigado pelo suporte. Vou usar muito essa biblioteca
