### ISSUE TITLE
Auto Incrementing Ids

### ISSUE THREAD

**Issue by luisvsilva** [mbdavid/LiteDB#10]
Is it possible to include auto-incrementing Ids? by using an attribute on the POCO for instance. 

That would be awesome!!!

Awesome Project By The Way

**Comment by mbdavid** [comment]
Hi Luis, I have plans for that. I'm working on dev branch before new releases.

Auto Id will be using not only in POCO, but in BsonDocuments too. So, if you use shell, _id will be created. I need implement ObjectId too...

**Comment by mbdavid** [comment]
Hi Luis, take a look on this commit on dev branch: https://github.com/mbdavid/LiteDB/commit/bf0cde93828c3032b1905264aac7bbc17cbe5eaa

**Comment by luisvsilva** [comment]
Good Stuff!!! Thanks
