### ISSUE TITLE
Observable collections

### ISSUE THREAD

**Issue by RussMathis** [mbdavid/LiteDB#100]
A way to convert, natively, the collection return type?
For example I need Observable collection for a WPF project.

**Comment by mbdavid** [comment]
Sorry @RussMathis, but I dont understand your need (I never used wpf). What did you mean collection return type? Can you post an example?

**Comment by RussMathis** [comment]
When creating ViewModels in WPF we often require ObservableCollections for list, grids or any other control needing itemsources. WPF works, somewhat, intelligently with ObservableCollections to automatically update the GUI when changes within the collection occur. 

When getting a list of records from LiteDb it would be nice if you could give the function a base collection type to derive from instead of the LiteDbCollection. This way we don't have to create a completely new ObservableCollection after fetching the LiteDbCollection. 

Otherwise we, me any way, always have to build another ObservableCollection list from the list returned from LiteDb?

Hope I've described it well enough.

Or maybe I'm lacking some understanding of how to get the ObservableCollection from the LiteCollection in the first place. Seems a waist to always be converting from list to collection. I understand, somewhat, the concept of keeping the view and viewmodel separate from the model and repository but for something so commonly used the feature just seems to fit better and a utility or extension in the BAL/Repository, for simplicity?

Thanks for the great tool!

**Comment by Skysper** [comment]
I think there is no need to do this. You can do this convert by yourself.So you can do a common BAL/Repository  which can be used anywhere ,even though the database changes to mysql or others.Or you can do this in your BAL/Repository when you get data from LiteDB.Use List class , you can convert to any others easily.
LiteDB should be independent. not only for ObservableCollection or other collection class . It will make LiteDB simple.
@RussMathis

**Comment by mbdavid** [comment]
Hi @RussMathis, now I got it. It´s like Angular/Knockout client MVVM. Observable collection "auto-update" and have changes.

This is very complicated to implement in a generic way and, as @Skysper say, it´s not primary focus of LiteDB. My work on LiteDB is to transform this database in a safe/solid solution desktop/web apps (portables/mobile in future).

If you build this solution, tell me so I can link this information with LiteDB documents.

**Comment by RussMathis** [comment]
Thanks for the input guys!

**Comment by RachamimYaakobov** [comment]
For use LiteDbCollection in WPF you just need to imploment INotifyCollectionChanged and IEditableCollectionView in LiteDbCollection.

**Comment by mbdavid** [comment]
Hi @RachamimYaakobov the problem is detect when a collection get new/deleted item from when another process (not thread). To do this, must use IPC (inter process comunication) like NamedPipes (and I'm not using yet).

**Comment by K1tson** [comment]
@RussMathis  One option to overcome this is by wrapping your LiteDB CRUD operations into separate class (which I guess that layer of abstraction is already in place) and then raising a custom event each time the DB could be changed. Then all that's needed is to instantiate and inject that wrapper reference to each of your ViewModels contructor and then subscribe your ViewModel to your custom DatabaseChanged event (or whatever you've called it) and raise INotifyPropertyChanged/CollectionChanged within the handler. I'm sure there's much better ways but it seems to be working well for me. 

Take a look at the quick (not so perfect) example I've put together below. It's not the greatest of examples but I'm sure you'll get the drift. 

**Presenter**
```
public class Presenter
{
        private DbLiteWrapper _dbLite;
        private IViewModel _presentedModel;

        public Presenter()
        {
            _dbLite = new DbLiteWrapper(@"MyDB.db");
            PresentedModel = new MainViewModel(_dbLite);
        }

        public IViewModel PresentedModel { get; set; } //with OnPropertyChanged etc...
}
```

**ViewModel**
```
public class MainViewModel : IViewModel
{
        private readonly DbLiteWrapper _dbLiteRef;
   
        public MainViewModel(DbLiteWrapper dbLiteRef)
        {
            _dbLiteRef =dbLiteRef;
            _dbLiteRef.DbUpdated += OnDbUpdate;
        }
       
        \\Bind XAML to ObservableCollection
        public ObservableCollection<ShopItem> ShopItems
        {
            get => new ObservableCollection<ShopItem>  (_dbLiteRef.GetItems<ShopItem>());
        }
        
        \\Bind XAML to ObservableCollection
        public ObservableCollection<ShopOffer> ShopOffers
        {
            get => new ObservableCollection<ShopOffer>(_dbLiteRef.GetItems<ShopOffer>());
        }

        private void OnDbUpdate(object sender, EventArgs args)
        {
            OnPropertyChanged(nameof(ShopOffers));
            OnPropertyChanged(nameof(ShopItems));
        }
}

```

**LiteDB Wrapper**
```
public class DbLiteWrapper
{
        private readonly string _dbPath;
        public event EventHandler DbUpdated;

        public ShopDb(string dbPath)
        {
            _dbPath = dbPath;
        }

        public bool AddRange<T>(IEnumerable<T> items)
        {
            using (var db = new LiteDatabase(_dbPath))
            {
                db.GetCollection<T>().InsertBulk(items);
                OnDbUpdated(this,null); \\Raise the event on DB change
                return true;
            }
        }

        protected virtual void OnDbUpdated(object sender, EventArgs args)
        {
            DbUpdated?.Invoke(sender, args);
        }
}
```
