### ISSUE TITLE
DbRef de objeto dentro de objeto

### ISSUE THREAD

**Issue by Rechdan** [mbdavid/LiteDB#1003]
Olá!

Gostaria de saber como faço para incluir objeto referenciado dentro de uma classe que referenciei em outra classe (meio confuso, eu acho kkkk)

**Comment by mbdavid** [comment]
Opa, e ae @Rechdan, tudo bom? Pois é, ficou meio confuso. Tens como copiar um exemplo? Ou dá uma olhada nos unit tests que tem sobre Include e DbRef pra ver se te ajuda

**Comment by Rechdan** [comment]
Sabia hahaha, então, queria saber se há alguma opção no próprio LiteDB para realizar o Include automático dos objetos que estão sendo referenciados dentro do meu objeto.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
