### ISSUE TITLE
IncludeAll missing in 4.1.3 build

### ISSUE THREAD

**Issue by SeAlwin** [mbdavid/LiteDB#1004]
Hello Mauricio,

Just switched from my local fork to the 4.1.3 nuget package and it seems that the new includeAll function is missing from the assembly. Do you have an updated package available?

Kind regards
Alwin

**Comment by mbdavid** [comment]
Hi @SeAlwin, I really don't know what happening...

I'm fixing in 4.1.4

**Comment by mbdavid** [comment]
https://www.nuget.org/packages/LiteDB/4.1.4

**Comment by SeAlwin** [comment]
Great, 4.1.4 does include the IncludeAll!

Thanx for the quick response.

Alwin
