### ISSUE TITLE
Collection name limitations

### ISSUE THREAD

**Issue by unoatbk** [mbdavid/LiteDB#1005]
When reading the documentation I came across:
"Collections: 3000 bytes to all collections names (each collection has 8 bytes of overhead)"

We were planning to use the LiteDB where we might end up having up towards 800-1000 collections in a single database/file , but seeing this limitation makes it look like we would have a problem using LiteDB.
Is this something that could be/will be changed sometime in the near future, or is it simply a question about changing the constant in the source and recompile?
Regards
    Uno

**Comment by mbdavid** [comment]
Hi @unoatbk, there is not only a constant in source. All collections names must be fit in database header page. For v4 (and before), LiteDB uses 4096 bytes per page (v5 will increase to 8192 with 7872 bytes for collection names + link pointer https://github.com/mbdavid/LiteDB/blob/v5/LiteDB/Utils/Constants.cs#L50). 

IF you have this amount of collections, I suggest you to split in many databases or use 3 digits collection name with C# CONSTANT or +1 collection for map 3 digis to collection name

**Comment by unoatbk** [comment]
Thank you for a quick reply. Our initial solution was designed by a person who had not seen this limitation. We had already thought of going through a mapping table table to handle this.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
