### ISSUE TITLE
FindAll() - Object inheritance and references seems to cause a problem?

### ISSUE THREAD

**Issue by digitalkirkley** [mbdavid/LiteDB#1007]
When starting up LiteDb, creating mappings, on one specific object type I keep getting an error/exception as below.  The object has property references to other objects with property names that are the same.  Is this the cause of this issue?  (I also get this on EnsureIndex)

 at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at LiteDB.EntityMapper.get_Id()
   at LiteDB.LiteCollection`1..ctor(String name, LazyLoad`1 engine, BsonMapper mapper, Logger log)
   at LiteDB.LiteDatabase.GetCollection[T](String name)

**Comment by mbdavid** [comment]
Hi, paste your code that are throwing this error to detect what going on

**Comment by mbdavid** [comment]
Hi @digitalkirkley, I will check this. Each entity must have only one single "_id" field into document.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
