### ISSUE TITLE
Check database integrity?

### ISSUE THREAD

**Issue by CIVITAS-John** [mbdavid/LiteDB#1009]
I've mentioned a rare situation that litedb may be corrupted where some pages are in wrong type which causes invalid type cast. This leads to a situation where any code visiting data may face an exception indicating the database to be corrupted, which is not acceptable, that we may encounter problems without notice and without way to fix or fully abandon the data. If we have a method for check (when the database is small it will cost very few) and recover (as many data as possible), it will be more robust even if we cannot solve the underlying problem right now.

**Comment by PascalSenn** [comment]
Can I get more information about this? How has that happened?

**Comment by CIVITAS-John** [comment]
@PascalSenn i've used modified version of 3.1.5 with reflection replaced to the unity3d branch and tested it in iOS build. I don't know how to reproduce but re-install it a lot did corrupt data 2 times. 

@mbdavid I cannot remove all Linq.Expression dependencies in 4.x so I remain in latest 3.x for now. If I am meeting with corrupted data (which is not important so I have overrided) I will send you again. Yet, as for 3.x do I have a good way to detect and abandon if needed?

**Comment by CIVITAS-John** [comment]
It will be better for user to lose some data than completely disabling the app and un-install..

**Comment by CIVITAS-John** [comment]
Or maybe we can have a mode where data integrity isn't that much ensured for a larger ability for tolerating errors, with a better ability for self-fixing

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
