### ISSUE TITLE
Zerar Autoincremento

### ISSUE THREAD

**Issue by saulovsx** [mbdavid/LiteDB#1010]
Olá Maurício,

É possível zerar o index _id autoincremento de uma coleção?
Percebi que isso ocorreu após uma atualização recente. É possível desabilitar essa função em uma coleção?

**Comment by mbdavid** [comment]
Oi @saulovsx, blz?

Cara, o AutoId só é usado quando não existe _id informado, caso contrário, ele usa o _id que tu passou. Por isso não fazia muito sentido não ter o AutoId. Lembrando que o campo "_id" é obrigatorio em todo documento armazenado em uma coleção e ele geralmente é convertido de uma classe pela propriedade "Id", marcada com atributo BsonId ou usando fluent mapper.

Se tu não quer usar o AutoId, vai ter que controlar manualmente.

Em termos de sequencial, não tem a opção de zerar pois este é pego direto pelo insert o maior valor, então teoricamente não teria motivo para zerar.

**Comment by mbdavid** [comment]
Então, essa informação fica na página da coleção e se chama `Sequence`. Fica aqui:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Engine/Pages/CollectionPage.cs#L49

Dá pra ver o incremento dela no insert, bem aqui:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Engine/Engine/Insert.cs#L85

Logo abaixo é possivel ver a regra que diz que, ao incluir um registro informando um "_id", com um valor maior que a sequence atual, a sequence assume este valor.

A opção de zerar realmente não tem. Vou adicionar como feature-request pois já estou trabalhando na proxima versão.

Abs,

**Comment by saulovsx** [comment]
Ok Maurício, Obrigado.
