### ISSUE TITLE
How to change the name of a BsonRef

### ISSUE THREAD

**Issue by wilberolive** [mbdavid/LiteDB#1012]
I have a class like this.

```
Public Class ClassItem
    Public Property Name As String

    <LiteDB.BsonRef("Category")>
    Public Property Group As ClassGroup
End Class
```

I have a list of object instances of this class that are stored in a database. When I load the database, I check the UserVersion to see if it needs to be upgraded. As part of this upgrade I need to change the BsonRef name from "Category" to "Group" but I don't know how.

When I inspect the database in LiteDB Viewer and inspect the object as a string for one of the items, it looks like this.

{"$id":80,"$ref":"Category"}

I need to upgrade it so it looks like this.

{"$id":80,"$ref":"Group"}

Also, how would I change the actual type name of the BsonRef if I need to?

For example, if I need to change:

```
<LiteDB.BsonRef("Group")>
Public Property Group As ClassGroup
```

To:

```
<LiteDB.BsonRef("Group")>
Public Property Group As ClassItemGroup
```

**Comment by mbdavid** [comment]
You can change your existing creating a small script that read your data as BsonDocument and change it. You can use `LiteEngine` instance for that:

```
var db = new LiteEngine("...");
var result = db.Query("yourCol").ToArray();
foreach(var doc in result)
{
    doc["field"].AsDocument["$ref"] = "Group";
    db.Update(doc);
}
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
