### ISSUE TITLE
Customly filter out type members

### ISSUE THREAD

**Issue by superware** [mbdavid/LiteDB#1014]
It's not always desired/possible to reference LiteDB and BsonIgnoreAttribute on any class being stored.

Will highly appreciate an option to customly filter out type members (e.g. according to IgnoreDataMemberAttribute, NonSerializedAttribute etc).

```
public Func<Type, MemberInfo, bool> FilterTypeMember;

...

// checks [BsonIgnore]
if (memberInfo.IsDefined(ignoreAttr, true)) continue;

if (!FilterTypeMember(type, memberInfo)) continue;
```

Thanks you!

**Comment by mbdavid** [comment]
Hi @superware, you can resolve this overwriting `BsonMapper.GetTypeMembers` (you need use this new class on `LiteDatabase` ctor).

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.cs#L346

You can remove (or add) any field that you can be serialized.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
