### ISSUE TITLE
Can I set a default value for a variable

### ISSUE THREAD

**Issue by Reddevildragg** [mbdavid/LiteDB#1017]
Is there a way to assign a default value to a variable of a class currently im doing it like this.

```
    public string Title { get; set; };
    public string Description{ get; set; };

//when creating a new entry in the database
                    _loaded = new ProjectData()
                    {
                        Title = "Title",
                        Description = "Description"
                    };
```

Which is fine and works, but wondering if there was a better way to assign default values IE

```
[Default("Title")
    public string Title { get; set; };
```

Thanks

**Comment by mbdavid** [comment]
Just use C# 7 doest work?

```
public class Order
{
    public string Title { get; set; } = "Default Value";
    public string Description { get; set; } = "My initial value";
}
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
