### ISSUE TITLE
Shell: Update existing doc by id throws Unexpected token

### ISSUE THREAD

**Issue by rhullah** [mbdavid/LiteDB#1019]
Using the following command: `db.Collection.update <jsonDoc>` in the shell returns an *Unexpected token* error.  I believe the issues is in [`CollectionUpdate` command](https://github.com/mbdavid/LiteDB/blob/d3fa9866d702ea35676f67b98b714689422a38bf/LiteDB/Shell/Collections/Update.cs) in that it deserializes the string but doesn't consume it from the StringScanner.  So when `s.ThrowIfNotFinish()` runs, it doesn't think the string is consumed so it throws an exception.

https://github.com/mbdavid/LiteDB/blob/d3fa9866d702ea35676f67b98b714689422a38bf/LiteDB/Shell/Collections/Update.cs#L34

**Comment by mbdavid** [comment]
Thanks... fixed. Will be in next release
