### ISSUE TITLE
Need Help: Reading from Json an inserting to collection

### ISSUE THREAD

**Issue by vijaykirann** [mbdavid/LiteDB#1020]
Hi,
Im getting the following error while trying to read from json and inserting into Db
 below is code:             
```
            openLoadDef.FileName = "";
            openLoadDef.ShowDialog();
            string errordef = openLoadDef.FileName;
            List<BsonDocument> docs = new List<BsonDocument>();
            StreamReader r = new StreamReader(errordef);
            var json = r.ReadToEnd();
            var jsonObj = JsonSerializer.Deserialize(json);
            docs = BsonMapper.Global.ToDocument(jsonObj);
            using (var db = new LiteDatabase("ErrorMsg.db"))
            {
                db.GetCollection("ErrorMsg").InsertBulk(docs);
            }
```
I'm getting the error at BsonMapper 
Cannot implicitly convert type 'LiteDB.BsonDocument' to System.Collections.Generic.List<LiteDB.BsonDocument>'

Can you please advise whats needs to be changed.
Input is a plain json file.

**Comment by mbdavid** [comment]
Is your file has a single JSON document or an JSON ARRAY of documents?.

**Comment by vijaykirann** [comment]
Hi David,
The file looks like below saved as error.json
{
"MessageCode" : "SBL-GEN-00010",
"MessageDescription" : "Siebel Internal Error",
"MessageSolution" : "Resolution Undocumented"
},
{
"MessageCode" : "SBL-GEN-00011",
"MessageDescription" : "Internal: invalid arguments",
"MessageSolution" : "Resolution Undocumented"
},
{
"MessageCode" : "SBL-GEN-00012",
"MessageDescription" : "Internal: insufficient buffer space provided",
"MessageSolution" : "Resolution Undocumented"
}

**Comment by mbdavid** [comment]
It's no a valid JSON file.... try add [ ] to transform into an array and than do a for-each to insert into database

**Comment by vijaykirann** [comment]
you mean like
 [{
"MessageCode" : "SBL-GEN-00010",
"MessageDescription" : "Siebel Internal Error",
"MessageSolution" : "No solution is documented at this time"
},
{
"MessageCode" : "SBL-GEN-00011",
"MessageDescription" : "Internal: invalid arguments",
"MessageSolution" : "No solution is documented at this time"
},
{
"MessageCode" : "SBL-GEN-00012",
"MessageDescription" : "Internal: insufficient buffer space provided",
"MessageSolution" : "No solution is documented at this time"
}]

But wanted to try InsertBulk .. please help..

**Comment by vijaykirann** [comment]
Hi David,
Im not able to convert the BsonValue (jsonObj) to BsonDoc (Docs), tried to loop the Obj but wasn't working. Please help

**Comment by mbdavid** [comment]
`BsonDocument` inherits `BsonValue` so you can cast or call `.AsDocument` property.

```
var array = JsonSerializer.DeserializeArray("[ { ... }, { .... }, ... ]"); // here an array
var docs = array.Select(x => x.AsDocument).ToList(); // here a document list (not array);
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
