### ISSUE TITLE
Concurrency, continuous write / continuous read..

### ISSUE THREAD

**Issue by unoatbk** [mbdavid/LiteDB#1021]
We have a scenario where we are recording data continuously into the database, basically via one thread in a process.  Then we have another thread that retrieves data from the database, like: give me all measurements from 12:00 today until 14:00, but it could be longer durations, like weeks.
My question would this worker having a writer and a reader, without having to close/open the database while they are runnning. I.e. could both treads be running all the time, and I would have consistent data?
Regards
   Uno

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
