### ISSUE TITLE
Any plan to seperate a 4.x version without emit?

### ISSUE THREAD

**Issue by CIVITAS-John** [mbdavid/LiteDB#1024]
It prevents litedb from working well on iOS platform whether for Unity (which already has 4.6 support and will have .net Standard 2.0 in a near future) or Xamarin..

**Comment by mbdavid** [comment]
Did you say `Reflection.Emit`?

**Comment by CIVITAS-John** [comment]
Yes, Reflection.Emit and all Linq.Expressions dependencies (since they share a common base)

**Comment by mbdavid** [comment]
Hi @CIVITAS-John, v4 and v5 needs use Linq.Expression and there is no way to remove this (BsonExpression must compile STRING expressions). For Unity version, you need check unity branch (v3).

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
