### ISSUE TITLE
DropCollection NullReferenceException

### ISSUE THREAD

**Issue by chenhuang444** [mbdavid/LiteDB#1028]
![capture](https://user-images.githubusercontent.com/14193838/42489257-980ea2ca-843c-11e8-95a0-62be0fd3d7da.PNG)
The DropCollection call was made from a separate thread, and Dispose was called explicitly on the main thread. It looks like its caused by a race condition in the null check for _steam in FileDiskService.Dispose(). Dunno is this is a bug or I should just use a lock when callilng DropCollection. Currently on version 4.1.2.0

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
