### ISSUE TITLE
How to map new project structure?

### ISSUE THREAD

**Issue by Big-ED** [mbdavid/LiteDB#1029]
Hi,

I had an assembly _Assembly1_ and class **SomeNamespace1.Class1**

Now I want to read and write my database with _Assembly2_ and class _SomeNamespace2.Class2_

But I receive **LiteDB.LiteException: 'Type 'Assembly1.SomeNamespace1.Class1' not found in current domain (_type format is 'Type.FullName, AssemblyName').'**, because LiteDB uses __type_ field for deserialization.

How I can map new structure?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
