### ISSUE TITLE
How to use shell commands in C# ?

### ISSUE THREAD

**Issue by blahasoft** [mbdavid/LiteDB#1030]
Hello,

I'm using LiteDB 4  in C#. LiteDB4 should have shell commands built-in. 

I've a collection defined: var col = LiteDatabase.GetCollection<T>(name);

I need to update all collection rows with the same value in certain column (eg. set columnValue=SampleString).
How can I use a collection command Update (eg. db.col.update {Name: "SampleString" }) on my collection? Existing command col.Update() doesn't allow such syntax.

Thanks for help.
Jan Blaha

**Comment by mbdavid** [comment]
In v4 you can use this syntax on shell:

update <field|path>=<value|expression>, [..] [where <filter>] - Update multiple documents fields using filter query

db.customer.update Name = "John" where _id = 1
db.customer.update Age = $.Age + 1 where _id > 0
db.customer.update Addresses[*].Full = Addresses[*].Street + ", " + Addresses[*].Number

But... take a look in new version... how cool is that (support for SQL command it's much easy) 😄 

![image](https://user-images.githubusercontent.com/1137197/42975622-7a0d3c6a-8b93-11e8-85cf-1bf778feecc2.png)

**Comment by E4N** [comment]
Do we have an ETA about the upcoming version? 👍

**Comment by mbdavid** [comment]
Sorry, but what `ETA` means?

**Comment by mbdavid** [comment]
I have not a clear roadmap for v5, but I believe that v5 engine are quite good... now I need work on client side (basically LINQ visitor and wired protocol). My goal still release in this year....
