### ISSUE TITLE
There is no _id field mapped in your type

### ISSUE THREAD

**Issue by zeehtecnologia** [mbdavid/LiteDB#1032]
Hello Everybody!

Maybe my doubt is so simple for you, but I have spent all my afternoon on it.
First, I'm Brazilian too, and I'm very glad to see what Mauricio have made until now.

So, let's go to the problem:
I am trying to make some one-to-many relationships, but with no success yet.

`public LiteDB.LiteDatabase GetConn() => new LiteDB.LiteDatabase("Filename=database.db;Password=dbPassword");

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            var db = GetConn();

            db.Mapper.Entity<Estufa>()
                .Id(x => x.Id)
                .DbRef(x => x.Secagens, "secagens");
            db.Mapper.Entity<MedidorPressao>()
                .Id(x => x.Id)
                .DbRef(x => x.Suspensao, "configuracoesSuspensao");
            db.Mapper.Entity<Configuracoes>()
                .Id(x => x.Id)
                .DbRef(x => x.Estufas, "estufas")
                .DbRef(x => x.MedidoresPressao, "medidoresPressao");

            var configuracoesCol = db.GetCollection<Configuracoes>("configuracoes");
            var estufasCol = db.GetCollection<Estufa>("estufas");
            var medidoresCol = db.GetCollection<MedidorPressao>("medidoresPressao");
            var secagensCol = db.GetCollection<Secagem>("secagens");

            configuracoesCol.IncludeAll().Delete(x => true);

            var config = new Model.Configuracoes();
            config.DadosEmpresa = new Model.DadosEmpresa
            {
                Nome = "Zeeh technologies"
            };
            var listaEstufas = new List<Estufa>();

            for (var i = 1; i <= 20; i++)
            {
                var estufa = new Estufa
                {
                    Descricao = $"Estufa {i}",
                    IsTcp = false,
                    Numero = i,
                    SerialPortName = "COM3"
                };
                //var secagens = new List<Secagem>()
                //{
                //    new Secagem
                //    {
                //        Byte1 = 255,
                //        Byte2 = 245,
                //        Byte3 = 222,
                //        Byte4 = 123,
                //        Byte5 = 221,
                //        Numero = 1
                //    }
                //};
                //secagensCol.Insert(secagens);
                //estufa.Secagens = secagens;
                listaEstufas.Add(estufa);
            }

            var medidores = new List<MedidorPressao>{new MedidorPressao
            {
                Descricao = "Pressão 1",
                IsTcp = false,
                Numero = 101,
                SerialPortName = "COM3"
            } };

            config.Estufas = listaEstufas;
            //config.MedidoresPressao = medidores;
            
            
            estufasCol.Insert(config.Estufas);
            //medidoresCol.Insert(config.MedidoresPressao);
            configuracoesCol.Insert(config);
        }`

```
public class Configuracoes
    {
        public int Id { get; set; }
        public DadosEmpresa DadosEmpresa { get; set; }
        public ConfigEmail ConfigEmail { get; set; }
        public IEnumerable<Estufa> Estufas { get; set; }
        [BsonRef("medidoresPressao")]
        public IEnumerable<MedidorPressao> MedidoresPressao { get; set; }
    }
```

```
public class Estufa
    {
        public int Id { get; set; }
        public int Numero { get; set; }
        public string Descricao { get; set; }
        public bool IsTcp { get; set; }
        public string SerialPortName { get; set; }
        public string TcpHostName { get; set; }
        public int TcpPort { get; set; }

        public IEnumerable<Secagem> Secagens { get; set; }
    }
```

I really don't have any idea on how can I "map" this _id Field, I have also tried to use the attribute [BsonId] on the Id property, also tried to change the type of Id Property to Guid, ObjectId, without success too...

Do anyone here already had this problem?
Your help will be really appreciated.

Thank's!

**Comment by zeehtecnologia** [comment]
Hello!! After spent a lot of time, I have finally found the problem...
It's related to the usage of "IEnumerable", I changed it to List and now everything looks fine!
I'll continue my research to found a way to use abstract classes and interfaces...

Regards!

**Comment by mregni** [comment]
This solution seems to fix my problem as well. But is there any way to use an IEnumerable instead of a List with [BsonRef]?
