### ISSUE TITLE
LiteDb 4.1.2 - Index on 'long' field does not work. Possible?

### ISSUE THREAD

**Issue by AntonSemenovKazan** [mbdavid/LiteDB#1034]
**Version:**
LiteDb 4.1.2

**Problem:**
I have about 10K documents in LiteDb.
I am trying to perform db.GetCollection<PosOrder>(CollectionName).Find(o => o.Revision => someValue).
I expect documents to be filtered and retrieved quickly by IndexField filter.
But it is slow, more than 1-5-10 minutes, so i suspect, index filter is working incorrectly.
And we tried using FindAll().ToList().Where(o => o.Revision => someValue), which should be slower, as it reads all data from DB and then filters in memory, but actually it works much faster even though filter leaves only about 30-50 entities, satisfying revision condition.

**Question:**
What I do wrong? Ideas?

**Code details:**

Data:
```
public class Order{
public Guid Id {get; set;}
public long Revision {get; set; }
}
```

Init Db:
```
var db = new LiteDatabase(connectionString);
                db.GetCollection<Order>(CollectionName).EnsureIndex(o => o.Id);
                db.GetCollection<Order>(CollectionName).EnsureIndex(o => o.Revision);
```

ConnectionString:
```
ConnectionString
            {
                Filename = Path.Combine(databaseDir, fileNum + ".litedb"),
                InitialSize = initialSizeMb * 1024 * 1024,
                LimitSize = int.MaxValue,
                Mode = FileMode.Exclusive,
                Journal = true,
                Timeout = TimeSpan.FromMinutes(1),
                CacheSize = 5000,
                Password = password,
            }
```

Slow query via LiteDb:
```
db.GetCollection<Order>(CollectionName)
.Find(o => o.Revision >= someValue)
.ToList()
```

Fast query, but not good:
```
db.GetCollection<Order>(CollectionName)
.FindAll()
.ToList()
.Where(o => o.Revision >= someValue)
.ToList()
```

**Remarks:**
1. I can get all indexes and i see there field Revision.
2. I tried using Query.GTE, but result the same.
And as I understand o => o.Revision > someValue the same thing.

**Comment by mbdavid** [comment]
Hi @AntonSemenovKazan,

How much result do you expect using this `>=`? Long values can be indexed with no problems.

Try see your index in shell:

`db.Order.indexes`

Can you write some code to test this?

(ps: You don't need create index in `Id` - it´s auto-created index on collection initialize)

**Comment by AntonSemenovKazan** [comment]
I tested a little bit more and I agree that indexes for long work fine.

I tested them manually with small written by me app.
And i' ve found that i have production db with strange page.
In logs I see that LiteDb try to read page and stuck.

I think this issue I can close and I`am creating a new one with sample and strange db+page.
Thanks. =)
