### ISSUE TITLE
Attribute to keep properties in memory when they aren't stored in database

### ISSUE THREAD

**Issue by E4N** [mbdavid/LiteDB#1037]
Title says it all, could there be an attribute that prevents the properties from being reset upon each retrieve? Thank you.

The only way right now is to get the collection and call FindAll() which is what I want to avoid because it loads the whole thing in memory (around 12k rows)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
