### ISSUE TITLE
LiteDb 4.1.2 stuck on reading page when perform Find() or DropIndex()

### ISSUE THREAD

**Issue by AntonSemenovKazan** [mbdavid/LiteDB#1038]
**Version:**
LiteDb 4.1.2

**Problem:**
I have copy of liteDb from one of client and when I try to perform Find(), it stuck.
In logs I see last record & process stuck on this:
`read page #0213 :: Index`

It looks like something wrong with this page.
More over, if I try to Perform DropIndex("Revision") and I' ve caught the same problem.
In logs I see similar things and nothing happens after:
`read page #0914 :: Index`

**Question**
I have created test project with this Db.
Visual Studio 2017.
Before RUN - set DbPath.

I have attached it.
[LiteDbTest.zip](https://github.com/mbdavid/LiteDB/files/2224070/LiteDbTest.zip)

Can you watch this and give some advices/help?

Thanks a lot.

**Comment by AntonSemenovKazan** [comment]
Hello, creators of LiteDb.
The problem is still actual.
Two weeks went and no answer.

Should I wait for help or no chances ? =)

I' ve created a small project with db with the problem for your comfort to solve this.
And I really hope to take your help.

**Comment by AntonSemenovKazan** [comment]
Hi.

What is wrong with my question?

We are going to change solution storing data...
Because this is critical for us.

**Comment by mbdavid** [comment]
Hi @AntonSemenovKazan, there is no problem with your question. I always try answer as much as possible, but there are some questions that has no simple solution.

You datafile is corrupted, and the main question is: how did you that? How do you use LiteDB that occurs this. 
Is async use? Is concurrent write? Is after some specific method (like shrink)?
I try many was to reproduce this and I still with no answer.
I use LiteDB.Demo project (inside source code) to test. If you want helps me I adding steps to reproduce (this in LiteDB.Demo project) I will appreciate..

ps: Current master branch contains a new static method in `LiteEngine` to recovery data.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
