### ISSUE TITLE
AutoId for custom types with 2.0.0-rc

### ISSUE THREAD

**Issue by remember664** [mbdavid/LiteDB#104]
Hi,
How can I configure `AutoId` for custom types with v2.0.0-rc?

As I can see, `BsonMapper.RegisterAutoId` method has been removed by 4952b03e and `LiteCollection.SetAutoId` does not handle custom types too.

**Comment by mbdavid** [comment]
Hi @remember664, yes, was removed... basicly because I thouth was not usable PER data type... maybe more usable PER collection. So for this v2 version, I only removed.

Did you have plans to use in another datatype diferent than ObjectId, Guid or Int?

**Comment by remember664** [comment]
@mbdavid,
I'm using `long` to support maximum documents count per collection(`UInt.MaxValue`).
For this case, I decided to generate ids from my code(by performance reason), but it's would be great to handle `long` out of box.
Also in other solutions `_id` can be a complex type.

And I have one more question: is `Documents per collections: UInt.MaxValue` a hard limitation or it can be increased?

**Comment by mbdavid** [comment]
Is your `long` _id sequencial or random? Current sequencial implementation are no concurrent safe and I didn't find an correct way to implement that (according my code structure). Now I'm using `max(_id) + 1` wicth is very fast by using index (but needs read, at least, 1 `IndexPage`). Another way that I try implement is using an "oracle sequence" like in `CollectionPage`. It's faster but I dont like too much (if I insert an document with future _id when this _id cames, will throw duplicate key).


About collection limit count, I found this:
    - `UInt DocumentCount` in `CollectionPage` class
    - `int Count(name, query)` in `Aggregate.cs` class (in this case is worst, limited in `int`). It's ease no fix, adding and `LongCount` as `List<T>` do.

The problem to change to `long` in `CollectionPage` is that all file structure will change - current datafile will not work.

**Comment by remember664** [comment]
@mbdavid,
Thanks for description. I use `long` sequence and handle thread-safe by custom code(in current case, I don't need ability to insert entity with exact id)
