### ISSUE TITLE
Nested population of a property that has no stored value throws a null ref exception

### ISSUE THREAD

**Issue by sonicblis** [mbdavid/LiteDB#1040]
When using the nested population hydration syntax (which is great), if the nested property (in the example below, AssignedUser or AssignedGroup) are both empty (non-existent in the datastore), a null ref exception is thrown.  The call looks like this:

    var assignmentInclude = taskCollection
        .Include(wt => wt.Assignments)
            .Include(wt => wt.Assignments[0].AssignedUser)
            .Include(wt => wt.Assignments[0].AssignedGroup);

and the stored task that is throwing the error (above one that is not) looks like this in the Assignments "column":

![image](https://user-images.githubusercontent.com/5229682/43270132-532cb2c2-90c2-11e8-887d-55d00665e522.png)

If this failed silently, that would be lovely.  =]

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
