### ISSUE TITLE
Sharing violation on path

### ISSUE THREAD

**Issue by emrys90** [mbdavid/LiteDB#1042]
I'm getting an exception when I try to delete my database file from within the app after opening a connection to it and closing it. This worked in v2, but not in v4. I wrap all my database calls in
using (LiteDatabase db = new LiteDatabase(DatabasePath))

What am I doing wrong that it's not releasing the file lock?

**Comment by emrys90** [comment]
I just figured it out. My Find calls I added a ToList after them, and now it seems to be working correctly.

**Comment by dxmann** [comment]
Same problem: I use the database encapsulated in a class: an ObservableCollection exposes data.

```
public class ItemsDb : IDisposable
    {
        private LiteDatabase db;
        private ILiteCollection<Item> dbItems;

        public readonly ObservableCollection<Item> Items = new ObservableCollection<Item>();

        public ItemsDb(string dbPath, string password)
        {
            db = new LiteDatabase($"Filename={dbPath};Password={password}");
            //dbItems = db.GetCollection<Item>(BsonAutoId.Guid);
            //Items = new ObservableCollection<Item>(dbItems.FindAll());
        }
        ~ItemsDb() { Dispose(); }

        public void Dispose()
        {
            Items.CollectionChanged -= Items_CollectionChanged;
            db.Dispose();
        }

        public void Load()
        {
            dbItems = db.GetCollection<Item>(BsonAutoId.Guid);
            foreach (Item i in dbItems.FindAll())
                Items.Add(i);
            Items.CollectionChanged += Items_CollectionChanged;
        }

        private void Items_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            switch (e.Action)
            {
                case NotifyCollectionChangedAction.Add:
                    foreach (Item i in e.NewItems)
                        dbItems.Insert(i);
                    break;
                case NotifyCollectionChangedAction.Remove:
                    foreach (Item x in e.OldItems)
                        dbItems.Delete(x.Id);
                    break;
                case NotifyCollectionChangedAction.Reset:
                    dbItems.DeleteAll();
                    break;
                case NotifyCollectionChangedAction.Replace:
                    foreach(Item i in e.NewItems)
                        dbItems.Update(i);
                    break;
            }
        }
    }
```
```
public partial class App : Application
{
    public ItemsDb db { get; }
    public App()
    {
        InitializeComponent();

        string key = . . . ;
        db = new ItemsDb(Path.Combine(FileSystem.AppDataDirectory, "items.db"), key);

        MainPage = new AppShell();
    }
    protected override void OnStart()
    {
        db.Load();
    }
}
```

The error appairs when:

1. I open the app: this class is created in the xamarin forms app constructor
2. I press the back button on Android and my app goes in background
3. I recall my app from the background selecting it from recent apps: when a new LiteDatabase instance is created I have the same error: `System.IO.IOException: 'Sharing violation on path /data/user/0/bla.bla.bla/files/items.db'`

What can I do?

**Comment by lbnascimento** [comment]
@dxmann Try making some code that disposes the database when your app goes to the background and opens it again when it comes back to foreground (I believe you can do it by overriding `OnSleep` and `OnResume`).

**Comment by dxmann** [comment]
I tried opening the db in OnStart and OnResume and closing it in OnSleep. It works but it not so elegant compared to the first implementation: I have to instantiate the db and the observable collection directly in the forms app.

Ciao :)
