### ISSUE TITLE
Find with Guid property

### ISSUE THREAD

**Issue by emrys90** [mbdavid/LiteDB#1043]
I'm trying to do a Find using a Guid property. It fails using both Query and Linq, no results are returned. This worked previously in v2, but not in v4. Am I doing something wrong, or are guids no longer supported?

**Comment by mbdavid** [comment]
Guid are supported in Bson specs. You can query using both Query class or Linq expression. Can you paste your code so I see what's going wrong

**Comment by mbdavid** [comment]
Is `ServerId` property your `_id` document field? Are you sure that your database constains only data that, in this field, are Guid data type. Because I don't see any problem in your code. This should be woks.... what exception/stacktrace are you getting?

**Comment by emrys90** [comment]
No it's not, it's just an id property to another model. Yes, I'm sure. As mentioned, it all worked correctly back in v2. The exception is an invalid operation on the First call due to the results being empty.

**Comment by emrys90** [comment]
If I retrieve all records and then filter by the Guid outside of the database logic I get the appropriate result back.

**Comment by emrys90** [comment]
After further testing, I've determined it's not just guids. I tried doing a Find on a string property in a different model as well and it still doesn't work. If I change it to a FindAll and then do a Where clause outside of it then it works. This was all functional in v2 though...

**Comment by mbdavid** [comment]
This made a big difference... LiteDB v4 uses Linq.Expressions to compile string expressions. This is not work in Unity. You must check last working version of LiteDB for Unity (see Unity3D branch)

**Comment by emrys90** [comment]
That's using v3 right, which has concurrency issues? Do you have any plans to get v4 or future compatible with Unity again?

**Comment by mbdavid** [comment]
In v3 you must use your own lock system. Unfortune is not possible be compatible with Unity (net 3.5 compatible) because there are lots of Linq Expressions. I was reading about some next version of Unity that works withs this linq expressions

**Comment by prajaybasu** [comment]
Unity should support .NET Standard 2.0 (according to [this](https://blogs.unity3d.com/2018/03/28/updated-scripting-runtime-in-unity-2018-1-what-does-the-future-hold/) blog post) - hopefully Unity will properly support modern C# once it moves to Roslyn soon.

**Comment by Shad0w1990** [comment]
YOU can use Query<Entity>().where(x=>x.yourGuid==id)
