### ISSUE TITLE
Uint32 properties

### ISSUE THREAD

**Issue by emrys90** [mbdavid/LiteDB#1044]
Uint32 properties seem to no longer be supported as data types. They worked in v2. Can they be added back in?

**Comment by mbdavid** [comment]
Bson specs has no support for Uin32, but in BsonMapper, Uint32 are converted into Int64 here:  https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.Serialize.cs#L72

**Comment by emrys90** [comment]
Okay then I guess the only issue is the implicit operators in BsonValue don't have Uint32 support?
