### ISSUE TITLE
Node.js

### ISSUE THREAD

**Issue by MohMehrnia** [mbdavid/LiteDB#1047]
Hi, I will connect to litedb with node.js, Is posible?

**Comment by MohMehrnia** [comment]
When release litedb with this feature

**Comment by mbdavid** [comment]
My plans is final of 2018...

**Comment by MohMehrnia** [comment]
thanks for response

*محمد مهرنیا*
*شرکت ایده پردازان دانش هوش مصنوعی*
*Cell Phone No.: **+989163085306*

*ساعت‌ها را بگذاريد كه بخوابند ، بيهوده زيستن را نيازی به شمردن نيست.*

**Comment by wormen** [comment]
hi
in current versions has the opportunity to work with NodeJS?

**Comment by lucwuyts** [comment]
Did you see this?
https://www.dotnetcurry.com/nodejs/1195/using-edgejs-combine-dotnet-nodejs

**Comment by mbdavid** [comment]
At this moment there is no way to work with LiteDB outside .net world. LiteDB is implemented and run over .net only,
