### ISSUE TITLE
IndexOutOfRangeExceptionLiteDB.IndexService in AddNode

### ISSUE THREAD

**Issue by AntonSemenovKazan** [mbdavid/LiteDB#1048]
Hello.

*Version:*
LiteDb 4.1.2

*Problem:*
Sometimes I have caught exceptions like these:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   в LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   в LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   в LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   в LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   в LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   в LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonType autoId)
   в LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   в LiteDB.LiteCollection`1.Insert(T document)
```
or
```
IndexOutOfRangeException: Index was outside the bounds of the array.
  Module "LiteDB.IndexService", line 0, col 0, in Find
    LiteDB.IndexNode Find(LiteDB.CollectionIndex, LiteDB.BsonValue, Boolean, Int32)
```

*Questions:*
Do you have any ideas what to do with these exceptions?
May be reasons?

*More details:*
We have a real example of db, where the problem appears instantly for some Ids.
Ids look like common Guid:
4bde9c40-a29f-43c1-81f7-11e3df56c989
1f1a6055-150e-40b7-8447-bb2d9cf093ad
But there are not exceptions for others Ids.

If we delete and recreate the db, there is no problem.
May be this is result of update to new version of LiteDb?
May be algorythm of calculating hash was changed or default size for hash-key, was not?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
