### ISSUE TITLE
Serializing and deserializing Dictionary<TKey,TValue> with a predefined set of keys

### ISSUE THREAD

**Issue by hoshinokanade** [mbdavid/LiteDB#1049]
I've got some troubles so far playing with a `Dictionary<TKey,TValue>` with a predefined set of keys

Here is my code where serialization will always fail. (Simplified code for simplicity)
```
public enum Genre
{
    Grass,
    Woodland,
    Deepsea,
}

public class GenresCollection: Dictionary<Genre, int>
{
    public GenresCollection(): base()
    {
        // Predefine the dictionary with all possible keys
        foreach (var item in Enum.GetValues(typeof(Genre)).Cast<Genre>())
            this[item] = default;
    }
}

public class IssueTest
{
    public void Test()
    {
         var collection = new GenresCollection();
         // This will reproduce the unexpected behavior [First issue]
         var doc = BsonMapper.Global.ToDocument(collection);
         // After bypassing [First issue], here comes [Second issue]
         var obj = BsonMapper.Global.ToObject<GenresCollection>(doc);
    }
}
```

### First issue: System.IndexOutOfRangeException
This issue is described in #928.
> If obj type is IDictionary but not generic type,this will cause the type.GetTypeInfo().GetGenericArguments() is empty and throw a System.IndexOutOfRangeException: Index was outside the bounds of the array

To further illustrate, this unexpected behavior could be easily reproduced by any class that inherit from Dictionary<TKey,TValue> but itself not generic. `GenresCollection` in the example falls in this case.

However, the build in the pull request failed and was not accepted at the end of the day.

### Second issue: System.ArgumentException
This issue seems to be new to the discussion.

Everybody knows a deserializer to get the dictionary by first calling the public parameterless constructor and then put the key value pairs into it.

For some particular purposes, for example when I am going to visualize all `Genre` with its `Value`. All `Genre` should show up no matter its corresponding value is not set. That's why one may inherit `Dictionary<Genre, int>` and do the magic in the default constructor.

This magic will fail because the deserializer attempted to add the key-value pair after the predefined set of keys all get settled down.

I guess, somehow `Add(key, value)` is called instead of `[key] = value`. If the indexer is called instead it would be nice as the indexer could override the value when the key is already defined.

In both issues, I don't think these features are intentionally left so these may be bugs. (Inherit from Dictionary<TKey,TValue> is just pretty normal)
Especially for pull request #928, I hope you would revisit and consider these minor changes again.
Thank you for your time.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
