### ISSUE TITLE
Version 2.0.0 release date

### ISSUE THREAD

**Issue by rokolab** [mbdavid/LiteDB#105]
Hello.

When do you expect official release for 2.0?

**Comment by a44281071** [comment]
I'm following it's progress closely, too.

**Comment by mbdavid** [comment]
Hi! My initial plans was release v2 in jan/31. This release will be only to fix bugs founded in current rc and update all documentation. But, #96 issue is bit complicated to resolve... and It´s very important to fix. So maby I will need more one or two weeks.

**Comment by rokolab** [comment]
Great. Tyt :+1:

**Comment by mbdavid** [comment]
After a long time, now it's official: 31/07 :smile:
