### ISSUE TITLE
How to run the shell on Raspberry Pi?

### ISSUE THREAD

**Issue by heyandy1st** [mbdavid/LiteDB#1050]
Ok, I am missing something obvious I am sure..

I have a program running written in .Net Core 2.1 running and writing to a LiteDB file on a Raspberry Pi.  That all appears to be working fine.  Now I want to run the shell so I can query the .db file to just see the data is good and indexes appear to be good.  (i.e. I want "adhoc" access to my .db file.)

How do I run the shell?   I know it is mentioned the functionality is in the LiteDB.dll, but I don't see a way to run it, if I try, of course I get the "No entry point" defined as it is a DLL not an executable.

I have tried just writing a basic Console app that simply did the following:
        static void Main(string[] args)
        {
            var db = new LiteEngine(args[0], false);
            string cmd = "empty";
            while (!cmd.Equals("quit", StringComparison.CurrentCultureIgnoreCase))
            {
                cmd = Console.ReadLine();
                db.Run(cmd);
            }
        }
This just always throws an error that it isn't a command.

Help, how to I run a simple adhoc console on a different platform then windows?

**Comment by stitch10925** [comment]
You can download the shell (LiteDB.Shell.exe) from here:

https://github.com/mbdavid/LiteDB/releases

You will also need the LiteDB.dll which needs to be in the same folder as the shell. Then you can simply execute the LiteDB.Shell.exe and query your database

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Comment by Pysis868** [comment]
> You can download the shell (LiteDB.Shell.exe) from here:
> 
> https://github.com/mbdavid/LiteDB/releases
> 
> You will also need the LiteDB.dll which needs to be in the same folder as the shell. Then you can simply execute the LiteDB.Shell.exe and query your database

I don't see a shell there.  Searched the page, expanded assets only contains source code archives.
Somewhat searched project, including issues, which is how I found this post.
Website just links to library access, such as using nuget and others.
Can be built, but not immediately available as mentioned.
Version `5.0.19` is recent for today.
I see `v5-0beta` mentions `Shell tool in netcore3.0`, but no additional asset row available there either.
`v5-alpha2`: `Added back LiteDB.Shell (netcore tool) for SQL commands`.
[v4.0 release](https://github.com/mbdavid/LiteDB/releases/tag/v4.0.0): does seem to have it, just not specified here, and probably an old version now, so building is best again?
