### ISSUE TITLE
Select data filtered by DateTime

### ISSUE THREAD

**Issue by ghost** [mbdavid/LiteDB#1053]
I have stored data to litedb, for exp.,

```
{
  {
    "_id": {
      "$guid": "fdc994f0-0e98-4d1a-4112-08d5f134d7f7"
    },
    "ValidFrom": {
      "$date": "2018-07-24T00:00:00.0000000Z"
    },
    "ValidTo": {
      "$date": "2018-08-11T00:00:00.0000000Z"
    }
  }
}
```

and I want to select it by query. 
I do request to litedb
`Find(Query.LTE("ValidTo", DateTime.Today)`
but no records were received from db.
I know that I can select all data from db and use `.Where` expression to filtered it, but I don't want read all data from db.
Any ideas?

**Comment by Alexbogss** [comment]
`[FromQuery(Name = "from_date")] DateTime? fromDate = null,
[FromQuery(Name = "to_date")] DateTime? toDate = null` - api args

                if (fromDate != null)
                {
                    query = Query.And(
                        query,
                        _db.Mapper.GetQuery<Document>(_ => _.CreateDateTime.ToFileTime() >= fromDate.Value.ToFileTime())
                    );
                }

                if (toDate != null)
                {
                    toDate = toDate.Value.AddDays(1); // include current day
                    query = Query.And(
                        query,
                        _db.Mapper.GetQuery<Document>(_ => _.CreateDateTime.ToFileTime() <= toDate.Value.ToFileTime())
                    );
                }

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
