### ISSUE TITLE
Could not load file or assembly 'LiteDB, Version=4.1.4.0

### ISSUE THREAD

**Issue by josephcenk** [mbdavid/LiteDB#1054]
On development machine everything is working good. 
When pushing code on buildserver to generate release for QA team, getting below error. Please advise to fix it

`[App][1] App exit due to exception: An unhandled exception occurred: Could not load file or assembly LiteDB, Version=4.1.4.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27' or one of its dependencies. The system cannot find the file specified.
16:27:50.387   [App][1] System.IO.FileNotFoundException: Could not load file or assembly 'LiteDB, Version=4.1.4.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27' or one of its dependencies. The system cannot find the file specified.

16:27:50.387   [App][1] File name: LiteDB, Version=4.1.4.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27

16:27:50.387   [App][1]    at ConfigurationCore.DB.LiteHelper.createDb()

16:27:50.387   [App][1]    at ConfigurationCore.DB.LiteHelper..ctor()

16:27:50.387   [App][1]    at ConfigurationCore.Config.RequireImport()

16:27:50.387   [App][1]    at ConfigurationCore.Config.Init()

16:27:50.387   [App][1]    at MainWindow.OnLoaded(Object sender, RoutedEventArgs e)

16:27:50.387   [App][1]    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

16:27:50.387   [App][1]    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

16:27:50.387   [App][1]    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

16:27:50.387   [App][1]    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)

16:27:50.387   [App][1]    at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)

16:27:50.387   [App][1]    at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)

16:27:50.387   [App][1]    at MS.Internal.LoadedOrUnloadedOperation.DoWork()

16:27:50.387   [App][1]    at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()

16:27:50.387   [App][1]    at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()

16:27:50.387   [App][1]    at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)

16:27:50.387   [App][1]    at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)

16:27:50.387   [App][1]    at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)

16:27:50.387   [App][1]    at System.Windows.Interop.HwndTarget.OnResize()

16:27:50.387   [App][1]    at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)

16:27:50.387   [App][1]    at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

16:27:50.387   [App][1]    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

16:27:50.387   [App][1]    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

16:27:50.387   [App][1]    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

16:27:50.387   [App][1]    at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

16:27:50.387   [App][1] 

16:27:50.387   [App][1] WRN: Assembly binding logging is turned OFF.

16:27:50.387   [App][1] To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

16:27:50.387   [App][1] Note: There is some performance penalty associated with assembly bind failure logging.

16:27:50.387   [App][1] To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

16:27:50.387   [App][1] `

**Comment by josephcenk** [comment]
Apologize for making noise, issue was on our side.

**Comment by fredrikbonde** [comment]
well, I have the same issue, but on my dev machine. Mind if I ask what the issue was?

**Comment by MichaelRumpler** [comment]
Same here.

I have a solution with multiple projects. One of them references LiteDB. My main project and the unit tests only reference the other project and not LiteDB directly. When I converted my  DB project from net47 to netstandard2.0 everything compiles, but the LiteDB.dll is not copied over to the other projects bin\debug folder.
I don't think, that this is LiteDB's problem, but I don't know what I did wrong and found this issue.

**Comment by fredrikbonde** [comment]
Turned out I was a muppet, I had a project called LiteDB (same name as the nuget package), that was a bad idea :-) after changing project name it worked.

**Comment by MichaelRumpler** [comment]
Looks like it is https://github.com/NuGet/Home/issues/4488

**Comment by Edgaras91** [comment]
For anyone googling the title, I had the same error when another NuGet package was using its own LiteDB, and I added this LiteDB in addition to it. In my scenario, it was [Monkey Cache](https://github.com/jamesmontemagno/monkey-cache) package
