### ISSUE TITLE
Timeout. Database is locked for more than 00:01:00

### ISSUE THREAD

**Issue by Crshi** [mbdavid/LiteDB#1056]
I use LiteDb to make a tool to manage data.
About 3 people use it ,and the database is in a Shared folder,the problem can not be position,now I just wanna know how can I recovery the database,because when I am updating data,it always been "Timeout. Database is locked for more than 00:01:00". thank you
.net Framework version:4.6.2
litedb version:4.1.4

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
