### ISSUE TITLE
Upsert array and Insert array memory leaks

### ISSUE THREAD

**Issue by falahati** [mbdavid/LiteDB#1058]
Hey David, me again :)

Take a look at the following results:

> Insert Test:
> -- Memory Used: 36MB - Elapsed: 81163ms
> Insert Array Test:
> -- Memory Used: 116MB - Elapsed: 1981ms
> Insert Bulk Test:
> -- Memory Used: 35MB - Elapsed: 1987ms
> Insert or Update Test:
> -- Memory Used: 36MB - Elapsed: 83342ms
> Upsert Test:
> -- Memory Used: 116MB - Elapsed: 2179ms
> Manual Upsert Test:
> -- Memory Used: 35MB - Elapsed: 145922ms
> Finished.

A sample project is attached:
[LiteDBUpsertLeak.zip](https://github.com/mbdavid/LiteDB/files/2281749/LiteDBUpsertLeak.zip)

Now, don't underestimate the 80MB difference, that's for 100,000 rows. Increasing the number to 1M rows and you get this:

> Insert Array Test:
> -- Memory Used: 1172MB - Elapsed: 21948ms
> Insert Bulk Test:
> -- Memory Used: 24MB - Elapsed: 22438ms
> Upsert Test:
> -- Memory Used: 1172MB - Elapsed: 24621ms
> Finished.

**Comment by falahati** [comment]
The proposed new method should kinda solve the problem with Upsert. I didn't actually go through all parts of the code as I was expecting to get lost, but simply batching the array seems to solve the problem. I have no idea why tho, so the underlying problem is still there.

Do you maybe cache something in transactions? It seems like a common problem with long transactions.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
