### ISSUE TITLE
Filter like full text search

### ISSUE THREAD

**Issue by ju2pom** [mbdavid/LiteDB#1060]
Hi David,

I have a database in which I'd like to perform a kind a full text search:
- In a search field the user can type words
- I want to search for those words in several fields (but in a single collection)
- One of the field is an array of strings.
- I'm currently using the Linq to Object query (but I'm open to another approach)

Could you explain me how to achieve such kind of query if it's possible?
Thanks for your help and for this great library !

**Comment by mbdavid** [comment]
Hi @ju2pom, in a very long time ago I pretend to implement full text search on LiteDB... it's is a branch called FTS. But it's quite complicated and I abandoned the idea.

There is Lucene.net for this. And also, there are a plugin that implement lucene disk inside LiteDB.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
