### ISSUE TITLE
LiteDb objects allocate 200mb for 20mb lists

### ISSUE THREAD

**Issue by fcin** [mbdavid/LiteDB#1062]
I have a project where I have to store 16 objects, each containing a list of 185000 doubles. Overall size of the object should be around 20-30 mb, but when I try to retrieve it from database, the database allocates 200 mb to retrieve this 20-30 mb object.  

My questions are:

1.  Is this expected behaviour?
2.  How can I avoid such huge allocation of memory when I just want to retrieve one document? Here is fully replicable example and screenshots of profiler:

```
class Program
    {
        private static string _path;

        static void Main(string[] args)
        {
            _path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "testDb");

            // Comment after first insert to avoid adding the same object.
            AddData();

            var data = GetData();

            Console.ReadLine();
        }

        public static void AddData()
        {
            var items = new List<Item>();
            for (var index = 0; index < 16; index++)
            {
                var item = new Item {Values = Enumerable.Range(0, 185_000).Select(v => (double) v).ToList()};
                items.Add(item);
            }
            var testData = new TestClass { Name = "Test1", Items = items.ToList() };

            using (var db = new LiteDatabase(_path))
            {
                var collection = db.GetCollection<TestClass>();
                collection.Insert(testData);
            }
        }

        public static TestClass GetData()
        {
            using (var db = new LiteDatabase(_path))
            {
                var collection = db.GetCollection<TestClass>();
                return collection.FindOne(Query.EQ(nameof(TestClass.Name), "Test1"));
            }
        }
    }

    public class TestClass
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IList<Item> Items { get; set; }
    }

    public class Item
    {
        public IList<double> Values { get; set; }
    }
```

And screenshot of profiler when the object is retrieved from database:

![heap](https://user-images.githubusercontent.com/16255350/44307630-bd8f0c00-a3a5-11e8-84d2-f3168ce28004.png)

**Comment by mbdavid** [comment]
Hi @fcin, there are some problems when you have so large single document. Each value is a BsonValue that use memory than original value. Also, all pages must be allocated in memory to read this document. Also, after read all bytes, must keep recovery pages in memory too. v4 need all byte[] before start deserialize document. So, it´s consume lot of memory for this case.

You can try my dev v5 branch that works very different:
- Do not cache Extend Page
- Do not need one single byte array to deserialize document (works with stream)
- Has no more ByteReader

This must reduce your memory load to read big documents

**Comment by fcin** [comment]
Hi,

Thanks, I downloaded v5 branch and had a very quick look at it. I can see definite memory management improvement. It still allocates ~200 mb, but there is much less garbage collection happening and it seems to return memory back to the system much quicker. I will share profiler results once I have more free time. 
Do you have any tips on what else I can do to improve memory?

**Comment by mbdavid** [comment]
All memory still must be loaded (because you request all document fields - in v5 you can request only part of fields). But in v5 don't need all byte array in memory to start deserialize document.

You main problem is this ultra-large double array. If you could model your structure to split this into many documents (in another collection) will be much more efficient. You can see how FileStorage (same as MongoDB GridFS - storaging files) are implemented. Its use 2 collections, 1 for file reference and another to file chunks.

**Comment by lidanger** [comment]
Is it there is memory leaks in litedb？
A program works with litedb in single process mode(using(var db = ...){...}) for one hour, the memory usage raise to serval gbs.Size of the data file is 13 gb around.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
