### ISSUE TITLE
ConfuderEx protector 

### ISSUE THREAD

**Issue by lumisoftusa** [mbdavid/LiteDB#1063]
Hi ,

I am loving to use LiteDB in mobile and some winform app.
Well everything is working perfectly now i am  deploying my apps.
I am using https://yck1509.github.io/ConfuserEx/  ConfuserEx tool to protect the code after protection LiteDB does not work . I don't know the the problem but if i remove code protection everything works fine.
I am in serious pain please help me ASAP.

I would be very thankful to you.

Regards

ATIF SHAHZAD

**Comment by mbdavid** [comment]
Hi @lumisoftusa, I use this tool before and have some problems with others libs. I don't how they obfuscate core but do not works as excepted.

Can you create a rule to not obfuscate LiteDB in your package?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
