### ISSUE TITLE
Add field to existing document

### ISSUE THREAD

**Issue by torrog** [mbdavid/LiteDB#1065]
I'm trying to add a new field to a existing document. Have read a little bit about how its done in Mongo, so I came up with this:
`var result = db.Database.GetCollection(Collection).FindById(id).Set("DocumentType", typeof(T).Name);`
The result is true, but the document is not updated? 
I'm pretty new to documetdb's, so a little push in the right direction would be appreciated

**Comment by mbdavid** [comment]
Hi @torrog, after update your document you must run `Update` method (from collection). 

```
var col = db.Database.GetCollection(Collection)
var doc = col.FindById(id)
doc[""DocumentType"] = typeof(T).Name;
col.Update(doc);
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
