### ISSUE TITLE
Datafile is not a LiteDB database (V1.4.1 encrypted .net CORE)

### ISSUE THREAD

**Issue by areichmann76** [mbdavid/LiteDB#1066]
Hi,

i have several systems getting a "Datafile is not a LiteDB database" after heavy use (data import).

It seems it happens only on encrypted Databases.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
