### ISSUE TITLE
lazy load no liteDb

### ISSUE THREAD

**Issue by fabio-olliveira** [mbdavid/LiteDB#1069]
é possível configurar o lazy load  ou algo semelhante ao entityframework?

**Comment by mbdavid** [comment]
Olá Fábio, não tem como. A implementação do lazy load é bem complexa e passar por criar classes dinamicamente, coisa que não é o foco no LiteDB. Neste caso, tu precisa ou carregar tudo na query (Com includes) e ter metodos na tua classe que faça esta carga antes de usar.

**Comment by fabio-olliveira** [comment]
Muito obrigado, eu consegui aqui o que queria, ma não sei se é o correto, é a primeira vez que trabalho com banco de dados não relacionaln mas sugiu uma duvida aqui.
 Com  o EntityFramework  nas classe que possuem propriedades de outras classes  sembre Tenho o ObjetoId e o virtual Objeto  como no exemplo abaixo 

public class ObjetoA{

	public int Id{get; set;}
	
	public string Nome{get; set;}
}

public class ObjetoB{

	
	public int Id{get; set;}
	
	public string Nome{get; set;}
	
	public int ObjetoAId{get; set;}
	
	public virtual ObjetoA ObjetoA{get; set;}
		
}
com lite db so vou usar o ObjetoA ? e toda vez que eu salvar um novo registro que possui uma referencia de outra classe como na classe ObjetoB tenho que mandar o objetoA todo novamente ?

**Comment by mbdavid** [comment]
Isso depende. Se a ideia é usar objeto embutido (embedded document) ao salvar ObjetoB no banco com a propriedade ObjetoA populado, tudo será salvo num unico documento. Ou seja, carregar o ObjetoB ele obrigatoriamente ja vem populado (pois o JSON serializado continha o documneto)

Agora, se a ideia for referencia a outra, neste caso precisa usar [DbRef] que cria apenas um ponteiro de referencia.

Dá uma olhada no MongoDB que foi de onde tirei todos estes conceitos:

https://docs.mongodb.com/manual/core/data-model-design/

**Comment by fabio-olliveira** [comment]
Entendi.  Os includes funcionam quanto temos uma lista de objetos ?
Estou tentando obter a lita de objetos ciclos mas sempre retorna nula estou  seguindo os exemplo  deste link 
[https://github.com/mbdavid/LiteDB/wiki/LiteRepository](url)
```
 private static BsonMapper Mapper()
{
            var mapper = BsonMapper.Global;
         
            mapper.Entity<Projeto>().DbRef(item => item.Usuario).DbRef(item => item.Ciclos);
            mapper.IncludeFields = true;
            return mapper;
        }
```

```
 public static Projeto Obter(Expression<Func<Projeto, bool>> query)
        {
            using (var db = new LiteRepository(Con, Mapper()))
            {
                var Projeto = db.Query<Projeto>().Include(item => item.Ciclos).Where(query).ToList();
                return Projeto[0];
                
            }

        }
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
