### ISSUE TITLE
Transaction functionality is not available as described in docs

### ISSUE THREAD

**Issue by DavidsonA** [mbdavid/LiteDB#107]
The transaction functionality described at https://github.com/mbdavid/LiteDB/wiki/Transactions-and-Concurrency is not present in 2.0.0-rc1. In particular, I can't see the BeginTrans() and Commit() methods on LiteDatabase. I do see references to these methods inside DbEngine but this is not exposed on the public API.

Am I missing an extension method, or has the transaction behavior changed / been removed? If so, what is the correct procedure for using transactions in 2.0.0-rc1?

**Comment by Dessix** [comment]
Version 2 has removed transactions in lieu of added safety for concurrent access and write. @mbdavid has, if I recall, stated that 2.1 *may* see the return of transactions.

**Comment by mbdavid** [comment]
Hi @DavidsonA, documentation was not updated to v2.0. I need update before release final version. New v2 has `Engine` module that has no external transaction to keep all commands isolated from dev. This mean: every command is atomic.

You are not the first asking about transaction.... I will review this to v2.1

**Comment by mbdavid** [comment]
Now it's back in `master` branch. :+1:
