### ISSUE TITLE
IOS Filename Absolute path 

### ISSUE THREAD

**Issue by matipazw** [mbdavid/LiteDB#1070]
Hi,
i am trying to use LiteDb in iOs + net core 2.0. I can connect to a relative path but when I define an absolute path, it doesn't work.

In my configuration file, I have:

Filename=~/Documents/sowa/dev/db/connect/connect.db;Mode=Exclusive;"

But, when LiteDb try to connect to the database, I have a Exception with a different path:
'/Users/matiaspw/Documents/sowa/dev/code/connect/app-desktop/code/front/~/Documents/sowa/dev/db/connect/connect.db'.

I tried other options as

Filename=/Documents/sowa/dev/db/connect/connect.db;Mode=Exclusive;"
Filename=Documents/sowa/dev/db/connect/connect.db;Mode=Exclusive;"

and anyone work.

**Comment by mbdavid** [comment]
Hi @matiaspw, I'm not iOS dev, but LiteDB use this "filename" key (on connection string) direct into `new FileStream(...)` to open datafile.

Try use "LiteEngine" class that accept direct filename

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
