### ISSUE TITLE
Make BsonMapper.Deserialize public

### ISSUE THREAD

**Issue by StefanKoell** [mbdavid/LiteDB#1071]
Hi,

reading the issue: https://github.com/mbdavid/LiteDB/issues/895
we're also hitting this "edge case". We need to deserialize a BsonValue to our custom type, not the whole document. Would it be possible to make this public, please?

Thank you!
Stefan

**Comment by mbdavid** [comment]
Hi @StefanKoell, this one?

https://github.com/mbdavid/LiteDB/blob/v5/LiteDB/Client/Mapper/BsonMapper.Serialize.cs#L32

**Comment by MichaelRumpler** [comment]
No, the other direction: Deserialize.
https://github.com/mbdavid/LiteDB/blob/v5/LiteDB/Client/Mapper/BsonMapper.Deserialize.cs#L75

**Comment by mbdavid** [comment]
oh, sure.... i miss the context.

Done, will be present in next version

**Comment by StefanKoell** [comment]
Thank you!
