### ISSUE TITLE
FirstOrDefault Question

### ISSUE THREAD

**Issue by jcapellman** [mbdavid/LiteDB#1075]
New to LiteDB (porting an app from SQLite), but wanted to know what the best FirstOrDefault equivalent would be to something like:

```
using (var db = new LiteDatabase("somedb.db")) {
   var collection = db.GetCollection<SomeTable>();

   return collection.FirstOrDefault();
}
```

I was thinking of doing a collection.FindOne(a => a != null), but wanted opinions on usage.

**Comment by mbdavid** [comment]
If you want only "first data you found on collection" this use are OK:

    collection.FindAll().FirstOrDefault();

There is no special index to be used (will use `_id` index). This way will read first document in collection and stop enumerable.

If you want only know if there is any data in collection, you can be faster using "Count()" (with no parameter) that looks only collection counter (no document will be returned)

**Comment by jcapellman** [comment]
Awesome thank you for getting back to me.

On a side note, a DeleteBulk would be awesome too, right now I replaced the Bulk Delete I was using in SQLite with a foreach loop and calling:

collection.Delete(a => a.ID == item.ID)

If it could take a collection of objects and simply match internally on the items in a single transaction I imagine I would get better perf.

**Comment by mbdavid** [comment]
Hi @jcapellman, I implemented `DeleteMany` with query expression as predicate in v5.

`col.DeleteMany(x => x.Name == "John")`

https://github.com/mbdavid/LiteDB/blob/v5/LiteDB/Client/Database/Collections/Delete.cs#L41

This delete occurs inside a transaction (v5 support transactions and there is no need to use Bulk)

**Comment by jcapellman** [comment]
Awesome - can't wait for v5 to come out then.

Thanks again - and awesome library.  Was very smooth migrating off of SQLite and got some performance back.
