### ISSUE TITLE
Suggestion: Password to use SecureString

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#1077]
I noticed that the encryption password is supplied using the connection string when connection to the DB. The problem with the string type is that the data is stored as plain text and stays around until the GC choses to get rid of it. For things like passwords, the SecureString type is available. Using it properly can be a little tricky though because it's a natural thing to want to convert it to or from a normal string somewhere down the line (although it can be avoided).

https://blog.thedigitalgroup.com/usability-of-securestring-object-in-c

In the future, it might be worth offering an overloaded connection method which accepts a SecureString password parameter. In its implemention, of course, it would be important not to end up converting the SecureString to a normal string somewhere or it would defeat the purpose.

Just a thought.

**Comment by xied75** [comment]
There is never enough security. So a good thought. 👍 

But SecureString might not be the solution, many people are sceptical about it:
https://stackoverflow.com/questions/141203/when-would-i-need-a-securestring-in-net

And we need to consider the __right__ problem to solve: for LiteDB as an in-process dll, is this really a problem? What would be the potential attack surface?

When LiteDB eventually reach v5 and turns into Server/Client, then it would be the communication layer that we need to worry about, most of the time people just pick TLS/SSL for that.

My 2 pence :)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
