### ISSUE TITLE
Graphs support from samples .net

### ISSUE THREAD

**Issue by papyr** [mbdavid/LiteDB#1079]
Hi, can you please support graphs, controller [code ](http://bit.ly/2xddS0u), and [graph elemen](http://bit.ly/2CWhkTp)t is in C# 

One more like [Fallen-8](https://github.com/cosh/fallen-8) C# graph DB idea (no longer supported)

**Comment by xied75** [comment]
@papyr Something like Neo4j?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Comment by papyr** [comment]
hi any updates
