### ISSUE TITLE
How Do I know if an Embedded document is loaded or newly added ?

### ISSUE THREAD

**Issue by toumir** [mbdavid/LiteDB#1080]
Hi
```
public class Order
{
    public List<OrderDetail> Details { get; set; } = new List<OrderDetail>();
}

// has no Id - is embedded document
public class OrderDetail
{
    public int Quantity { get; set; }
    [DbRef("products")]
    public Product { get; set; }
}

public class Product
{
    public int ProductId { get; set; }
    public string ProductName { get; set; }
    public decimal Price { get; set; }
}
```
After loading an Order with its embedded documents, I want to change an OrderDetail via UI
how do I know if the OrderDetail in question is loaded or newly added as long as there is not an Id?
Thanks for the great project :)

**Comment by mbdavid** [comment]
When you save one Order, there is difference between loaded/newly OrderDetail.. all items will be saved inside datafile. If you want track this, you must implement some check property using `[BsonIgnore]` in OrderDetail

**Comment by toumir** [comment]
@mbdavid  I am getting confused, can you explain more? can give me a pseudo code ? 
Thanks for your time

**Comment by toumir** [comment]
I've figured it out how to do this, add not mapping property : IsLoaded to OrderDetail, when loading an order I mark  all details as loaded, when saving I know if it newly or loaded document, is what you mean Sir.
Thanks in advance

**Comment by mbdavid** [comment]
If you want detect if an instance was loaded from database and not fill by your code, you can add a property to control this:

```
public class Order
{
    public int Id { get; set; }
    public List<OrderDetail> Details { get; set; } = new List<OrderDetail>();

    [BsonIgnore]
    public bool IsNew { get; set; }

    public static Order Create()
    {
        return new Order { IsNew = true };
    }
}
```

Now, you can just use `Order.Create()` static method to create new instances... and `IsNew` will be true. When loaded from database, this property remains `false` (BsonIgnore will mark as not serialized)

**Comment by toumir** [comment]
@mbdavid there is a misunderstanding, I apologize if I did not well explain my problem, I do not mean the Main document(Order) but the I mean subdocuments(OrderDetail), how do Know if they are loaded or newly added
thanks Sir for your time

**Comment by mbdavid** [comment]
Hi @toumir, the ideia are the same. You can just add this `IsNew` property  in OrderDetail and use a static `Create` method to create instances of OrderDetail with `IsNew = true`. When engine load List of OrderDetail, each instance will have IsNew = false because was ignored when serialize.

**Comment by toumir** [comment]
@mbdavid  yes I figure it out thank you Sir :)
