### ISSUE TITLE
How do I find the liteDB size on disk?

### ISSUE THREAD

**Issue by kudlatiger** [mbdavid/LiteDB#1081]
I observed that liteDB is maintaining it's size even after we delete the records from it. I my case, it shows 2mb even after deleting many data from it. so how do I know the actual size on disk of liteDB data?

I am using c# code but i still get the full size of the liteDB

        public static long GetFileSizeOnDisk(FileInfo file)
        {
           
            uint dummy, sectorsPerCluster, bytesPerSector;
            int result = GetDiskFreeSpaceW(file.Directory.Root.FullName, out sectorsPerCluster, out bytesPerSector, out dummy, out dummy);
            if (result == 0) throw new Win32Exception();
            uint clusterSize = sectorsPerCluster * bytesPerSector;
            uint hosize;
            uint losize = GetCompressedFileSizeW(file.FullName, out hosize);
            long size;
            size = (long)hosize << 32 | losize;
            return ((size + clusterSize - 1) / clusterSize) * clusterSize;
        }

**Comment by mbdavid** [comment]
Hi @isharehappycode, if you want reduce your filesize after a delete command, you must use Shrink method. This command will rebuild all your database, so it's not a fast command and must not use after all delete.

As expected, this empty space will be used in next insert.

**Comment by isharehappycode** [comment]
Since Shrink is not recommended, can we some how get the content and calculate actual size of the DB?

**Comment by mbdavid** [comment]
There is no direct method to calculate this in v4.  In next v5 will be possible by do a sum (free bytes) over `$dump` collection:

```SQL
SELECT ALL 
{ 
    used: SUM(usedBytes), 
    free: SUM(freeBytes), 
    total: SUM(usedBytes+freeBytes)
}
  FROM $dump
```

![image](https://user-images.githubusercontent.com/1137197/45689996-ba657800-bb2b-11e8-9a4f-50af10eb3e7d.png)

**Comment by isharehappycode** [comment]
Impressed by LiteDB Studio. Where I get this?

**Comment by mbdavid** [comment]
You can download from `v5` branch and compile in VS2017. The v5 roadmap are not closed yet, but will be release in 2018 (maybe in december....)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Comment by nightroman** [comment]
FYI The suggested method

```sql
SELECT {used: SUM(*.usedBytes), free: SUM(*.freeBytes)} FROM $dump
```

works in v5.0.3 but only for not "large" databases. Otherwise you get:

```
OrderBy/GroupBy operation are supported only in virtual collection with less than 2000 documents
```

**Comment by nightroman** [comment]
But it is still possible to sum these numbers manually without grouping.

Example, using PowerShell and [Ldbc](https://github.com/nightroman/Ldbc)

```powershell
Use-LiteDatabase $FileName {
    $usedBytes = 0
    $freeBytes = 0
    foreach($_ in Invoke-LiteCommand 'SELECT {usedBytes, freeBytes} FROM $dump') {
        $usedBytes += $_.usedBytes
        $freeBytes += $_.freeBytes
    }
    $usedBytes
    $freeBytes
}
```

**Comment by mbdavid** [comment]
Hi @nightroman, I think that can be created another $ collection to store this operations: pages free, avaiable pages in IndexPages, in DataPages, grouped by collection.... it's quite simple and will have no problem with big databases

**Comment by mbdavid** [comment]
Can be added as a suggestion issue

**Comment by nightroman** [comment]
I do not know how many users might be interested. Maybe some more feedback can tell.

I have a question about the matter thought. It looks like total usedBytes +
freeBytes is usually less then the actual file size. Is this expected, normal?
The difference is significant for large files.

Example for one db:

    used: 115345270
    free: 32014222
    file length - (used + free): 3086588 (3mb+)

**Comment by mbdavid** [comment]
I will write som "Suggestion Issues" on github for collectect 👍 to check if is a good implementation
