### ISSUE TITLE
LiteDB.LiteException While Insert New Record

### ISSUE THREAD

**Issue by antonilamo** [mbdavid/LiteDB#1082]
I want to insert data from textbox, then i got this exception
**LiteDB.LiteException: 'Index key must be less than 512 bytes.'**

`var new_data = new URLIBData
                {
                    Uid = guid,
                    enableRule = _component.enable_url_rule.Checked,
                    ruleData = _component.url_rule_data.Text,
                    linkData = _component.url_list.Text
                };
                link_data.Insert(new_data);`

How to fix this?

**Comment by mbdavid** [comment]
Hi @antonilamo, indexes key can not exceed 512 bytes. Do not create index on too long string fields

**Comment by mbdavid** [comment]
There is not limit size to just store a field. You can use any size to just store.

But, if you want create a index in this fields, this string can pass 512 bytes. This is common in all databases.

In your case, I recommend you to use an array (or `List<string>`) that each item will be index.

**Comment by antonilamo** [comment]
ok, thank you !
