### ISSUE TITLE
Push notification from asp.net web api to angular?

### ISSUE THREAD

**Issue by b-mi** [mbdavid/LiteDB#1084]
Is it possible to have push notification  after data change  in LiteDb from asp.net web api service for angular  6 application? Any sample for it?

**Comment by dlidstrom** [comment]
If real-time updates is your #1 priority, check out https://www.rethinkdb.com/. It is meant for exactly this purpose.

—
Daniel Lidström

**Comment by b-mi** [comment]
There are dozens various databases, but I need database easily embeddable to .net web api service. LitedDB need just add one dll to references od asp.net web api service. This solve easy instalation database service on site provider too. RethinkDb is from another world. Maybe have push notifications, but it is complicated for integration with asp.net web api service on site provider.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
