### ISSUE TITLE
Question: Optimistic concurrency

### ISSUE THREAD

**Issue by sajagi** [mbdavid/LiteDB#1085]
Hi, 

Is there a way to enable optimistic concurrency control? Scenario:

Process 1, Process 2:
P1: reads record from collection
P2: reads same record from collection, makes changes, updates record to LiteDB file
P1: makes changes, tries to update record in LiteDB but fails because record version changed

Thanks!

**Comment by mbdavid** [comment]
Hi @sajagi, quick anwser: in v4, there is no way to do this in atomic transaction. v4 has no support for transaction. For high concurrency read/write you will need v5 (with transaction support) and `UpdateMany` with support update with predicate.

But if you just want implement this for some user interface control (two users changing same entity), you can implement a simple int `Version` field for this and checks before update.

**Comment by sajagi** [comment]
Hi @mbdavid, thank you for quick reply! 

Using Version field wouldn't help as there still is a possibility of race condition :( I'm looking forward to v5 then!

Thanks

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
