### ISSUE TITLE
Question: Optimum database structure?

### ISSUE THREAD

**Issue by matkuki** [mbdavid/LiteDB#1086]
Hi guys,

I have a database with a single collection of the following objects:
```c#
public class StateMessage
{
        public int id { get; set; }
        public string type { get; set; }
        public DateTime time { get; set; }
        public string[] states { get; set; }
}
```
I am logging messages every couple of minutes, with messages having a different `type` and different length of the `states` (the length of `states` ranging from 30 to 1000).

Storing messages into the database works great. But after storing data for some time the database grows to a couple of 100MB in size, then querying from the database becomes very slow. I am querying using the `Repository Pattern`, like:
```c#
using(var db = new LiteRepository(my_connection_string))
{
    var result = db.Query<StateMessage>(my_table)
        .Where(x => x.type == searched_type)
        .ToArray();
    // more code ...
}
```

My question is: Is it better to split the messages into separate objects for each message type and store them in separate collections, or am I doing something wrong?

Thanks

**Comment by mbdavid** [comment]
Hi @matkuki, did you create index over this `type` field? You must do this to avoid need read all document.

When you open your database, add:

`db.EnsureIndex<StateMessage>(x => x.type)`

Also, i don't know what you will use this in-memory objects, but do not use ToArray() if you using in a paging grid... it's better use Limit/Offset before ToArray().

**Comment by matkuki** [comment]
@mbdavid Thanks, that worked!
