### ISSUE TITLE
concurrency on UWP

### ISSUE THREAD

**Issue by hanniiel** [mbdavid/LiteDB#1090]
I was trying to use LiteDB on UWP from a project created with Unity it works fine in IOS and Android but doesn't work with UWP it says System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage' I heard it was a problen related to concurrency and it was solved in a higher version but I'm using the branch for Unity so whenever I try to upgrade LiteDB there's a problem with System.Reflection.Emit is not supported.

Best regards

**Comment by mbdavid** [comment]
Hi @hanniiel, if you need run unity version you will take care about your concurrency access. If you have low concurrency just wrap you database access using `lock`. If you need write more complex solution, you can use ReaderWriterLockSlim

**Comment by hanniiel** [comment]
Thank you, I will try to do what you mention above, I'd be good to have an updated version of LDB for Unity users. Anyways, It's a great DB and very helpful, I really enjoy usign it on every project.

Best regards and keep the great work !!

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
