### ISSUE TITLE
Please add support "Seek operations" for FileStream reading and writing.

### ISSUE THREAD

**Issue by IvanKonov** [mbdavid/LiteDB#1094]
Please add support "Seek operations" for FileStream reading and writing.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Comment by nightroman** [comment]
I am second to this. At least it would be useful to know that this is possible and might be eventually expected. /cc @mbdavid

**Comment by mbdavid** [comment]
For read stream is possible.... but to write stream is not possible (or is hard to do)

**Comment by nightroman** [comment]
Even just read stream is better than none!

Think read only LiteDB databases stored as "files" in a sup LiteDB database. I do not have yet practical applications but I might have some in the future.
