### ISSUE TITLE
FindSort Can Return More Result Than It Should

### ISSUE THREAD

**Issue by ooikengsiang** [mbdavid/LiteDB#1095]
LiteDB: 4.1.4
Platform: iOS 12

FindSort seem to return more result than it should have if skip > 0.
Example if
collection.Count(Query.All()) return me 90
then I call get the following statement on LiteDB
db.Engine.FindSort("collectionName", Query.All(), "$.Date", Query.Descending, 50, 50)
it will still return me 50 results
if I continue to call the following statement on LiteDB
db.Engine.FindSort("collectionName", Query.All(), "$.Date", Query.Descending, 100, 50)
it will still return me more 50 results (I do observe some result is duplicated)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
