### ISSUE TITLE
How to retrieve strings based on length randomly

### ISSUE THREAD

**Issue by MercedeX** [mbdavid/LiteDB#1098]
Hi there, 
I used it first time in some distributed computing and my project was a success. since then whenever I get chance I use Lite DB. Recently I encountered an issue. I have to retrieve strings randomly but based on length. so it goes like this: I have this object declaration. which I store in LiteDB

    [Description("Numbers")]
    internal class DBItem<T> where T:IComparable<T>
    {
        [BsonId]
        public long Id { get; set; }
        public T Value { get; set; }
        public DateTime CreatedOn { get; set; }
    }

The actual value is stored in Value which is string, I'm using BigInteger from System.Numerics which could be 20 digits long hence using them as string. 

Now the problem is that I want to upload random strings of at least certain length. Logically I want to load like numbers with at least 13 digits and they should be picked randomly.

I looked into documentation but could not find anything. How could I do that?

**Comment by stitch10925** [comment]
I am not sure I understand what you are trying to achieve. From what I understand you are trying to do the following:

You have documents in your database which contain string values of maximum 20 digits long. You want to query these documents by string length and return from the results a random entry. Is this correct?

If so, then there are quite a few options. One of them would be to simple add an int field which contains the length of the string. You can then retrieve all entries with the correct length from that field and randomly pick one of the entries to use. If you do not want to retrieve all entries, you can run your query the first time with .Count() to find out how many results there are, and then retrieve a random entry from the database directly by using the .Find()'s skip and take overloads. For example: 

database.Find(e => e.Length == 10, 3, 1) // skip 3 entries and take 1 entry.

Do not forget to put an index on this field.

Another option would be to use Query.EQ("LENGTH($.Value)", 10) //UNTESTED
Where 10 is the desired length, to query from the database. This however does a full table scan, so performance-wise this might not be the best option.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
