### ISSUE TITLE
Changing culture breaks collection

### ISSUE THREAD

**Issue by Tviljan** [mbdavid/LiteDB#1099]
Creating db and collection in "en-gb" culture and reading it in "fi" culture makes some collection items not found.

You can test the problem from example [here](https://github.com/Tviljan/LiteDbCultureProblem)

**Comment by xied75** [comment]
Some background knowledge here for better understanding of the problem:
https://www.w3resource.com/csharp-exercises/string/csharp-string-exercise-27.php
https://www.omniglot.com/writing/finnish.htm
https://docs.microsoft.com/en-us/globalization/locale/sorting-and-string-comparison

**Comment by Tviljan** [comment]
Seems to be still an issue with v5

**Comment by Tviljan** [comment]
Here is a simple way to make the error happen

`

    using System;
    using LiteDB;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading;
    using System.Globalization;

    public class DataItem

    {

        public string Id { get; set; }
        public string Name { get; set; }
    }

    class Program
    {
        private static Random random = new Random();
        public static string GetId()
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            return new string(Enumerable.Repeat(chars, 10)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        static void Main(string[] args)
        {
            // Open database (or create if doesn't exist)

            var idList = new List<string>();





            Thread.CurrentThread.CurrentCulture = new CultureInfo("fi");

            Console.WriteLine($"Running with {Thread.CurrentThread.CurrentCulture.Name} culture");

            using (var db = new LiteDatabase(@"MyData.db"))
            {
                db.DropCollection("data");
                // Get customer collection
                var col = db.GetCollection("data");

                for (int i = 0; i < 100; i++)
                {
                    var id = GetId();
                    idList.Add(id);
                    var item = new DataItem() { Id = id, Name = "Name of {i}" };
                    var wrappedData = BsonMapper.Global.ToDocument(item);

                    col.Insert(wrappedData);
                }

            }


            Thread.CurrentThread.CurrentCulture = new CultureInfo("en-gb");

            Console.WriteLine($"Switch to { Thread.CurrentThread.CurrentCulture.Name} culture");

            var notFoundId = new List<string>();
            //Reopen
            using (var db = new LiteDatabase(@"MyData.db"))
            {
                // Get customer collection
                var col = db.GetCollection("data");

                // Use LINQ to query documents (with no index)
                foreach (var id in idList)
                {

                    var result = col.FindById(id);
                    if (result == null)
                    {
                        notFoundId.Add(id);
                    }

                }

            }

            Console.WriteLine($"Missing {notFoundId.Count} ids from {idList.Count}");
            foreach (var missingId in notFoundId)
            {
                Console.WriteLine($"MISSING ID {missingId} ");
            }


        }
    }

`

**Comment by Tviljan** [comment]
Does Find work differently than FindById? Using FindById seems to still be broken

**Comment by Tviljan** [comment]
Here is example unit test used https://gist.github.com/Tviljan/f48fea8d5f6f8800ab7884a5af5cadf7

**Comment by Tviljan** [comment]
Hi,

My test still fails using latest v5

Here is gist https://gist.github.com/Tviljan/f48fea8d5f6f8800ab7884a5af5cadf7
