### ISSUE TITLE
Why is BJSONParameters.UseExtension hard coded to false?

### ISSUE THREAD

**Issue by rischwa** [mbdavid/LiteDB#11]
My understanding is that this excludes using interface types for properties.
Is there a specific reason you hardcode it, or could it be made configurable?

**Comment by mbdavid** [comment]
There is no specific reason, just to keep simple. Using extension fastBinaryJson create _types properties that use a lot of space after serialize. Do you have some example how you want use interface?

BTW, in next version I´m removing fastBinaryJson lib and using BSON serializer + BSON mapper (my own code). If you want, take a look on dev branch and wiki (not finish yet).

**Comment by rischwa** [comment]
My use case is just ordinary OO modelling, e.g. (I know, stupid example...) I want to store a List of Shapes which contains a circle and a square.
Without support for interfaces i'd have to add an own additional mapping between my type hierarchy and e.g. a single concrete union type.
If it would be configurable (and maybe turned off by default), you don't incur any overhead, but if needed, it could be actived.
But, it's good to know that there is no other technical reason, now I can just change it myself and don't need to study the code to see, if I break something.

Thank you for this awesome lib! It looks like it is just what I need for my little project.
I will take a look at your dev branch, too. But, first I need to have something working now :).
