### ISSUE TITLE
Concrete types not serialized / deserialized

### ISSUE THREAD

**Issue by zawasp** [mbdavid/LiteDB#110]
Hello, am I missing something or I can't store derived types in a collection of base types?

For example:

```
public class Base
    {
        public int Id { get; set; }
        public Base()
        {

        }
    }

    public class Derived1 : Base
    {
        public string Member1 { get; set; }
        public Derived1()
        {

        }
    }

    public class Derived2 : Base
    {
        public string Member2 { get; set; }
        public Derived2()
        {

        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new LiteDatabase("test.db"))
            {
                var collection = db.GetCollection<Base>("Collection");
                var derived1 = new Derived1();
                var derived2 = new Derived2();
                collection.Insert(derived1);
                collection.Insert(derived2);

                var resultingCollection = db.GetCollection<Base>("Collection");
                var list = new List<Base>();
                list.AddRange(resultingCollection.FindAll());
            }
        }
    }

```

The resulting list contains 2 Base items, not 1 Derived1 and 1 Derived2.

Please help, thank you.

**Comment by mbdavid** [comment]
Hi @zawasp, Try this:

```
Base derived1 = new Derived1();
Base derived2 = new Derived2();
```

LiteDB checks if variable is the same type of object intance. If not, add `_t` field with type. In your case, variable is the same type of instance.

**Comment by zawasp** [comment]
Thanks @mbdavid , but I get the same result. See the list in locals below:
[debug](http://oi68.tinypic.com/2z6in85.jpg)

Both items in the list are Base.
I'm using LiteDB 2.0 rc, but I have the same behavior with version 1.x.

**Comment by mbdavid** [comment]
Hi @zawasp, I found the problem. Take a look on `master` branch with your example in unit tests.

**Comment by zawasp** [comment]
Thanks, @mbdavid. That fixed the issue :+1:
