### ISSUE TITLE
When insert document causes LiteException.

### ISSUE THREAD

**Issue by nathan130200** [mbdavid/LiteDB#1100]
When i try to insert document on collection cause LiteException:

LiteDB.LiteException: Invalid BSON data type 'Null' on field '_id'.
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>cDisplayClass22_0.<Insert>b0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection1.Insert(T document)
   at ForGer.Modules.DeveloperModule.CadastraTodosAsync(CommandContext ctx) in C:\Users\Nathan Ferreira\Desktop\ForGer\ForGer\Modules\DeveloperModule.cs:line 48
   at DSharpPlus.CommandsNext.Command.ExecuteAsync(CommandContext ctx)

Class:

```cs
	public class Usuario
	{
		[BsonId]
		protected ObjectId _id;

		[BsonField("user_id")]
		private string _user_id;

		[BsonIgnore]
		public ulong UserId {
			get { return ulong.Parse(_user_id); }
			set { _user_id = value.ToString(); }
		}

		[BsonField("experience")]
		public long Experience { get; set; }
	}
```

Insert method:

```cs
var user = new User();
user.UserId  = 235088799074484224;
user.Experience = 62754;

var mapper = new BsonMapper();
mapper.IncludeNonPublic = true; // accepts protected, internal and private fields.

var db = new LiteDatabase("Users.db", mapper);
var col = db.GetCollection<Usuario>();
col.Insert(user); // Causes LiteException Invalid BSON data type 'Null' on field '_id'.
```  

Same exception in this class: (Using no protected fields)

```cs
public class Usuario
{
	[BsonId]
	public ObjectId _id;

	[BsonField("user_id")]
	public ulong UserId { get; set; }

	[BsonField("experience")]
	public long Experience { get; set; }
}
```

No way to auto create an object id?

**Comment by stitch10925** [comment]
What version of LiteDB are you using? According to the documentation ObjectId is supported in v4:
[https://github.com/mbdavid/LiteDB/wiki/Object-Mapping#autoid](https://github.com/mbdavid/LiteDB/wiki/Object-Mapping#autoid)

Not sure if it was supported in previous versions

**Comment by nathan130200** [comment]
I'm using .NET Core 2.1 with latest LiteDB version.

**Comment by xied75** [comment]
quick thinking from my mind: can this _id be protected? Should it be public?
```csharp
protected ObjectId _id;
```

**Comment by lilasquared** [comment]
@nathan130200 make your _id field a property and it should work, or use the `BsonMapper.Global.IncludeFields = true` option

**Comment by nathan130200** [comment]
Fixed! Thanks for help.
