### ISSUE TITLE
Deserializing null values

### ISSUE THREAD

**Issue by superware** [mbdavid/LiteDB#1107]
Please consider the following class:

```
class MyDocument
{
	public MyDocument()
	{
		NetworkId = "MyNetwork1";
	}

	public string NetworkId { get; set; }
}
```

Where the default value is defined in the constructor (a common practice). Now, let's say I set `NetworkId` to null and use `BsonMapper.Global.ToDocument` to update the document inside the db.

The next time I fetch the document from the db, and use `BsonMapper.Global.ToObject` to deserialize, the `DeserializeObject` method will [skip](https://github.com/mbdavid/LiteDB/blob/00df88645effe031d32b9558562697ca15b4a750/LiteDB/Mapper/BsonMapper.Deserialize.cs#L249) `NetworkId` since it's null, leaving the default value which was set in the constructor but now doesn't represent the actual value stored in the document.

Please advise.

**Comment by lilasquared** [comment]
What advice are you looking for?  It looks like you know exactly why it is behaving in this way.  

here is a link to defining your own custom deserializer behavior https://github.com/mbdavid/LiteDB/wiki/Object-Mapping#register-a-custom-type

If you think this should be how the default behavior works I'm sure you are more than welcome to propose a pull request.

**Comment by superware** [comment]
Don't you think this is a deserialization bug? `{"NetworkId":null}` should set `NetworkId` property to null. 

Maybe there's something I'm missing...

**Comment by lilasquared** [comment]
im sure it is, but you can work around it with a custom deserializer, and in the meantime you can make the change to fix it :+1:

**Comment by lilasquared** [comment]
the code is explicitly ignoring null values so i would think he had a reason to do so - though i don't know what it might be

**Comment by superware** [comment]
@mbdavid can you please shed some light on this? :)

**Comment by mbdavid** [comment]
Hi guys, sorry about delay... I'm quite out in github last time...

Did you try use `BsonMapper.Global.SerializeNullValues = true` ? This will generate null value inside BsonDocument

**Comment by superware** [comment]
This seems like a deserialization bug, I don't think `BsonMapper.Global.SerializeNullValues` is related.

Please see [here](https://github.com/mbdavid/LiteDB/blob/00df88645effe031d32b9558562697ca15b4a750/LiteDB/Mapper/BsonMapper.Deserialize.cs#L249), if the document holds a null - it must reflect that in the target object.

Maybe as `null` for reference types / `Nullable<T>`, and `default(T)` for value types... skipping like the current behavior is definitely a bad idea :)

**Comment by mbdavid** [comment]
Hi @superware, ok... in this case do not load null value can cause this result. I will fix this....

**Comment by superware** [comment]
Hi @mbdavid, I believe this is a pretty critical issue affecting integrity between serialized-deserialized documents. Is it on your roadmap? how may I help?

**Comment by mbdavid** [comment]
Hi @superware, I was super-busy last 2 months with new v5 engine.

I think this problem can be resolved removing this IF statment, but need more test about `ValueTypes`. Do you want help fix this? A PR about this will be great!

**Comment by superware** [comment]
How about:

```
private void DeserializeObject(Type type, object obj, BsonDocument value)
{
    var entity = this.GetEntityMapper(type);

    foreach (var member in entity.Members.Where(x => x.Setter != null))
    {
        var val = value[member.FieldName];
        var dataType = member.DataType;
        object deserialized;

        if (!val.IsNull)
        {
            // check if has a custom deserialize function
            if (member.Deserialize != null)
            {
                deserialized = member.Deserialize(val, this);
            }
            else
            {
                deserialized = this.Deserialize(dataType, val);
            }
        }
        else
        {
            if (!dataType.IsValueType || (dataType.IsGenericType && dataType.GetGenericTypeDefinition() == typeof(Nullable<>)))
            {
                deserialized = null;
            }
            else
            {
                deserialized = Activator.CreateInstance(member.DataType);
            }
        }

        member.Setter(obj, deserialized);
    }
}
```

1. Not using `Nullable.GetUnderlyingType`, reason [here](https://stackoverflow.com/a/8939958/1549486).
2. Couldn't be absolutely sure whether to set value-types as their default or not. Leaving a member as-is will only happen if that member doesn't exist in the BsonDocument, which might be a good reason to have the suggested behavior.

**Comment by superware** [comment]
Hi @mbdavid, what do you say about incorporating this fix in the next minor release?

**Comment by mbdavid** [comment]
Hi @superware, I will... I have some small fixes to make in current version so I will add this too.

**Comment by superware** [comment]
Hi @mbdavid, why not incorporating the suggested fix?

**Comment by superware** [comment]
@mbdavid ? :)
