### ISSUE TITLE
Serialize exception caused by insert operation

### ISSUE THREAD

**Issue by lidanger** [mbdavid/LiteDB#111]
exception caused by insert operation.
The type to be serialized is System.Net.IPEndPoint.
The version of LiteDB is 1.0.4 fetched by nuget, and the framework is 4.0(v4.0.30319).

Exception Message:

参考的对象类型不支持尝试的操作(Reference object type does not support the operation to try)。

Part of Stack Trace:

  在 System.Net.IPAddress.get_ScopeId()
   在 _(Object )
   在 LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
   在 LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   在 LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
   在 LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   在 LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
   在 LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   在 LiteDB.BsonMapper.SerializeArray(Type type, IEnumerable array, Int32 depth)
   在 LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   在 LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)
   在 LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)
   在 LiteDB.BsonMapper.ToDocument(Object entity)
   在 LiteDB.LiteCollection`1.Insert(T document)

**Comment by mbdavid** [comment]
Hi @lidanger, for serialize this type, you need create a custom serialization funcion. Take a look on this example for `Uri` class

```
Mapper.Global.RegisterType<Uri>
(
    serialize: (uri) => uri.AbsoluteUri,
    deserialize: (bson) => new Uri(bson.AsString)
);
```

**Comment by lidanger** [comment]
That's good,thank you.
