### ISSUE TITLE
Question: how to specify thread-safe concurrency

### ISSUE THREAD

**Issue by djarvis** [mbdavid/LiteDB#1110]
Hi.

The documentation didn't indicate how to specify to LiteDb to use thread-safe concurrency versus process-safe concurrency.  Do I not have to set anything or did I miss something?

Thanks!

**Comment by ooikengsiang** [comment]
> You can share a single LiteRepository, LiteDatabase or LiteEngine instance across your threads (thread-safe)
Use a share instance, the library will handle all the concurrency lock for you.

There are nothing to configure as I know, just you either let the library handle it for you, or you choose to handle yourself.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
