### ISSUE TITLE
QUESTION: timeout connections string value

### ISSUE THREAD

**Issue by janantos** [mbdavid/LiteDB#1111]
HI, thanks for great job in first place.
can you please clarify what is the granularity and max value of timeout setting in connection string.
have tried Timeout=120 (assuming seconds) and I am receiving out of boundary error.

I need to set higher value, while I am using LiteDB for multi million (20M+) document storage.

thanks Jan

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
