### ISSUE TITLE
a bug with  field order

### ISSUE THREAD

**Issue by Lovecxgood** [mbdavid/LiteDB#1112]
Hi~ I found a sort bug in using this project version 4.0
when I use Query.All("_id",1) or Query.All("_id",-1) it works
but when order by other field that I custom defined it is not work as  my expected
just like Query.All("myField",1) or Query.All("myField",-1)  no effect~
could you have fixed this  bug in the latest version?
Thank you!

**Comment by mbdavid** [comment]
Did you have any index in this "MyField" field? In v4 this Query order works only for indexed fields.

**Comment by Lovecxgood** [comment]
Got it,  I will try it later , thank you
