### ISSUE TITLE
why litedb has no batch delete method

### ISSUE THREAD

**Issue by Lovecxgood** [mbdavid/LiteDB#1113]
why litedb dont provide a batch delete method,just like  
public int Delete(string collection, BsonArray ids);

**Comment by mbdavid** [comment]
Hi @Lovecxgood, yes, there is no ids avaiable in v4 for delete. You can only use Query object for this. This was implemented in v5 only

**Comment by Lovecxgood** [comment]
Ok thank you and when are going to publish the  V5 version?

**Comment by mbdavid** [comment]
Hi @Lovecxgood, there is date yet. My plan was final of 2018, but I still have lot of works to this version work like I expects... so, maybe for 2019Q1

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
