### ISSUE TITLE
LiteDB.LiteException: 'Cannot insert duplicate key in unique index '_id'

### ISSUE THREAD

**Issue by JohnnyDeeee** [mbdavid/LiteDB#1117]
How come that i get a `LiteDB.LiteException: 'Cannot insert duplicate key in unique index '_id'. The duplicate value is '0'.'` with the following code?

It looks like the AutoId doesn't work in this scenario, or am i missing something?

```c#
    public class Test {
        public int id { get; set; }
        public string text { get; set; }
    }

    static class Program
    {
        static void Main()
        {
            using (var db = new LiteDatabase("database.db")) {
                LiteCollection<object> collection = db.GetCollection<object>("testCollection");

                collection.Insert(new Test { text = "aaa" });
                collection.Insert(new Test { text = "bbb" });
            }
        }
    }
```

**Comment by lilasquared** [comment]
@JohnnyDeeee why are you using `db.GetCollection<object>()`? that will have no way of knowing which fields you have, since the typeof(T) is how litedb is able to determine appropriate fields.

Use `db.GetCollection<Test>()` and it will work

**Comment by JohnnyDeeee** [comment]
@lilasquared This is part from a bigger piece of code that can insert/retrieve any sort of Type (i call them records), so it needs to be dynamic

**Comment by lilasquared** [comment]
An you use generics? You need to be able to specify and id property, otherwise you might need to use the lower level BsonDocument for all of your “records”

**Comment by JohnnyDeeee** [comment]
As you can see in the example, i have provided an ID property.

Imagine having `Test` and `Test2`, they can both be given to the function as a parameter.

The problem is the ID doesn't get set for any of them..

**Comment by lilasquared** [comment]
Yes your types have an ID property but object does not. LiteDb uses the type given to the getcollection function to know what properties should be used. In your case you have passed object. As I said look into use generics or the dynamic keyword for this

**Comment by JohnnyDeeee** [comment]
Ah yes ofcourse, that makes sense..
I have been using the object type as a generic 😅.

Thanks !

**Comment by lilasquared** [comment]
Happy to help!
