### ISSUE TITLE
asp.net core mvc service drains memory 

### ISSUE THREAD

**Issue by autiarii** [mbdavid/LiteDB#1121]
I have implemented the simple crud service based on unit of work pattern and asp.core mvc (.net core 2.1), yet I ran into inadequate memory usage that increases with database size. When my database is around 20mb, giving server a load makes it consume around 1gb of ram. I have tried several implementations but I always end up with almost the same results. [Here I have made the  little sample project](https://github.com/autiarii/litedbtestweb)

![memoryusage](https://user-images.githubusercontent.com/14825915/48344153-566fb380-e685-11e8-95ac-5b6dca044a6b.png)
)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
