### ISSUE TITLE
How to resolve reference within nested document?

### ISSUE THREAD

**Issue by wilberolive** [mbdavid/LiteDB#1122]
I have some classes like this.

```
Public Class Category
    Public Property Id As Integer
    Public Property Name As String
    Public Property Groups As List(Of Group)
End Class

Public Class Group
    Public Property Id As Integer
    Public Property Name As String
    Public Property Items As List(Of Item)
    <LiteDB.BsonRef("Category")>
    Public Property Parent as Category
End Class

Public Class Item
    Public Property Id As Integer
    Public Property Name As String
    <LiteDB.BsonRef("Group")>
    Public Property Parent as Group
End Class
```

Then I have a list of categories, which I'm storing in the database as a collection, like this.

```
Dim Categories As New List(Of Category)
Repository.Insert(Of Category)(Categories, "Category")
```

I only have the one collection. I don't have a separate collection of the groups and items due to the way the application is designed and how it works. The groups need to be nested in the categories and the items in the groups.

The problem is, when I load the collection back from the database, like this, the Parent references in the Group and Item classes are empty.

`Repository.Database.GetCollection(Of Category)("Category").FindAll.ToList`

Is there a way to restore these references when loading the collection? What about the Group reference inside the Item class, as it is referencing an object nested in an array inside a Category object of the collection?

I'm guessing I probably need to do something like this, but I can't get the syntax right. The compiler always just complains that Include resolution failed with these arguments, and I don't know how to resolve the reference to the Item Parent.

`Repository.Database.GetCollection(Of Category)("Category").Include(Function(C) C.Groups.ForEach(Function(G) G.Category = C)).FindAll.ToList`

However I notice when I inspect the database in an external tool, it shows the Parent reference to Category in the Group object for example, however the ref id is always 0. So maybe I’m not storing it correctly?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
