### ISSUE TITLE
The link in the title of the project main page without https seems broken

### ISSUE THREAD

**Issue by davidsmithgf** [mbdavid/LiteDB#1123]
Hello, Is there anyone responsible to maintain the main page?

The link in the title of the project main page without https seems broken.
www.litedb.org links to http://www.litedb.org.
It seems not available unless using: **https://**www.litedb.org.

**Comment by neilsb** [comment]
Seems fine for me at the moment....

**Comment by JensSchadron** [comment]
@davidsmithgf While it worked without the "https://" on our end, we still did add it hoping it would resolve your issue.
