### ISSUE TITLE
How to represent dictionary as array of key/value pair

### ISSUE THREAD

**Issue by amir734jj** [mbdavid/LiteDB#1125]
I am trying to store a dictionary in LiteDB and the keys of the dictionary are complex data types. In MongoDB we have an option to use `ArrayOfDocuments` enum (i.e. `[BsonDictionaryOptions(DictionaryRepresentation.ArrayOfDocuments)]`). I am wondering does LiteDB support a similar feature?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
