### ISSUE TITLE
How to find the max _id or most recently updated object in collection

### ISSUE THREAD

**Issue by chucksullivancvs** [mbdavid/LiteDB#1128]
_**_**How to find the max _id or most recently updated object in collection?**_**_

I'm kind of new to LiteDB.

Got most things working. I can create a POCO, make a db connection and do a collection.Insert().

Now I need to get the most recently added record so I can pull a value  from it and increment it in a pattern.

I am struggling with using Queries and Expressions to find the MAX _id item in the collection.

Seems like this should be a pretty common problem but I can't find any examples.

Can someone help?

**Comment by nh43de** [comment]
I just had this problem yesterday

`var latest = Coll.FindOne(Query.All(1));`

where coll is your LiteDbCollection

let me know if that works for you

**Comment by mbdavid** [comment]
Hi guys,

First, your poco class will be updated with _id inserted.

Also, Insert method returns this number.

But, as @nh43de say, you can get lower (or highest) value in a index using this command:

`var latest = Coll.FindOne(Query.All(Query.Asc));`

**Comment by chucksullivancvs** [comment]
Hey Thanks!

I'm not used to people replying so quick and with such good options.

Both of these work:

var latest = collection.FindOne(Query.All(-1));
var latest = collection.FindOne(Query.All(Query.Descending));

Makes sense if you think of it as an object store and index rather than a database where you expect a simple MAX(col) function.

**Comment by nh43de** [comment]
Awesome! Glad it worked for you. Also @mbdavid - this is one of the coolest libraries I have come accross in several years. Thank you thank you for you hard work! This library is an amazing alternative to using a MongoDb backend for lightweight applications in .NET

**Comment by chucksullivancvs** [comment]
Agree Totally!

I've been using it now for just over a day and have already built an application using it. Great alternative to client-server SQL or NoSQL databases for some applications (like mine - a low use Windows Form application with just local storage needs).

**Comment by mbdavid** [comment]
Thanks guys! It's really nice to know about this. I'm still working v5 version that will the a biggest change in this project. In this case, you will resolve this using a single SQL query (or Linq query) like:

`SELECT MAX(_id) FROM your_col`
or
`col.Query().Max(x => x.Id)`

**Comment by MinChanSike** [comment]
As I see in `LiteCollection.cs`,

`// Summary:`
        `//     Insert a new entity to this collection. Document Id must be a new value in collection`
       ` //     - Returns document Id`
       ` public BsonValue Insert(T document);`
```
int recentId = -1;
var docId = coll.Insert(info);
if (docId != null) recentId = docId .AsInt32;
```
@chucksullivancvs  it's working for me.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Comment by Gavenatore** [comment]
Sorry for reopening this post, but it is my first time using LiteDB

var iLatestID = MainDB_Coll.FindOne(Query.All("iID", 1));
            if (iLatestID == null)
            {
                MessageBox.Show("NULL");
                DatabaseTemplate.iID = 1;
            }
            else
            {
                MessageBox.Show(int.Parse(iLatestID.ToString()).ToString());   //PROBLEM
                DatabaseTemplate.iID = int.Parse(iLatestID.ToString()) + 1;
            }

Seems like int.Parse(iLatestID.ToString()).ToString() returns a false string...
Why?

**Comment by Gavenatore** [comment]
Sorry for reopening this post, but it is my first time using LiteDB
`var iLatestID = MainDB_Coll.FindOne(Query.All("iID", 1));`
`if (iLatestID == null)`
`{`
`MessageBox.Show("NULL");`
`DatabaseTemplate.iID = 1;`
`}`
`else`
`{`
`MessageBox.Show(int.Parse(iLatestID.ToString()).ToString()); //PROBLEM`
`DatabaseTemplate.iID = int.Parse(iLatestID.ToString()) + 1;`
`}`

Seems like `int.Parse(iLatestID.ToString()).ToString()` returns a false string...
