### ISSUE TITLE
Documentation: "Id" is a property, not a field.

### ISSUE THREAD

**Issue by padillah** [mbdavid/LiteDB#1129]
All the references I find refer to the Id field (and, sometimes, the _id field), and none mention the type.

After testing I have discovered that auto-generate does not use a field, but a property and the data type should be int. The documentation needs to be updated. These phrases mean something in C# and this is terribly misleading.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
