### ISSUE TITLE
[Question] LiteCollection<T> return type parameter.

### ISSUE THREAD

**Issue by nicktheone** [mbdavid/LiteDB#1130]
I have a method that I use to return a collection as follows:

`public static LiteCollection<Item> GetItems()
        {
            return ConnectToDB().GetCollection<Item>("items");
        }`

Item is a simple strongly typed class and items is the name of the table. What I'd like to be able to do is to make this method a generic one, something I don't need to know beforehand the return type to assign it to the LiteCollection<T>. Ideally what I'd like to do would look like this:

`public static LiteCollection<T> Get(string tableName)
        {
            return ConnectToDB().GetCollection<T>(tableName);
        }`

Unfortunately, though, it won't let me have it because it says T isn't recognized as a parameter. Am I doing something wrong here or I'm asking for something impossible?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
