### ISSUE TITLE
LiteDB causing Visual Studio 2017 Designer view to bug out

### ISSUE THREAD

**Issue by stigzler** [mbdavid/LiteDB#1133]
Hi,
Firstly - love the project. However, recently, I'm getting an error in one of my froms' designer views (the type where you can't actually see the form design). It appears to have soemthing to do with LiteDB:

```
To prevent possible data loss before loading the designer, the following errors must be resolved:   
   
   Value cannot be null. Parameter name: connectionString     
 
 
Instances of this error (1)  
 
1.   Hide Call Stack 
 
at LiteDB.ConnectionString..ctor(String connectionString)
at LiteDB.LiteDatabase..ctor(String connectionString, BsonMapper mapper, Logger log)
at GameInfoz.db..ctor(String file) in C:\Users\Steve\Documents\Visual Studio 2017\Projects\GameInfoz\GameInfoz\Data\db\db.vb:line 48
at GameInfoz.Main..ctor() in C:\Users\Steve\Documents\Visual Studio 2017\Projects\GameInfoz\GameInfoz\Forms\Main.vb:line 11 
```

the db.vb..line48 is just a connector class:

  ```
  Public Sub New(file As String)

        _dbConnection = New LiteDatabase(file)

        _dbfile = file

        _collections.DatabaseConnection = _dbConnection

        _collections.PopulateCollections()

        _queries.Collection = _collections

    End Sub
```
Weird thing is the app compiles and executes fine. The problem is that I can no longer edit my form :(

Hope you can help.

**Comment by a44281071** [comment]
please use design time.
···csharp
 var descriptor = DependencyPropertyDescriptor.FromProperty(DesignerProperties.IsInDesignModeProperty, typeof(FrameworkElement));
inDesignMode = (bool)descriptor.Metadata.DefaultValue;
···
code from caliburn.micro project.

**Comment by stigzler** [comment]
Just an update - nothing to do with LiteDB - shonky VS install. All better since re-installing.
