### ISSUE TITLE
Selecting a range of dates using Query

### ISSUE THREAD

**Issue by chucksullivancvs** [mbdavid/LiteDB#1134]
Hi.

I was  struggling a bit with selecting items from a collection based on date ranges (from,to) and here's what I came up with. If there is a better approach I'd like to know, but in the meantime this seems to work Ok if you are also struggling with this problem.

I have collection with a property called CreateDate and I want to do a from-to query on it. To assist I added a second property called CreateTick and set it to CreateDate.Ticks so it stores the serial long number representation of the date.

Then in my Get method where I call Find I can compare the CreateTick to other tick values representing to and from date ticks from datetimes passed into the method..

Looks something like this and it works!

 public static IEnumerable<Request> GetByDateRange(DateTime from, DateTime to)
        {
            try
            {
                // set from to short 12am, to to short 12pm and convert to ticks
                DateTime fromDate = Convert.ToDateTime(from.ToShortDateString());
                DateTime toDate = Convert.ToDateTime(to.AddDays(1).ToShortDateString());
                long fromTicks = fromDate.Ticks;
                long toTicks = toDate.Ticks;

                using (var db = new LiteDatabase(@DBConnection))
                {
                    var requests = db.GetCollection<Request>("Request");
                    var results = requests.Find(Query.Between("CreateTick", fromTicks, toTicks));
                    return results;

                }

            }

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
