### ISSUE TITLE
Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.CollectionPage'

### ISSUE THREAD

**Issue by josephcenk** [mbdavid/LiteDB#1135]
LiteDb is corrupted and throws exception on FindAll. Please advise corruption reason and way to fix it

    `public List<T> FindAll<T>() where T: class {
            try {
                lock(_readLock) {
                    using(var liteDb = new LiteDatabase(_readConnectionString)) {
                        if(collectionExist<T>(liteDb)) { return null; }

                        LiteCollection<T> collection = liteDb.GetCollection<T>(typeof(T).Name);
                        return collection?.FindAll()?.ToList();
                    }
                }
            }
            catch(Exception ex) {
                exceptionRequireRecreateDb(ex,nameof(FindAll));
            }
            return null;
        }`

    `10:41:29.874   [LiteHelper][6] FindAll throws some Exception

    10:41:29.931   [LiteHelper][6] . Exception occured: Unable to cast object of type 'LiteDB.EmptyPage' to 
    type 'LiteDB.CollectionPage'. Callstack -> <RequireImportAsync>d__147.Void MoveNext()(..)-> 
    LiteHelper.System.Collections.Generic.List1[T] FindAll[T]()(..)-> LiteHelper.Void 
    exceptionRequireRecreateDb(System.Exception, System.String)(..)-> Logs.Void Exc(System.Exception, 
    System.String)(..)-> Logs.Void Exc(System.String)(..). 

    10:41:29.931   [LiteHelper][6] Recreating Db due to ErrorCode: Unable to cast object of type 
    'LiteDB.EmptyPage' to type 'LiteDB.CollectionPage'.`

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
