### ISSUE TITLE
Preserve auto increment

### ISSUE THREAD

**Issue by Gecko8401** [mbdavid/LiteDB#1136]
Hello, 

I took a little experience on LiteDB yet and quiet happy so far. But I encounter one issue.
I'd like to use the auto id (primary key) as permanent key.
The problem I encounter is, the Id property of my entities ist set correctly when I persist my POCOs, 
but when I load them on next application start, all ids are 0. So they not seem to be persisted, am  I right?
Or just using it in a wrong way?

My persistance class looks like that : 
`using LiteDB;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WTHAMembers.Data;
using WTHAMembers.Enumeration;

namespace WTHAMembers.Persistence
{
    public class DataPersistence
    {
        public MemoryStream DatabaseStream { get; private set; }
        private BsonMapper mapper;

        public DataPersistence(MemoryStream databaseStream)
        {
            mapper = BsonMapper.Global;
            mapper.Entity<PersonData>().Id(x => x.Id);
            mapper.Entity<EmailHistoryData>().Id(x => x.Id);
            mapper.Entity<AttachmentData>().Id(x => x.Id);

            DatabaseStream = databaseStream;
        }

        public void Persist<T>(T item)
        {
            using (var db = new LiteDatabase(DatabaseStream, mapper))
            {
                Type itemType = typeof(T);
                var items = db.GetCollection<T>(itemType.Name);                
                items.Insert(item);
            }
        }

        public IEnumerable<T> Load<T>()
        {
            using (var db = new LiteDatabase(DatabaseStream, mapper))
            {
                Type itemType = typeof(T);
                var items = db.GetCollection<T>(itemType.Name);
                return items.FindAll();
            }
        }

        public void Remove<T>(int id)
        {
            using (var db = new LiteDatabase(DatabaseStream, mapper))
            {
                Type itemType = typeof(T);
                var members = db.GetCollection<T>(itemType.Name);
                members.Delete(id);
            }            
        }

        public void UpdateMember<T>(T item)
        {
            if (item == null)
                return;

            using (var db = new LiteDatabase(DatabaseStream, mapper))
            {
                Type itemType = typeof(T);
                var items = db.GetCollection<T>(itemType.Name);
                items.Update(item);
            }
        }
    }
}`

Any help welcome! 

Thanks in advanced.

Best,
Gregor

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
