### ISSUE TITLE
Converting ints to longs

### ISSUE THREAD

**Issue by KevinDJones** [mbdavid/LiteDB#1138]
I have a situation where I would like to change a field from int to long. In .NET, that's not a problem. An int can be assigned to a long no problem. However, in LiteDb, it throws an invalid cast exception. This is an issue as I have clients that have an object with an `int` saved. Is there anyway I can switch this to a long and still have it be read?

Example:

```
   public class MyThing
    {
        public int MyNumber { get; set; }
    }
...
    Database = new LiteDatabase(localDbConnectionString);
    TestCollection = Database.GetCollection<MyThing>("things");
    var myThing = new MyThing();
    myThing.MyNumber = 55;
    TestCollection.Insert(myThing);
    var things = TestCollection.FindAll();
```

That all works fine. However, if I switch `MyThing` to a long:

```
   public class MyThing
    {
        public long MyNumber { get; set; }
    }
```

And then run `TestCollection.FindAll()`, I get `Specified cast is not valid.'`. Anyway around that?

**Comment by KevinDJones** [comment]
Feel free to close the issue if there are any other workarounds other than converting each and every int to long like shown here https://github.com/mbdavid/LiteDB/issues/524#issuecomment-285698172

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
