### ISSUE TITLE
Database locked for 1 minute - using LiteDB on a web app hosted in IIS

### ISSUE THREAD

**Issue by alonso01** [mbdavid/LiteDB#1142]
I have developed a web app using litedb, due to the ease of use it provides. I started to use and initially was all ok. But when I deployed the app to live use at the production IIS on multiple clients premises, then I started to notice very odd problems. First of all, a simple insert was taking usually 30+ secs normally, seeing the insert attempts on the logs, I could see some normal insert times (+-1 sec), then next transactions take a lot of time (30-60 secs), then it normalizes again, then it takes a lot of time. Then, I get the database locked for 1 min error.

Initially, the DB file was being accessed disconnected, with Shared access, by the web app and by a other process that gets invoked several times (once or twice a minute) and performs a single insert.

Due to the database locked error, I switched the usage pattern to Exclusive Mode, and created in the web  app a single instance, thread safe, to access litedb, i am now working connected to the db file when the app is started. Also, made sure the other process that gets invoked several times (once or twice a minute) and performs a single insert, accessed the web app to perform the operation needed to avoid directly accessing the .db file. Thing is that, still I am encountering the database locked issue problem. So, I am not sure at all what is the usage pattern that is needed for litedb to work ok for web apps on IIS.

If anyone can clarify me this problem, I'd appreciate it. I did all my homework, reading the wiki, other issues, search at google and SO, without being sure what's the cause of this problem. I am using LiteDB 4.1.4 and .NET Framework 4.7.

Class I use know for thread safe access:
``
` public class LiteDBSingletonThreadSafe
    {

        public LiteDatabase db;
        public string connectionString = ConfigurationManager.ConnectionStrings["LiteDB"].ConnectionString;

        LiteDBSingletonThreadSafe()
        {
            db = new LiteDatabase(connectionString);
        }
        
        private static LiteDBSingletonThreadSafe instance = null;
        private static readonly object padlock = new object();

        public static LiteDBSingletonThreadSafe Instance
        {
            get
            {

                lock (padlock)
                {

                    if(instance == null)
                    {
                        instance = new LiteDBSingletonThreadSafe();
                    }
                    return instance;

                }
            }
        }

        public void Kill()
        {
            lock (padlock)
            {
                if(db != null)
                {
                    db.Dispose();
                }
                instance = null;
            }
        }
    }`

Insert operation that gets executed multiple times:

`            
            var tx = new Transaccion
            {
                Consecutivo = consecutivo,
                ClaveNumerica = claveNumerica,
                MensajeErrorRecibido = msjError,
                MontoFacturado = monto,
                Integrador = integrador,
                FechaEnvio = fechaEnvio,
                RecibidoCorrectamentePorFacturador = enviadoFacturador,
                RecibidoCorrectamentePorHacienda = enviadoHacienda,
                TipoTransaccion = tipoTransaccion,
                IdCliente = idCliente,
                XmlRespuesta = xmlRespuesta,
                Impreso = impreso,
                NombreCliente = nombreCliente,
                EmailCliente = correoCliente,
                TelefonoCliente = telCliente,
                NumeroTerminal = int.Parse(numeroTerminal),
                Observaciones = observaciones
            };

            var txDb = LiteDBSingletonThreadSafe.Instance.db.GetCollection<Transaccion>("transacciones");

            var result = txDb.Insert(tx);

            return result.AsInt32 > 0;
`

Model Class:

` 
public class Transaccion
    {

        public int _id { get; set; }
        public DateTime FechaEnvio { get; set; }

        public string MensajeErrorRecibido { get; set; }

        public bool RecibidoCorrectamentePorFacturador { get; set; }

        public bool RecibidoCorrectamentePorHacienda { get; set; }

        public bool FacturaEnviadaACliente { get; set; }

        public DateTime? FechaUltimoEnvioFacturaCliente { get; set; }

        public decimal MontoFacturado { get; set; }

        public decimal MontoDescuento { get; set; }

        public string ClaveNumerica  { get; set; }

        public string Consecutivo { get; set; }

        public string Integrador { get; set; }

        public int TipoTransaccion { get; set; }

        public int TipoPago { get; set; }
        
        public int? IdCliente { get; set; }

        public string XmlRespuesta { get; set; }

        public bool Impreso { get; set; }

        public string NombreCliente { get; set; }

        public string TelefonoCliente { get; set; }

        public string EmailCliente { get; set; }

        public int NumeroTerminal { get; set; }

        public string Observaciones { get; set; }

        public string IdInternoPago { get; set; }
    }
`

Connection string:

` <add name="LiteDB" connectionString="Filename=C:\FE-CRI\fecridb-testing.db;journal=false;Mode=Exclusive;" />`

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
