### ISSUE TITLE
Question about EnsureIndex

### ISSUE THREAD

**Issue by aelassas** [mbdavid/LiteDB#1145]
Hi,
Should we call EnsureIndex before insert or after insert or is it the same?
Regards,

**Comment by ooikengsiang** [comment]
Is best to call it once when you connect to the LiteDB, it doesn't need to be call it every single time when you perform write.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
