### ISSUE TITLE
Auto ID not working for int Id

### ISSUE THREAD

**Issue by johnkslg** [mbdavid/LiteDB#1149]
From what I could gather, the Id field should auto-increment upon insertion if set to zero. However it generates an exception for me when I try that:
![image](https://user-images.githubusercontent.com/3536496/50107437-94617980-01e7-11e9-9064-6a8e0be7049b.png)
![image](https://user-images.githubusercontent.com/3536496/50107442-97f50080-01e7-11e9-977d-eefd8aed4b06.png)

On the second insertion, I get "LiteDB.LiteException: 'Cannot insert duplicate key in unique index '_id'. The duplicate value is '0'.'"

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
