### ISSUE TITLE
An exception occured on windows 2003

### ISSUE THREAD

**Issue by lidanger** [mbdavid/LiteDB#115]
I have a program using litedb(1.04 nuget).It runs well on windows 10 x64 with .net framework 4,but when I copy the program to another machine running windows 2003 with .net framework 4 client profile and extended,it gives an exception.

Part of the StackTrace:

System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 LiteDB.IndexNode.IsHeadTail(CollectionIndex index)
   在 LiteDB.IndexService.<FindAll>d__2.MoveNext()
   在 LiteDB.LiteCollection`1.EnsureIndex(String field, IndexOptions options)
   在 LiteDB.LiteCollection`1.EnsureIndex(String field, Boolean unique)
   在 LiteDB.Query.Run[T](LiteCollection`1 collection)
   在 LiteDB.LiteCollection`1.<Find>d__9.MoveNext()
   在 System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   在 Core.Service.HJT212Service.CheckUnSend()

Code snippet:

    List<Helper.DataSegmt> segs = new List<Helper.DataSegmt>();
    using (var ldb = new LiteDB.LiteDatabase(Sys.DB))
    {
          var col = ldb.GetCollection<Helper.DataSegmt>("packs");
          var items = col.Find(item => item.MN == MN);
          if (items == null || !items.Any())     // exception occures here
              return 0;

          segs.AddRange(items);
    }

Please give me some help.

**Comment by lidanger** [comment]
A simple test runs the same result.

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    namespace Test
    {
        public class Child
        {
            public string ID { get; set; }
            public string Name { get; set; }
            public int Age { get; set; }
        }

        class Program
        {
            static void Main(string[] args)
            {
                AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;

                using (var ldb = new LiteDB.LiteDatabase("test.db"))
                {
                    var col = ldb.GetCollection<Child>("test");

                    for (int i = 0; i < 10; i++)
                    {
                        col.Insert(new Child
                        {
                            ID = Guid.NewGuid().ToString("N"),
                            Name = "test" + i.ToString(),
                            Age = i
                        });
                    }
                }

                List<Child> segs = new List<Child>();
                using (var ldb = new LiteDB.LiteDatabase("test.db"))
                {
                    var col = ldb.GetCollection<Child>("test");
                    var items = col.Find(item => item.Name.Contains("test"));
                    if (items == null || !items.Any())
                        return;

                    segs.AddRange(items);
                }

                foreach (var seg in segs)
                {
                    Console.WriteLine("{0}\t{1}\t{2}", seg.ID, seg.Name, seg.Age);
                }

                Console.ReadLine();
            }

            private static void CurrentDomain_UnhandledException(object sender, 
                UnhandledExceptionEventArgs e)
            {
                System.IO.File.WriteAllText("testexp.log", string.Format("{0}", e.ExceptionObject));
            }
        }
    }

**Comment by mbdavid** [comment]
Hi @lidanger, your error is similar (or the same) as #44 - Error in Windows XP. Can be a problem when using .NET framework profile? Can you test with full .NET? Did you test with v2?

**Comment by lidanger** [comment]
Hi @mbdavid, as you say, I downloaded the code 1.04, with little modify I compiled it to the target framework .NET 3.5 and refer it to the test program.
It runs well on the Windows 2003 with full .NET 3.5 sp1.
Another thing is, when I refered the dll compiled to the target framework .NET 4.0 client profile, nothing abnormal happened too.
Maybe the only problem is the framework compatibility.
