### ISSUE TITLE
Update http://www.litedb.org/ website

### ISSUE THREAD

**Issue by MiroslavMikus** [mbdavid/LiteDB#1150]
Hi, 
the [website](http://www.litedb.org/) is outdated.

![image](https://user-images.githubusercontent.com/29312172/50182206-0385bd80-030f-11e9-9501-66f28c4cc802.png)

In the latest version is this method called `FileStorage`.

Thank you :)

**Comment by JensSchadron** [comment]
At the moment of writing, preparations are being done to update the website for the upcoming v5 of LiteDB. The beta will be released shortly.
