### ISSUE TITLE
Descending sort of documents

### ISSUE THREAD

**Issue by toumir** [mbdavid/LiteDB#1151]
Hi,
simple question,
I'm using pagination(skip, limit) to show data in a list :
how to sort data by **id/_id** by default in **Descending** order instead of Ascending order? 
Thank you in advance

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
