### ISSUE TITLE
Loop on upsert operation

### ISSUE THREAD

**Issue by Dannnil** [mbdavid/LiteDB#1153]
Hello everybody. Sorry, my English is not so good.
When I perform an upsert(or insert) operation the program loops on this line: https://github.com/mbdavid/LiteDB/blob/0864d8f888af427571487b84652567c1fd78d97f/LiteDB/Engine/Services/PageService.cs#L230
'free' variable is always less than next.FreeBytes

Code:

public class StatisticsItem
{
        public int Id { get; set; }
        public string AccountId { get; set; }
        public DateTime Date { get; set; }
        public int? Followers { get; set; }
        public int Followings { get; set; }
        [BsonIgnore]
        public int? FollowersIncrease { get; set; }
        public int Follows { get; set; }
        public int Likes { get; set; }
        public int UnFollows { get; set; }
        public int DirectSends { get; set; }
        public int Comments { get; set; }
        public int Publications { get; set; }
}

var item = new StatisticsItem();
item.AccountId = "4565346434";
item.Date = DateTime.Now;
item.Followers = 32;
item.Followings = 324;
item.Publications = 32;
Collection.Insert(item);

But, if remove line 'item.Followers = 32' - will be inserted successfully

Database file [Main_statistics.zip](https://github.com/mbdavid/LiteDB/files/2699893/Main_statistics.zip)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
