### ISSUE TITLE
CDC/Auditing?

### ISSUE THREAD

**Issue by weitzhandler** [mbdavid/LiteDB#1155]
Hi,

Does LiteDB provide a [CDC](https://en.wikipedia.org/wiki/Change_data_capture) mechanism like SQL Server?  
I'm building a community driven website where I want most of the data to be editable by the users I need to keep a record of everything that was changed, so I can then revert/rollback to older versions.

Thanks!

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
