### ISSUE TITLE
BsonField cannot use . in the name

### ISSUE THREAD

**Issue by maxhamulyak** [mbdavid/LiteDB#1156]
I have the following POCO.
```cs
 public class Document
 {
    [BsonField("System.Id")]
    public int Id { get;set; }

    [BsonField("System.Created")]
    public DateTime Created { get;set; }
}
```

In case of Id, the name gets ignored completely (and will be _id). In case of Created I will get the following exception. Which is confusing since JSON it self does not have any restrictions on the key. In my application I have the notion of namespaces for fields. Some fields are system generated and will be in the system namespace.

```
Unhandled Exception: LiteDB.LiteException: Invalid format: Created
   at LiteDB.BsonMapper.BuildEntityMapper(Type type)
   at LiteDB.BsonMapper.GetEntityMapper(Type type)
   at LiteDB.LiteCollection`1..ctor(String name, LazyLoad`1 engine, BsonMapper mapper, Logger log)
   at LiteDB.LiteDatabase.GetCollection[T](String name)
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
