### ISSUE TITLE
Invalid serialization handling of wrapper structs

### ISSUE THREAD

**Issue by nh43de** [mbdavid/LiteDB#1157]
See github repro repo here:

[https://github.com/nh43de/LiteDbIssueRepo](https://github.com/nh43de/LiteDbIssueRepo)

Basically, we have a struct that wraps a string, and it get inserted into database as null.

Steps to reproduce: 

1. Clone repro repo
2. Run console app
3. See notes and comments in program.cs for expected vs. actual behavior

Here are is the class/struct in question that do not get serialized property. Currency is always serialized to the db as (null).

`

    /// <summary>
    /// Our class that contains Currency properties
    /// </summary>
    public class CurrencyPairInfo
    {
        public Guid Id { get; set; }

        public Currency BaseCurrency { get; set; } = new Currency("USD");
        public Currency QuoteCurrency { get; set; } = new Currency("EUR");

        public double Price { get; set; } = 12.00;

        public override string ToString()
        {
            return $"{BaseCurrency}-{QuoteCurrency}: {Price}";
        }
    }

    /// <summary>
    /// Represents currency key.
    /// </summary>
    public readonly struct Currency : IEquatable<Currency>
    {
        internal Currency(string keyValue)
        {
            KeyValue = keyValue;
        }

        internal bool IsNull => KeyValue == null;

        internal bool IsEmpty => string.IsNullOrEmpty(KeyValue);

        internal string KeyValue { get; }

        public static bool operator !=(Currency x, Currency y)
        {
            return !(x == y);
        }

        public static bool operator !=(string x, Currency y)
        {
            return !(x == y);
        }

        public static bool operator !=(Currency x, string y)
        {
            return !(x == y);
        }

        private static bool CompositeEquals(string keyValue0, string keyValue1)
        {
            return keyValue0.Equals(keyValue1, StringComparison.CurrentCultureIgnoreCase);
        }

        public static bool operator ==(Currency x, Currency y)
        {
            return CompositeEquals(x.KeyValue, y.KeyValue);
        }

        public static bool operator ==(string x, Currency y)
        {
            return CompositeEquals(x, y.KeyValue);
        }

        public static bool operator ==(Currency x, string y)
        {
            return CompositeEquals(x.KeyValue, y);
        }

        public override bool Equals(object obj)
        {
            object obj1;
            if ((obj1 = obj) is Currency)
            {
                var currencyKey = (Currency)obj1;
                return CompositeEquals(KeyValue, currencyKey.KeyValue);
            }

            if (obj is string s)
                return CompositeEquals(KeyValue, s);
            return false;
        }

        public bool Equals(Currency other)
        {
            return CompositeEquals(KeyValue, other.KeyValue);
        }

        public override int GetHashCode()
        {
            return KeyValue?.ToUpperInvariant().GetHashCode() ?? 0;
        }

        public override string ToString()
        {
            return (string)this ?? "(null)";
        }

        internal void AssertNotNull()
        {
            if (IsNull)
                throw new ArgumentException("A null key is not valid in this context");
        }

        /// <summary>
        ///     Create a <see cref="T:ConsoleApp1.Currency" /> from a <see cref="T:System.String" />.
        /// </summary>
        /// <param name="key">The string to get a key from.</param>
        public static implicit operator Currency(string key)
        {
            if (key == null)
                return new Currency();
            return new Currency(key);
        }

        /// <summary>
        ///     Obtain the key as a <see cref="T:System.String" />.
        /// </summary>
        /// <param name="key">The key to get a string for.</param>
        public static implicit operator string(Currency key)
        {
            switch (key.KeyValue)
            {
                case null:
                    return null;
                case string s:
                    return s;
            }
        }
    }
`

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
