### ISSUE TITLE
Unable to retrieve typed objects after changing their class' property type from int to decimal

### ISSUE THREAD

**Issue by Deilan** [mbdavid/LiteDB#1158]
### Description
Unable to retrieve typed object after changing some of it's class' property type from `int` to `decimal`.

### Repro steps:
1. Create a model:
```csharp
public class Customer
{
    public int Id { get; set; }
    public int? Sum { get; set; }
}
```
2. Create an object:
```csharp
var customer = new Customer() { Sum = 100 };
```
3. Persist the typed document:
```csharp
liteDatabase.GetCollection<Customer>("Customer").Insert(customer);
```
4. Change type of `Sum` property from `int` to `decimal`.
```csharp
public class Customer
{
    public int Id { get; set; }
    public decimal? Sum { get; set; }
}
```
5. Retrieve the typed document
```csharp
liteDatabase.GetCollection<Customer>("Customer").FindById(customerId);
```
### Expected Result
The document successfully retrieved.

### Actual Result
System.InvalidCastException: 'Unable to cast object of type 'System.Int32' to type 'System.Decimal'.' on retrieval.

### Tests
[Repository with the tests](https://github.com/deilan-issues-samples/LiteDB.Issues). More specifically:
- [TypedCollectionModelPropertyTypeChangeTests](https://github.com/deilan-issues-samples/LiteDB.Issues/blob/60189d5c53d0823cb6f99e3a9009458fce619994/LiteDB.Issues.Tests/ModelChange/TypedCollectionModelPropertyTypeChangeTests.cs)

**Comment by Deilan** [comment]
The same works fine for a schemeless collection:
- [SchemelessCollectionModelPropertyTypeChangeTests](https://github.com/deilan-issues-samples/LiteDB.Issues/blob/master/LiteDB.Issues.Tests/ModelChange/SchemelessCollectionModelPropertyTypeChangeTests.cs)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
