### ISSUE TITLE
QueryVisitor Error if value and Member are inversed

### ISSUE THREAD

**Issue by techrising** [mbdavid/LiteDB#117]
If I do something like this in a repository
`_db.GetCollection<TType>(typeof (TType).Name).Find(x => id==x.Id)`

In QueryVisitor:
` QueryXXX(this.VisitMember(bin.Left), this.VisitValue(bin.Right));`

VisitMember will be call on "id" which is a value and VisitValue on x.Id which is a Member.
I will get the following error.
> 
Unhandled Exception: LiteDB.LiteException: Property 'Framework' was not mapped into BsonDocument

Which is not very easy to understand.

Member and Value must be identified first.
I will try to fix it in the next few days if I manage to find the time.

**Comment by mbdavid** [comment]
Hi @techrising, internal LiteDB uses only Query object to search documents. `QueryVisitor` is a very, very simple way trying to convert Linq expression to Query object instance. Linq is very complex to me :). I always know about this limitation, if you can fix this will be welcome
