### ISSUE TITLE
LiteDB v5 Release

### ISSUE THREAD

**Issue by mi-uhu** [mbdavid/LiteDB#1179]
@mbdavid 

I wanted to ask if you know until when you will release LiteDB v5 or when there will be a beta version available, because it sounds exactly like what I'm searching for.

Thanks,
Michael

**Comment by JensSchadron** [comment]
Not sure if you'd already seen it or not, but, according to the latest info in the v5 branch, a beta version will be released at the end of this month (~31/05)

**Comment by mi-uhu** [comment]
havn't seen it yet. Thanks! :)

**Comment by JensSchadron** [comment]
Just for future reference, the info was found here
https://github.com/mbdavid/LiteDB/commit/e98c83482d0d42cd3cf0c9cde64435ae69c47b0e

**Comment by JensSchadron** [comment]
Beta release of the v5 branch is expected somewhere in August unless we come across any unforeseen issues.
