### ISSUE TITLE
When 'upserting' using LiteRepository without specifying collection name, a NullReferenceException is thrown

### ISSUE THREAD

**Issue by grisharav** [mbdavid/LiteDB#1187]
The following code works as expected:
``` 
_db.GetCollection<MyType>().Upsert(new MyType());
```
But this code throws:
```
new LiteRepository(_db).Upsert(new MyType());
```

**Comment by JensSchadron** [comment]
I tried to reproduce this but it works as expected on my end. Therefor I'll close the issue.
Feel free to re-open the bug if you found a way to consistently reproduce this. 🙂
