### ISSUE TITLE
"Produts" typo on litedb.org

### ISSUE THREAD

**Issue by NDKilla** [mbdavid/LiteDB#1195]
Sorry if this is the incorrect place, didn't see a repo or file for the litedb.org source, so I figured I'd note it here.

On litedb.org, under the "DbRef for cross references" tab of the simple api section, there's a comment in the preformatted code that says `// Produts and Customer are other collections (not embedded document)`

I believe this should just be "products"

**Comment by JensSchadron** [comment]
@NDKilla could you close this issue as it has been resolved 🙂
