### ISSUE TITLE
LiteDB ObjectID is serialized into a object in JSON

### ISSUE THREAD

**Issue by DonTristras** [mbdavid/LiteDB#1197]
Hi David,

I switched all my model id's to the ObjectID. Now I have an issue, when serializing to JSON what I get is an object instead of a string.

{
  "Timestamp": 1553180302,
  "Machine": 10465542,
  "Pid": 1000,
  "Increment": 2078337,
  "CreationTime": "2019-03-21T14:58:22Z"
}

I know I can convert this object using ToString(), but is there any way to automatically serialize ObjectID to string for a collection? I wouldn't like to have to write an extra Linq query for each controller.

 public JsonResult List()
        {
            try
            {
                var Trees = db.List<Tree>().FindAll();
                return Json(new { status = "OK", record = Trees });
            }
            catch (Exception ex)
            {
                return Json(new { status = "ERROR", message = ex.Message });
            }
        }

**Comment by JensSchadron** [comment]
@DonTristras I don't think there's a way to automatically serialize ObjectIds to strings so you'll have to call ToString() every time. I'll close the issue for now.
