### ISSUE TITLE
ID field selection

### ISSUE THREAD

**Issue by JordanMarr** [mbdavid/LiteDB#12]
After doing spikes with NDatabase, RaptorDB, iBoxDB and LiteDB, I am strongly leaning toward using LiteDB as my lightweight, embedded document datastore of choice due to the easy to understand (and read) examples, intuitive API and Linq query functionality via visitor pattern.  Nice library!

The main rub for me at the moment is the imposition that I must change my domain entities to have a property named "ID", that ends with "ID" or that has a BsonIdAttribute.  I do think that it is a nice convention to have since a lot of entities do have an ID field.  Likewise, the attribute is also a nice option for some.  However, I do not like the design of my domain entities to be driven by third party frameworks, and I also prefer not to litter them with attributes from 3rd party namespaces / attributes. 

So I think there really needs to be a way for a user to designate a unique identifier field via the API.  Ideally, this could be configured on the Collection object right alongside any calls to "EnsureIndex".  

I went ahead and took a quick stab at this and got it working for my purposes.  The change is very simple:

In BsonSerializer.cs, change the _cacheId field to protected:
```
internal static Dictionary<Type, PropertyInfo> _cacheId = new Dictionary<Type, PropertyInfo>();
```

In Collection.Index.cs, add the following API method:
```
		/// <summary>
		/// Sets the designated property to act as the primary key for this entity.
		/// </summary>
		/// <typeparam name="K"></typeparam>
		/// <param name="property"></param>
		public void SetPrimaryKey<K>(Expression<Func<T, K>> property)
		{
			var type = typeof(T);
			var p = QueryVisitor.GetProperty<T, K>(property);
			lock (BsonSerializer._cacheId)
			{
				BsonSerializer._cacheId[type] = p;
			}
		}
```

NOTE: Method could alternatively be called "SetUniqueIndex", or whatever.

Example of calling this:
```
			using (var db = CreateDB())
			{
				var collection = GetCollection<Domain.Document>(db);
				collection.SetPrimaryKey(d => d.Title);
				collection.EnsureIndex(d => d.Author);
			}
```

(It might also be nice to store an array of PropertyInfo objects so as to allow composite keys.)

Thanks,
Jordan

**Comment by mbdavid** [comment]
Hi Jordan,

Your need is acceptable, I never thing about that. Next LiteDB version will came with a `BsonMapper` class. Now, you will can create your own mapper serialize/deserialize functions. 

```C#
BsonMapper.Global.RegisterType<Album>
(
    serialize: (a) => new BsonDocument().Add("_id", a.Title).Add("folder", a.Folder),
    deserialize: (doc) => new Album { Title = doc["_id"].AsString, Folder = doc["folder"].AsString }
);
```

Take a look on [Github Wiki](https://github.com/mbdavid/LiteDB/wiki/Object-Mapping) and `dev` branch.

**Comment by JordanMarr** [comment]
One question about the new serialize/deserialize mapping:
If I manually create a mapping, would I then be required to manually map all the properties for that entity?  For example, if I just wanted to map the ID property, would I then be required to manually map the rest of the properties?

**Comment by mbdavid** [comment]
Unfortunately yes. It's because you are mapping any king of `Type`. Can be a simple `Uri` or a full class. I'm reviewing a way to re-use serialize/deserialize functions to inner properties (like a `Customer` type that as a list of `Address`)
