### ISSUE TITLE
Missing null check when trimming whitespace 

### ISSUE THREAD

**Issue by peters** [mbdavid/LiteDB#120]
Please see attached images:

![image](https://cloud.githubusercontent.com/assets/869/12914010/506b3202-cf22-11e5-90d1-db9ba1a06950.png)

![image](https://cloud.githubusercontent.com/assets/869/12914025/64a3b01e-cf22-11e5-9d9e-396150f0b235.png)

**Comment by peters** [comment]
Fixed in https://github.com/peters/LiteDB/commit/0dcd668255708501961148a7c451ce13f5dc5380

**Comment by mbdavid** [comment]
Hi @peters, thanks for found this bug, but the bug is in another castle :) When `BsonValue` is `Type == BsonType.String` RawValue can be null (if RawValue is null than Type must be BsonType.Null). Now, I need found how did you initialize a BsonValue with Null value but Type marks as String.
