### ISSUE TITLE
Exception while shrinking database

### ISSUE THREAD

**Issue by lordmampf** [mbdavid/LiteDB#1201]
Hello ;)

I'd like to shrink a ~5GB db file.

```

Welcome to LiteDB Shell

Getting started with `help`, `help full` or `help <command>`

> open Game.db
> db.shrink
Shrinking datafile...
No encryption

Unhandled Exception: System.ArgumentOutOfRangeException: Stream length must be non-negative and less than 2^31 - 1 - origin.
Parameter name: value
   at System.IO.MemoryStream.SetLength(Int64 value)
   at LiteDB.TransactionService.PersistDirtyPages()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.InsertBulk(String collection, IEnumerable`1 docs, Int32 batchSize, BsonType autoId)
   at LiteDB.LiteEngine.Shrink(String password, IDiskService tempDisk)
   at LiteDB.Shell.Commands.Shrink.Execute(StringScanner s, Env env)
   at LiteDB.Shell.ShellProgram.Start(InputCommand input, Display display)
   at LiteDB.Shell.Program.Main(String[] args)
   
```

**Comment by lidanger** [comment]
The shrink operation only removes the empty and reused pages.I think you can implement one yourself.Like this

`   /// <summary>
    /// 备份数据库
    /// </summary>
    public static void Backup()
    {
        _logger.Debug("开始备份数据库");

        var path = string.Format("./data/db_{0}.db", DateTime.Now.ToString("yyyyMMddHHmmss"));
        var dbpath = "./data/db.db";

        lock (_locker)
        {
            if (_db != null)
            {
                _logger.Debug("销毁数据库实例");

                try
                {
                    _db.Dispose();
                }
                catch { }
                _db = null;
            }

            try
            {
                // 备份文件
                File.Move(dbpath, path);

                // 创建新实例
                _db = new LiteDatabase(_connStr);

                _logger.DebugFormat("创建数据库实例{0}", _connStr);

                using (var olddb = new LiteDatabase(path))
                {
                    // 创建索引
                    xxxx.EnsureIndex();
                    ...
                    xxxx.EnsureIndex();

                    // 复制集合
                    var colnames = olddb.GetCollectionNames();
                    foreach (var name in colnames)
                    {
                        _logger.DebugFormat("备份集合{0}", name);

                        var col = olddb.GetCollection(name);

                        try
                        {
                            _db.GetCollection(name).InsertBulk(col.FindAll());
                        }
                        catch (Exception ex)
                        {
                            _logger.ErrorFormat("备份集合{0}异常{1}", name, ex.Message);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.ErrorFormat("备份数据库异常{0}", ex.Message);

                try
                {
                    File.Delete(dbpath);
                    File.Move(path, dbpath);
                }
                catch { }
            }
        }

        _logger.DebugFormat("备份数据库结束，备份文件{0}", path);
    }`

**Comment by lordmampf** [comment]
Thank you very much!
I'll test that!
