### ISSUE TITLE
HELP on MAX() and MIN() query with filter

### ISSUE THREAD

**Issue by Gerardo-Sista** [mbdavid/LiteDB#1204]
Hello expert good people, 
Sorry for disturbing but I'm stuck on this it's 3 days. Thank you in advance!

### REQUEST:
I need a **very fast** query finding **MAX(Id)** and **MIN(Id)** filtering by **LanguageId** and **CategoryId**. 

I tried **everything** (Find, Query.And, Linq etc). but did not find an OPTIMIZED FOR SPEED way to get this query: **Select MAX(Id) where LanguageId = MyLangId   AND CategoryId = MyCatId**  working with accceptable speed (only 1800 records takes 3 to 5 seconds!!)

### POCO CLASS
```
  public class ImageInfoDB
    {
        public int Id { get; set; }                      
        public int LanguageId { get; set; }
        public int CategoryId { get; set; }
        public byte[] Data { get; set; }       // <---this is max 30 Kb!
    }
```

### LiteDB CURRENT USAGE
   ```
 ConnectionString = new ConnectionString(DatabaseFullName)
     {
         Password = LiteDbPwd
      };
 using (LiteDatabase db = new LiteDatabase(This.ConnectionString))
      {
         LiteCollection<ImageInfoDB> LiteDbImages= db.GetCollection<ImageInfoDB> 
                      (ImagesTableName);
          LiteDbImages.EnsureIndex(p => p.Id);
          LiteDbImages.EnsureIndex(p => p.LanguageId );
          LiteDbImages.EnsureIndex(p => p.CategoryId);
                     
          int min = LiteDbImages.Min();   //<---- this is SUPER FAST (runs on Id index)
          int max = LiteDbImages.Max();   //<----this is SUPER FAST (runs on Id index)
 
          int minFilteredByLanguageAndCategory  =  ??  all attempts VERY SLOW
          int maxFilteredByLanguageAndCategory =  ??  all attempts VERY SLOW
```

**Comment by mbdavid** [comment]
Hi, if you have only ~1800 docs, I think your performance problem can be this `byte[]` - when you run this kind of query (in v4) engine must deserialize all document (even if you are not use). To be sure of this, try re-create you data in another collection without this `byte[]`;

You don't know if this will works in v4, but if you create an index with this 3 fields (an array data type) inside an array and test `>` using LanguageId and CategoryId in filter only.

**Comment by Gerardo-Sista** [comment]
Thank you for your answer.
I resolved, for now, precaching MIN and MAX from SQL sync database (!!!!!) since there's no way to avoid full deserialization of every record. 
I really hope in v5 there will be some kind of mechanism to partial deserialize only required fields involved in query (and then full deserialize results) otherwise LiteDb would be not usable in many scenarios. :(

**Comment by JensSchadron** [comment]
@Gerardo-Sista LiteDB v5 will have support for partial bson document queries and has a "query analyser" so it might run quite a bit faster.
Anyways, I'll close your issue as it has been answered (I think) in the case of v4. Feel free to re-open the issue if you feel like the given answer wasn't good enough or didn't cover the entire question.
