### ISSUE TITLE
Multiple processes accessing a database on a network share

### ISSUE THREAD

**Issue by UweKeim** [mbdavid/LiteDB#1205]
Trying to run a single instance of a test application against a database stored on a network share, I get approx. a factor of 3 slower performance when doing read/write operations.

This is acceptable for me.

When trying to run multiple instances against the very same database stored on a network share, the first started application seems to run somewhat slower, too, but the secondly started application has approx. a factor of 20 slower performance.

**My question:**

Is a network share stored database accessed by multiple processes a scenario that is not supported, or am I doing something wrong?

**Comment by mbdavid** [comment]
That's not recommended used shared file across multi process. But it's not about LiteDB, but it's about `FileStream` class and how OS LOCK files.

**Comment by UweKeim** [comment]
Thank you, Mauricio.

Strange thing that using a Microsoft Access MDB from network is (relatively) smooth. Makes me wonder, what Access makes different than the `FileStream` implementation.

**Comment by RussellHaley** [comment]
https://en.m.wikipedia.org/wiki/Microsoft_Jet_Database_Engine
