### ISSUE TITLE
how to dump db data directly instead enter interactive mode

### ISSUE THREAD

**Issue by guilechao** [mbdavid/LiteDB#1206]
I need use below command to list all data
LiteDB.Shell.exe
-->enter interactive mode
open mydb
db.myconnection.find

How to use single command to get data and not enter interactive mode
thanks

**Comment by lidanger** [comment]
LiteDB.Shell Usage:
	 LiteDB.Shell [myfile.db] --param1 value1 --params2 "value 2"
	 Parameters:
	 --exec "command"   : Execute an shell command (can be multiples --exec)
	 --run script.txt   : Run script commands file
	 --pretty           : Show JSON in multiline + indented
	 --exit             : Exit after last command

**Comment by lidanger** [comment]
I find this is not listed in the document.

@mbdavid

**Comment by JensSchadron** [comment]
I'm closing the issue as the question has been resolved. Please note that, in the upcoming LiteDB v5,  the LiteDB.Shell has been removed in favor of LiteDB Studio.
