### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. Parameter name: filename - Mac OS

### ISSUE THREAD

**Issue by avfranco-br** [mbdavid/LiteDB#1207]
Hello, 

I am trying to run a simple program to create a new DB file,  insert, query and delete documents. I've set the Mode=Exclusive in the connection string and database being created fine however any operation throws the exception Value cannot be null. Parameter name: filename.

Thanks for any advice.

Alexandre

**Comment by JensSchadron** [comment]
Hi @avfranco-br,

This error might get thrown if you don't specify a filename for you database. You should try to create your LiteDatabase instance like this.
`var dbInstance = new LiteDatabase(new ConnectionString("litedb.db") {
    Mode = LiteDB.FileMode.Exclusive}
);`

I hope this solves your issue.

**Comment by avfranco-br** [comment]
> Hi @avfranco-br,
> 
> This error might get thrown if you don't specify a filename for you database. You should try to create your LiteDatabase instance like this.
> `var dbInstance = new LiteDatabase(new ConnectionString("litedb.db") { Mode = LiteDB.FileMode.Exclusive} );`
> 
> I hope this solves your issue.

Hi @JensSchadron , sorry for not replying sooner but I was able to test only today! It's working now. Many thanks for your help!
