### ISSUE TITLE
Unable to cast object of type 'LiteDB.CollectionPage' to type 'LiteDB.IndexPage'.

### ISSUE THREAD

**Issue by nguyentuevuong** [mbdavid/LiteDB#121]
Has an error:
Unable to cast object of type 'LiteDB.CollectionPage' to type 'LiteDB.IndexPage'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
Exception Details: System.InvalidCastException: Unable to cast object of type 'LiteDB.CollectionPage' to type 'LiteDB.IndexPage'.
Source Error: 
```
Line 45:             }
Line 46: 
Line 47:             return (T)page;
Line 48:         }
Line 49: 
```

Source File: ...\LiteDB\DbEngine\Services\PageService.cs    Line: 47

**Comment by mbdavid** [comment]
Did you have code snippet to reproduce this error?

**Comment by nguyentuevuong** [comment]
![image](https://cloud.githubusercontent.com/assets/3804521/13053282/404924ba-d436-11e5-8b47-017d2dfa3d5a.png)
Here you are.

**Comment by nguyentuevuong** [comment]
This is the call stack
![image](https://cloud.githubusercontent.com/assets/3804521/13053591/e643f524-d437-11e5-9816-d92cb39049d5.png)

**Comment by adoconnection** [comment]
Any thoughts?

**Comment by mbdavid** [comment]
I re-write a lot of disk strategy to avoid this. Can you test again using master branch?

**Comment by mahmoud-samy-symbyo** [comment]
+1 for the bug
package: v2.0.2
