### ISSUE TITLE
Unable to store classes inherited from a collection.

### ISSUE THREAD

**Issue by gunpal5** [mbdavid/LiteDB#1211]
Hello,

I have many desktop applications developed over last 4-5 years. I recently needed to change data storage used in the software. I decided to use LiteDb. The problem I am facing is that I have most of the classes inherited from ObservableCollection<T>. e.g.
`
public class SomeItem
{
public string SomeProperty{get;set;}
}
}
`
`
public class SomeItemCollection:ObservableCollection<SomeItem>
{
//Codes.....
//Codes...
}`
`
public class MyProjectClass
{
public string ProjectName{get;set;}
public SomeItemCollection Items{get;set;}
}
`
Now whenever I try to store the project classes which have many properties like SomeItemCollection in example, I get this exception:
![image](https://user-images.githubusercontent.com/10114874/56827875-9e724380-687d-11e9-945d-484a663c2824.png)

Is there anyway to register a custom bson mapper so that I can map the classes in my project into bson. The classes I am trying to store into the database can be serialized without any issue using Newtonsoft.Json.JsonConvert.Serialize method, but some how litedb is unable to serialize them.

Thanks
Gunpal Jain

**Comment by gunpal5** [comment]
Please consider this pull request:
https://github.com/mbdavid/LiteDB/pull/1212

**Comment by JensSchadron** [comment]
Hi @gunpal5 ,

I've been trying to reproduce your case with the classes you provided, without success so far as it correctly (de)serializes the classes.
Below is the code I wrote in an attempt to reproduce it.
```csharp
public class SomeItem
{
    public string SomeProperty { get; set; }
}

public class SomeItemCollection : ObservableCollection<SomeItem>
{
    //Codes..... //Codes...
}

public class MyProjectClass
{
    [BsonId]
    public string ProjectName { get; set; }
    public SomeItemCollection Items { get; set; }
}

static void Main(string[] args)
{
    var projectClass = new MyProjectClass
    {
        ProjectName = "Test",
        Items = new SomeItemCollection
        {
            new SomeItem {SomeProperty = "Test 1"},
            new SomeItem {SomeProperty = "Test 2"},
            new SomeItem {SomeProperty = "Test 3"}
        }
    };

    var liteDb = new LiteDatabase(new MemoryStream()); // In-memory database for testing purposes.
    /*liteDb.Mapper.RegisterType<SomeItemCollection>(obsCol => new BsonArray(obsCol.Select(obj => liteDb.Mapper.ToDocument(obj))), bsonValue =>
    {
        var coll = new SomeItemCollection();
        var bsonArray = bsonValue.AsArray;

        foreach (var bsonValueOfArray in bsonArray)
        {
            coll.Add(liteDb.Mapper.ToObject<SomeItem>(bsonValueOfArray.AsDocument));
        }

        return coll;
    });*/

    var myProjectClassCollection = liteDb.GetCollection<MyProjectClass>();
    myProjectClassCollection.Insert(projectClass);

    var deserializedProjectClass = myProjectClassCollection.FindOne(Query.All());
}
```

**Comment by JensSchadron** [comment]
@gunpal5 I believe my answer resolves your question so I'm closing the issue. Feel free to re-open the issue if you feel like your issue hasn't been resolved yet.
