### ISSUE TITLE
Large Data base file - 15GB - What's the best way to read the content and export to a file?

### ISSUE THREAD

**Issue by avfranco-br** [mbdavid/LiteDB#1217]

**Comment by avfranco-br** [comment]
Hello guys,

I have a 15GB data base file which I need to read the content and export to a text file. The documents are small but amount of records is greater than 15,000,000. 

To avoid issues with the server memory is there any way to read bunch of data only, write to the file, move to next and so on until reach the end of the file?

Many thanks,
Alexandre

**Comment by mbdavid** [comment]
Hi Alexandre, you can use Find method that returns an `IEnumerable` content... and than save direct into a FileStream in any format you want. There is no memory consume in this case because will run 1 document per time.

**Comment by avfranco-br** [comment]
Hi Mauricio, obrigado & thanks! It's working fine.
