### ISSUE TITLE
Issue with retrieving data

### ISSUE THREAD

**Issue by chrisrwebb** [mbdavid/LiteDB#123]
Hi All,

I am new to LiteDB. I am testing out the database but am running into an error retrieving data. I have pretty much copied the sample getting started program. I tried changing the DLL to version 2 but I am still getting the same error. I am getting the folowing error. I would really appreciate some help. 

Additional information: Failed to create instance for type 'CDBTest.BoatClass' from assembly 'CDBTest.BoatClass, CDBTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Checks if has a public constructor with no parameters

Source 
`namespace CDBTest
{

    class BoatClass
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Length { get; set; }
        public bool IsActive { get; set; }
    }

    public partial class Form1 : Form
    {
     
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            using (var db = new LiteDB.LiteDatabase(@"TestDb.db"))
            {
                var boats = db.GetCollection<BoatClass>("boats");

                //var boat = new BoatClass
                //{
                //    Name = "PARU",
                //    Length = 35,
                //    IsActive = true
                //};

                boats.EnsureIndex(x => x.Name);

                

                //boats.Insert(boat);
                //var results = boats.FindAll();
                
                foreach( BoatClass RtnBoat in boats.FindAll() )
                {
                    label1.Text = RtnBoat.Id.ToString();
                    label2.Text = RtnBoat.Name;

                }

              //  'label1.Text = results

            }
        }

        private void button2_Click(object sender, EventArgs e)
        {
           
        }
    }
}`

**Comment by mbdavid** [comment]
Hi, sorry not long wait. You entity class must be public.

```
public class BoatClass
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Length { get; set; }
    public bool IsActive { get; set; }
}
```
