### ISSUE TITLE
LiteDB query in 2 related Collections

### ISSUE THREAD

**Issue by cese01** [mbdavid/LiteDB#1231]
I have a LiteDB database with 2 POCO classes
Author that includes "Id" and "Name", as Properties
Book that includes "Title" "Id" and "Author"(this property has a bson reference to the Author's collection)
I'm trying to query the book collection in order to retrieve all authors named "John" that wrote one or more books.

 class Author // collection "authors"
 {
     [BsonId]
     public int id {get; set;}
     public string Name{get; set;}
 }
 class Book //collection "books"
 {
     [BsonId]
     public int id {get; set;}
     public string Title{get; set;}
     [BsonRef("authors")] 
     public Author author {get; set;}
}
Thank you for the help
P.S. I know that it's not for what litedb is been made for but I have to do this.

**Comment by Brannos1970** [comment]
You can use Linq to do this:
`db.Query<Authors>()
    .Include(x => x.Books)
    .Where(x => x.Name.Containes("John")
    .ToList()`

Or you can do it this way with LiteDB expressions:
`var result = Authors
    .Include(x => x.Books)
    .Find(Query.Contains("Name", "John")`

**Comment by JensSchadron** [comment]
@cese01 I believe the answer of @Brannos1970 resolves your question so I'm closing the issue. If you feel like you're question hasn't been answered yet, you can re-open the issue.
