### ISSUE TITLE
Min entity data size. 

### ISSUE THREAD

**Issue by lobster2012-user** [mbdavid/LiteDB#1233]
Hello. 
 I want to use the repository for one task.  The number of records is about 50,000. After the first filling, I will only update them.  The size of one record is limited.  I think it would be nice to enter the parameters - the granularity and the minimum size of the record, which would save you from swelling.  Perhaps in my case it is not so critical.  What do you think about it?
IGetBufferSizeStrategy

**Comment by mbdavid** [comment]
Hi @lobster2012-user, again about v5: now page allocation contains 5 free-space lists with diferent sizes.

```
/// 90% - 100% = 0 (7344 - 8160)
/// 75% -  90% = 1 (6120 - 7343)
/// 60% -  75% = 2 (4896 - 6119)
/// 30% -  60% = 3 (2448 - 4895)
///  0% -  30% = 4 (0000 - 2447)
```

Every time a document are inserted/update, page are realocated in one index based on how many bytes are free
