### ISSUE TITLE
Memory managment and perfomance

### ISSUE THREAD

**Issue by lobster2012-user** [mbdavid/LiteDB#1235]
Hi!
I wanted to make a comment about excessive memory allocation.
Looked at version 5, saw some mentions of pools.
By redundant allocation of memory, I mean frequent calls to new and clear instead of using the allocated memory earlier. You can also write immediately in memory (file), instead of pre-recording in the buffer.
I would like to understand what we are going to in version 5.
Keeping keys, using buffers, etc.
I wanted to debug an upsert in version 5, so to speak, to feel the difference, but inside notImplemented.

**Comment by mbdavid** [comment]
Hi @lobster2012-user, now upsert already implemented. New v5 works complete different from all other version about how use memory buffers and re-allocate and share same memory spaces.
In v5 I implement some like virtual file mapping, in memory, in pages blocks. Each page buffer can be shared across threads when are read-only but has a own page buffer when need write. This avoid lot's off byte[] creation...

**Comment by lobster2012-user** [comment]
Hi @mbdavid .
Thank you for answer.
