### ISSUE TITLE
Keep multi-process support in v5

### ISSUE THREAD

**Issue by viktor-svub** [mbdavid/LiteDB#1240]
I see in v5 branch, "Single process only - optimazed for multi thread (open file as exclusive mode)". 

I'm tracking this project with great interest, as it could be a fully managed SQLite alternative -- if the access pattern is similar/adaptable enough, that is -- and I'm afraid making this a simpler in-process storage will lose a lot of possible use cases, e.g. cross-service logging backend, not just for myself. 

Dropping multi-process access would for sure enable much better single-process performance, 
but there are many alternatives already available, like https://microsoft.github.io/FASTER/, 
with different features, not as easy to use, but adapters can be written, and the engine is what matters in the end.

**Comment by mbdavid** [comment]
Hi @viktor-svub, core engine will support only single in-memory instance to keep locks/variable controls in one single memory allocation.

But, I'm also working in shared implementation on Database level (client). This will manage this single instance across processes. I don't know if will be the best performance, but will works for almost solutions
