### ISSUE TITLE
what time v5 publish?

### ISSUE THREAD

**Issue by zjsxfly** [mbdavid/LiteDB#1241]

**Comment by PascalSenn** [comment]
https://github.com/mbdavid/LiteDB/issues/1179

**Comment by delphidoc** [comment]
?

**Comment by Szymaniuk** [comment]
Duplicated or not, it was about to be published by the end of May. It's already July, and there is no v5 yet. Any new planned release date?

**Comment by JensSchadron** [comment]
As far as I know, the author experienced some issues and and required more time to sort those out. A new release date hasn't been published yet.

**Comment by mbdavid** [comment]
Hi guys, I'm backing to code in LiteDB v5 the release as soon as possible. I had some family problems that was not possible release in May/31. I had no fixed date yet, but I'm going to SF in Sep/3 to pitch about LiteDB... and in this presentation I will show new v5! Now it's time to work harder.

**Comment by mbdavid** [comment]
In this month I will release first alpha version and update some documentation.
