### ISSUE TITLE
Is this project still being actively maintained?

### ISSUE THREAD

**Issue by rolandh** [mbdavid/LiteDB#1247]
Is this project still being actively maintained? I see there are a large number of issues open that go back to 2017 ?

**Comment by PascalSenn** [comment]
The author is currently working on v5 and had some private stuff to do. Have a look at https://github.com/mbdavid/LiteDB/issues/1241

**Comment by mbdavid** [comment]
Hi @rolandh, as @PascalSenn says, I'm working in v5 and there is a lot of duplicate issues here. I will try keep clean and answer more offen. Take a look on v5, it's a great new version and has many new features

**Comment by rolandh** [comment]
There are some specific bugs that I want to know if they are fixed. Can you reply to my other open ticket and let me know if it is fixed in version 5?
