### ISSUE TITLE
FindAll() Failed to create instance for type 'System.Xml.XmlCDataSection'

### ISSUE THREAD

**Issue by AndreasHohnholt** [mbdavid/LiteDB#125]
Hi @ll,

if I try to receive objects with a property of the type System.Xml.XmlCDataSection I run in this exception:

Failed to create instance for type 'System.Xml.XmlCDataSection' from assembly 'System.Xml.XmlCDataSection, System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Checks if has a public constructor with no parameters

Any ideas how to fix this?

Kind regards,
Andy

**Comment by mbdavid** [comment]
Hi @AndreasHohnholt,

To convert a class to a BSON document, your class must have a public constructor. See all rules here:

https://github.com/mbdavid/LiteDB/wiki/Object-Mapping

I recomend you create your own classes instanted use .NET base classes for that (to avoid more problems)

**Comment by AndreasHohnholt** [comment]
Ok i have fix the problem by adding a custom CData class based on the solution in this post http://stackoverflow.com/questions/1379888/how-do-you-serialize-a-string-as-cdata-using-xmlserializer

My CData Class:
`    public class CData : IXmlSerializable
    {
        private string _value;

        public string Value {
            get
            {
                return _value;
            }
            set
            {
                _value = value;
            }
        }

        /// <summary>
        /// Allow direct assignment from string:
        /// CData cdata = "abc";
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static implicit operator CData(string value)
        {
            return new CData(value);
        }

        /// <summary>
        /// Allow direct assigment to string
        /// string str = cdata;
        /// </summary>
        /// <param name="cdata"></param>
        /// <returns></returns>
        public static implicit operator string(CData cdata)
        {
            return cdata._value;
        }

        public CData()
            : this(string.Empty)
        {
        }

        public CData(string value)
        {
            _value = value;
        }

        public override string ToString()
        {
            return _value;
        }

        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }

        public void ReadXml(System.Xml.XmlReader reader)
        {
            _value = reader.ReadElementString();
        }

        public void WriteXml(System.Xml.XmlWriter writer)
        {
            writer.WriteCData(_value);
        }
    }`
