### ISSUE TITLE
Multithreaded data reading

### ISSUE THREAD

**Issue by MaoqingWang** [mbdavid/LiteDB#1250]
If I have five tables and each table has 140,000 data, and now five threads are going to read the data in full, why does the time consumption increase

**Comment by mbdavid** [comment]
Hi @MaoqingWang, in v5, each thread will use a exclusive `FileStream` instance. In v4, all threads use same FileStream instance. You will see a great performance improve in this way.

**Comment by JensSchadron** [comment]
@MaoqingWang does this answer? If so, could you close the issue?
