### ISSUE TITLE
Strange (wrong?) Include behaviour 

### ISSUE THREAD

**Issue by matryosha** [mbdavid/LiteDB#1253]
# Using Inlcude breaks collection reference load
Code to reproduce:
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using LiteDB;

namespace TestLiteDb
{
    class Program
    {
        static void Main(string[] args)
        {
            var mapper = BsonMapper.Global;
            mapper.Entity<Customer>()
                .Id(c => c.Guid)
                .DbRef(c => c.Orders, "orders");
            mapper.Entity<Order>()
                .Id(o => o.Guid);


            var customer1 = new Customer
            {
                Name = "Customer1"
            };
            
            var customer2 = new Customer
            {
                Name = "Customer2"
            };
            
            var order1 = new Order
            {
                Name = "order1"
            };

            var order2 = new Order
            {
                Name = "order1"
            };
            

            var db = new LiteDatabase("Testdb");
            var col = db.GetCollection<Customer>("customers");
            customer1.Orders.Add(order1);
            col.Insert(customer1);
            col.Insert(customer2);
            customer2.Orders.Add(order2);
            col.Update(customer2);
            
            var findAllwithoutInclude = col
                .FindAll().ToList();

            var findOneByIdWithoutInclude = col.FindById(customer1.Guid);
            var findOneByIdWithoutInclude2 = col.FindById(customer2.Guid);
            
            var findAllWithInclude = col
                .Include(c => c.Orders)
                .FindAll().ToList();
            
            var findOneByIdWithInclude = col.Include(c=>c.Orders).FindById(customer1.Guid);
            var findOneByIdWithInclude2 = col.Include(c=>c.Orders).FindById(customer2.Guid);

            

        }
    }

    class Customer
    {
        public Customer()
        {
            Orders = new List<Order>();
        }
        public string Guid { get; set; } = System.Guid.NewGuid().ToString();
        public string Name { get; set; }
        public List<Order> Orders { get; set; } 
    }

    class Order
    {
        public string Guid { get; set; } = System.Guid.NewGuid().ToString();
        public string Name { get; set; }
    }
}

```
# Results:
### Correct:
![1](https://user-images.githubusercontent.com/23679019/61648524-439f8b00-acb8-11e9-9fc9-498aa53f12b5.png)
### Correct:
![2](https://user-images.githubusercontent.com/23679019/61648581-65990d80-acb8-11e9-8aef-a6c94496ebfc.png)
### Correct:
![3](https://user-images.githubusercontent.com/23679019/61648604-6df14880-acb8-11e9-8356-6221e1cbfc3a.png)
### Wrong:
![4](https://user-images.githubusercontent.com/23679019/61648635-7cd7fb00-acb8-11e9-8c9f-657e8a126c9d.png)
### Wrong:
![5](https://user-images.githubusercontent.com/23679019/61648758-c0cb0000-acb8-11e9-8c2a-30b5064f02a1.png)
### Wrong:
![6](https://user-images.githubusercontent.com/23679019/61648787-cfb1b280-acb8-11e9-820e-c5ce95e7998c.png)

So, does it work as intened or is this really a bug? Thanks in advance.

ps. Ubuntu 19, netcore 2.2

**Comment by JensSchadron** [comment]
Not sure if it's intended, but I noticed that you had to store the object that you want to get referenced yourself.
So in your case, you would have to save the instance of Customer in the Customer collection, but also the Orders (that are contained in the Customer object) in the Order collection.

**Comment by matryosha** [comment]
It's kinda sad that one need to wrap existed entities to get things work as needed. Thanks for sharing a workaround, though.
