### ISSUE TITLE
Data not saved after Insert

### ISSUE THREAD

**Issue by omfgicbf** [mbdavid/LiteDB#1260]
Whilst attempting to create a test database using version 5 (commit 0eb8940), I add a number of rows using `Collection.Insert`, yet when I use `FindAll()`, no documents are returned.

(See #1259 for sample code)

The query is this:-
```
foreach (var e in col.FindAll())
{
	Debug.WriteLine($"{e.DateTime}");
}
```

When I create the data, I get a `test.litedb` file (which is the nominated filename) and a `test-log.litedb`.

`test.litedb` is only 8KB, whereas the `test-log.litedb` is 3,976KB (or larger, depending on how many documents I insert)

**Comment by omfgicbf** [comment]
To clarify, I'm using the `public int Insert(IEnumerable<T> docs)` overload of Insert.

Here is the debug log whilst for the insert run:-

```
1|ENGINE: start initializing
1|CACHE: extending memory usage: (segments: 1 - used: 7.8MB)
1|DISK: creating new database: 'test.litedb'
1|ENGINE: initialization completed
1|CACHE: extending memory usage: (segments: 2 - used: 15.6MB)
1|CACHE: extending memory usage: (segments: 3 - used: 23.4MB)
1|TRANSACTION: commit transaction (2885 pages)
1|DISK: disposing disk writer queue (with 2266 pages in queue)
1|ENGINE: engine disposed
```

Files after insert:-
![image](https://user-images.githubusercontent.com/39300379/61851373-20641e00-aefa-11e9-99fe-ebd898a3d5db.png)

Debug output from running `FindAll`:-
```
1|ENGINE: start initializing
1|CACHE: extending memory usage: (segments: 1 - used: 7.8MB)
1|ENGINE: initialization completed
1|TRANSACTION: commit transaction (0 pages)
1|ENGINE: engine disposed
```

**Comment by mbdavid** [comment]
Can you paste your code so I can test local here?

**Comment by omfgicbf** [comment]
To write:-
```
static void Main(string[] args)
{
	var file = @"test.litedb";

	using (var db = new LiteDatabase(file))
	{
		var col = db.GetCollection<Event>("event");

		var tmp = new List<Event>();

		for (var i = 0; i < 100_000; i++)
		{
			tmp.Add(new Event()
			{
				Data = "the quick brown fox jumps over the lazy dog",
				DateTime = DateTime.Now
			});
		}

		col.Insert(tmp);
	}
}


public class Event
{
	public Guid Id { get; set; }

	public DateTime DateTime { get; set; }

	public string Data { get; set; }
}
```

To read:-

```
static void Main(string[] args)
{
	var file = @"test.litedb";

	using (var db = new LiteDatabase(file))
	{
		var col = db.GetCollection<Event>("event");

		foreach (var e in col.FindAll())
		{
			Debug.WriteLine($"{e.DateTime}");
		}
	}
}
```

**Comment by omfgicbf** [comment]
So I've just tested using `Checkpoint()`, and the data is now available when I call `FindAll()`.

Is this expected? I have run other different tests (where I was inserting individual documents) without `Checkpoint()` and the results were still available via `FindAll()`.

**Comment by mbdavid** [comment]
Ok, maybe was fixed when I fix last issue. With or without checkpoint you must can read data

**Comment by JensSchadron** [comment]
@omfgicbf Were you able to verify it using the latest commits? If it works, could you close the issue?

**Comment by omfgicbf** [comment]
@JensSchadron unable to re-test per #1270

**Comment by omfgicbf** [comment]
As of v5 (master 203edef) this issue is no longer occurring.

Data saved via the `public int Insert(IEnumerable<T> docs)` overload is retrievable irrespective of whether `Checkpoint` is called.

**Comment by twostepdevelopers** [comment]
Here same thing happend. First table with is primary did not insert records but giving Id=1 then when i  am going to insert in second table second table inserted with ref id 1. but in primary table there is no record. after that in second hit all good.
item.CreatedDate = DateTime.Now;
                        collection.Insert(item);
                        collection.EnsureIndex(x => x.Id);
                        collection.EnsureIndex(x => x.ItemName);
                        collection.EnsureIndex(x => x.ItemCode);
                        collection.EnsureIndex(x => x.ItemType);
                        BsonMapper.Global.Entity<ItemStock>().DbRef(x => x.Item, "Items");
            var itemStock = new ItemStock
            {
                CreatedDate = DateTime.Now,
                Item = item,
                Quantity = item.OpeningStock
            };
            switch (stockType)
            {
                case StockType.OpeningStock:
                    itemStock.TransactionType = StockType.OpeningStock;
                    break;
                case StockType.AddStock:
                    itemStock.TransactionType = StockType.AddStock;
                    break;
                case StockType.ReduceStock:
                    itemStock.TransactionType = StockType.ReduceStock;
                    break;
            }

            this.ItemStocks.Insert(itemStock);
            this.ItemStocks.EnsureIndex(x => x.Id);
            this.ItemStocks.EnsureIndex(x => x.TransactionType);
            this.ItemStocks.EnsureIndex(x => x.Quantity);
            this.ItemStocks.EnsureIndex(x => x.Item);
