### ISSUE TITLE
LiteDB.Shell missing

### ISSUE THREAD

**Issue by omfgicbf** [mbdavid/LiteDB#1261]
LiteDB.Shell appears to be missing in version 5.

Has the shell been discontinued in version 5? and if so, what is the replacement tool for command-line use-cases?

**Comment by mbdavid** [comment]
Hi, yes, shell was discontinued and was created a Windows UI interface: LiteDB.Studio (are in same solution). There is no more shell tool and no more shell command parser (was replaced to SQL-Like language)

![image](https://user-images.githubusercontent.com/1137197/61870132-bb85d500-aeb3-11e9-99b8-f00e86bf7404.png)

**Comment by omfgicbf** [comment]
Right; so if you are running in an environment without a UI, there will no longer be a method of managing databases outside of code?

**Comment by mbdavid** [comment]
It's too hard keep two interfaces working... Its only 1 dev :) 

To create a new console tool now must use SQL syntax. Maybe another project...
