### ISSUE TITLE
Excessive log size

### ISSUE THREAD

**Issue by omfgicbf** [mbdavid/LiteDB#1262]
When creating a test database in version 5 (commit 0eb8940) and inserting 100,000 documents (approx 150 bytes each when represented using JSON), the resulting `test.litedb` file is only 8KB, whilst the `test-log.litedb` file is >4GB.

Using the following (see also sample code in #1259):-

```
for (var i = 0; i < 100_000; i++)
{
	col.Insert(new Event()
	{
		Data = "the quick brown fox jumps over the lazy dog",
		DateTime = DateTime.Now
	});
}
```

Querying documents afterwards returns results as expected.

**Comment by mbdavid** [comment]
Current alfa version has no auto-checkpoint to move from log file to data file. You must call manual (`db.Checkpoint()`).

Also, you are creating 100_000 transactions. If you create a single transaction this log will be much smaller:

```C#
IEnumerable<Event> GetEvents() 
{
    for (var i = 0; i < 100_000; i++)
    {
        yield return new Event()
        {
            Data = "the quick brown fox jumps over the lazy dog",
            DateTime = DateTime.Now
        };
    }
}

col.Insert(GetEvents());

**Comment by omfgicbf** [comment]
Thanks.

So is this requirement to call `Checkpoint()` expected to remain in the release version?

**Comment by Jacko1394** [comment]
I am wondering this also

**Comment by mbdavid** [comment]
Hi guys, current master branch version are doing "auto-checkpoint" when log file gets 1000 pages.

This will be available in next beta version.
