### ISSUE TITLE
[Question] Query.All() is missing in v5

### ISSUE THREAD

**Issue by JensSchadron** [mbdavid/LiteDB#1264]
While trying to reproduce issue #1263, I noticed that `Query.All()` is missing in LiteDB v5.
Is this intended or has this gone lost in the rewrite?
I know it's possible to use `.FindAll()`, but we sometimes use `Query.All()` to pass it to a service which appends another part to the query predicate before passing it to the `.Find(...)` method.

**Comment by mbdavid** [comment]
No, was my fault. New v5 works complete about running queries. Query class now works as a query definition. Now, all `Query` static methods must return a `BsonExpressions`. I will add `Query.All()` as `1=1`

**Comment by toumir** [comment]
@JensSchadron  the issue was fixed for V4 ?

**Comment by JensSchadron** [comment]
@toumir This issue was about existing functionality of v4 that went lost in the v5 beta branch.
So in short, your issue (#1263) hasn't been fixed (yet).
