### ISSUE TITLE
Failed to upgrade database file to v2.0rc from v1.04 .

### ISSUE THREAD

**Issue by suxiaojack** [mbdavid/LiteDB#127]
I recompiled the shell tool  from V2.0 RC source code for upgrading the database file. But the upgrade failed.
Yet,when I recompiled the v1.04 version of the source code in local machine , and replace the LiteDB104.DLL file under 'Resource' Directory, the data is updated normally.
The Unicode character string be used in my language environment,maybe the LiteDB104.DLL file,that pre-complied ,has some bug.

**Comment by mbdavid** [comment]
Hi @suxiaojack, new version are released. Now I fixed english language in assembly properties.
