### ISSUE TITLE
Sequence contains no elements at  5.0.0-alpha

### ISSUE THREAD

**Issue by VasenevEA** [mbdavid/LiteDB#1275]
Every operation with collection throw System.InvalidOperationException.

Framework: Xamarin.Forms
Platform:  Android OS
Library Version: 5.0.0-alpha

Code to reproduce:

```
var db = new LiteDatabase("database.db"));
var collection = db.GetCollection<T>("exampleColleciton");
var allElements= collection.FindAll();
```
Also **Insert**, **Delete**, **Find** will throw
System.InvalidOperationException: Sequence contains no elements
StackTrace:
```

Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source)
LiteDB.Engine.LiteEngine
LiteDB.Engine.LiteEngine..ctor (LiteDB.Engine.EngineSettings settings) [0x0011b] in <c593d84b647a4ed5b475ff841900e3c2>:0
LiteDB
ConnectionString.CreateEngine ()
System
Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode)
System
LazyHelper.ThrowException ()
System
Lazy`1[T].CreateValue ()
System
Lazy`1[T].get_Value ()
System
Lazy`1[T].CreateValue ()
System
Lazy`1[T].get_Value ()
LiteDB
LiteCollection`1[T].Find (LiteDB.Query query, System.Int32 skip, System.Int32 limit)
```

**Comment by Enviolet** [comment]
I ran into the same problem. It only occurs when I create the database completely new (0kB file). The Exception is thrown on ```LiteDatabase db = new LiteDatabase(liteDbPath)```. It can however be opened by the LiteDB Studio.
I solved the problem by simply downgrading to 4.1.4.

**Comment by bluekuen** [comment]
Yeah I've got the same problem with Xamarin.Forms 4.5.
The App is crashing at this Line:

` var db = new LiteDatabase(dbPath);`

I switched back to 4.1.4.

**Comment by biapar** [comment]
Also 5.0.7

**Comment by lbnascimento** [comment]
@VasenevEA @Enviolet @bluekuen @biapar This error is probably happening because LiteDB is trying to open a zero-byte file (which is obviously not a valid datafile). We'll release a fix for this eventually, but in the meantime just make sure the file you're trying to open is a valid datafile (and not a zero-byte file).

**Comment by bluekuen** [comment]
yeah that was the problem, i fixed it by deleting the file creation:

```
        public string GetDatabasePath()
        {
            var path = Path.Combine(_appData, "ZAsetMobile.db");

            //if (!File.Exists(path))
            //{
            //    using (var streamWriter = new StreamWriter(File.Create(path))) ;
            //}

            return path;
        }

```
Many thanks for your help!
kind regards, bluekuen

**Comment by jez9999** [comment]
> @VasenevEA @Enviolet @bluekuen @biapar This error is probably happening because LiteDB is trying to open a zero-byte file (which is obviously not a valid datafile). We'll release a fix for this eventually, but in the meantime just make sure the file you're trying to open is a valid datafile (and not a zero-byte file).

"Fix this eventually"?  I just came across this problem and it seems like it should be a relatively simply fix to check for a zero byte file and act accordingly.  It's something people are quite likely to do when creating a new DB so I think you guys should fix it ASAP.

**Comment by bluekuen** [comment]
Is this fixed already?

**Comment by FringeScientist** [comment]
Unfortunately still no fix...

**Comment by riuson** [comment]
2020-10-26
v 5.0.9
Not fixed yet.

**Comment by garrypopplewell** [comment]
Still seems to be happening in 5.0.10 but I got around it by setting an initial size with the following code...

`string dbpath = DependencyService.Get<IDataBaseAccess>().DatabasePath();
            var conn = new ConnectionString()
            {
                Filename = dbpath,
                Connection = ConnectionType.Direct,
                **InitialSize = 8192**
            };
            
            DBInstance = new LiteDatabase(conn);   `

**Comment by jez9999** [comment]
This has apparently been fixed, and the bug should probably be closed; see: https://github.com/mbdavid/LiteDB/issues/1956
