### ISSUE TITLE
[question] [bug] which simbol to use for naming reserved collections in my application?

### ISSUE THREAD

**Issue by alemik** [mbdavid/LiteDB#1282]
Hi,
Collection name starting with "_" is used to naming reserved collection inside LiteDB engine.

[bug]
If i create a collection named "$col" directly, i recieve an exeption: "invalid format "$col".
But if, for example, i create a collection named "col" and i rename it as "$col", everything works fine. Is this a bug?

[question]
Now i know that can be used only letters, numbers and _
Which starting simbol can i use to identify my reserved collections instead "$"?
Can use "_" too? I think it could be dangerous.
If it is possible, i prefer to avoid numbers.

Thanks

**Comment by mbdavid** [comment]
Hi @alemik, are you using v4 or v5? There are some difference in versions.

I found a bug (in v5) in this nameing checking - will fix

**Comment by mbdavid** [comment]
Here v5 name validation:

- Names should be a word: `[a-z]_$` (case insensitive)
- Names should not starts with `$` (reserved for system collections)

System collection are "virtual collections", is not concrete data (like `$transactions` returns all open transactions) or "functions" (like `$file_csv('c:\temp\data.csv')` to read data from CSV file as a collection)

Collections that starts with `_` are normal user collections. Need attention only for FileStorage: file storage need 2 user collections to store data and, by default, names are `_files` and `_chunks` (this names can be changed is used with `GetStorage` method).

**Comment by alemik** [comment]
Thanks @mbdavid 
I'm still using V4 and waiting for V5 stable release.
For now i will use _ with care.
