### ISSUE TITLE
Am I setting up DBRef incorrectly? v5.0.0-alpha

### ISSUE THREAD

**Issue by lxman** [mbdavid/LiteDB#1285]
This is the code snippet that I am focusing on:
```
                    var zipData = db.GetCollection<ZipCodeData>(Constants.ZipDataDocuments);
                    DateTime insertTime = DateTime.Now;
                    zipData.Insert(zdata);
                    Console.WriteLine($"Insert time : {(DateTime.Now - insertTime).TotalMilliseconds} ms");
                    DateTime queryStart = DateTime.Now;
                    var result = zipData
                        .Include(zd => zd.AreaCode)
                        .Include(zd => zd.City)
                        .Include(zd => zd.County)
                        .Include(zd => zd.FIPS)
                        .Include(zd => zd.State)
                        .Include(zd => zd.Zip)
                        .FindAll()
                        .ToList();
                    result = result.Where(zd => Convert.ToInt32(zd.Zip.Value) < 10000).ToList();
```
A bit of explanation to help understand:

I am starting with a text file which has rows of data. Each row has Area Code, City, County, State, etc. There are repeats in all of the columns, so once I draw the original data in, I do a Select().Distinct() on each column to get the distinct values from each column.
I then create separate LiteCollection's for each of the selection results defined by a simple POCO that has two properties, an int Id and a string Value.
Based on this, I create 6 collections named (surprisingly enough) AreaCode, City, County, State, etc., I then create a list of POCO objects for each, and insert them into their respective collections.

This part of the process is working as expected.

I then define a POCO defined as:
```
    internal class ZipCodeData
    {
        public int Id { get; set; }

        [BsonRef(Constants.CityDocuments)]
        public City City { get; set; }

        [BsonRef(Constants.StateDocuments)]
        public State State { get; set; }

        [BsonRef(Constants.ZipDocuments)]
        public Zip Zip { get; set; }

        [BsonRef(Constants.AreaCodeDocuments)]
        public AreaCode AreaCode { get; set; }

        [BsonRef(Constants.FIPSDocuments)]
        public FIPS FIPS { get; set; }

        [BsonRef(Constants.CountyDocuments)]
        public County County { get; set; }
    }
```
I then run through my original text data rows and create a list of ZipCodeData objects by looking up the reference in each of the previous collections I have created.

This works as expected as well. When I open the resulting database in Studio, I see the references to the documents where I expect them.

Where I am experiencing difficulty is when I carry out the query mentioned at the outset. I understood (and was able to accomplish (with v4)) that by using Include, I could get back objects that had the actual document, and not just the reference to the document. When I execute the query, however, each of the Value properties is null.

Is there something that I am doing wrong here?

**Comment by mbdavid** [comment]
Hi @lxman 

If I understand, you are getting this error here (it's commented on unit test)

https://github.com/mbdavid/LiteDB/blob/master/LiteDB.Tests/Database/DbRef_Include_Tests.cs#L154

It's a bug in v5 yet... v4 implementation are not good and I want write a better solution. Will be fixed until final release.

**Comment by lxman** [comment]
Okay, thank you for that.

FYI I am getting around it for now by retrieving each of the individual collections, querying out the references and reconstructing a POCO with that information.

Do you want me to leave this open, or close it?

**Comment by mbdavid** [comment]
Hi Ixman, I will close this because already in my "Project" todo items. Thanks!
