### ISSUE TITLE
Could you tell us when can we get a stable V5 version of LiteDB?

### ISSUE THREAD

**Issue by mrscript21** [mbdavid/LiteDB#1286]

**Comment by mbdavid** [comment]
Hi @mrscript21, there is no fixed date yet. I released alpa version and have plans to release beta before september. Then, I will wait for community do more tests in real-life and get some feedbacks before stable version. This may occurs in 2 or 3 months

**Comment by stephenhauck** [comment]
@mrscript21 , as I am new to LiteDB and coming from another object database can you tell me what features in version 5 you are looking forward to the most so that I can keep them in mind as compared with the current release I am working with ?

**Comment by mrscript21** [comment]
@mbdavid, First of all, thanks for the answer. That could help me for coming schedule how to adopt V5 of LiteDB.

**Comment by mrscript21** [comment]
Hi @stephenhauck.
Well, I am also new to LiteDB but as I found this repo and LiteDB, I was happy to wish to try it.
I could say what I liked from LiteDB.
First is .NET based and even adopted .NET Core newest APIs set such.
Second is just single .dll file to offer db features much attractive point too.
Third as I think, in many cases, local db, and lightweight db such features need to be considered for many applications.
We see SQLite and some others keep going on such purposes.
That is why I really consider to adopt LiteDB but would like to see more improvement with coming V5 release too.
Thanks.

**Comment by JensSchadron** [comment]
v5 also has a more visually appealing tooling called LiteDB.Studio. It's currently only available for Windows, but I'm working on a Mac version as well.

**Comment by JensSchadron** [comment]
I'm going to close this "issue" to make sure we don't lose sight of older reported issues 🙂
