### ISSUE TITLE
Guid without a hyphen on insert ?

### ISSUE THREAD

**Issue by stephenhauck** [mbdavid/LiteDB#1287]
I have a class like so ...
`    public class Customer
    {
        public Customer()
        {
            CustomerServiceLocations = new List<ServiceLocation>();
        }

        public Guid CustomerID { get; set; }
        public string CustomerName { get; set; }
        [BsonRef("customerservicelocations")]
        public List<ServiceLocation> CustomerServiceLocations { get; set; }
    }`

when the guid is generated can I set it to NOT have hyphens like when you generate a new new guid ?

Currently being generated : 2cb54392-e882-49d7-8452-42ca527b6a38
what I would like: 2cb54392e88249d7845242ca527b6a38

Thanks in advance for any help or suggestions

**Comment by mbdavid** [comment]
`Guid` are stored as `byte[16]` as BSON specifications. It's recommend you not convert to string, keeping `Guid` data type all the time. In JSON (string), `Guid` are represent as a sub-document:

`{ "_id": { "$guid": "2cb54392-e882-49d7-8452-42ca527b6a38" } }`

**Comment by stephenhauck** [comment]
ok, thanks
