### ISSUE TITLE
Invalid BSON data type 'Null' on field '_id'

### ISSUE THREAD

**Issue by lxman** [mbdavid/LiteDB#1288]
Working with 4.1.4 here, I have a POCO defined as:
```
    internal class User
    {
        [BsonId(true)]
        internal int Id { get; set; }

        internal string Name { get; set; }

        internal string Password { get; set; }

        internal int UserLevel { get; set; }

        //internal Guid Guid { get; set; }
    }
```

But whenever I create the DB, get the collection and try to insert a new one, I am getting this error. However, I found that if I change all of the internals to public, this works.

Just something to know, that internal properties won't work with LiteDB?

**Comment by mbdavid** [comment]
By default only public member are converted to document. But you can set `BsonMapper.Global.IncludeNonPublic = true`

**Comment by lxman** [comment]
Ah, ok, didn't realize that! Thanks!
