### ISSUE TITLE
Inserting into a referenced document ....

### ISSUE THREAD

**Issue by stephenhauck** [mbdavid/LiteDB#1289]
I have a couple of classes ..
![image](https://user-images.githubusercontent.com/12648793/63129696-3e1b2500-bf86-11e9-9165-293fae4ae709.png)
and
![image](https://user-images.githubusercontent.com/12648793/63129717-4bd0aa80-bf86-11e9-8fd6-05fcd363b0f0.png)

In my code I insert some data, then find the row then try to add an element to the list and when I update it the data is stored in the Customer collection????
I thought the annotation would put the ServiceLocations into a collection named "svcloc" ?
![image](https://user-images.githubusercontent.com/12648793/63129837-9c480800-bf86-11e9-88eb-9442821e5571.png)

I can see it in the viewer .... I expected it to be in a different collection ??
![image](https://user-images.githubusercontent.com/12648793/63129920-dca78600-bf86-11e9-9d71-fb4b3ff016b9.png)

**Comment by kosorin** [comment]
If you look closely at the array you can see something like this:
`[ { $ref: 'svcloc', $key: '1234' } ]`
So you actually didn't insert ServiceLocation to the database.
You must insert ServiceLocation separately
`svclocCollection.Insert(tempServiceLocation);`

**Comment by stephenhauck** [comment]
ok, that worked..... I expected it to add it for me ....
Thanks for the info!
