### ISSUE TITLE
col.EnsureIndex looks bugged

### ISSUE THREAD

**Issue by russosalv** [mbdavid/LiteDB#129]
Hi
Looks that 
`EnsureIndex(x => x.ProcessIdentifier, true);`

is bugged,
i have:

```
public class ProcessTrace
    {
        public ProcessTrace()
        {
            listString = new List<string>();
            ProcessIdentifier = Guid.NewGuid();
            tasked = false;
        }

        public Guid ProcessIdentifier { get; set; }
        public List<string> listString { get; set; } 
        public Object generalfiled { get; set; }
        public bool tasked { get; set; }
        public int howTasked { get; set; }
    }
```

if i run my class (test class) with a cicle that populate the collection

```
using (var db = new LiteDatabase(@"C:\Temp\MyData.db"))
            {
                var col = db.GetCollection<ProcessTrace>("processTrace");

                for (int i = 0; i <= 100; i++)
                {
                    var process = new ProcessTrace()
                    {
                        listString = new List<string>() { "1", "2" },
                        generalfiled = new DataShared.a1_counterlog() { CounterDate = "12333", CounterID = "00091", CounterLogID = "124578", CounterValue = 11.2, DeptID = "1" }
                    };


                    worker.SaveValue();
                    col.Insert(process);

                }
```

then it try to create index using
`col.EnsureIndex("ProcessIdentifier", true);`

the index is created correctly , BUT
if at second instance I comment the for cicle and perform only
`col.EnsureIndex("ProcessIdentifier", true);`

Will be created an extra index but for field tasked

this problem NOT exist if used

`col.EnsureIndex("ProcessIdentifier", true);
`

**Comment by mbdavid** [comment]
Is `ProcessIdentifier` your document `id`? Try set with `[BsonId]` attribute that will auto-create an `_id` field and index when convert to `BsonDocument`. Then you can use `col.FindById`.

**Comment by russosalv** [comment]
Thx works
