### ISSUE TITLE
How to add date condition in SQL command

### ISSUE THREAD

**Issue by sunaccess** [mbdavid/LiteDB#1292]
_SELECT $ FROM ScanList where ScanTime>'{"$date":"2019-07-27T14:20:42.9310000Z"}';_
and
_SELECT $ FROM ScanList where ScanTime>"2019-07-27T14:20:42.9310000Z";_
and
_SELECT $ FROM ScanList;_

**Is the same query result**

![err](https://user-images.githubusercontent.com/4462119/63269144-41851800-c2c8-11e9-9195-1ae24bd86509.jpg)

**Comment by mbdavid** [comment]
Try convert DATE function

```SQL
SELECT $ FROM ScanList where ScanTime > DATE("2019-07-27T14:20:42.9310000Z")
```
