### ISSUE TITLE
Return NetStandard 1.3 support

### ISSUE THREAD

**Issue by Tirraon** [mbdavid/LiteDB#1321]
As described in https://docs.microsoft.com/en-us/dotnet/standard/net-standard NS2.0 is supported only by newer platforms versions. But in real world there are cases, when our applications have to support out of dated platfroms and we can't easelly use NS2.0 libralies.
In my case, I support UWP 14393.0, which allows to use only NS1.4 or lower.

**Comment by Asyvix** [comment]
.net standard 2.0 has included many api. and v5 need that api probably.

**Comment by Tirraon** [comment]
@Asyvix 
See comment from PR https://github.com/mbdavid/LiteDB/pull/1322#issuecomment-534181447
"The main reason to use v2.0 is not valid anymore: FileStream#Lock|Unlock (used in LiteDB v4)."

**Comment by Tirraon** [comment]
PR was merged
