### ISSUE TITLE
What is the DB size we can manage

### ISSUE THREAD

**Issue by sureshk1985** [mbdavid/LiteDB#1327]
We are trying to develop a platform what is the data size it can support.

**Comment by mbdavid** [comment]
Hi @sureshk1985, did you want to know if there is any database file size limit?

**Comment by sureshk1985** [comment]
yes, we need to know how good the database is, size and how many requests it can handle at a time.

**Comment by mbdavid** [comment]
Are you want to use for mobile (Xamarin), games (Unity), desktop apps ou web apps? For windows or other platforms?

**Comment by mbdavid** [comment]
Well, in this case:

- LiteDB has no file size limit, you can grow as large as you want... there is only file system limit (beleave, it's huge).
- About request: the main ideia here is re-use same instance across your web app. In web case you can use IoC with singleton pattern. LiteDB support multi threads.
- Current v5 version support, by default, 100 concurrent transactions... it's a fixed value and in final version will be a external parameter (this number helps do memory initial allocations). I suggest you to do some tests if performance will be as you exptect - in this case need to know how your model / data access will works.

**Comment by sureshk1985** [comment]
Ok, Let we test how LiteDB can support our Applicaiton.

Thank you for your timely response.
Regards
Sureshkumar, K
