### ISSUE TITLE
Saving inherited entities to collection of base class?

### ISSUE THREAD

**Issue by vasiliy-vdovichenko** [mbdavid/LiteDB#133]
I want to keep in the same collection entities which has the same base class.
For instance BaseEntity is base for Entity1 and Entity2, is it possible to save objects of  type Entity1 and Entity2 in the same collection?

**Comment by mbdavid** [comment]
LiteDB is a Document database (not an object database). So, you can insert any document structure (or object type) inside same collection.

The problem will be deserialize this BsonDocument to to your class. If you get a collection with `GetCollection<BaseEntity>(...)` and insert an especialized object from `BaseEntity`, like `Entity1`, serialization will add a field `_t` with your bson document that will be used when deserialize.

**Comment by vasiliy-vdovichenko** [comment]
Thank you for quick reply.

I am trying to implement this approach but LiteDatabase just has generic method for deserializing BsonDocument:

         public T ToObject<T>(BsonDocument doc) where T : new()

but I need deserializing method which takes Type parameter, is there such method?
Of course I can use generic method via reflection and it would be nice to avoid reflection.

I have found that BsonMapper has such method but I couldn't find way to access BsonMapper instance.

**Comment by vasiliy-vdovichenko** [comment]
I have implemented this solution with invoking BsonMapper.Deserialize(Type type, BsonValue value)  via reflection and it works fine.

But it would be nice if you make this method public and also make LiteDatabase.Mapper as public property.

LiteDb is very cool 
Thank you

**Comment by sergiorykov** [comment]
Duplicate issue #71 
Can be closed.

**Comment by mbdavid** [comment]
Hi @vasiliy-vdovichenko, for next version, BsonMapper will be public with a Global instance do be customized by user. Thanks for using!
