### ISSUE TITLE
Question - Immutable models

### ISSUE THREAD

**Issue by rmszc81** [mbdavid/LiteDB#1334]
Hi @mbdavid! (and @everyone)

Long time no see you. how's it going? I hope that everything is fine there in brazil. I'm still in vietnam, maybe when I go brazil see my family I can go there to have a coffee with you, 🍡 

Anyway, today I have another interesting question: **How does LiteDB behave with Immutable models? Is it possible to implement?**

Documentation for older versions says: **"must be parameterless constructor"**. Is this still true?

Please consider the answer of this thread on stackoverflow to understand better what do I mean:

[https://stackoverflow.com/questions/32405383/entity-framework-6-with-an-immutable-class](https://stackoverflow.com/questions/32405383/entity-framework-6-with-an-immutable-class)

As always, thank you very much!

Regards,

[],

@rmszc81

**Comment by mbdavid** [comment]
Hi @rmszc81, nice to see you here again! You are very welcome here for a coffee and code!

Documentation are not done yet for v5, but new version support ctor with parameters - so you can run immutable classes. Take a look on this unit tests:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB.Tests/Mapper/CustomMappingCtor_Tests.cs

Here's how `BsonMapper` decide for which ctor will be used:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Client/Mapper/BsonMapper.cs#L363

[]s

**Comment by VistianOpenSource** [comment]
Hi, following up on this, it would appear that the non-parameterless constructor is only selected if all of the properties are 'built in' to the mapper e.g. not another type which you have in your project which you are also serialising. Is this correct?
