### ISSUE TITLE
Clarification for v5 - single process only?

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#1337]
The v5 blurb says this:

###
What was dropped?
Single process only - optimized for multi thread (open file as exclusive mode)
###

It is a tad confusing, though I suspect that you mean that the file will be locked in the future and can be accessed by a single process only. Can you confirm?

If so, will it be possible for different class instances of LiteDatabase running in the same process to access the file?

**Comment by mbdavid** [comment]
Hi @kuiperzone,

Now, when your first `LiteEngine` instance open data file, this open occurs as exclusive write. No others can open same datafile. This exclusive locks was nedded to support WAL index implementation. Of course, this single LiteEngine support multiple threads access (and are optimized for that).

If you need open same datafile from many different processes (like open in shell + open in you application) you must use `LiteDatabase` with `ConnectionMode = Shared`. This option use a simple "open-read/write-close" `LiteEngine` implementation. It's not optimized becasuse every time you close/open a database, there are read overhead and no cache-reuse.

**Comment by kuiperzone** [comment]
Thanks for the reply David. First of all, let me say that I can understand why you have made locking exclusive and I think it's probably the right choice for LiteDB.

However, your answer doesn't quite answer my question. If I were to write:

var ldb1 = new LiteDatabase("FileName= C:/temp/file");
var ldb2 = new LiteDatabase("FileName= C:/temp/file");

I'm guessing the second one will fail because the first has a full lock and, significantly, the stream instance is NOT shared between the two instances.

This would be fine, but I just wanted to confirm because I will need to make some code changes to support V5 in the future.

Andy

**Comment by mbdavid** [comment]
Hi @kuiperzone, yes, your ldb2 will fail because ldb1 open datafile in exclusive mode. In this case, you need a Singleton pattern do always reuse same ldb1 instance.

**Comment by kuiperzone** [comment]
Thanks and all the best with V5.
