### ISSUE TITLE
What is efficient way to Insert or Update multiple entities

### ISSUE THREAD

**Issue by vasiliy-vdovichenko** [mbdavid/LiteDB#135]
Currently I just iterate through entities and insert or update them one by one

               foreach (var entity in entities)
                {
                    if (!col.Update(entity))
                    {
                        col.Insert(entity);
                    } 
                }

Is there more deficient way to do this?

**Comment by mbdavid** [comment]
Without change your entity, this is the best way. If you can change your entity, you can have a flag with `bool IsNew` or `DateTime? ChangeDate` that you can check if new or existing instance.
