### ISSUE TITLE
how can i use   when  TEntity Get(TKey id)

### ISSUE THREAD

**Issue by gjl8820** [mbdavid/LiteDB#1357]
when i use     v5.0  
 public TEntity Get(TKey id)
  {
       return _collection.FindById(new BsonValue(id));
  }
it is wrong and  show can not  convert  Tkey to int,
in 4.0 it is OK

**Comment by mbdavid** [comment]
v5 removes ctor `new BsonValue(object value)`.

You can use: `BsonMapper.Global.Serialize(id)`
