### ISSUE TITLE
v5 DeleteMany(x=> ids.Contains(x.Id)) 

### ISSUE THREAD

**Issue by zmrhi** [mbdavid/LiteDB#1358]
Hello,

I'm trying to delete many records like this:

var ids = new int[] {1,2,3};
col.DeleteMany(x=> ids.Contains(x.Id)) 

Result only deleted id=1 record.

**Comment by mbdavid** [comment]
Hi @zmrhi, thanks. I fixed this in master branch

**Comment by zmrhi** [comment]
Thanks!

**Comment by zmrhi** [comment]
Another bug when I trying to like this:

var list = new List<int>() { 1, 2, 3 };
col.DeleteMany(x=> list.Contains(x.Id))

Then throw an exception of type 'System.ArgumentOutOfRangeException'

**Comment by zmrhi** [comment]
Hi @mbdavid Another bug when I trying to like this:

var list = new List() { 1, 2, 3 };
col.DeleteMany(x=> list.Contains(x.Id))

Then throw an exception of type 'System.ArgumentOutOfRangeException'

**Comment by mbdavid** [comment]
Hi @zmrhi, it's a complete different bug :smile:

Now, it's about how `List<T>` are converted into `BsonExpression`. Just fix it. Thanks!
