### ISSUE TITLE
Register a custom mapper types globally in v2

### ISSUE THREAD

**Issue by vasiliy-vdovichenko** [mbdavid/LiteDB#136]
In documentation for v1 (https://github.com/mbdavid/LiteDB/wiki/Object-Mapping) there are following description how to register custom type for mapping:

BsonMapper.Global.RegisterType<Uri>
(
    serialize: (uri) => uri.AbsoluteUri,
    deserialize: (bson) => new Uri(bson.AsString)
);

But BsonMapper of v2 doesn't contain Global property.
Is there a way to do register custom class in v2 globally?

**Comment by mbdavid** [comment]
At this point, no (but I will change it). Now mapper are per Database class type.
```
        private static Dictionary<Type, BsonMapper> _mapperCache = new Dictionary<Type, BsonMapper>();

        private void InitializeMapper()
        {
            var type = this.GetType();

            if (!_mapperCache.TryGetValue(type, out _mapper))
            {
                lock (_mapperCache)
                {
                    if (!_mapperCache.TryGetValue(type, out _mapper))
                    {
                        _mapper = new BsonMapper();
                        this.OnModelCreating(_mapper);

                        _mapperCache.Add(type, _mapper);
                    }
                }
            }
        }
```

**Comment by mbdavid** [comment]
Global instance are back in `master` branch :+1:
