### ISSUE TITLE
Is there any way to make a remote database?

### ISSUE THREAD

**Issue by TheBottleCyber** [mbdavid/LiteDB#1362]
Wanted to know if there are plans to add the use of a remote LiteDB server
I see it this way: `using(var db = new LiteRemoteDatabase(ip, port, password, dbName))`

If not, please advise how to do it better using the current version
Thanks for the answer

**Comment by mbdavid** [comment]
YES !!! There is real plans to implement LiteDB Server mode. This release will be next implementation after deliver v5 stable. And API will be better: will use same `LiteDatabase` class (just another constructor and new connection string parameters).  The main idea is that you can switch from embedded database to server database just changing connection string.

LiteDB Server will be a .NET core console app that implement TCP/IP (or REST) protocol to communicate clients (using same LiteDB.dll) to this server (LiteDB.Server.exe).

ps: I want invite you to answer my survey form to understand how devs are using LiteDB, so it's easy to me understand how improve for next versions:

https://docs.google.com/forms/d/e/1FAIpQLSc4cNG7wyLKXXcOLIt7Ea4TlXCG6s-51_EfHPu2p5WZ2dIx7A/viewform

Thanks

**Comment by ADeltsidis** [comment]
Connecting remotely to LiteDB server is definitely a very important feature.
Any estimation about when it will be implemented?
Looking forward for your answer.

**Comment by theoparis** [comment]
Why is this closed? I was looking for a MIT licensed NoSQL database, but this one doesn't have a server mode still 😕
