### ISSUE TITLE
Docker support with LiteDb

### ISSUE THREAD

**Issue by rahulsahay19** [mbdavid/LiteDB#1367]
Hi Team,

Wanted to check whether I can install lite db in docker image alongwith asp.net core. If so, can you provide few examples or samples which I can refer. I tried finding documents around but didn't fine. This is meant for developers machine. 

Thanks,
Rahul

**Comment by GreemDev** [comment]
Well...LiteDB isn't a server. It's a file, managed by *your* code. There shouldn't be an issue with running it in Docker.

**Comment by rahulsahay19** [comment]
Yeah thanks for the response. Figured out this.
