### ISSUE TITLE
Question: V5 Estimated release date, again

### ISSUE THREAD

**Issue by Pokis** [mbdavid/LiteDB#1371]
Hey, 
I appreciate the amazing work David and others are doing towards this project. We love LiteDB very much.
We are currently using V4 extensively in production, we use bare minimum, single tread, few tables, but important data. And we are facing a critical bug on "This is not LiteDB file" error that sometimes pop-up in production and corrupt data of an user. (we have thousands of users per week on windows apps, adding thousands of elements to their local DBs, but error happens like once a week or so) And our management cant hold out much longer. The devs do like LiteDB, and we really hope it's a fixed issue in V5, and we really want to use it. But we're under pressure to move to another DB just because of that (not release ready).

It would be awesome to get +- estimate on the V5 production ready release, so we could have some arguments that we can wait a little bit. I checked some threads, initially i can see estimate was May, then August, now unclear.

TD;DR: 
Any estimate on V5 prod release?

P.s. Once again, we really do appreciate all the work you David and the guys are doing. This software is amazing and we love it.

**Comment by GitOffice** [comment]
I can't  wait for LiteDB V5 with built-in OrderBy feature and  full-text search referred to [this thread](https://github.com/mbdavid/LiteDB/issues/910#issuecomment-365960703) . Migrating data in production from LiteDB V4 to Lucene.Net is a high cost.

**Comment by JensSchadron** [comment]
@Pokis Not sure if it will still be in time, but the v5 release date is currently pinned at the 31st of January. Anyways, I'll be closing this ticket as I'm trying to clean up the issue tracker so we can keep a better overview of what's still relevant and whatnot :)
