### ISSUE TITLE
I have the same problem and I think I know where the problem lies.

### ISSUE THREAD

**Issue by soundarmoorthy** [mbdavid/LiteDB#1375]
I have the same problem and I think I know where the problem lies.
If a collection name exceeds 30 positions, it fails!

Could you please increase the limit of the name, or at least generate some kind of error...

_Originally posted by @ftamminga in https://github.com/mbdavid/LiteDB/issues/554#issuecomment-310664772_

This works like charm. Never thought this could be the issue.

**Comment by mbdavid** [comment]
Hi @soundarmoorthy, this was changed in v5. There is no more collection name limit... and all possible errors in collection creation has better messages:

        public static void CheckName(string name, HeaderPage header)
        {
            if (Encoding.UTF8.GetByteCount(name) > header.GetAvaiableCollectionSpace()) throw LiteException.InvalidCollectionName(name, "There is no space in header this collection name");
            if (!name.IsWord()) throw LiteException.InvalidCollectionName(name, "Use only [a-Z$_]");
            if (name.StartsWith("$")) throw LiteException.InvalidCollectionName(name, "Collection can't starts with `$` (reserved for system collections)");
        }

**Comment by soundarmoorthy** [comment]
Awesome !, Thanks @mbdavid.
