### ISSUE TITLE
Shell Help, Collection Mapping and Dynamic LINQ

### ISSUE THREAD

**Issue by Siegmar** [mbdavid/LiteDB#138]
Hi,

**First of all congratulations for LiteDB.**
I got from ZERO to a working Demo Application in less than an hour.
After using for some time I have only 3 issues about LiteDB:

1) Include "show collections" in the Shell "help" or "help full".
It works but is not shown in the help.

2) Could you include a new maping Method to define the Collection Name ?

```cs
mapper.Entity<Album>()
	.Collection("Artist");
```
	
So it would not be necessary to define the Collection Name in commands like this:

```cs
db.GetCollection<Album>("Album")

.DbRef(x => x.Artist, "Artist")
```

3) Could you create a Where(), OrderBy(), Skip() and Take() methods in your LINQ Library ?
I do use a Dynamic LINQ (https://github.com/kahanu/System.Linq.Dynamic) and so I am able to create (EF) LINQ like this:

```cs
IQueryable<Album> iq = context.Albums
	.Where("AlbumId > @0", 1)
	.OrderBy("Title descending")
	.Skip(10)
	.Take(10);
```
	
A normal (EF) LINQ would look like this:

```cs
IQueryable<Album> iq = context.Albums
	.Where(x => x.AlbumId > 1)
	.OrderByDescending(x => x.Title)
	.Skip(10)
	.Take(10);
```
	
As far as I saw, LIteDB has only a Fund() method.			
I get search parameters as text from JavaScript components, so Dynamic LINQ is necessary

Thanks

**Comment by Siegmar** [comment]
Just to enhance the description of the 3rd issue:

```cs
.Where(Expression<Func<T, bool>> predicate)
.OrderBy(Expression<Func<T, TKey>> keySelector)
.Skip(int count)
.Take(int count)
```

As far as I understood, once this Methods are implemented, Dynamic LINQ goves me the option to use LINQ expressions in text form.

**Comment by Siegmar** [comment]
After some work I found a workaround for Dynamic LINQ:

LINQ

```cs
// WHERE
albumEnumerable = albumCollection
    .Include(x => x.Artist)
    //.Find(x => x.AlbumId > albumId, skip , limit);
    .Find(x => x.AlbumId > albumId);
// ORDER BY
albumEnumerable = albumEnumerable
    .OrderByDescending(x => x.Title)
    .Skip(skip)
    .Take(limit);
foreach (Album x in albumEnumerable)
{
    Console.WriteLine("Id: {0} - Title: {1} - Artist Name: {2}", x.AlbumId, x.Title, x.Artist.Name);
}
```
Dynamic LINQ

```cs
// WHERE
Expression<Func<Album, bool>> where =
    System.Linq.Dynamic.DynamicExpression.ParseLambda<Album, bool>("AlbumId > @0", albumId);
albumEnumerable = albumCollection
    .Include(x => x.Artist) // should be .Include("Artist")
    //.Find(where, skip, limit);
    .Find(where);
// ORDER BY
albumEnumerable = albumEnumerable
    .OrderBy("Title descending")
    .Skip(skip)
    .Take(limit);
foreach (Album x in albumEnumerable)
{
    Console.WriteLine("Id: {0} - Title: {1} - Artist Name: {2}", x.AlbumId, x.Title, x.Artist.Name);
}
```
The only problem I still have, compared to Entity Framework and NHibernate implementations, is that the ".Include()" should accept a string: .Include("Artist").

**Comment by mbdavid** [comment]
Hi @Siegmar, thanks for using and for your contribution. It's really nice to know when some one liked this project.

1) It's implemented in `master` branch. Will be in next version

2) Sounds nice, but I need analyze if it's possible and how do it.

3) Looks nice, but LINQ support is very hard (at least to me - my undersand about this are very basic). Maybe in future I will improve this.

**Comment by Siegmar** [comment]
Thanks for the answer.
Anyway, I found a solution for the ".Include(string)":

```cs
Expression<Func<Album, object>> include = System.Linq.Dynamic.DynamicExpression.ParseLambda<Album, object>("Artist");
Expression<Func<Album, bool>> where = System.Linq.Dynamic.DynamicExpression.ParseLambda<Album, bool>("AlbumId > @0", albumId);
albumQueryable = albumCollection
    .Include(include)
    .Find(where)
    .AsQueryable();
albumEnumerable = albumQueryable
    .OrderBy("Title descending")
    .Skip(skip)
    .Take(limit);
``` 
Dynamic LINQ is really powerfull for dealing with strings.
