### ISSUE TITLE
Obtaining index values in v5

### ISSUE THREAD

**Issue by matelich** [mbdavid/LiteDB#1382]
Hi, just getting started with LiteDB, trying out v5 beta.

If I have a collection of objects with an index on `Name`, how do I get all the `Name`s from the database, rather than all the objects?

Also, do you think v5 will be done within 4 months? Trying to decide if I'm ok to start out on v5 based on the timeline for my project.

Thanks!

**Comment by matelich** [comment]
Guess this is a duplicate of #269 except the fix referenced there no longer seems to exist.

**Comment by mbdavid** [comment]
Hi @matelich, in v5 you can run this query:

`SELECT name FROM customer`

If you have index index `name` field, your query will be run only over index. You can see here (lookup loader uses only index key):

(select with no index)
![image](https://user-images.githubusercontent.com/1137197/70471344-b9f82a80-1aab-11ea-9bc9-251818973011.png)

(after create index)
![image](https://user-images.githubusercontent.com/1137197/70471401-d98f5300-1aab-11ea-9a62-e7b762c12f1e.png)

(but if you add more fields in you query, query engine will return to document lookup loader)
![image](https://user-images.githubusercontent.com/1137197/70471505-0f343c00-1aac-11ea-8206-7ccecababcdf.png)

v5 status: still in beta but I'm working hard to deliver as soon as possible. My plans still release this month, but maybe will I will not deliver new documentation/new site.

**Comment by matelich** [comment]
Excellent, looks like I'd wrap that in a db.Execute().

Thanks for the quick response and the progress on a new version, @mbdavid!
