### ISSUE TITLE
Forward compatibility

### ISSUE THREAD

**Issue by matelich** [mbdavid/LiteDB#1383]
One of the requirements for the application I'm looking at using LiteDb on is forward compatibility. I'm curious is you have any policies about that. 

If I ship v5 for example, will I likely be stuck on v5 forever? Or would you expect a v5 client to be able to read a database created by software using v7?

**Comment by lbnascimento** [comment]
@matelich Sorry for the delay. While datafile formats are not compatible, LiteDB ships with the ability to read older file formats and upgrade them to the latest format. This has happened for the last few versions of LiteDB and we intend to do the same for future versions.

Worst case scenario, the export to JSON functionality could be used to manually migrate collections.

**Comment by matelich** [comment]
@lbnascimento Thanks for getting back to me. I was actually asking about the other direction (old software reading newer databases) which sounds like its definitely not a feature considered valuable (and I don't necessarily think that's a big deal). We'll just make sure to understand long term that this the case and discuss whether we want a JSON import/export feature.
