### ISSUE TITLE
How to explore a v4 database ?

### ISSUE THREAD

**Issue by Fangh** [mbdavid/LiteDB#1387]
Hello.

I did not find in the wiki how to explore my database ? I use Visual Studio code and I get used to the plugin Azure Cosmos DB which let you explore a MongoDB database.

I know there is DBLite Studio for v5. I tried to use it for v4 but it corrupted my DB so I think it's because it's only for v5.

TL;Dr Is there some command line or GUI plugin to explore the .db ?

Thank you.

**Comment by JensSchadron** [comment]
Hi @Fangh,
Your database wasn't really corrupted, but rather "upgraded" to the new datafile format for the v5 of LiteDB. However, the v4 doesn't know how to read the file, therefor indicating it like it had been corrupted.

The [v4 release on github](https://github.com/mbdavid/LiteDB/releases/tag/v4.1.4) also contained a shell application which could be used to explore your database.
If you like graphical applications more than CLI based tools to explore your database, there are a few 3rd party projects on Github as well. I, personally, use this [one ](https://github.com/julianpaulozzi/LiteDbExplorer), but there are probably others as well.

Assuming that this answers your question, I'm going to close this tickets so I can slowly clean up the issue tracker. If you've more questions related to this, feel free to re-open it :)
