### ISSUE TITLE
some questions about the Probability of SkipList

### ISSUE THREAD

**Issue by luckymark** [mbdavid/LiteDB#1391]
Do you test another probability value (such as 1/4 rather than 1/2) for SkipList? 

In this paper : [https://epaperpress.com/sortsearch/download/skiplist.pdf](https://epaperpress.com/sortsearch/download/skiplist.pdf) , William Pugh suggest: 

>  Since some of the constant overheads are related to L(n) (rather than L(n)/p), choosing p = 1/4 (rather than
1/2) slightly improves the constant factors of the speed of the
algorithms as well. I suggest that a value of 1/4 be used for p
unless the variability of running times is a primary concern, in
which case p should be 1/2.

ps: I really really like LiteDB,great lib,thank you very much!

**Comment by JensSchadron** [comment]
Hi @luckymark 

I started adding a BenchmarkDotNet project last night. When I've progressed a bit further with the initial setup, we can possibly add some benchmarks to see the difference between the different probability values.
