### ISSUE TITLE
question: how does litedb project to the right sub types?

### ISSUE THREAD

**Issue by MHDuke** [mbdavid/LiteDB#1393]
first of all thank you for the great library. 
I have a dbLite collection of ITimeFramePolicy, i populate it with several different sub type instances. when i query that collection how does it project back to the correct types!

```
public interface ITimeFramePolicy
    {
        string Type { get; }
    }

public class DateRangePolicy : ITimeFramePolicy
    {
        public string Type => "date.range";
        public DateTime StartDate { get; private set; }
        public DateTime EndDate { get; private set; }
    }

public class DaysOfWeekPolicy : ITimeFramePolicy
    {
        public string Type => "days.of.week";
        public IEnumerable<DayOfWeek> Days { get; private set; }
    }
```
as you can see I added the `string Type{ get; }` there, but ended up not using it! how do you do it? :)

**Comment by mbdavid** [comment]
Are you storing this 2 types in different collections? How did you get `GetCollection`?

If you use `GetCollection<ITimeFramePolicy>` to use same collection for both types, each document will contains `_type` to store concrete class

**Comment by MHDuke** [comment]
i actually store them in single collection. i decided to add the `string Type` property, and later on try to figure out will i cast back to concrete types, just to find out it is working out of the box. so i came here to appreciate the smooth experience. thank you :+1: and to learn how did you do it.

**Comment by lbnascimento** [comment]
@MHDuke Sorry about the delay. `_type` is used to store the name of the concrete class for each document in a collection. If a type is renamed or deleted, you'll have issues. In such cases, it is recommended to open the collection in an untyped manner and manually changing the `_type` attribute.

In case you're using your project with many different datafiles, you can use the USER_VERSION pragma to control whether a particular datafile needs the manual changing of the `_type` attribute or not (for more info, check the [Pragmas documentation](http://www.litedb.org/docs/pragmas/)).
