### ISSUE TITLE
IDs are required (but should they always be?)

### ISSUE THREAD

**Issue by JordanMarr** [mbdavid/LiteDB#14]
In my comparison of small nosql database, one difference I found is that LiteDB requires an ID field, whereas some of the others (like NDatabase) do not.  

For many cases I can see why an ID would be required. 
However, consider my current scenario where I want to store a list of records that I will never need to pull individual via a unique ID field: 
The properties for my entity are "ProjectURL", "Title", and "Filename".  
In this case, none of these fields are unique identifier candidate, but that should be OK because my use case dictates that I will only ever need to query multiple record results via the "ProjectURL" property.  So I should be able to call "EnsureIndex(x => x.ProjectURL)" and be done.  
However, LiteDB throws an exception because I do not have an ID!

Now I know that I could work around this problem by adding a GUID ID property that is generated in the entity constructor, but I would prefer to not let a 3rd party library drive my domain design.  

So my question is this:  Is it absolutely necessary for LiteDB to REQUIRE an ID / PrimaryKey field at all?  Could this be made to be optional?  If it were optional, then you could move the check and exception into the "FindById" function (since this function obviously depends on the fact that an ID has been specified previously). 

Thanks,
Jordan

**Comment by mbdavid** [comment]
Hi Jordan, thanks for your interesting in LiteDB.

LiteDB requires an ID because it's primary unique index, used when update a document. Documents can only be founded in they have at least one index. By default, LiteDB uses Id for this first index.

BUT, I'm working in v.1.0 of LiteDB and in this new version it was not required. Why? Because if you didn't have an Id attribute, LiteDB will add automatic in insert an `ObjectId` as `_id`, as MongoDB do.

**Comment by JordanMarr** [comment]
That sounds like a great solution!  How far off is the 1.0 release?

**Comment by mbdavid** [comment]
It's near. I guess less than a month. I need only validate better source, do more tests and finish wiki documentation. Source are in `dev` branch if you want testing...

**Comment by caverna** [comment]
Please check at: UnitTest.AutoIdTest.AutoId_Test(), line 60.

Test method UnitTest.AutoIdTest.AutoId_Test threw exception: 
System.InvalidCastException: Conversão especificada não é válida.
    em LiteDB.BsonMapper.<.ctor>b__a(LiteCollection`1 c) na BsonMapper.cs: line 98
   em LiteDB.BsonMapper.<>c__DisplayClass1b`1.<RegisterAutoId>b__1a(LiteCollection`1 c) na BsonMapper.cs: line 125
   em LiteDB.BsonMapper.SetAutoId(Object poco, LiteCollection`1 col) na BsonMapper.cs: line 154
   em LiteDB.LiteCollection`1.Insert(T document) na Insert.cs: line 16
   em UnitTest.AutoIdTest.AutoId_Test() na AutoIdTest.cs: line 60

Wich is:
return (Int32)value.RawValue;

And value.RawValue is: "-oo"(string)

**Comment by JordanMarr** [comment]
The 1.0 dev branch seems to have resolved my issue.  I am now able to insert my objects without specifying an ID property.  

Also, I like that you renamed LiteEngine to LiteDatabase, and I also like that you renamed All() to FindAll().

**Comment by mbdavid** [comment]
Thanks! Fixed

On Thu, Mar 19, 2015 at 1:19 PM, Carlos Alberto Nunes <
notifications@github.com> wrote:

> Please check at: UnitTest.AutoIdTest.AutoId_Test(), line 60.
>
> Test method UnitTest.AutoIdTest.AutoId_Test threw exception:
> System.InvalidCastException: Conversão especificada não é válida.
> em LiteDB.BsonMapper.<.ctor>b__a(LiteCollection1 c) na BsonMapper.cs:
> line 98
> em LiteDB.BsonMapper.<>c__DisplayClass1b1.b__1a(LiteCollection1 c) na
> BsonMapper.cs: line 125
> em LiteDB.BsonMapper.SetAutoId(Object poco, LiteCollection1 col) na
> BsonMapper.cs: line 154
> em LiteDB.LiteCollection`1.Insert(T document) na Insert.cs: line 16
> em UnitTest.AutoIdTest.AutoId_Test() na AutoIdTest.cs: line 60
>
> Wich is:
> return (Int32)value.RawValue;
>
> And value.RawValue is: "-oo"(string)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbdavid/LiteDB/issues/14#issuecomment-83648423>.
>



-- 
  Maurício David
