### ISSUE TITLE
Question: Can you perform an update without loading the entire document first

### ISSUE THREAD

**Issue by isaacabraham** [mbdavid/LiteDB#1405]
Does LiteDB support update of a document (including potentially adding fields) to a document without loading the entire document into memory first?

I had a look at the documentation and tried performing two updates on the same document (with different shapes) in the same collection but the behaviour seems to be "last one wins".

Thanks

**Comment by lbnascimento** [comment]
Hello!

LiteDB v5 RC currently supports it with the SQL syntax:

```C#
db.Execute("update Person set Age = $.Age * 2 where _id = 1"); //field Age is updated, other fields are unchanged
```

In the v5 release, it will also be possible to update only certain fields with the `collection.UpdateMany` method.

**Comment by isaacabraham** [comment]
Great. I'll have an eye out for that then. Thanks!

**Comment by picolino** [comment]
@isaacabraham  I'm facing the same issue right now, and at the current version can't understand how to update some fields in the document through that expressions. LiteDatabase neither LiteCollection don't have `Execute` method anymore and docs says nothing about that :C
