### ISSUE TITLE
v4.1.4 Datafile is not a LiteDB database.

### ISSUE THREAD

**Issue by kube1206** [mbdavid/LiteDB#1406]
dear mbdavid,
when I open the lite database with the litedb studio.exe,and closed it,it happend when I am running the project.
detail:
GetLatestBlockAsyncTest
   源: LiteDbStoreTest.cs 行 201
   持续时间: 81 毫秒

  消息: 
    LiteDB.LiteException : Datafile is not a LiteDB database.
  堆栈跟踪: 
    HeaderPage.ReadContent(ByteReader reader)
    BasePage.ReadPage(Byte[] buffer)
    LiteEngine.ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
    <.ctor>b__0()
    LazyLoad`1.get_Value()
    LiteCollection`1.Find(Query query, Int32 skip, Int32 limit)+MoveNext()
    EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
    Buffer`1.ctor(IEnumerable`1 source)
    OrderedEnumerable`1.ToList()
    Enumerable.ToList[TSource](IEnumerable`1 source)
    LiteDbStore.<GetLatestBlockAsync>b__6_0() 行 40
    Task`1.InnerInvoke()
    ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
    Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
    --- End of stack trace from previous location where exception was thrown ---
    LiteDbStore.GetLatestBlockAsync() 行 35
    LiteDbStoreTest.GetLatestBlockAsyncTest() 行 203
    GenericAdapter`1.BlockUntilCompleted() 行 95
    AsyncToSyncAdapter.Await(Func`1 invoke) 行 60
    TestMethodCommand.Execute(TestExecutionContext context) 行 64

**Comment by JensSchadron** [comment]
Hi @kube1206 

LiteDB Studio is program written for LiteDB v5 and it converts old databases to a newer format when opening. The problem that you stumbled upon is that v4.1.4 doesn't know how to read the new dataformat.

**Comment by JensSchadron** [comment]
I'm going to close this ticket as I think this answers your question. If you aren't satisfied with the answer, feel free to re-open this ticket.
