### ISSUE TITLE
System.ArgumentOutOfRangeException: 'Positive number required. (Parameter 'culture')'

### ISSUE THREAD

**Issue by Craftplacer** [mbdavid/LiteDB#1407]
I have LiteDB 5.0.0-rc on .NET Core 3.0 crashing when using LiteDatabase.GetCollection<>().FindById(string) with following stack trace:
```
This exception was originally thrown at this call stack:
	System.Globalization.CultureInfo.GetCultureInfo(int)
	LiteDB.Collation.Collation(int, System.Globalization.CompareOptions)
	LiteDB.Engine.EnginePragmas..ctor.AnonymousMethod__36_7(LiteDB.BufferSlice)
	LiteDB.Engine.EnginePragmas.EnginePragmas(LiteDB.BufferSlice, LiteDB.Engine.HeaderPage)
	LiteDB.Engine.HeaderPage.LoadPage()
	LiteDB.Engine.HeaderPage.HeaderPage(LiteDB.Engine.PageBuffer)
	LiteDB.Engine.LiteEngine.LiteEngine(LiteDB.Engine.EngineSettings)
	LiteDB.ConnectionString.CreateEngine()
	System.Lazy<T>.ViaFactory(System.Threading.LazyThreadSafetyMode)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    ...
    [Call Stack Truncated]
```

This issue did not occur before upgrading LiteDB to 5.0.0.

**Comment by mbdavid** [comment]
Hi, are you using datafile created by alpha/beta version? If true, RC (and final release) will be not compatible because datafile was changed (file structure was changed to fix a critical bug)

**Comment by Craftplacer** [comment]
Could be the case, I recently reinstalled Visual Studio and restored and upgraded packages first, it seems like I have to start off clean then.

**Comment by JensSchadron** [comment]
@Craftplacer I think that this "issue" is resolved then? If so, could you please close this ticket as I'm trying to tidy up the issue tracker to make it more manageable :)
