### ISSUE TITLE
Exception: Unable to cast object while getting collections

### ISSUE THREAD

**Issue by 3HMonkey** [mbdavid/LiteDB#1408]
Hi guys,

I am really new to this database but I also really like it so far. BTW while implementing LiteDB to our project, the following issue came up.

Lets say we have a struct called Point2D. It has some internal variables which doesn't matter here, but also 2 public variables called "X" and "Y". We are using no ID here because we cannot change the struct (third-party). => Auto-ID

Something like:
```CSharp
public struct Point2D 
{
   public int X;
   public int Y;
}
``` 

I am filling the table/collection in this way (as an example), which is working fine so far:
```CSharp
using (var db = Database.Instance)
      {
        var results = db.GetCollection<Point2D>("mytable");

        foreach (var item in collection)
        {
          Point2D pnt = new Point2D(item.x, item.y);
          results.Insert(pnt);
        }
      }
``` 

After connecting to the DB using a LiteDBViewer/Studio here is the expected output(?):
![grafik](https://user-images.githubusercontent.com/4610892/72807545-f0eb5f80-3c57-11ea-9ae8-b9386994ee70.png)

Now we are going to programmically query this to print out the Content:
```CSharp
try
      {
        using (var db = Database.Instance)
        {
          var results = db.GetCollection<Point2D>("mytable");

          foreach (var result in results.FindAll())
          {
            //Point2D pnt = new Point2D(result.X, result.Y);  METHODE 1
            //Console.WriteLine(pnt.ToString()); METHODE 1
            Console.WriteLine(result.ToString()); //METHODE 2 Because result is already type of Point2D
          }
        }
      }
      catch (LiteException ex)
      {
        throw ex;
      }
``` 

Now I got an exception because of this line:
```CSharp
var results = db.GetCollection<Point2D>("mytable");
``` 

Here is the stacktrace:
![grafik](https://user-images.githubusercontent.com/4610892/72808205-58ee7580-3c59-11ea-9ab7-c88049f33c64.png)

This problem is new to me.  Maybe you guys have a solution because it is already working with other classes.

Greetings

**Comment by lbnascimento** [comment]
Hello!

There was an issue when dealing with structs, which was fixed in the last commit. Also, your struct uses attributes instead of properties, and the fluent mapper only maps properties by default. You can override this behavior with the command

```C#
BsonMapper.Global.IncludeFields = true;
```

**Comment by 3HMonkey** [comment]
@mbdavid Is this already available on nuget? Or do I need to compile it myself? BTW thank you really much.

**Comment by mbdavid** [comment]
Hi @3HMonkey, no, only in master branch. My idea is release next nuget only in jan/31 with final v5 release.

**Comment by 3HMonkey** [comment]
> Hi @3HMonkey, no, only in master branch. My idea is release next nuget only in jan/31 with final v5 release.

Great, glad to hear that. I gonna implement it in other classes meanwhile until the release. And again, good job with this DB.

**Comment by JensSchadron** [comment]
Given that the issue has already been resolved in the master branch and it will be released in the next NuGet release, I'll close the ticket. Feel free to reopen the ticket if you still have question regarding this ticket. 🙂
