### ISSUE TITLE
Problem/Solution for "where T : new()"

### ISSUE THREAD

**Issue by zig-github** [mbdavid/LiteDB#141]
HI @mbdavid,
I have used LiteDB as an example for my current Unit of Work and Repository pattern implementation, beside Entity Framework and NHibernate.
After some minor problems, It worked perfectly but I had to make a small change in yout code.

Using version 2rc I get the following error for the code below:

Error CS0310
'TEntity' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'T' in the generic type or method 'LiteCollection<T>'	ZPersistenceLiteDB

```cs
public LiteCollection<TEntity> Collection
{
	get { return Database.GetCollection<TEntity>(typeof(TEntity).Name); }
}
```
To get rid of this problem, I just removed the "where T : new()" from 4 methods in your code:

```cs
public sealed partial class LiteCollection<T>
	//where T : new()
	
public partial class LiteDatabase : IDisposable
{
	public LiteCollection<T> GetCollection<T>(string name)
		//where T : new()

public partial class LiteDatabase : IDisposable
{
	public T ToObject<T>(BsonDocument doc)
		//where T : new()

public partial class BsonMapper
{
	public T ToObject<T>(BsonDocument doc)
		//where T : new()
```

I made some CRDU tests and they worked perfectly.
I am not sure why did you include it in your code, but, please, considerer removing it.
Thanks

**Comment by Dessix** [comment]
This is a factor that prevents me from straight-up encoding of certain value types, leading to custom serialization wrappers everywhere. +1
