### ISSUE TITLE
Upsert Returns False on Update

### ISSUE THREAD

**Issue by henzard** [mbdavid/LiteDB#1410]
Var _collection.Upsert(newItem) returns true, _collection.Upsert(item) doing a update returns false
I am expecting a false on no action

**Comment by lbnascimento** [comment]
Hello!

Upsert returns true if it performs an insertion and false if it performs an update.

The documentation is being reviewed for v5.

**Comment by JensSchadron** [comment]
Marked this ticket as duplicate as this "issue" is a duplicate of #1388. To keep the issue tracker a bit more manageable, I'll be closing this ticket.
