### ISSUE TITLE
'FileMode' does not contain definition for 'Shared'

### ISSUE THREAD

**Issue by DavidSanschagrin** [mbdavid/LiteDB#1414]
Good day!

We have a compilation error when trying to compile in Release:
"'FileMode' does not contain definition for 'Shared'"

When I look at the source code, I see that there is a conditionnal compilation with "HAVE_LOCK".

    public enum FileMode
    {
#if HAVE_LOCK
        Shared,
#endif
        Exclusive,
        ReadOnly
    }

To fix the situation, do we simply have to add the conditionnal compilation symbol "HAVE_LOCK" or is there more to it? Are there other symbols that we should know about?

To give more context: We have problems with the LiteDB file getting locked when we execute our code in acceptation environment. We suspect that it defaults to "Exclusive" rather than "Shared".

**Comment by lbnascimento** [comment]
In LiteDB v4, the method `FileStream.Lock` is used to lock the file when it is being written to. However, NET Standard 1.3 does not implement the method, so the Shared mode is not available for NET Standard 1.3.

LiteDB v5 works around this issue by opening a FileStream for an operation and immediately closing it when the operation is done.

**Comment by DavidSanschagrin** [comment]
We found our problem. It was just a case of lost compilation parameters. It works now.
