### ISSUE TITLE
How to save base version of objects in collections.

### ISSUE THREAD

**Issue by darcome** [mbdavid/LiteDB#1417]
Hi all, 
Here is an example of what I have in code and what I'd like to happen:
I have the following property in my object:

public List<Animal> Animals {get;set;} = new List<Animal> ();

and then the following objects get added to it:

Animals.Add (new Dog ());
Animals.Add (new Cat ());

In the database, the objects of the list are saved as Dog and Cat objects, with their properties.

How can I get them saved as Animal objects?

Thanks in advance

**Comment by lbnascimento** [comment]
@darcome I'm assuming that `Cat` and `Dog` are subtypes of `Animal`.

In this situation, I don't understand what's the issue with storing the objects with their real types. For all intents and purposes, every instance of `Cat` and `Dog` is an instance of `Animal` and can be used anywhere an instance of `Animal` is expected. You can always cast it to `Animal` if you really want to treat it as an instance of the base class.

**Comment by darcome** [comment]
After your answer, I began to think about my code and probably I asked the question because I am still too used to RDBMS and it's difficult to think in terms of NoSQL.

Thank you very much!

I'll close this issue!
