### ISSUE TITLE
disable Id auto order when id is string

### ISSUE THREAD

**Issue by mabezat** [mbdavid/LiteDB#1418]
Hi David, Hi everyone,
Thanks for this amazing framework , i have a problem i don't know if there is solution for it or no,
I have a collection named Products with a product_Id as a string , whenever i insert a new product , there is an auto order , i hope the image explains this more.
![screentemp](https://user-images.githubusercontent.com/4215602/73283274-29101680-41f3-11ea-953f-f6126554ed08.png)

i want the item with index Pct0010 to be in the last position

Thanks again

**Comment by lbnascimento** [comment]
@mabezat Which version of LiteDB are you using?

**Comment by mabezat** [comment]
I am using version 4

**Comment by lbnascimento** [comment]
You can simulate this behavior on retrieval ordering the results by the length of the field and then by the value.

```C#
var result = col.FindAll().OrderBy(x => x.Id.Length).ThenBy(x => x.Id);
```

**Comment by mabezat** [comment]
@lbnascimento  thanks bro , that helped a lot , this is what i needed

`var orderedCollection = col.FindAll().OrderBy(x => x.Product_Id.Length).ThenBy(x => x.Product_Id).Last<Product>().Product_Id;`
