### ISSUE TITLE
Deserialize Internal Properties

### ISSUE THREAD

**Issue by windischb** [mbdavid/LiteDB#142]
Hi!

I have Problems with deserialize a class which has internal properties.
I can't use the Bsonfield Attribute because the class is declared in a 3rd party library.
Insert in database is working without any problems, but on the Find method all internal properties have there default values...
Is there any Solution for this Problem?
Maybe a custom deserializer or something?

**Comment by Dessix** [comment]
I'd very much love to see custom serializers supported, as Json.Net is already used as the root of all (de)serialization throughout my project.

**Comment by mbdavid** [comment]
Hi @windischb, in this case you can use RegisterCustomType. Take o look here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Serializer/Mapper/BsonMapper.cs#L67

You can use mapper class overriting `LiteDatabase.OnModelCreating(BsonMapper mapper)`

If you type will be in a direct in a collection (like `var col = db.GetCollection<MyExternalClass>("...")`), remeber to map an `_id` field with you identification property.
