### ISSUE TITLE
Add Pragma enums

### ISSUE THREAD

**Issue by JensSchadron** [mbdavid/LiteDB#1426]
I think it might be nice to add an additional overload to the Pragma() method that accepts an enum value for the pragma key instead of a string.
Users can benefit from this because their IDE can assist them in giving suggestions for the pragma keys and as an additional bonus, the users don't need to define magical string constants.

I can create a pull request for it if you want me to.

**Comment by Tirraon** [comment]
Or a class with constant strings for build in pragmas.

**Comment by JensSchadron** [comment]
I don't mind either suggestion. If you guys feel like a class with string constants is the better idea, then I'll implement it that way.
