### ISSUE TITLE
FindById leaves open cursors on transaction

### ISSUE THREAD

**Issue by clooudch** [mbdavid/LiteDB#1427]
It seems like the 'FindById' operation on the database (and potentially other operations as well), leave an open cursor on the transaction.

This can easily be reproduced. Just begin a transaction on the database and run a 'FindById' operation on a collection. You will see that you can not commit the transaction as it still contains open cursors.

I think this has something to do with the combination of 'FirstOrDefault' and IEnumerable functions. My guess is that the cursor will only be returned after the enumerator completed and 'FirstOrDefault' will stop the enumerator after the first element.

**Comment by clooudch** [comment]
Will leave an open cursor on the transaction (as the enumeration never completes):
```collection.FindById(id);```

Will NOT leave an open cursor on the transaction (as the enumeration completes):
```collection.Find(x => x.Id == id, skip: 0, limit: 1).ToArray().FirstOrDefault();```

**Comment by clooudch** [comment]
https://github.com/mbdavid/LiteDB/blob/055f47d074d0a6f5da756a30cee817436c2f27eb/LiteDB/Engine/Engine/Transaction.cs#L38

This line currently stops you from running an 'FindById' operation inside of a transaction.

**Comment by lbnascimento** [comment]
@clooudch Could you test it with v5.0.1?

**Comment by OrkanCom** [comment]
Due to my tests, I can confirm that v5.0.1 fixed the problem. Thanks.
