### ISSUE TITLE
System.IndexOutOfRangeException when query index

### ISSUE THREAD

**Issue by Lupinho** [mbdavid/LiteDB#1429]
Sometimes I get this exception when I query my db by one of 4 indexes on a collection of a simple database. It only occurres on stress tests on final v5.0 LiteDB.

System.IndexOutOfRangeException
   at LiteDB.Engine.IndexService.Find(CollectionIndex index, BsonValue value, Boolean sibling, Int32 order)
   at LiteDB.Engine.IndexEquals.<Execute>d__3.MoveNext()
   at LiteDB.Engine.BasePipe.<LoadDocument>d__6.MoveNext()
   at LiteDB.Engine.BasePipe.<Filter>d__8.MoveNext()
   at LiteDB.Engine.QueryPipe.<Select>d__2.MoveNext()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass10_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader..ctor(IEnumerable`1 values, String collection)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery()
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
   at LiteDB.LiteQueryable`1.<ToDocuments>d__26.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)

**Comment by mbdavid** [comment]
Hi, can you provide a full example to inspect whats going on?

**Comment by Lupinho** [comment]
I can try to build some. It must be a multi-threading issue. When I do updates/inserts in one thread and do a query in another on the same collection, this error occurres. At this time I try to prevent this situation. If I've git time I try to build an example from scratch...

**Comment by lbnascimento** [comment]
@Lupinho Could you test it with v5.0.1?

**Comment by Lupinho** [comment]
I tried to recreate the error situation. I have to say, that I became sometime the error above (System.IndexOutOfRangeException) or "Invalid IndexPage buffer" (there is another issue #1374  for this). I could easily reproduce the later error, also with Version 5.0.1:
LiteDB.LiteException
  HResult=0x80131500
  Message=Invalid IndexPage buffer on 494
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

  This exception was originally thrown at this call stack:
	LiteDB.Engine.IndexPage.IndexPage(LiteDB.Engine.PageBuffer)
	LiteDB.Engine.IndexService.Find(LiteDB.Engine.CollectionIndex, LiteDB.BsonValue, bool, int)
	LiteDB.Engine.IndexEquals.Execute(LiteDB.Engine.IndexService, LiteDB.Engine.CollectionIndex)
	LiteDB.Engine.BasePipe.LoadDocument(System.Collections.Generic.IEnumerable<LiteDB.Engine.IndexNode>)
	LiteDB.Engine.BasePipe.Filter(System.Collections.Generic.IEnumerable<LiteDB.BsonDocument>, LiteDB.BsonExpression)
	LiteDB.Engine.BasePipe.Filter(System.Collections.Generic.IEnumerable<LiteDB.BsonDocument>, LiteDB.BsonExpression)
	LiteDB.Engine.QueryPipe.Select(System.Collections.Generic.IEnumerable<LiteDB.BsonDocument>, LiteDB.BsonExpression)
    ...
    [Call Stack Truncated]

My test case inserts many documents in bunches into the db. When I do this asynchronously in another thread and do a query while this is going on, this error occurres (and sometimes the other error). I try to build a simple test, if I get time for this. 
Thanks for your support!

**Comment by Lupinho** [comment]
Here is a simple Unit-Test to reproduce the "Invalid IndexPage buffer" error:` 

	[TestClass]
	public class LiteDBBugTest {
		public class Data {

			[BsonId]
			public ObjectId Id { get; set; }
			public string Name { get; set; }

			public string Index {
				get { return GetIndex(Name); }
			}
			public static string GetIndex(string name) {
				if (name == null) {
					return null;
				} else {
					byte[] hash = new SHA256Managed().ComputeHash(Encoding.Unicode.GetBytes(name.ToLowerInvariant()));
					StringBuilder str = new StringBuilder();
					foreach (byte num in hash) {
						str.Append(num.ToString("x2"));
					}
					return str.ToString();
				}
			}
		}
		[TestMethod]
		public void Test() {
			string tmp = System.IO.Path.GetTempFileName();
			File.Delete(tmp);
			const int MAX_DATA = 1000000;
			const int MAX_CACHE = 10000;
			ConnectionString conf = new ConnectionString(tmp);
			conf.Password = "1234567890";
			using (LiteDatabase db = new LiteDatabase(conf)) {
				ILiteCollection<Data> dataCol=db.GetCollection<Data>("data");
				dataCol.EnsureIndex(x => x.Index);
				Random rnd=new Random();
				List<Data> cache=new List<Data>();
				Task flushTask = null;
				for (int i = 0; i < MAX_DATA; i++) {
					cache.Add(new Data(){
						Name="Name_"+i.ToString("D8")
					});
					if (cache.Count > MAX_CACHE) {
						List<Data> fcache = cache;
						cache=new List<Data>();
						if (flushTask != null) {
							flushTask.Wait();
						}
						flushTask=Task.Factory.StartNew(() => {
							db.BeginTrans();
							dataCol.Insert(fcache);
							db.Commit();
						});
					}
					dataCol.Query().Where(x => x.Index == Data.GetIndex("Name_" + rnd.Next(0, MAX_DATA).ToString("D8"))).ToList();
				}
				if (flushTask != null) {
					flushTask.Wait();
				}
			}
		}
	}
`

**Comment by mbdavid** [comment]
This insert thread, are you using explicit transaction, insert as array of documents or insert one by one? Is this document too big or have any special type of something?

I do many test using this scenario and got error only in alpha e beta version (and I fix in RC). I will publish in another repo this tests so we can do any test there

**Comment by Lupinho** [comment]
I think the error occurred with or without explicit transactions. The document I work with is very simple and normally not big. It consists of some strings, a long, an enum, a DataTime and a Id. Nothing special. I put 3 indexes o calculated properties as strings. I splitted away an array of Guid's in an own document, which is referred via BsonRef; because I realized that updating the main document took a lot of time by updating the indexes. Only updating the referenced document seemed to be faster.
But even if my real setting is a bit more complicated you should be able to reproduce the example above to run into the error.

**Comment by mbdavid** [comment]
Hi @Lupinho, I found this problem and fix in current master branch. Can you please test again? I will release this fix in next release

**Comment by Lupinho** [comment]
Yes! At least now my test does not run into errors anymore. Tested with and without extra transaction. Also my other use-case seems to behave now errorless!
Thanks alot!
