### ISSUE TITLE
One to Many DbRef association

### ISSUE THREAD

**Issue by idansh** [mbdavid/LiteDB#143]
How to create DbRef many to one. 

I have classes for both `Customer` and `Job`. I want the Customer to store a list of jobs that the Customer has.

So in the Customer class, I need to have a` DbRef<Job> Jobs` ? Furthermore, DbRef is not recognized as a type with `using LiteDB`.

**Comment by mbdavid** [comment]
Hi @idansh, using v2.0rc you can use `List<Job> Jobs` on `Customer` class. After, use DbRef to map. Take a look here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB.Tests/Mapping/IncludeTest.cs#L14

**Comment by idansh** [comment]
Where in that example I specify the database location. In my code when I used the version one code I used:   `using (var db = new LiteDatabase(System.AppDomain.CurrentDomain.BaseDirectory + @"MyData.db")) `, but in the example you referred me to it shows:

 ```
public class IncludeDatabase : LiteDatabase
    {
        public IncludeDatabase()
            : base(new MemoryStream())
        {
        }
```
If I create my own IncludeDatabase class, where I specify the database name and location?

Thanks.

**Comment by mbdavid** [comment]
At this time (I have plans to change) you can only use an derived class. So you class must be:

```
public class MyDatabase : LiteDatabase
{
    public MyDatabase(string conn) : base(conn) { }

    protected override void OnModelCreating(BsonMapper mapper)
    {
        mapper.Entity<Order>()
            .DbRef(x => x.Products, "products");
    }
}

using(var db = new MyDatabase(System.AppDomain.CurrentDomain.BaseDirectory + @"MyData.db"))
{
    ....
}
```
