### ISSUE TITLE
Invalid LCID Code

### ISSUE THREAD

**Issue by fastlink30** [mbdavid/LiteDB#1430]
Blazor
vs2019 v16.4.4

update from 5.0alpha2 to 5.0

connection string "Filename=database.db;Upgrade=true;Mode=Shared"

when i try to open (new LiteDatabase()) exception 'Invalid LCID code'
the same happen if i try to open with LiteDB.Studio 1.0.0.0 with the previous version i use (0.5) nothing happen

**Comment by JensSchadron** [comment]
@fastlink30 The dataformat changed between the 5.0.0-beta and the 5.0.0-RC and it is completely incompatible, so you need to recreate your database file.

**Comment by phischepi** [comment]
Hi, I faced the same issue. Is there a way to migrate the database to the new format?

**Comment by fastlink30** [comment]
as phischepi there a way to migrate the database? i hope yes, my database is not so small and recreate all is impossible

**Comment by mbdavid** [comment]
Hi @fastlink30, your database was created with v5 alpha/beta version?

**Comment by fastlink30** [comment]
i not remember, probably with a previous version
i think you want say, open the 'old' db with vs 5alpha and write datas to new db + vs5.0
yes, sure is possible, but i must loose much time to do this, if is transparent the 'upgrade' sure is better

**Comment by mbdavid** [comment]
If you open your datafile with LiteStudio 0.5.2 you can easy export your collections data as JSON files. And than, open LiteStudio 1.0.1 and import as JSON file:

To export (in 0.5.2):
`SELECT $ INTO $file_json('c:/data/col1.json') FROM col1;`

To import (in 1.0.1)
`SELECT $ INTO col1 FROM $file('c:/data/col1.json')`

**Comment by fastlink30** [comment]
thanks, this solved

**Comment by demeyera** [comment]
Is it possible to use this method for _chunks and _files as well?

**Comment by mbdavid** [comment]
@demeyera yes, no problem. _chunks and _files are normal collection and can be exported/imported
