### ISSUE TITLE
How to migrate database file from 4.1.4 to 5.0.0?

### ISSUE THREAD

**Issue by W0lfgang** [mbdavid/LiteDB#1434]
After updating my NuGet package to 5.0.0, I always get the error:

> LiteException: This file is not encrypted.

Is there any guideline on how to migrate my existing database files to the latest version?

Thank you very much in advance!

**Comment by BangL** [comment]
http://www.litedb.org/docs/connection-string/

there's a new "Upgrade" option for the ConnectionString, that should do the tricks, i guess.
remember to keep a backup :)

**Comment by W0lfgang** [comment]
Awesome. And thank you very much for this fast response :-)
Keep up your great work mate! ❤

**Comment by BangL** [comment]
i'm just a random dude, trying to help, not the dev :P
but thank you too :*

**Comment by W0lfgang** [comment]
Helping is great work, too ;-) xP

**Comment by JensSchadron** [comment]
For those using the `ConnectionString` class instead of an actual string, you can also set the `Upgrade` property to true

Eg:
```csharp
var connectionString = new ConnectionString
{
    Filename = "test.db",
    Connection = ConnectionType.Direct,
    Upgrade = true
};
```

**Comment by JensSchadron** [comment]
But given that the issue was already resolved by @BangL, I'll close the issue :)
