### ISSUE TITLE
What is the optimal number of documents for LiteDB

### ISSUE THREAD

**Issue by idansh** [mbdavid/LiteDB#144]
What is the optimal number of documents for LiteDB which it can operate with relatively good performance and when it's better no use another Server DB solution?

BTW: how do I mark an issue as a question here?

**Comment by mbdavid** [comment]
Hi @idansh, I saw your question on StackOverflow now and I created and filter using `litedb` tag to anwser there. There in github only I can mark an issue as a question.

About your question: LiteDB is an young embedded database made basicly by me. I still working to keep better and more stable as possible. The main problem in LiteDB is not the size of database or how many documents are you storing. You can have 1 milion documents and search using an index reading no more than 15 disk pages (60K) in less than 200ms.

LiteDB is my second database. FileDB, my first try, use some conecpts but much more basic (works for store files only). In FileDB I have databases with more than 3gb size and 4 year in production working fine.

Right now, the main problem here is concurrency. It's hard job keep file consistent with many processes/thread reading/writing. This is my priority now to fix as much as possible any concurrency problem and delivery a stable 2.0 version.

So, don't worry to much about database size or number of documents. Keep low (or zero) concurrency, work if small documents (or use FileStorage) and small transactions (do not insert 100.000 document at once).
