### ISSUE TITLE
"Part URI cannot start with two forward slashes " occurs when v4 to v5

### ISSUE THREAD

**Issue by GitOffice** [mbdavid/LiteDB#1442]
It scratches my head over these days. 
"Part URI cannot start with two forward slashes " always occurs When I update litedb from v4.1.4 to v5.0.1 through nuget package cosole or GUI.

It still fails even if I uninstall litedb v4.1.4 before upgradation.

VS environment is VS2013 
.net framework is v4.6
 windows8.1 OS

**Comment by mbdavid** [comment]
Hi @GitOffice, can you paste your snippet code with stacktrace error message?

**Comment by GitOffice** [comment]
PM> install-package litedb
install-package : Part URI cannot start with two forward slashes.
At line:1 char:1
+ install-package litedb
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], ArgumentException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

-------------------
When I type "install-package litedb" and hit Enter,  "Downloading LiteDB 5.0.1" appears in VS status bar. After a few minutes, the error message is listed above.

**Comment by mbdavid** [comment]
Try "Install-Package LiteDB" with same capitalize as registered in nuget

![install](https://user-images.githubusercontent.com/1137197/73941443-11f4b700-48cc-11ea-850d-ee69531df23e.gif)

**Comment by GitOffice** [comment]
![QQ拼音截图20200207081742](https://user-images.githubusercontent.com/1814649/73990223-7f175380-4983-11ea-8af2-b2350428e025.png)
Is it maybe the reason for Internet Service Provider in China ?
