### ISSUE TITLE
[BUG] Predicates with arguments do not work with DeleteMany

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#1445]
**Version**
LiteDB 5.0.1, net45, Windows 10

**Describe the bug**
Predicates with arguments do not work with collection's `DeleteMany` in LiteDB v5.0.1

**Code to Reproduce**
Example:

- create `BsonExpression` predicate with an argument
- use it with `DeleteMany`, the expected document is not deleted
- the same predicate works fine with `FindOne`
- `DeleteMany` still works with the similar predicate without arguments

```csharp
using (var db = new LiteDatabase(":memory:"))
{
    var c1 = db.GetCollection("Test");

    var d1 = new BsonDocument() { ["_id"] = 1, ["p1"] = 1 };
    c1.Insert(d1);
    Console.WriteLine($"count {c1.Count()}");

    {
        // try BsonExpression predicate with argument - not deleted
        var e1 = BsonExpression.Create("$._id = @0", 1);
        var r1 = c1.DeleteMany(e1);
        Console.WriteLine($"1. deleted {r1}");

        // the same BsonExpression predicate works fine in FindOne
        var r = c1.FindOne(e1);
        Console.WriteLine($"document: {r}");
    }

    {
        // try BsonExpression predicate hardcoded - deleted
        var e1 = BsonExpression.Create("$._id = 1");
        var r1 = c1.DeleteMany(e1);
        Console.WriteLine($"2. deleted {r1}");

        // double check - Count = 0
        Console.WriteLine($"count {c1.Count()}");
    }
}
```

Output:

```
count 1
1. deleted 0
document: {"_id":1,"p1":1}
2. deleted 1
count 0
```

**Comment by nightroman** [comment]
The same problem with database's `Execute`:

- hardcoded `DELETE test WHERE $._id = 1` works
- but `DELETE test WHERE $._id = @0` with argument 1 does not

Please let me know if I should create a separate issue for `Execute`.

**Comment by mbdavid** [comment]
Thanks @nightroman, was a missing copy parameters in specific "_id = " DeleteMany();

**Comment by mbdavid** [comment]
Will be available in next minor version (will release tomorrow or monday)

**Comment by nightroman** [comment]
@mbdavid Thank you!

May I ask off-topic but related question about `Execute`? Is `INSERT` supposed to support parameters in `VALUES`? These now fail with "Unexpected token `@`":

```sql
INSERT INTO test : INT VALUES @0
INSERT INTO test : INT VALUES {p1 : @0}
```

Maybe it's by design.
If yes, I wounder if this is planned for the future perhaps.
If no, I'll open the separate issue then.

**Comment by mbdavid** [comment]
At this moment, no. Insert is the only SQL command that not accept expressions (only JSON). It's because parse/compile expressions are very slow (if compared with only parse JSON). I have plans to auto-detect with user input pure JSON (and then resolve with JsonReader) or an expression (and then resolve with BsonExpression)

**Comment by nightroman** [comment]
Thank you, no problem at all, it's very useful to know in any case.

**Comment by mbdavid** [comment]
This will be very important when LiteDB will support some "T-SQL-Like" language for store procedures and triggers (is on my roadmap)

**Comment by qart2003** [comment]
Hi @mbdavid , this method is from DAL (repo) implemented in linq way
Doesnot work
`       public void DeleteByIds(IEnumerable<int> ids)
        {
            Collection.DeleteMany(v => ids.ToList().IndexOf(v.Id) > -1);
        }
`
 
I'm thinking it's a bug but not sure (may ne should not be implemented on the db level)
I had something like this and my solution was
`public static class RepoBasicExt
    {
        public static IEnumerable<T> FindWithBug<T>(this RepoBasic repo, ILiteCollection<T> Collection, Expression<Func<T, bool>> func)
        {
            try
            {
                return Collection.Find(func);
            }
            catch (NotSupportedException ex)
            {
                var internalFunc = func.Compile();
                return Collection.FindAll().Where(internalFunc);
            }
        }
//not good if we talk about performance, may be make sense to think about it on the "db level"
        public static IEnumerable<T> Find<T>(this RepoBasic repo, ILiteCollection<T> Collection, Expression<Func<T, bool>> func) => Collection.FindAll().Where(func.Compile());

    }`
