### ISSUE TITLE
[BUG] [v5] Unable to upgrade Version 4 to version 5 when index has "." in name

### ISSUE THREAD

**Issue by cjvanwyk3** [mbdavid/LiteDB#1447]
<img width="321" alt="ErrorImage" src="https://user-images.githubusercontent.com/60750704/73963571-2a69cf00-48d6-11ea-9d16-da3342113d1a.PNG">
**Version**
Lite Db Version 5

**Describe the bug**
When creating an index on a property that is more than one level deep in version 4
public bool EnsureIndex<K>(Expression<Func<T, K>> property, bool unique = false);
the index gets created with a "." in between the nested property.  For example:
collection.EnsureIndex(m => m.CustomerChild.ChildName);
creates an index field "CustomerChild.ChildName" and this prevents an upgrade to version 5

**Code to Reproduce**
        public class Customer
        {
            public int Id { get; set; }

            public string Name { get; set; }

            public CustomerChild CustomerChild { get; set; }
        }

        public class CustomerChild
        {
            public int Id { get; set; }

            public string ChildName { get; set; }
        }

        [TestMethod]
        public async Task TestIndex()
        {
            var database = new LiteDatabase(@"C:\LiteDbTest\TestIndex.db");
            var collection = database.GetCollection<Customer>();
            collection.EnsureIndex(m => m.CustomerChild.ChildName);
        }

After creating this database with Version 4, the LiteDb Studio cannot update the file.  
Also, using the following code does not work when using version 5 code

                            try
                            {
                                var updated = LiteEngine.Upgrade(ConnectionString?.Filename);
                                if (!updated)
                                {
                                    Debug.WriteLine("Unable to update liteDb");
                                    throw;
                                }
                            }
                            catch (Exception ex2)
                            {
                                Debug.WriteLine(ex2);
                            }

**Expected behavior**
Upgrading to version 5 should take the field value from version 4 and translate it to an acceptable value for the name property in version 5.

**Comment by lbnascimento** [comment]
@cjvanwyk3 This issue is fixed in master and will be included in the next incremental release (which will probably go live on Monday).
