### ISSUE TITLE
LiteDB works only with local drive

### ISSUE THREAD

**Issue by seahawks8** [mbdavid/LiteDB#1449]
wrote A desktop application early last year, but now this issue started showing up, is there a way I can enable to read from shared drive.
![7832FBB8-5728-4DE0-8DBB-DB9CEE76E9D1](https://user-images.githubusercontent.com/20735170/74041282-9ace2a00-4982-11ea-9a49-2576e4c0a03d.jpeg)

**Comment by lbnascimento** [comment]
@seahawks8 Could you provide us more info, like the LiteDB version you're running?

**Comment by seahawks8** [comment]
> @seahawks8 Could you provide us more info, like the LiteDB version you're running?

Using Version 5.0.1 (the Older version where I did not get this error was 4.1.4)

**Comment by lbnascimento** [comment]
Try using the shared mode. Use the follwing connection string:

```C#
using(var db = new LiteDatabase("filename=yourfile.db;mode=shared"))
{
    ...
}
```

**Comment by seahawks8** [comment]
Thanks, I will give it a shot, I thought it was enabled by default.

**Comment by JensSchadron** [comment]
@seahawks8 If you've tested this and it meets your requirements, could you please close the issue :) 
It helps in not losing sight of other tickets.

**Comment by seahawks8** [comment]
No problem, I will test it shortly after work.
