### ISSUE TITLE
Could be faster?If alloc more file size at once time.

### ISSUE THREAD

**Issue by suxiaojack** [mbdavid/LiteDB#145]
On data size is big ,then insert a little data would be slow,because file size would be increase a little  but rebuild indexs was needed and slow.Why not to get more file caching size at once ,so there is no need to oftenly changing file size.

**Comment by mbdavid** [comment]
Hi @suxiaojack, Litedb increses data file size when writing all new pages. If you are writing a long sequence of documents (using `Insert(IEnumerable<T>)`) all new pages are writed in a single operation.

So, I beleave if database increase by percentage (like sql server) this will not increase speed with a relevant results. Also, Litedb support initial datafile size.
