### ISSUE TITLE
[QUESTION] Can't get collection of interface

### ISSUE THREAD

**Issue by moabtools** [mbdavid/LiteDB#1455]
Hi!

In version 4.1.4 I was able to get interface collection like
```
jobsDb.GetCollection<IJob>("jobs");
```
In version 5.0.1 I can't do this - it needs type, not interface.

Why? How to fix it?

**Comment by JensSchadron** [comment]
Hi @moabtools 

I've tried to reproduce your issue, however... I didn't find anything that could be wrong.
You can find the code that I used below (tested against v5.0.2 though) :)

```csharp
class Program
{
    static void Main(string[] args)
    {
        using var db = new LiteDatabase("test.db");
        var collection = db.GetCollection<IFruit>();
        collection.Insert(new Apple{Amount = 2});
        collection.Insert(new Lemon{ExpiryDate = DateTimeOffset.Now.AddDays(2)});

        var fruitSalad = collection.FindAll().ToList();
        
        Debugger.Break();
    }
}

interface IFruit
{
    [BsonId]
    Guid Id { get; set; }
}

class Apple : IFruit
{
    public Guid Id { get; set; }
    public string Type => nameof(Apple);
    
    public int Amount { get; set; }
}

class Lemon : IFruit
{
    public Guid Id { get; set; }
    public string Type => nameof(Lemon);
    
    public DateTimeOffset ExpiryDate { get; set; }
}
```

Inspecting the fruitsalad list gives us 1 Apple and 1 lemon object with the correct properties.
Can you let us know if you still have the same issue on 5.0.2? If not, you can close the issue :)

**Comment by moabtools** [comment]
Sorry, it was urgent and I temporary moved to Mongo :) So, if you checked it - I think it works now.
