### ISSUE TITLE
[QUESTION] {"This operation is not supported for a relative URI."}

### ISSUE THREAD

**Issue by mbaletic** [mbdavid/LiteDB#1457]
I'm getting this error, my code is:

`private bool InsertBotConfigToDb(string path)
        {

                var stream = new StreamReader(path).ReadToEnd();
            // Open data file (or create if not exits)
            using (var db = new LiteDatabase(Server.MapPath("~/db.db")))
            {
                // Get customer collection
                var col = db.GetCollection<BotConfig>("botconfigs");

                var config = JsonConvert.DeserializeObject<BotConfig>(stream);

                // Insert new customer document
                col.Insert(1, config);

                //var result = col.Find(x => x.Name.StartsWith("Jo"));
            }
            return true;
        }`

**Comment by JensSchadron** [comment]
Hi @mbaletic,
Can you show us what the result is of `Server.MapPath("~/db.db")`?
Also, could you provide us with the version of LiteDB you're utilizing?

**Comment by mbaletic** [comment]
C:\\Users\\user\\source\\repos\\project\\project\\db.db

Latest version from nuget

**Comment by mbaletic** [comment]
What's weird is that Db is working in console application but on my MVC app it doesn't.

**Comment by mbaletic** [comment]
Help!!!

**Comment by mbdavid** [comment]
Did you try to put this path fixed in LiteDatabase creation? This folder has permission on IIS?

**Comment by mbaletic** [comment]
Yes and yes

**Comment by JensSchadron** [comment]
Could you provide us with the stacktrace of the exception?
Also, it might speed things up if we could get some minimal code that easily reproduces your exception as I can't seem to reproduce your issue.

**Comment by mbaletic** [comment]
"   at System.Uri.get_AbsoluteUri()\r\n   at LiteDB.BsonMapper.<>c.<.ctor>b__34_4(Uri uri)\r\n   at LiteDB.BsonMapper.<>c__DisplayClass35_0`1.<RegisterType>b__0(Object o)\r\n   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)\r\n   at LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)\r\n   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)\r\n   at LiteDB.BsonMapper.ToDocument(Type type, Object entity)\r\n   at LiteDB.BsonMapper.ToDocument[T](T entity)\r\n   at LiteDB.LiteCollection`1.Insert(T entity)\r\n   at nanobot.DB.InsertBotConfigToDb(String path) in C:\\Users\\Marko\\source\\repos\\Nanobot\\nanobot\\DB.cs:line 28\r\n   at nanobot.Controllers.HomeController.Index(HttpPostedFileBase file) in C:\\Users\\user\\source\\repos\\project\\project\\Controllers\\HomeController.cs:line 30"

**Comment by mbaletic** [comment]
"   at System.Uri.get_AbsoluteUri()\r\n   at LiteDB.BsonMapper.<>c.<.ctor>b__34_4(Uri uri)\r\n   at LiteDB.BsonMapper.<>c__DisplayClass35_0`1.<RegisterType>b__0(Object o)\r\n   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)\r\n   at LiteDB.BsonMapper.SerializeObject(Type type, Object obj, Int32 depth)\r\n   at LiteDB.BsonMapper.Serialize(Type type, Object obj, Int32 depth)\r\n   at LiteDB.BsonMapper.ToDocument(Type type, Object entity)\r\n   at LiteDB.BsonMapper.ToDocument[T](T entity)\r\n   at LiteDB.LiteCollection`1.Insert(T entity)\r\n   at nanobot.DB.InsertBotConfigToDb(String path) in C:\\Users\\Marko\\source\\repos\\Nanobot\\nanobot\\DB.cs:line 28\r\n   at nanobot.Controllers.HomeController.Index(HttpPostedFileBase file) in C:\\Users\\Marko\\source\\repos\\Nanobot\\nanobot\\Controllers\\HomeController.cs:line 30"

**Comment by JensSchadron** [comment]
@mbaletic does this mean your issue has been resolved?
