### ISSUE TITLE
Adding UWP support

### ISSUE THREAD

**Issue by dygestor** [mbdavid/LiteDB#146]
Hello, 
are you planning to add support for UWP? I'd like to store simple objects in a local DB and LiteDB seems like the way to go. However, the package is currently not compatible with UWP.

Thanks!

**Comment by mbdavid** [comment]
Hi @dygestor, yes, it's on plans, but not now for v2. I'm removing all not supported classes and making a conditional compilation for support both plataform.

**Comment by mbdavid** [comment]
@dygestor, take a look on `master` branch :+1:
