### ISSUE TITLE
[QUESTION] Do Exists and Count "Need indexes on query expression", as comments tell?

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#1461]
Do collection methods `Exists` and `Count` "Need indexes on query expression", as comments tell?

XML documentation code comments tell:

`Exists`:

> Returns true if query returns any document. This method does not deserialize any document.
> Needs indexes on query expression

`Count`:

> Count documents matching a query. This method does not deserialize any document.
> Needs indexes on query expression

What does "Needs indexes on query expression" mean?
My tests show that indexes are not *required*.
Are these comments out of date perhaps?

**Comment by mbdavid** [comment]
Is this about v4 or v5?

**Comment by nightroman** [comment]
v5 and the current source code (with these doc comment) from master

**Comment by mbdavid** [comment]
hummm... so it´s old documentation (required for v4). I will update XML documentation
