### ISSUE TITLE
[QUESTION] disable creation of LiteDB-log

### ISSUE THREAD

**Issue by asakl** [mbdavid/LiteDB#1462]
when I create a database (let's call him "DB"), it's created me a file DB.db and DB-log.db.
how I can create a database without the log file?

the c# code is:
`var db = new LiteDatabase(@"DB.db");`

**Comment by mbdavid** [comment]
This temp file are required in LiteDB v5 because it's used as WAL (write ahead log). All databases needs this to implement of ACID. This file are deleted when you close database.

**Comment by asakl** [comment]
OK thanks. 
but, even when i close my program entirely it's still there... 
the file can risk my data? (like, if it's a private info)

**Comment by duduric** [comment]
It seems it's only deleted when you call LiteDatabase.Dispose();

**Comment by mbdavid** [comment]
You always should call Dispose() on LiteDatabase after use. If not, you will not close file connections

**Comment by asakl** [comment]
OK, thank you very much!

**Comment by DinoChan** [comment]
在某些情况下，我们没权限删除目录下的任何文件（GMP或21CRF），这个临时的日志文件会引起某些异常。真的没办法禁止日志文件吗？

**Comment by AntonyNET** [comment]
Hi!
I open DB on my app start and dispose it when app closed.
Sometimes my app crashs and when i start it next time i have no data that i save. 
How i can flush changes from log file to main DB? log file is 7GB already

**Comment by lbnascimento** [comment]
@AntonyNET Just run a checkpoint operation after opening the datafile (actually, it should automatically run checkpoint when opening a datafile)

**Comment by challamzinniagroup** [comment]
> Hi!
> I open DB on my app start and dispose it when app closed.
> Sometimes my app crashs and when i start it next time i have no data that i save.
> How i can flush changes from log file to main DB? log file is 7GB already

@AntonyNET Sorry to drag up an old post - but can you explain a little further about the checkpoint operation (or point me to the docs section, if such a section exists)? I am using LiteDB on an API that is always on. I wrap the connection in `using` statements so they are always disposed. Yet I recently revisited an old project and the db file shows a last updated timestamp of 8 months ago, while the log file shows last updated of today and is over 3GB in size. So the log file is clearly not being merged back into the db file, nor is it being deleted.

Any more info you could provide would be appreciated.

Thanks!
