### ISSUE TITLE
[BUG] Exception when rebuild to change password

### ISSUE THREAD

**Issue by alemik** [mbdavid/LiteDB#1464]
LiteDB v5

Hello
If I use this code, after running a rebuild to change password ( from 1234 to 12345) I get this exception: "Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks". Am I doing something wrong or is it a bug?
The code is pretty much the same as LiteDB.Studio.

    public partial class MainWindow : Window
    {
        public LiteDatabase LiteDatabase { get; set; }
        public MainWindow()
        {
            InitializeComponent();
            TestOpenDataBase();
        }
        public void TestOpenDataBase()
        {   
            var cn = new ConnectionString(@"C:\Users\michele\Documents\DatabaseFolder\TestV5\testV5_PSW.db")
            {
                Password = "12345"
                //Connection = ConnectionType.Shared
                //string InitalSize = "";
                //bool ReadOnly = False; //True or False
                //bool Upgrade = False; //True or False
            };
            Connect(cn);            
        }
        public async void Connect(ConnectionString connectionString)
        {
            try
            {
                LiteDatabase = await this.AsyncConnect(connectionString);
                //TestRebuild();
                // force open database
                var uv = LiteDatabase.UserVersion;
            }
            catch (Exception ex)
            {
                LiteDatabase?.Dispose();
                LiteDatabase = null;
                Console.WriteLine(ex.Message, "Error");
                return;
            }
        }
        private async Task<LiteDatabase> AsyncConnect(ConnectionString connectionString)
        {
            return await Task.Run(() =>
            {
                return new LiteDatabase(connectionString);
            });
        }

        public void TestRebuild()
        {
            RebuildOptions rebuilOptions = new RebuildOptions
            {
                Password = "12345"
            };
            if (LiteDatabase != null)
            {
                LiteDatabase.Rebuild(rebuilOptions);
            }
        }
}

**Comment by mbdavid** [comment]
Hi @alemik, can you paste your stacktrace so I can track what's going on.

**Comment by alemik** [comment]
Everything seems to be working properly today. I'll investigate better. For now, I'm sorry I wasted your time.

**Comment by mbdavid** [comment]
No problems, I will close this issue. If happing again, please reopen or create a new one.
