### ISSUE TITLE
[BUG] Always NullReferenceException in FileStorage.Find()

### ISSUE THREAD

**Issue by duduric** [mbdavid/LiteDB#1469]
**Version**
Using version 5.0.2

**Describe the bug**
Find always returns a System.NullReferenceException in any path or database we try. The same code works perfectly and was in production on Version 4.1.4.
We know there are file because Exists() and Download() is working correctly with the same paths

**Code to Reproduce**

        public List<string> GetFilesInPath(string path)
        {
            List<string> foundFiles = new List<string>();
            // Returns all the files in this path
            var files = db.FileStorage.Find("$" + path);
            foreach (var lf in files)
            {
                foundFiles.Add(lf.Id);
            }
            return foundFiles;
        }

**Expected behavior**
Should return a list with all the file ids

**Screenshots/Stacktrace**
Result StackTrace:	
at LiteDB.BsonExpressionParser.TryParseFunction(Tokenizer tokenizer, ExpressionContext context, Boolean isRoot)
   at LiteDB.BsonExpressionParser.ParseSingleExpression(Tokenizer tokenizer, ExpressionContext context, Boolean isRoot)
   at LiteDB.BsonExpressionParser.ParseFullExpression(Tokenizer tokenizer, ExpressionContext context, Boolean isRoot)
   at LiteDB.BsonExpression.Parse(Tokenizer tokenizer, BsonExpressionParserMode mode, Boolean isRoot)
   at LiteDB.BsonExpression.Create(String expression)
   at LiteDB.BsonExpression.Create(String expression, BsonValue[] args)
   at LiteDB.LiteStorage`1.Find(String predicate, BsonValue[] args)
   at ....
Result Message:	
Method threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by deje07** [comment]
FileStorage.FindAll() is also affected...

**Comment by mbdavid** [comment]
Hi @duduric,

FileStorage works a bit different in v5. There is no more restriction about `_id` type in `_files` collection. In v4, `_id` is the filename with path. In v5, is any unique _id (with any data type you what, like `string`, `int`, ...). So, the `Find()` method change to implement any type of query over `_files`. You can write like:

`fs.Find("_id LIKE @0", path + "%")`

or 

`fs.Find("_id = @0", path);` 

or

`fs.Find("filename = @0", filename)`

**Comment by mbdavid** [comment]
@deje07, yes, it's a bug. I'm fixing this. For now you can use some like `fs.Find("1 =1")`

**Comment by duduric** [comment]
Thanks, we have been able to fix this part of the code

**Comment by LabuzzMichal** [comment]
Hi @mbdavid , could you change FileStorage section on https://www.litedb.org/docs/filestorage/ ?
Example described doesnt work anymore

// Find all files references in a "directory"
var files = fs.Find("$/photos/2014/");
