### ISSUE TITLE
[QUESTION] When installing LiteDB I get an error that the package does not contain assembly references .NETFramework, Version = v4.0

### ISSUE THREAD

**Issue by jmr85** [mbdavid/LiteDB#1470]
`Install-Package LiteDB -Version 5.0.2`
 
When I want to install LiteDB I get a .NETFramework error

Install-Package: The package 'LiteDB 5.0.2' could not be installed. You are trying to install this package in a project that has '.NETFramework, Version = v4.0, Profile = Client'

Install-Package: The package 'LiteDB 5.0.2' could not be installed. You are trying to install this package in a project that has '.NETFramework, Version = v4.0, Profile = Client'
as a destination, but the package does not contain assembly references or content files compatible with that framework. For more information, contact
The author of the package.

![image](https://user-images.githubusercontent.com/2564998/74337628-693cd080-4d7f-11ea-907c-11b544e10df2.png)

I think I understand that it depends on .net framework Version = v4.0 ... but I have that framework installed in my windows 10.

Then I try to add the reference but I don't have it in the list

![image](https://user-images.githubusercontent.com/2564998/74341147-fc790480-4d85-11ea-84e9-66dfe979735f.png)

**Comment by mbdavid** [comment]
Hi @jmr85, v5 requires NET 4.5+or NETCore 1.1+

If you need run in v4 you should keep in v4.x version
