### ISSUE TITLE
[BUG] Query.Descending / Query.Ascending

### ISSUE THREAD

**Issue by jackkoolage** [mbdavid/LiteDB#1473]
**Version**
Which LiteDB version/OS/.NET framework version are you using. **(REQUIRED)**
litedb.5.0.0-rc / 7 x32 / 4.5.2

**Describe the bug**
col.Find(Query.All(Query.Ascending), limit:=Limit)
col.Find(Query.All(Query.Descending), limit:=Limit)
both commands gives same results (Ascending)

**Code to Reproduce**
```vb.net
dim db = New LiteDatabase(Application.StartupPath + "\Settings\DB.db")
Dim col = Ldb.GetCollection(Of TBCls)("Metadata")
Return col.Find(Query.All(Query.Descending), limit:=20).ToList() 
```

**Comment by mbdavid** [comment]
Hi @jackkoolage, thanks! I miss the `_id` parameter when not passed. Fixed and will be avaiable in nuget this next week

**Comment by jackkoolage** [comment]
thanks
im in love with that db .. keep going
