### ISSUE TITLE
FileNotFoundException thrown when LiteDatabase constructed (mydb-journal.db not found)

### ISSUE THREAD

**Issue by geoffwc** [mbdavid/LiteDB#148]
I'd first like to say I'm really liking LiteDB!

Just spotted in the output window I'm getting a FileNotFoundException on LiteDatabase  construction.

I'm doing this:

`var dataDir = (string)AppDomain.CurrentDomain.GetData("DataDirectory");
            var connectionString = ConfigurationManager.ConnectionStrings["litedb"].ConnectionString.Replace("|DataDirectory|", dataDir);
            _database = new LiteDatabase(connectionString);`

I notice the -journal file is getting created fine upon write though.

**Comment by mbdavid** [comment]
Hi @geoffwc, thanks for using LiteDB and found this issue. I fixed in master branch.
