### ISSUE TITLE
[QUESTION] How to filter by referenced collection primary key?

### ISSUE THREAD

**Issue by maxkatz6** [mbdavid/LiteDB#1484]
Let's take next relation
```csharp
class Child
{
   int Id {get;set;}
}
class Owner
{
    int Id {get;set;}
    Child Child {get;set;}
}
```
Which is registered in next way
```csharp
Database.Mapper.Entity<Child>()
     .Id(e => e.Id, false);
Database.Mapper.Entity<Owner>()
     .DbRef(e => e.Child)
     .Id(e => e.Id, false);
```
On this point I understand, Owner document will contain only id of child document.
But how should I filter Owner documents by Child id?
I can use next code:
```csharp
Collection
    .Include(o => o.Child)
    .Find(Query.EQ($"{nameof(Owner.Child)}.{nameof(Child.Id)}", new BsonValue(idValue))))
```
But is it the best way to do filter by referenced document id? Because code above requires Include, when I don't really need child document, except of Id.
Also, how should I ensure index for it?

Thanks.

**Comment by mbdavid** [comment]
Hi @maxkatz6, if you don't need to include you can filter by `$id` key. Like this:

```
collection.Query()
    .Where("$.Child.$id = @0", idValue)
    .ToList()
```

**Comment by maxkatz6** [comment]
@mbdavid thanks!
I will try it
