### ISSUE TITLE
[QUESTION] Can I use LiteDB V5 do not create or delete log file (GMP or 21crf) ?

### ISSUE THREAD

**Issue by yaozhong-OMEC** [mbdavid/LiteDB#1486]
I use LiteDB V5 for data file to store data. In some cases, we do not have permission to delete any files (GMP or 21crf) in the directory. This temporary log file will cause some exceptions. Does it have solution?

**Comment by mbdavid** [comment]
You can use in-memory log file. But be careful, if occurs any error during checkpoint process can (and will) corrupt your datafile. At this point, to do this, you must work only with `LiteEngine` class because this option are not available in `LiteDatabase`.

**Comment by yaozhong-OMEC** [comment]
Thanks. Will the option be available in `LiteDatabase` in the future?

**Comment by mbdavid** [comment]
Yes, will be part of 5.1 (will be release next month)
