### ISSUE TITLE
[SUGGESTION] Use LiteDB in memory with password

### ISSUE THREAD

**Issue by undergroundwires** [mbdavid/LiteDB#1488]
**Is your feature request related to a problem? Please describe.**
I'd like to use the LiteDB in memory with password protection.

**Describe the solution you'd like**
Add password in constructor that will configure `EngineSettings` with a password.
`new LiteDatabase(Stream stream, BsonMapper mapper = null, string password = null)`

**Comment by mbdavid** [comment]
Hi @undergroundwires, added in 5.1 roadmap support again to constructor with `ILiteEngine`

**Comment by undergroundwires** [comment]
Thanks @mbdavid ! Smart way to solve it.
