### ISSUE TITLE
[BUG] LiteDatabase is not thread safe

### ISSUE THREAD

**Issue by Thdm1907** [mbdavid/LiteDB#1489]
**Version**
LiteDB 5.0.2 with .NET Core 3.1 (don't think this part matters)

**Describe the bug**
Per the suggestion at https://github.com/mbdavid/LiteDB/wiki/Concurrency, I create a single LiteDatabase instance to share with multiple thread. The code snippet inserts a single record then queue a Task to remove the record. Even though the deletion Tasks are running on a separate thread, the Tasks are chained so only one deletion is running at a time. At the end of the program, the code output 0 items. When using LiteDB Studio to view the database, there are still records in the table. The number of left-over records are random.

**Code to Reproduce**
```
class Program
    {
        
        private static LiteDatabase _db;
        private static Task _eventProcessingTask;
        private static readonly object _processingTaskLock = new object();
        private static string _tableName = "myTable";
        static void Main(string[] args)
        {
            _db = new LiteDatabase($"Filename=MyDb;Mode=Exclusive;Async=false;Flush=true;");
            
            for (int i = 1; i < 1000; i++)
            {
                Insert(i);
            }
            
            System.Threading.Thread.Sleep(5000);
            
            var table = _db.GetCollection<TableRow>(_tableName);
            Console.WriteLine($"There are {table.Count()} items.");
        }

        static void Insert(int id)
        {
            var table = _db.GetCollection<TableRow>(_tableName);
            table.Insert(new TableRow { Id = id, Data = $"item {id}"});
            
            lock (_processingTaskLock)
            {
                if (_eventProcessingTask == null)
                    _eventProcessingTask = Task.Run(() => Delete(id));
                else
                    _eventProcessingTask = _eventProcessingTask.ContinueWith((t) => Delete(id));
            }
        }

        static void Delete(int id)
        {
            var table = _db.GetCollection<TableRow>(_tableName);
            table.Delete(new BsonValue(id));
        }
    }

    public class TableRow
    {
        public int Id { get; set; }
        public string Data { get; set; }
    }
```

**Expected behavior**
In-memory count should show the count of the items of the database in the file system.

**Comment by mbdavid** [comment]
Hi @Thdm1907, I just run you code and works as expected: all documents was inserted and collection are empty on LiteStudio.

![concurrency](https://user-images.githubusercontent.com/1137197/74837972-656df880-5301-11ea-9ac0-f8167d5b530e.gif)


ps: (you are looking documentation for v4 - use www.litedb.org for v5 documentation)

**Comment by Thdm1907** [comment]
I'd say the result is mix. I re-run the test code multiple times, there are times when it works fine and there are times when it doesn't work. From my tests, it works 2 out of 10 times. If you re-run the test code multiple times, hopefully you can see it too. If it doesn't, maybe there's some issue with my environment and you can close this issue as not reproducible.

**Comment by mbdavid** [comment]
I test again multiple times... and 100% I get same result. But, I made some changes in your code:

- DropCollection just after open database (to ensure there is no previous data)
- Use `_eventProcessingTask.Wait()` insted sleep (to ensure deleted was finish)
- Call `_db.Dispose()` before finish (to ensure checkpoint runs)

Try do this in your environment to check if could be some like this.

About v5 is same concurrency suggestion. I'm still updating documentation.

But I found a minor bug in LiteDB when testing your example: DropCollection are not removing start index page when has no documents inside collection. The problem is datafile contains an unsed page. I'm fixing and pushing soon.

**Comment by pablopioli** [comment]
Well I have found another case, in this case involving files. I have a controller that display images stored in a LiteDb database

        [HttpGet]
        public ActionResult Get([FromRoute] string id)
        {
            var db = _options.Database;

            var file = db.FileStorage.FindById("$/image/" + id);

            if (file == null)
            {
                return NotFound();
            }

            var ms = new MemoryStream();
            file.CopyTo(ms);
            ms.Position = 0;

            return new FileStreamResult(ms, "image/jpeg");
        }

See attached file (for better formatting)
[error.txt](https://github.com/mbdavid/LiteDB/files/4227296/error.txt)

As a good concurrency problem, it appears randomly. I made an image gallery and 25% of the times I get an exception.

**Comment by Thdm1907** [comment]
@mbdavid I see that adding a Dispose call at the end of the program helps and the database is consistent with what I expect. Another way to implement it is to give the Insert and Delete call its own instance of LiteDatabase via the `using `statement like:
```
            using (var db = new LiteDatabase("Filename=Mydb"))
            {
                var table = _db.GetCollection<TableRow>(_tableName);
                table.Insert(new TableRow {Id = id, Data = $"item {id}"});
            }
```
I assume that the Dispose call will make sure the transactions are flushed to the file system and that's why it works for either calling Dispose explicitly or via `using`. I was expecting that each Insert/Delete call will make its way to the file system as soon as the call is complete. Closing this issue.

**Comment by mbdavid** [comment]
@pablopioli, can you open another issue about your error. Can be a concurrency problem but are not related with this issue.

**Comment by mbdavid** [comment]
Hi @Thdm1907, there is some points here:

Engine contains an async writer queue to write in disk (in async thread) all dirty pages direct to Log file. This process still occurs after user get "Insert OK" (or delete, update...). If you interrupt your program during this async write, this missing pages/transactions will not be write and when open database again you will see "half" operations.

When you call `Dispose` from `LiteDatabase`, this method waits for this async thread finish before close database, runs Checkpoint operation (coping LOG file into datafile) before everything finish. So, with no `Dispose`, you can get some "random" data inside database. Maybe is the case for you.

**Comment by pablopioli** [comment]
> 
> 
> @pablopioli, can you open another issue about your error. Can be a concurrency problem but are not related with this issue.

Yes, sorry, it was late on night and wasn't thinking properly. I'm building a repro app to attach to the issue.
