### ISSUE TITLE
[QUESTION] DOCS\BsonDocument - "Keys are case-sensitive" - is this correct?

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#1496]
[DOCS\BsonDocument](https://www.litedb.org/docs/bsondocument/) says

> Keys are case-sensitive

Is this correct? Tests, e.g. [Case_Insensitive_Tests.cs](https://github.com/mbdavid/LiteDB/blob/master/LiteDB.Tests/Document/Case_Insensitive_Tests.cs), show the opposite.

**Comment by mbdavid** [comment]
Keys are not sensetive. I will fix documentation. Thanks
