### ISSUE TITLE
Named collections suggestion

### ISSUE THREAD

**Issue by JordanMarr** [mbdavid/LiteDB#15]
Currently, the GetCollection<T> method requires a string:name parameter.  
Since a .db file is limited to storing one type of entity, I'm not sure why a name is required at all.  
But if it must exist, it would be nice if it was at least changed to be an optional parameter.

Maybe something like:
```
public LiteCollection<T> GetCollection<T>(string name = null)
{
    name = name ?? typeof(T).Name;
    ...
}
```

**Comment by mbdavid** [comment]
Each .db can have multiple collections and each collection needs a name.

You can use like this:

```C#
var col1 = db.GetCollection<User>("users");
var col2 = db.GetCollection<User>("inactive_users");

var col3 = db.GetCollection<BsonDocument>("users");
```

Two distinct collections using same entity. Or, you can use `BsonDocument` to read/write your documents too. That's the reason to get a named to a collection.

Also, each collection store documents (that are scheme-less): each documents can have different data structures.

```JS
db.col1.insert {_id:1, name: "John", age: 30}
db.col1.insert {_id:"myIdString", name: true}
db.col1.insert {age: "ten"}
db.col1.ensureIndex name
```

This is a complete valid 3 documents, in same collection. And index works too.

I recommend to use a repository pattern like this:

```C#
public class MyDB : LiteDatabase
{
    public LiteCollection<User> Users { get; private set; }
    public LiteCollection<User> ObsoleteUsers { get; private set; }

    public MyDB() : base("stringConnection")
    {
        this.Users = this.GetCollection<User>("user");
        this.ObsoleteUsers = this.GetCollection<User>("obsolete_user");
    }
}

using(var db = new MyDB())
{
    db.Users.Find(...);
}
```

Using this, you will never write collection name again.
