### ISSUE TITLE
Having trouble with getting Data/String from a Query

### ISSUE THREAD

**Issue by philbertphotos** [mbdavid/LiteDB#150]
I been playing with LITEDB and the only placed I am stuck on is converting the query to a string ... any help in the right direction would be greatly appreciated .. I could find no documentation anywhere that would help.
Simple Query
var results = collection.Find(Query.StartsWith("Name", "Jo"));

This is GETTYPE "LiteDB.LiteCollection`1+<Find>d__4[createRDPprocess.noSql]"

**Comment by Xicy** [comment]
because find return IEnumerable<T> type so we use ToArray, ToList ....

try this
`var results = collection.Find(Query.StartsWith("Name", "Jo")).ToArray();`

**Comment by philbertphotos** [comment]
This is what I am getting 
System.InvalidCastException: Specified cast is not valid.
   at _(Object , Object )
   at LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value) \LiteDB\Serializer\Mapper\BsonMapper.Deserialize.cs
244
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value) in \LiteDB\Serializer\Mapper\BsonMapper.Deserialize.cs:line 163

**Comment by philbertphotos** [comment]
Here is the function	

	public static string ListDBValues()
		{
			using (var db = new LiteDatabase(root + "createRDPprocess.db")) {
				var col = db.GetCollection<noSql>("checkidle");
                            var results = col.Find(x => x.Name.StartsWith("student")).ToArray();
				//Console.WriteLine(results);	
				return ""; 
	
			}
		}

**Comment by mbdavid** [comment]
Hi @philbertphotos, is your collection has convertable data to your class? All document fields can be convert to you `noSql` data struct? If not, you will get error like this.

1) Try query this data in Lite Shell app to check data structure.
2) Test with an empty database - insert each document at time
3) Take a look on wiki documentation. It's for v1.x but has no big changes for v2beta

https://github.com/mbdavid/LiteDB/wiki

4) Show your `noSql` class to understand how works.

**Comment by philbertphotos** [comment]
public class noSql
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int idleTime { get; set; }
    public int LastUpdate { get; set; }
    public bool IsActive { get; set; }

**Comment by philbertphotos** [comment]
Data.......
[7]:
{
    "_id": 18,
    "Name": "student26",
    "idleTime": "20",
    "LastUpdate": "92",
    "IsActive": false
}
[8]:
{
    "_id": 15,
    "Name": "student27",
    "idleTime": "20",
    "LastUpdate": "92",
    "IsActive": false
}

**Comment by philbertphotos** [comment]
Also get an Arithmetic operation resulted in an overflow.
When I do a "db.Run("db.checkidle.find Name like \"student2\" ");"
This exact command works in the shell perfectly.

**Comment by philbertphotos** [comment]
Thanks for your help it was either a corrupted DB or one I was doing crap on and it had invalid table.
Soon as I deleted it and have it recreated it worked fine.
