### ISSUE TITLE
Any()  are not supported when convert to BsonExpression

### ISSUE THREAD

**Issue by GitOffice** [mbdavid/LiteDB#1505]
LiteDB 5.0.3 , Windows 8, net46
But failing while converting predicate with Any() to BsonExpression.
```
public class Customer
{
    public int Id { get; set; }
    public List<string>Phones { get; set; } 
}
var customer1= new Customer {Phones =new List<string> { "11", "22" }};
var customer2= new Customer {Phones =new List<string> { "22", "33" }};
db.EnsureIndex<Customer>("Name");
db.Insert<Customer>(customer1);
db.Insert<Customer>(customer2);
```
When I type search term "11@33" or "22",  the two above records are what I want. 
But the error message is : 
> Method Any() in Enumerable are not supported when convert to BsonExpression (x.Phones.Any()).

My partial code is 
```
var searchTerm="11@33".Split('@');  
db.Query<Customer>().Where(x => x.Phones.Any() &&
                                                  x.Phones.Any(y => searchTerm.Contains(y))
);

```
Any help would be appreciated!

**Comment by lbnascimento** [comment]
@GitOffice A Linq-to-BsonExpression for the method `Any()` was created. It is avaliable in the master branch and should be present in the next incremental release. In the meantime, you can use `.Where(x => x.Phones.Count() > 0)`.

**Comment by KaJIbI4** [comment]
same situation with .Equals() ("==" work):
var i = db.GetCollection< ... >( "..." );
var s = i.FindOne( x => x.name.Equals( name ) );

**Comment by lbnascimento** [comment]
@KaJIbI4 I created a Linq-to-BsonExpression conversion for the method `Equals()` (only for `string`, `DateTime`, `ObjectId`, `Guid` and numerical types). It is avaliable in the master branch and should be present in the next incremental release. In the meantime, you can just use `x => x.Name = name`.

**Comment by EeveeWhitefire** [comment]
same issue for a List object's `Exists`, and in general the new updates removed any way to use external methods for the predicate and it's really annoying

**Comment by lbnascimento** [comment]
@EeveeWhitefire LiteDB v4 allowed for any Linq expression to be used as predicate, however when it found an expression that couldn't be converted to `BsonExpression`, it would store it and run with Linq-to-object after retrieval (it was equivalent to `col.FindAll().Where(predicate)`). This feature was removed in v5 due to performance concerns.
