### ISSUE TITLE
[QUESTION] Does the power interruption of the execution Rebuild()(V5) or Shrink()(V4) cause the file to be damaged

### ISSUE THREAD

**Issue by yaozhong-OMEC** [mbdavid/LiteDB#1508]
I use LiteDB V4 and V5 in some project. I want to know if the database will be damaged due to power failure when I delete records and execute  Rebuild()(V5) or Shrink()(V4). And what if V5 using use in-memory log file?

**Comment by lbnascimento** [comment]
@yaozhong-OMEC Both LiteDB v4 and v5 implement the ACID properties, so the datafile will not be corrupted in case of a power failure. When the datafile is opened, if a log file is found, commited transactions in the log file are written to the datafile and uncommited transactions are discarded.

However, this is **not** the case with in-memory log. In this scenario, power failure in the middle of a checkpoint operation would result in data corruption.

If this answers your question, please close the issue.
