### ISSUE TITLE
Invalid LCID code after upgrade from 4.1.4 to 5.0.3

### ISSUE THREAD

**Issue by josephinenewbie** [mbdavid/LiteDB#1509]
Got the following error when calling from my C# :
` System.ArgumentException: Invalid LCID code
   at LiteDB.LCID.GetCulture(Int32 lcid)
   at LiteDB.Collation..ctor(Int32 lcid, CompareOptions sortOptions)
   at LiteDB.Engine.EnginePragmas.<.ctor>b__36_7(BufferSlice b)
   at LiteDB.Engine.EnginePragmas..ctor(BufferSlice buffer, HeaderPage headerPage)
   at LiteDB.Engine.HeaderPage.LoadPage()
   at LiteDB.Engine.HeaderPage..ctor(PageBuffer buffer)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
`

Previous environment:
- .net standard 2.0 
- litedb v4.1.4 nuget package

Current environment
- .net standard 2.0 
- litedb v5.0.3 nuget package

Attempt 1:
I have upgrade the existing db by lite.studio. I can open the upgraded db in lite.studio. Then when i try to call from my C#, it shows Invalid Lcid code.

Attempt 2:
I set connection string with **upgrade = true** when calling db in C#. Still shows same error.

Attempt 3:
 Tried to export json and import json in lite.studio. Work fine in lite.studio. But show Invalid LCID again when i try to call from C#.

Can you please advise how to fix it?

Thanks!

**Comment by lbnascimento** [comment]
@josephinenewbie, could you provide the datafile you're trying to upgrade?

**Comment by luckymark** [comment]
I have some problem similarly:
1)C# write to db (Nuget:LiteDb 5.0.0-beta)
2)LiteDbStudio(v.0.5.1.0) to connect  the db is OK
3)LiteDbStudio(v.1.0) to connect  the db, report "Invalid LCID code"

[abc.sdd.zip](https://github.com/mbdavid/LiteDB/files/4270137/abc.sdd.zip)

**Comment by mbdavid** [comment]
Hi @luckymark, LiteStudio 0.5.1 uses LiteDB-rc, where this ir no LCID support.

You need use LiteDBStudio 1.x and Lite v5.0.x - always new versions.... convert your old dabtase using this tools

**Comment by josephinenewbie** [comment]
Thank you all. 
Finally upgrade the DB with a correct version of LiteDBStudio v1.0.1. (Previously i used the LiteDBStudio exe from source so maybe that's not the correct.
