### ISSUE TITLE
[BUG] Rebuild crashes on a particular database and leaves WAL

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#1510]
Rebuild crashes on a particular database and leaves WAL

**Version**

- LiteDB 5.0.3 and the latest from repo, Windows 10/8.1, net45
- Same with LiteDB.Studio 1.0.1 on invoking REBUILD (and studio kind of crashes on closing)

**Describe the bug**

- Get the problem database file "Programs.LiteDB".
    - I do not want to attach 12Mb zip, also not that public.
    - Please let me know if it is fine to send it by email.
- Build and run the below code with the path adjusted.
- It crashes in both Debug and Release configurations and leaves the WAL file.
    - In Release this workflow seems to be recoverable, the database survives.
    - In Debug the database is dead on some runs, all (2) collections are missing.

**Code to Reproduce**

```csharp
class Program
{
    static void Main(string[] args)
    {
        using (var db = new LiteDatabase(@"...\Programs.LiteDB"))
        {
            db.Rebuild();
        }
    }
}
```

**Expected behavior**

Rebuild should work.

**Stack**

Release

```
Unhandled Exception: System.Threading.LockRecursionException: Recursive write lock acquisitions not allowed in this mode.
   at System.Threading.ReaderWriterLockSlim.TryEnterWriteLockCore(TimeoutTracker timeout)
   at System.Threading.ReaderWriterLockSlim.TryEnterWriteLock(TimeoutTracker timeout)
   at LiteDB.Engine.LockService.TryEnterExclusive()
   at LiteDB.Engine.WalIndexService.Checkpoint(Boolean soft)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.RebuildContent(IFileReader reader)
   at LiteDB.Engine.LiteEngine.Rebuild(RebuildOptions options)
   at TryLiteDB.Program.Main(String[] args)
```

Debug

```
Unhandled Exception: System.Exception: ENSURE: must have no pages in used when call Clear() cache
   at LiteDB.Constants.ENSURE(Boolean conditional, String message)
   at LiteDB.Engine.MemoryCache.Clear()
   at LiteDB.Engine.WalIndexService.Clear()
   at LiteDB.Engine.LiteEngine.RebuildContent(IFileReader reader)
   at LiteDB.Engine.LiteEngine.Rebuild(RebuildOptions options)
   at LiteDB.LiteDatabase.Rebuild(RebuildOptions options)
   at TryLiteDB.Program.Main(String[] args)
```

**Comment by lbnascimento** [comment]
@nightroman You can send the datafile to me at lbnascimento@inf.ufrgs.br

**Comment by nightroman** [comment]
@lbnascimento Done!

**Comment by lbnascimento** [comment]
@nightroman Was your datafile upgraded from v4 to v5?

**Comment by nightroman** [comment]
@lbnascimento No, I never used v4. I have similar databases produced on other machines (basically dumps of file info from Program Files) and they are rebuilt fine. But this one fails.

**Comment by nightroman** [comment]
NB On some of these other files I can see that REBUILD may return negative values. This looks a little strange. But maybe it's OK, I do not know.

**Comment by nightroman** [comment]
For a example I have a zip of DB for which several REBUILD in a row produce this results:

    0 8192 8192 -16384

I may send it, too, if needed.

**Comment by mbdavid** [comment]
Hi @nightroman, try run with my fixes... I found a bug in rebuild reader file.

**Comment by nightroman** [comment]
OK, I will try with the next update.
BTW, the sequence I provided above is not deterministic.

**Comment by nightroman** [comment]
@mbdavid It works with the problem db!

Just for info, the series of or repeated Rebuild, produced numbers:
24576 0 8192 8192 -8192
(if it's OK or not it's up to you)

**Comment by mbdavid** [comment]
This numbers are reduced bytes. Only first time has a minimal expected. Others are just difference because index use Random levels and can be small difference between many rebuilds.

**Comment by nightroman** [comment]
Thank you. I close it then. I'll try in the next update anyway.
