### ISSUE TITLE
[BUG] Apparently invalid expression should fail

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#1517]
**Version**

LiteDB 5.0.3 and the latest from repo, Windows 10, net45

**Describe the bug**

Run the below code with presumably invalid expression syntax.

**Code to Reproduce**

```csharp
doc = new BsonDocument();
var expr = BsonExpression.Create("5 FOOBAR < 5");
var r = expr.ExecuteScalar(doc);
r.AsInt32.ExpectValue(5);
```

**Expected behavior**

The above test should fail with some "invalid syntax", "invalid operator 'FOOBAR'", etc.
But it passes.

**Comment by mbdavid** [comment]
Thanks @nightroman, fixed.
