### ISSUE TITLE
Proposal: How to do concurrency access?

### ISSUE THREAD

**Issue by mbdavid** [mbdavid/LiteDB#152]
Well, LiteDb must improve concurrency access in datafile to be more safe (avoiding corruped data). So my idea is implement a solid and simple solution to v2.

1) No more thread-safe. It's a little complicate handle with that. Keep as v1 version and be only "process safe".
2) Back transaction operations. 

How will work concurrency in v2:

- Datafile will be opened in READONLY shared support. So, can have multiple read only connections at same time.
- All write operations will be inside a transaction. 
- Begin transaction will try open file as WRITE exclusive operation. No one can write/read data file until Commit/Rollback.
- Cached pages will be clear after any read (non-transaction) operation (non-dirty). Avoid concurrency changes between run queries.
- Transaction operations (read/write) will keep cached pages (or journal file with more than 5000 pages in memory) until end transaction. At end of transaction, clear all pages (dirty and non-dirty).
- All this operations will works only with `FileDiskServices` na `EncryptedDiskService`. `StreamDiskService` will be to single-connection only.

Did you enjoy LiteDB and have any suggestion about that? Please, comment here.

**Comment by jbrozek** [comment]
I think this sounds good, simple and clear.

**Comment by vacuumstate** [comment]
I agree - it will support my LiteDB usage perfectly.

In the meantime, I'm going to wrap all usages with a (machine) global mutex to guarantee concurrency/stability; - I'll take the performance hit for now.

**Comment by a44281071** [comment]
good job, but i can't wait for new 2.0 stable ver.You know I've been pulling for you.

**Comment by BO45** [comment]
Yes please. Concurrency safety should come first. Right now we are in 2.0RC and are syncing across the public API surface. I'd rather have the sync granularity on a transactional basis.

**Comment by nvivo** [comment]
I just found LiteDB. Great project!

All locking seems to be based on file locking. I was wondering how locking works when you're writing to custom streams instead of file streams. With 2.0, is it possible to delegate locking to some custom object?
