### ISSUE TITLE
[SUGGESTION] Please make LiteCollection.AutoId public property

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#1520]
**The problem**

I have a "function" (PowerShell cmdlet, to be precise) with the following input:

- A `LiteCollection<BsonDocument>` opened by a user with some `BsonAutoId` value specified.
- Documents to insert. They are `BsonDocument`s produced from typed data using BsonMapper.Serialize`.

The documents may (and normally do) have their `_id` with default values like
`0`, `ObjectId.Empty`, `Guid.Empty`... I cannot insert these documents right
away, this fails due to duplicated ids.

Thus, I have to remove those `_id` from documents if they have the same
`BsonAutoId` type as the collection has and default values of this type.

It is not possible because there is no public `LiteCollection.AutoId`
or any other way to get this information (except reflection hacks).

**The solution**

I suggest making `LiteCollection.AutoId` the public read only property.

**The workaround (partial)**

Currently, in the described scenario I can only remove all `_id` with **any**
default value, regardless of the actual current auto id. This kind of works
but introduces some weird limitations. It is not possible to insert documents
with any of `0`, `0L`, `ObjectId.Empty`, `Guid.Empty`. This is especially bad
in case of `Int32`. I sometimes want `_id`s to be some zero based indexes.

**Comment by nightroman** [comment]
I can help with the PR and testing, if the suggestion is accepted as such.
Please let me know.

**Comment by mbdavid** [comment]
Sure, please make a PR about this that I will merge in master

**Comment by nightroman** [comment]
Thank you, done. Looking forward to the updated package!
