### ISSUE TITLE
[BUG] Update db to v5 unsupport class type BsonId

### ISSUE THREAD

**Issue by hualiao** [mbdavid/LiteDB#1523]
**Version**
4.1.4.0
.Net Framework 4.7.2

**Describe the bug**
When I update to v5 encounter an error both in LiteDB studio and connection string with "upgrade=true" .
The error says Invalid index name '_id.TweetId' on collection 'tweet': Use only [a-Z$_]

**Code to Reproduce**

```
    public class Tweet
    {
        [BsonId]
        public TweetKey Key { get; set; } = new TweetKey();
        
        ....
   }

    public class TweetKey
    {
        public string TweetId { get; set; }

        public string UserName { get; set; }

    }

```

**Comment by lbnascimento** [comment]
@hualiao Are you running the latest version of v5? There was a bug when upgrading indexes with a `.` in the name (see #1447), and it is already fixed.

**Comment by hualiao** [comment]
Thanks for your reply. The latest version fix this. Yesterday firstly I use early v5 and LiteDB studio, lately I use latest v5 unfortunately there was another error I thought was the same one. Sorry to waste your time.
