### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by filipgeens** [mbdavid/LiteDB#1528]
In version 4.x, I used the function GetIndexes() of the LiteCollection<T> to view the existing indexes. This allowed me to view the existing indexes and drop them automatically if the where absolute in older collections.
But in version 5 this functionality is missing in the ILiteCollection<T>. Is there a way to get the existing indexes (I only need the names of the indexes)?

**Comment by lbnascimento** [comment]
@filipgeens You can list indexes by querying the `$indexes` system collection. You can open it as if it were a regular collection: `var col = db.GetCollection("$indexes")`.

Each document returned has the following structure:

```javascript
{
   "collection":"Customers",
   "name":"_id",
   "expression":"$._id",
   "unique":true,
   "maxLevel":19
}
```

You can use filters too. For example, if you wanted only the indexes for the collection `Customers`, you can use `col.Find("$.collection = 'Customers'")`.

**Comment by filipgeens** [comment]
Great! Thx
