### ISSUE TITLE
[BUG]LiteDb doesn't insert data in .NET 5.0.100-preview.1.20125.9

### ISSUE THREAD

**Issue by DotNetAppCompatFeiWang** [mbdavid/LiteDB#1529]
**Version**
.NET Core 5.0.100-preview.1.20125.9

**Describe the bug**
LiteDb doesn't insert data in .NET 5.0.100-preview.1.20125.9

**Code to Reproduce**
using LiteDB;
using System;
using System.IO;

 public class Author
    {
        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }

using (var db = new LiteDatabase("mytest.db"))
            {
                var collection = db.GetCollection<Author>("authors");
                var author = new Author
                {
                    Id = Guid.NewGuid(),
                    FirstName = "Mark",
                    LastName = "Twain"
                };
                collection.Insert(author);
                var results = collection.Find(Query.All(Query.Descending), limit: 100);
                foreach (var item in results)
                {
                    Console.WriteLine(item.FirstName + " " + item.LastName + " " + item.Id);
                }
                Console.WriteLine("Record Count:" + collection.Count());
            }

**Expected behavior**
data insert successfully.

**Screenshots/Stacktrace**
If applicable, add screenshots/stacktrace

**Additional context**
.NET Core SDK (reflecting any global.json):
Version: 5.0.100-preview.1.20125.9
Commit: 12e88ed2e5
Runtime Environment:
OS Name: Windows
OS Version: 10.0.17763
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\5.0.100-preview.1.20125.9\
Host (useful for support):
Version: 5.0.0-preview.1.20120.5
Commit: 3c523a6a7a
.NET Core SDKs installed:
5.0.100-preview.1.20125.9 [C:\Program Files\dotnet\sdk]
.NET Core runtimes installed:
Microsoft.AspNetCore.App 5.0.0-preview.1.20124.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.0-preview.1.20120.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 5.0.0-preview.1.20122.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Verify Scenarios:
1). Windows 10 RS5 X64 + .NET Core SDK build 5.0.100-preview.1.20125.9: Fail
2). Windows 10 RS5 X64 + .NET Core SDK build : 3.1.101 Pass

Copy from https://github.com/dotnet/aspnetcore/issues/19491

@dotnet-actwx-bot FYI

**Comment by lbnascimento** [comment]
@DotNetAppCompatFeiWang This bug was fixed in the master and will be present in the next incremental release.

This bug happened because the implementation of `Enum.CompareTo` was recently changed in the CoreCLR. For more info, see #1533 .
