### ISSUE TITLE
[QUESTION] Can't load a document based on a model that has a collection in its constructor.

### ISSUE THREAD

**Issue by koddek** [mbdavid/LiteDB#1532]
**Version**
v5.0.3
**Steps To Recreate**
1. use the given code in LinqPad
2. adjust the db paths.
3. uncomment the code to create a person and save it to db.
4. comment the code to create a person
5. now try to load a person using the constructor with the list
6. it throws.
7. comment out that constructor and try to load a person wit the constructor that does not have the list.
8. it successfully loads the person.
9. so the problem is found when the constructor has a collection as a parameter

**Describe the bug**
I am trying to load a person from the litedb database. 
if I use a constructor that has a list, the app throws an exception saying that it can't find a parameterless constructor. When I remove the list from the constructor, it loads fine. So I think that there's a bug when loading any type of collection in the constructor. I tried string[], List<string>, IEnumerable<string> and they all threw.

**Code to Reproduce**
``` csharp
void Main()
{
//	var person = new Person("1", "John Doe", new List<string> { "Gaming", "Coding", "Learning" });
//	AddPerson(person);

	var p = LoadPerson("1");
	p.Dump();
}

void AddPerson(Person person)
{
	using (var db = new LiteDatabase(@"%username%\Desktop\tmp_databases\people.db"))
	{
		var collection = db.GetCollection<Person>();
		collection.Upsert(person);
	}
}

Person LoadPerson(string id)
{
	using (var db = new LiteDatabase(@"%username%\Desktop\tmp_databases\people.db"))
	{
		var collection = db.GetCollection<Person>();
		return collection.FindById(id);
	}
}

public class Person
{
        // loads the persion when using this constructor
	//public Person(string id, string name)
	//{
	//	Id = id;
	//	Name = name;
	//	Hobbies = new List<string>();
	//}

         // trows exception when trying to load a person with this constructor. Even if I use [BsonCtor] it still throws
        [BsonCtor]
	public Person(string id, string name, List<string> hobbies)
	{
		Id = id;
		Name = name;
		Hobbies = hobbies;
	}

	public string Id { get; }
	public string Name { get; }
	public int Age { get; }
	public List<string> Hobbies { get; }
}
```

**Expected behavior**
I should be able to load a person with a public or internal constructor once all my parameters are supported by LiteDb and once the constructor is decorated with [BsonCtor]. This is a must-have feature especially for loading immutable objects from a database. Thank you very much for adding it and the other great work done in v5.   "JsonConstructorAttribute" <= this is awesome.

**Get Exception**
threw exception: 
    LiteDB.LiteException: Failed to create instance for type 'AppLibrary.Models.Person' from assembly 'AppLibrary.Models.Person, AppLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Checks if the class has a public constructor with no parameters. ---> System.ArgumentException: Type 'AppLibrary.Models.Person' does not have a default constructor (Parameter 'type')
**Screenshots/Stacktrace**
If applicable, add screenshots/stacktrace

**Comment by lbnascimento** [comment]
@koddek This is not exactly a bug, but a limitation of how the BSON deserialization works. It converts BSON types to equivalent .NET types, however there is no .NET equivalent to a BSON array, so arrays are converted to our `BsonArray` class. You would have to do something like this for your constructor to work:

```C#
[BsonCtor]
public Person(string id, string name, BsonArray hobbies)
{
    Id = id;
    Name = name;
    Hobbies = hobbies.Select(x => x.AsString).ToList();
}
```

We realize this is not ideal and we're thinking of ways to improve it. Also, we're reviewing our documentation to make this limitation clearer.
