### ISSUE TITLE
Support for OpenUploadStream()? 

### ISSUE THREAD

**Issue by MeirionHughes** [mbdavid/LiteDB#154]
Mongo has the feature where you can stream upload to the driver. usage: 

```
using (var stream = bucket.OpenUploadStream("filename"))
{
    var id = stream.Id; // the unique Id of the file being uploaded
    // write the contents of the file to stream using synchronous Stream methods
    stream.Close(); // optional because Dispose calls Close
}
```

this is useful if you're on the receiving end of a stream of undefined-length.  

is this something that is planned for v2?

**Comment by mbdavid** [comment]
Hi @MeirionHughes, not for v2. I know this feature but I have a problem to implemenet: I need all Stream length before start serialize document. I knw it's possible to be changed but it's not easy. I will add this in my features list to future versions.

**Comment by mbdavid** [comment]
Hi, it's done on next v3 version :)
