### ISSUE TITLE
Querying an array of documents nested within a field

### ISSUE THREAD

**Issue by sanjeevbaral** [mbdavid/LiteDB#1542]
I am new to LiteDB and have been trying it for a few days and loving it. However, I have run into a problem. I have a collection that contains an array of documents in one of the fields. I am trying to run a query that involves querying a certain field in the nested document array. What is the syntax? From one of the examples given for queries, I tried 

var test = collection.Find(Query.EQ("Tumors[*].site", 'C400'));

The above gives me the error - 
Left expression `($.Tumor[*]=>@.site)` returns more than one result. Try use ANY or ALL before operant.

"Tumors" field contains an array of documents that has "site" as one of the fields. The array of documents is created using BsonArray. Did I create the array incorrectly? I am not sure how to use ANY or ALL with the above query. Or I misunderstood the query syntax?

**Comment by sanjeevbaral** [comment]
Figured out. I just had to look through questions answered earlier. You may want to update the page that shows query examples. I needed 

var test = collection.Find(Query.EQ("Tumors[*].site ALL", "C400"));

**Comment by lbnascimento** [comment]
@sanjeevbaral Query static methods are not recommended anymore, they might be marked as deprecated in a future version.

You could use `collection.Find("Tumors[*].site ALL = 'C400'")` or, if you prefer SQL syntax, `db.Execute("select $ from collection where $.Tumors[*].site ALL = 'C400'")`.

**Comment by sanjeevbaral** [comment]
Thank you! Both worked beautifully!
