### ISSUE TITLE
[BUG]Find with enum consts has wrong behavior when BsonMapper.Global.EnumAsInteger = false

### ISSUE THREAD

**Issue by holyping** [mbdavid/LiteDB#1548]
**Version**
5.0.3

**Describe the bug**
When BsonMapper.Global.EnumAsInteger = false, then Find method does wrong behavior.

**Code to Reproduce**
```
var db = new LiteDbDatabase();

//This will return nothing because the linq expression will cast the enum value MyEnum.A to integer
//As the mapper option EnumAsInteger is false, enum values is stored as string,
//and the Find method below takes a comparsion between string and int, result always be false
var data = db.GetCollection<MyClass>().Find(x => x.Flag == MyEnum.A).ToList();
```

**Comment by lbnascimento** [comment]
@holyping This is not a bug, but a current limitation of the mapper: LINQ expressions are only supported if `EnumAsInteger = true`. I will update the documentation to state this more clearly.

**Comment by lbnascimento** [comment]
@holyping This issue was solved in the master branch and should be present in the next incremental release.
