### ISSUE TITLE
How to update and exsiting document

### ISSUE THREAD

**Issue by philbertphotos** [mbdavid/LiteDB#155]
IS there a way to update a field in an existing document or do you have to delete it and create a new one?

**Comment by philbertphotos** [comment]
Figured it out thanks for a great simple DB all needs to happen is update the Wiki with a few helpful coding scenarios

**Comment by mbdavid** [comment]
Hi @philbertphotos, thanks for using LiteDB. Wiki is out dated, I will try fix this as soon as I finish version 2.
