### ISSUE TITLE
[BUG] Rebuild() throws System.Threading.SynchronizationLockException

### ISSUE THREAD

**Issue by JensSchadron** [mbdavid/LiteDB#1551]
**Version**
Which LiteDB version/OS/.NET framework version are you using. **(REQUIRED)**
Latest version from master, commit 6c0886ec063f8bd272a91dd87973863e4668550d

**Describe the bug**
_A clear and concise description of what the bug is._
Calling `Rebuild()` on a LiteDatabase instance results in a SynchronizationLockException.

**Code to Reproduce**
_Write a small snippet to isolate your bug and could be possible to our team test. **(REQUIRED)**_
```csharp
var db = new LiteDatabase(new ConnectionString("Lite.db")
{
    Connection = ConnectionType.Direct
});

try
{
    db.Rebuild();
    Console.WriteLine("Rebuild succeeded.");
}
catch (Exception e)
{
    Console.WriteLine(e);
    throw;
}
```

**Expected behavior**
_A clear and concise description of what you expected to happen._
Should rebuild the datafile without throwing an exception.

**Screenshots/Stacktrace**
_If applicable, add screenshots/stacktrace_
```
System.Threading.SynchronizationLockException: The write lock is being released without being held.
   at System.Threading.ReaderWriterLockSlim.ExitWriteLock()
   at LiteDB.Engine.LockService.ExitExclusive() in /Users/jens/Documents/Projects/LiteDB/LiteDB/Engine/Services/LockService.cs:line 140
   at LiteDB.Engine.LiteEngine.Rebuild(RebuildOptions options) in /Users/jens/Documents/Projects/LiteDB/LiteDB/Engine/Engine/Rebuild.cs:line 87
   at LiteDB.LiteDatabase.Rebuild(RebuildOptions options) in /Users/jens/Documents/Projects/LiteDB/LiteDB/Client/Database/LiteDatabase.cs:line 273
   at LiteDB.Sandbox.Program.Main(String[] args) in /Users/jens/Documents/Projects/LiteDB/LiteDB.Sandbox/Program.cs:line 23
```

**Additional context**
_Add any other context about the problem here._
As far as my testing goes, the bug was introduced in commit 3bda0f068de9295ff033628976c82a524f2995fd as my code snippet was still working when I was testing with commit 8c956c541a9414ada9700f996475ea8a1847e216

**Comment by lbnascimento** [comment]
@JensSchadron Could you test with the current master? The transaction model was entirely rewritten.

**Comment by JensSchadron** [comment]
I'was following the progression of PR #1560 "live". But was going to close this ticket when it got merged into master.
That being the case, I'll close this ticket as it works just fine now.
