### ISSUE TITLE
[SUGGESTION] JsonSerializer should write certain Unicode characters without escaping

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#1552]
**JsonSerializer should write certain Unicode characters without escaping**

The original issue is opened in LiteDB.Studio:
https://github.com/mbdavid/LiteDB.Studio/issues/16

But the problem seems to be in the LiteDB `JsonSerializer` which uses oversimplified escaping approach:
https://github.com/mbdavid/LiteDB/blob/6c0886ec063f8bd272a91dd87973863e4668550d/LiteDB/Document/Json/JsonWriter.cs#L197-L207

Compare with more elaborated approach in MongoDB C# driver:
https://github.com/mongodb/mongo-csharp-driver/blob/b0b11348e1fb2418ca6a5999a2494db54ec186e5/src/MongoDB.Bson/IO/JsonWriter.cs#L737-L762

This is not necessarily a bug in LiteDB, just the current implementation.
But I would say, it's a serious limitation for not-Latin locales/users.

P.S. I can help with the PR and test if it is that straightforward as in the MongoDB C# driver. This would be easier if my other PR is merged first: https://github.com/mbdavid/LiteDB/pull/1531

**Comment by nightroman** [comment]
Hello. Any thoughts and/or plans on this issue? If it is going to be the long story, "no problem", but then I should probably use Json.NET for the time being... It would be useful to get some feedback for some planning.

**Comment by lbnascimento** [comment]
@nightroman Thank you for your suggestions and contributions to LiteDB. I've implemented your suggestion and it should be present in the next incremental release.

**Comment by nightroman** [comment]
@lbnascimento Many thanks for fixing this. The issue was a real pain!

**Comment by nightroman** [comment]
P.S. And thank you for merging my other PR. I am about to submit a new PR fixing serialization of non-generic dictionaries. Now it is easier.
