### ISSUE TITLE
[QUESTION] Any API to include data on deployment

### ISSUE THREAD

**Issue by meteorsnows** [mbdavid/LiteDB#1555]
```
public class Customer
{
    public ObjectId CustomerId { get; set; }
    public CustomerType type  { get; set; }
    public string Name { get; set; }
    public DateTime CreateDate { get; set; }
    public List<Phone> Phones { get; set; }
    public bool IsActive { get; set; }
}

public class CustomerType
{
    public ObjectId Id { get; set; }
    public string Type{ get; set; }

}
```

I wanted to include default data for Customer type while deploying the WPF app. Any API for that?
Id Type
1 Loyal
2 Normal

**Comment by lbnascimento** [comment]
@meteorsnows Sorry, I didn't understand your question. Could you explain what you're trying to do?

**Comment by meteorsnows** [comment]
I am trying to include default data for CustomerType Table

Id Type
1 Loyal
2 Normal

**Comment by lbnascimento** [comment]
@meteorsnows There is no specific collection initialization functionality. You would have to do it manually, something like this:

```C#
var types = db.GetCollection<CustomerType>();
if(types.Count() == 0)
{
	types.Insert(new CustomerType { Type = "Loyal" });
	types.Insert(new CustomerType { Type = "Normal" });
}
```

**Comment by meteorsnows** [comment]
Okie, fair enough. 
Good enough for me.
