### ISSUE TITLE
[BUG] Freezing in foreach inserting

### ISSUE THREAD

**Issue by Delog-ru** [mbdavid/LiteDB#1556]
**Version**
LiteDB v5.0.3
Windows 10 (1903)
.NET Framework 4.7.2

**Describe the bug**
Infinite freezing occurs in foreach inserting. Sometimes it freezes at the first try, sometimes you have to click button several times before it happens.

**Code to Reproduce**
```
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        public class SimpleClass
        {
            public int id { get; set; }
            public string name { get; set; }
        }

        int generation;
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            generation++;
            List<SimpleClass> list = new List<SimpleClass>();
            for (int i = 1; i < 2000; i++)
                list.Add(new SimpleClass() { name = $"My name is {generation}-{i}" });

            using (LiteDatabase db = new LiteDatabase("test.db"))
            {
                var col = db.GetCollection<SimpleClass>("MyCollection");
                foreach (SimpleClass sc in list)
                        col.Insert(sc);
            }
        }
    }
```

**Expected behavior**
No infinite freezing.

**Additional context**
It doesn't freeze if you use InsertBulk() but unfortunately there're cases where you can't use it. My example is deliberately simplified.

**Comment by lbnascimento** [comment]
@Delog-ru I could not replicate the issue. I created a forms project and created a button that does exactly what your example does. I presses the button probably hundreds of time and every time the operation eventually ended. I created the project on .NET Framework 4.7.2 using LiteDB v5.0.3 release and I'm running Windows 10 1803.

Is there anything else you could do to help me replicate the issue? Maybe provide a project and datafile in which the problem happens.

**Comment by Delog-ru** [comment]
@lbnascimento it's pretty much standard WPF project generated by VS 2019. I tried the new version 5.0.4 you released yesterday and it looks like the problem has gone.
