### ISSUE TITLE
[QUESTION] Issue with upgrading to version 5

### ISSUE THREAD

**Issue by eman1986** [mbdavid/LiteDB#1559]
Hello,

I'm currently using version 4 of LiteDb on a Xamarin project and I'm looking to upgrade it to version 5 but having an issue where when I read a collection, my objects come back as null.

Here's one such exmaple:

```cs
public class UserCache
{
    [BsonId]
    public ObjectId Id { get; set; } = ObjectId.NewObjectId(); // this is populated

    public DateTime DateCreated { get; set; } = DateTime.Now; // this is populated

    public User UserData { get; set; } // this comes back as null

    [BsonCtorAttribute]
    public UserCache(User userData)
    {
        UserData = userData;
    }
}
```

I did setup a mapper but that didn't seem to help either

```cs
var mapper = BsonMapper.Global;

mapper.Entity<UserCache>()
    .Id(x => x.Id)
    .Field(x => x.UserData, "UserData");
```

I'm clearly missing something but I'm not exactly sure what.

I appreciate the help.

**Comment by lbnascimento** [comment]
@eman1986 The parameters in the constructor annotated by `BsonCtorAttributes` must be of symple types (this is not in the documentation, I'll add it).

Given that all the properties in `UserCache` have public setters, you don't need to use `BsonCtorAttribute` anyway. Just remove this constructor - or, if you need it for something else, remove the attribute and create a parameterless constructor that does nothing.

**Comment by eman1986** [comment]
It wasn't working before I added that as currently with version 4 I didn't have a constructor used.

I added it because I thought I needed it.

**Comment by lbnascimento** [comment]
@eman1986 If no `BsonCtor` is found by the mapper, it then tries to use a parameterless constructor (or the default constructor, if there is no explicitly defined constructor). This will only work if your properties have public setters.

Your example class has public setters, so it should work with a parameterless/default constructor. In fact, I just tested it and it works fine.

**Comment by eman1986** [comment]
do I need a mapper for it to work? I didn't have one for v4

**Comment by lbnascimento** [comment]
@eman1986 No mapper should be necessary.

**Comment by eman1986** [comment]
I tried it again and I'm still seeing my type be null

**Comment by lbnascimento** [comment]
@eman1986 Could you send me the datafile you're using?

**Comment by eman1986** [comment]
I took a little more time debugging the xamarin app, and it seems like there's another process that may be the root cause. I don't think it's anything related to LiteDb itself now.
