### ISSUE TITLE
[QUESTION]Index values must have less than 255 bytes after upgrate to v5

### ISSUE THREAD

**Issue by ambyte** [mbdavid/LiteDB#1563]
I updates library to version 5.
When I open a database created in version 4 with upgrade=true flag I get an error
"Index key must be less than 255 bytes"
In the documentation is written for v4, "Index values must have at most 512 bytes"
For v5 "Index values must have less than 255 bytes"
I have a lot of clients who will lose data, because it is impossible to update the database
What can be done

**Comment by lbnascimento** [comment]
@ambyte Are there any custom indexes in the datafile (that is, an index over a field other than `_id`)?

If the error is happening on a custom index, I might create a way to upgrade the datafile without the indexes, which would circumvent the limitation. However, if the error is happening on an id index, I'm not sure what could be done (and index keys shouldn't be this long anyway, it would hurt performance a lot).

**Comment by ambyte** [comment]
Thank you, upgrade=DataOnly solved the problem, the database update goes without errors
