### ISSUE TITLE
[BUG] Cannot access a disposed object.

### ISSUE THREAD

**Issue by josephinenewbie** [mbdavid/LiteDB#1565]
**Version**
Upgrade to v.5.0.4 from v4.1.4

**Bug**
When try to .Find() with query inside, it hits the following error.

**Stacktrace**
```
System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(TimeoutTracker timeout)
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLock(TimeSpan timeout)
   at LiteDB.Engine.LockService.EnterTransaction()
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery()
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
   at LiteDB.LiteQueryable`1.ToDocuments()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
```
Code to Reproduce
 ```
   public IEnumerable<Member> GetActiveMembers()
        {
            return databaseInstance.GetCollection<Member>("Members")
                    .Find(Query.Or(
                            Query.GTE("ExpireOnDateTime", DateTime.Now),
                            Query.EQ("ExpireOnDateTime", BsonValue.Null)
                          ))
                    .OrderBy(x => x.Name);
        }
```

Againg, previously work fine in v4.1.4 :)

Thanks guys.

**Comment by lbnascimento** [comment]
@josephinenewbie I tested your example with a datafile upgraded from v4.1.4 to v5.0.4 and it worked fine. Could you maybe send me the datafile you're using?

**Comment by maxkatz6** [comment]
I think, it depends on GetActiveMembers usage, because IEnumerable is lazy and could be used after some internal staff was disposed

**Comment by josephinenewbie** [comment]
> @josephinenewbie I tested your example with a datafile upgraded from v4.1.4 to v5.0.4 and it worked fine. Could you maybe send me the datafile you're using?

Thanks, here is the data file.
[Data.zip](https://github.com/mbdavid/LiteDB/files/4332338/Data.zip)

@maxkatz6 yes, i am actually thinking is it related to IEnumerable  that trying to load after staff was disposed. :) Anyway lets me also see where the bug is.

**Comment by josephinenewbie** [comment]
Yes, just checked there is two issue in my implementation code, although same code is used in LiteDB 4.0.4

1. IEnumeralbe. I better not use it.
2. Probabaly the way I connect the LiteDB. Here:
`            
**MemberDataAccess memberDataAccess = new MemberDataAccess(await _databaseAccess.GetLiteDatabaseAsync());**

            try
            {
                memberList = memberDataAccess.GetActiveMembers();
            }
            catch (InvalidOperationException ioe)
            {
                return StatusCode(404,
                    string.Format("No active member was found. {0} .", ioe.Message)
                );
            }
            finally
            {
                _databaseAccess.ReleaseDatabaseInstance();
            }
            return StatusCode(200, memberList);`

Actualy the _databaseAccess class is like this:
`
 public IncentiveCommissionManagementDbAccess(string databaseLocation, int semaphoreSlimLimit)
        {
            connectionString = new ConnectionString(databaseLocation);
            semaphore = new SemaphoreSlim(semaphoreSlimLimit);
        }

        public async Task<LiteDatabase> GetLiteDatabaseAsync()
        {
            if (!await semaphore.WaitAsync(30000))
            {
                throw new TimeoutException();
            }

            **using (var db = new LiteDatabase(connectionString))
            {
                return db;
            }**
        }

        public void ReleaseDatabaseInstance()
        {
            semaphore.Release();
        }
`

So it said i am disposed...

(sorry for my messy code. I am still not really good at coding)

**Comment by josephinenewbie** [comment]
Thank you all. I have rewrite the way on connecting so that it can work well in v.5.0.4

**Comment by Lonli-Lokli** [comment]
@lbnascimento
I think there is an issue here, why does you have a restriction over IEnumerable? It's actually a good practice when you have to load only some part of the data and even might be not needed.

I have this issue as well. I do not have persistent connection to the database and I do not want to change IEnumerable to List

**Comment by lbnascimento** [comment]
@Lonli-Lokli I replied to you in the issue you opened (#1747).
