### ISSUE TITLE
[BUG] Log file continously grows in 5.0.4

### ISSUE THREAD

**Issue by Reetus** [mbdavid/LiteDB#1568]
5.0.4 Windows 10 .NET Core 3.1

![image](https://user-images.githubusercontent.com/6239195/76677241-ec637780-6606-11ea-8ed1-b0c20712bb64.png)

With my real database with 1.3million records the -log.db was up to 32gb.

**Comment by LennardF1989** [comment]
I can confirm I've seen this happen too in the latest version from NuGet. Log-File went from a few MB's to almost 5 times the size, after a rebuild file-size was 0 where the DB-File was only a few MB's again.

**Comment by lbnascimento** [comment]
@Reetus @LennardF1989 Could you test with the current master?
