### ISSUE TITLE
(Q?) Large file size

### ISSUE THREAD

**Issue by carlokok** [mbdavid/LiteDB#157]
I was comparing litedb against sqlite and noticed a rather large comparative file size. I have a 21mb sqlite db (30mb of sql) with an index on the string key, ended up as 64mb before I even got to add the index. (data is mostly like:
 db.keyword.insert { data: [10,"java.applet.Applet.Applet() constructor",0]}
)

Is this something expected or am I doing something wrong?

**Comment by mbdavid** [comment]
I don't know how SQLite implements storage system, but LiteDB is a not optimezed for use less space, it´s optimazed to be fast as possible. LiteDB uses pages (4kb) to store documents. When an page use more than 50% of size (2kb) the next document will use another page. All empty page area are reserved for document updates.
So, if you need change a document with extra bytes, the document will keep all in some page and will still fast to get this document. If you document needs grow more than this page area, will be created an Extended Page. Take a look on this class (I know this class in not easy, but I tried to comment as must as possible)

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/DbEngine/Services/DataService.cs

So, 3500 bytes document will use 1 data data. And 5000 bytes document will use 1 data page (as entry pointer) and 2 extended pages.

**Comment by carlokok** [comment]
Ah that does explain things. My documents are very small, on average they look like:
```{data: [10,"java.applet.Applet.Applet() constructor",0]} ```

so they'd use 4k for just this entry and in the end the file ends up large?

**Comment by mbdavid** [comment]
In 4K page, LiteDB will use (for small documents) like 2kb of data (so, if you document is 200 bytes size, will have ~ 10 document per page). The rest of 2kb on page will keep empty and next document will use another page. This 2kb empty area will be used in case that you update that documents.

So, when you insert only 1 document in an empty database LiteDB creates:
1 Header Page (page # 0) [1 per database]
1 Collection Page (will keep all informations about this page) [1 per collection]
1 Data Page (with your document in BSON format) [1 per N documents]
1 Index Page (with you document ID referenre) [1 per N indexes entry / per collection]
-----
4 pages = 20kb

Pages are reused. If you delete a document, next document can use this empty space. But are rules for that: One datapage has only document from same collection. On indexpage has only indexes tree for one collection/index.  Only when you empty a whole page, this page can be used for any other collection.
