### ISSUE TITLE
Object InnerList auto incremented id

### ISSUE THREAD

**Issue by oleksiivasylenko** [mbdavid/LiteDB#1570]
Hi, please explain how to auto increment sub object ids.

I have two classes(model), and one class for saving data.  
```
public class Author
{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<Post> Posts { get; set; } = new List<Post>();
}
```
```
public class Posts 
{
    public int Id { get; set; }
    public string Title { get; set; }
}
```
```
public static class DataAccess 
{
    static DataAccess()
    {
        //Line below also doesn't help
        //BsonMapper.Global.Entity<Post>().Id(x => x.Id, true); 
    }
    public static void UpsertAuthor(Author author)
    {
        using (var db = new LiteDatabase(AppSettings.DbPath))
        {
            var authors = db.GetCollection<Author>("authors");
            authors.Insert(author);
            //PostId's here is not incremeted. All inner objects have Id == 0
        }
    }
}
```
So how to auto increment Id's of inner list?
Also I've tried to mark Post.Id with [BsonId] attribute, this doesn't help as well. 
LiteDb  v5.0.4

**Comment by lbnascimento** [comment]
@oleksiivasylenko The auto-incremented id only works for the root document. Ids are used as unique identifiers inside a collection, and embedded documents are not stored in a collection of their own, so they don't need an id.

If you really want auto-incrementing id in inner objects, you can either implement it manually or use `BsonRef`
