### ISSUE TITLE
startswith query

### ISSUE THREAD

**Issue by sanjeevbaral** [mbdavid/LiteDB#1571]
Hello, 
The following gives me the syntax error - "Unexpected token `startswith` in position 41". I was looking at samples in https://github.com/mbdavid/LiteDB/wiki/Expressions and I see startswith is supported. Is startswith supported or something else is wrong with this query?

IBsonDataReader rdr = db.Execute("select $ from Patients WHERE nameLast startswith  'John'");

I figured I can use LIKE 'John%' if startswith is not supported.

**Comment by lbnascimento** [comment]
@sanjeevbaral The documentation in our github wiki is for v4, the updated documentation for v5 is in [our homepage](http://www.litedb.org/).

You should use `db.Execute("select $ from Patients WHERE nameLast like 'John%'");`.

**Comment by sanjeevbaral** [comment]
Thank you!
