### ISSUE TITLE
IN() in SQL

### ISSUE THREAD

**Issue by sanjeevbaral** [mbdavid/LiteDB#1572]
Hello,

I found that the following executes fine 

select $ from Patients WHERE $.Tumors[*].primarySite ALL  IN ('C447')

However, if I add more values to the list like this I get syntax error on the comma separating the values. 

select $ from Patients WHERE $.Tumors[*].primarySite ALL  IN ('C447','C500')

What is the correct syntax for specifying a list of values?

**Comment by lbnascimento** [comment]
@sanjeevbaral You should use `select $ from Patients WHERE $.Tumors[*].primarySite ALL IN ['C447','C500']`

**Comment by sanjeevbaral** [comment]
Thank you!
