### ISSUE TITLE
Filtering on child field using substring

### ISSUE THREAD

**Issue by sanjeevbaral** [mbdavid/LiteDB#1573]
Hello,

When I execute the following SQL which filters documents on a parent field, the query seems to get the correct result.

select $ from Patients WHERE substring($.nameFirst,0,1) ALL = 'd'

However, when I use the following SQL on a child field using substring I do not get any result.
 
select $ from Patients WHERE substring($.Tumors[*].dateOfDiagnosis,0,4) ALL = '2018'

What am I doing wrong?

**Comment by lbnascimento** [comment]
@sanjeevbaral `substring` can only be used with scalar expressions (expressions that evaluate to a single value), and `$.Tumors[*].dateOfDiagnosis` is an enumerable expression (it evaluates to all the dates of diagnosis).

You could use `select $ from Patients WHERE $.Tumors[*].dateOfDiagnosis ALL like '2018%'`.

**Comment by sanjeevbaral** [comment]
Thanks!
