### ISSUE TITLE
[QUESTION] How to Backup a LiteDB

### ISSUE THREAD

**Issue by josephinenewbie** [mbdavid/LiteDB#1579]
May I know how to backup a LiteDB?
Or 'rollback' to previously commits.
Or use Export json file is the best option?

(Because I am inserting data to LiteDB. But sometimes I just insert some improper JSON...)

Thanks!

**Comment by lbnascimento** [comment]
@josephinenewbie There is no way to rollback a commited transaction - however, an uncommited transaction can be manually rolled back and it will be discarded if the datafile is abruptly closed (process crashed, power loss etc.).

Regarding backup, there is no specific functionality for it. Making copies of the datafile should be fine for most purposes.

**Comment by josephinenewbie** [comment]
@lbnascimento 
Thank you so much :) that's reasonable.

**Comment by HolyOne** [comment]
Can I copy litedb file while my website is running?
Will it always create a working copy of the database? O is there a chance for it to be broken if there are write operations on the website while copying?

**Comment by lbnascimento** [comment]
@HolyOne You can't simply copy the file while it's open by LiteDB. You have to make sure the file is closed and that the log file is empty by running `db.Checkpoint()` before copying the file.
