### ISSUE TITLE
Notification on DB update

### ISSUE THREAD

**Issue by JohnnyBerg** [mbdavid/LiteDB#158]
Is it possible to get a notification when another user/process updates the database?

I want to read all data when the application starts, and do updates from time to time. I would be nice to inform other processes or users that data has changed, so they can get a update.

**Comment by Xicy** [comment]
i think use like a this `using System.IO;

namespace CAMP.Utiles
{
    public class FileWatcher
    {
        public delegate void FileChangedEventArgs(string path);

        public event FileChangedEventArgs FileChanged;

        public FileWatcher(string path, string filefilter)
        {
            var watcher = new FileSystemWatcher
            {
                Path = path,
                IncludeSubdirectories = true,
                NotifyFilter = NotifyFilters.LastWrite,
                Filter = filefilter,
                EnableRaisingEvents = true
            };

            watcher.Changed += (sender, args) => { FileChanged?.Invoke(args.FullPath); };
        }
    }
}`
