### ISSUE TITLE
[QUESTION] How do I fetch a list of KeyValuePair from db?

### ISSUE THREAD

**Issue by Mbogdan95** [mbdavid/LiteDB#1584]
For example I have `List<KeyValuePair<string, Rectangle>> listName` that I can write and update in the db. When I am checking with LiteStudio I can see that the list has been written correctly but when I fetch the list i get the number of elements in the list but the Key and the Value are empty

**Comment by lbnascimento** [comment]
@Mbogdan95 Is there any specific reason you're not using `Dictionary<string, Rectangle>`?

**Comment by Mbogdan95** [comment]
@lbnascimento no particular reason but changing from `List<KeyValuePair<string, Rectangle>>` to `Dictionary<string, Rectangle>` seems to have solved the problem. Thank you for this!
