### ISSUE TITLE
[BUG]FindById or FindOne returns NULL intermittently when executed from xUnit

### ISSUE THREAD

**Issue by HippyRock** [mbdavid/LiteDB#1585]
**Version**
Latest build commit: 811e6ad
.NET Core 3.1
Windows 10

**Describe the bug**
FindOne or FindById returns null sometimes although object is explicitly added into collection just before. I noticed it in xUnit tests, each time different test may fail.

**Code to Reproduce**
```
public class PlayerDto
    {
        [BsonId]
        public Guid Id { get; }
        public string Name { get; }

        public PlayerDto(Guid id, string name)
        {
            Id = id;
            Name = name;
        }
    }
```

3-4 identical tests in 2 two files (it is important as issues happen when you have multiple files, when all tests are in one file they seems working fine)

```
DtoTests1.cs/DtoTests2.cs
        [Fact]
        public void Dto_Read()
        {
            using (var db = new LiteDatabase(new MemoryStream()))
            {
                var id = Guid.NewGuid();
                var col = db.GetCollection<PlayerDto>();
                col.Insert(new PlayerDto(id, "Bob"));
                var player = col.FindOne(x => x.Id == id);
                Assert.NotNull(player);
            }
        }
        [Fact]
        public void Dto_Read2(){<same>}
        [Fact]
        public void Dto_Read3(){<same>}
        [Fact]
        public void Dto_Read4(){<same>}
```

**Expected behavior**
Tests shouldn't fail.

**Screenshots/Stacktrace**
<img width="1227" alt="Annotation 2020-03-22 120048" src="https://user-images.githubusercontent.com/42009164/77255372-e8ea7480-6c34-11ea-96fd-04baed2a2196.png">

**Additional context**
Each time different test may fail.

**Comment by lbnascimento** [comment]
@HippyRock This issue is fixed in the master and will be present in the next incremental release.
