### ISSUE TITLE
Why the v5 needs 2 files per db?

### ISSUE THREAD

**Issue by aelassas** [mbdavid/LiteDB#1588]
Why the v5 needs 2 files per db (*.db and *-log.db)? 

The v4 needed only 1 file per db (*.db).

**Comment by maxkatz6** [comment]
Duplicate of https://github.com/mbdavid/LiteDB/issues/1486 and https://github.com/mbdavid/LiteDB/issues/1462

**Comment by aelassas** [comment]
@maxkatz6 Thanks. I figured it out.
