### ISSUE TITLE
[QUESTION] How do you load a encrypted db from System.IO.Stream?

### ISSUE THREAD

**Issue by koddek** [mbdavid/LiteDB#1594]
First of all, thank you, LiteDB is AWESOME!!

I have a database in a dll stored as an EmbeddedResource. It is encrypted with a password.
How do I load it as a stream and pass it the password?.

If it is a file from disk, I can do this:
``` csharp
var connectionString="Filename=C:\database.db;Password=1234";
var db = new LiteDatabase(connectionString);
```
But I want to stream the EmbeddedResource directly without copying it to disk.
```csharp
var stream = GetAssembly().GetManifestResourceStream("MyApp.database.db");
var db = new LiteDatabase(stream); // how do I specify the password???
```

**Comment by lbnascimento** [comment]
You can do something like this:
```C#
var aesStream = new LiteDB.Engine.AesStream("mypassword", stream);
var db = new LiteDatabase(aesStream);
```

**Comment by lbnascimento** [comment]
@koddek You can do something like this:
```C#
var aesStream = new LiteDB.Engine.AesStream("mypassword", stream);
var db = new LiteDatabase(aesStream);
```

**Comment by koddek** [comment]
Thank you for your help @lbnascimento. It worked.
