### ISSUE TITLE
"ERROR: Invalid query operator" when I try: db.customers.find name like "John"

### ISSUE THREAD

**Issue by donners77** [mbdavid/LiteDB#16]
Hi. Thank you for making this amazing project available.  

I also really like your Web Shell concept.

However, when I tried the LiteDB Web Shell and followed the suggested Try commands I got at error message (see image below). This happened in both IE and Chrome.

![litedb web shell - google chrome_2015-03-27_11-05-58](https://cloud.githubusercontent.com/assets/5105950/6859796/7533eb76-d471-11e4-88fc-48ee69ee291a.jpg)

Kind regards,
Craig.

**Comment by mbdavid** [comment]
Hi donners77! Thansk for report this bug. Fixed update database version (web shell was in 0.8, current version is 0.9). Please, reload webshell and press F5 (html page stay in cache until F5). 

In next week I will release the big new version: v1.0 :)

**Comment by donners77** [comment]
Wow. That was quick.
Unfortunately I think you may have introduced a new bug...

![litedb web shell - google chrome_2015-03-27_11-56-13](https://cloud.githubusercontent.com/assets/5105950/6860155/6c7e89bc-d478-11e4-8b21-eaa3b6ebc581.jpg)

**Comment by mbdavid** [comment]
Ops, I forget that v.9 was not compatible with v0.8. I update localStorage. Please, another F5.

**Comment by donners77** [comment]
Great. Working now.

A question...

I have an existing console app and I'm interested in running the user interface in your web shell.

I'm not very experienced with web stuff (since to date I've just been working in C# code).

Besides the LiteDB-WebShell code repository, what other frameworks/environments would I need to install and learn? e.g. Nina? Nacy? IIS?

Is there a way to a way to run the web shell without IIS? e.g. using node or something like that?

Kind regards
Craig.

**Comment by mbdavid** [comment]
Hi Craig. Web shell for LiteDB is a very simple solution to .NET. Basicly it's 2 files: one html to show console UI (and a minimal JS to ajax) and and .ASHX handler for .NET. Inside ASHX I run LiteDB command shell and return result as HTML.
There is not "execution command" on Javascript or ASHX. JS only send text command and receive html result.
As server, I run in a simple IIS (with no special configuration). But you can run in any platform you want.

If you want create a rich web console, with more javascript api, take a look on this project: http://webshell.io/
