### ISSUE TITLE
Polymorphic records support on root level

### ISSUE THREAD

**Issue by scaredfinger** [mbdavid/LiteDB#160]
It is possible to save descending nested records but not root level ones.

```
class B {}
class D1: B {}
class D2: B {}
class C {
    public B[] Bs { get; set; }
}
var bs = new [] { new D1(), new D2() };
var col = db.GetCollection<B>();
col.InsertBulk(bs); // (1)
var recoveredBs = col.FindAll(); // Type lost!! They will all be plain Bs

var c = new C {
    Bs = new [] { new D1(), new D2() }
};
var col2 = db.GetCollection<C>();
col2.Insert(c);
var recoveredC = col2.FindAll().First(); // Type not lost....Bs contains a D1 and a D2
```

I attach boundary tests with both cases.
[polymorphic records.zip](https://github.com/mbdavid/LiteDB/files/231267/polymorphic.records.zip)

**Comment by mbdavid** [comment]
Hi @scaredfinger, are you using `mater` branch version to test this? I made some changes on BsonMapper serializer to support root level `_type`. Take a look on this class:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Serializer/Mapper/BsonMapper.Serialize.cs#L24

**Comment by scaredfinger** [comment]
Hi there!! I've been using the stable version. Not testing again code. Will try to test against the code and let you know!!

**Comment by sergiorykov** [comment]
Duplicate issue #71 
@mbdavid it seems three duplicates more then enough to publish it as RC2 :)
