### ISSUE TITLE
Updating a value in a document

### ISSUE THREAD

**Issue by philbertphotos** [mbdavid/LiteDB#161]
Is it possible to find a value and modify it in an existing index or do I need to make a new document at the same index.

**Comment by mbdavid** [comment]
When you run an Update an document, all indexes are checked if the field value are changed. If changed, drop/recreate an index. All this occurs here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/DbEngine/Actions/Update.cs#L46
