### ISSUE TITLE
[BUG] LINQ !Contains returns no result

### ISSUE THREAD

**Issue by MuhKuh7** [mbdavid/LiteDB#1613]
**Version**
5.0.5

**Describe the bug**
The negated LINQ contains does not work

**Code to Reproduce**
This should get me all my objects where StringList does not contain myString
`
results = results.Where(x => !x.StringList.Contains(myString));
`
The resulting collection is empty however.

A workaround is:
`
results = results.Where(x => x.StringList.All(t => t != myString));
`

**Comment by ajmal-ahmed** [comment]
this usually happens in LiteDB when you does not assign any value for a field it's considered as null (which in turn is a separate data type) and when you query that field you have to avoid those records. 
As of now you might see your code first might work as
`results = results.Where(x => (x.StringList!=null)&&(!x.StringList.Contains(myString)));`

**Comment by lbnascimento** [comment]
@MuhKuh7 This issue is fixed in master and its fix will be present in the next incremental release.

**Comment by MuhKuh7** [comment]
Tested and works.
Thx for the fast fix!
