### ISSUE TITLE
[BUG] Problems on using LiteDatabase with SharedEngine and MemoryStream

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#1614]
## Problems on using LiteDatabase with SharedEngine and MemoryStream

**Version**

The latest master.

**Describe the bug**

(1) Cannot specify just a memory stream. We have to invent some fake file name.
This is unexpected and error prone, any name will do, not carefully selected
names may clash.

BTW, for a memory stream use of a named mutex might be not quite right. It
should be in-process mutex, not global named. (Disclaimer: I am not an expert
in this area).

(2) Something is not quite right with the mutex, it fails on the first database operation.

**Code to Reproduce**

```csharp
using System.IO;
using LiteDB.Engine;
using Xunit;

namespace LiteDB.Tests.Engine
{
    public class SharedEndine_Tests
    {
        [Fact]
        public void DataStream_No_Filename()
        {
            using var mem = new MemoryStream();
            var settings = new EngineSettings()
            {
                DataStream = mem
            };
            using var engine = new SharedEngine(settings);
            //! System.NullReferenceException: 'Object reference not set to an instance of an object.'
        }

        [Fact]
        public void Just_DataStream()
        {
            using var mem = new MemoryStream();
            var settings = new EngineSettings()
            {
                DataStream = mem,
                Filename = "zzz" //! now we have to provide something
            };
            using var engine = new SharedEngine(settings);
            using var db = new LiteDatabase(engine);
            var col = db.GetCollection("test");
            col.Insert(new BsonDocument() { ["_id"] = 1 });
            //! System.Threading.AbandonedMutexException: 'The wait completed due to an abandoned mutex.'
        }
    }
}
```

**Expected behavior**

Both tests should pass.
They fail with NRE and AbandonedMutexException.

**Comment by lbnascimento** [comment]
Problem 1 can be fixed easily (I was thinking of using the hashcode of the `MemoryStream` to name the mutex). However, I could not reproduce problem 2, it works just fine here.

Anyway, I don't think there is much sense in using `SharedEngine` with a `MemoryStream`. `SharedEngine` is meant for multi-process usage, it uses a system-wide mutex to control file access and closes the file/releases the mutex after every operation.

**Comment by nightroman** [comment]
> Anyway, I don't think there is much sense in using `SharedEngine` with a `MemoryStream`. `SharedEngine` is meant for multi-process usage, it uses a system-wide mutex to control file access and closes the file/releases the mutex after every operation.

Hmm, maybe... Then what is the recommended scenario for using a memory database from several threads of the same app?

**Comment by nightroman** [comment]
> Problem 1 can be fixed easily (I was thinking of using the hashcode of the `MemoryStream` to name the mutex). However, I could not reproduce problem 2, it works just fine here.

Like I said, I think this is wrong to use a named mutex for a memory stream. If I am not mistaken named mutex works for all apps on a machine. This does not make sense for a memory stream in a particular app, each instance uses its own memory steam.

**Comment by nightroman** [comment]
Update on the second test `Just_DataStream`. For some reason I cannot reproduce the problem with this 1 thread scenario. Maybe one of the recent changes affected this test.

But I still have the same exception on using the similar scenario from several threads.

I can create a more complex test with 2+ threads. But now I am not sure, you say this is not the "right way". Then what is the "right way"? I will use it and if it works then this is not the issue.

**Comment by nightroman** [comment]
Update 2. The original test still fails, just not always. It's some timing issue of something else is unstable.

Can you try the same test in a loop?

```csharp
[Fact]
public void Just_DataStream()
{
    for (int i = 0; i < 10000; ++i)
    {
        using var mem = new MemoryStream();
        var settings = new EngineSettings()
        {
            DataStream = mem,
            Filename = "zzz" //! now we have to provide something
        };
        using var engine = new SharedEngine(settings);
        using var db = new LiteDatabase(engine);
        var col = db.GetCollection("test");
        col.Insert(new BsonDocument() { ["_id"] = 1 });
        //! System.Threading.AbandonedMutexException: 'The wait completed due to an abandoned mutex.'
    }
}
```

**Comment by lbnascimento** [comment]
I tried your loop example and it also worked fine. Not sure what is going on at this point.

Anyway, the recommended way to use a memory database amongst multiple threads would be to create a single instance of  `LiteDatabase` using a `MemoryStream` and sharing this instance of `LiteDatabase` between the threads.

**Comment by nightroman** [comment]
A note about potential gotcha with the first issue.
A mutex name is defined as `settings.Filename.ToLower().Sha1()`.
So, for these 4 paths pointing to the same file we get 4 different mutex names:

- `C:\tmp\my.db`
- `C:/tmp/my.db` (different slashes)
- `C:\\tmp\\my.db` (double slashes)
- `.\my.db` (relative path, given the current directory is C:\tmp)
- etc.

The path should be converted to full and normalized before using it for mutex name.
