### ISSUE TITLE
[QUESTION] LiteDB not ignoring property annotated by NotMappedAttribute

### ISSUE THREAD

**Issue by ahmedflix25** [mbdavid/LiteDB#1617]
**Version**
Which LiteDB version/OS/.NET framework version are you using. **(REQUIRED)**
5.0.5/ windows 10 1909/ .net core 3.1
**Describe the bug**
marking property as [NotMapped] do nothing

**Code to Reproduce**
```
[NotMapped]
public bool IsSelected { get; set; }
```

**Expected behavior**
this property shouldn't be a part from the collection

**Comment by lbnascimento** [comment]
@ahmedflix25 LiteDB does not use the `NotMappedAttribute`. If you want to ignore a property, you must annotate it with `BsonIgnoreAttribute`. Alternatively, if you can't or won't add external references to your class, you can use our fluent mapping API.

```C#
var mapper = BsonMapper.Global;
mapper.Entity<MyClass>()
    .Ignore(x => x.IsSelected);
```

**Comment by ahmedflix25** [comment]
ok, thanks
