### ISSUE TITLE
[BUG] 5.0.5 Shared mode not working in Xamarin iOS

### ISSUE THREAD

**Issue by zelsius** [mbdavid/LiteDB#1618]
**Version**
LiteDB: 5.0.5
Project: Xamarin iOS w/MvvmCross
App Solution: Mono Framework MDK 6.10.0.95 (Preview)
Core Solution: .NET Standard 2.0

**Describe the bug**
Trying to initiate a connection to a LiteDatabase, but upon creation, I am thrown an error stating that **Mutex (bool initiallyOwned, string name)** is not supported.

**Code to Reproduce**
```
private static LiteDatabase _db = null;

private ConnectionString GetConnectionString()
{
    var root = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
    var dbpath = Path.Combine(root, "AppName");

    if (!Directory.Exists(dbpath))
        Directory.CreateDirectory(dbpath);

    var fileName = dbpath + "/database.db";

    return new ConnectionString()
    {
        Filename = fileName,
        Upgrade = UpgradeOption.True,
        Connection = ConnectionType.Shared

    };
}

public LiteDatabase Database()
{
    if (_db == null)
        _db = new LiteDatabase(GetConnectionString());
        //EXCEPTION OCCURS HERE

    return _db;
}

//Run this function to init DB.
private void InitDB()
{
    var users = Database().GetCollection<User>("user").FindAll();
}

```

**Expected behavior**
Database created and ready for use.

**Screenshots/Stacktrace**

Stack Trace:
`{System.NotSupportedException: Specified method is not supported.
  at System.Threading.Mutex..ctor (System.Boolean initiallyOwned, System.String name) [0x00006] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.Threading/Mutex.cs:180 
  at LiteDB.SharedEngine..ctor (LiteDB.Engine.EngineSettings settings) [0x0002b] in <29f0b34292254704bfb9a87692bfd38d>:0 
  at LiteDB.ConnectionString.CreateEngine () [0x0004e] in <29f0b34292254704bfb9a87692bfd38d>:0 
  at LiteDB.LiteDatabase..ctor (LiteDB.ConnectionString connectionString, LiteDB.BsonMapper mapper) [0x00034] in <29f0b34292254704bfb9a87692bfd38d>:0 
  at App.Core.Services.Repository.Database () [0x00002] in /Users/.../Documents/GitHub/...-Xamarin/App.Core/Services/Repository.cs:95 }`

**Additional context**
See [https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Threading/Mutex.cs](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Threading/Mutex.cs) for Mutex function used by Xamarin iOS.

**Comment by lbnascimento** [comment]
@zelsius Is there a specific reason you're using shared mode in Xamarin? Shared mode is meant for multiprocess usage of the same datafile and, as far as I know, this is not an issue on mobile applications.

**Comment by lbnascimento** [comment]
@zelsius Given that Xamarin.iOS does not support named (system-wide) mutex, there's not much we can do regarding Shared mode - other than a complete rewrite. I've added a catch for `NotImplementedException` that throws an exception with a message explaining the limitation. Out documentation will be updated to reflect this limitation.

**Comment by zelsius** [comment]
> @zelsius Given that Xamarin.iOS does not support named (system-wide) mutex, there's not much we can do regarding Shared mode - other than a complete rewrite. I've added a catch for `NotImplementedException` that throws an exception with a message explaining the limitation. Our documentation will be updated to reflect this limitation.

No particular reason for using shared. I just updated from LiteDB v4 and wanted to test the database in Shared mode as this was from what I have understood, the default in v4.

I am currently using Direct mode, and it seems to work pretty well, except an exception from time to time on **ReaderWriterLockSlim.TryEnterReadLockCore** stating that **recursive read lock acquisitions not allowed in this mode**, but I believe this issue is located in my solution and not in LiteDB v5.0.5.

Many thanks for this commit and your swift reply.

**Comment by mportune-bw** [comment]
We've run into this issue when sharing a database between an iOS app and the app's extensions, which run in separate processes.  Since shared mode doesn't appear to be possible on iOS, is there a way we can force a collection to reload without tearing down and rebuilding the db connection?
