### ISSUE TITLE
[BUG] System.Globalization.CultureNotFoundException - Invalid culture

### ISSUE THREAD

**Issue by aelassas** [mbdavid/LiteDB#1619]
**Version**

LiteDB 5.0.5/Windows 10/.NET framework version 4.6.1

**Describe the bug**

I get the following error when starting LiteDB:

Invalid culture

Exception Info: System.Globalization.CultureNotFoundException
at System.Globalization.CultureInfo..ctor(System.String, Boolean)
at LiteDB.LCID.GetCulture(Int32)
at LiteDB.Collation..ctor(Int32, System.Globalization.CompareOptions)
at LiteDB.Engine.EnginePragmas.<.ctor>b__36_7(LiteDB.BufferSlice)
at LiteDB.Engine.EnginePragmas..ctor(LiteDB.BufferSlice, LiteDB.Engine.HeaderPage)
at LiteDB.Engine.HeaderPage.LoadPage()
at LiteDB.Engine.LiteEngine..ctor(LiteDB.Engine.EngineSettings)
at LiteDB.ConnectionString.CreateEngine()
at LiteDB.LiteDatabase..ctor(LiteDB.ConnectionString, LiteDB.BsonMapper)

**Code to Reproduce**

```cs
private static LiteDatabase _db;

public Db(string connectionString) : base(connectionString)
{
	_db = new LiteDatabase(ConnectionString);
}

public override void InsertUser(Core.Db.User user)
{
    var col = _db.GetCollection<User>(Core.Db.User.DocumentName);
    user.CreatedOn = DateTime.Now;
    col.Insert(new User
    {
        CreatedOn = user.CreatedOn,
        Email = user.Email,
        ModifiedOn = user.ModifiedOn,
        Password = user.Password,
        Username = user.Username,
        UserProfile = user.UserProfile
    });
    //col.EnsureIndex(u => u.Username, "LOWER($.Username)");
    col.EnsureIndex(u => u.Username);
    col.EnsureIndex(u => u.UserProfile);
}

// ...

public override void Dispose()
{
    _db.Dispose();
}

```

**Comment by lbnascimento** [comment]
@aelassas Could you provide the datafile you're using? You can annex it here or send it to me at lbnascimento@inf.ufrgs.br

**Comment by aelassas** [comment]
@lbnascimento Do you want .db file?

**Comment by lbnascimento** [comment]
@aelassas Yes, that would be helpful (this issue is really dependant on the datafile you're using)

**Comment by aelassas** [comment]
@lbnascimento I've just sent you an email with the data file in attachments. The object of the email is Wexflow.db.

**Comment by lbnascimento** [comment]
@aelassas Your datafile is opening without problems here, and the collation is detected as "fr-MA/IgnoreCase". What connection string are you using?

**Comment by aelassas** [comment]
@lbnascimento Here is the connection string: 

```cs
"Filename=C:\Wexflow\Database\Wexflow.db; Connection=direct"
```

**Comment by lbnascimento** [comment]
@aelassas I can't reproduce the issue. I'm running Windows 10, I tested it with the v5.0.5 release and I created a test project running .NET Framework 4.6.1.

The stack trace indicates that the error happened in the `CultureInfo` constructor, maybe somehow your OS can't find the culture `fr-MA`.

**Comment by aelassas** [comment]
@lbnascimento Is it possible to set InvariantCulture in the collation or set the collation of the os when the engine starts?

**Comment by lbnascimento** [comment]
@aelassas Yes, but you need to be able to open the datafile. Just run:
```C#
db.Rebuild(new LiteDB.Engine.RebuildOptions { Collation = new Collation("/IgnoreCase") });
```

**Comment by aelassas** [comment]
@lbnascimento I can't open the datafile so that's the problem. The [documentation](https://www.litedb.org/docs/collation/) says that when an unsupported culture is detected, the rebuild defaults to CultureInfo.InvariantCulture. So, why LiteDB is throwing the exception?

**Comment by lbnascimento** [comment]
@aelassas This happens on rebuild, but that's what not what happened: this file was created on an environment where "fr-MA" is a valid culture and is being run on an environment that can't find the culture "fr-MA", that's why it's failing. Anyway, I've sent you an email with the datafile rebuilt with `InvariantCulture`.

**Comment by aelassas** [comment]
@lbnascimento Is it safe to rebuild the database after opening it like this:

```cs
private static LiteDatabase _db;

public Db(string connectionString) : base(connectionString)
{
    _db = new LiteDatabase(ConnectionString);
    _db.Rebuild(new RebuildOptions { Collation = new Collation("/None") }); // /IgnoreCase, en-US/None, en-US/IgnoreCase, en-US/IgnoreCase,IgnoreSymbols
}
```

**Comment by lbnascimento** [comment]
@aelassas Yes, I don't see any issues with it.

**Comment by aelassas** [comment]
@lbnascimento  All fixed. Thanks!
