### ISSUE TITLE
[QUESTION] How can I store an array of strings in this database?

### ISSUE THREAD

**Issue by riksking** [mbdavid/LiteDB#1620]
I don`t wanna create new class to do this. 
I need fast way to store and read array of strings and nothing else.

Is there a method to do this?
If not, are there plans to add?

**Comment by lbnascimento** [comment]
@riksking I took the code you mentioned in #1597 and modified it:

```C#
public static void WriteToExistDb(IEnumerable<string> chunk, string pathToDb, string tableName)
{
	using (var testDb = new LiteDatabase(pathToDb))
	{
		var col = testDb.GetCollection(tableName);
		foreach (var str in chunk)
		{
			col.Insert(new BsonDocument { ["value"] = str });
		}
	}
}

public static IEnumerable<string> ReadFromExistDb(string pathToDb, sting tableName)
{
	using (var testDb = new LiteDatabase(pathToDb))
	{
		var col = testDb.GetCollection(tableName);
		foreach(var doc in col.FindAll())
		{
			yield return doc["value"].AsString;
		}
	}
}
```

**Comment by riksking** [comment]
@lbnascimento Thanks a lot.
It seems to me that it would be nice if it were possible to save primitive types without casting to a type BsonDocument. More precisely, that it should be implemented inside LiteDb. 
As for example, this is implemented with an implicit identifier, which is created automatically if it is not in the specified type.
