### ISSUE TITLE
[QUESTION] Why is the max index string/binary length 1021, not 1023?

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#1621]
The latest master supports longer indexes, the maximum length is 1023. This is really great.

But in fact the maximum string (and probably binary) length is 1021 (try and see errors on 1022 or 1023). Why is this?

As far as I understand these two "difference" bytes are data type and length bytes packed together.
And presumably they may encode the length 1023, right? Then why to limit the allowed length to 1021?

P.S. If this limit 1021 is really required then it should be documented explicitly. Because the documented "1023 after serialization" is less helpful. It is not clear what the actual string/binary length is. Developers may want to know the exact actual limit for checks in applications before serializing and getting exceptions.

**Comment by lbnascimento** [comment]
@nightroman You are correct: in practice, string and binary lengths in index entries are limited to 1021 bytes. I will update the documentation to reflect this limitation.

**Comment by nightroman** [comment]
I am still curious why? Two bytes with packed type and length may keep length info up to 1023, right?

**Comment by nightroman** [comment]
And there is a bug / inconsistent checks:

In here the key length is limited by 1023:
        
        public static void WriteIndexKey(this BufferSlice buffer, BsonValue value, int offset)
        {
            ENSURE(value.GetBytesCount(false) <= MAX_INDEX_KEY_LENGTH, "index key must have less than 1023 bytes");

But in these two places it is limited by 1021:

        public void Insert(IEnumerable<KeyValuePair<BsonValue, PageAddress>> items, int order, BufferSlice buffer)
                var keyLength = GetKeyLength(item.Key);
                if (keyLength > MAX_INDEX_KEY_LENGTH) throw LiteException.InvalidIndexKey($"Sort key must be less than {MAX_INDEX_KEY_LENGTH} bytes.");


        private IndexNode AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, byte level, IndexNode last)
        {
            // get a free index page for head note
            var bytesLength = IndexNode.GetNodeLength(level, key, out var keyLength);

            // test for index key maxlength (length must fit in 1 byte)
            if (keyLength > MAX_INDEX_KEY_LENGTH) throw LiteException.InvalidIndexKey($"Index key must be less than {MAX_INDEX_KEY_LENGTH} bytes.");

**Comment by nightroman** [comment]
Either the first check should be corrected or the last two. I think it is better to correct the last two checks. I still have no answer why 1021 is the limit, not 1023 (which fits to 2 bytes together with type).
