### ISSUE TITLE
[QUESTION] Could you please release the recent fixes and changes?

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#1624]
Could you please release the recent fixes and changes? v5 is officially not beta but production and every reported bug or issue is a show stopper for some users.

Do not get this as a complain please. The project is amazing and the team response too. Just do not hold the available fixes for long please, if it is technically possible.

If it is not technically possible, could you share your pain points? We/users may help perhaps.

Thank you for your great work.

**Comment by mbdavid** [comment]
Hi @nightroman, current version has 14 days and only 47 downloads (in nuget couter)... and we are already working in 5.1 "single datafile" version.

Tomorrow I release next 5.0.6.

**Comment by nightroman** [comment]
I think it does not matter how many days passed since the last release or how many downloads happened. If a user reported bug is fixed and tests pass it should be released. What is the reason to hold it?

NB But if we pay attention to these numbers then I find them worrying, 30 days old release has 3,766 download and 14 days release only 47.

**Comment by nightroman** [comment]
Also, people keep posting issues about already fixed bugs. The answer "this is already fixed and will be available in the incremental release" is quite frequent.
