### ISSUE TITLE
DateTime field not handling UTC

### ISSUE THREAD

**Issue by thosoft** [mbdavid/LiteDB#163]
1. Store original in UTC, but loading always local.
2. Different result between FindById and Find when _id is DateTime type in UTC.

Workaround, use Ticks in long/Int64 of DateTime instead of DateTime

**Comment by mbdavid** [comment]
LiteDB uses BSON specification to store DateTime. In BSON, DateTime are store as milliseconds from UNIX Epoch (using UTC)

http://bsonspec.org/spec.html

Here is how was implemented:

Write:
https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Serializer/Bson/BsonWriter.cs#L112

Read:
https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Serializer/Bson/BsonReader.cs#L113
