### ISSUE TITLE
[Bug] Exception while de-serializing Uris

### ISSUE THREAD

**Issue by nik-net** [mbdavid/LiteDB#1630]
If the stored value in a document is URI, then this code statement throws error (class BsonMapper.cs)

```
private void DeserializeDictionary(Type K, Type T, IDictionary dict, BsonDocument value)
        {
            var isKEnum = K.GetTypeInfo().IsEnum;
            foreach (var el in value.GetElements())
            {
               
                    var k = isKEnum ? Enum.Parse(K, el.Key) : Convert.ChangeType(el.Key, K); //Convert.ChangeType will throw error if K is Uri and el.Key is a string such as https://dev.azure.com
                    var v = this.Deserialize(T, el.Value);
                    dict.Add(k, v);
               }
        }
```

Modifying this line to 

`var k = isKEnum ? Enum.Parse(K, el.Key) : K == typeof(Uri) ? new Uri(el.Key) : Convert.ChangeType(el.Key, K);`

works.

**Comment by lbnascimento** [comment]
@nik-net This is not a bug in LiteDB, but a limitation in `Convert.ChangeType`: all this method does is try to cast an object to another type, and there is no valid cast from `string` to `Uri` (LiteDB serializes `Uri` as their string representation). It is possible to create a `Uri` from a `string` with the `Uri` constructor, and that is what your second example does, but `ChangeType` is not aware of that.

**Comment by nik-net** [comment]
> @nik-net This is not a bug in LiteDB, but a limitation in `Convert.ChangeType`: all this method does is try to cast an object to another type, and there is no valid cast from `string` to `Uri` (LiteDB serializes `Uri` as their string representation). It is possible to create a `Uri` from a `string` with the `Uri` constructor, and that is what your second example does, but `ChangeType` is not aware of that.

Thank you, yes I understand that this is due to ChangeType's inability to convert a string to it's URI representation. Given this known limitation would you be looking to handle this edge case in the code?

**Comment by lbnascimento** [comment]
@nik-net Sorry, for whatever reason I didn't realize the `DeserializeDictionary` was in our BsonMapper, I thought it was some code of yours. I'll add your fix.
