### ISSUE TITLE
[BUG]Excluding And and Or Expressions

### ISSUE THREAD

**Issue by kampilan** [mbdavid/LiteDB#1633]
Which LiteDB version/OS/.NET framework version are you using. **(REQUIRED)**
5.0.7

**Describe the bug**

The code below is missing And and Or

        private string GetOperator(ExpressionType nodeType)
        {
            switch (nodeType)
            {
                case ExpressionType.Add: return " + ";
                case ExpressionType.Multiply: return " * ";
                case ExpressionType.Subtract: return " - ";
                case ExpressionType.Divide: return " / ";
                case ExpressionType.Equal: return " = ";
                case ExpressionType.NotEqual: return " != ";
                case ExpressionType.GreaterThan: return " > ";
                case ExpressionType.GreaterThanOrEqual: return " >= ";
                case ExpressionType.LessThan: return " < ";
                case ExpressionType.LessThanOrEqual: return " <= ";
                case ExpressionType.AndAlso: return " AND ";
                case ExpressionType.OrElse: return " OR ";
            }

**Code to Reproduce**
Not needed

**Expected behavior**

        private string GetOperator(ExpressionType nodeType)
        {
            switch (nodeType)
            {
                case ExpressionType.Add: return " + ";
                case ExpressionType.Multiply: return " * ";
                case ExpressionType.Subtract: return " - ";
                case ExpressionType.Divide: return " / ";
                case ExpressionType.Equal: return " = ";
                case ExpressionType.NotEqual: return " != ";
                case ExpressionType.GreaterThan: return " > ";
                case ExpressionType.GreaterThanOrEqual: return " >= ";
                case ExpressionType.LessThan: return " < ";
                case ExpressionType.LessThanOrEqual: return " <= ";
                case ExpressionType.And: return " AND ";
                case ExpressionType.AndAlso: return " AND ";
                case ExpressionType.Or: return " OR ";
                case ExpressionType.OrElse: return " OR ";
            }

It makes no sense to exclude And and Or as they differ from AndAlso and OrElse only in logical short-cutting which appears to be inconsequential  to your use-case.

X == 0 & Y == 1  And Evaluates entire expression even if X != 0
X == 0 && Y == 1 AndAlso. This shortcuts the expression if X != 0

In you use-case this nuance is meaningless so why exclude them?

Thanks
Jim

**Comment by lbnascimento** [comment]
@kampilan Done. It will be present in the next incremental release.

**Comment by nightroman** [comment]
@kampilan I am curious, why is this needed in practice? (Not criticizing in any way, just want to learn)

**Comment by nightroman** [comment]
@lbnascimento Do we or will we have the same form in LiteDB string expressions?

**Comment by lbnascimento** [comment]
@lbnascimento While it could be done, I'm not sure there's any point to it.

**Comment by kampilan** [comment]
It's needed because it is in fact a legitimate  expression.  Like me, most people use Expression.And and Expression.Or. Technically one should use AndAlso and OrElse. I have in fact changed my implementation to use AndAlso and OrElse. It is more correct to do so. But And and Or  still need to be supported in this use-case because they are perfectly valid.

**Comment by lbnascimento** [comment]
@kampilan I think @nightroman was talking about having actual non-short-circuit operators in BsonExpressions, which I don't think is useful. The solution that you proposed in your first post (and which was implemented, by the way) merely maps `&` to `AND` and `|` to `OR`, which are then executed as short-circuit operators.

**Comment by nightroman** [comment]
I am confused by the example `X == 0 & Y == 1` and the tests following the change:

```csharp
TestPredicate<User>(x => x.Salary > 50 && x.Name == "John", "((Salary > @p0) AND (Name = @p1))", 50, "John");
TestPredicate<User>(x => x.Salary > 50 & x.Name == "John", "((Salary > @p0) AND (Name = @p1))", 50, "John");
TestPredicate<User>(x => x.Salary > 50 || x.Name == "John", "((Salary > @p0) OR (Name = @p1))", 50, "John");
TestPredicate<User>(x => x.Salary > 50 | x.Name == "John", "((Salary > @p0) OR (Name = @p1))", 50, "John");
```

`|` and `&` are not Boolean operators at all. What are these tests doing and checking is not clear.

**Comment by nightroman** [comment]
These are **bitwise** AND and OR operators. They operate on integers and return integers. Why in the above cases they are treated as Boolean operators is not clear. Technically, translation to string expressions is even wrong. Maybe I miss something simple.

**Comment by lbnascimento** [comment]
@nightroman They are overloaded operators: between two integers, they act as bitwise and/or; between two bools, they act as non-short-circuit logic operators. Check the [official C# documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/boolean-logical-operators#logical-and-operator-).

**Comment by nightroman** [comment]
Ah, I see now. Yes, learned something new! TBH, never used & and | as Booleans for many years :)

**Comment by kampilan** [comment]
lbnascimento sorry 2 discussions going on at the same time. I agree unneeded,

nightroman I also learned something new. In my opinion poor naming and documentation on MS part.
