### ISSUE TITLE
Slow write speeds 

### ISSUE THREAD

**Issue by CarbonEdge** [mbdavid/LiteDB#164]
Hey

I did a little test and LiteDB was really slow, Is my code bad?
This just read ten text files and saved the text and line number. Each file was about 1mb, the whole folder was less than 13mb. 

Do you have any benchmark tests?

 public class Computer
        {
            public int Id { get; set; }
            public string text { get; set; }
            public int lineNumber { get; set; }
            public string type { get; set; }
        }

        private void button1_Click(object sender, EventArgs e)
        {
            using (var db = new LiteDatabase(@"C:\Users\Desktop\Test\MyData.db"))
            {
                // Get a collection (or create, if doesn't exist)
                var col = db.GetCollection<Computer>("PC");
                string[] files = Directory.GetFiles(@"C: \Users\Desktop\Test\Sample data", "*.txt", SearchOption.AllDirectories);
                foreach(string file in files)
                {
                    using (StreamReader sr = new StreamReader(file))
                    {
                        string s;
                        int line = 0;
                        while((s=sr.ReadLine())!=null)
                        {
                            var pc = new Computer
                            {
                                text = s,
                                lineNumber = line
                            };
                            line++;
                            col.Insert(pc);
                        }
                    }
                }//                
            }//exit db
        }//exit button

**Comment by mbdavid** [comment]
Hello @CarbonEdge, your code are not best optimized for write operation. In this case, each insert will be inside an transaction. So, for each document, will be created a journal file, write 2 or 3 pages on journal file, write in database file and the delete journal file.

When you have loop insert operation, the best way is use `col.Insert(IEnumerable<T> docs)`. Test with this:

```
 using (var db = new LiteDatabase(@"C:\Users\Desktop\Test\MyData.db"))
{
    var col = db.GetCollection<Computer>("PC");
    col.Insert(GetComputers());
}

private IEnumerable<Computer> GetComputers()
{
    string[] files = Directory.GetFiles(@"C: \Users\Desktop\Test\Sample data", "*.txt", SearchOption.AllDirectories);
    foreach(string file in files)
    {
        using (StreamReader sr = new StreamReader(file))
        {
            string s;
            int line = 0;
            while((s=sr.ReadLine())!=null)
            {
                var pc = new Computer
                {
                    text = s,
                    lineNumber = line
                };
                line++;
                yield return pc;
            }
        }
    }
}
```

Now, all documents will be saved in a single transaction.
