### ISSUE TITLE
[QUESTION] Find if database exists and seed data after being created

### ISSUE THREAD

**Issue by mdmoura** [mbdavid/LiteDB#1640]
When using the following:

    using(var db = new LiteDatabase(@"MyData.db"))
    }

LiteDB creates a new database if it does not exist.

Is there a way to determine if a database exists or not? Or if it is empty?

I would like to seed the database with data but only after its creation.

**Comment by lbnascimento** [comment]
@mdmoura I think something like this would work for you:
```C#
using(var db = new LiteDatabase(@"MyData.db"))
{
    int colCount = db.GetCollectionNames().Count();
    if (colCount == 0)
    {
        //initialization code here
    }
}
```

**Comment by mdmoura** [comment]
@lbnascimento I have been reading your docs and I found different information.

For example, in [here](https://dev.listera.top/docs/litedb/LiteDB-v1/#updating-database-version) there is an OnVersionUpdate method and a version can be included in the connection string.

But in source code and in [here](http://www.litedb.org/docs/connection-string/) there is no such option.

I am trying the following to seed initial data:

 ```
 public class Database : LiteDatabase {
    
    public Database(String connectionString, DatabaseMapper databaseMapper) : base (connectionString, databaseMapper) { 

      if (base.UserVersion == 0) {
        // seed initial data
       base.UserVersion = base.UserVersion + 1;
      } 

      if (base.UserVersion == 1) {
        // do something else
      } 

    }

  }
```

Does this make sense?

The class DatabaseMapper is the following:

```
  public class DatabaseMapper : BsonMapper {
    public DatabaseMapper() {
         base.Entity<Post>()
           .DbRef(x => x.Tags, "tags");
    } 
  } 
```

Then I created an extension to inject Database class in ASP.NET Core:

```
    public static void AddLiteDatabase<TDatabase, TDatabaseMapper>(this IServiceCollection services, String connectionString) where TDatabase : LiteDatabase where TDatabaseMapper : BsonMapper {

      TDatabaseMapper contextMapper = (TDatabaseMapper)Activator.CreateInstance(typeof(TDatabaseMapper));

      TDatabase context = (TDatabase)Activator.CreateInstance(typeof(TDatabase), new Object[] { connectionString, contextMapper });

      services.AddScoped<TDatabase>(x => context);

    }
```

Does this make sense?

**Comment by lbnascimento** [comment]
@mdmoura Regarding the documentation you linked, that's for v1, a very old version. Other than that, your solution seems good to me.
