### ISSUE TITLE
[BUG] no results are being returned when filtering a nested array by an indexed property

### ISSUE THREAD

**Issue by zmira** [mbdavid/LiteDB#1642]
**Version**
5.0.7

**Describe the bug**
no results are being returned when filtering a nested array by an indexed property.
when applying the same filter without having the same property indexed, the expected result is returned:
```
-------------
WITHOUT INDEX
-------------
PLAN: {"collection":"Set","snaphost":"read","pipe":"queryPipe","index":{"name":"_id","expr":"$._id","order":1,"mode":"FULL INDEX SCAN(_id)","cost":100},"lookup":{"loader":"document","fields":"$"},"includeBefore":["$.Tags"],"filters":["MAP($.Tags[*]=>@.Value) ANY=@0"],"select":{"expr":"$","all":false}}
RESULT: [{"Id":888,"Tags":[{"Id":111,"Value":"tag one"}]},{"Id":999,"Tags":[{"Id":111,"Value":"tag one"},{"Id":222,"Value":"tag two"}]}]
-------------
-------------
WITH INDEX
-------------
PLAN: {"collection":"Set","snaphost":"read","pipe":"queryPipe","index":{"name":"MAPTagsValue","expr":"MAP($.Tags[*]=>@.Value)","order":1,"mode":"INDEX SEEK(MAPTagsValue = \"tag one\")","cost":10},"lookup":{"loader":"document","fields":"$"},"includeAfter":["$.Tags"],"select":{"expr":"$","all":false}}
RESULT: []
-------------
```
on version 5.0.4 this does not happen!

**Code to Reproduce**
https://gist.github.com/zmira/92a7ddf248a73b70791da33c0db65426

**Expected behavior**
results should be returned regardless of a nested array object property being indexed or not

**Comment by lbnascimento** [comment]
@zmira You cannot create an index over a field in a `BsonRef` document (other than `$id`). References are only resolved upon retrieval, and you can only create indexes over values that are acutally stored in the collection.

This expression worked in v5.0.4 because that version didn't use indexes for `ANY` queries.

**Comment by zmira** [comment]
oh. ok. hadn't realized that. thanks for the clarification.
will remove the index on the field of the referenced document.
will close the issue.
