### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by hvson** [mbdavid/LiteDB#1643]
I'm a newbie in LiteDB. I make an asp.net mvc project to interact with a LiteDB file. All function is ok, but the data only save in DB-log.db file. DB.db file don't change. 
 Please help me how to commit data from log file to main db file.
 Thanks!

**Comment by lbnascimento** [comment]
@hvson While auto-checkpoint is supposed to run eventually (by default, every time the log file reaches 8MB), it might not happen if your application is always using the datafile.

Try running a `db.Checkpoint()` every once in a while.

**Comment by hvson** [comment]
Thanks @lbnascimento. That's solve my problem. Thank a lot!

**Comment by TigerHix** [comment]
This should be in the documentation. Suffered a lot of strange data loss and just knew this was the cause.
