### ISSUE TITLE
In memory database with encryption, persisting to file system

### ISSUE THREAD

**Issue by mvdzwaan** [mbdavid/LiteDB#1646]
I want to use LiteDB to create an in-memory database with encryption and once it has been build I want to persist it to disk.

If I use a memorystream to persist it, I cannot specify a password.
If I use :memory: to create it, I cannot persist it.

Any hints on how to do this ?

**Comment by lbnascimento** [comment]
@mvdzwaan Something like this should work:
```C#
var stream = new MemoryStream();
var aesStream = new LiteDB.Engine.AesStream("mypassword", stream);

using (var db = new LiteDatabase(aesStream))
{
    //do whatever you want
}

using (var fs = File.Create("C:\\Temp\\outputfile.db"))
{
    stream.Seek(0, SeekOrigin.Begin);
    stream.CopyTo(fs);
}
```

**Comment by mvdzwaan** [comment]
thanks
