### ISSUE TITLE
[QUESTION] Update record without overwriting unspecified fields

### ISSUE THREAD

**Issue by TheAb03** [mbdavid/LiteDB#1649]
Let's say I have a `Person` object:

```json
{
    "name": "John",
    "age": 13
}
```

This object is stored in a LiteDB collection. If I call `Update` on this object with the following:
```json
{
    "age": 15
}
```
`"name"` will be overridden back to null.
Is there any way to bypass this, or will I have to do it manually?

**Comment by lbnascimento** [comment]
@TheAb03 If you class has an id (as it should, because the resulting document will have an id anyway) and you're willing to use SQL syntax, you could do something like `db.Execute($"update collection set age = 15 where _id = {myid}")`.
