### ISSUE TITLE
[BUG] Access to the path 'xxx.Mutex' is denied.

### ISSUE THREAD

**Issue by prafinski** [mbdavid/LiteDB#1658]
**Version**
Windows Server / Windows 10 / LiteDB 5.0.7 from NuGet

**Describe the bug**
Access to the path '426A3A7DF4D3C22E07885822D797639FA2DEEBB4.Mutex' is denied. When using same LiteDB file with two diffrent apps. One is IIS application, one is windows service. They are using diffrent users. I think problem is read/write permissions or some ACL.

I found that it can be resolved with SecurityIdentifier / MutexSecurity / MutexAccessRule,

Maybe this will help:
https://stackoverflow.com/questions/229565/what-is-a-good-pattern-for-using-a-global-mutex-in-c/229567#229567

**Code to Reproduce**
Cannot write directly - it is connected to user permission not strictly to code. Normal Insert / Update operations on same objects.

**Comment by lbnascimento** [comment]
@prafinski Could you try with the latest master? Coincidently, I added the `Global\` to the mutex name earlier today.

**Comment by prafinski** [comment]
@lbnascimento sure we will try and give a feedback soon

**Comment by prafinski** [comment]
@lbnascimento we checked and it dosn't resolve problem. You can easly reproduce it with Lite.Studio. When opened with some file (as your user - admin), application like IIS Website cannot open database (diffrent user). It does work with console app as it would run as your user - admin also.

I've change code and make it work even for production server with IIS + Windows service + Lite.Studio:

```
public SharedEngine(EngineSettings settings)
        {
            _settings = settings;

            var name = Path.GetFullPath(settings.Filename).ToLower().Sha1();

            try
            {
                var allowEveryoneRule = new MutexAccessRule(new SecurityIdentifier(WellKnownSidType.WorldSid, null)
                           , MutexRights.FullControl
                           , AccessControlType.Allow
                           );

                var securitySettings = new MutexSecurity();
                securitySettings.AddAccessRule(allowEveryoneRule);

                bool createdNew;

                _mutex = new Mutex(false, "Global\\" + name + ".Mutex", out createdNew, securitySettings);
            }
            catch(NotSupportedException ex)
            {
                throw new PlatformNotSupportedException("Shared mode is not supported in platforms that do not implement named mutex.", ex);
            }
        }
```

I need only .NET 4.5 version so it is working. I cannot make it compile for .NET Standard because SecurityIdentifier and MutexRights and not present. I'm not good in .NET Standard so just pasting idea how it can be fixed / upgraded.

**Comment by prafinski** [comment]
Maybe you can implement option to set MutexSecurity for users who want to do it? as an **EngineSettings.MutexSecurity** ?

**Comment by nathanjeynes** [comment]
This is similar to another issue #1656 and fixed our issue.

Using @prafinski solution we wrapped the following code to only implement on NETFRAMEWORK

```
        #if NETFRAMEWORK
                var allowEveryoneRule = new MutexAccessRule(new SecurityIdentifier(WellKnownSidType.WorldSid, null)
                           , MutexRights.FullControl
                           , AccessControlType.Allow
                           );

                var securitySettings = new MutexSecurity();
                securitySettings.AddAccessRule(allowEveryoneRule);

                bool createdNew = false;

                _mutex = new Mutex(false, "Global\\" + name + ".Mutex", out createdNew, securitySettings);
        #else
                _mutex = new Mutex(false, "Global\\" + name + ".Mutex");
        #753 

```

You also need 

```
#if NETFRAMEWORK
using System.Security.AccessControl;
using System.Security.Principal;
#endif
```

Can this potentially be considered and added to the master?

**Comment by lbnascimento** [comment]
I committed @nathanjeynes's suggestion to the master. I believe it should work now.

**Comment by Filip01011010** [comment]
Same error happens for C# / UWP projects
Any change for debug / fix anytime soon?
