### ISSUE TITLE
[QUESTION] How to create a query/expression with a NOT clause

### ISSUE THREAD

**Issue by jonlipsky** [mbdavid/LiteDB#1659]
In LiteDB v4 you could construct a query (using the API) like the following:

`
var query = Query.Not(someOtherQuery);
`

In LiteDB v5 that option no longer exists.  Is there a method that I am missing that replaces that functionality?  I would have expected to see something like this:

`
var bsonExpression = Query.Not(someOtherBsonExpression);
`

**Comment by lbnascimento** [comment]
@jonlipsky There's no explicit `NOT` operator currently. You could do something like this:

```C#
BsonExpression expr2 = string.Format("({0})=false", expr1.Source);
```

It's a bit convoluted, but it works perfectly.

**Comment by jonlipsky** [comment]
That worked great.  Thanks!
