### ISSUE TITLE
Feature Request: Control Serialization Mapping Programmaticlly without Attributes

### ISSUE THREAD

**Issue by CreepyGnome** [mbdavid/LiteDB#166]
We got pretty far into evaluating LiteDB and we hit a road block when we couldn't configure what fields are serialized using code mapping and could only do it via attributes.   Empty attributes would be fine we can create our own empty attributes that are part of our namespace, and they are just tags that are checked by string name instead of specific type.

Examples for attribute issue would be ReShaper, where I can create their empty attributes and the namespace and exact type doesn't matter. What matters is the class name only. This allows for not having to have a ReSharper assembly in your code.

As for programmatically mapping without using attributes the reasoning is the same. We have a model assembly that we don't allow any dependencies other than the BCL.  

We have used Entity Framework and MongoDB which both have great support for mapping with code instead of attributes so that the mapping logic is separate from the model object. Makes sharing the model objects much cleaner.

**Comment by mbdavid** [comment]
Hi @CreepyGnome, after a long time while, I'm backing to this project. LiteDB 2 (in master branch) supports fluent mapper, as you can see here:
```
using(var db = new LiteDatabase(@"MyData.db"))
{
    db.Mapper.Entity<Customer>()
        .Key(x => x.CustomerKey)
        .Map(x => x.Name, "customer_name")
        .Ignore(x => x.Age)
        .Index(x => x.Name, unique);

}
```

**Comment by CreepyGnome** [comment]
Are you saying it is not released or that it has been released for a long time, I am not sure as to your meaning? 

If this is released where is this feature documented? We couldn't find anything stating how to do that when we were evaluating LiteDB. 

If it isn't released when will it be released? And will it be documented?

**Comment by mbdavid** [comment]
This feature is present in v2, that are not release yet. Wiki documentation are not updated yet.

You can download master branch and see some unit test to see how works. My plans are release (in nuget) as soon I update wiki.
