### ISSUE TITLE
[QUESTION] Upgrade v4 to v5 Issue

### ISSUE THREAD

**Issue by DanTwomey** [mbdavid/LiteDB#1664]
After using the latest master to build LiteDB for the issues that were fixed in the last commit we have come across a big problem. (This would also appear to happen with the latest stable NuGet release)

We have an upgrade section to take our app's previous v4 database to v5 by calling:

```
_upgraded = LiteDB.Engine.LiteEngine.Upgrade(_litedb4Path, _liteDBPassword);
```

This runs successfully and the application restarts, however from this point forward, access to the database is extremely slow and the main database file does not get updated at all. Only the .log file gets updated.

If a new database is created this problem does not exist, the .log file appears and then disappears and the main database file gets updated. The performance is as expected.

Note: This also happens with the connection string containing upgrade=true and no manual upgrade being performed.

**Comment by lbnascimento** [comment]
@DanTwomey Have you tried running Checkpoint manually?

**Comment by lbnascimento** [comment]
@DanTwomey I found the issue: the auto-checkpoint was disabled during upgrade and was not re-enabled, which meant that the changes in the log file would only be commited to the datafile when `Checkpoint` was manually called.

I made a commit that fixes this issue, and a release should be out soon, but in the meantime you can just run `db.Pragma("CHECKPOINT", 1000)` once for every affected datafile and it should be fixed.
