### ISSUE TITLE
[BUG] drop collection and REBUILD corrupts the file

### ISSUE THREAD

**Issue by nant1086** [mbdavid/LiteDB#1665]
**Version:** litedb-ce-v5.0.7 / LiteDB Studio 1.0.2.0 / Windows 10 / Net Core 3

**Describe the bug**
First of all, I think this project is amazing!, after some toying with it, I found a scenario which throws an error and I wasn't able to access the database anymore

**Steps to reproduce**
1.  Open the file with `ConnectionType.Shared`, 
1.  Insert rows to 1 single collection, there is one single collection only
1.  With LiteDB Studio, execute `drop collection` then `rebuild` with collation or selecting the rebuild word only 
1. Try to connect to the file and this error is thrown: _Unable to cast object of type 'LiteDB.Engine.HeaderPage' to type 'LiteDB.Engine.IndexPage'_.

A possible workaround is to delete all rows instead of dropping the collection, then `rebuild` to reduce the file size, and everything works ok

I hope this bug isn't so hard to solve, good luck!

**Comment by lbnascimento** [comment]
@nant1086 This issue has been fixed in the master and its fix will be present in the next incremental release;

**Comment by lbnascimento** [comment]
@nant1086 This issue has been fixed in the master and its fix will be present in the next incremental release.
