### ISSUE TITLE
Selection a random document from a collection

### ISSUE THREAD

**Issue by FrancescaY** [mbdavid/LiteDB#1666]
Hello,
I am quite new to LiteDB, but my first impression is enthusiastic. I am trying to investigate its capabilities, which is not always easy, since the documentation is still somewhat sparse.
My first issue is as follows: I need to select random elements from a collection, how can I do it? The Query class does not seem to provide for such a possibility, is there any (in SQLite I would use ORDER BY RANDOM or so)?
Thanks, F.

**Comment by lbnascimento** [comment]
@FrancescaY There's no specific funcionality for querying a random document. You could do something like this:

```C#
var rnd = new Random();
var offset = rnd.Next(0, col.Count());
var result = col.Query().Limit(1).Offset(offset).SingleOrDefault();
```

**Comment by FrancescaY** [comment]
Thanks a lot Leonardo, this is really easy. Best, Francesca.
