### ISSUE TITLE
[BUG] Upgrade V4 to V5 does not keep the UserVersion from V4

### ISSUE THREAD

**Issue by ChrisCross67** [mbdavid/LiteDB#1668]
I was using a file build with the version 4.1.0 of LiteDB, when I upgrade the file to V5, the UserVersion does not keep the value of the previous version... 

The UserVersion on V4 was 4 and on the V5 0.
I was expecting the UserVersion from the V4 would be the same for the V5 once upgraded.

Could you please fix it?

**Comment by lbnascimento** [comment]
@ChrisCross67 This issue is fixed in the latest master and its fix will be present in the next incremental release.
