### ISSUE TITLE
Incremental backup

### ISSUE THREAD

**Issue by schotime** [mbdavid/LiteDB#167]
Hi,
I am looking to use this as a file store, and was wondering if there were someway to only backup the differential each day. 

1. 2 gig of files
2. do a full backup
3. every day perform an incremental backup (might be only 100mb)
4. I could then restore using the incremental's if needed.

Also, can multiple users open the database to write to?

Cheers,
Adam

**Comment by mbdavid** [comment]
Hi @schotime, after a while i'm backing to LiteDB. LiteDB is a flat file database, so full backups it's just a simple copy/paste.
To have an incremental solution it's be very hard to implement. LiteDB must track all changes to re-create after some point.
