### ISSUE TITLE
[QUESTION] How to properly work with JSONString

### ISSUE THREAD

**Issue by Thomas-6freedom** [mbdavid/LiteDB#1670]
Hello.

I have a JSON of a class and I want to save it into the database.
What I am currently doing 

    var database = new new LiteDatabase("demo.db");
    string JSON = "{"foo":"bar", "fooInt" : 2}";
    BsonValue bson = JsonSerializer.Deserialize(JSON);
    MyClass myObj = BsonMapper.Global.Deserialize<MyClass>(bson);
    using (database)
    {
        var myClassCollection = database.GetCollection<MyClass>("objects");
        myClassCollection.Insert(myObj);
    }

I think there is a better way. Especially the steps where I transform a string to a BSON then to a MyClass.

What do you recommend me to do ? 

Thank you

**Comment by lbnascimento** [comment]
@Thomas-6freedom If you don't need to work with a class and just want to insert the JSON in a collection, you can use untyped collections:

```C#
var database = new LiteDatabase("demo.db");
string JSON = "{\"foo\":\"bar\", \"fooInt\" : 2}";
BsonDocument doc = JsonSerializer.Deserialize(JSON) as BsonDocument;
using (database)
{
    var myClassCollection = database.GetCollection("objects");
    myClassCollection.Insert(doc);
}
```
