### ISSUE TITLE
[QUESTION] Nested Document DBRef

### ISSUE THREAD

**Issue by lilasquared** [mbdavid/LiteDB#1673]
Is it possible to define a DBRef on a nested property of a document?

ex:
```csharp
class Document {
  public SubDocument Sub { get; set; }
}

class SubDocument {
  public SomeRef Ref { get; set; }
}

class SomeRef {
  public Int32 Id { get; set; }
}
```
I'm wanting the Ref property to be a DBRef.  When trying to do this with the fluent mapper:
```csharp
mapper.Entity<Document>().DbRef(x => x.Sub.Ref)
```
I get an error that `Parameter Member "Sub.Ref" not found in type "Document"`.

**Comment by lbnascimento** [comment]
@lilasquared This is not supported. The Id field must always be in the "top-level" object - either explicitly or through inheritance.

Maybe I could help you further if you explained what you're trying to achieve.

**Comment by lilasquared** [comment]
I figured as much.  I am trying to persist a linked list / tree type structure which is very nested but also referencing entities that exist in a different collection.  Not sure how to persist it with LiteDB yet.  Might need to break out the components into other entities.

**Comment by lilasquared** [comment]
I think i'm getting there by flattening out the structure a bit, closing this.
