### ISSUE TITLE
[QUESTION] POCO classes having a Guid Id

### ISSUE THREAD

**Issue by ssteiner** [mbdavid/LiteDB#1674]
Most of the data I'm dealing with has a Guid as unique identifier. When I'm trying to add an object that has a property called Id of type System.Guid to LiteDB I'm stopped by 

> System.InvalidCastException: 'Unable to cast object of type 'System.Guid' to type 'System.Int32'.'

Is there any way to get this done? I can't change the object model.

**Comment by lbnascimento** [comment]
@ssteiner Could you post more info about the object you're trying to store? `Guid` is supported natively by LiteDB, there shouldn't be any issues.

**Comment by ssteiner** [comment]
Here's the object I'm trying to store

`public class PluginConfiguration
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public SpecialConfiguration SpecialConfig { get; set; }
        
    }

    public class SpecialConfiguration
    {
        public string Value1 { get; set; }

        public string Value2 { get; set; }
    }`

**Comment by lbnascimento** [comment]
@ssteiner This class is perfectly fine, I just tested it and it works fine. Could you show me how you're opening the datafile, the collection and inserting the object?

**Comment by ssteiner** [comment]
@lbnascimento sure thing - here's how I'm trying to insert. Note I commented out the EnsureIndex because I first though maybe that's what's tripping it up, but it happens either way.

```csharp
internal void AddConfig(PluginConfiguration config)
        {
            using (var db = new LiteDatabase(databaseFile))
            {
                var configs = db.GetCollection<PluginConfiguration>(nameof(PluginConfiguration));
                //configs.EnsureIndex(x => x.Id);
                int nbRows = configs.Insert(config);
            }
        }

**Comment by lbnascimento** [comment]
@ssteiner The error is happening because you're attributing the result of the `Insert` to an `int`. `Insert` returns the Id of the inserted document, which is a `Guid` in your case.

**Comment by ssteiner** [comment]
@lbnascimento : Ahh, I see. While I have you, do I need the EnsureIndex in this case or is it automatically indexed on Id?

**Comment by lbnascimento** [comment]
@ssteiner It is not needed, the Id field is always indexed.
