### ISSUE TITLE
[BUG] Filter on multi fields only applies first filter

### ISSUE THREAD

**Issue by seertenedos** [mbdavid/LiteDB#1677]
**Version**
Windows 10 & LiteDB 5.0.7

**Describe the bug**
Using the query below where Status is an enum and LastModified is a date the results coming back from the collection are of the correct status but fail the date check part. The && means they should have to mach both conditions. 
_mappings.Find(x => x.Status == status && x.LastModified <= maxLastModified).ToList();

BsonMapper.Global.EnumAsInteger = true; is set and Status is indexed but .LastModified is not

At the moment i fix the issue using the following
_mappings.Find(x => x.Status == status && x.LastModified <= maxLastModified)
                .Where(x => x.Status == status && x.LastModified <= maxLastModified).ToList();

My concern is that maybe this bug affects Exist calls or other calls i have not got enough unit tests over.

**Comment by lbnascimento** [comment]
@seertenedos Could you test with the latest master?

**Comment by seertenedos** [comment]
If it has a NuGet anywhere that I can pull then yea if not it is a bit
harder as I need to pull the whole source into my project, make it build in
my dotnet core project and change all my references to project references.
It is a pain.

**Comment by seertenedos** [comment]
Can the build system be configured to auto build master and publish them as a pre-release so the builds are easy to access or even put them on a different nuget feed somewhere if that is not an option?
