### ISSUE TITLE
[BUG] UserVersion is lost when migrating

### ISSUE THREAD

**Issue by kakone** [mbdavid/LiteDB#1679]
**Version**
5.0.7

**Describe the bug**
UserVersion is lost when we upgrade from version 4 to 5.

**Code to Reproduce**
After call LiteEngine.Upgrade method, the LiteDatabase.UserVersion go back to 0.

**Expected behavior**
UserVersion should be kept when migrating to version 5.

**Comment by temnava** [comment]
I think this is it: https://github.com/mbdavid/LiteDB/issues/1668
