### ISSUE TITLE
query based on object in object

### ISSUE THREAD

**Issue by trondkristiansen** [mbdavid/LiteDB#168]
Hello
I have some objects stored in a LiteDB database. I'm trying to get a result of all CostBasisTradeSessionObjects that include Marked objects with a particular name, MarkedNameString. I find the Marked object easily enough, but I dont now how to query for object in object. 

`public string Marked
{
        public ObjectId MarkedId { get; set; }
        public String Name { get; set; }
}

public class CostBasisTradeSessionObject
    {
        public ObjectId CostBasisTradeSessionId { get; set; }
        public bool IsActive { get; set; }
        public DateTime SessionStarted { get; set; }
        public DateTime SessionClosed { get; set; }
        public Marked Marked { get; set; }
    }

 using (var db = new LiteDatabase(@"CostBasesTradeSessionsDatabase.db"))
            {
                var costBasisTradeSessionObjects = db.GetCollection<CostBasisTradeSessionObject>("costBasisTradeSessionObjects");

                Marked marked = db.GetCollection<Marked>("markeds").Find(Query.EQ("Name", "<MarkedNameString>")).Single();
            }
`

So I try to get an result with CostBasisTradeSessionObject objects that includes the marked object returned in var marked.

So I tried a couple of things
var cb = costBasisTradeSessionObjects.Include(x => x.Marked).Equals(marked);
and justing jusing the MarkedNameString directory
var results = costBasisTradeSessionObjects.(Query.("Marked.name", "MarkedNameString"));
or
var results = costBasisTradeSessionObjects.Find(x => x.Marked.Name.Equals("MarkedNameString"));
but all the things I tried return an empty result or dont work. 

Regards

**Comment by mbdavid** [comment]
Hi @trondkristiansen, if your Marked object is a reference in CostBasisTradeSessionObject there is no index available (there is not "Name" field CostBasisTradeSessionObject). To fix this, use Marked as an embedded document.
