### ISSUE TITLE
[BUG] LiteDB Does Not Properly Handle an AbandonedMutexException

### ISSUE THREAD

**Issue by 9ee1** [mbdavid/LiteDB#1682]
**Version**
LiteDB => 5.0.5
OS => Windows 10
.NET => .NET Core 3.1

**Describe the bug**
If a database is opened and the process crashes or is forcefully terminated (through no fault of LiteDB), the Mutax held by LiteDB is not properly released. The next time the process is launched, the database cannot be opened because LiteDB does not properly handle an `AbandonedMutexException`.

```
System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitOne()
   at LiteDB.SharedEngine.OpenDatabase()
```

**Code to Reproduce**
```
static LiteDatabase CreateDatabase(string cFilePath, BsonMapper cMapper) {
    // ...
    //
    // Throws an exception if the operation fails.
    var cConnectionString = $"Filename={cFilePath}; Connection=Shared";
    var cDatabase = new LiteDatabase(cConnectionString, cMapper);
    return cDatabase;
}
```

**Expected behavior**
Opening the database properly handles an `AbandonedMutexException`.

**Screenshots/Stacktrace**
N/A

**Additional context**
N/A

**Comment by lbnascimento** [comment]
@9ee1 Could you try with the latest master?

**Comment by 9ee1** [comment]
Thanks for the quick response @lbnascimento. I tried latest master and it seems to have resolved the problem. Will there be a new Nuget package with this soon?

**Comment by lbnascimento** [comment]
@9ee1 v5.0.8 is out.

**Comment by 9ee1** [comment]
Thanks a lot @lbnascimento.
