### ISSUE TITLE
[QUESTION] How to store via object

### ISSUE THREAD

**Issue by matelich** [mbdavid/LiteDB#1683]
Using 5.0.8

Porting some XML serialization code for a class which holds essentially a dictionary of objects (though the objects are wrapped in a class). It currently stores a type for every value which isn't a string and uses that during deserialization. I wasn't clear if there was a built-in way to do this in LiteDB.

I'm currently writing a custom mapper for this and going to follow the same scheme of storing types, but would love it if someone could point out a simpler way. The objects may be any built-in type or some smaller custom types. It *seems* like I could do something with BsonDocument, but I'm not quite sure how to tackle it.

**Comment by lbnascimento** [comment]
@matelich Could you provide more info on what you're trying to do? Some examples of your XML serialization code would be nice.

**Comment by matelich** [comment]
Naturally, I discovered BsonMapper.ToDocument and ToObject about 10 minutes after posting. I think they will do the job.

Thanks, @lbnascimento!
