### ISSUE TITLE
[BUG] GetPlan of empty collection throw exception

### ISSUE THREAD

**Issue by mikhail-khalizev** [mbdavid/LiteDB#1685]
**Version**
5.0.8

**Describe the bug**
`GetPlan` method of empty collection throw System.InvalidOperationException : Sequence contains no elements.

**Code to Reproduce**
```
public class StateModel
{
    [BsonId]
    public int Id { get; set; }
}

[Fact]
public void MyTest()
{
    using (var db = new LiteDatabase(":memory:"))
    {
        var col = db.GetCollection<StateModel>("col");
        var query = col.Query();
        var plan = query.GetPlan();
    }
}
```

**Expected behavior**
Exception is not thrown.

**Comment by lbnascimento** [comment]
@mikhail-khalizev This issue has been fixed in master and its fix will be present in the next incremental release.
