### ISSUE TITLE
[QUESTION] Weird behavior when performing multiple upserts in a for loop

### ISSUE THREAD

**Issue by tingyus995** [mbdavid/LiteDB#1687]
```C#
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Salary { get; set; }
        public DateTime Birthday { get; set; }
        public string ContactNumber { get; set; }
        public byte[] Image { get; set; }
        public string[] Categories { get; set; }
        public WorkTime[] workTime { get; set; }
    }


    public class WorkTime
    {
        public DateTime Date { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        
    }

    private void btnClear_Click(object sender, EventArgs e)
    {
            Employee[] employees = colEmployee.FindAll().ToArray();
            
            foreach (Employee employee in employees)
            {
                employee.workTime = null;
                colEmployee.Upsert(employee);
                Thread.Sleep(10);
            }
    }
```

I don't understand the reason why I need to add ``Thread.Sleep(10)`` or ``MessageBox.Show()`` for it to properly remove all workTime in each employees, considering ``Upsert()`` is a synchronous function and will only return when the database is updated.

If there's no ``Thread.Sleep(10);``, it sometimes only clear part of workTime in each employees, and rarely clear all workTime in each employees.

**Comment by lbnascimento** [comment]
@tingyus995 I ran some tests and could not reproduce the issue. Could you provide more info (like LiteDB version, platform/framework and OS) and the datafile you're using?

**Comment by tingyus995** [comment]
After some more testing and reading documentation, I found that I forgot to call ``LiteDatabase.Dispose()`` throughout my app.

Thus, the changes aren't flushed to the disk after multiple upserts (operations).

However, if there's only one operation (e.g. one upsert, one insert) the changes seem to be immediately written to the disk. That's the reason why I ignore ``LiteDatabase.Dispose()`` until near the end of the project I'm doing.
