### ISSUE TITLE
Iterating over query result

### ISSUE THREAD

**Issue by sanjeevbaral** [mbdavid/LiteDB#1689]
Hi,

I am executing SQL and iterating over result set with data reader. I am finding that if SQL returns more than 45,000 matches the loop still stops at 45,000. Is there a limit to how many results can be returned? Can I increase the limit?

                   IBsonDataReader rdr = db.Execute(sql);
                    int i = 0;
                    
                    while (rdr.Read())
                    {
                        BsonDocument patientDoc = new BsonDocument();                        
                        patientDoc["_id"] = rdr["_id"].AsObjectId;
                        _dicSeachResultIds.Add(i, patientDoc);
                        i++;
                    }

**Comment by sanjeevbaral** [comment]
Never mind! The database had gotten somehow corrupted. I dropped and re-built collection and now the count looks good. Not sure what caused it to get corrupted.

**Comment by lbnascimento** [comment]
@sanjeevbaral I'm going to close this issue, if you get corruption again please open another issue.
