### ISSUE TITLE
[BUG] Auto id produce duplicate value

### ISSUE THREAD

**Issue by mikhail-khalizev** [mbdavid/LiteDB#1691]
**Version**
5.0.8

**Describe the bug**
Just look to code below - when I open db second time and delete last item in collection, id of newly added item became last deleted item id. 

**Code to Reproduce**
```
public class StateModel
{
    [BsonId]
    public int Id { get; set; }
}

[Fact]
public void MyTest()
{
    var ms = new MemoryStream();
    
    var m1 = new StateModel();
    var m2 = new StateModel();

    using (var db = new LiteDatabase(ms))
    {
        var col = db.GetCollection<StateModel>("col");
        col.Insert(m1);
    }

    using (var db = new LiteDatabase(ms))
    {
        var col = db.GetCollection<StateModel>("col");
        
        col.FindById(m1.Id).Should().NotBeNull();
        col.Delete(m1.Id);
        
        col.Insert(m2);
    }

    m1.Id.Should().NotBe(m2.Id); // Throw exception.
}
```

**Expected behavior**
I expected that id of newly added item is absolute new (never used any time before). 

I.e. `Id` of `m1` and `m2` should be differs.

**Comment by lbnascimento** [comment]
@mikhail-khalizev When Using `Int32` or `Int64` as auto-id, LiteDB will always use the next available value. If you really need for your objects to have an unique id, consider using `Guid` or `ObjectId` as id.

**Comment by mikhail-khalizev** [comment]
Okay
