### ISSUE TITLE
Question with an association

### ISSUE THREAD

**Issue by Hidend** [mbdavid/LiteDB#1693]
LiteDB:
I'm creating Models and storing them on Database using this:
```csharp
            var item = new ItemModel("Rol", 10000, "Se te da un rol a elegir");
            List<ItemModel> listOfItems = new List<ItemModel>();
            listOfItems.Add(item);
            var shop = new ShopModel("DiscordShop", "Description de la tienda", listOfItems);
            _databaseHandler.Save(item);
            _databaseHandler.Save(shop);
```
I can just store one ItemModel on a ShopModel, and a ShopModel can have many ItemModel, so I have a List of ItemModel on ShopModel
ShopModel Class:
```csharp
        [BsonRef("ItemModel")]
        public List<ItemModel> Items { get; set; }
```
StoreModel in Database (Table is called StoreModel):
<https://i.imgur.com/VlJkdpt.png>
ItemModel in Database (Table is called ItemModel):
<https://i.imgur.com/2y7QBlt.png>

The problem is that when I reference ItemModel in ShopModel, when I access the list of ItemModel inside a ShopModel, all properties of the ItemModel are empty as shown here:
<https://i.imgur.com/1c8qNR5.png>

But if I get all ItemModel from the database I get the properties:
<https://i.imgur.com/cZK9AtQ.png>

If I remove the association ([BsonRef("ItemModel")]) I can read the properties of an ItemModel inside a list of ShopModel, the problem is that they are not associated and if I modify a value of an ItemModel, it's not getting updated in the list of a ShopModel
I'm kinda lost here

**Comment by zmira** [comment]
when you are reading `StoreModel` from the database are you including the referenced `ItemModel`?
e.g.
```
db.GetCollection<StoreModel>("store")
    .Include(store => store.Items)
    ...
```

**Comment by Hidend** [comment]
@zmira No, but I tried to do it with Include and it doesn't work too.

```csharp
       public List<ShopModel> GetAllSmModels<T>()
        {
	        using (var database = new LiteDatabase("database.db"))
            {
                var collection = GetCollectionSM<ShopModel>(database).Include(store => store.Items);
                var get = collection?.FindAll()?.ToList();
                return get;
            }
        }
```

**Comment by Hidend** [comment]
It is because of what @zmira , thank you! Is there any way to just include all associations by default or do I have to specify each one of them in Include (In the case I had more than one association)

**Comment by zmira** [comment]
great! unfortunately, you have to specify each one of the includes.
