### ISSUE TITLE
[QUESTION] EnsureIndex on empty collection

### ISSUE THREAD

**Issue by abrca** [mbdavid/LiteDB#1696]
Is it OK to call EnsureIndex on empty collection - at database creation time, to register index fields, or there must be at least one data entry in collection?

**Comment by lbnascimento** [comment]
@abrca It is perfectly fine to call `EnsureIndex` for a possibly non-existent collection, it will be created if it doesn't exist.

**Comment by abrca** [comment]
Thank you
