### ISSUE TITLE
[QUESTION] three-levels tree

### ISSUE THREAD

**Issue by dxmann** [mbdavid/LiteDB#1698]
Hello!!
I'm working with data structured in three levels
```
// all public and {get; set;}
class A {
  int Id;
  List<B> Bs;
}
class B {
  int Id;
  List<C> Cs;
}
class C {
  int Id;
  bool Happy;
}

BsonMapper.Global.Entity<C>().Id(x => x.Id, false);
BsonMapper.Global.Entity<B>().Id(x => x.Id, false).DbRef(x => x.Cs, "cs");
BsonMapper.Global.Entity<A>().Id(x => x.Id, false).DbRef(x => x.Bs, "bs");
db = new LiteDatabase($"Filename={dbPath};Password={password}", BsonMapper.Global);

a = new A {Id = 1};
b1 = new B {Id = 1};
b2 = new B {Id = 2};
c1 = new C {Id = 1};
c2 = new C {Id = 2};
c3 = new C {Id = 3};

a.Bs.Add(b1);
a.Bs.Add(b2);
b1.Cs.Add(c1);
b1.Cs.Add(c2);
b2.Cs.Add(c3);

var dba = db.GetCollection<A>().Add(a);
var res = dba.Include(x => x.Bs).FindAll().ToList();
```

__Question 1__: res will include all A and their children B... but how to include C too (they are contained in B.Cs) ?
__Question 2__: if I use a configuration like Nodes and Archs, stored in 2 different collections, is it possible to investigate the graph in depth for n levels?

Thank you very much in advice ;) 
bye!!!

**Comment by dxmann** [comment]
Again:
if I add to the code 

```
var b = db.GetCollection<B>().FindAll().ToList();
var c = db.GetCollection<C>().FindAll().ToList();
```

b and c are both empty... Why?

**Comment by lbnascimento** [comment]
@dxmann `DbRef` and `Include` are used to define and resolve references, but they do not automatically insert referenced documents in their collections, you must do it manually.

Also, given that you used the collection name parameter in the `DbRef` call, you should also use it in the `GetCollection` call.

**Comment by dxmann** [comment]
So if I have my three levels tree should I insert manually any item for any level?

**Comment by lbnascimento** [comment]
@dxmann Yes, you must manually insert all referenced documents.

It is possible to navigate through the documents, but you'll need to use [Bson Expressions](http://www.litedb.org/docs/expressions/). Here's an example:

```C#
var colAs = db.GetCollection<A>("as").Include("$.Bs").Include("$.Bs[*].Cs");
var colBs = db.GetCollection<B>("bs").Include("$.Cs");
var colCs = db.GetCollection<C>("cs");

var r = colAs.Find("count($.Bs) > 0 and $.Bs[*].Cs[*].Happy all = true").ToList();
// returns all As for which Bs is not empty and all Cs in all Bs have Happy = true
```

**Comment by dxmann** [comment]
Ok, Thank you very much!! :)
