### ISSUE TITLE
[QUESTION] Confusion with BsonCtorAttribute

### ISSUE THREAD

**Issue by ordinaryorange** [mbdavid/LiteDB#1699]
The [documentation](https://www.litedb.org/docs/object-mapping/) in respect of the `BsonCtorAttribute` says..

> Please note that all the parameters in the constructor annotated with BsonCtorAttribute must be of a simple type, BsonDocument or BsonArray.

So I was expecting the following code to work
```
[BsonCtor]
public Foo(BsonDocument doc)
{
        //Instantiate class from doc
}
```

But `doc` is always `null`
I can get simple types to work, just not the former. 
What am I missing ?

**Comment by lbnascimento** [comment]
@ordinaryorange This feature works by trying to match fields in the document with parameters in the constructor annotated by `BsonCtor`. For example, if your constructor has the signature `public Foo(int id, string name)` and your document has fields `_id` and `Name`, the value of these fields will be matched with the corresponding parameter in the constructor call (name matching is case-insensitive).

If you want to control how your object is deserialized from a document, you should use a custom deserializer.

**Comment by ordinaryorange** [comment]
So the documentation appears to be incorrect then ?
In the quoted sentence I provided, _"BsonDocument and BsonArray"_ should be deleted therefore ?

**Comment by lbnascimento** [comment]
@ordinaryorange You can use `BsonDocument` and `BsonArray` to populate lists and sub-objects. Example:

```C#
public class SubEntry
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class SuperEntry
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class Entry
{
    public int Id { get; private set; }
    public string Name { get; private set; }
    public SuperEntry SuperEntry { get; private set; }
    public List<SubEntry> SubEntries { get; private set; }

    [BsonCtor]
    public Entry(int id, string name, BsonDocument superEntry, BsonArray subEntries)
    {
        var mapper = BsonMapper.Global;
        Id = id;
        Name = name;
        SuperEntry = mapper.Deserialize<SuperEntry>(superEntry);
        SubEntries = subEntries.Select(x => mapper.Deserialize<SubEntry>(x)).ToList();
    }
}
```

**Comment by jake1164** [comment]
It would be really nice if the documentation had some examples like this for the BsonCtor.
