### ISSUE TITLE
[QUESTION] Multiple Includes of generic classes

### ISSUE THREAD

**Issue by Scantraxx123** [mbdavid/LiteDB#1704]
Hi!
I have a implemenation for a generic base class for my objects with LiteDB functions. It works wonderful but my problem is that I need to include DBRefs.
The problem there is that I only know the fields while runtime in the LiteDB functions like Find() or FindAll(). So my question is, if its possible to include multiple fields in one include statement?

I found only this in the docs
![image](https://user-images.githubusercontent.com/34422209/83453809-6f081000-a45b-11ea-894b-194e52edc342.png)

But this is not working for me in v5 because the syntax got removed(?).

I hope you can help me!

Best regards
Felix

**Comment by lbnascimento** [comment]
@Scantraxx123 In v5, due to changes in how includes are resolved, they must be added individually, like `col = col.Include("$.Customer").Include("$.Products[*]")`.

**Comment by Scantraxx123** [comment]
Should it be possible to include a list of strings in a loop on a collection? I testet it yesterday and it didn't gave me a good result. But I have some ideas to test something later.

**Comment by lbnascimento** [comment]
@Scantraxx123 Yes, it should work:
```C#
foreach(var include in includes)
    col = col.Include(include);
```
Please note that every `Include` call returns a new instance of `ILiteCollection<T>`.
