### ISSUE TITLE
[QUESTION] How to store/retrieve datetime with DateTimeKind.Unspecified (without LOCAL <-> UTC convert) only?

### ISSUE THREAD

**Issue by mwkldeveloper** [mbdavid/LiteDB#1705]
LiteDb version : v5.0.8

There is an offset between Insert and Retrieve .
All DateTime values converts to UTC before store and converts back to local on retrieve.

In LiteDb Studio:
![image](https://user-images.githubusercontent.com/8042599/83714490-80b90580-a65d-11ea-88a0-41cb7e6b3812.png)

![image](https://user-images.githubusercontent.com/8042599/83714475-7860ca80-a65d-11ea-9667-b783b1682fa0.png)

The problem:  The time is different with different timezone I set,
If i am in tokyo, the time is +9, if i am in HK time is +8.
 
How can i store/Retrieve the DateTime exactly the same (DateTimeKind.Unspecified), no matter my local time zone is?

In v4, there seems have an option in connection string "utc=true"

**Comment by lbnascimento** [comment]
@mwkldeveloper If you set the `UTC_DATE` pragma in your datafile to `true` (`db.Pragma("UTC_DATE", true);`), all dates will be retrieved with `DateTimeKind.Utc` – so the retrieved value might not be exactly the same than the value that was stored, but at least it'll be deserialized the same in every time zone. If you really need to retrieve dates exactly as they were stored, you should use a custom serializer for `DateTimeOffset`, as I suggested in #1686.

**Comment by mwkldeveloper** [comment]
@lbnascimento Thanks for your suggestion.
In my case, actually need store as DateTimeKind.Unspecified,
So my partner and i ( one in Tokyo and one in HK )can see the same value in LiteDb Studio/ C# program , also can do Query have same result

From LiteDb Studio (Text)
![image](https://user-images.githubusercontent.com/8042599/83847076-32c7fe80-a73e-11ea-8b17-ac848be9c146.png)
![image](https://user-images.githubusercontent.com/8042599/83847086-38bddf80-a73e-11ea-8f8d-db8d8a71883c.png)
![image](https://user-images.githubusercontent.com/8042599/83847107-3f4c5700-a73e-11ea-97ae-6c0b5b38e54d.png)

From LiteDb Studio (Grid)
![image](https://user-images.githubusercontent.com/8042599/83847044-280d6980-a73e-11ea-9140-73f18ca8823d.png)

From Web API (C#)
![image](https://user-images.githubusercontent.com/8042599/83847286-8fc3b480-a73e-11ea-8e70-7fe7f98e7f4c.png)
![image](https://user-images.githubusercontent.com/8042599/83847272-88041000-a73e-11ea-860f-8b166740dff7.png)
![image](https://user-images.githubusercontent.com/8042599/83847212-728ee600-a73e-11ea-9e09-86ced0ea81d2.png)



Maybe that is unusual case, but that is what i need.

After i try and error, Now my sulotion is:
1. set `db.Pragma("UTC_DATE", true);`
2. Add below:
```
BsonMapper.Global.ResolveMember += (type, memberInfo, member) =>
            {
                if (member.DataType == typeof(DateTime))
                {
                        member.Deserialize = (v, m) =>
                        {
                            return DateTime.SpecifyKind(v.AsDateTime.ToUniversalTime(), DateTimeKind.Unspecified);
                        };
                }
            };
```

3. Change All `DateTime` field to `DateTimeKind.Utc` before Insert to LiteDb or do some Query
 e.g  `DateTime.SpecifyKind(DateTime.Now, DateTimeKind.Utc)`


Btw i am not understand why LiteDb need convert LOCAL <-> UTC,
For store what kind of data to Database, should it be designed by programmer not database it self??

I have tried below code, but it break native LiteDb datetime API, and cannot do Query, but for me it seems make sense, to store what data i want to store
```
member.Deserialize = (v, m) =>
                        {
                           var doc = ((BsonDocument)v);
                            var dateValue = doc["$date"];
                            return dateValue.AsString.Contains("Z") switch
                            {
                                true => DateTime.Parse(dateValue).ToUniversalTime(),
                                _ => DateTime.Parse(dateValue)
                            };
                        };
                        member.Serialize = (o, m) =>
                        {
                            var dt = (DateTime)o;
                            var doc = new BsonDocument();
                            doc["$date"] = dt.ToString("o");
                            return doc;
                        };
```

![image](https://user-images.githubusercontent.com/8042599/83849062-6ce6cf80-a741-11ea-8548-eb04b5da481e.png)
![image](https://user-images.githubusercontent.com/8042599/83849083-7708ce00-a741-11ea-8464-c5112113e6e8.png)
![image](https://user-images.githubusercontent.com/8042599/83849106-7e2fdc00-a741-11ea-9f2b-d176cb7c1d72.png)
![image](https://user-images.githubusercontent.com/8042599/83849130-86881700-a741-11ea-8d07-4e1e0882b98e.png)

**Comment by lbnascimento** [comment]
@lbnascimento LiteDB internally uses BSON (a subset of it, actually), and the BSON specification states that datetime must be stored as the miliseconds since the Unix epoch, which means all dates are stored in UTC. This means that all local datetimes must be converted to UTC before storage, and they may be converted back to local time or returned as `DateTimeKind.Utc` upon retrieval.

This also means that there is not a particularly good way for LiteDB to deal with `DateTimeKind.Unspecified`. In fact, LiteDB calls `DateTime.ToUniversalTime()` before storage, and this method simply assumes that the `DateTime` is in local time if it's `DateTimeKind.Unspecified`.

Also, `DateTime` is a basic type in LiteDB, so using a custom serializer would not work. Your best bet would be either to create a custom serializer for the class that contains the `DateTime` or to create a wrapper class for `DateTime` and create a custom serializer for it.

We will consider alternatives to the current `DateTime` serialization (like an option to serialize all dates as strings).
