### ISSUE TITLE
ReadOnly Collections

### ISSUE THREAD

**Issue by xszaboj** [mbdavid/LiteDB#171]
Hi,

I choose to use LiteDb as a database on a project. And I like thr db very much. But I found out that if I use read only collections (collections with private setter) database is not able deserialize back the object that is saved into db. 

I changed this behaviour in original source code of LiteDB.

Can I somehow push the code that I wrote into a new branch on my local machine into this repository?

**Comment by nerai** [comment]
I would love this feature.

It would concern two variants:

1. properties with public getter, private setter
2. public readonly fields

Support for these two would be very useful and also make integrating LiteDB a lot easier. Right now, I have to create a "full access public setter" copy of my classes, which is tedious and error prone code duplication.

**Comment by mbdavid** [comment]
Hi @nerai, this could be an options in BsonMapper. But how set values in deserialize to privete setters/readonly fields?

**Comment by nerai** [comment]
@mbdavid Via Reflection. I've never done it myself, but I threw together a quick (and bare-bones) example that I hope works.

```
class C {
    int _V;
    public C (int v) { _V = v; }
    public int V { get { return _V; } }
}

var foo = new C (3);
PropertyInfo pi = typeof (C).GetProperty ("V");
FieldInfo fi = pi.GetBackingField ();
fi.SetValue (foo, 4);
```

**Comment by nerai** [comment]
I'm not sure if @xszaboj already did something like this?

**Comment by frg** [comment]
@mbdavid Is there any plan to support private setters in the future? I've encountered a similar situation as @xszaboj. A similar scenario I've encountered is when using JSON.Net to deserialize - but in that case I was able to use a contractresolver and some reflection magic.
