### ISSUE TITLE
[QUESTION] Is it possible to use LiteDB for Identity purposes?

### ISSUE THREAD

**Issue by a-a-k** [mbdavid/LiteDB#1711]
I mean using LiteDB instead of classic mechanism with relational DbContext. Any examples if exist?

**Comment by lbnascimento** [comment]
@a-a-k Sorry, I didn't understand your question. Could you explain it further?

**Comment by captmomo** [comment]
Something like this? https://github.com/fabian-blum/AspNetCore.Identity.LiteDB

**Comment by quicksln** [comment]
Hi @a-a-k and @lbnascimento 
If your meant Microsoft AspNetCore Identity, then yes - it is possible. 
Could you please check following project, I'm working on:

https://github.com/quicksln/LiteDB.Identity
https://www.nuget.org/packages/LiteDB.Identity/

There is also sample with base implementation with Default Identity UI.
In near future, I hope to post more advanced scenario for ASP.NET Core 3.1 Identity.

Let me know what scenarios you want to use it for ?

Cheers
Piotr

**Comment by a-a-k** [comment]
@quicksln thank you! This is what I asking for. I have a most primitive scenario - small web app with a few users and two roles.
