### ISSUE TITLE
[QUESTION] LiteDb v5 Query Api Group By Issue

### ISSUE THREAD

**Issue by oleg-chibikov** [mbdavid/LiteDB#1716]
Hi!
I am trying to execute a LiteDB (v5) query but facing the problem with Group By.

I am building my expression in C# like that:
var r1 = collection.Query()
		        .GroupBy("Age")
		        .Select("{Key: @Key,Max: Max(Id)}").
		        ToArray();
Here I want to get the maximum Id of the person in each age group.

It results in the following SQL:

SELECT {Key:@Key,Max:MAX($.Id)}
FROM Person
GROUP BY $.Age

However, the engine throws this exception:

'Field 'Id' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.'

Could you please explain how to use aggregate functions with Group By?

I was able to use only Count(*) or Max(@Key).

PS. I thought I might need to use 'Include' function to add the Id field into the groups, but GROUP BY doesn't allow me to do it.

**Comment by oleg-chibikov** [comment]
Thank you! It works.

**Comment by 1nfected** [comment]
> @oleg-chibikov Just replace `MAX($.Id)` with `MAX(*.Id)` and it should work

This is such an important piece of info, which should definitely be a part of the documentation.
