### ISSUE TITLE
[QUESTION] Database file size reduction

### ISSUE THREAD

**Issue by SKProCH** [mbdavid/LiteDB#1719]
I would like to know all the available methods for reducing the size of database files, without data loss.

One of them, it seems to me, would be the ability to disable Extended JSON. 
![image](https://user-images.githubusercontent.com/29896317/84568987-ed35b200-ad8b-11ea-9c03-dcddced061c6.png)

Yes, it helps to store data more reliably, but my classes do not change, and if I change them, I will manually write a patch that will be launched when the database is initialized.

For me, the size of the database is critical, and I would like to know how to implement this and what other solutions exist to reduce its size.

**Comment by lbnascimento** [comment]
@SKProCH The term "extended JSON" refers merely to the notation that LiteDB uses to represent certain BSON types when converted to JSON, given that BSON is a superset of JSON. This has no impact in the storage size.

If you really need to reduce datafile size, your best option would be to rebuild the datafile frequently.

**Comment by SKProCH** [comment]
Ok i got you, thanks
