### ISSUE TITLE
Error while installing LiteDB v5 in Vs2015

### ISSUE THREAD

**Issue by Fanom2813** [mbdavid/LiteDB#1723]
Hello,  I'm new to liteDB and o tried to install it on visual studio 2015 but am getting an error " failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache. "
When I downgrade to 4x it installs successfully can anyone help me to fix that thank you

**Comment by TRYGISER** [comment]
Install-Package System.Runtime -Version 4.3.1

**Comment by TRYGISER** [comment]
System.Runtime package is a part of dotnet standard but not in dotnetFrameWork 4.6.you can install it with package manager cli.

**Comment by TRYGISER** [comment]
> Hello, I'm new to liteDB and o tried to install it on visual studio 2015 but am getting an error " failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache. "
> When I downgrade to 4x it installs successfully can anyone help me to fix that thank you
Install-Package System.Runtime -Version 4.3.1

**Comment by Fanom2813** [comment]
> Install-Package System.Runtime -Version 4.3.1

At first I had installed it but I had the save message that's because vs did not add System.Runtime In my references so I had To do it manually  and it worked out 

Thank you
