### ISSUE TITLE
[QUESTION] Best practice for lifetime of LiteDatabase?

### ISSUE THREAD

**Issue by jez9999** [mbdavid/LiteDB#1728]
The docs on the website give an example of creating `LiteDatabase` in a `using` block:

`using(var db = new LiteDatabase(@"C:\Temp\MyData.db")) { ... }`

But in our application, we're going to be using `LiteDatabase` in lots of different places.  Is it best practice for us to create just one instance of `LiteDatabase` and get that instance from a service that has lifetime scope over our application, or to instantiate a new instance in a `using` block each time we want to use LiteDB?

**Comment by lbnascimento** [comment]
@jez9999 If keeping the file locked indefinitely is not an issue for you, then it should be fine keeping a live instance of `LiteDatabase` throughout the life cycle of your application. Making sure it is disposed on shutdown is good practice, but technically not necessary. If you're dealing with large amounts of data and experience performance loss or large log files, just run a checkpoint every once in a while.
