### ISSUE TITLE
Lite DB V4 to V5 Upgrade Documentation

### ISSUE THREAD

**Issue by Niku1985** [mbdavid/LiteDB#1729]
Please share the documentation on Lite DB V4 to V5.

**Comment by lbnascimento** [comment]
@Niku1985 Do you mean documentation on upgrading a LiteDB v4 datafile to v5? There's not much to it, all you need to do is set `Upgrade` to `true` in the connection string and the datafile should be upgraded automatically. For more info, check out our [Connection String documentation](http://www.litedb.org/docs/connection-string/).

**Comment by JelleDamen** [comment]
Is it correct that utc=true is not needed anymore in V5. Because it is UTC by default now ?

**Comment by lbnascimento** [comment]
@JelleDamen The UTC configuration is no longer done in the connection string, it is now a pragma. You can change with `db.UtcDate = true;`. The default value is still `false` though.

**Comment by Niku1985** [comment]
Thanks a lot for your email

Thanks
Nithyakumar
