### ISSUE TITLE
v1.0.4  Enum type is only queryable with the Query syntax

### ISSUE THREAD

**Issue by mishrsud** [mbdavid/LiteDB#173]
Summary: Save a poco type with an Enum type as a property, index on that property
When querying using Linq syntax, no data found (even though I can query using the Shell)
Using the Query syntax returns the expected data

The issue is demonstrated in this gist: https://gist.github.com/mishrsud/8f65bc4fe085e11ce0d5c5d00770ab44

**Comment by mbdavid** [comment]
Hi @mishrsud, BsonMapper store enuns as string, but I beleave that Linq are not converting this. I will made some tests about that.
