### ISSUE TITLE
[QUESTION] Does LiteDB 5 actually support transactions?

### ISSUE THREAD

**Issue by jez9999** [mbdavid/LiteDB#1730]
The discussion [here](https://github.com/mbdavid/LiteDB/issues/791) would seem to suggest a re-introduction of transactions was being planned for LiteDB 5, and indeed `db.BeginTrans()` does exist, yet that issue is still open; so does LiteDB 5 now support transactions or not?

**Comment by lbnascimento** [comment]
@jez9999 Transactions are supported in LiteDB v5.
