### ISSUE TITLE
[QUESTION] Sharing the database between processes on Android?

### ISSUE THREAD

**Issue by jez9999** [mbdavid/LiteDB#1731]
We need to share a LiteDB database between 2 processes on Android, but if we try to use `Connection = ConnectionType.Shared`, we get the error "Shared mode is not supported in platforms that do not implement named mutex".  SQLite allows multiple processes to share a single-file DB on Android so it's obviously possible... why can't LiteDB do it?

**Comment by lbnascimento** [comment]
@jez9999 Shared mode currently uses a system-wide mutex to control file access. If the platform doesn't implement system-wide mutex, there's not much that can be currently done. However, the shared mode will be completely reworked for the next major release, and a version that uses lock files is currently in testing.
