### ISSUE TITLE
[QUESTION] Automatically Insert new Entities

### ISSUE THREAD

**Issue by JoshuaWegener** [mbdavid/LiteDB#1732]
I am having some trouble to understand what is possible and what isn't with LiteDB. We are saving some entities in our database that have references of other entities. For example:

public class InvoiceLine : IEquatable<InvoiceLine>
{
    [BsonRef("BillingAccount")] public BillingAccount Account { get; private set; }

[BsonRef("Employee")] public Employee Employee { get; private set; }

public Amount Amount { get; private set; }
}

So when I save an invoiceLine that has an existing Employee and a BillingAccount everything works as expected. But when I save an InvoiceLine with an Employee that does not exist I would expect that LiteDB inserts that Employee into the correct collection and saves the newly added reference.
Sadly it seems like it saves a reference with the id "0", meaning none is created. I checked that with lite studio and there is no new entity created besides the InvoiceLine with faulty references.

Is there anything I have to add to create new entities automatically or is this not supported by LiteDB?

**Comment by lbnascimento** [comment]
@JoshuaWegener The `BsonRef` attribute is only used to create references upon storage and resolve references upon retrieval. Insertions and updates to the referenced collection still have to be done manually.
