### ISSUE TITLE
[QUESTION] How to use fluent mapper to ignore properties from a complex object?

### ISSUE THREAD

**Issue by luismiguelbarruco** [mbdavid/LiteDB#1734]
I'm trying to use fluent mapper to ignore some properties from a comples object, but when the application try to map object, a exception is throwing. It's possible to ignore a properties from a complex object?
![error](https://user-images.githubusercontent.com/61190302/85929411-de222a00-b88a-11ea-813b-1640f7f05099.png)

**Comment by lbnascimento** [comment]
@luismiguelbarruco You should run the fluent mapper commands over the `Versao` class (or whatever it's called):

`mapper.Entity<Versao>().Ignore(v => v.DiretorioRelease).Ignore(V => v.DiretorioTeste);`
