### ISSUE TITLE
[BUG] DBs with empty password parameter in the connection string still gets encrypted

### ISSUE THREAD

**Issue by duduric** [mbdavid/LiteDB#1735]
**Version**
5.0.8

**Describe the bug**
DBs with empty password in the connection string still gets encrypted somehow. We are only able to access it again if we keep the empty parameter in the connection string, but we are not able to open the files in LiteDB Studio since we can't give an empty password.

**Code to Reproduce**
Example connection string
Connection=shared;Password=;InitialSize=0;ReadOnly=false;Upgrade=true

**Expected behavior**
The password parameter should be ignored and the DB should not be encrypted

**Screenshots/Stacktrace**
![image](https://user-images.githubusercontent.com/5911443/86043317-ead78700-ba1e-11ea-9d4e-331d7f1eeb2c.png)

**Comment by lbnascimento** [comment]
@duduric This issue has been fixed in the master and its fix will be present in the next incremental release.

**Comment by duduric** [comment]
@lbnascimento is there an easy way to batch decrypt all our affected files? I assume they would stop working in the new version.

**Comment by lbnascimento** [comment]
@duduric Just run `db.Rebuild(new RebuildOptions { Password = null });`, this should decrypt the file.
