### ISSUE TITLE
Id by another class

### ISSUE THREAD

**Issue by Yaniv-Y** [mbdavid/LiteDB#1737]
Dear LiteDB team

I am trying to create, like mentioned in [this comment](https://github.com/mbdavid/LiteDB/issues/741#issuecomment-333200925), a new class for my Id.

```
public class Target
{
    [BsonId]
    public EntityId Id { get; set; }
    public string Name { get; set; }
}

public class EntityId
{
    public EntityId()
    {
    }
    [BsonId]
    public int Id { get; set; }
}

static void Main(string[] args)
{
    using (var db = new LiteDatabase(@"t.db"))
    {
        var col = db.GetCollection<Target>("t");
        col.Insert(new Target { Name = "t" });
    }
}
```

I get the next exception in versions 4.x:
> Invalid BSON data type 'Null' on field '_id'.

I get the next exception in versions 5.x:
> Unable to cast object of type 'LiteDB.ObjectId' to type 'Mongo.EntityId'.

Many thanks for help.
Many thanks for your feature.

Yaniv

**Comment by lbnascimento** [comment]
@Yaniv-Y If you want to use a custom class as your document id, you'll have to manually set its value for every document to be inserted. The Auto Id feature only works for types `ObjectId`, `Guid`, `Int32` and `Int64`.

**Comment by Yaniv-Y** [comment]
Thanks for reply. Is there a way to get a new int id without iterating the entire collection?

**Comment by lbnascimento** [comment]
@Yaniv-Y Yes, just make sure that the `Id` field in your class is of type `Int32` and open your collection like this: `var col = db.GetCollection<MyClass>("CollectionName", BsonAutoId.Int32)`. This way, every inserted document will get a new id automatically.

**Comment by Yaniv-Y** [comment]
I meant weather there is a way in code to generate the Id, I know about the automatic way 😁

**Comment by lbnascimento** [comment]
@Yaniv-Y You would have to come up with a manual solution for your use case. LiteDB uses skip lists for indexing (and the `_id` field is always indexed), so `col.Max()` should run on average in **O(log n)** - the worst case is **O(n)**, but this should be very rare.
