### ISSUE TITLE
[V4] Prevent a field from being updated with Upsert ?

### ISSUE THREAD

**Issue by ju2pom** [mbdavid/LiteDB#1738]
Hi,
When adding a new document I always use **Upsert** because I don't know if it's already in the db and I don't want to check for each document if it exists or not because I can add tens of thousand documents in a batch.
My document has a "Date Added" property which tells when the document has been added to the database.

My problem is that this property gets updated every time when it should stick to its original value.
Is there a way to do this kind of behavior?

Thanks.

**Comment by lbnascimento** [comment]
@ju2pom There's currently no way to make `Update` or `Upsert` ignore certain fields when updating. They always replace the entire document.

A feature like this is being considered for future versions.
