### ISSUE TITLE
Support parameterized constructors to be compatible with [ContractInvariantMethod] from Code Contracts

### ISSUE THREAD

**Issue by RufusJWB** [mbdavid/LiteDB#174]
It would be great, if you could support the use of parameterised constructurs for deserialization of objects out of the DB. This is essential for the use of Code Contracts [ContractInvariantMethod]. Compare with http://stackoverflow.com/questions/26902210/temporarily-disable-code-contracts-inside-a-block for details.

**Comment by mbdavid** [comment]
Hi, i'm organizing issues so I will reference this in #20 issue.
