### ISSUE TITLE
[QUESTION] A few questions on the LiteEngine and LiteDatabase classes

### ISSUE THREAD

**Issue by Dyaminigo** [mbdavid/LiteDB#1741]
I recently upgraded LiteDB to version 5 and I had some questions that I couldn’t find answers to.
1. What kind of LiteEngine class appeared in version 5 and how does it differ from the standard LiteDatabase class?
2. In version 4, I very often used the ability to set indexes when initializing the database, but in version 5 I found such an opportunity only in the LiteEngine class. I would very much like to know why the installation of indexes during database initialization was moved to the LiteEngine class, but is missing in LiteDatabase?
3. Is it possible to use the LiteEngine class to fully work with the database instead of the LiteDatabase class, whose capabilities are not enough for me to work properly?

Thank you all in advance for your answers.

**Comment by lbnascimento** [comment]
1. `LiteEngine` is the class that actually implements the LiteDB engine, while `LiteDatabase` provides a more friendly API for users by abstracting away some implementation details of LiteDB.
2. Could you explain what you mean by "ability to set indexes when initializing the database"? I'm not aware of such features in v4 (maybe because I didn't contribute to v4, so my knowledge is somewhat limited in that regard)
3. While not standard practice, I believe it is possible to use `LiteEngine` directly. You won't be able to get `LiteCollection` objects, you'll have to use it like `engine.Insert(collectionName, documents, BsonAutoId.ObjectId)`. And you'll also lose all mapper functionality, like object-to-document mapping and Linq-to-BsonExpression mapping.

**Comment by Dyaminigo** [comment]
2. In v4, it was possible to define indexes for different collections and their fields when initializing the database using the methods of the engine. For clarity, I will write below a part of my code that always worked on v4, freeing me from defining indexes when receiving collections, and in v5 it stopped working:

internal static LiteDatabase _baseDB { get; private set; }
...
static LDB()
{
_baseDB = InitializeDB();
}
...
private static LiteDatabase InitializeDB()
{
var db = new LiteDatabase(DatabasePath);
var engine = db.Engine;

engine.EnsureIndex("Account", "UserId", true);
engine.EnsureIndex("Account", "PVersion", false);
engine.EnsureIndex("UserGuid", "UniqueGuid", true);
engine.EnsureIndex("UserGuid", "CreationDate", false);
engine.EnsureIndex("OriginalHash", "Hash", true);
engine.EnsureIndex("OriginalHash", "Version", true);
engine.EnsureIndex("BadRequest", "HttpMethod", false);
engine.EnsureIndex("BadRequest", "IP", false);
engine.EnsureIndex("BadRequest", "RequestDate", false);
return db;
}

In v5, there is no longer the Engine namespace in LiteDatabase, which made it unclear to me how indexes can be defined when initializing the database. It was convenient. If you tell me how to do this conveniently in v5, I will be very grateful to you.
3. Although I found several features I needed in the LiteEngine class, which are not in the LiteDatabase class and which were by default in v4, but I am not ready to lose the ability to map objects. I do not know what to do. Multiple indexes, generating expressions on the fly, generating predicates and working with them in the Delete, Update, etc methods was very convenient in v4. But now I have build errors and need to change the code. I thought about returning to v4, but it would be a pity to lose the ability to work normally from the many threads that are implemented in v5.

Maybe the respected @mbdavid will be able to tell me how to use the above functionality in v5 as it was in v4.

**Comment by lbnascimento** [comment]
@Dyaminigo You could use our SQL-like syntax to create indexes on initialization:

```C#
var db = new LiteDatabase(DatabasePath);
db.Execute("create unique index UserId on Account ($.UserId)");
db.Execute("create index PVersion on Account ($.PVersion)");
```

The syntax for index creation is: `CREATE [ UNIQUE ] INDEX {indexName} ON {collection} ({indexExpr})`.

**Comment by Dyaminigo** [comment]
@lbnascimento This is exactly what I needed. Thank you for your help!
