### ISSUE TITLE
[QUESTION] Accessing nested objects in LiteDB v5

### ISSUE THREAD

**Issue by panther142** [mbdavid/LiteDB#1743]
Hi,

I am using LiteDB v5.08 and have a simple scenario where I have a number of POCO's such as:

```
class Portfolio
{
   public int Id { get; set; }
   public List<Holdings> Holdings { get; set; } = new List<Holdings>();
}

class Holdings
{
  public int Id { get; set; }
  public List<Transaction> Transactions { get; } = new List<Transaction>();
}

class Transactions
{
  public int Id { get; set; }
  public int Value {get; set; }
}
```

I am able to create my collection in the database and the objects are correctly nested as I expect, such as Portfolio -> Holdings -> Transactions. No issues with In/Upsert. As an example I created:
- 1 Portfolio
   - Holdings #1
      - 2 Transactions
   - Holdings #2
      - 2 Transactions

However, when I use LiteDB to get the portfolio collection from the database, it returns my 1 Portfolio, 2 Holdings but neither of the Holdings objects contain any transactions even though LiteDBStudio shows them as existing.

I have tried a series of comibantions of Include, FindOne, FindAll etc without any success.  So, how do I go about including the Transactions in my collection?

My ultimate goal is to return a portfolio that contains all its holdings and all the transactions for those holdings.

Thanks in advance.

**Comment by lbnascimento** [comment]
@panther142 This is happening because the `Transactions` attribute in `Holdings` is read-only. The transactions are being stored correctly (that is why you see them in LiteDB.Studio), but they are not being returned because the mapper looks for a public setter and doesn't find one.

The simplest solution would be to add a public setter. If that is not possible in your scenario, you could create a custom constructor and add `BsonCtorAttribute` to it so that the mapper knows to use it.

**Comment by panther142** [comment]
Thanks for your reply @lbnascimento - would you be so kind as to provide a small code example for both options please?

**Comment by lbnascimento** [comment]
@panther142 If you want to add a public setter to the `Transactions ` property in `Holdings`, just add `set;` after `get;` in its declaration. If you want to make a custom constructor, it would be something like this:

```C#
public Holdings(int id, BsonArray transactions)
{
        var mapper = BsonMapper.Global;
        Id = id;
        Transactions = transactions.Select(x => mapper.Deserialize<Transactions>(x)).ToList();
}
```

**Comment by panther142** [comment]
Thanks for your help!
