### ISSUE TITLE
About partition 

### ISSUE THREAD

**Issue by hiddenuser** [mbdavid/LiteDB#1744]
I’m using `LiteDb `  to store information in a single file. My goal is to have one file per month. But the record number has increased so much that file is almost over 2GB in size. Is there a way I can partition this information without major changes to the code? Something like having multiple files related to the same database?

**Comment by lbnascimento** [comment]
@hiddenuser LiteDB has no specific functionality regarding data partition or multiple datafiles. You would have to implement a solution of your own, I believe.
