### ISSUE TITLE
[QUESTION] Converting vb.net lambdas on upgrade to V5

### ISSUE THREAD

**Issue by stigzler** [mbdavid/LiteDB#1745]
I do love LiteDb, but I've come across a real pain on upgrading to V5. I've got 18 months of code using lambdas in find queries and now having to go through converting them all (as these don't work in V5 as per post [here](https://github.com/mbdavid/LiteDB/issues/1433)). I think I can do the basics - e.g.:

`db.Collections.mDisplayAdapters.Find(function(x) x.DeviceKey = disp.Adapter.DeviceKey.ToString).FirstOrDefault`

becomes:

`db.Collections.mDisplayAdapters.Find(Query.EQ("DeviceKey", disp.Adapter.DeviceKey.ToString)).FirstOrDefault`

However, how do I do similar on child properties of a top-level property. E.g:

`Dim gamesList = db.Collections.mGames.Find(Function(x) x.System.ID = System.ID)`

Would this just be:

`Dim gamesList = db.Collections.mGames.Find(Query.EQ("System.ID",System.ID))`

Hope there's a work around as don't want to roll back to V3!

**Comment by lbnascimento** [comment]
@stigzler Regarding the issue you mentioned, a simple workaround would be to use `.Equals` instead of the equality comparer. So, your second example would be something like `mGames.Find(Function(x) x.System.ID.Equals(System.ID))`.

**Comment by stigzler** [comment]
@lbnascimento - thanks for the quick reply. I'll substitute this in and test if it works. One reservation is that is looks like lambdas in V5 don't work in vb.net (they do in c#) - so we'll see how this goes..

**Comment by stigzler** [comment]
You got it, fella!!! It works. Hmmm - mysterious vb.net lambdas. Thanks again.
