### ISSUE TITLE
Query.Where is missing

### ISSUE THREAD

**Issue by Tyr0000** [mbdavid/LiteDB#1746]
Hi
I downloaded the master branch and 'm trying to work with liteDB
But I can not implement a db query

It looks like  Query.Where is missing  is missing in LiteDB.5.0.8 version

**Comment by lbnascimento** [comment]
@Tyr0000 It is not recommended to use the static `Query` methods in LiteDB v5. They were kept only for compatibility with v4 queries, are considered deprecated and may be removed in future versions.

There are three ways to make a query in LiteDB:
* Using our SQL syntax;
* Using BSON expressions;
* Using Linq expressions (if you open your collection in a typed manner)

For more info, check the [Expressions documentation](http://www.litedb.org/docs/expressions/) and the [SQL syntax documentation](http://www.litedb.org/api/query/). If you have more specific questions, I'm happy to help you.

**Comment by Tyr0000** [comment]
thank's for the information
'll follow it
