### ISSUE TITLE
[BUG] System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by Lonli-Lokli** [mbdavid/LiteDB#1747]
**Version**
LiteDB 5.0.8

**Describe the bug**
IEnumerable usage of LiteDB causing exceptions

**Code to Reproduce**
1) Clone application
https://github.com/Lonli-Lokli/LiteDbDisposed
2) Run application

-  On the screen choose 1 to add a document, enter the title and press enter
-  On the screen choose 2 to display added documents

**Expected behavior**
documents should be printed
System.ObjectDisposedException: Cannot access a disposed object. at System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(TimeoutTracker timeout) at System.Threading.ReaderWriterLockSlim.TryEnterReadLock(TimeSpan timeout) at LiteDB.Engine.LockService.EnterTransaction() at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew) at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan) at LiteDB.Engine.QueryExecutor.ExecuteQuery() at LiteDB.Engine.LiteEngine.Query(String collection, Query query) at LiteDB.LiteQueryable1.ToDocuments()+MoveNext() at System.Linq.Enumerable.SelectEnumerableIterator2.MoveNext()

**Comment by lbnascimento** [comment]
@Lonli-Lokli Your code tries to iterate through an `IEnumerable` after the `LiteDatabase` has already been disposed, which is definitely not possible. If you really need to structure your code in such a way, you should use Shared mode (just add `Connection=Shared;` to your connection string.

**Comment by Lonli-Lokli** [comment]
@lbnascimento Got your point regarding LINQ deferred execution. The it's not clear for me why we have IEnumerable over ILiteDatabase for FindAll.

Do you see any allowed usage of deferred execution with maybe IQuerable?

**Comment by lbnascimento** [comment]
@Lonli-Lokli The Direct mode does not support any form of deferred execution, but the Shared mode does.

**Comment by Lonli-Lokli** [comment]
@lbnascimento thankz closing then
