### ISSUE TITLE
System.InvalidCastException:“无法将类型为“System.Boolean”的对象强制转换为类型“System.String”。

### ISSUE THREAD

**Issue by caochang** [mbdavid/LiteDB#1748]
[db.zip](https://github.com/mbdavid/LiteDB/files/4887875/db.zip)
   在 lambda_method(Closure , Object , Object )
   在 LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
   在 LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   在 LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   在 LiteDB.LiteCollection`1.FindOne(Query query)
   在 xxx.LiteDBManager.GetRecord[T](String tableName, Query query) 位置 xxx\LiteDBManager.cs:行号 229

这是我在插入一条数据后，对该数据进行检索时出现的异常

LiteDB:v5.0.8
.Net Framework 4.5

在表为空时 通过FindOne(Query query)来检索数据也会出现同样的异常

**Comment by lbnascimento** [comment]
@caochang Could you provide the data file for which it is happening?

**Comment by caochang** [comment]
@lbnascimento Uploaded

**Comment by lbnascimento** [comment]
@caochang Could you provide some more information, like your connection string, the code you're using to open a collection and your query?

**Comment by caochang** [comment]
liteDB = new LiteDataBase(fileFullName);
lc1 = liteDB.GetCollection<T>(tableName1);
lc1.EnsureIndex(indexName, true);
lc2 = liteDB.GetCollection<T>(tableName2);
lc2.EnsureIndex(indexName, true);

query = new Query();
query.Select = Query.EQ(indexName, new BsonValue(str));

我看了源码
这样做似乎是错误的 

我沿用了4.x版本LiteDB的用法
4.x版本的 LiteCollection.FindOne(Query) 是应该改为使用 LiteCollection.FindOne(BsonExpression)么？

@lbnascimento

**Comment by lbnascimento** [comment]
@caochang You are using `Query` incorrectly. You're attributing a `Query.EQ` to `query.Select`, which is wrong. You should be adding it to `query.Where` instead: `query.Where.Add(Query.EQ(indexName, new BsonValue(str)))`.

You can also use `BsonExpression` and its implicit conversion from string: `lc1.FindOne($"{indexName} = '{str}'")`.

**Comment by caochang** [comment]
建议在Query的属性上添加注释 利于理解功能
