### ISSUE TITLE
Web Assembly support

### ISSUE THREAD

**Issue by danielmeza** [mbdavid/LiteDB#1749]
As web assembly come into the .NET world as a new platform, bring the support for this platform will be awesome! This way we can have a NoSql database write entirely in manage code in the browser side.

**Comment by chaseaucoin** [comment]
There is an example of this here. 
https://github.com/nukedbit/BlazorLiteDbQuickHack

The problem you're going to run into is currently only Chrome gives full read and write control over filesystem objects. So actually creating performant file streams is pretty much a non-starter; You could have a very small db in memory and flush to the indexdb or cache every so often but ultimately any kind of long term persistent storage is going to be off the table for client application via WASM

**Comment by danielmeza** [comment]
Nice answer! I will close this since its not depende n the package but the framework.

**Comment by danielmeza** [comment]
@chaseaucoin  The chrome option can work well for electron desktop apps, thanks again!

**Comment by chaseaucoin** [comment]
If you are using Electron, you can actually just use .NET straight up with direct access to the file system. 

https://itnext.io/create-desktop-with-electron-react-and-c-86f9765809b7
