### ISSUE TITLE
[BUG] LiteDB.LiteException: 'Invalid BSON data type 'Null' on field '_id'.'

### ISSUE THREAD

**Issue by offengenden** [mbdavid/LiteDB#1750]
Using: LiteDB 5.0.8, .Core  3.1

I've created a collection using interface. I can get or insert data. When I update existing rows I get this error message: LiteDB.LiteException: 'Invalid BSON data type 'Null' on field '_id'.'

```
internal static LiteDatabase GetDatabase()
{
            var mapper = BsonMapper.Global;
            mapper.Entity<IProductItem>().Id(x => x.Barcode, autoId: false);
            return new LiteDatabase(@"C:\Users\micha\path\LiteDB\Database.db", mapper);
}
```

```
public int UpdateProducts(List<IProductItem> updatedProducts)
{
            using var db = DataBase.GetDatabase();
            var col = db.GetCollection<IProductItem>("inventory");
            var count = col.Update(updatedProducts);
            return count;
}
```

**Comment by chaseaucoin** [comment]
Do all of the updatedProducts have barcodes? Because it looks like some might be null.

**Comment by lbnascimento** [comment]
@offengenden This issue has been fixed in the master and its fix will be present in the next incremental release.

**Comment by lbnascimento** [comment]
@chaseaucoin I will reopen this issue, because the solution I came up with had some issues and was not up to our standards. We are currently thinking of a way to fix this issue.

**Comment by lbnascimento** [comment]
I did some research on this subject. The fluent mapper commands are meant to be functionally identical to the Bson attributes, and C# does not allow for attributes in an interface to be automatically inherited in classes that implement the interface (attributes should be re-declared in base classes). Actually, nothing is inherited from an interface to a derived class, everything must be implemented.

While it is possible in theory to come up with a solution that detects attributes in interfaces, I'm not even sure it should be done, given that it goes against the C# language design.
