### ISSUE TITLE
[QUESTION] Is this the correct way to create / read and find data with LiteDB ?

### ISSUE THREAD

**Issue by stephenhauck** [mbdavid/LiteDB#1751]
I have a class like so ...
![image](https://user-images.githubusercontent.com/12648793/87089441-719d1880-c204-11ea-81af-6cb5cbc668c0.png)

If I do not decorate the ObjectId field with the Bson attribute it does not map it when retrieved from the database but it does correctly set the value when it writes to the database ?
![image](https://user-images.githubusercontent.com/12648793/87089590-a27d4d80-c204-11ea-8ec2-d5ea544c9f0e.png)

I have declared a method like so ..
![image](https://user-images.githubusercontent.com/12648793/87089710-d8223680-c204-11ea-9a1d-31a7a0246430.png)

Do I have to send in the object id like this every time ?
![image](https://user-images.githubusercontent.com/12648793/87089780-f1c37e00-c204-11ea-958a-cb10017f590b.png)

**Comment by lbnascimento** [comment]
@stephenhauck If you don't use `BsonIdAttribute` to select your id property, the mapper automatically searches for a property in your class with name `Id` or `<ClassName>Id` (in your example, it would be `TodoSimpleId`). If none is found, it creates an additional unmapped `_id` field in the mapped document (a random `ObjectId` will be stored internally, but it will not be mapped to any property in your class upon retrieval).

LiteDB also supports Auto Id: if your id field is of the type `ObjectId`, `Guid`, `Int32` or `Int64`, you don't need to specify an id value upon insertion, an appropriate id will be generated (a random value if id is `ObjectId` or `Guid`, the next possible value if id is `Int32` or `Int64`).

Regarding your `GetTodoSimple` method, I believe it is the correct way to find by id when it is of type `ObjectId` (at best, you could take an string as argument and call the `ObjectId` constructor inside your method). If you want an easier way to use it, consider using `Int32` or `Int64` as your id.

**Comment by stephenhauck** [comment]
ok, thanks
