### ISSUE TITLE
Can I create a database in memory as I have no file storage

### ISSUE THREAD

**Issue by GregObleshchuk** [mbdavid/LiteDB#1752]
I need a light weight database engine for an Azure function I am writing.  As I have file storage I can't create a database in a file location.    Is it possible to just create a database in memory (Like SQLLite)

cheers
Greg

**Comment by lbnascimento** [comment]
@GregObleshchuk Yes, you can create an in-memory database with `var db = new LiteDatabase(":memory:")` or `var db = new LiteDatabase(new MemoryStream())`.
