### ISSUE TITLE
[QUESTION] Why are the tests for GROUP BY commented out

### ISSUE THREAD

**Issue by dangershony** [mbdavid/LiteDB#1753]
https://github.com/mbdavid/LiteDB/blob/master/LiteDB.Tests/Query/GroupBy_Tests.cs#L49

I am especially interested in the GROUP BY and SUM from expressions calls

**Comment by dangershony** [comment]
Further to that I wonder if `Sum` is in he plans? I dont see it here

https://github.com/mbdavid/LiteDB/blob/8bfdc4fb58559c62a2a394c55847b80e65ac24d5/LiteDB/Client/Database/ILiteQueryable.cs

**Comment by lbnascimento** [comment]
@dangershony I believe these tests were made for a possible implementation of grouping expressions in Linq, which are not currently available in LiteDB. Personally, I don't think it makes much sense to use Linq expressions with GROUP BY: Linq expressions are meant for "typed" collections, where there is a fixed structure to the documents (defined by the LiteDB mapper), and grouping modifies the structure of the documents.

You can still use GROUP BY with Bson expressions and with the SQL syntax.

**Comment by dangershony** [comment]
thanks @lbnascimento
