### ISSUE TITLE
[BUG] System.InvalidOperationException This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

### ISSUE THREAD

**Issue by BruceMellows** [mbdavid/LiteDB#1754]
**Version**
LiteDB: 5.0.8.0

Windows 10 Enterprise
OSVersion: 10.0.17763
ServicePackLevel: 1809
CLRVersion: 4.0.30319.42000

This version of windows is configured for "FIPS" -  https://www.eonesolutions.com/help-article/this-implementation-is-not-part-of-the-windows-platform-fips-validated-cryptographic-algorithms/

**Describe the bug**
Opening a shared connection has an exception due to the hashing algorithm implementation being used not being considered safe by the OS configuration.

**Code to Reproduce**
using (var database = new LiteDatabase("filename=irrelevant.litedb;connection=shared")) { }

**Expected behavior**
No exception would be thrown.

**Screenshots/Stacktrace**
```
ExceptionType: System.InvalidOperationException 
Message: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms. 
HResult: 0x80131509 
 at System.Security.Cryptography.SHA1Managed..ctor()
 at LiteDB.StringExtensions.Sha1(String value)
 at LiteDB.SharedEngine..ctor(EngineSettings settings)
 at LiteDB.ConnectionString.CreateEngine()
 at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
 at LiteDB.LiteDatabase..ctor(String connectionString, BsonMapper mapper)
```

**Additional context**
I have tried with HAVE_SHA1_MANAGED not present, and it does work under this configuration

**Comment by lbnascimento** [comment]
@BruceMellows LiteDB currently uses AES with ECB as its block cipher mode, which is known to leak data patterns. We are currently testing an XTS implementation, and it should be available in the next major release.

**Comment by BruceMellows** [comment]
This is not an encryption issue as such, it is the hash algorithm used to derive the shared mutex name.

In my case (because I have control of the application config) I can use <runtime><enforceFIPSPolicy enabled="false"/></runtime> to work around the issue

**Comment by BruceMellows** [comment]
XML went missing ... `<runtime><enforceFIPSPolicy enabled="false"/></runtime>`

**Comment by lbnascimento** [comment]
@BruceMellows This issue has been fixed in the master and its fix will present in the next incremental release.

**Comment by BruceMellows** [comment]
I did my testing from a master copy, so I think that this is not correct.

**Comment by lbnascimento** [comment]
@BruceMellows Did you test with the latest master? The `SHA1Managed` was removed, leaving only the default `SHA1` object.
