### ISSUE TITLE
DI: ILiteDbContext not found -- v5.0.8, .Net Core 3.1 MVC

### ISSUE THREAD

**Issue by looselyhuman** [mbdavid/LiteDB#1763]
Hi all,

First LiteDB app here. I'm following the guide at https://blog.georgekosmidis.net/2019/11/02/using-litedb-in-an-asp-net-core-api/

In creating my DBContext class, I'm unable to implement ILiteDbContext - not found.

What am I missing?

Many thanks!

**Comment by ZenSystemOutlookCom** [comment]
Check out this code here: https://github.com/georgekosmidis/LiteDbSample he has created the ILideDBContext himself so the code is there - I was just having the same issue just copying his code from the page but it missed some steps.

**Comment by looselyhuman** [comment]
Haha! Thanks! Duh.
I was kind of wondering where that weather thing came from... The DI pattern was just so standard that it seemed official.
Thanks again.
