### ISSUE TITLE
Just upgraded a project from V4 to latest V5 getting "Cannot convert lambda expression to type 'BsonValue' because it is not a delegate type"

### ISSUE THREAD

**Issue by chucksullivancvs** [mbdavid/LiteDB#1767]
I just upgraded a C# project reference from LiteDB 4 to latest v5.0.8. First converted data file using LiteDB Studio. Still worked.

Change the C# project reference to v5 and now get a compiler error:

"Cannot convert lambda expression to type 'BsonValue' because it is not a delegate type"

on this Collection Delete method statement that was previously working.

`using (var db = new LiteDatabase(@DBConnection))
{
                    var requests = db.GetCollection<Request>("Request");
                    requests.Delete(x => x.CreateDate < deletedate);                    
 }`

I'm not an expert in Lambda, LINQ or BSON.

Didn't find any obvious answers.

I'm looking for an easy fix. Please advise. Thx.

**Comment by lbnascimento** [comment]
@chucksullivancvs There was a small change in the delete syntax for v5: the method `LiteCollection.Delete` is now only used when you want to delete a single document by its id. For other usage, you should use `DeleteMany`.

**Comment by chucksullivancvs** [comment]
Thanks Leonardo for the quick reply. I had just found the DeleteMany and was looking into it,

That worked!

Changed to this and it compiled and worked.

                  requests.DeleteMany(x => x.CreateDate < deletedate);    

Now on to the next upgrade issues...

Chuck

**Comment by gbthakkar** [comment]
Hi,
I am little late here.
The answer definately solved the issue for chucksullivancvs . But there is sitution where we want to delete one record(document) in collection based on ID.
Like
public class Service
    {
        public int Id { get; set; }
        public string Name { get; set; } = "";
        public bool IsActive { get; set; }=true;
    }
Now what should be the code to delete one service based on ID. Because BsonValue is known to me in this case.

**Comment by chucksullivancvs** [comment]
Good to know. Thx for your consideration.
