### ISSUE TITLE
Upgraded from V4 to V4 - simple Find(Query.All()) stopped working

### ISSUE THREAD

**Issue by chucksullivancvs** [mbdavid/LiteDB#1769]
Searched for this but found nothing.

Problem:

This works fine in V4, fails to produce usable results in V5. 

This pretty basic operation has been upgraded to V5. Data file has been upgraded using LiteDB Studio.

               using (var db = new LiteDatabase(@ConfigDBConnection))
                {
                    var items = db.GetCollection<Item>(collection);

                    var results = items.Find(Query.All());

                }

New LiteDatabase produces what looks like a valid LiteDB.LiteDatabase reference.

GetCollection returns a seemingly valid object reference to the right type: "LiteDB.LiteCollection<AIMFacTool.Item>"

V5 Query.All produces an unusable "System.Linq.Enumerable.WhereSelectEnumerableIterator<LiteDB.BsonDocument, AIMFacTool.Item>" and an error in the ResultsView of "Error The function evaluation requires all threads to run."

Whereas V4 produces a usable "LiteDB.LiteCollection<AIMFacTool.Item>" object.

I am hoping there is a workaround or alternative I can use, otherwise I will have to revert back to V4.

Am looking forward to using LiteDB Studio though so I am keeping my hopes up that this is an easy fix.

Thanks in advance for your help.

**Comment by lbnascimento** [comment]
I'm not sure why you call the result of the `LiteCollection.Find` method unusable. This class `WhereSelectEnumerableIterator<T>` is an internal C# class, and it implements `IEnumerable<T>`, so you can use it in many ways, like iterating with a `foreach` loop and calling `ToList()` or `ToArray()`.

Also, the `The function evaluation requires all threads to run` error is related to a limitation of the Visual Studio debugger for multi-threaded code, it has nothing to do with LiteDB itself and should never happen when running it without a debugger attached.

**Comment by chucksullivancvs** [comment]
Perhaps I should have said "I don't know how to use it" which is really what I was trying to say.

Casting the result to a List solved the problem, as in:

                    var items = db.GetCollection<Item>(collection);
                    var results = items.Find(Query.All());
                    results = results.ToList();
                    return results;

I did not have to do this in V4 and did not find anything in the documentation that mentioned this change in behavior.

Thanks again Leonardo.

LiteDB is a great little tool and overall I have had good success using it.

Keep up the good work!
