### ISSUE TITLE
[BUG] Include ignored with Query instruction

### ISSUE THREAD

**Issue by animha** [mbdavid/LiteDB#1774]
Hello,

I'm using LiteDb 5.0.8, in a NetCore 3.1 application.

I'm encountered a strange issue working with BsonRef.

I have an object A, which contains a list of objects B (BsonRef):
`[BsonRef]
public List<B> Bees { get; set; }`

If I load an instance of A, using:
`db.GetCollection<A>()
.Include(a=>a.Bees)
.FindById(....)`

I get my instance, with my property "Bees" fully polulated.

If I load the same instance using Query() instruction:
`db.GetCollection<A>()
.Include(a=>a.Bees)
.Query()
.Where(a=>.....)
.ToList()`

The collection "Bees" is populated with only the keys of the objects, but all other B's properties are null (in other words: the "Include" instruction is somehow ignored).

Is this an expected behaviour?

**Comment by lbnascimento** [comment]
@animha This issue has been fixed in the master and its fix will be present in the next incremental release.

In the meantime, you can call `Include` after `Query` and it should work.

**Comment by animha** [comment]
Wonderful!
