### ISSUE TITLE
[QUESTION] Get collection size or how can calculate the collection size Version 5

### ISSUE THREAD

**Issue by foxshooter** [mbdavid/LiteDB#1779]
Hello,

give a function how can read the collection size out of the box?

or

How can the calculate this? 
In the version 4 i have claculate this about the singel documents with "GetBytesCount(true)" but this is not working on liteDB 5.

I switch liteDB 4.1.4 to 5.0.8.

Have you an Idee? Thank you

**Comment by lbnascimento** [comment]
@foxshooter If you want to read the total size occupied by a collection, you can do it with the following command:

```C#
int bytes = db.Execute("select SUM(*.usedBytes) from $dump where pageType = 'Data' and collection = 'collection'").Single()["usedBytes"];
```

It's a bit convoluted, but it works fine. Of couse, you need to change the collection name in the query. We'll consider adding a property to the `LiteCollection` that gets this count.

**Comment by foxshooter** [comment]
@lbnascimento Thank you.
Can you explain why pageType='Data' and which Type can use?

**Comment by lbnascimento** [comment]
@foxshooter If you leave out the `pageType='Data'`, this will also include Index pages.

**Comment by foxshooter** [comment]
@lbnascimento okay, 
Thank you!

You helped me a lot.
