### ISSUE TITLE
Incorrect example on home page

### ISSUE THREAD

**Issue by thomaslevesque** [mbdavid/LiteDB#178]
I'm trying the examples on http://www.litedb.org/, and I realized that the one about "Fluent entity mapping" is incorrect: there is no `db.Mapper.Entity<T>` (tried with the latest stable version, 1.0.4). I thought that maybe it was added in the upcoming 2.0.0 version, but in that version there is no `db.Mapper` property...

**Comment by thomaslevesque** [comment]
Actually, the "Stream as database" example also doesn't work... there's no `LiteDatabase` constructor that accepts a `Stream`. Which version are the examples for?

**Comment by xszaboj** [comment]
I had the same problem, So I donwloaded 2.0.0 version and it worked fine.
Are you also using nuget package? because that has old version...

**Comment by thomaslevesque** [comment]
Yes, I'm using the NuGet package (2.0.0-rc). I understood how to do the mapping by looking at the tests in the source code: I had to create a subclass of `LiteDatabase` and override the `OnModelCreating` method. Which is probably a better approach IMO.

**Comment by mbdavid** [comment]
Hi guys, yes, wiki is for 1.04, homepage is for 2.0. It´s out of date. I'm working in LiteDB only weekends in `dev` branch.
And I'm not convinced how `BsonMapper` instance must be setted: Passed as parameter in constructor in LiteDatabase, using `OnModelCreating` like EF or as a Lambda expression property like `db.Configure((mapper) => { .... })`.

What did you think? Any idea?

**Comment by thomaslevesque** [comment]
> And I'm not convinced how BsonMapper instance must be setted: Passed as parameter in constructor in LiteDatabase, using OnModelCreating like EF or as a Lambda expression property like db.Configure((mapper) => { .... }).

I think the `OnModelCreating` is the cleanest one (because it prevents the user from changing the mapping after the `LiteDatabase` is constructed), but it's also a bit less flexible, because it forces you to subclass `LiteDatabase` if you want to customize the mapping. Another option would be to accept a delegate in the constructor:

    var db = new LiteDatabase(mapper => {...})

**Comment by mbdavid** [comment]
Nice idea, but I was thinking where store this instace after created BsonMapper instance. This instance must be `static` or be cached to avoid every run. Using subclass I stored in a static dictionary based on this database class Type.

**Comment by mbdavid** [comment]
Mapper instance are back in LiteDatabase. Now mapper can be passed in ctor or used from a BsonMapper.Global (like in v.1.0.4). Will be in next master commit
