### ISSUE TITLE
[BUG] High CPU usage when inserting POCOs with indexed DateTime property

### ISSUE THREAD

**Issue by botne** [mbdavid/LiteDB#1781]
**Version**
5.0.8

**Describe the bug**
High CPU usage when inserting POCOs with indexed DateTime property. When collecting stacks using PerfView in production half the CPU time is spent on converting between Local and Utc. It does not seem to matter if pragma for Utc is added.

**Code to Reproduce**
```
public class Event
{
    public int Id { get; set; }
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
}

using (var db = new LiteDatabase(new MemoryStream()))
{
    var users = db.GetCollection<Event>("events");
    users.EnsureIndex(u => u.Timestamp);

    // insert
    for(int i=0; i<100; i++)
    {
        users.Insert(new Event());
    }
}

```
**Expected behavior**
No transformation between UTC and LocalTime

**Screenshots/Stacktrace**

When running this invokes BufferSliceExtensions.ReadDateTime, and the DateTime is made Local:
![image](https://user-images.githubusercontent.com/17578375/89640761-8b3b8980-d8b0-11ea-877e-c94fcfe44c89.png)

![image](https://user-images.githubusercontent.com/17578375/89640643-4f082900-d8b0-11ea-90f9-04580c580c74.png)

**Additional context**
Not directly related to #1776, but I see that the same extenstion seems to be part of the problem there.

**Comment by lbnascimento** [comment]
@botne Could you test with the latest master?

**Comment by botne** [comment]
@lbnascimento: Looks good now! Have just tested in test enviroment. Looking forward to having this in a release. Thx! :D
