### ISSUE TITLE
How to create an index on a nested array?

### ISSUE THREAD

**Issue by tomthebearded** [mbdavid/LiteDB#1784]
Hi,

i've an object that is something like this 
```
public class Entry {
      public string Word {get; set;}
      public IEnumerable<Meaning> Meanings {get; set;}
}
public class Meaning {
     public string Info {get; set;}
     public IEnumerable<Reference> References {get; set;}
}
public class Reference{
     public string Index {get; set;}
     publi IEnumerable<string> Texts{get; set;}
}
```
and i'm trying to understand how can i create an index on the text property.
My guess after reading about expressions it's something like this
` entriesCollection.EnsureIndex("texts", "$Entry.Meanings[*].References[*].Text[*]");`
but i'm really not sure.

Can someone put me in the right direction?

**Comment by lbnascimento** [comment]
@tomthebearded Something like `entriesCollection.EnsureIndex("texts", "$.Entry.Meanings[*].References[*].Text");` should work fine.

**Comment by tomthebearded** [comment]
@lbnascimento thank you!

**Comment by lbnascimento** [comment]
@tomthebearded `entriesCollection.EnsureIndex("reference_word", "$.Senses[*].References[*].Word")` should work, but I found a bug in the expression parsing. I'll be working on a fix.

**Comment by lbnascimento** [comment]
@tomthebearded This issue has been fixed in the master and its fix will be present in the next incremental release.

**Comment by tomthebearded** [comment]
@lbnascimento super quick! awesome!

thank you very much!
