### ISSUE TITLE
[BUG] InvalidCastException when using `RegisterType` for basic types and a custom constructor

### ISSUE THREAD

**Issue by dropsonic** [mbdavid/LiteDB#1788]
**Version**
LiteDB 5.0.9
.NET Framework 4.8 / .NET Standard 2.0 / .NET Core 3.1

**Describe the bug**
`InvalidCastException` is thrown when using `RegisterType` for basic types and a POCO class with read-only properties and a custom constructor.
It works fine with a settable property and a parameterless constructor.

**Code to Reproduce**

https://dotnetfiddle.net/08Qnnh

```csharp
public class Foo
{
    public Foo(DateTime value)
    {
        Value = value;
    }

    public DateTime Value { get; }
}

// Main()
var mapper = new BsonMapper();
mapper.RegisterType<DateTime>(
    value => value.ToString("o", CultureInfo.InvariantCulture), 
    bson => DateTime.ParseExact(bson, "o", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind));
using (var db = new LiteDatabase("instance.db", mapper) { UtcDate = true })
{
    var expected = new Foo(new DateTime(637310234309996491, DateTimeKind.Utc));
    var col = db.GetCollection<Foo>();
    col.DeleteAll();
    col.Insert(expected);
    var actual = col.FindAll().First(); // InvalidCastException is thrown here
}
```

**Expected behavior**
No exceptions; the object is deserialized using the mapper provided with the custom registrations called for all inner types.

**Screenshots/Stacktrace**

```csharp
Unhandled Exception: System.InvalidCastException: Specified cast is not valid.
   at lambda_method(Closure , BsonDocument )
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LiteDBTest.Program.Main(String[] args)
```

![image](https://user-images.githubusercontent.com/1544021/89815399-6283f000-db4d-11ea-8591-1dda46c30499.png)
![image](https://user-images.githubusercontent.com/1544021/89817068-3e75de00-db50-11ea-945e-1c5c32052319.png)

**Additional context**
It works fine with a settable property and a parameterless constructor.

**Comment by lbnascimento** [comment]
@dropsonic This issue has been fixed in the master and its fix will be present in the next incremental release.

**Comment by dropsonic** [comment]
@lbnascimento thanks!
