### ISSUE TITLE
Query.Where / case insensitive search

### ISSUE THREAD

**Issue by yisman** [mbdavid/LiteDB#1790]
hi
i recently updated the litedb nuget package in xamarin forms
since then, this  line has stopped working. it wont compile

var fieldContains = Query.Where(column.Name, x => !x.IsNull && x.AsString.IndexOf(srbMain.Text, StringComparison.CurrentCultureIgnoreCase) > -1);

actually, it seems the Where method entirely disappeared
how can i make a case insensitive search on an arbitrary field?
or for that matter make the entire db/collection case insensitive, since I never have need for case-sensitive searches.
thanks

**Comment by bierdosenhalter** [comment]
I have the same problem too.

**Comment by lbnascimento** [comment]
@yisman The syntax has changed for LiteDB v5.0.x. The best way to run your query is probably something like this:

```C#
var col = db.GetCollection<MyClass>();
var result = col.Find(x => x.Name != null && x.Name.Contains(srbMain.Text));
```

LiteDB defines a collation for your datafile when it is created, and the default collation is `[CurrentCulture]/IgnoreCase`, so case-insensitive comparisons are the defaut behavior. You can check the `Collation` property in your `ILiteDatabase` object and, if you want to change it, you can run a rebuild:

```C#
db.Rebuild(new RebuildOptions { Collation = new Collation("en-US/IgnoreCase,IgnoreNonSpace,IgnoreSymbols") });
```

**Comment by yisman** [comment]
Make your new year an innovative one!

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-4666046?e=eab1cb8453)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=e1f771c482&e=eab1cb8453
בס"ד

לכל לקוחותיי וידידיי היקרים

[ אין לכם זמן לקרוא את ההודעה?
פנו אלינו לקבל מערכת חדשה לניהול נתונים, שתחסוך לכם שעות כל יום!! ]

בפרוס השנה החדשה הבאה עלינו לטובה,
נאחל לכם ולמשפחתכם
ברכת שנה טובה ומתוקה,
שנת בריאות, שמחה ופרנסה טובה,
שפע ברכה והצלחה.
Wishing you all a happy and healthy New Year


תוסף חדש מבית 'מחשבת'
מהיום תראה את כל פרטי אנשי הקשר בחלון ה-Gmail שלך.
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=bd2ab5d16f&e=eab1cb8453
Turbo Paced Custom Software Development
Tel: +972 (52) 764-9971 (tel:972527649971)

============================================================
** (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=399eeb5ecc&e=eab1cb8453)
** ***@***.***)
Copyright © 2021 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=eab1cb8453&c=a6138bfd9a)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=eab1cb8453&c=a6138bfd9a)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=752c5e4f79a9fa7c8f2e896ea&afl=1

**Comment by yisman** [comment]
Make your new year an innovative one!

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-4666046?e=14541b075d)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=e1f771c482&e=14541b075d
בס"ד

לכל לקוחותיי וידידיי היקרים

[ אין לכם זמן לקרוא את ההודעה?
פנו אלינו לקבל מערכת חדשה לניהול נתונים, שתחסוך לכם שעות כל יום!! ]

בפרוס השנה החדשה הבאה עלינו לטובה,
נאחל לכם ולמשפחתכם
ברכת שנה טובה ומתוקה,
שנת בריאות, שמחה ופרנסה טובה,
שפע ברכה והצלחה.
Wishing you all a happy and healthy New Year


תוסף חדש מבית 'מחשבת'
מהיום תראה את כל פרטי אנשי הקשר בחלון ה-Gmail שלך.
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=bd2ab5d16f&e=14541b075d
Turbo Paced Custom Software Development
Tel: +972 (52) 764-9971 (tel:972527649971)

============================================================
** (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=399eeb5ecc&e=14541b075d)
** ***@***.***)
Copyright © 2021 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=14541b075d&c=a6138bfd9a)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=14541b075d&c=a6138bfd9a)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=752c5e4f79a9fa7c8f2e896ea&afl=1

**Comment by yisman** [comment]
Make your new year an innovative one!

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-4666046?e=ddf73f8bae)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=e1f771c482&e=ddf73f8bae
בס"ד

לכל לקוחותיי וידידיי היקרים

[ אין לכם זמן לקרוא את ההודעה?
פנו אלינו לקבל מערכת חדשה לניהול נתונים, שתחסוך לכם שעות כל יום!! ]

בפרוס השנה החדשה הבאה עלינו לטובה,
נאחל לכם ולמשפחתכם
ברכת שנה טובה ומתוקה,
שנת בריאות, שמחה ופרנסה טובה,
שפע ברכה והצלחה.
Wishing you all a happy and healthy New Year


תוסף חדש מבית 'מחשבת'
מהיום תראה את כל פרטי אנשי הקשר בחלון ה-Gmail שלך.
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=bd2ab5d16f&e=ddf73f8bae
Turbo Paced Custom Software Development
Tel: +972 (52) 764-9971 (tel:972527649971)

============================================================
** (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=399eeb5ecc&e=ddf73f8bae)
** ***@***.***)
Copyright © 2021 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=ddf73f8bae&c=a6138bfd9a)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=ddf73f8bae&c=a6138bfd9a)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=752c5e4f79a9fa7c8f2e896ea&afl=1

**Comment by yisman** [comment]
Make your new year an innovative one!

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-5231876?e=14541b075d)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=95f7cedbf2&e=14541b075d
בס"ד

לכל לקוחותיי וידידיי היקרים

[ אין לכם זמן לקרוא את ההודעה?
פנו אלינו לקבל מערכת חדשה לניהול נתונים, שתחסוך לכם שעות כל יום!! ]

בפרוס השנה החדשה הבאה עלינו לטובה,
נאחל לכם ולמשפחתכם
ברכת שנה טובה ומתוקה,
שנת בריאות, שמחה ופרנסה טובה,
שפע ברכה והצלחה.
Wishing you all a happy and healthy New Year


מיוחד מבית "מחשבת"
אזור איש ללקוחות שלכם לראות סטטוס הזמנות, חיובים ועוד
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=239a4155f1&e=14541b075d
Turbo Paced Custom Software Development
Tel: +972 (52) 764-9971 (tel:972527649971)

============================================================
** (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=21034de83b&e=14541b075d)
** ***@***.***)
Copyright © 2022 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=14541b075d&c=1f3e2f8a3b)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=14541b075d&c=1f3e2f8a3b)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=752c5e4f79a9fa7c8f2e896ea&afl=1

**Comment by yisman** [comment]
Make your new year an innovative one!

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-5231876?e=eab1cb8453)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=95f7cedbf2&e=eab1cb8453
בס"ד

לכל לקוחותיי וידידיי היקרים

[ אין לכם זמן לקרוא את ההודעה?
פנו אלינו לקבל מערכת חדשה לניהול נתונים, שתחסוך לכם שעות כל יום!! ]

בפרוס השנה החדשה הבאה עלינו לטובה,
נאחל לכם ולמשפחתכם
ברכת שנה טובה ומתוקה,
שנת בריאות, שמחה ופרנסה טובה,
שפע ברכה והצלחה.
Wishing you all a happy and healthy New Year


מיוחד מבית "מחשבת"
אזור איש ללקוחות שלכם לראות סטטוס הזמנות, חיובים ועוד
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=239a4155f1&e=eab1cb8453
Turbo Paced Custom Software Development
Tel: +972 (52) 764-9971 (tel:972527649971)

============================================================
** (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=21034de83b&e=eab1cb8453)
** ***@***.***)
Copyright © 2022 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=eab1cb8453&c=1f3e2f8a3b)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=eab1cb8453&c=1f3e2f8a3b)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=752c5e4f79a9fa7c8f2e896ea&afl=1

**Comment by yisman** [comment]
Make your new year an innovative one!

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-5231876?e=ddf73f8bae)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=95f7cedbf2&e=ddf73f8bae
בס"ד

לכל לקוחותיי וידידיי היקרים

[ אין לכם זמן לקרוא את ההודעה?
פנו אלינו לקבל מערכת חדשה לניהול נתונים, שתחסוך לכם שעות כל יום!! ]

בפרוס השנה החדשה הבאה עלינו לטובה,
נאחל לכם ולמשפחתכם
ברכת שנה טובה ומתוקה,
שנת בריאות, שמחה ופרנסה טובה,
שפע ברכה והצלחה.
Wishing you all a happy and healthy New Year


מיוחד מבית "מחשבת"
אזור איש ללקוחות שלכם לראות סטטוס הזמנות, חיובים ועוד
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=239a4155f1&e=ddf73f8bae
Turbo Paced Custom Software Development
Tel: +972 (52) 764-9971 (tel:972527649971)

============================================================
** (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=21034de83b&e=ddf73f8bae)
** ***@***.***)
Copyright © 2022 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=ddf73f8bae&c=1f3e2f8a3b)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=ddf73f8bae&c=1f3e2f8a3b)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=752c5e4f79a9fa7c8f2e896ea&afl=1

**Comment by yisman** [comment]
Make your new year an innovative one!

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-5412508?e=ddf73f8bae)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=bcd81feef0&e=ddf73f8bae
בס"ד

לכל לקוחותינו וידידינו היקרים

[ אין לכם זמן לקרוא את ההודעה?
פנו אלינו לקבל מערכת חדשה לניהול נתונים, שתחסוך לכם שעות כל יום!! ]

בפרוס השנה החדשה הבאה עלינו לטובה,
נאחל לכם ולמשפחתכם
ברכת שנה טובה ומתוקה,
שנת בריאות, שמחה ופרנסה טובה,
שפע ברכה והצלחה.
Wishing you all a happy and healthy New Year


מיוחד מבית "מחשבת"
אזור אישי ללקוחות שלכם לראות סטטוס הזמנות, חיובים ועוד
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=dd866fa5ba&e=ddf73f8bae
Turbo Paced Custom Software Development
Tel: +972 (52) 764-9971 (tel:972527649971)

============================================================
** Website (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=e22f98ed3c&e=ddf73f8bae)
** Email ***@***.***)
Copyright © 2023 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=ddf73f8bae&c=746ecb8128)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=ddf73f8bae&c=746ecb8128)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=752c5e4f79a9fa7c8f2e896ea&afl=1

**Comment by yisman** [comment]
Make your new year an innovative one!

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-5412508?e=14541b075d)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=bcd81feef0&e=14541b075d
בס"ד

לכל לקוחותינו וידידינו היקרים

[ אין לכם זמן לקרוא את ההודעה?
פנו אלינו לקבל מערכת חדשה לניהול נתונים, שתחסוך לכם שעות כל יום!! ]

בפרוס השנה החדשה הבאה עלינו לטובה,
נאחל לכם ולמשפחתכם
ברכת שנה טובה ומתוקה,
שנת בריאות, שמחה ופרנסה טובה,
שפע ברכה והצלחה.
Wishing you all a happy and healthy New Year


מיוחד מבית "מחשבת"
אזור אישי ללקוחות שלכם לראות סטטוס הזמנות, חיובים ועוד
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=dd866fa5ba&e=14541b075d
Turbo Paced Custom Software Development
Tel: +972 (52) 764-9971 (tel:972527649971)

============================================================
** Website (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=e22f98ed3c&e=14541b075d)
** Email ***@***.***)
Copyright © 2023 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=14541b075d&c=746ecb8128)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=14541b075d&c=746ecb8128)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=752c5e4f79a9fa7c8f2e896ea&afl=1

**Comment by yisman** [comment]
Make your new year an innovative one!

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-5412508?e=eab1cb8453)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=bcd81feef0&e=eab1cb8453
בס"ד

לכל לקוחותינו וידידינו היקרים

[ אין לכם זמן לקרוא את ההודעה?
פנו אלינו לקבל מערכת חדשה לניהול נתונים, שתחסוך לכם שעות כל יום!! ]

בפרוס השנה החדשה הבאה עלינו לטובה,
נאחל לכם ולמשפחתכם
ברכת שנה טובה ומתוקה,
שנת בריאות, שמחה ופרנסה טובה,
שפע ברכה והצלחה.
Wishing you all a happy and healthy New Year


מיוחד מבית "מחשבת"
אזור אישי ללקוחות שלכם לראות סטטוס הזמנות, חיובים ועוד
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=dd866fa5ba&e=eab1cb8453
Turbo Paced Custom Software Development
Tel: +972 (52) 764-9971 (tel:972527649971)

============================================================
** Website (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=e22f98ed3c&e=eab1cb8453)
** Email ***@***.***)
Copyright © 2023 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=eab1cb8453&c=746ecb8128)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=eab1cb8453&c=746ecb8128)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=752c5e4f79a9fa7c8f2e896ea&afl=1

**Comment by yisman** [comment]
שנה טובה ומתוקתקת - פ'תרון ת'וכנה ש'מקיף ה'כל

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-5844976?e=ddf73f8bae)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=bd98d8dc80&e=ddf73f8bae

שנה חדשה זו ההזדמנות שלכם לגלות את המערכות המידע המתקדמות של מחשבת, המתאימות לכל סוגי העסקים והארגונים... גם שלכם! עם כלים עוצמתיים כמו:
* 📧 חיבור לג'ימייל ושילוב מיילים וסמסים
* 📊 ייבוא וייצוא מאקסל
* 📞 חיבור למרכזיה טלפונית
* 💼 ניהול לקוחות ולידים בצורה אוטומטית
* 🔔 דוחות והתראות חכמות בזמן אמת
* 💰 גביה באשראי והוראות קבע
* 📦 ניהול מלאי ומשלוחים
* 📅 יומן פגישות עם תזכורן חכם וגמיש

לא רק שזה מתאים בדיוק לכם, אלא גם מותאם אישית לכל משתמש! כל משתמש יכול לסדר את הממשק בדיוק לפי הצרכים שלו 🎯. מדהים, לא?

אם אתם מחפשים להתקדם ולהפוך את העסק שלכם ליעיל יותר ב-תשפ"ה, אין זמן טוב יותר להתחיל!

המערכות שלנו מתחברות ומשתלבות עם המון ספקים מובילים, וביניהם:


מכירים?

וגם חשבונית ירוקה, בנק ישראל, מערכות גביה ומשלוחים ועוד המון פלטפורמות נפוצות ושימושיות .

ובמשפט אחד?

פתרון תוכנה שמקיף הכל!

בא נצא לדרך חדשה ביחד, ותראו איך המערכות של מחשבת יעזרו לכם להצליח ולגדול בס"ד
לקבלת הדגמה אישית עכשיו! ***@***.***)

יותר טיפוס של דיבורים? התקשרו אלינו כבר עכשיו
+972-5276-49971 (tel:972527649971)

מאחלים לכם שנה של התפתחות, הצלחות חדשות ושיתופי פעולה פוריים,
צוות מחשבת

להסרה מרשימת התפוצה, לחץ כאן (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&t=b&e=ddf73f8bae&c=824fac5f79) .

============================================================
** Website (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=1e7d51142d&e=ddf73f8bae)
** Email ***@***.***)
Copyright © 2024 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=ddf73f8bae&c=824fac5f79)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&t=b&e=ddf73f8bae&c=824fac5f79)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=752c5e4f79a9fa7c8f2e896ea

**Comment by yisman** [comment]
שנה טובה ומתוקתקת - פ'תרון ת'וכנה ש'מקיף ה'כל

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-5844976?e=eab1cb8453)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=bd98d8dc80&e=eab1cb8453

שנה חדשה זו ההזדמנות שלכם לגלות את המערכות המידע המתקדמות של מחשבת, המתאימות לכל סוגי העסקים והארגונים... גם שלכם! עם כלים עוצמתיים כמו:
* 📧 חיבור לג'ימייל ושילוב מיילים וסמסים
* 📊 ייבוא וייצוא מאקסל
* 📞 חיבור למרכזיה טלפונית
* 💼 ניהול לקוחות ולידים בצורה אוטומטית
* 🔔 דוחות והתראות חכמות בזמן אמת
* 💰 גביה באשראי והוראות קבע
* 📦 ניהול מלאי ומשלוחים
* 📅 יומן פגישות עם תזכורן חכם וגמיש

לא רק שזה מתאים בדיוק לכם, אלא גם מותאם אישית לכל משתמש! כל משתמש יכול לסדר את הממשק בדיוק לפי הצרכים שלו 🎯. מדהים, לא?

אם אתם מחפשים להתקדם ולהפוך את העסק שלכם ליעיל יותר ב-תשפ"ה, אין זמן טוב יותר להתחיל!

המערכות שלנו מתחברות ומשתלבות עם המון ספקים מובילים, וביניהם:


מכירים?

וגם חשבונית ירוקה, בנק ישראל, מערכות גביה ומשלוחים ועוד המון פלטפורמות נפוצות ושימושיות .

ובמשפט אחד?

פתרון תוכנה שמקיף הכל!

בא נצא לדרך חדשה ביחד, ותראו איך המערכות של מחשבת יעזרו לכם להצליח ולגדול בס"ד
לקבלת הדגמה אישית עכשיו! ***@***.***)

יותר טיפוס של דיבורים? התקשרו אלינו כבר עכשיו
+972-5276-49971 (tel:972527649971)

מאחלים לכם שנה של התפתחות, הצלחות חדשות ושיתופי פעולה פוריים,
צוות מחשבת

להסרה מרשימת התפוצה, לחץ כאן (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&t=b&e=eab1cb8453&c=824fac5f79) .

============================================================
** Website (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=1e7d51142d&e=eab1cb8453)
** Email ***@***.***)
Copyright © 2024 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=eab1cb8453&c=824fac5f79)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&t=b&e=eab1cb8453&c=824fac5f79)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=752c5e4f79a9fa7c8f2e896ea

**Comment by yisman** [comment]
שנה טובה ומתוקתקת - פ'תרון ת'וכנה ש'מקיף ה'כל

View this email in your browser (https://mailchi.mp/machshevet/drfklqb6ix-5844976?e=14541b075d)
https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=bd98d8dc80&e=14541b075d

שנה חדשה זו ההזדמנות שלכם לגלות את המערכות המידע המתקדמות של מחשבת, המתאימות לכל סוגי העסקים והארגונים... גם שלכם! עם כלים עוצמתיים כמו:
* 📧 חיבור לג'ימייל ושילוב מיילים וסמסים
* 📊 ייבוא וייצוא מאקסל
* 📞 חיבור למרכזיה טלפונית
* 💼 ניהול לקוחות ולידים בצורה אוטומטית
* 🔔 דוחות והתראות חכמות בזמן אמת
* 💰 גביה באשראי והוראות קבע
* 📦 ניהול מלאי ומשלוחים
* 📅 יומן פגישות עם תזכורן חכם וגמיש

לא רק שזה מתאים בדיוק לכם, אלא גם מותאם אישית לכל משתמש! כל משתמש יכול לסדר את הממשק בדיוק לפי הצרכים שלו 🎯. מדהים, לא?

אם אתם מחפשים להתקדם ולהפוך את העסק שלכם ליעיל יותר ב-תשפ"ה, אין זמן טוב יותר להתחיל!

המערכות שלנו מתחברות ומשתלבות עם המון ספקים מובילים, וביניהם:


מכירים?

וגם חשבונית ירוקה, בנק ישראל, מערכות גביה ומשלוחים ועוד המון פלטפורמות נפוצות ושימושיות .

ובמשפט אחד?

פתרון תוכנה שמקיף הכל!

בא נצא לדרך חדשה ביחד, ותראו איך המערכות של מחשבת יעזרו לכם להצליח ולגדול בס"ד
לקבלת הדגמה אישית עכשיו! ***@***.***)

יותר טיפוס של דיבורים? התקשרו אלינו כבר עכשיו
+972-5276-49971 (tel:972527649971)

מאחלים לכם שנה של התפתחות, הצלחות חדשות ושיתופי פעולה פוריים,
צוות מחשבת

להסרה מרשימת התפוצה, לחץ כאן (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&t=b&e=14541b075d&c=824fac5f79) .

============================================================
** Website (https://machshevet.us3.list-manage.com/track/click?u=752c5e4f79a9fa7c8f2e896ea&id=1e7d51142d&e=14541b075d)
** Email ***@***.***)
Copyright © 2024 machshevet, All rights reserved.
 contact

Our mailing address is:
machshevet
88 Agripas Street
jerusalem 9453331
Israel
Want to change how you receive these emails?
You can ** update your preferences (https://machshevet.us3.list-manage.com/profile?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&e=14541b075d&c=824fac5f79)
or ** unsubscribe from this list (https://machshevet.us3.list-manage.com/unsubscribe?u=752c5e4f79a9fa7c8f2e896ea&id=37a3cbc8b7&t=b&e=14541b075d&c=824fac5f79)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=752c5e4f79a9fa7c8f2e896ea
