### ISSUE TITLE
Xamarin forms: System.PlatformNotSupportedException: 'Shared mode is not supported in platforms that do not implement named mutex.'

### ISSUE THREAD

**Issue by Nitharshan1993** [mbdavid/LiteDB#1791]
I get this error when I try to make the database connection as shared:

public static string DevicePath = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
public const string LiteDBName = "Object.db";
public static string DBPath = Path.Combine("Filename="+DevicePath, LiteDBName + ";connection=shared");

        public List<EventModelDB> GetEvents()
        {
            try
            {
                using (var db = new LiteDatabase(Constants.DBPath))
                {
                    var col = db.GetCollection<ModelDB>();

                    return col.FindAll().ToList();
                }
            }
            catch (Exception e)
            {
                throw e;
            }
        }

**Comment by lbnascimento** [comment]
@Nitharshan1993 The LiteDB shared mode uses a system-wide named mutex to synchronize file access between multiple processes. If the platform does not support named mutex, then you won't be able to use shared mode with it.

Anyway, you should only use shared mode if you need multi-process access to the same datafile. In all other cases, you should use direct mode.
