### ISSUE TITLE
[QUESTION] Merging result data of a GROUP BY query into a flat list

### ISSUE THREAD

**Issue by eschlot** [mbdavid/LiteDB#1792]
I already asked one question here: [https://github.com/mbdavid/LiteDB/issues/1739](https://github.com/mbdavid/LiteDB/issues/1739) and need to come back to this once again. 

The answer of Leonardo helps me a lot and I am able now to retrieve the desired data form the database, but in fact I am still struggling with the consequences of the excellent and helpful answer received.

My GUI application works on the premises that all queries return flat BSONArrays of one single type like follows:

`SELECT $ FROM picturedata;`

returns data sets like 

```
/* 1 */
{
  "_id": 1,
  "FileName": "20140314_204844.jpg",
  "FolderPath": "C:\\Users\\eckar\\Pictures\\1601\\01\\20140314_204844.jpg",
  "RootFolderPath": "C:\\Users\\eckar\\Pictures",
  "SHA": "122B84CB99FA881A1A159EF85F37AD28112552CA5CA372DEAFE6BBD77D536C56",
  "DateTime": "01.01.1601 02:00:00",
  "DateTimeObject": {"$date": "1601-01-01T01:00:00.0000000Z"},
  "Categories": 
  [
    {
      "_id": 17,
      "Pos": 16,
      "Name": "Jokes",
      "Accelerator": "<unset>"
    }
  ]
}
/* 2 */
{
  "_id": 2,
  "FileName": "image-381364-panomobile-mepm.jpg",
  "FolderPath": "C:\\Users\\eckar\\Pictures\\1601\\01\\image-381364-panomobile-mepm.jpg",
  "RootFolderPath": "C:\\Users\\eckar\\Pictures",
  "SHA": "25F42F641FEB2B1024AB6CA9990BF6AB5017013707A7E10BC734020F47A036B4",
  "DateTime": "01.01.1601 02:00:00",
  "DateTimeObject": {"$date": "1601-01-01T01:00:00.0000000Z"},
  "Categories": 
  [
    {
      "_id": 17,
      "Pos": 16,
      "Name": "Jokes",
      "Accelerator": "<unset>"
    }
  ]
}
/* 3 */
{
...

```

When I use the following query:

```
SELECT * AS items, @key , count(*) AS c into temptable FROM picturedata GROUP BY SHA HAVING count(*)>1 ;

SELECT $.items[*] FROM temptable;

```
always return objects like 

```
/* 1 */
{
  "items": 
  [
    {
      "_id": 6214,
      "FileName": "DSC_0428 - Kopie (2).JPG",
      "FolderPath": "C:\\Users\\eckar\\Pictures\\2014\\04\\DSC_0428 - Kopie (2).JPG",
      "RootFolderPath": "C:\\Users\\eckar\\Pictures",
      "SHA": "003A02B8781B45C9CB3053F63B5171BA4FA6BCE9618D61E92F9BD92B78A0EAC2",
      "DateTime": "12.04.2014 21:39:35",
      "DateTimeObject": {"$date": "2014-04-12T19:39:35.0000000Z"},
      "Longitude": 9.344133833,
      "Latitude": 48.923536639,
      "Categories": 
      [
        {
          "_id": 1,
          "Pos": 0,
          "Name": "L",
          "Accelerator": "<unset>"
        },
        {
          "_id": 13,
          "Pos": 12,
          "Name": "g",
          "Accelerator": "<unset>"
        }
      ]
    },
    {
      "_id": 6215,
      "FileName": "DSC_0428 - Kopie.JPG",
      "FolderPath": "C:\\Users\\eckar\\Pictures\\2014\\04\\DSC_0428 - Kopie.JPG",
      "RootFolderPath": "C:\\Users\\eckar\\Pictures",
      "SHA": "003A02B8781B45C9CB3053F63B5171BA4FA6BCE9618D61E92F9BD92B78A0EAC2",
      "DateTime": "12.04.2014 21:39:35",
      "DateTimeObject": {"$date": "2014-04-12T19:39:35.0000000Z"},
      "Categories": []
    },
    {
      "_id": 6216,
      "FileName": "DSC_0428.JPG",
      "FolderPath": "C:\\Users\\eckar\\Pictures\\2014\\04\\DSC_0428.JPG",
      "RootFolderPath": "C:\\Users\\eckar\\Pictures",
      "SHA": "003A02B8781B45C9CB3053F63B5171BA4FA6BCE9618D61E92F9BD92B78A0EAC2",
      "DateTime": "12.04.2014 21:39:35",
      "DateTimeObject": {"$date": "2014-04-12T19:39:35.0000000Z"},
      "Categories": []
    }
  ]
}
/* 2 */
{
  "items": 
  [
    {
      "_id": 9505,
      "FileName": "DSC_0057 (2).JPG",
      "FolderPath": "C:\\Users\\eckar\\Pictures\\2015\\10\\DSC_0057 (2).JPG",
      "RootFolderPath": "C:\\Users\\eckar\\Pictures",
      "SHA": "00591012282E6A002227CA68AE0B834BCB9ADC78344FE334D810C6939B0E6AC3",
      "DateTime": "18.10.2015 13:27:26",
      "DateTimeObject": {"$date": "2015-10-18T11:27:26.0000000Z"},
      "Longitude": 9.325696361,
      "Latitude": 48.924540833,
      "Categories": []
    },
    {
      "_id": 9506,
      "FileName": "DSC_0057 (3).JPG",
      "FolderPath": "C:\\Users\\eckar\\Pictures\\2015\\10\\DSC_0057 (3).JPG",
      "RootFolderPath": "C:\\Users\\eckar\\Pictures",
      "SHA": "00591012282E6A002227CA68AE0B834BCB9ADC78344FE334D810C6939B0E6AC3",
      "DateTime": "18.10.2015 13:27:26",
      "DateTimeObject": {"$date": "2015-10-18T11:27:26.0000000Z"},
      "Longitude": 9.325696361,
      "Latitude": 48.924540833,
      "Categories": []
    }
  ]
}
/* 3 */
{
  "items": 
...

```

The problem with this is that I find no way to merge all objects in "items" into one flat list of objects which my GUI can handle.

Is there a way to achieve the same within a query? With other words: How to concatenate all entries of the inner type into one flat list?

**Comment by lbnascimento** [comment]
@eschlot If you run the query `select *.items from temptable`, you'll get an array of arrays, where each entry is an array that represents a group in the original query. If you want to completely flatten this structure, you can run `select *.items[*] from temptable`.

**Comment by eschlot** [comment]
Hello Leonardo,

thank You very much for the answer.
Unfortunately the  request 
`select *.items[*] from temptable`

still returns the following:
```
{
  "items": 
  [
    {
      "_id": 6214,
      "FileName": "DSC_0428 - Kopie (2).JPG",
      "FolderPath": "C:\\Users\\eckar\\Pictures\\2014\\04\\DSC_0428 - Kopie (2).JPG",
      "RootFolderPath": "C:\\Users\\eckar\\Pictures",
      "SHA": "003A02B8781B45C9CB3053F63B5171BA4FA6BCE9618D61E92F9BD92B78A0EAC2",
      "DateTime": "12.04.2014 21:39:35",
      "DateTimeObject": {"$date": "2014-04-12T19:39:35.0000000Z"},
      "Longitude": 9.344133833,
      "Latitude": 48.923536639,
      "Categories": 
      [
        {
          "_id": 1,
          "Pos": 0,
          "Name": "L",
          "Accelerator": "<unset>"
        },
        {
          "_id": 13,
          "Pos": 12,
          "Name": "g",
          "Accelerator": "<unset>"
        }
      ]
    },
    {
      "_id": 6215,
      "FileName": "DSC_0428 - Kopie.JPG",
      "FolderPath": "C:\\Users\\eckar\\Pictures\\2014\\04\\DSC_0428 - Kopie.JPG",
      "RootFolderPath": "C:\\Users\\eckar\\Pictures",
      "SHA": "003A02B8781B45C9CB3053F63B5171BA4FA6BCE9618D61E92F9BD92B78A0EAC2",
      "DateTime": "12.04.2014 21:39:35",
      "DateTimeObject": {"$date": "2014-04-12T19:39:35.0000000Z"},
      "Categories": []
    },
    {
      "_id": 6216,
      "FileName": "DSC_0428.JPG",
      "FolderPath": "C:\\Users\\eckar\\Pictures\\2014\\04\\DSC_0428.JPG",
      "RootFolderPath": "C:\\Users\\eckar\\Pictures",
      "SHA": "003A02B8781B45C9CB3053F63B5171BA4FA6BCE9618D61E92F9BD92B78A0EAC2",
      "DateTime": "12.04.2014 21:39:35",
      "DateTimeObject": {"$date": "2014-04-12T19:39:35.0000000Z"},
      "Categories": []
    },
    {
      "_id": 9505,
      "FileName": "DSC_0057 (2).JPG",
      "FolderPath": "C:\\Users\\eckar\\Pictures\\2015\\10\\DSC_0057 (2).JPG",
      "RootFolderPath": "C:\\Users\\eckar\\Pictures",
      "SHA": "00591012282E6A002227CA68AE0B834BCB9ADC78344FE334D810C6939B0E6AC3",
      "DateTime": "18.10.2015 13:27:26",
      "DateTimeObject": {"$date": "2015-10-18T11:27:26.0000000Z"},
      "Longitude": 9.325696361,
      "Latitude": 48.924540833,
      "Categories": []
    },
    {
      "_id": 9506,
      "FileName": "DSC_0057 (3).JPG",
      "FolderPath": "C:\\Users\\eckar\\Pictures\\2015\\10\\DSC_0057 (3).JPG",
      "RootFolderPath": "C:\\Users\\eckar\\Pictures",
      "SHA": "00591012282E6A002227CA68AE0B834BCB9ADC78344FE334D810C6939B0E6AC3",
      "DateTime": "18.10.2015 13:27:26",
      "DateTimeObject": {"$date": "2015-10-18T11:27:26.0000000Z"},
      "Longitude": 9.325696361,
      "Latitude": 48.924540833,
      "Categories": []
    },
....
```

...and this is exactly the problem I am facing with many different queries which I tried already. I am not able to get a real flat list. It is always a list in a dictionary what I get in return.

**Comment by lbnascimento** [comment]
@eschlot This is currently not possible with the way our query pipeline is implemented, and you can see exactly why here: https://github.com/mbdavid/LiteDB/blob/8238d861d2001cfd75e8bce7b2c0b11494c311ca/LiteDB/Engine/Query/Pipeline/QueryPipe.cs#L85-L97

If the returned value is not a document, is is encapsuled inside a document before being returned.

If it is not feasible for you to do something like `db.Execute("select *.items[*] from temptable").FirstOrDefault()?["items"]`, I believe it is possible to achieve this by implementing your own `IBsonReader` (you'd also have to implement your own `ILiteDatabase`, but you could simply encapsulate an instance of `LiteDatabase` and redirect all calls to it, except for the `Execute` calls, which would return the custom `IBsonReader`.

Let me know if this is something you'd be interested in.

**Comment by eschlot** [comment]
Hello Leonardo,

thank you very much for the answer. This helps me to understand that there is no way to achieve the desired behavior out of the box. 
In my application I let the user declare a BsonExpression for collection.Find() usage by a tree structure. My plan was to add a pre-defined BsonExpression to find all duplicates in the collection of a database. But for my application the behavior of LiteDB has now two issues:

1. As You have pointed out the returned values from the SELECT method are not structured in the same way as they are for a collection.Find() method. 
2. The collection.Find() cannot be used to do a complicated select method with GROUP BY part. Moreover I need an intermediate table to be created for the final result in the format above.  And the intermediate table needs to be dropped before any execution of the two step query. 

 So to solve these two problems I see the following possibilities, now:
1. handle the search for duplicates as a very special case in my application. But probably in this approach it might be easier to use a Linq expression on the result of the collection.Find() result. 
2. expand LiteDB's interface for the collection.Find() in such a way that it get's possible to use the full properties of select. But also this would still mean a broader re-structurering of my code base. 
3. Understand more about the ILiteCollection.Query interface and it's possibilities. Maybe that would still be an opportunity together with Your proposal to simply access the FirstOrDefault().

But at the moment point 1 seems to be the most attractive one to me since this is something that comes with the least complications and can be added to any result of a prior Collection.Find() result. 

Nevertheless: Thank you very much, again.
