### ISSUE TITLE
[QUESTION] That are the sort order of document indexes

### ISSUE THREAD

**Issue by katdti** [mbdavid/LiteDB#1797]
Quoting from https://www.litedb.org/docs/indexes/: 

> When comparing documents, the values in the key-value pairs are compared in the order that they appear until a tie is broken.

- Question: 
   That are the order of the key-value pairs? As Listed in code or in database or sorted by key name?

>You can use EnsureIndex("Address") to create an index to all Address embedded document
- Question:
   How can the index order of the document value be controled?

**Comment by lbnascimento** [comment]
> That are the order of the key-value pairs? As Listed in code or in database or sorted by key name?

The `_id` field (if it exists) will always be compared first. For the other fields, if the document was mapped using our `BsonMapper`, they will be compared by the order in which they appear in the code. If you have a custom serializer, however, the fields will be compared by the order in which they were added to the `BsonDocument`.

> How can the index order of the document value be controled?
I don't think I understood this question. Indexes are only for internal use, you can't control how they are ordered. Sub-documents respect the order that I described in the question above.

**Comment by katdti** [comment]
Ok - I understand: One have to manually setup a BsonMapper to control the compare order
