### ISSUE TITLE
Shrink

### ISSUE THREAD

**Issue by lppanariello** [mbdavid/LiteDB#18]
It's not really an issue but I think you should implement a shrink/compact method because after delete operation database file is always in the same file size.
Regards

**Comment by mbdavid** [comment]
Hi @lppanariello, thanks for your feedback. After delete documents (for files) this empty space will be re-used in insert operation. Empty pages are manage by `PageService`. But I agree with you, all databases has a shirink operation and LiteDB will have too.

I'm creating an issue in Github for features/ideias to LiteDB future versions to anyone can +1.
