### ISSUE TITLE
[SUGGESTION] Support for SAFE stack (netcore 3.1)

### ISSUE THREAD

**Issue by davedawkins** [mbdavid/LiteDB#1800]
I was planning on using LiteDB with the F# SAFE stack, but the use of Saturn in that stack has a netcoreapp3.1 dependency that doesn't allow LiteDB to be incorporated. (At least, I don't know yet know how to resolve it).

I think I can still do this if I drop Saturn (netcoreapp3.1) from the template, but I'd like to know if there any plans to support netcore3.1 (or if this would even make sense)

Thank you!

**Comment by lbnascimento** [comment]
@davedawkins LiteDB does not directly target .NET Core, it targets .NET Standard 2.0, which is implemented by .NET Core 2.0 and greater. I'm not sure if there's some sort of incompatibility or additional configuration needed for F# or the SAFE stack.

**Comment by davedawkins** [comment]
Yes, I think LiteDB has its targeting set up just fine. It's taken me a while to make sense of all the different target options between the various components. Thanks for the response.
