### ISSUE TITLE
[QUESTION] Setting Subdocument fields in a Query

### ISSUE THREAD

**Issue by NongBenz** [mbdavid/LiteDB#1802]
I want to change values in a subdocument field from null to empty strings and here's my Query in LiteDB Studio.

```
UPDATE
users
SET
Character.AppTransactions = ""
WHERE
Character.AppTransactions = null
```

But I get this error
```
Unexpected token `.` in position 29.

UPDATE  users  SET  Character.AppTransaction
-----------------------------^
```

Seems we are unable to use valid JSON paths to update subdocuments? Is there a Query that would let me do this operation?

Thanks
Benz

**Comment by lbnascimento** [comment]
@NongBenz The only way to update subdocuments in an update query is ti recreate the structure of the original document. Something like this:

```SQL
UPDATE users SET
{
	_id: $._id,
	Name: $.Name,
	...,
	Characters:
	{
		AppTransactions: '',
		SubField2: $.Characters.SubField2,
		...
	}
}
WHERE $.Characters.AppTransactions = null
```

**Comment by NongBenz** [comment]
Thanks for the reply - Think it'll be easier to edit and upsert back to the DB using managed code instead of Queries.

Cheers
Benz
