### ISSUE TITLE
BsonMapper.TrimWhitespace is not available

### ISSUE THREAD

**Issue by adoconnection** [mbdavid/LiteDB#181]
One of my document entitys stores value array as joined string.
value1 \n value2 \n value3

if value3 is absent, string turns into value1 \n value2 \n and
last \n got cleaned on insert/update due to BsonMapper.TrimWhitespace = true

So I had to compile my own version with BsonMapper.TrimWhitespace = false by default
due its unavailability as a public property #

**Comment by mbdavid** [comment]
Hi @adoconnection, I made some changes in current master branch. Now BsonMapper has a global instance that can be changed before using LiteDatabase.

`BsonMapper.Global.TrimWhitespace = false`;
