### ISSUE TITLE
What is the position of a page when it is on disk?

### ISSUE THREAD

**Issue by weishuo2** [mbdavid/LiteDB#1812]
I noticed that in BasepPage, page is uniquely identified by pageID. When I close the created database, the data will be written to the SSD as files. So when I open it next time, how is the data loaded into a page again? In other words, after these pages are placed on the SSD, what is used to identify their location (to read it from SSD to memory next time)?
Could you tell me the answer or relevant code file names?

**Comment by lbnascimento** [comment]
@weishuo2 Pages are 8192-byte chunks in the data file, so they can be identified by their position. Page 0 will be at bytes 0-8191, page 1 at 8192-16383 and so on.

Unless your data file is encrypted, then bytes 0-8191 are for internal usage and the actual (encrypted) datafile starts at byte 8192.
