### ISSUE TITLE
[QUESTION] Updating Sub document

### ISSUE THREAD

**Issue by Avatarchik** [mbdavid/LiteDB#1814]
Is there a way to update or add a sub object without getting the whole array?
Or do you need to put everything in separate collections? And make simple objects? I may have thousands of objects in the array, and if I add or remove one of them, I don't want to get all

**Comment by lbnascimento** [comment]
@Avatarchik If you have large arrays and intend to frequently include and remove objects from it, it is recommended to store these objects in their own collection, keeping only a reference in the original object.
