### ISSUE TITLE
Updating related objects

### ISSUE THREAD

**Issue by MarianoLaiseca** [mbdavid/LiteDB#1816]
Hi Everyone, 
This is the first time that I write a question in github so sorry if I'm doing something wrong!

This is my question

I have 2 entities

**UnidadDeMedida**
```
namespace LibroDeRecetas.Models
{
    public enum TipoUnidadDeMedida
    {
        Peso,
        Volumen,
        Unidad,
        Otro
    }

    public class UnidadDeMedida
    {
        public int UnidadDeMedidaID { get; set; }
        public string Descripcion { get; set; }
        public TipoUnidadDeMedida TipoUM { get; set; }

        public UnidadDeMedida() { }

        public UnidadDeMedida(string descripcion, TipoUnidadDeMedida tum)
        {
            this.Descripcion = descripcion;
            this.TipoUM = tum;
        }
    }
}
```
 
**IngredienteSimple**
```
using System;

namespace LibroDeRecetas.Models
{
    public class IngredienteSimple
    {
        public string Descripcion { get; set; }
        public UnidadDeMedida UdM { get; set; }

        //Constructor
        public Ingrediente() { }

        public Ingrediente (string descripcion, UnidadDeMedida udM)
        {
            this.Descripcion = descripcion;
            this.UdM = udM;
        }
    }
}
```

If I update, for example, the Property Descripcion in a UnidadDeMedida that is related to an IngredienteSimple, the UnidadDeMedida document is updated but not in the related IngredienteSimple.

Example

```
        private void CmdPrueba3_Click(object sender, RoutedEventArgs e)
        {
            using (var db = new LiteDatabase(@"C:\Temp\MyData.db"))
            {
                //Unidades de Medida
                UnidadDeMedida udm1 = new UnidadDeMedida("udm1", TipoUnidadDeMedida.Peso);

                // Get a collection (or create, if doesn't exist)
                var unidadesDeMedida = db.GetCollection<UnidadDeMedida>("UnidadDeMedida");

                unidadesDeMedida.Insert(udm1);

                //Ingredientes Simples
                IngredienteSimple ing1 = new IngredienteSimple("Ingrediente", udm1);

                var ingredientesSimples = db.GetCollection<IngredienteSimple>("IngredienteSimple");
                ingredientesSimples.Insert(ing1);


                UnidadDeMedida um = unidadesDeMedida.FindById(1);
                um.Descripcion="udm1111";
                unidadesDeMedida.Update(um);
            }
        } 
```

In the example the UnidadDeMedida collection is updated in the file to udm1111 but in the IngredienteSimple I still see udm1.

How would be the correct way to
 to update all IngredienteSimple instances that are using the UnidadDeMedida modified.

Attached you have 2 screenshot from LiteDB Studio with the example after update

![liteDB1](https://user-images.githubusercontent.com/27965829/93028919-925f6100-f5ed-11ea-846c-1b7b3cf21fa7.PNG)
![liteDB2](https://user-images.githubusercontent.com/27965829/93028920-93908e00-f5ed-11ea-815f-497ed1b083c5.PNG)

Thanks.

**Comment by lbnascimento** [comment]
@MarianoLaiseca By default, LiteDB stores sub-objects as embedded documents. If you want to store them in a separate collection, you should use `BsonCtorAttribute`:

```C#
public class IngredienteSimple
{
	...

    [BsonRef("UnidadDeMedida")]
    public UnidadDeMedida UdM { get; set; }
	
	...
}
```

And when opening the collection for `IngredienteSimple`:

```C#
var ingredientesSimples = db.GetCollection<IngredienteSimple>("IngredienteSimple").Include(x => x.UdM);
```

Please note that the `Include` call is only used to resolve the reference on queries. You still have to do insertions and updates manually to the `UnidadDeMedida` collection.

**Comment by MarianoLaiseca** [comment]
@lbnascimento 

Thanks so much for your help! Your answer was really helpful


Regards
