### ISSUE TITLE
File in use issues in V5

### ISSUE THREAD

**Issue by chucksullivancvs** [mbdavid/LiteDB#1817]
I am using LiteDB in a simple desktop app that uses 2 shared db files on an EMC Isilon (CIFS and NFS) file share.

I upgraded to V5 recently, largely to use LiteDB Studio and for a couple of features like DeleteMany.

Now my users are continually getting transient "file in use" errors trying the read or update the files. Error msgs include.

"The process cannot access the file .. because it is being used by another process"
"Access to the path is denied"

All LiteDB access is done inside Using blocks. I do a db.Commit() after each transaction.

I  open/connected to  the file in LiteDB Studio and queried it using Direct mode. When I disconnect I got the "Access to the path is denied" error. Next time I tried in Shared mode and got the access denied just trying to connect to file.

The locked condition seems to persist for an indeterminant period of time even when no one accesses the file.

Has anyone seen this behavior and/or have a way to work around it?

I am having a hard time determining if is enviornmental or something I am doing wrong.

I never saw this in the same environment in 18 months of using LiteDB V4.

**Comment by chucksullivancvs** [comment]
Also, I notice that a file with the same name as the data.db file with "-log.db" appended to it. If I rename or delete the -log file the file lock seems to clear. I understand this to be the temp transaction file and should be cleaned up automatically which apparently is not happening.

Would it be "safe" to check for and delete this file as a mitigation? Or might that cause more problems than it solves?

**Comment by lbnascimento** [comment]
@chucksullivancvs LiteDB v5.0.x does not support network shares. This is because the Shared mode uses an OS-wide mutex to synchronize file access, which obviously doesn't work over the network. v4 used file locks, which are implemented by network file systems, but it has problems of its own.

I suggest you stay at v4 until we release v5.1, which will use lock files to synchronize file access and, therefore, should work with network shares.

**Comment by chucksullivancvs** [comment]
@lbnascimento - thx. i gone ahead and downgraded to 4.1.4. was pretty easy. just had to get rid ofthe Commit() and rewrite the DeleteMany. So far so good on that. new issue though I will post seperately
