### ISSUE TITLE
Win10 StorageFolder compatibility

### ISSUE THREAD

**Issue by WattsC-90** [mbdavid/LiteDB#182]
Hi,
Very interested in this database DLL, do the core file access layers utilise the Storage Folder access code in the new Win10 system? I am trying to find a database tech that can use a database on an external device. 
Sorry if this question doesn't make sense, if you need more information, please ask, very impressed with the database.

**Comment by mbdavid** [comment]
Hi @WattsC-90, take a look in this pull request: https://github.com/mbdavid/LiteDB/pull/159

I don't know if uses StorageFolder but it's a version for portable. Is in my list to merge with trunk

**Comment by WattsC-90** [comment]
Hi @mbdavid, looking further at litedb, the stream constructor is perfect, just need that nuget now!;) thanks for getting back to me! I'll keep my eye on that pull request
