### ISSUE TITLE
[QUESTION] Querying in children documents

### ISSUE THREAD

**Issue by mipsweb** [mbdavid/LiteDB#1821]
Hi,

I have a question about querying in children documents.

The structure of collection looks like:

```
/* 1 */
{
  "_id": {"$oid": "5f61fb63d2c59b07d22cad08"},
  "SetID": 8,
  "ParamValueRealList": 
  [
    {
      "ParamValue": 100,
      "ParamID": 15002
    }
  ]
 }
/* 2 */ 
 {
  "_id": {"$oid": "5f61fb63d2c59b07d22cad09"},
  "SetID": 9,
  "ParamValueRealList": 
  [
    {
      "ParamValue": 120,
      "ParamID": 15002
    }
  ]
 }
```

I want to get records where ParamID = 15002 and ParamValue > 100.
I have tried with:
`(MAP($.ParamValueRealList[*]=>@.ParamID) ANY = 15002 AND MAP($.ParamValueRealList[*]=>@.ParamValue) ANY > 100.0);`

It almost works but it ignores that ParamValue must be greater then 100.0 and returns both records.

Do you have any ideas what I’m missing in the query statement?

Thanks in advance.

**Comment by lbnascimento** [comment]
@mipsweb I just tested your expression (`SELECT $ FROM collection WHERE MAP($.ParamValueRealList[*]=>@.ParamID) ANY = 15002 AND MAP($.ParamValueRealList[*]=>@.ParamValue) ANY > 100`) and it works exactly as intended. What version of LiteDB are you using?

**Comment by mipsweb** [comment]
@lbnascimento Right now I'm trying in LiteDB Studio 1.0.2.0.

When I can the query to ParamID = 2 and ParamValue > 100. It is returning ParamValue 0.0. I have have a screenshot from LiteDB Studio.

![image](https://user-images.githubusercontent.com/12269574/93484270-022d5e80-f902-11ea-8d5c-06561c55af81.png)

**Comment by mipsweb** [comment]
With the filter I'm getting what I need. 

Thanks for your help @lbnascimento

**Comment by tomthebearded** [comment]
Can i say that this query `SELECT $ FROM collection WHERE MAP($.ParamValueRealList[*]=>@.ParamID) ANY = 15002 AND MAP($.ParamValueRealList[*]=>@.ParamValue) ANY > 100` as it is written seems to me counterintuitive?

Reading the query i expect to get all the ParamValueRealList that have id 15002 AND all the ones that have value > 100, not a combination of the two values, meaning that i could get duplicates.

The same applies for similar queries in c# that aim to do the same thing
`Query.And(Query.Any().EQ("p[*].t", type), Query.Any().EQ("p[*].c", code))`
