### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by themronion** [mbdavid/LiteDB#1823]
**Version**
LiteDB - latest, Xamarin.Forms - latest. Tested on Android device.

**Describe the bug**
So here is the story. I've been using LiteDB 4.4 a long time in my project and decided to upgrade to the latest LiteDB. The structure of my project is like this: https://xamarinmonkeys.blogspot.com/2019/02/xamarinforms-working-with-litedb-crud.html. I've upgraded my packages using nuget manager as i usually do with other plugins. I deleted and reinstalled my app before moving somewhere else. I launched my app and on the first call of one of one of my methods:
```csharp
 public List<User> GetUsers()
        {
            var users = new List<User>(usersCollection.FindAll());
            return users;
        }
```
i got this error: System.ObjectDisposedException: 'Cannot access a disposed object.'  Then i switched back to 4.4 and it all worked normally again. I've read somewhere that now i need to specify the filename in some other way but i haven't managed to do that - got another error. Or i need to wrap all my calls to the database in a using statement in version 5? Can someone guide me what is wrong or it is a bug in Xamarin?

**Code to Reproduce**
No code.

**Expected behavior**
Everything works normally after updating the packages

**Screenshots/Stacktrace**

**Comment by lbnascimento** [comment]
@themronion Could you provide a stacktrace? Also, it would be helpful if you could provide some samples on how you're opening and using your data file.

**Comment by themronion** [comment]
You can just follow all the steps as in the link i mentioned - https://xamarinmonkeys.blogspot.com/2019/02/xamarinforms-working-with-litedb-crud.html. The only change is that instead of LiteCollection we use ILiteCollection in v5.

**Comment by lbnascimento** [comment]
@themronion In the link you mentioned, the `LiteDBHelper` ctor creates the `LiteDatabase` instance in a using block, while storing the `LiteCollection<Person>` instance. The `LiteDatabase` instance is disposed after the `using` block finishes executing, and your instance of `LiteCollection<Person>` now refers to a disposed database.

If you want to use it in this way, you should not use `using`. Instead, you should use it normally and, if possible, manually calling `db.Dispose()` when you're done with it. One way of achieving this is to make `LiteDBHelper` implement `IDisposable` and making a `void Dispose()` method that calls `db.Dispose()`, then you'll be able to instantiate `LiteDBHelper` in an `using` block.

**Comment by themronion** [comment]
Oh, i see now) Okay, i will try without using and see where it gets me

**Comment by themronion** [comment]
Works like a charm. I went with the "no using" option. I guess it is not the best choice, but its enough for me. Thanks! Closing this one
