### ISSUE TITLE
Still can't execute Find/Count with dynamically built predicates,

### ISSUE THREAD

**Issue by toumir** [mbdavid/LiteDB#1824]
Still can't execute Find/Count with dynamically built predicates,
LiteDB version **master branch** with the fixed bug above,

Let say I have two methods that return a predicates: 
- The first returns `var predicate1 = t=>true;`
- and the second returns the same thing `var predicate2 = t=>true`

After combining the two results : `var result = predicate1.And(predicate2);` and call the find method 
`col.Find(result);`
I get this error:
`Expression '@p1' are not supported as predicate expression.`

Can someone help

_Originally posted by @toumir in https://github.com/mbdavid/LiteDB/issues/1813#issuecomment-695783562_

**Comment by lbnascimento** [comment]
@toumir This issue has been fixed in the master and its fix will be present in the next incremental release.

**Comment by toumir** [comment]
I wonder if the order is matter  when querying the database ?
The **results** of the following two queries are **different**, can someone explain that to me,

LiteDB version:  **master branch**

```
void Main()
{
	var cs = new ConnectionString
	{
		Filename = @"c:\mydb.db",
		Password = @"MyP@55w0rd"
	};

	using (var db = new LiteDatabase(cs))
	{
		var col = db.GetCollection<Product>("Prods");
		col.DeleteAll();
		
		#region
		col.Insert(new Product { Id = 4, Name = "Vantage" });
		col.Insert(new Product { Id = 5, Name = "Corvette" });
		col.Insert(new Product { Id = 7, Name = "Caprice" });
		col.Insert(new Product { Id = 6, Name = "3000GT" });
		#endregion
		
		col.EnsureIndex(c => c.Name);
		
		Expression<Func<Product, bool>> p1 = p=>false; 
		Expression<Func<Product, bool>> p2 = p=>p.Name.Contains("a");
		
		//1 query
		col
		.Query()
		.Where(p2.Or(p1))
		.Count();//<== cout == 2
		
		//2 query
		col
		.Query()
		.Where(p1.Or(p2))
		.Count();//<== cout == 0
	}
}
// Define other methods, classes and namespaces here
public class Product
{
	public int Id{get;set;}
	public string Name{get;set;}
}

```

Thank you in advance
