### ISSUE TITLE
About running the test.

### ISSUE THREAD

**Issue by weishuo2** [mbdavid/LiteDB#1828]
I want to test some examples in LiteDB/LiteDB.Tests/Engine to  understand part of the underlying calls of litedb.
So how to generate an exe file that uses the examples in LiteDB/LiteDB.Tests/Engine to debug step by step to view the call,instead of a dll file？
Thanks.

**Comment by toumir** [comment]
@weishuo2  clone the LiteDB project to you computer, add it to your project and reference it, that all, you can now debug the LiteDB step by step
