### ISSUE TITLE
GetCollection now returns Interface ILiteCollection (of T)) instead of  Class LiteCollection(of T). Is this intentional?

### ISSUE THREAD

**Issue by sojatay** [mbdavid/LiteDB#1832]
**Version**
 5.0.9.0

**Describe the bug**
GetCollection is now returning Interface ILiteCollection (of T)) instead of LiteCollection(of T)

**Code to Reproduce**
I'm using VB .NET - Option Strict "On"
All previous code I used (for years) returns LiteCollection (prior to V5). I now have to do an explicit cast on each line of code that uses. This has broken all previous code

**Expected behavior**
return LiteCollection(of T) CLASS - NOT the Interface

**Screenshots/Stacktrace**
N/A

**Additional context**

**Comment by lbnascimento** [comment]
@sojatay This was done to allow for a `LiteCollection` to be mocked, which was a feature that many users require. Also, it opens up the possibility of alternative implementations in the future.

**Comment by sojatay** [comment]
Thanks Leonardo. I don't pretend to be anything like as expert as you (in fact, I'm a rank amateur), nor what your thinking has been on making this change. But I now have to ask 2 additional questions:

I'm not 100% sure what you mean by "mocked", but could not the same effect have been achieved simply by making a LiteCollection(of T) Inheritable - which I assumed they are anyway? I just find it weird to create data "variables" that aren't really variables, but Interfaces instead. I don't believe (i.e. _never understood_) that's what Interfaces are intended for in .Net for; they are in there to enforce a structure or contract to ensure specific functionality for classes that implement that functionality, and not to be used as a pseudo "class" in their own right........ I guess you have your reasons; I just don't understand them fully.

C# is pretty lax with its casts since most are implicit anyway. However, in VB.Net which distinguishes Option Strict (requiring an exact cast) vs Strict Off (which leaves the compiler to decide) that can be different. I write all my code in VB.Net with Option Strict set to On. There must be some overhead involved with doing a conversion explicit cast from ILiteCollection(of T) to Collection(of T) I would have thought?

The Wiki / Documentation makes no reference at all to GetCollection returning and ILiteCollection(of T). It all refers to a LiteCollection(of T), so that needs to be updated if this is now the way things will be in the future.

**Comment by sojatay** [comment]
Thank you. I still don't fully understand - but I can deal with it! I'll close this for you now as the behavior is obviously intentional.
