### ISSUE TITLE
Invalid index name ... MaxLength = 32

### ISSUE THREAD

**Issue by GW-FUB** [mbdavid/LiteDB#1833]
**Version**
v5.0.9

**Describe the bug**
There seems to be a new (in comparison to v4) restriction for index name lengths to 32. But why so few?

**Code to Reproduce**
Create a new ILiteCollection and use a property with long name as index.

**Expected behavior**
Accepts long property name as index.

**Screenshots/Stacktrace**
```
LiteDB.LiteException: Invalid index name 'IdSchlagErntejahrBearbeitungseinheit' on collection 'BearbeitungseinheitKulturDtos': MaxLength = 32
  at LiteDB.Engine.LiteEngine.EnsureIndex (System.String collection, System.String name, LiteDB.BsonExpression expression, System.Boolean unique) [0x000c1] in <f444c2857b9a479a901d740a1e5a3662>:0 
  at LiteDB.Engine.LiteEngine.RebuildContent (LiteDB.Engine.IFileReader reader) [0x0005d] in <f444c2857b9a479a901d740a1e5a3662>:0
```

**Comment by GW-FUB** [comment]
@lbnascimento  Is there a way to update my data file? If I upgrade the db I get an error at conversion (MaxLength = 32). If I don't upgrade it I get an error "Not a valid LiteDB database format"

**Comment by lbnascimento** [comment]
@GW-FUB I have pushed a fix for this issue to the master.

**Comment by GW-FUB** [comment]
Wow, that was a really fast fix. Thanks a lot, it worked 🙌
