### ISSUE TITLE
I think LiteDB should join the .Net Foundation, what do you think?

### ISSUE THREAD

**Issue by maikebing** [mbdavid/LiteDB#1835]
@mbdavid Have you considered joining the .Net Foundation?

**Comment by mbdavid** [comment]
Hi @maikebing, I totaly agree. I will try to submit LiteDB to .NET Foundation.... will be great to be part of this. 

Last year I tried to be MVP but LiteDB project/community was not enougth for MVP 🤕

**Comment by maikebing** [comment]
I think LiteDB is a very good project. I hope it can join as soon as possible.
