### ISSUE TITLE
[QUESTION] How do you DeleteMany efficiently

### ISSUE THREAD

**Issue by trockefeller-pathway** [mbdavid/LiteDB#1842]
I've looked through the documentation and there is a lot of information about querying and indexes to query things efficiently, but I don't see a lot of information about deleting things efficiently.

I'm trying to DeleteMany from a LiteDb database, but even relatively small deletes of 3000 items takes 10-20 seconds. Right now I am just experimenting with smaller data sets, but I plan to scale things up to much larger data sets, but I'm concerned that if the performance scales as well, then some of my deletion operations may take 30 minutes or more.

I'm trying to make a generic database implementation using LiteDB, and below is the code that I'm using for deleting from the database

```csharp
public void Delete<T>(IEnumerable<T> items)
{
    //Gets the collection name based on type. Will throw an exception if we don't support the type used.
    var collectionName = getCollectionNameAndThrowIfNotSupported<T>();
    //Gets the connection string. We are only specifying Filename, ReadOnly, and the Connection is shared
    var connectionString = getConnectionString(read_only: false);
    using (var db = new LiteDatabase(connectionString))
    {
        var collectionExists = db.CollectionExists(collectionName);
        if (!collectionExists)
            return; //no collection exists, so there is nothing to delete

        //converting items to a hash set to help find matches more quickly
        var hashedItems = items.ToHashSet();

        var collection = db.GetCollection<T>(collectionName);
        //This is the line that I have the most questions about. Is there a better way of writing this line to be more efficient?
        collection.DeleteMany(x => hashedItems.Contains(x));
    }
}
``` 

I thought that `Contains` would check if the items are equal, and for my objects that are being stored in LiteDb I am overriding `Equals` and `GetHashCode` and for two items to be equal I am only checking if the `ObjectId`s are equal.

From the documentation it would appear that if you have an `ObjectId Id` that this will automatically get indexed, but am I missing something in my `DeleteMany` predicate that would help take advantage of indexes? Is there something that can be done to make this process faster?

**Comment by trockefeller-pathway** [comment]
@lbnascimento in my LiteDb objects I have a `public ObjectId Id { get; }` property. I don't explicitly have a private _id field. Do I need to explicitly create this field, or does it automatically get created because of my public Id property?

**Comment by trockefeller-pathway** [comment]
@lbnascimento I was able to test the code you suggested, and it did work to delete the items I was needing to, and it was at least 100x faster than how I was doing it previously. Thank you.

**Comment by lbnascimento** [comment]
@trockefeller-pathway The id property in your object always becomes "_id" in the mapped `BsonDocument`, which is why I used it after the `BsonMapper.Serialize<T>(T obj)` call. I did this because your method is generic, so you can't simply do something like `collection.Delete(item.Id)`.

There are other ways to solve your problem, of course. You could get the Id field by reflection, but that's exactly what `BsonMapper` does. You could also make all of your data classes implement an interface that has a public property Id, which would allow you to use `collection.Delete(item.Id)`, but I think it would be over-engineering and it would only work if you own all of your data classes.
