### ISSUE TITLE
Storing objects of anonymous type

### ISSUE THREAD

**Issue by AniaDomachowska** [mbdavid/LiteDB#185]
Hi,

Is there a way to persist directly anonymous objects and retrieve them back as anonymous objects?

I tried to store anonymous objects, the result was plain object without property information returned.

Maybe it's possible to feed-in json strings directly, so that anonymous objects could be converted to json before adding to database and then restored back?

Regards,
AD

**Comment by inosik** [comment]
If I understand you correctly, this is what you want:

``` csharp
using (var db = new LiteDatabase("test.db"))
{
  var newStuff = new BsonDocument().Set("id", 42).Set("foo", "bar");
  // No generic type here, the return value is a LiteCollection<BsonDocument>
  var stuff = db.GetCollection("blobs");
  stuff.Insert(newStuff);
}
```

You can also build a JSON string and then parse it to a `BsonDocument` with the `JsonSerializer.Deserialize` method.

**Comment by AniaDomachowska** [comment]
I more meant storing .Net anonymous objects in form of:

new {Name="parent", Child = new {Name="child"}}
(notice object hierarchy there)

How to deserialize BsonDocument back to anonymous type? (By keeping the object hierarchy?)

Cheers,

**Comment by inosik** [comment]
I don't think that's possible, because LiteDB [doesn't support](https://github.com/mbdavid/LiteDB/wiki/Object-Mapping#mapper-conventions) deserialization of classes, which don't have a parameterless constructor. Anonymous objects in C# still have a proper (compiler generated) type, and that type always has only one constructor, which takes all the property values as parameters.

**Comment by mbdavid** [comment]
Hi @AniaDomachowska, @inosik are right, there is no suppor for anonymous type. If you have an scheme less data structure, use BsonDocument.

To implement this are very complex. I have plan in future to support 3th party serializers, like Json.NET
