### ISSUE TITLE
[QUESTION] How to use Functions and Expressions in Query In Collection Level, and for global level

### ISSUE THREAD

**Issue by AlBannaTechno** [mbdavid/LiteDB#1850]
**Hi**, How can i use

[Functions ](https://www.litedb.org/api/functions/) and [Expressions ](https://www.litedb.org/docs/expressions/) in search/filter in collection level

For Example, take this example from the [expressions ](https://www.litedb.org/docs/expressions/) page

`SELECT { upper_titles: ARRAY(UPPER($.Books[*].Title)) } WHERE $.Name LIKE "John%"`

Where Can I execute this?

### The Second Question,

How Can I Execute Expression In a Global Scope of the document

Suppose this structure

```C#
public class Contract
{
    [BsonId]
    public ObjectId Id { get; set; }
    public string Title { get; set; }
    public decimal Money { get; set; }
    public List<Fund> Funds { get; set; }

    public Contract()
    {
        Funds = new List<Fund>();
    }
}
```

```C#
public class Fund
{
    public decimal Value { get; set; }
    public DateTime DateTime { get; set; }
}
```

i need to get the `SUM` of all `Funds` For All `Contracts` With `Money ` > **500**

**Comment by AlBannaTechno** [comment]
Note: I Used This

```C#

var result = new List<BsonValue>();

using (var bsonReader = db.Execute("SELECT {title:$.Title} FROM Contracts WHERE $.Money > 1000 AND "))
{

    while (bsonReader.Read())
    {
        result.Add(bsonReader.Current);
    }
}
```

But still can not figure how this line `SELECT { upper_titles: ARRAY(UPPER($.Books[*].Title)) } WHERE $.Name LIKE "John%"`

Should executed 

Since, reading this line, we can figure that collection is pre selected, but where ? I do not know.

Also, For Info,

```C#
var firstMatchResult = contracts.Query().Where("$.Money > 300").Select("{val:SUM($.Funds[*].Value), title:$.Title}").ExecuteReader().Current;

```

**Comment by lbnascimento** [comment]
@AlBannaTechno The expression you mentioned in your first question is incorrect, it definitely should have a `FROM` clause. I'll fix it in the documentation. Sorry about that.

A tip about using `db.Execute(...)`: the easiest way to use it is to call `.ToEnumerable()` or `ToList()` after it.

> i need to get the SUM of all Funds For All Contracts With Money > 500

Something like this should work:
```SQL
select SUM(*.Funds.Value[*]) from Contracts where $.Money > 500;
```

You could also use our Linq-to-BsonExpression automatic conversion:

```C#
var contracts = db.GetCollection<Contract>();
var result = contracts.Find(x => x.Money > 500).Sum(x => x.Funds.Sum(x => x.Value));
```

**Comment by AlBannaTechno** [comment]
@lbnascimento thankyou.
