### ISSUE TITLE
[BUG] Deserializing TimeSpan (TimeSpan?) is broken in version 5.0.9 (the same code works in version 5.0.8

### ISSUE THREAD

**Issue by Kermel** [mbdavid/LiteDB#1858]
**Version**
5.0.9

**Describe the bug**
After updating nuget package to version 5.0.9, deserializing of TimeSpan (TimeSpan? nullable) is broken:
System.InvalidCastException : Unable to cast object of type 'System.Int64' to type 'System.Nullable`1[System.TimeSpan]'.

Object containing the TimeSpan? property is serialized and stored in the database. Viewing the record in the collection shows the following value: 
{"StringProp":"Some_Test_String","IntProp":124,"TimeSpanProp":{"$numberLong":"1800000000"}}

(The original class looks as follows: 
public class TestPersistClass
        {
            public string StringProp { get; set; }
            public int IntProp { get; set; }
            public TimeSpan? TimeSpanProp { get; set; }
        }
)

This numberLong value then fails when attempting to read the value back from the database.

Note: Running the same test with version 5.0.8 works correctly, the serialized JSON value is persisted exactly the same

**Comment by botne** [comment]
@Kermel ,
I ran into this issue in 5.0.9 as well, but seems like it is gone in the current master branch.
I guess we can join @pietsoftwaretogo in looking forward to the next release ( #1810 )

**Comment by Kermel** [comment]
The issue is fixed in version 5.0.10.
Closing
