### ISSUE TITLE
Logging message for update document missing _id value

### ISSUE THREAD

**Issue by Abdul-Rahman-Ahmad** [mbdavid/LiteDB#186]
Hi,
Thanks for greate work.

I think the mistake in this line:
`                    _log.Write(Logger.COMMAND, "update document on '{0}' :: _id = ", colName, id);`
There no second argument placeholder {1} after _id =
Should be
`                    _log.Write(Logger.COMMAND, "update document on '{0}' :: _id = {1}", colName, id);`

Example:
06:36:30.7073 [COMMAND] create new collection 'Person'
06:36:30.7265 [COMMAND] insert document on 'Person' :: _id = 1
06:36:30.7495 [COMMAND] update document on 'Person' :: _id = 
06:36:30.7725 [COMMAND] delete document on 'Person' :: _id = 1
06:36:30.7815 [COMMAND] insert document on 'Person' :: _id = 1
06:36:30.7835 [COMMAND] insert document on 'Person' :: _id = 2
06:36:30.7845 [COMMAND] insert document on 'Person' :: _id = 3
06:36:30.7856 [COMMAND] insert document on 'Person' :: _id = 4
06:36:30.7907 [COMMAND] update document on 'Person' :: _id = 
06:36:30.7917 [COMMAND] update document on 'Person' :: _id = 
06:36:30.7917 [COMMAND] update document on 'Person' :: _id = 
06:36:30.7927 [COMMAND] update document on 'Person' :: _id = 

Best Regards
Abdul-Rahman Ahmed

**Comment by mbdavid** [comment]
Thanks! I'm fixing this in master branch
