### ISSUE TITLE
Is there a limit for total amount of collections?

### ISSUE THREAD

**Issue by andtii** [mbdavid/LiteDB#1870]
I want to dynamically create 10000 collections but after creating 450 i get exception about "Index was outside the bounds of the array." Is there a limit of the amount of collections that can be created?

**Comment by for7raid** [comment]
Take a look at documentation http://www.litedb.org/docs/collections/
> The total size of all the collections names in a database is limited to 8000 bytes. If you plan to have many collections in your database, make sure to use short names for your collections. For example, if collection names are about 10 bytes in length, you can have ~800 collection in the database.

**Comment by andtii** [comment]
Aha, thnx i totally missed that!
