### ISSUE TITLE
How to query by GUID field

### ISSUE THREAD

**Issue by sysmirror** [mbdavid/LiteDB#1875]
For example

public class Test
{
  public Guid Key {get; set;}
}

Test test = new Test() { Key = new Guid("1eb2c168-ea2c-4692-b492-1309671c093a") }

I've tried to query the collection using the expression $.Key = '1eb2c168-ea2c-4692-b492-1309671c093a' but this returns no records.

Is there a special syntax required to query GUID columns?

Thanks

**Comment by lbnascimento** [comment]
@sysmirror `$.Key = GUID('1eb2c168-ea2c-4692-b492-1309671c093b')` should work.

**Comment by sysmirror** [comment]
> @sysmirror `$.Key = GUID('1eb2c168-ea2c-4692-b492-1309671c093b')` should work.

That worked. Thanks
