### ISSUE TITLE
Unit Test failed?

### ISSUE THREAD

**Issue by kozmaj** [mbdavid/LiteDB#19]
Hi David!

LiteDB is great job!

When I tried to run the unit tests, there was a failed test inside the Bson_Test() method. At calling Assert.AreEqual(d["minDate"].AsDateTime, DateTime.MinValue) the test result was "Assert.AreEqual failed. Expected:<0001.01.01. 1:00:00>. Actual:<0001.01.01. 0:00:00>." Before the serialization the value of d["minDate"] was "0001.01.01. 0:00:00", but after the deserialization it was "0001.01.01. 1:00:00" (one hour different).

Thanks.

**Comment by mbdavid** [comment]
Hi @kozmaj, thanks for your bug report. You right, depend on timezone you are, min date has a bug after convert to UTC date (according BSON spec). I fixed on master branch, please, pull and test again. Thanks.

**Comment by kozmaj** [comment]
Hi David!

I run the unit tests of new, master version again and everything OK!

Thanks.

József
