### ISSUE TITLE
Change desirialization of Nullable types

### ISSUE THREAD

**Issue by joelweiss** [mbdavid/LiteDB#190]
Is there a way I can change the default behavior of Nullable types to desiralize to null if they were serialized to null? the following doesn't seem to work
```csharp
protected override void OnModelCreating(BsonMapper mapper)
{
	mapper.RegisterType<DateTimeOffset?>
		(
			serialize: dto => new BsonValue(dto.HasValue ? dto.Value.UtcDateTime : default(DateTimeOffset?)),
			deserialize: bson => bson.IsNull ? default(DateTimeOffset?) : bson.AsDateTime.ToUniversalTime()
		);
	mapper.RegisterType<TimeSpan?>
	(
		serialize: ts => new BsonValue(ts.HasValue ? ts.Value : default(TimeSpan?)),
		deserialize: ts => ts.IsNull ? default(TimeSpan?) : TimeSpan.Parse(ts.AsString)
	);
	base.OnModelCreating(mapper);
}
```
since that is was a nullable gets lost [here](https://github.com/mbdavid/LiteDB/blob/6dbc17ad757a9b42100dad2d1d6a8f1e4194a03c/LiteDB/Serializer/Mapper/BsonMapper.Deserialize.cs#L122)
```csharp
else if (Reflection.IsNullable(type)) 
{ 
  type = Reflection.UnderlyingTypeOf(type); 
} 
```
so 
```csharp
else if (_customDeserializer.TryGetValue(type, out custom)) 
{ 
	return custom(value); 
} 
```
will never find the custom mapper

Any suggestions?

**Comment by mbdavid** [comment]
Is there any special reason to store another value than null? If you map non nullable values will work. And null values are indexed too.

**Comment by joelweiss** [comment]
My bad the documentation confused me. [Mapper Conventions](https://github.com/mbdavid/LiteDB/wiki/Object-Mapping#mapper-conventions)
it says:

> * Nullable<T> are accepted. If value is null the BSON type is Null, otherwise the mapper will use T.

I thought that the null gets lost and returns you the default of `T`,  maybe change it to "otherwise the mapper will use `T?`.

Thanks for the quick response and the awesome library.
