### ISSUE TITLE
How to include/fetch nested data when using a query?

### ISSUE THREAD

**Issue by MacDennis76** [mbdavid/LiteDB#191]
Hello,

I am using version v.2.0.0-rc. I am trying to figure out how to fetch a deeply nested structure from the database by using a Find query.

Let's say this is the structure of the data ..
Order > OrderLines > Product
How to retrieve a particular order which includes all orderlines and all product data? Basically, all nested data.

Looking at the most recent code I can only include one level deep? Like ..
var orders = collection.Include(x => x.OrderLines).Find(x => (x.OrderNumber == orderno));

This fetches all data of the order and the orderlines but not of the product. 
Is this possible?

With kind regards,
Dennis Velthuis

**Comment by mbdavid** [comment]
Hi @MacDennis76, by now it's not possible, but take a look on this solution (i didn't test yet).

https://github.com/mbdavid/LiteDB/issues/149

**Comment by MacDennis76** [comment]
Hi @mbdavid,

I tried try the code but I hadn't had much luck with it.
Would be great if this could be a feature of an upcoming release.

Keep up the good work, this project is very much welcome!
