### ISSUE TITLE
[BUG] Cannot access the file... it is being used by another process

### ISSUE THREAD

**Issue by milos12345** [mbdavid/LiteDB#1915]
**Version**
LiteDB version 5.0.9, WIndows 10, .NET 4.8

**Describe the bug**
Getting crash reports from users with
```
System.IO.IOException: The process cannot access the file 'C:\ProgramX\Tags.db' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at LiteDB.Engine.FileStreamFactory.GetStream(Boolean canWrite, Boolean sequencial)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at LiteDB.Engine.DiskService..ctor(EngineSettings settings, Int32[] memorySegmentSizes)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.ConnectionString.CreateEngine()
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
```

**Code to Reproduce**
Automatically sent crash reports
```
lock (dbLock)
    using (var db = new LiteDatabase( FullPathToDb )) { // <----- here
        // loading or saving to dictionary
    }
```

**Additional context**
I am only loading the db into a dictionary on program start and save the dictionary into the db when window closes, not using async but in UI thread

I've even added a lock with  `private static readonly object dbLock = new object();` before saving and loading 

I am also making sure there is only one instance of the program with a code [similar to this one ](https://github.com/codemodify/filewatcher/blob/549e47ef35f18ebb69bccda31a85631d1cac5411/SingleInstanceManager/ApplicationInstanceManager.cs)

I have never caught it myself but only get these in automatically sent crash report, but since these are anonymous I cannot find any more information

**Comment by siquylee** [comment]
I had the same issue although I used _Connection=shared_

**Comment by dkalnauz** [comment]
Hello. 
By default, context is creating with the Direct connection mode which means that the database file cannot be opened by another process. 
To fix that you have to use Shared connection mode, which will close the database files after each operation.
Connection string will have next view: 
```
var connectionString = @#"Filename={FullPathToDb}; Connection=Shared;
```
And whole context initialization: 
```
var connectionString = @$"Filename={FullPathToDb}; Connection=Shared;";
          using (var db = new LiteDatabase(connectionString))
          {
              // loading or saving to dictionary
          }
```
I believe, that lock is unnecessary with this solution.

**Comment by fadif91** [comment]
I thought in a multithreaded same process scenario direct should work. But I need to use Shared as Connection type
That is when creating a new LiteDatabase instance or when using the same one as well

This means that same instance of LiteDatabase is not threadsafe nor LiteRepository, unless you set Connection=shared;
but in your comment above you stated that it should be done for multiple processes to access the file 

Could you elaborate on that ?

**Comment by siquylee** [comment]
I resolved the issue by using a shared db variable instead of
```
using (var db = new LiteDatabase(connectionString))
          {
              // loading or saving to dictionary
          }
```

 I used LiteDb for MS Excel add-in so it was single process.

**Comment by dkalnauz** [comment]
> I thought in a multithreaded same process scenario direct should work. But I need to use Shared as Connection type
> That is when creating a new LiteDatabase instance or when using the same one as well
> 
> This means that same instance of LiteDatabase is not threadsafe nor LiteRepository, unless you set Connection=shared;
> but in your comment above you stated that it should be done for multiple processes to access the file
> 
> Could you elaborate on that ?

Yes, LiteDatabase and Lite Repository isn't threadsafe. 
If you have multi-threaded database queries, in case if they are executed in parallel, you can treat each thread as one "independent" program/process.

**Comment by milos12345** [comment]
Thank you. The `Connection=Shared;` seems to has fixed it as I didn't receive another automatic crash report with anything related. I have just expected that it would not be necessary since I am loading db into a dictionary at the program start and save on program close; both done from UI thread, and forced single instance of the program
