### ISSUE TITLE
[QUESTION]  Extended Json

### ISSUE THREAD

**Issue by AngelMunoz** [mbdavid/LiteDB#1919]
Does LiteDB support the MongoDB's [extended json](https://docs.mongodb.com/manual/reference/mongodb-extended-json/) format or is it a slightly different one?

**As an aside, this is the motivation**

I've been working on past months on a [small library for F#](https://github.com/AngelMunoz/Mondocks) users that works with the extended json to provide a DSL like API for them to write queries.
It would be nice to know if there's a way to run the extended json as commands like in the [mongo driver](https://mongodb.github.io/mongo-csharp-driver/2.11/apidocs/html/M_MongoDB_Driver_IMongoDatabase_RunCommandAsync__1.htm)

that way I could work in LiteDB commands as well

**Comment by mbdavid** [comment]
Hi! There is no complete support for MongoDB extended JSON. In LiteDB there is no "Regular expression" and "Timestamp". But all other are the same BSON binary generated.

**Comment by AngelMunoz** [comment]
I see, thanks!
