### ISSUE TITLE
[QUESTION] Complex nested objects - v5.0.10

### ISSUE THREAD

**Issue by panther142** [mbdavid/LiteDB#1926]
Hi,

I am using LiteDB v5.0.10 and have a simple scenario where I have a number of POCO's such as:

```
class Portfolio
{
   public int Id { get; set; }
   [BsonRef("holdings")]
   public List<Holdings> Holdings { get; set; } = new List<Holdings>();
}

class Holdings
{
  public int Id { get; set; }
  [BsonRef("transactions")]
  public List<Transaction> Transactions { get; set; } = new List<Transaction>();
}

class Transactions
{
  public int Id { get; set; }
  public int Value {get; set; }
}
```

I have two questions:

1. What is the correct way to store these object in a LiteDB with each class (Portfolio, Holdings and Transactions) being in a separate collection?

2. What is the correct way to retrieve this data from LiteDB as a single Portfolio object?

Thanks in advance.

**Comment by panther142** [comment]
@mbdavid @lbnascimento any advice on this - thanks!

**Comment by mbdavid** [comment]
Hi @panther142, document store reference are quite different from relational database. Take a look how your document are converted before store in disk

```JS
// portifolio
{
    _id: 1,
    Holdings: [
        { $id: 10, $ref:"holdings" },
        { $id: 11: $ref:"holdings" },
        ....
    ]
}
```

The same occurs inside Holding collection (with transaction).

It´s quite different from relational database.... because `$id` refs will always on top collection.

**Comment by panther142** [comment]
Thanks for your reply @mbdavid - so is there an approach that would work in my scenario using LiteDB or are we better to use a more traditional RDBMS?

**Comment by panther142** [comment]
@mbdavid ?

**Comment by mbdavid** [comment]
There is no better in this case. All works fine but it's better to know how your data will be storaged. You can read about document store database in MongoDB docs (are my best source https://docs.mongodb.com/manual/reference/database-references/)
