### ISSUE TITLE
[1.0.4] Wrong calculation of start position in recovery

### ISSUE THREAD

**Issue by nerai** [mbdavid/LiteDB#193]
I'm a bit confused by `ReadPageJournal (BinaryReader reader)` in RecoveryService.

It reads:

            var stream = reader.BaseStream;
            var posStart = stream.Position * BasePage.PAGE_SIZE;
            var posEnd = posStart + BasePage.PAGE_SIZE;

Is this the right way to calculate posStart? I would have thought it should instead just be `var posStart = stream.Position`. I've notice this because later on there is this line:

            reader.ReadBytes((int)(posEnd - stream.Position));

and the argument becomes negative, because posEnd is huge, and substracting stream.Position yields an apparently random value, which, when cut down to `int` size, is negative, raising an exception.

It seems this was completely rewritten in 2.0, so this is a historic ticket. Nontheless, my 60GB database is having this hickup and it would be great if this could be had a look at :)

**Comment by nerai** [comment]
For what it's worth, I've tried and changed the line in question and the recovery then completed successfully, the DB seems to be usable and not corrupted.

**Comment by mbdavid** [comment]
Hi @nerai, I review this source and a can't remember why I made this. Did you fix? Can you make a pull request for 1.0.4 tag version?

BTW, 60gb in LiteDB?

**Comment by nerai** [comment]
I've added a PR, please see if it can still be used in the current version. I was unable to create a PR against 1.0.4 for some reason (github did not let me), sorry. Maybe you can merge it in manually, if applicable.

This change seemed to fix it. I've not studied it a lot, but it seems a lot more logical after the change, too.

Yes, 60GB (9m rows) of cached results of some program of mine, expected to grow to ~200-500GB with ~100-150m rows. So far, I've not had much trouble. I used SQLite before, but it became incredibly slow at around 10GB.

**Comment by nerai** [comment]
Fixed in v1 branch as per https://github.com/mbdavid/LiteDB/compare/29e02bec71...17214c89bc
