### ISSUE TITLE
Flaws in encryption?

### ISSUE THREAD

**Issue by imerzan** [mbdavid/LiteDB#1936]
https://github.com/mbdavid/LiteDB/blob/81c4216f01686e84a51f12872331b9862407aa7e/LiteDB/Engine/Disk/Streams/AesStream.cs#L81
I believe this is using an identical IV for each run?
`_aes.GenerateIV();` should generate a sufficiently random IV

![image](https://user-images.githubusercontent.com/42287509/106955406-d406ba80-66fa-11eb-8873-ddb0cdb78780.png)
As you can see a lot of duplicate entries in the DB which indicates the SALT/IV are not unique. I am worried that this implementation is susceptible to attack.

**Comment by NHodgesVFX** [comment]
Encryption also uses ecb mode which is broken and considered insecure. Besides the ecb mode and above there are also other issues mentioned in another pr as well. Encryption should really be cbc then hmac or xchacha-poly1309 today.

**Comment by imerzan** [comment]
I'm more familiar with CBC myself, but upon reading up on ECB it states:
> Because ECB encrypts identical plaintext blocks into identical ciphertext blocks, it does not hide data patterns well. ECB is not recommended for use in cryptographic protocols.

In some of my own code that I've used CBC for encrypting byte arrays, I would implement as follows:
```csharp
byte[] data = [ ... ]; // Random data
byte[] salt = GetSalt(8) // Method to generate 8 byte crypto-random salt
memoryStream.Write(SALT, 0, SALT.Length); // Write SALT to stream
_aes.Key = psk.GetBytes(32); // 256 bit AES
_aes.GenerateIV() // Get crypto-random IV
memoryStream.Write(aes.IV, 0, aes.IV.Length); // Write IV to stream
using (CryptoStream cryptoStream = new CryptoStream(memoryStream, aes.CreateEncryptor(), CryptoStreamMode.Write))
                {
                    cryptoStream.Write(data, 0, data.Length); // Write encrypted data to stream
                }
```

You should be able to store the IV/SALT with the encrypted payload safely (or at least the IV, if you want to obscure the SALT by another means).

To decrypt

```csharp
byte[] SALT = encrypted.Take(8).ToArray(); // Get the SALT from payload
_aes.IV = encrypted.Skip(8).Take(16).ToArray(); // Get the IV from payload
// continue decryption with password
```

Honestly not sure how to optimize for this program in particular but you get the idea. Each write operation would generate unique output, even if the input remains 100% the same.

**Comment by NHodgesVFX** [comment]
Cbc is fine but you need to add authentication see https://docs.microsoft.com/en-us/dotnet/standard/security/vulnerabilities-cbc-mode

Also not a crypto expert but have used it in personal programs as well and have tried to best be aware of gotchas.

**Comment by imerzan** [comment]
Yeah, makes sense to me. Hopefully author will work on this, I don't see any indication of this being on the ToDo despite #1273 being years old.

**Comment by NHodgesVFX** [comment]
To bad Microsoft example code isn't stream friendly. If it was you could just copy paste it.

**Comment by mbdavid** [comment]
Hi guys, thanks for this subject. Current branch 5.1 use another algorith to encryption: XTS: https://github.com/mbdavid/LiteDB/tree/v5.1/LiteDB/Utils/Xts

Current ECB still works but all new database will be created using this new algorithm

**Comment by imerzan** [comment]
Wonderful! Thanks for the heads up.
