### ISSUE TITLE
int Upsert(IEnumerable<T> entities);

### ISSUE THREAD

**Issue by sigmarsson** [mbdavid/LiteDB#1941]
Hi, 

Shall this method return the number of records either inserted or updated successfully ? 
I detect a 0 return value meanwhile a record updated.

**Comment by lbnascimento** [comment]
@sigmarsson The `int Upsert(...)` overload returns the number of _inserted_ records. So, if it returned 0, it means that all of the records in the `IEnumerable<T>` were updated and none needed to be inserted.

**Comment by sigmarsson** [comment]
Cool. ic. & no negative values. you throw ex in case of problems.
