### ISSUE TITLE
[BUG] LiteDb can't read Bson.ObjectId

### ISSUE THREAD

**Issue by fritz-net** [mbdavid/LiteDB#1944]
**Version**
LiteDB version: 5.0.10 (nuget)
OS: Win10 64bit
.NET framework: 3.1 Core

**Describe the bug**
When reading an object with Bon.Object ID I get the following error:
Value cannot be null. (Parameter 'bytes')

It seems LiteDB is calling the `public ObjectId(byte[] bytes)` constructor but with null
When i Look at the DB with LiteDB Studio all ID fields have data in them.

**Code to Reproduce**
```
public class MongoEntity
{
    [BsonId]
    public ObjectId _id { get; set; }
}

var collection = db.GetCollection</* child of MongoEntity*/>("some name");

var result = collection.FindAll();
foreach (var row in result) // here the error occours
{
```

**Expected behavior**

**Screenshots/Stacktrace**
```
 at MongoDB.Bson.ObjectId..ctor(Byte[] bytes)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
```

![image](https://user-images.githubusercontent.com/2499282/109006506-70ddc780-76ab-11eb-9c80-71dbdd829337.png)

**Additional context**
as I saw, Bson.ObjectId has no arg free Constructor

**Comment by lbnascimento** [comment]
@fritz-net You're using the MongDB `ObjectId` type. The LiteDB mapper doesn't know how to deserialize it and ends up using the wrong constructor. You can get it working by adding the following code to your project:

```C#
BsonMapper.Global.Entity<MongoDB.Bson.ObjectId>().Ctor(doc =>
            new MongoDB.Bson.ObjectId(
                doc["TimeStamp"].AsInt32,
                doc["Machine"].AsInt32,
                (short)doc["Pid"].AsInt32,
                doc["Increment"].AsInt32));
```

While this should work, you'll be storing the oid as a document, which will perform worse than using the native LiteDB `ObjectId` type.

**Comment by fritz-net** [comment]
Thank you @lbnascimento this fixed the issue for me.

Also thanks for the hint regarding perfomance. The issue with Chaning the ObjectId is that I want to be able to both use Mongo or LiteDb debending on the Setup of the program (stanalone = litedb OR server = mongo)

**Comment by lbnascimento** [comment]
@fritz-net In theory, it should be possible to use pre-processor directives for this purpose:

```C#
public class MyClass
{
#if SERVER
	MongoDB.Bson.ObjectId _id { get; set; }
#else
	[BsonId]
	LiteDB.ObjectId _id { get; set; }
#endif
}
```

You would also have to do the same for every time you access the `_id` property. Honestly, I wouldn't bother with it unless I actually experienced performance issues.

**Comment by fritz-net** [comment]
@lbnascimento thanks for your response. I think I will use your first suggestion.

Performance is no issue at the moment. If there are issues I will benchmark and decide if its worth the effort to have 2 executables.
