### ISSUE TITLE
Signed [BsonId]

### ISSUE THREAD

**Issue by sigmarsson** [mbdavid/LiteDB#1946]
Even though I aim to ensure the Key property hashes the Id property on my entity object, I witness different Id values coming in and out of the DB. Is `BsonId` ignored upon insert even in a blank DB or why are there multiple entities with the same Key and different Ids ?

```
        #region Member
        [BsonId]
        public long Id { get; set; }

        [BsonField]
        public string Key { get; set; }
```

And the ctor : 

```
        public ctor(string key) : this()
        {
            Id = key.GetHashCode();

            Key = key;
```

**Comment by lbnascimento** [comment]
@sigmarsson I could not reproduce the issue. What OS, runtime and LiteDB version are you running? Are you sure that there isn't a piece of code somewhere that overwrites `Id`? Are you able to reproduce this in a simple test case or it only happens in your application?

**Comment by sigmarsson** [comment]
#@K there is bug in the library in this context. .GetHashCode() has fooled me. This is not a real hash function on a string I am sure. 

`**Id = key.GetHashCode();**`

It yields miscellaneous values for the same string.
