### ISSUE TITLE
[QUESTION] Using LiteDB as Dictionary replacement and the failing to understand EnsureIndex 

### ISSUE THREAD

**Issue by milos12345** [mbdavid/LiteDB#1947]
I plan to use LiteDB as a replacement for Dictionary so it doesn't have to be loaded into memory. The Key (or ID) would be the Paths to folders, and I'm storing custom properties for each.

I was expecting that the `col.EnsureIndex(x => x.Path);` would make the `Path` property into the id, sort by it, and also prevent duplicates when executing `Upsert`, but it looks like this

![image](https://user-images.githubusercontent.com/5231547/109406629-a94e0180-7948-11eb-99c8-9970aa9f1057.png)

```
internal void AddOrUpdate(string path, FolderView fv)	
{					 
	using (var db = new LiteDatabase(new ConnectionString {Filename = pathToDb, Connection = ConnectionType.Shared}))
	{    
		var col = db.GetCollection<FolderView>("FolderViews");  
		if (col.Count() == 0)
			col.EnsureIndex(x => x.Path); 
		col.Upsert(fv);
	}
}

class FolderView
{
    public string Path { get; set; } 
    public SortingData SD { get; set; }
    public string FVD { get; set; } 
}
```
I have understood that `col.EnsureIndex(x => x.Path)` would make the `Path` into the ID or at least sort entries by `Path`. 
What am I missing here?

**Comment by lbnascimento** [comment]
@milos12345 The correct way to make `Path` your id is to add the `[BsonId]` attribute above it. Or, alternatively, if you don't want to change your class:

```C#
BsonMapper.Global.Entity<FolderView>().Id(x => x.Path);
```

`EnsureIndex` is used to create an index over a field, which speeds up queries over that field. It can also be used to ensure uniqueness on a non-id field:

```C#
col.EnsureIndex(x => x.Field, unique: true);
```

**Comment by milos12345** [comment]
Thank you for the clarification! It works as expected and doesn't duplicate the field.
