### ISSUE TITLE
[QUESTION] How get items filtered by many parameters in Array?

### ISSUE THREAD

**Issue by tivial19** [mbdavid/LiteDB#1948]
For example there is some shops and they have some products. Every product have array of string parameters.
How can i selection shops by product parameters? All params must be in one product.

Shop1
{
	"_id" : 1,
	"products":
	[
		{
		"name":phone,
		"params":["black","small","Germany"]
		},
		{
		"name":tablet 
		"params":["blue","big","China"]	
		},
		{
		"name":apple 
		"params":["red","big","Sweet"]
		}
	]
}
Shop2
{
	"_id" : 2,
	"products":
	[
		{
		"name":phone,
		"params":["green","small","France"]
		},
		{
		"name":book 
		"params":["red","big","China"]	
		},
		{
		"name":pumpkin 
		"params":["yellow","big","Sweet"]
		}
	]
}		

One shop is one BsonDocument. I make like this:	
	
using (var db = new LiteDatabase(DBname))
{
	string Query=products[*].params[*] ANY LIKE('red') AND products[*].params[*] ANY LIKE('sweet');
	db.GetCollection(Name).Find(BsonExpression.Create(Query)));
}		

I get result Shop1 and Shop2.
In shop 1 red and sweet is apple. in shop 2 red is book, sweet is pumpkin.
BUT I want get only Shop1 with apple, where all params is in one product.
Something like this:

string Query=products[*].params[*] ANY (LIKE('red') AND LIKE('sweet'));

**Comment by lbnascimento** [comment]
@tivial19 The following expression should work:

`COUNT($.products[@.params any like 'red' and @.params any like 'sweet']) > 0`

**Comment by tivial19** [comment]
Leonardo Nascimento, yes it work. Thank you very much for help.
