### ISSUE TITLE
[BUG] Composite filter return no results

### ISSUE THREAD

**Issue by WebDucer** [mbdavid/LiteDB#1957]
**Version**
Which LiteDB version/OS/.NET framework version are you using. **(REQUIRED)**
- LiteDB: 5.0.10
- Runtime: .net 5

**Describe the bug**
I use the database as a cache for some GitLab hooks (error analysis for WebHooks). In the application I have a simple `Where` clauses, that ends in an empty result. If I execute the same query in Studio (or on in Memory data), I get the correct data.

**Code to Reproduce**
```csharp
var projectName = "dev/web/api/i-recy-crm";
var branchName = "support/6.3.48";
// Query on BsonDocument, like also used in LINQPad 6
var count1 = _db.GetCollection(nameof(PipelineHook)).Query()
	.Where(w => w["Project"]["PathWithNamespace"] == "dev/web/api/i-recy-crm" && w["Attributes"]["Ref"] == "support/6.3.48")
	.Count(); // Result: 0

// Query with LINQ on typed collection
var count2 = _db.GetCollection<PipelineHook>().Query()
	.Where(w => w.Project.PathWithNamespace == projectName)
	.Where(w => w.Attributes.Ref == branchName)
	.Count(); // Result: 0

// Query first on indexed property, then materialize
var count3 = _db.GetCollection<PipelineHook>().Query()
	.Where(w => w.Project.PathWithNamespace == projectName)
	.ToArray()
	.Where(w => w.Attributes.Ref == branchName)
	.ToArray()
	.Count(); // Result: 0

// Materialize all then query
var count4 = _db.GetCollection<PipelineHook>().Query()
	.ToArray()
	.Where(w => w.Project.PathWithNamespace == projectName)
	.Where(w => w.Attributes.Ref == branchName)
	.ToArray()
	.Count(); // Result: 6
```

The same SQL query in LiteDB.Studio return 6 items

```sql
SELECT $ FROM PipelineHook
WHERE $.Project.PathWithNamespace = "dev/web/api/i-recy-crm"
AND $.Attributes.Ref = "support/6.3.48"
```

**Expected behavior**
Query with LINQ should return the same results as in SQL

**Screenshots/Stacktrace**
- 
![image](https://user-images.githubusercontent.com/761881/111329828-b6b8fa80-866f-11eb-936e-25086db8c4e8.png)
- 
![image](https://user-images.githubusercontent.com/761881/111329999-da7c4080-866f-11eb-8d57-c11bc50f8390.png)

**Additional context**

Following indexes set (same db in Studio and C# project):

```csharp
var pipelineCollection = db.GetCollection<PipelineHook>();
pipelineCollection.EnsureIndex(i => i.Attributes.Id);
pipelineCollection.EnsureIndex(i => i.Attributes.Ref);
pipelineCollection.EnsureIndex(i => i.Attributes.Status);
pipelineCollection.EnsureIndex(i => i.Attributes.CreatedAt);
pipelineCollection.EnsureIndex(i => i.Attributes.FinishedAt);
pipelineCollection.EnsureIndex(i => i.User.Username);
pipelineCollection.EnsureIndex(i => i.User.Email);
pipelineCollection.EnsureIndex(i => i.Project.Id);
pipelineCollection.EnsureIndex(i => i.Project.PathWithNamespace);
```

**Comment by WebDucer** [comment]
Here is the DB:

- [hooks.ldb.zip](https://github.com/mbdavid/LiteDB/files/6149962/hooks.ldb.zip)

**Comment by lbnascimento** [comment]
@WebDucer Apparently there was some sort of corruption in the `ProjectPathWithNamespace` index. Your last query worked because it "forced" LiteDB to use the `AttributesRef` index, which was not affected. The good news is that you can easily fix this by dropping and recreating the index.

What's really weird though is that LiteDB running on .NET Framework is able to return the correct results even when using the corrupted index – this is not the case when running on .NET Core. I have no idea why this is the case, but I'll look into it.

**Comment by WebDucer** [comment]
@lbnascimento Can I somehow query the health of the index? If so, I would run the recreation after I deleted old entries (some  cleanup once a day :) ).
