### ISSUE TITLE
[QUESTION]How get not root items filtered by many parameters in Array?

### ISSUE THREAD

**Issue by tivial19** [mbdavid/LiteDB#1963]
For example there is some shops and they have some products. Every product have array of string parameters.
How can i select products by some product parameters? All params must be in one product.

Shop1
{
"_id" : 1,
"products":
[
{
"name":phone,
"params":["black","small","Germany"]
},
{
"name":tablet
"params":["blue","big","China"]
},
{
"name":apple
"params":["red","big","Sweet"]
}
]
}
Shop2
{
"_id" : 2,
"products":
[
{
"name":phone,
"params":["green","small","France"]
},
{
"name":book
"params":["red","big","China"]
},
{
"name":pumpkin
"params":["yellow","big","Sweet"]
}
]
}

One shop is one BsonDocument. I make like this:

string CMD="SELECT products FROM DBname WHERE  COUNT(products[params any like 'red' and params any like 'sweet']) > 0";
using (var db = new LiteDatabase(DBname))
{
    var result = db.Execute(CMD).ToArray();
}

The result is ALL products from shop1 (in shop1 there is red and sweet apple), but i want to get only  like 'red' and like 'sweet' products. This is only one apple.
How can i get select products by my filter?

**Comment by lbnascimento** [comment]
@tivial19 Try this: `SELECT products[params any like 'red' and params any like 'sweet'] FROM DBname WHERE COUNT(products[params any like 'red' and params any like 'sweet']) > 0`

You can actually omit the `WHERE` clause, but then you'll apply the `products[params any like 'red' and params any like 'sweet']` projection for every product, even the ones that don't match the predicate, and you'll end up with a lot of empty arrays.

**Comment by tivial19** [comment]
lbnascimento, I find another way without empty arrays:  SELECT *.products[params any like 'red' and params any like 'sweet'] FROM DBname;
It will return one BsonDocument with one key and one value as BsonArray of products. 
The same is
using (var db = new LiteDatabase(DBname))
{
   var Qq = db.GetCollection(ColName).Query().
   Select(BsonExpression.Create("*.products[params any like 'red' and params any like 'sweet']")).ToArray();
 }
It will return Array of BsonDocuments of products.
