### ISSUE TITLE
[SUGGESTION] Enable the discussion section to reduce false issues, and migrate all questions, and dicussions to.

### ISSUE THREAD

**Issue by AlBannaTechno** [mbdavid/LiteDB#1964]
Hi @mbdavid I think you should open the [discussion tab/section](https://docs.github.com/en/discussions/quickstart)
this will reduce the false issues, here because there are lots of issues, that only a question or discussion, so all these issues should move to the discussion section

![101874632-34c6ba80-3bc4-11eb-92e7-4ced85d568f6](https://user-images.githubusercontent.com/13814190/111974063-d33db280-8b07-11eb-8805-341f8181dae5.png)

**Comment by CadmiumC4** [comment]
I also suggest the same.

**Comment by mbdavid** [comment]
Thats right, I will enable this! Thanks!

**Comment by AlBannaTechno** [comment]
@mbdavid 👍 , but I think you should convert all questions `issues` to a discussion, there is an option on the right menu to do this,
also, you can **pin issue** that tells all developers that `some of the issues transferred to discussion section`, for anyone who missed `search for` his issue.
