### ISSUE TITLE
[QUESTION] How use Index of Array?

### ISSUE THREAD

**Issue by tivial19** [mbdavid/LiteDB#1965]
I have data:
Shop1
{
"_id" : 1,
"products":
[
{
"name":phone,
"params":["black","small","Germany"]
},
{
"name":tablet
"params":["blue","big","China"]
},
{
"name":apple
"params":["red","big","Sweet"]
}
]
}
Shop2
{
"_id" : 2,
"products":
[
{
"name":phone,
"params":["green","small","France"]
},
{
"name":book
"params":["red","big","China"]
},
{
"name":pumpkin
"params":["yellow","big","Sweet"]
}
]
}

I made index: col.EnsureIndex("Index", "$.products[*].params"); It look like: MAP($.products[*]=>@.params).
How can i use index in query?
Select $ From DBname WHERE $.products[*].params ANY Like 'red' => return 2 results but 
Select $ From DBname WHERE Index ANY Like 'red' => return 0 result

**Comment by lbnascimento** [comment]
@tivial19 It is not possible to use indexes explicitly. They are used internally to speed up certain queries.
