### ISSUE TITLE
How to add DbRef on BsonDocument [QUESTION]

### ISSUE THREAD

**Issue by maxvodoo** [mbdavid/LiteDB#1970]
### I am trying to achive the following

```
class Child{
   public string Id {get;set;}
  
  [DbRef]
  public string Parent Parent {get;set;}
}
```

using BsonDocument

```
 var doc = new BsonDocument();
doc.Add("Parent", new Parent()); //how to make it dbref instead of normal object
?
```

**Comment by mbdavid** [comment]
Hi @maxvodoo, if you use `DbRef` you should use your own `Child` class with mapping (using `BsonMapper`). Use `LiteDatabase` to get `GetCollection<Child>()`

If you want use `BsonDocument` you need implement this reference:

`doc.Add("Parent", new BsonDocument { ["$id"] = idParent, ["$ref"] = "parent_collection_name" });`
