### ISSUE TITLE
serialization fails on nested types

### ISSUE THREAD

**Issue by matteofabbri** [mbdavid/LiteDB#2]

**Comment by mbdavid** [comment]
Hi Matteo, can you post some code example?

**Comment by matteofabbri** [comment]
using System;
using LiteDB;
using System.IO;

namespace Test
{
    class Program
    {
        public class ccc
        {
            [BsonId]
            public Guid CustomerId { get; set; }

            public string val { get; set; }
        }

        static void Main(string[] args)
        {
            File.Delete("test.db");

            var db = new LiteEngine("test.db");
            //db.ConnectionString.JournalEnabled = false;

            var col = db.GetCollection<ccc>("ddd");

            col.Insert(new ccc() { CustomerId = Guid.NewGuid(), val = new string('c', 1024 * 1024) });

            for (int i = 0; i < 100000; i++)
            {
                //db.BeginTrans();
                Console.WriteLine(i);
                col.Insert(new ccc() { CustomerId=Guid.NewGuid(),val=new string('c',1024*1024) });
                //db.Commit();
            }
        }
    }
}

**Comment by mbdavid** [comment]
Did you get last version from NuGet? I tried this example and woks fine.

```C#
namespace Test
{
    public class ccc
    {
        [BsonId]
        public Guid CustomerId { get; set; }

        public string val { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            File.Delete("test.db");

            var db = new LiteEngine("filename=test.db;journal=false");

            var col = db.GetCollection<ccc>("ddd");

            col.Insert(new ccc() { CustomerId = Guid.NewGuid(), val = new string('c', 3024) });

            db.BeginTrans();

            for (int i = 0; i < 100000; i++)
            {
                col.Insert(new ccc() { CustomerId = Guid.NewGuid(), val = new string('c', 3024) });

                if (i % 1000 == 0) Console.WriteLine(i);
            }

            db.Commit();
        }
    }
}
```
Remember:
1) Your class must be public e non-inner class (use fastBinaryJSON for serialize/deserialize)
2) Document size limits it´s 256kb
