### ISSUE TITLE
How can I disable journal mode?

### ISSUE THREAD

**Issue by zenchanhk** [mbdavid/LiteDB#2012]
Hi,

I cannot find a way to turn journal mode off, highly appreciate for any help.

**Comment by mbdavid** [comment]
Journal file exists only in v4 and you can set journal=false in connection string.

https://github.com/mbdavid/LiteDB/wiki/Journaling-and-Recovery

v5 uses WAL (log file) that works different and can't be disabled.

**Comment by zenchanhk** [comment]
oic, thanks a lot.
