### ISSUE TITLE
System.InvalidOperationException: 'This operation is not supported for a relative URI.'

### ISSUE THREAD

**Issue by MenNoWar** [mbdavid/LiteDB#2021]
Problem: Serializing an object which has not an absolute URI, just a relative.
`Exception thrown: System.InvalidOperationException: 'This operation is not supported for a relative URI.'`

Source of the Problem: `LiteDB/Client/Mapper/BsonMapper.cs::128`

Original: 
`RegisterType<Uri>(uri => uri.AbsoluteUri, bson => new Uri(bson.AsString));`

correct Version should be:
`RegisterType<Uri>(uri => uri.IsAbsoluteUri ? uri.AbsoluteUri : uri.ToString(), bson => new Uri(bson.AsString));`

**Workaround:**
manually register the custom mapper like:
`BsonMapper.Global.RegisterType<Uri>(uri => uri.IsAbsoluteUri ? uri.AbsoluteUri : uri.ToString(), bson => new Uri(bson.AsString));`

**Comment by lbnascimento** [comment]
@MenNoWar Thank you. This issue has been fixed in the master and its fix will be present in the next incremental release.
