### ISSUE TITLE
[QUESTION] How to delete an entry from a collection and update the database?

### ISSUE THREAD

**Issue by Akitakek** [mbdavid/LiteDB#2022]
Current code:

```csharp
/// <summary>
/// Remove entries that are not present in ids
/// </summary>
public static List<ulong> Trim(List<ulong> ids)
{
    using (var db = new LiteDatabase($"{AppContext.BaseDirectory}Data.db"))
    {
        // Get collection
        var col = db.GetCollection<LilyraUser>("lilyrausers");
        // Get list of users
        var users = col.FindAll();

        // Create return list
        var deleted = new List<ulong>();
        // Foreach user in the database..
        foreach (var user in users)
        {
            // If the user id isn't present in "ids"
            if (!ids.Contains(user.Id))
            {
                // Delete
                deleted.Add(user.Id);
                col.Delete(user.Id);
            }
        }

        // Return deleted ids;
        return deleted;
    };
}
```

No matter how many times i run the function, it keeps returning 30 entries (in my use case).
So I can only assume they're not actually being deleted.

Edit: I think I know why, it's updating the collection variable but it's not actually updating the database itself, not sure how to do that though.

Am I doing something wrong?
Thank you.

**Comment by lbnascimento** [comment]
@Akitakek By any chance, are the ids of these 30 remaining entries greater than `long.MaxValue` (9223372036854775807)?

**Comment by Akitakek** [comment]
```
180574360459935745, 191169158807814144, 207358761671720960, 223736077788119040, 242683787882790912, 285890131955548160, 320530192709844992, 364501380762959872, 376141189415436289, 394299162834763777, 425740125717397515, 496752341857468416, 539820622121795635, 617752993441382464, 632494262931423242, 639233686574858278, 670483337713811476, 692316673096679465, 704735068068905031, 726141314177171506, 740791396901978242, 764339672356225064, 771708394591354922, 807434479332229153, 814518777026445336, 816723378072977490, 834820140923093032, 853321652200013846, 855706831970893834, 858834073962545183
```

These are the IDs it's trying to delete but can't.

**Comment by lbnascimento** [comment]
@Akitakek LiteDB does not natively suport `UInt64`, but it supports `Int64` and `Double`. What is happening is that C# is implicitly casting the id to `Double` when you call `col.Delete(...)`, and apparently `Double` is losing precision at such magnitudes (just try `Convert.ToDouble(180574360459935745).ToString("N0")` and you'll see it becomes 180574360459936000). Why C# is opting to implicitly cast it to `Double` instead of `Int64` is beyond me.

The easiest fix would be to simply change your id field to `Int64` (given that's how LiteDB will store your `UInt64` anyway). If that is not possible, you must be careful to always explicitly cast your `UInt64` to `Int64` when using any method that takes a `BsonValue` as id.

**Comment by Akitakek** [comment]
> 
> 
> @Akitakek LiteDB does not natively suport `UInt64`, but it supports `Int64` and `Double`. What is happening is that C# is implicitly casting the id to `Double` when you call `col.Delete(...)`, and apparently `Double` is losing precision at such magnitudes (just try `Convert.ToDouble(180574360459935745).ToString("N0")` and you'll see it becomes 180574360459936000). Why C# is opting to implicitly cast it to `Double` instead of `Int64` is beyond me.
> 
> The easiest fix would be to simply change your id field to `Int64` (given that's how LiteDB will store your `UInt64` anyway). If that is not possible, you must be careful to always explicitly cast your `UInt64` to `Int64` when using any method that takes a `BsonValue` as id.

But how come that it works for essentially everything else I've used it for with litedb, just not col.Delete(), doesn't make much sense to me?
I'll try the casting in this function at least, and see if that fixes it and report on it.

**Comment by Akitakek** [comment]
Coming back to it now, seems like that was indeed the issue.

That said this issue only seems to be a problem when trying to delete, the rest of the time it's perfectly fine.
