### ISSUE TITLE
Query performance, v4 vs v5 vs v4->v5

### ISSUE THREAD

**Issue by PeterThornton4Ing** [mbdavid/LiteDB#2023]
Im seeing some really strange Query performance problems after updating to version 5:

The context is 1.5 million simple POCO objects "Item" in a collection. 
The Item has a bool property "ShowInSys" 
There is a related index _db.GetCollection<Item>().EnsureIndex(i => i.ShowInSys);

We query for items like this: _db.GetCollection<Item>().Find(i => i.ShowInSys)
This returns about 50 items (of the 1.5 million total)

When doing the above query in version 4.1.4 the query takes 68ms.

When upgrading an existing v4 database to v5 and doing the query it takes 68ms

When creating a new v5 database (and inserting the 1.5 mil items) the query takes 38000ms

Maybe im missing something here, but this makes no sense to me. Could someone shed some light on what is going on here? 
Why in the world is a "fresh" v5 so much slower than an updated v4? 

Edit: Running the same query "SELECT $ FROM Item where $.ShowIn= true" from LiteDb Studio exchibits the same problems when doing if on a upgraded v4->5 vs a clean v5 database.,

**Comment by lbnascimento** [comment]
@PeterThornton4Ing Could you send me your datafiles? You can send them to me at lbnascimento@inf.ufrgs.br

**Comment by PeterThornton4Ing** [comment]
> @PeterThornton4Ing Could you send me your datafiles? You can send them to me at [lbnascimento@inf.ufrgs.br](mailto:lbnascimento@inf.ufrgs.br)

Will do :-)

**Comment by lbnascimento** [comment]
There was a bug where indexes over `bool` fields were being created with an incorrect expression, so the query optimizer was not finding them. The fix for it is to open the affected datafile with the latest master of LiteDB, dropping all of the `bool` indexes and recreating them.

@PeterThornton4Ing Given that you have an unaffected version of your datafile, you may simply keep using them.

**Comment by PeterThornton4Ing** [comment]
Excellent! Thank you very much. 
Any ETA on a new release?

**Comment by lbnascimento** [comment]
@PeterThornton4Ing It has been released.

**Comment by PeterThornton4Ing** [comment]
> @PeterThornton4Ing It has been released.

Excellent. I see the new build, but the NuGet package is still version 5.0.10 any ETA on an updated NuGet package?

**Comment by lbnascimento** [comment]
@PeterThornton4Ing It should be out now.
