### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lileishihaoren** [mbdavid/LiteDB#2028]
**Version**
LiteDB 5.0.10

**Describe the bug**
SQL syntax LIKE return unexpected result.

**Screenshots/Stacktrace**
![图片](https://user-images.githubusercontent.com/14323630/125427180-6eec1a8b-d151-49a3-8cf4-21feae17bfd2.png)

**Comment by lbnascimento** [comment]
@lileishihaoren Are you referring to the case insensitivity? LiteDB datafiles are case insensitive by default, but this can be changed with a rebuild: `rebuild {"collation": "en-US/None"}`. You can change the `en-US` to any other culture supported by C#. And you can change the `None` to one or more of the [C# compare options](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.compareoptions?view=net-5.0).
