### ISSUE TITLE
[QUESTION] how to update array field only?

### ISSUE THREAD

**Issue by xibaoning** [mbdavid/LiteDB#2030]
{
    "name": "John",
    "age": 13,
    "items":[1,2,3]
}
db.Execute($"update collection set items=???? where _id = {myid}").

and any way to append data to items ?
eg: db.Execute($"update collection set items.append(?????) where _id = {myid}").

**Comment by lbnascimento** [comment]
@xibaoning This should work: `update collection set items = CONCAT(items, [4,5,6]) where _id = {myid}`.
