### ISSUE TITLE
[BUG] "Sharing violation on path" error on EnsureIndex

### ISSUE THREAD

**Issue by Krypt0nC0R3** [mbdavid/LiteDB#2035]
**Version**
LiteDB: 5.0.10
OS: Raspbian
.NET Framework: 4.5 on Mono

**Describe the bug**
Randomly, when simultaneously accessing the database when calling EnsureIndex, the program crashes with the message "Sharing violation on path /home/pi/blah/blah/LocalData.db"

**Code to Reproduce**
https://pastebin.com/ReYhEpwn

**Screenshots/Stacktrace**
Stacktrace: https://pastebin.com/uKuiHJVZ

**Comment by lbnascimento** [comment]
@Krypt0nC0R3 The `SharedEngine` class uses a global mutex to synchronize the datafile access between multiple instances of LiteDB. However, if another process locks the datafile for whatever reason, you'll get these kinds of errors.

**Comment by Krypt0nC0R3** [comment]
@lbnascimento I am working with this file only from this application with file pre-locked on my side. There are no other applications working with this file on the device.

**Comment by lbnascimento** [comment]
@Krypt0nC0R3 What do you mean by "with file pre-locked on my side"? The C# `lock` instruction uses a monitor to synchronize access between threads in the same process, it does nothing to other processes.

Anti-viruses and versioning control tools (like TortoiseGit) are some applications that are known to randomly lock LiteDB datafiles.

**Comment by Krypt0nC0R3** [comment]
@lbnascimento Yes, I meant the lock instruction. I use it to provide thread safety in my application so that no other thread can access the database while working with it. There are no other applications (antiviruses, etc.) on the device. Only "naked" Raspbian and my application. The moment I get the exception, I run the fuser command with my database specified, but the command output only shows my application. Those. no other process is using the database file

**Comment by lbnascimento** [comment]
@Krypt0nC0R3 If you're not accessing the same datafile from multiple processes, there's no reason to use `connection=shared`. Just drop it and let's see what happens.

**Comment by Krypt0nC0R3** [comment]
@lbnascimento I removed the `connection=shared` from the connection string but the exception is still thrown

**Comment by lbnascimento** [comment]
@Krypt0nC0R3 Is this still an intermittent issue? Try opening the database once and keeping it open for the lifetime of the process.

**Comment by Krypt0nC0R3** [comment]
@lbnascimento When is it physically written to a file? At the time of the call to Update/Upsert/Insert/Delete? Or when calling Dispose on a database object? If the first option, then I will. I just need that when the computer (Raspberry) is suddenly turned off, the data is saved in storage

**Comment by Krypt0nC0R3** [comment]
I found a solution. I will keep the database open, and record changes using Checkpoint
