### ISSUE TITLE
[QUESTION]Null object cannot be converted to a value type Everthing is Ok

### ISSUE THREAD

**Issue by lucaswhob** [mbdavid/LiteDB#2040]
Hello My Friends 
I Write to LiteDb Is Ok Please See This Picture :
[Write To DB IS OK](https://www.mediafire.com/convkey/49ed/1q4739v3v2pjzwf9g.jpg?size_id=5)
But Read From DB IS Fail 
[Read From Db  Fail](https://www.mediafire.com/convkey/c946/51hhlayktl1o7tm9g.jpg?size_id=5)
I After Several hour I Know Property SystemFontNme Is Null !
Please See My Database Record in LiteDb Studio
[My DataBase Record ScreenShot](https://www.mediafire.com/convkey/e635/0fv8ddcek39awbs9g.jpg?size_id=7)
Question : How Sole This Problem ?
Question2 : How Skip serialize Specific Property ?
thx

**Comment by lucaswhob** [comment]
My Data Class ScreenShot : Please See
[MyClass ScreenShot](https://www.mediafire.com/convkey/2689/jhf3fws1d4sy57z9g.jpg?size_id=5)

**Comment by lbnascimento** [comment]
@lucaswhob The LiteDB mapper doesn't like the `Font` class very much, You can add a custom serializer/deserializer, if you want. Something like this should work fine:

```C#
BsonMapper.Global.EnumAsInteger = true;
BsonMapper.Global.RegisterType<Font>
(
    font => new BsonDocument
    {
        ["FamilyName"] = font.FontFamily.Name,
        ["EmSize"] = font.SizeInPoints,
        ["FontStyle"] = BsonMapper.Global.Serialize(font.Style)
    },
    doc => new Font
    (
        doc["FamilyName"].AsString,
        (float)doc["EmSize"].AsDouble,
        BsonMapper.Global.Deserialize<FontStyle>(doc["FontStyle"])
    )
);
```

Alternatively, if you want to ignore this property, you can add the `BsonIgnore` attribute to it.

**Comment by lucaswhob** [comment]
Thx My Friend My Problem Is Solved .
