### ISSUE TITLE
[QUESTION] GetCollection<T> doesnt work

### ISSUE THREAD

**Issue by Krypt0nC0R3** [mbdavid/LiteDB#2041]
I wanted to test how fast a large database `Rebuild` (over 50,000 records) would run on my machine. For this I have created a simplest class and am trying to store it in the database. But in the output I only get `_id` without my data. Although I do everything in the same way as it is written in the [wiki ](http://www.litedb.org/docs/object-mapping/)
My code: 
https://pastebin.com/m9bN6w48

Here is an example of how it should look: 
![image](https://user-images.githubusercontent.com/46594859/127262062-49020861-9ce6-4257-9488-9d9741aaa665.png)

This is what I see:
![image](https://user-images.githubusercontent.com/46594859/127262141-dabcb4f5-7913-4546-8e24-ef698e5e1eb9.png)

What i do wrong?

**Comment by lbnascimento** [comment]
@Krypt0nC0R3 By default, the LiteDB mapper only serializer properties. If you want it to serialize public fields too, you can run the following command once: `BsonMapper.Global.IncludeFields = true;`

**Comment by Krypt0nC0R3** [comment]
@lbnascimento thanks, it works!
