### ISSUE TITLE
[QUESTION] does LiteDB support C# 9 record?

### ISSUE THREAD

**Issue by roubachof** [mbdavid/LiteDB#2044]
C#9 records are finally the immutable type that we needed in C#.
Since it's syntax is game changing, does refit supports serializing/deserializing such objects ?

**Comment by lbnascimento** [comment]
@roubachof Given that records are merely syntatic sugar and are implemented using regular objects, the LiteDB mapper shouldn't have any issues serializing them. If you find a bug or weird behavior, you can open an issue.

**Comment by roubachof** [comment]
To follow-up this question. 
**WARNING** LiteDB has a limited C# 9 record support.
It doesn't support primary contructors, so you will have to type this:

```csharp
public record TourInfo()
{
    public int Id { get; init; }
    public Sector? Sector { get; init; }
    public Collector Collector { get; init; }
    public TourState TourState { get; init; }
    public string? Name { get; init; }
    public DateTime Date { get; init; }
    public List<int> SortedCollectionIdList { get; init; }
}
```

instead of this:

```csharp
public record TourInfo(
        int Id,
        Sector? Sector,
        Collector Collector,
        TourState TourState,
        string? Name,
        DateTime Date,
        List<int> SortedCollectionIdList);
```
