### ISSUE TITLE
[QUESTION] FIND/QUERY throw exception

### ISSUE THREAD

**Issue by valvenetbabu** [mbdavid/LiteDB#2054]
I'm a begginer in C#. Just started using LiteDB in one of my project.

My class:
```
  public class KeyValueObject
    {
        [BsonId]
        public ObjectId id;
        public string keyName;
        public object dataValue;
        public long lastUpdated;
    }
```
I'm inserting document. It's working fine.
```
        public void Store(string name, object value)
        {
            Console.WriteLine(Collection().Insert(new KeyValueObject { keyName = name,  dataValue = value }).ToString());
        }
```

I've a problem here, coll.Find thows exception "Member keyName not found on BsonMapper for type LocalDBStoreLibrary.KeyValueObject."
```
   public KeyValueObject Find(string name)
        {
            var coll = Collection();
            var res = coll.FindOne(x => x.keyName == name);
            if (res != null)
                return (KeyValueObject)res;
            else
                return null;
        }
```

What am I missing? How do I solve it?

**Comment by lbnascimento** [comment]
@valvenetbabu By default, the LiteDB mapper only serializes properties. If you want it to store fields too, you must run `BsonMapper.Global.IncludeFields = true`.

**Comment by valvenetbabu** [comment]
You are right, now it's ok. Thank you.

**Comment by valvenetbabu** [comment]
@lbnascimento  Thank you. That was it, now it's ok.
