### ISSUE TITLE
[BUG] The ROUND method parameter is incorrectly referenced

### ISSUE THREAD

**Issue by sunaccess** [mbdavid/LiteDB#2063]
**Version**
.NET Core 5.0 - Package version 5.0.9 - Development on Windows (Visual Studio) 

Development: Windows 10 x64

**Describe the bug**
The ROUND method parameter is incorrectly referenced
 "BsonExpression.Create(@"Round(126.118,1)").ExecuteScalar();"
Cannot return correct results
**Code to Reproduce**
 ![image](https://github.com/sunaccess/doc/blob/7f6b15c8ac5e6eb5d0e7c6157f3184b1ede4b45f/RoundBug.png?raw=true)
**Expected behavior**

**Screenshots/Stacktrace**

**Additional context**

**Comment by lbnascimento** [comment]
@sunaccess This issue has been fixed in the master and its fix will be present in the next incremental release.
