### ISSUE TITLE
[QUESTION] Was logging completely removed in v5?

### ISSUE THREAD

**Issue by Lukkian** [mbdavid/LiteDB#2086]
### Discussed in https://github.com/mbdavid/LiteDB/discussions/2070

<div type='discussions-op-text'>

<sup>Originally posted by **Lukkian** September 20, 2021</sup>
I would like to make some logging, looked in the documentation and didn't find anything, then I found this issue: https://github.com/mbdavid/LiteDB/issues/776

But this api is not available in v5, so has logging been completely removed since v4?</div>

**Comment by kcsombrio** [comment]
Hi @Lukkian, yes, this logging referred on issue #776 was removed in v5

**Comment by Lukkian** [comment]
Thank you very much, but please consider put some similar interface for logging in a future version.

**Comment by Lukkian** [comment]
Accidentally close, will reopen the issue for reference and keep the hope for a new logging interface, but feel free to close if you want. :)

**Comment by kcsombrio** [comment]
Ok, yes, I'll close this issue since there is a discussion related to this, as I think it's better there than as a issue
