### ISSUE TITLE
FileNotFoundException thrown when LiteDatabase use GetCollection

### ISSUE THREAD

**Issue by hanc2006** [mbdavid/LiteDB#209]
Hi,
II upgraded to version 2.0 RC LiteDB but the problem with the journal.db FileNotFoundException still persists when I debug. Now the exception was throw when I try to retrieve the data with the function GetCollection(). I use the correct connection string found in the wiki page for skip the journal but does not change.

` ConnectionString = string.Format("filename={0}; journal=false", ConfigurationManager.AppSettings["dbpath"]);`

Thx you

**Comment by mbdavid** [comment]
Hi, now rc2 was released. Please, update your datafile that must fix this.
