### ISSUE TITLE
FileStorage delete bug

### ISSUE THREAD

**Issue by naranakula** [mbdavid/LiteDB#21]
FileStorage.Upload("Core.dll",@"E:\Core.dll");        
if (FileStorage.Exists("Core.dll")) //return true
     FileStorage.Delete("Core.dll");//return false
             
FileStorage.Delete( "Core.dll".ToLower() );//return true

Delete must send lower case?why?

**Comment by mbdavid** [comment]
Hi @naranakula, yes, there is a bug that I fixed. Source in master branch. I added a UnitTest too.
