### ISSUE TITLE
Support for .net core

### ISSUE THREAD

**Issue by anishpsla** [mbdavid/LiteDB#210]
I am using lite DB for WPF application. Now I would like to know whether lite DB will support .net core and asp.net core

**Comment by mbdavid** [comment]
Hi @anishpsla, we are working on a portable version at this moment. To new .net core and asp.net core will take more time, but I don´t know yet any date.

**Comment by anishpsla** [comment]
What you mean by portable version ? Already it doesn't have any external dependencies.

**Comment by mbdavid** [comment]
Lite.Core has no platform dependency (eg: disk access). So, LiteDB.Core is used when you need multi platform app (like linux, macos or mobile). Lite.Core are very near to .net core/asp.net core, but it´s not tested yet. I will wait for final release before start testing.
