### ISSUE TITLE
[SUGGESTION] maybe do not store FiledName into data?

### ISSUE THREAD

**Issue by sgf** [mbdavid/LiteDB#2117]
**Is your feature request related to a problem? Please describe.**
i make a test store 1-million data in 2 files. one is CTS,one is CodeTask.  
```C#

    public class CTS {
        public CTS(string code, int taskId) {
            id = code;
            d = taskId;
        }
        [LiteDB.BsonId]
        public string id;
        public int d;
    }

       public class CodeTask {

            public CodeTask(string code, int taskId) {
                Code = code;
                TaskId = taskId;
            }

            [LiteDB.BsonId]
            public string Code;

            public int TaskId;
        }
```
im got 2 files.
![image](https://user-images.githubusercontent.com/2557696/146151498-9a1c4fa1-1ca5-4964-96b3-598b8c077322.png)

theres about 7mb size different.
 
if litedb make a field map(hold),maybe will be better ?

**Comment by sgf** [comment]
another  problem is when im query some field not in the data,it seems LiteDB will do full table scan ?
emm.

**Comment by kcsombrio** [comment]
Hi @sgf, the size difference is due to the indexing system. LiteDB uses SkippedLists as the indexing system, which generates a random sized linked pointer array. So if you recreate these same databases again with the same amount of records, you should get different sized datafiles

**Comment by sgf** [comment]
> Hi @sgf, the size difference is due to the indexing system. LiteDB uses SkippedLists as the indexing system, which generates a random sized linked pointer array. So if you recreate these same databases again with the same amount of records, you should get different sized datafiles

im just want to say,im open the db file,and its store the Field Name in there(every recored).

**Comment by sgf** [comment]
> > Hi @sgf, the size difference is due to the indexing system. LiteDB uses SkippedLists as the indexing system, which generates a random sized linked pointer array. So if you recreate these same databases again with the same amount of records, you should get different sized datafiles
> 
> im just want to say,im open the db file by notepad++ ,and its store the Field Name in there(every recored).

**Comment by kcsombrio** [comment]
Ok, yes, this is by design. The object is serialized into a document on Bson format, which records the name of each property. This is a feature so you have the flexibility to store a modified object within the same collection without having to change its structure.
