### ISSUE TITLE
How can I Serialize an IEnumerable<BsonDocument> to Json?

### ISSUE THREAD

**Issue by leavesgreen** [mbdavid/LiteDB#213]
Hi, everyone.
I do not want to define a new class. so I Deserialize a json string by this
`var res1 =JsonSerializer.Deserialize(s.Replace('\'','"'));
var col = db.GetCollection("aaa");
col.Insert(res1.AsDocument);
`
and it work fine. I can got the result count correctly. 
but when I want to get the result to json by 
`
var res3 = col.FindAll();
JsonSerializer.Serialize(res3);
`
and res3 is an IEnumerable<BsonDocument>, but the Serialize function need a BsonValue param. I learned the documents but find nothing about how to trans the IEnumerable<BsonDocument> to a Bson Value. so who can give me a help?

All I want is to save the json in LiteDB, and can get back to a Json string again. of course I may change the property during this process.

**Comment by mbdavid** [comment]
try:

```
var array = new BsonArray(col.FindAll().Select(x => x as BsonValue));
var json = JsonSerializer.Serialize(array);
```

**Comment by leavesgreen** [comment]
@mbdavid , it works! thanks you very much!
