### ISSUE TITLE
saving text removes white space and line breaks at the beginning and end of text

### ISSUE THREAD

**Issue by cl2raul66** [mbdavid/LiteDB#2132]
hello, I try to save a text string like this: " I am your master \n ", but when I recover it looks like this: "I am your master"

**Comment by cl2raul66** [comment]
How can I do that?

**Comment by kcsombrio** [comment]
Hi @cl2raul66, in your case, try setting the BsonMapper.Global.TrimWhitespace to false. It's default value is true. Please see more info at http://www.litedb.org/docs/object-mapping/
