### ISSUE TITLE
Count or Exists method wrong for ID field

### ISSUE THREAD

**Issue by taoqiping** [mbdavid/LiteDB#216]
I am trying to determined to use Update or Insert by using Count or Exists method to check if the document is existing or not. The key is ID field, I am not sure if there is bug in such scenario while it is correct when I use other field. 

you can see screen-shot, for document with ID 3166, I can get it by method FindByID, or Find from a list. but when I try to use Exists or Count, it fail always.
![screenshot - 2016_7_23 0_28_56](https://cloud.githubusercontent.com/assets/8456940/17063990/b5188daa-506c-11e6-83fe-7062e0daa7fc.png)

Code is simple as below:
` foreach (var msg in messages)
  {
            var isExisting = col.Exists(Query.EQ("ID",msg.ID));
            if (isExisting)
             {
                      col.Update(msg);
              }
             else
              {
                      col.Insert(msg);
               }
  }`

**Comment by mbdavid** [comment]
Hi @taoqiping, ID property (from class) are converted to `_id` document field. Try use: 
`Count(Query.EQ("_id", 3166))`
or use Linq
`Count(x => x.ID == 3166)`

**Comment by taoqiping** [comment]
yes, it works. but only property "ID" with the special process?

**Comment by mbdavid** [comment]
Yes, because all document must have an _id field. It's same syntax used in MongoDB: https://docs.mongodb.com/manual/reference/method/db.collection.insert/#id-field
