### ISSUE TITLE
Assembly Name change

### ISSUE THREAD

**Issue by bluekuen** [mbdavid/LiteDB#2170]
### Discussed in https://github.com/mbdavid/LiteDB/discussions/2168

<div type='discussions-op-text'>

<sup>Originally posted by **bluekuen** April  7, 2022</sup>
Hello together,

like the title says did my Type name change from DeviceSetMobile to DeviceSet.Mobile my Assembly Name to DeviceSet and now i got these Exceptions from all of my database classes which are stored:

LiteDB.LiteException: 'Type 'DeviceSetMobile.Models.BleDevice, DeviceSetMobile' not found in current domain (_type format is 'Type.FullName, AssemblyName').

Is there an simple and easy way to announce assembly name changes? 

I'm thankful for every answer!

Kind regards
bluekuen</div>

**Comment by mr-sven** [comment]
Hi, you can use the LiteDB studio to update the type ref in your entries. If you have it already in Prod you can use the statements in a migration function.

**Comment by bluekuen** [comment]
Hello, thanks for the answer! 
Yes its already in prod and i already tried it this way:

 var updateSQL = "UPDATE User SET _type = " +
     "REPLACE(_type, 'DeviceSetMobile.Models.BleDevice, DeviceSetMobile', 'DeviceSet.Mobile.Models.BleDevice, DeviceSet') " +
     "WHERE _type LIKE 'DeviceSetMobile.Models.BleDevice, DeviceSetMobile'";

 _database.Execute(updateSQL);

But it didn't work somehow. Am i doing it wrong?

Thanks in advance!

**Comment by mr-sven** [comment]
ok, it looks like you try to set the _type of the user, not the the type of entry of the users device list.
Can you paste a sample text output from LiteDB Studio?

**Comment by bluekuen** [comment]
There's just a zero:
![image](https://user-images.githubusercontent.com/35228746/162940759-68ec5fdd-0abd-4be9-8468-fdfaa244c4f6.png)

**Comment by mr-sven** [comment]
I mean a user object

**Comment by bluekuen** [comment]
Ok i see. But how am i able to update the Devices inside the User? if i try update User.Devices it would be the list right?
Also User.Devices can't be updated.

**Comment by mr-sven** [comment]
make a backup,
try something like:
`UPDATE User SET $.Devices[@._type = 'DeviceSetMobile.Models.BleDevice, DeviceSetMobile']._type = 'DeviceSet.Mobile.Models.BleDevice, DeviceSet'`

**Comment by bluekuen** [comment]
thanks so much for your help! 
I tried the command you provided but get following error:

Unexpected token `$` in position 17.

UPDATE User SET $.Devices[@._typ
-----------------^

Do i need to escape with an escape char?

**Comment by mr-sven** [comment]
maybe omit?
`UPDATE User SET Devices[@._type = 'DeviceSetMobile.Models.BleDevice, DeviceSetMobile']._type = 'DeviceSet.Mobile.Models.BleDevice, DeviceSet'`

**Comment by mr-sven** [comment]
hm, very tricky

**Comment by mr-sven** [comment]
maybe you can try convert it with a Untyped collection:
```csharp
using(var db = new LiteDatabase("mydb.db"))
{
    var col = db.GetCollection("User");
	
	foreach (var user in col.FindAll())
	{
		foreach (var device in user["Devices"])
		{
			if (device["_type"] == "DeviceSetMobile.Models.BleDevice, DeviceSetMobile")
			{
				device["_type"] = "DeviceSet.Mobile.Models.BleDevice, DeviceSet";
			}
		}
		col.Update(user);
	}
}

```

**Comment by mr-sven** [comment]
Untyped collection also not working?

**Comment by bluekuen** [comment]
Untyped collection did work! Thank you very very much! You saved my day!
