### ISSUE TITLE
why execute _disk.Close() after transaction commit(Complete)

### ISSUE THREAD

**Issue by speedb** [mbdavid/LiteDB#218]
hi dear:

    updated to the 2.0.0 - rc2, I found it always throw exception while I do GetIndexes() after EnsureIndex().

    step into the source code, I found that caused by transaction commit (line 67 in "DBEngine\Services\TransactionService.cs" file)

    ps: compared with last version( 2.0.0 -rc), It's written with _disk.unlock().

**Comment by speedb** [comment]
it's appeared in FileDiskService while StreamDiskService doing nothing in Close()

**Comment by mbdavid** [comment]
Hi @speedb, this new version use open mode as a concurrency control. So it´s ok close file after each operation. In StreamDisk implementation are complete "single user/no concurrency", so keeps stream open all the time.
I look source and found the bug - are missing "open transaction" here https://github.com/mbdavid/LiteDB/blob/master/LiteDB/DbEngine/DbEngine/Index.cs#L94
I will fix at today and add some unit tests to validate.

**Comment by speedb** [comment]
yes I see, thanks for your answer
