### ISSUE TITLE
about Min()

### ISSUE THREAD

**Issue by speedb** [mbdavid/LiteDB#220]
https://github.com/mbdavid/LiteDB/blob/master/LiteDB/DbEngine/DbEngine/Aggregate.cs#L12
<long> should be <BsonValue>？

**Comment by mbdavid** [comment]
Yes, it´s open database to access collection page/indexes references.

**Comment by speedb** [comment]
I means should be return a "long" type instead of BsonValue?

**Comment by mbdavid** [comment]
No, because collection didn't know which data type your ID class has. You can use Min to Date, Int, Guid, String, ... And if there is no document, LiteDB returns BsonValue.MinValue

**Comment by speedb** [comment]
but in source code, it appears as "long", not BsonValue, that's my question
https://github.com/mbdavid/LiteDB/blob/master/LiteDB/DbEngine/DbEngine/Aggregate.cs#L12

**Comment by mbdavid** [comment]
Oh, you right...  thanks.
