### ISSUE TITLE
Updating Sub document

### ISSUE THREAD

**Issue by anishpsla** [mbdavid/LiteDB#223]
I have no idea how to update a sub document in Lite DB. For example, I have a document like this one.

`{
    "name": "user1",
    "Addr": "Address",
    "service": [{
        "name": "Service1",
        "type": "Service type1"
    }, {
        "name": "service2",
        "type": "service type2"
    }]
}`

I want to add or remove services to the customer.  I have no idea how to do it.

**Comment by mbdavid** [comment]
Hi @anishpsla, you cannot access sub document only. You must read your document "User", insert/update "Services" and save "User" again. Something like this:

```
public class User
{
    public string Name { get; set; }
    public string Addr { get; set; }
    public List<Service> Service { get; set; }
}

public class Service
{
    public string Name { get; set; }
    public string Type { get; set; }
}

var u = users.FindById(123);

u.Services.Add(new Service { Name = "s1", Type = "t1" });

users.Update(u);
```

**Comment by anishpsla** [comment]
```javascript
            using (var db = new LiteDatabase(@"MyData.db"))
            {
                var CustomerTbl = db.GetCollection<Customer_model>("customer");
                var cus = CustomerTbl.FindById(cusid);
                cus.Service.Add(new CusService { Name = "BB", Type="Test"});
                CustomerTbl.Update(cus);
            }
```

Causing 

> NullReferenceException: Object reference not set to an instance of an object.

Error on line
 > cus.Service.Add(new CusService { Name = "BB", Type="Test"});

**Comment by mbdavid** [comment]
Post your `Customer_model` class to check if has an ID identifacation, and how you are inserting your customer.

**Comment by anishpsla** [comment]
Customer_mode class have id of type integer. Also 'cus' variable have data in it. the next line causing problem.

**Comment by mbdavid** [comment]
Can you post an gist unit test of this problem? I will need debug this code to know where problem is.

**Comment by anishpsla** [comment]
Thanks for your help. Finally, I find the solution. Here is the raw, code

```
using (var db = new LiteDatabase(@"MyData.db"))
            {
                var CustomerTbl = db.GetCollection<Customer_model>("customer");
                List<CusService> test = new List<CusService>();
                var ResultSet = CustomerTbl.Find(x => x.Id.Equals(23));
                foreach (var result in ResultSet)
                {
                    test = result.Service;
                }
                var test13 = new CusService { Name = "CA", Type = "123" };
                test.Add(test13);

                var CustomerInfo = new Customer_model
                {
                    Id=23,
                    Name = "asdfsd",
                    Addr = "sdfsd",
                    Service = test
                };
                CustomerTbl.Update(CustomerInfo);
            }
```
