### ISSUE TITLE
Query with EndsWith

### ISSUE THREAD

**Issue by bencz** [mbdavid/LiteDB#224]
Hi
It is not possible to run a query with "EndsWith"

```
var tmp = reg.Find(x => x.Name.EndsWith("P"));
tmp.ForEach(x => Console.WriteLine(x.Name));
```

**Comment by mbdavid** [comment]
Hi @bencz, because there is not index that catch EndsWith (I think in no one database). So, when you don't have an index (using in Find(predicate)) you need use a non-indexed query:

`var tmp = reg.FindAll().Where(x => x.Name.EndsWith("P"));`

**Comment by bencz** [comment]
Hi @mbdavid, thanks!
use the findall, if I have a 'table' with a lot of documents.... it's not a good idea...
I can do something different... just save the last chars of field name, and create a index in this field and query based in this field...

**Comment by mbdavid** [comment]
Yes, you can create a get only property with ends of name, index this property and quering using indexed query.

**Comment by bencz** [comment]
Thanks!
I did this!!
