### ISSUE TITLE
[BUG] Collection returns incorrect count when database loaded from memory stream

### ISSUE THREAD

**Issue by TrevorDArcyEvans** [mbdavid/LiteDB#2248]
**Version**
LiteDB commit 6d9ac6237ff8cae104a3c57a8de4ec55b4506e87 (June 15, 2022)

**Describe the bug**
Collection returns incorrect count when database loaded from memory stream

**Code to Reproduce**
```csharp
using LiteDB;
using System.Diagnostics;
using System.Text;

public static class Program
{
  public static void Main(string[] args)
  {
    const string DbName = "v5-test.db";

    var dbStr = File.ReadAllText(DbName);
    var strm = new MemoryStream(Encoding.ASCII.GetBytes(dbStr));
    using var db = new LiteDatabase(strm);

    // This works as expected
    //using var db = new LiteDatabase(DbName);

    var col1 = db.GetCollection("col1");
    var count = col1.Count();

    Debug.Assert(count == 3);
  }
}
```
[v5-test.zip](https://github.com/mbdavid/LiteDB/files/9952673/v5-test.zip)

**Expected behavior**
Collection count should be 3 but is 0

**Additional context**
see also #2247

**Comment by pjy612** [comment]
why not use File.ReadAllBytes ?

**Comment by TrevorDArcyEvans** [comment]
I'm trying to get LiteDB working in WebAssembly:
https://github.com/TrevorDArcyEvans/LiteDB.Studio.WebAssembly
https://github.com/TrevorDArcyEvans/LiteDB.Studio.WebAssembly/blob/855818616ae29bfb3510dfc5f23ee15cc90b0784/Pages/Index.razor.cs#L100

**Comment by JintaoXIAO** [comment]
is it ok to read text content from a binary file?
I think you should read this in binary format.

**Comment by TrevorDArcyEvans** [comment]
LiteDB loads correctly from the stream and even returns some correct information eg LiteDatabase.GetCollectionNames(), but some operations do not work eg LiteDatabase.DropCollection()

**Comment by pjy612** [comment]
> I'm trying to get LiteDB working in WebAssembly: https://github.com/TrevorDArcyEvans/LiteDB.Studio.WebAssembly https://github.com/TrevorDArcyEvans/LiteDB.Studio.WebAssembly/blob/855818616ae29bfb3510dfc5f23ee15cc90b0784/Pages/Index.razor.cs#L100

```
var dataBytes = await file.ArrayBufferAsync();
var strm = GenerateStreamFromBytes(dataBytes);


private static Stream GenerateStreamFromBytes(byte[] bytes)
  {
    return new MemoryStream(bytes);
  }
```

**Comment by TrevorDArcyEvans** [comment]
Thanks for the guidance.  It is now working as expected!
