### ISSUE TITLE
When will it be updated

### ISSUE THREAD

**Issue by xizhengchao** [mbdavid/LiteDB#2250]
When will litedb be updated

**Comment by 7702244** [comment]
I think the project is abandoned.

**Comment by kcsombrio** [comment]
Hi guys, the project is not abandoned, we are just working on multiple projects (personal and commercial projects), we keep looking at issues and working as we can. We are planning on coming back with more attention this season.

**Comment by vecalion** [comment]
@kcsombrio, I wonder if there are any updates regarding the plans that you can share with us? We all know the nature of open-source projects; we love working with LiteDB, but the number of critical issues and unaddressed PRs raises concerns among our team members. Feedback from the project owners might mitigate those concerns and help us better understand what's going on.
