### ISSUE TITLE
No unique exception code is thrown for certain exceptions

### ISSUE THREAD

**Issue by arcanelab** [mbdavid/LiteDB#2257]
Version: 5.0.12.

When trying to open an unencrypted database with a password in the connection string, I get the following exception: "This file is not encrypted". Unfortunately the exception is thrown with a generic code of 0, so I can't check for this particular use-case in the exception handler. Is there a particular reason why a dedicated error code was not added for this exception?

**Comment by ProKn1fe** [comment]
I thing no, author just forget about this part of code.
