### ISSUE TITLE
Collection using many different extended classes

### ISSUE THREAD

**Issue by emrys90** [mbdavid/LiteDB#226]
For example, I have an Item class and a WeaponItem class that extends Item. It has a couple extra fields in it that need to be saved as well. Is it possible to store this is one collection, and return the appropriate class instance based on which type of item it is? My current thoughts is I am going to have to have an ItemModel class that has every field in it for all classes, and then will instantiate a separate object based on that. I am hoping there's a better way I can do this though.

**Comment by mbdavid** [comment]
Hi @emrys90, yes, you can store all deriveded classes in some collections. Take a look in this unit test:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB.Tests/Tests/PolymorphicTest.cs

**Comment by emrys90** [comment]
Nice! Thank you!
