### ISSUE TITLE
Exception : Invalid transaction on top of stack

### ISSUE THREAD

**Issue by ldubrois** [mbdavid/LiteDB#228]
Hello,

I just started using your DB. Seems it is exactly what I was looking, simple, NoSQL.
I tried to use LiteDB in a windows service  with multiple threads accessing the DB.
The service is something similar to a job scheduler, and tasks are stored in the DB.

At the very beginning of the app when DB access (read or write) are done, I get the following exception :
```

Type : System.ArgumentException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
        Message : Invalid transaction on top of stack
        Source : LiteDB
        HelpLink :
        Data : None
        Additional Infos :
            ParamName : null

        StackTrace :
             at LiteDB.TransactionService.popTopTransaction(LiteTransaction trans)
             at LiteDB.TransactionService.Complete(LiteTransaction trans)
             at LiteDB.LiteTransaction.Commit()
             at LiteDB.LiteTransaction.Dispose()
             at LiteDB.DbEngine.<Find>d__9.System.IDisposable.Dispose()
             at LiteDB.DbEngine.<Find>d__9.MoveNext()
             at LiteDB.LiteCollection`1.<Find>d__34.MoveNext()
             at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
             at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
             at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
             at xxxxxxxxxxxxxxxxx
```

Is the LiteDatabase thread-safe ? Because I'm sharing the LiteDatabase instance on all threads.
Should I do differently ?

Thanks for your help.

Luc

**Comment by mbdavid** [comment]
Hi @ldubrois, no, it's not thread-safe. Reusing same LiteDatabase instance in different threads/tasks causes invalid states. Try use one instance per thread (LiteDB support multiple concurrency instances).

**Comment by ldubrois** [comment]
Thanks for your quick answer.
As a very quick fix on my issue, I've added a lock on the LiteDatabase to get it working.

I assume creating a new LiteDatabase instance per request will be too heavy, I will search a way to maintain a LiteDatabase instance per thread and dispose it nicely when the thread exit.

Thanks again.

**Comment by mbdavid** [comment]
It´s not heavy. LiteDatabase instance is just a simple layer of `DbEngine` class. Havy operation is initialize `BsonMapper`, so it´s importat to keep this in a single instance (by default, using BsonMapper.Global is single static instance).

If you have lots of read operation, you need lock them too. In this case, use multiple instances of LiteDatabase is better way. This current version keeps datafile always closed and open only when need execute an disk operation.

I had a old version with lock in all operations. But had some bugs and I gave up. Maybe for `2.1` release I try add this again.
