### ISSUE TITLE
Custom Exception Types

### ISSUE THREAD

**Issue by falahati** [mbdavid/LiteDB#229]
Please consider defining exception classes for better error handling. For example following exception arise when opening a v1.x database with v2.0 binaries. This is hard to catch except by comparing the error message as string which can be localized later.

https://github.com/mbdavid/LiteDB/blob/8902d0e31e82c3dc096fdd32c65ac843c96a58cb/LiteDB/DbEngine/Pages/BasePage.cs#L141

**Comment by mbdavid** [comment]
Hi @falahati, all LiteDB error throw a `LiteException` with a different Error Code. This exception, in particular, is the type of "never should happend" exceptions. If you are open an 1,x file in v2 the error should be another (https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Exceptions/LiteException.cs#L46). I will check why this not throwing...

**Comment by falahati** [comment]
I see,
well if it help to detect the problem I must say that I created database with LiteDB v1.0.4 and tried opening it with LiteDB 2.0.0-rc2 (both nuget versions) and that the exception in question is raised at "GetCollectionNames()" and "GetVersion()" methods. LiteDatabase constructor raises no exception tho.

**Comment by mbdavid** [comment]
LiteDatabase constructor has no datafile access. So, when first command runs, Header page will be loaded. I made some changes to detect beter old version.
