### ISSUE TITLE
[QUESTION] Where is NuGet v5.0.16?

### ISSUE THREAD

**Issue by nightroman** [mbdavid/LiteDB#2294]
The recent release https://github.com/mbdavid/LiteDB/releases/tag/v5.0.16 does not seem to have the corresponding NuGet package https://www.nuget.org/packages/LiteDB#versions-body-tab

**Comment by mbdavid** [comment]
Hi @nightroman, I get some problems with appvyon and signpath certificate when publishing in nuget. But now it's normalized!

**Comment by nightroman** [comment]
Thank you!
