### ISSUE TITLE
Not null constraint

### ISSUE THREAD

**Issue by emrys90** [mbdavid/LiteDB#230]
Is there anyway to mark a field as not allowing null/empty values?

**Comment by mbdavid** [comment]
Hi @emrys90, LiteDB has no schema validation. I think you can use native .NET DataAnnotations for that.

**Comment by emrys90** [comment]
Would you happen to know the performance hit of that offhand? Any chance of this becoming something that is supported, maybe a config setting on the database that does the data annotations validator?
