### ISSUE TITLE
[SUGGESTION] - EntityMapper Constructor/Object creation behavior

### ISSUE THREAD

**Issue by superahoy** [mbdavid/LiteDB#2304]
**Is your feature request related to a problem? Please describe.**
I am looking for better defined behavior for LiteDB object creation during deserialization. This corresponds to bugs #2298 and #2303.

**Describe the solution you'd like**
Update EntityMapper to support 3 types of constructors with the following behavior:

- Default Constructor

LiteDB creates new object by executing default constructor, the sets all object properties via the BsonMapper DeserializeObject method.

- Parameterized Constructor

LiteDB deserializes object properties and creates new object by executing parameterized constructor with the matching properties. Exception is raised if properties / constructor parameters cannot be fully matched. The object properties are NOT set a second time, the parameterized constructor is responsible for fully setting the object properties.

- Document Constructor

LiteDB executes a constructor function which accepts a single parameter, which is a BsonDocument. This method is responsible for creating and restoring the object based on the contents of the BsonDocument.

**Describe alternatives you've considered**
I have tried using the existing functionality and because BsonMapper.DeserializeObject appears to always be called, I run into issues where I need to modify the constructor behavior to avoid deserialization issues but cannot avoid this call.

**Additional context**

**Comment by pjy612** [comment]
maybe you need use
```
BsonMapper.Global.RegisterType
```
