### ISSUE TITLE
Performance for thousands of updates

### ISSUE THREAD

**Issue by emrys90** [mbdavid/LiteDB#231]
On average for thousands of updates I seem to be getting about 10 updates per millisecond. For example, doing an update of 6,781 objects takes about 674 milliseconds. Is this normal? Wondering if it's possible to get it any faster than this, or if I'm going to have to batch updates to do less per iteration. I'm using the Update(IEnumerable<T> documents) method to update all the objects.

**Comment by mbdavid** [comment]
Hi @emrys90, performance time has a lot of variables that can be analysed. Document size, CPU/Disk access, ..... But you are using the right way: Update(IEnumerable) do all operations in memory (or in disk if exceeds 5000 dirty pages) and then write all to disk.
You can turn off journal file to be faster, but you will loose crash write safe operation (use `journal=false` on connection string)

**Comment by emrys90** [comment]
Do you have any statistics for the amount of updates you can usually do in say one second or something? I'm just trying to figure out if this is a normal time, or if I am doing something that can be better optimized. In the end it doesn't matter too much, I wound up just putting that in a separate thread, but if I can get it any faster then great.

**Comment by mbdavid** [comment]
A long time ago I make this: https://github.com/mbdavid/LiteDB-Benchmark - It´s a benchmark to compare some simple operations using LiteDB (v0.9) with MongoDB. Off course that LiteDB is slower than Mongo, but not too much (using 10.000 documents). I removed results from site because It´s a old version of LiteDB, but you can clone and run to compare results.

**Comment by negue** [comment]
@emrys90 could you create a test or an example project ? Maybe something else is the problem (if there is one)
