### ISSUE TITLE
[QUESTION] Cannot delete using predicate

### ISSUE THREAD

**Issue by timheuer** [mbdavid/LiteDB#2319]
Tried to search issues and other people seem to have this working but I cannot.

```
public void DeletePackage(string identifier)
{
    var db = _database.GetCollection<ExtensionManifest>("packages");
    db.Delete(x => x.Identifier == identifier)
}
```

Error is
```
CS1660	Cannot convert lambda expression to type 'BsonValue' because it is not a delegate type
```

**Comment by mbdavid** [comment]
Hi @timheuer,

`Delete` method must be used with an `BsonValue` (accepts only `_id` value).

If you don't know the `_id` you can try `DeleteMany` with an expression (your expression is a valid expression).

Tip: if you have too many documents in this collection or query/delete/update by this identifier, create an index on this field and you will not loose performance..

**Comment by timheuer** [comment]
This is excellent @mbdavid thank you.
