### ISSUE TITLE
float/Single is not a valid BSON data type

### ISSUE THREAD

**Issue by wleev** [mbdavid/LiteDB#232]
Trying to wrap a float/Single in a BsonValue will throw an InvalidCastException. Double seems to work, Decimal throws as well.

Using V2.0.0-rc2 in a UWP app.

Edit: Just read docs. Is there a reason you're not supporting them?

**Comment by mbdavid** [comment]
Hi @wleev, float/decimal are not native BSON data type (http://bsonspec.org/spec.html). You must use `Double` type only. But how are you using? Are you using `BsonDocument` or mapping with `BsonMapper`? `BsonMapper` do this conversion automatic.

**Comment by wleev** [comment]
I'm using BsonDocument, but I've already switched to using double.

I also did a quick implementation of my own for float and decimal. It works but totally disregards the BSON spec. I'll just use a custom type for representing financial data.

Thanks.
