### ISSUE TITLE
[QUESTION] AOT Compilation support for .NET 7.0+ and newer

### ISSUE THREAD

**Issue by GiaNTizmO** [mbdavid/LiteDB#2338]
At the moment, AOT compilation is not supported for LiteDB (Linq expressions not support compilation in AOT builds, and reflections, as I understand it, are not supported).
Do you plan to somehow launch AOT support at least at an experimental level?

**Comment by mbdavid** [comment]
Hi @GiaNTizmO,

Current v5.x will have no more major updates, only security issues. I'm working in months on new version with no LINQ expression needs for BsonExpression resolution. Also, Reflection used in LiteDB do not use "Emit" to generate code. So, I think when this new version came out will be possible compile in AOT support.

**Comment by GiaNTizmO** [comment]
> Hi @GiaNTizmO,
> 
> Current v5.x will have no more major updates, only security issues. I'm working in months on new version with no LINQ expression needs for BsonExpression resolution. Also, Reflection used in LiteDB do not use "Emit" to generate code. So, I think when this new version came out will be possible compile in AOT support.

Okay. Thank you and all contributors for this awesome db!

**Comment by Pulse-Git** [comment]
@mbdavid is there any ETA planned?

**Comment by vvolkgang** [comment]
@mbdavid hey! 👋🏾 Any recent developments on the AOT front?

**Comment by WCKYWCKF** [comment]
@mbdavid Hey! How's the AOT progressing?
