### ISSUE TITLE
[QUESTION] Export CRUD statements?

### ISSUE THREAD

**Issue by Amplificator** [mbdavid/LiteDB#2350]
Is it possible to save CRUD statements as a string, json or something else, for then to execute the actual command, maybe using .Execute(), on another machine?

I've been tinkering with the idea of building a server that handles the actual database and for clients to send commands and get updates from the server.

My idea was to have all clients export their CRUD statements as a string, json or something else, send it to the server which then does the actual processing and later update the clients with a status message.

I'm completely new to networking projects like these, but the above is the gist of what I want to do. I'm looking into NetworkStream and Sockets in general.

So my question is, besides being able to export/save CRUD statements, if there would be a better way to expose the database to several clients at once?

**Comment by JKamsker** [comment]
Originally, this seems to be the plan; it would be possible. You can give it SQL strings, and it returns a serializable BSON document.

But actually hooking it up to a wire protocol... well, I am sure you can do that without changing anything in LiteDB itself.
