### ISSUE TITLE
[SUGGESTION] .NET 6 LTS builds - Previous .NET are now End of Life

### ISSUE THREAD

**Issue by CastleSoft** [mbdavid/LiteDB#2353]
Can the repository be switch to current/supported .NET versions ?

All pre .NET 6 are now End of Life.

<img width="1368" alt="Screenshot 2023-08-04 at 12 34 40 pm" src="https://github.com/mbdavid/LiteDB/assets/740215/1c5c6f25-f115-44fa-9960-19fd3c280b04">

**Comment by JKamsker** [comment]
As long as the library doesn't need newer dependencies, no. You can use LiteDB just fine even with .NET 8 without any problems.
