### ISSUE TITLE
Mapping sub keys to class fields.

### ISSUE THREAD

**Issue by sim1986** [mbdavid/LiteDB#237]
Hi i am trying to map a JSON property as a key using

.DbRef(x => x.Properties.Name, "properties.name");

My json object looks like the following 

{
    "type": "Feature",
    "properties": {
      "name": "Shop 1",
      "show_on_map": false,
      "address": "123 Fake Street"
}

How can i map sub keys inside a JSON object?

Thank you

**Comment by mbdavid** [comment]
DbRef is used to map external document as reference. First parameter is property that maps another document and second parameter is collection reference name: https://github.com/mbdavid/LiteDB/wiki/DbRef

You can map entity (or subclass) using BsonMapper.Global.Entity<ClassName>() where ClassName can be you entity or any subclass

**Comment by sim1986** [comment]
Hi mbdavid,

Thank you for the quick reply.

I am still having issues with retrieving data from the collection. I'm not even sure the collection is being populated. I have checked my LiteDb file and it is populated with the correct data but I cannot seem to get any further. 

Do you have an example anywhere of how to get data from a external JSON file and query the LiteDb database file?

Thank you

**Comment by mbdavid** [comment]
Hi @sim1986, did you try shell tool? In shell you can do any command use command line. You can check if you data is in collection (I made this tools to check this). You can run "bulk" insert too (based on a .json file too). 
Run LiteDB.Shell.exe:

```
open mydb.db
db.mycol.bulk external_file.json
db.mycol.find
```

here an example of "external_file.json"
```
[
   { _id:1, name:"Jose" },
   { _id:2, name:"Carlos" },
   { _id:3, name:"Marcos" }
]
```

- Must by an array
- If not found `_id` field in each document, an auto id will be created.
