### ISSUE TITLE
Using MongoDB ObjectId as id

### ISSUE THREAD

**Issue by MarkioE** [mbdavid/LiteDB#24]
Hi Mauricio,

Thanks for this library, I'm enjoying using it at the moment. We're looking at using MongoDB as our main database system, while also using another embedded solution (maybe LiteDB) for the desktop version of our software.

Do you think it's possible for LiteDB to use the same ObjectId as MongoDB, so that we can re-use one C# class for both storage types?

Thanks,
Mark.

**Comment by mbdavid** [comment]
Hey Mark, thanks for using LiteDB. It's really nice to know.... :smile:

LiteDB.ObjectId is almost the same class than MongoDB.Bson.ObjectId. To use MongoDB.Bson.ObjectId as you Id, just write a small custom serialize/deserialize functions to do this:

```C#
LiteDB.BsonMapper.Global.RegisterType<MongoDB.Bson.ObjectId>
(
    (oid) => new LiteDB.ObjectId(oid.ToByteArray()),
    (bson) => new MongoDB.Bson.ObjectId(bson.AsObjectId.ToByteArray())
);
```
