### ISSUE TITLE
Compilation errords

### ISSUE THREAD

**Issue by wvdvegt** [mbdavid/LiteDB#241]
Hi

just cloned the repo to see how this library works, but I'm having some problems with compiling the **Universal10** project.

First I got a load of errors that types like string where not defined. 
after updating the 
**Microsoft.NETCore.UniversalWindowsPlatform nuGet package** 
to v5.2.2. these where gone. 

The only error left in the **Universal10** project is:

```
Error   CS0246  The type or namespace name '**NameValueCollection**' could not be found (are you missing a using directive or an assembly reference?)   
LiteDB.Platform.Universal10 LitePlatformWindowsStore.cs 60
```

And some issues with the Android project not being able to see the correct SDK (my problem I guess).

Any suggestions?
any clies

**Comment by mbdavid** [comment]
Hi @wvdvegt, about android, just change sdk version to a most recent version that your vs has installed.

About NameValueCollection in Universal10 it's strange, because here compile fine. To quick test, just removed this part. @negue, do you have any idea?
