### ISSUE TITLE
Reduce file size of the database file

### ISSUE THREAD

**Issue by khoaho** [mbdavid/LiteDB#242]
Hi,

Can we reduce the file size of the output database? I see it is more than double of its JSON file.

Thank you.

**Comment by mbdavid** [comment]
Hi, LiteDB can use much more space than a plain json file. LiteDB store documents in pages, keeping avaiable space reserved when you need update a document and keep in same page. LiteDB creates indexes (at least ID index) that consume disk space too. So, it's dificult to compare json file with LiteDB datafile.

**Comment by khoaho** [comment]
Can we have a new feature for a compressed LiteDB that can decompress and compress on the fly (with the fastest and low CPU zip compressor)?

`LiteCollection<T>.Insert(T document)` will compress the document and store to database file.
`LiteCollection<T>.FindById(BsonValue id)` will decompress the document and return to object type T.

This "compress" feature will be an option to turn on or off.

**Comment by mbdavid** [comment]
Yes, can be used compress stream when writing on disk. If you want try, change this 

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/DbEngine/Pages/DataPage.cs#L20

To a number near PAGE_AVAILABLE_BYTES (like PAGE_AVAILABLE_BYTES - 300). This will reduce a lot your datafile, but if you need update documents can be cause a lot of extension pages (which is slow to access after)

**Comment by mbdavid** [comment]
I will reference this isse with #20 New Features

**Comment by khoaho** [comment]
The file size does not change whenever I change the DATA_RESERVED_BYTES to be smaller or bigger.

DATA_RESERVED_BYTES = PAGE_AVAILABLE_BYTES / x (x is any number)
