### ISSUE TITLE
[QUESTION] Does LiteDB 5 support .NET 8 Ahead-of-Time Compilation?

### ISSUE THREAD

**Issue by yimengfan** [mbdavid/LiteDB#2428]

**Comment by mbdavid** [comment]
No, becasue v5 needs `Expressions` to resolve `BsonExpression`. Mas a proxima versão já está previsto isso, pois não há mais a dependencia com `Expressions`:

https://github.com/mbdavid/LiteDB/blob/dev/src/LiteDB/Expression/BsonExpression.cs
