### ISSUE TITLE
How to select and then remove n rows from collection

### ISSUE THREAD

**Issue by takaaptech** [mbdavid/LiteDB#243]
Hi there,
I am newbie here. I want to select and then remove n rows (random or by created time) from collection? How to do this?
Thank you!

**Comment by mbdavid** [comment]
Hi @takaaptech, delete command from collection can be used with document _id or any `Query`. There is no needs to select before delete.

```C#
var col = db.GetCollection<YourClass>("collection");

col.Delete(x => x.Created < DateTime.Now);
```

**Comment by takaaptech** [comment]
Hi @mbdavid, Thanks for your quickly answer! In my case, i have a collection with have 10.000 rows. Each time, i need to select exactly 20 rows for processing and then delete them from collection. 
For now, i am using this:

            var data_return = new List<RowClass>();
            using (LiteDatabase db = new LiteDatabase(@"db"))
            {
                // Get a collection (or create, if doesn't exist)
                var col = db.GetCollection<RowClass>("Collection");
                var data_list = col.Find(Query.All(), 0, 20);

                foreach (var row in data_list) 
                {
                    col.Delete(row.Id);
                    data_return.Add(row);
                }
                db.Dispose();
            }
            return data_return;

Is this ok or we can using something better?

**Comment by mbdavid** [comment]
I recommend to you transform your data_list in an `List<T>` before loop.

**Comment by sanju-singh** [comment]
> I recommend to you transform your data_list in an `List<T>` before loop.

@mbdavid , could you please explain the reason behind it?
