### ISSUE TITLE
A strange problem with nesting class

### ISSUE THREAD

**Issue by lidanger** [mbdavid/LiteDB#244]
**Test environment:**
LiteDB Version: 2.0
.Net Framework:4.0
Operating System:Windows 10.0.10586 x64

**The test program like this:**

	using Modbus.Utility;
	using System;
	using System.Collections.Generic;
	using System.Diagnostics;
	using System.Linq;
	using System.Text;
	using System.Threading;

	namespace Test2
	{
		class Program
		{
			static log4net.ILog logger;

			static void Main(string[] args)
			{
				log4net.Config.XmlConfigurator.Configure(new System.IO.FileInfo("log4net.config"));

				logger = log4net.LogManager.GetLogger("main");

				TestLiteDb2();

				Console.ReadLine();
			}

			public class Person
			{
				public string Id { get; set; }
				public string Name { get; set; }
				public int Age { get; set; }
				public int Sex { get; set; }

				public Person()
				{
					Id = Guid.NewGuid().ToString("N");
				}
			}

			static void TestLiteDb2()
			{
				using (var conn = new LiteDB.LiteDatabase("test.db"))
				{
					var col = conn.GetCollection<Person>("p2");
					col.Insert(new Person
					{
						Age = 20,
						Name = "adfas",
						Sex = 1
					});
				}

				using (var conn = new LiteDB.LiteDatabase("test.db"))
				{
					var col = conn.GetCollection<Person>("p2");
					var ps = col.Find(p => p.Age == 20);
					foreach (var p in ps)
					{
						logger.InfoFormat("读取信息，姓名:{0}\t年龄:{1}\t性别:{2}", p.Name, p.Age,
							p.Sex == 0 ? "女" : "男");
					}
				}
			}
		}
	}

**And it gives an exception like this:**

LiteDB.LiteException: Failed to create instance for type 'Test2.Program+Person' from assembly 'Test2.Program+Person, Test2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Checks if the class has a public constructor with no parameters
   在 LiteDB.Reflection.CreateInstance(Type type)
   在 LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   在 LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
   在 LiteDB.LiteCollection`1.<Find>d__34.MoveNext()
   在 Test2.Program.TestLiteDb2() 位置 E:\DJWryWater\代码\Test2\Program.cs:行号 91
   在 Test2.Program.Main(String[] args) 位置 E:\DJWryWater\代码\Test2\Program.cs:行号 48
   在 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   在 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   在 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

**Non nesting class performs OK.**

**Comment by mbdavid** [comment]
Yes, classes must be non nested. LiteDB (in this version) used Reflection.Emit that can initialize this kind of class.
