### ISSUE TITLE
Can I ask a concurrency question?

### ISSUE THREAD

**Issue by lidanger** [mbdavid/LiteDB#245]
I found LiteDB supports multiple connections on same data file,but it seems not perfect.
The test program like this:

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading;

namespace Test2
{
    public class Person
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public int Sex { get; set; }
    }

    class Program
    {
        static log4net.ILog logger;

        static void Main(string[] args)
        {
            AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;

            log4net.Config.XmlConfigurator.Configure(new System.IO.FileInfo("log4net.config"));

            logger = log4net.LogManager.GetLogger("main");

            TestLiteDb();

            Console.ReadLine();
        }

        private static void CurrentDomain_UnhandledException(object sender,
            UnhandledExceptionEventArgs e)
        {
            System.IO.File.AppendAllText("exception.log",
                string.Format("未知异常{0}\r\n", e.ExceptionObject));
            running = false;
        }

        static void TestLiteDb()
        {
            running = true;

            for (int i = 0; i < 5; i++)
            {
                Thread thread = new Thread(insertWork);
                thread.Start();
            }
            for (int i = 0; i < 5; i++)
            {
                Thread thread = new Thread(readWork);
                thread.Start();
            }

            DateTime begin = DateTime.Now;
            while (running)
            {
                if (DateTime.Now >= begin.AddMinutes(10))
                {
                    running = false;
                    break;
                }
            }
        }

        static bool running;

        static void insertWork()
        {
            logger.Info("创建存储线程成功");

            var watch = new Stopwatch();
            int nCount = 0;
            Random rand = new Random(DateTime.Now.Millisecond);

            while (running)
            {
                watch.Start();

                using (var conn = new LiteDB.LiteDatabase("test2.db"))
                {
                    var col = conn.GetCollection<Person>("china");
                    var p = new Person
                    {
                        Name = "张工" + rand.Next().ToString(),
                        Age = (int)(rand.NextDouble() * 70),
                        Sex = rand.Next() % 2
                    };
                    col.Insert(p);
                    logger.InfoFormat("存储信息，姓名:{0}\t年龄:{1}\t性别:{2}", p.Name, p.Age,
                                p.Sex == 0 ? "女" : "男");
                }

                watch.Stop();
                nCount++;

                Thread.Sleep(1000);
            }

            logger.InfoFormat("写操作平均用时{0}毫秒", watch.ElapsedMilliseconds / nCount);
        }

        static void readWork()
        {
            logger.Info("创建读取线程成功");

            var watch = new Stopwatch();
            int nCount = 0;
            Random rand = new Random(DateTime.Now.Millisecond);

            while (running)
            {
                watch.Start();

                using (var conn = new LiteDB.LiteDatabase("test2.db"))
                {
                    var col = conn.GetCollection<Person>("china");
                    var ps = col.Find(p => p.Age == (int)(rand.NextDouble() * 70));
                    if (ps != null)
                    {
                        foreach (var p in ps)
                        {
                            logger.InfoFormat("读取信息，姓名:{0}\t年龄:{1}\t性别:{2}", p.Name,
                                p.Age, p.Sex == 0 ? "女" : "男");
                        }
                    }

                    watch.Stop();
                    nCount++;

                    Thread.Sleep(1000);
                }
            }

            logger.InfoFormat("读操作平均用时{0}毫秒", watch.ElapsedMilliseconds / nCount);
        }
    }
}
```

After running about one minute, a timeout exception is throwed.
So is there any application scenarios?

**Comment by lidanger** [comment]
Yes,it's my fault.Thank you!

**Comment by lidanger** [comment]
I modify then code,but the program still gives exception sometimes.

The modified code:

		static void TestLiteDb()
	{
		using (var conn = new LiteDB.LiteDatabase("text2.db"))
		{
			var col = conn.GetCollection<Person>("china");
			col.Insert(new Person
			{
				Name = "张工松",
				Age = 43,
				Sex = 1
			});
		}

		running = true;

		for (int i = 0; i < 5; i++)
		{
			Thread thread = new Thread(insertWork);
			thread.Start();
		}
		for (int i = 0; i < 5; i++)
		{
			Thread thread = new Thread(readWork);
			thread.Start();
		}

		DateTime begin = DateTime.Now;
		while (running)
		{
			if (DateTime.Now >= begin.AddHours(1))
			{
				running = false;
				break;
			}

			Thread.Sleep(100);
		}
	}

	static bool running;

	static void insertWork()
	{
		logger.Info("创建存储线程成功");

		var watch = new Stopwatch();
		int nCount = 0;
		Random rand = new Random(DateTime.Now.Millisecond);

		while (running)
		{
			var p = new Person
			{
				Name = "张工" + rand.Next().ToString(),
				Age = (int)(rand.NextDouble() * 70),
				Sex = rand.Next() % 2
			};

			watch.Start();

			using (var conn = new LiteDB.LiteDatabase("test2.db"))
			{
				var col = conn.GetCollection<Person>("china");

				col.Insert(p);
			}

			watch.Stop();
			nCount++;

			logger.InfoFormat("存储信息，姓名:{0}\t年龄:{1}\t性别:{2}", p.Name, p.Age,
				p.Sex == 0 ? "女" : "男");

			Thread.Sleep(1000);
		}

		logger.InfoFormat("写操作平均用时{0}毫秒", watch.ElapsedMilliseconds / nCount);
	}

	static void readWork()
	{
		logger.Info("创建读取线程成功");

		var watch = new Stopwatch();
		int nCount = 0;
		Random rand = new Random(DateTime.Now.Millisecond);

		while (running)
		{
			var list = new List<Person>();

			watch.Start();

			using (var conn = new LiteDB.LiteDatabase("test2.db"))
			{
				var col = conn.GetCollection<Person>("china");
				var ps = col.Find(p => p.Age == (int)(rand.NextDouble() * 70));
				if (ps != null)
				{
					list.AddRange(ps);
				}
			}

			watch.Stop();
			nCount++;

			foreach (var p in list)
			{
				logger.InfoFormat("读取信息，姓名:{0}\t年龄:{1}\t性别:{2}", p.Name,
					p.Age, p.Sex == 0 ? "女" : "男");
			}

			Thread.Sleep(1000);
		}

		logger.InfoFormat("读操作平均用时{0}毫秒", watch.ElapsedMilliseconds / nCount);
	}

**Comment by mbdavid** [comment]
You exception is about timeout? I will made a unit test to check this.

**Comment by lidanger** [comment]
Timeout and deserialize failure.

**Comment by mbdavid** [comment]
Hi @lidanger, v3 was released and now support multi-thread in a single LiteDatabase instance.
