### ISSUE TITLE
Is LiteDB still being maintained?

### ISSUE THREAD

**Issue by superware** [mbdavid/LiteDB#2478]
In light of recent critical issues and repository activity, is LiteDB still being maintained?

**Comment by HEIC-to-JPEG-Dev** [comment]
I believe so, it had a new release in Feb this year

**Comment by ensemblebd** [comment]
Personally, I have had nothing but problems with this library. 
Specifically the "shared" mode and asynchronous code. 
It's like balancing a **single** hair on a pin needle, and has lead to complete application deadlocks (try operating this lib in a Quartz background job), constant random runtime errors (disposed??? what disposed it?), and unreliable operation execution timing (try deleting everything, and reinserting everything - duplicate Id's).
The error codes are generic and unhelpful. And there's no documentation to figure out "why" something isn't working.
It's madness. 

I really want to love this product. But yeah, I had the same question. 
Who's in charge of bugs around here anway? Sheesh. 658 open issues is notable to say the least.

Personally I've had far more success with Lucene.Net, highly reliable for at least 5 years so far for me. 
But Lucene.net is very hard to work with when you're new to it or need advanced "flow patterns" (zero Linq options).

**Comment by superware** [comment]
It's natural for every open source project to have an instability phase, the issue with LiteDB is that this phase takes too long. I hope @mbdavid will get back to this (and the many PRs) or at least find some other coordinator so the truly wonderful potential will not go to waste.

**Comment by HEIC-to-JPEG-Dev** [comment]
I’ve not found any open source projects, even large company funded ones, that have good documentation or fix the PR’s efficiently. I recently used AvaloniaUI, had an issue, got told to look elsewhere. This project is great, but lacks documentation and has bugs that stopped me using it.

I think the problem, specifically with this repository, besides the original developer had to re-prioritise other life scenarios, is that it got to a popular and cool state, then, instead of focusing on making it great, they added stuff to it like sql syntax

**Comment by nantianliao** [comment]
Actually, we can try using sqlite.

**Comment by sgf** [comment]
If the author is short of money, I think donations to the project can be opened.

**Comment by almonie** [comment]
I think the project is all but dead. The last two releases are bug-ridden and encryption weaknesses have not been fixed for years. It's not usable in any serious project. It need a quick change of direction with more than one person looking after it. @mbdavid has done a great job getting it this far, but it needs support from more than him now to move it forward.
There is nothing else like it for C#, and I hope it can survive, but I can't wait on it any longer. I'll be moving all my code to a SQLite version with encryption

**Comment by JKamsker** [comment]
The bug has been fixed and released in [v5.0.20](https://github.com/mbdavid/LiteDB/releases/tag/v5.0.20)
