### ISSUE TITLE
Alternative to Generics methods

### ISSUE THREAD

**Issue by aletfa** [mbdavid/LiteDB#248]
Hello, will be nice a custom EntityBuilder without a generic type.
`new EntityBuilder(entity.GetType())`
this little improvement open the door to a lot of custom implentations

for example

```
class Pizza
{
     [MyCustomAndAllPurposeIdAttribute]
     public Guid ID { get; set; }
}
```

if all methods isn't generics i can read my attribute and call all appropriate methods from the builder.
ex: 

```
foreach property... in ...
if property has atrribute
    mapper.Id(property) (without T)
```

**Comment by aletfa** [comment]
Reading source code i can resolve with a custom BsonMapper.
But no interfaces are defined on this class ad implementation contains a lot of private ed internal methods. So i can't creare my BsonMapper because i can't access to the private collection _mapper.

No way :(
Please make LiteDB a little more open.

**Comment by mbdavid** [comment]
Hi @aletfa, is on plans has a custom IBsonMapper to implement. It´s not a easy thing because some operation (like DbRef) are implemented inside BsonMapper. This is an old resquest because .NET mapper is a too hard implement for all possible things. Json.net has a great mapping that will be possible to use

**Comment by aletfa** [comment]
I see.
First step can be to change items visibility from internal to public.
Next, if the IBsonMapper it's hard to extract, you can change the BsonMapper class. Mark methods that can be replaced as virtual.

This because if i add your attributes i become dependent to this tecnology. Attributes should be external and not related to LiteDB's assemblies.

TY for the answer. Nice project if i can i will contribute.

**Comment by mbdavid** [comment]
Hi @aletfa, I change the way how BsonMapper works and now are much more flexible. It's possible to override only how get properties, how setup each property. It's ease to use your custom attributes. Take a look on this v3-beta that can be helps you.
