### ISSUE TITLE
[BUG] Use EnterTransaction() before EnterLock

### ISSUE THREAD

**Issue by 390620652** [mbdavid/LiteDB#2484]
**Version**
5.019/OS/.NET 8. **(REQUIRED)**

**Describe the bug**
When I call Upsert function in two thread, this exception might occur occasionally.

 ---> LiteDB.LiteException: Use EnterTransaction() before EnterLock(name)
   at LiteDB.Engine.EngineState.Validate()
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.LiteCollection`1.Upsert(T entity)

**Comment by JKamsker** [comment]
Could you please provide a small repro?

**Comment by JKamsker** [comment]
The bug should have been resolved in v5.0.20
