### ISSUE TITLE
[BUG] At least for now, please do not update to 5.0.18 or 5.0.19. These two versions have more bugs.Keep Use Version -5.0.17 until Author Fix that

### ISSUE THREAD

**Issue by sgf** [mbdavid/LiteDB#2485]
At least for now, please do not update to 5.0.18 or 5.0.19. These two versions have more bugs.
After trying it once and having problems, I rolled back to 5.0.17.

**Comment by alexbereznikov** [comment]
There are already some pull requests for the most important issues

**Comment by JKamsker** [comment]
The bug has been resolved in v5.0.20
