### ISSUE TITLE
Max depth of 20 inner classes

### ISSUE THREAD

**Issue by haricharan123** [mbdavid/LiteDB#250]
Hi David,

I was playing around with LiteDb, is there any way to extend the Max depth of inner classes.

btw. nice fun project.Cheers

**Comment by mbdavid** [comment]
Hi @haricharan123, is you class has more than 20 inner objects? This limit was implemented to avoid circular references. Is not that case?

At now, there is no way to change this value, only changing in LiteDB source: https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Serializer/Mapper/BsonMapper.cs#L22
