### ISSUE TITLE
Make all internal Task SyncContext agnostic

### ISSUE THREAD

**Issue by pictos** [mbdavid/LiteDB#2505]
Raised on #2447, the long running task is sensitive to `SyncronizationContext`, that's devs can force that code execute inside the `SyncronizationContext`, and probably isn't what we want.

So in order to fix that we need to make sure our tasks will run under the `TaskScheduler.Default`.

The linked PR is one example, but we should investigate on our code base more places where we may have this issue.

**Comment by alexbereznikov** [comment]
@pictos Probably this issue should be closed due to #2515
