### ISSUE TITLE
Failing to serialize (or deserialize) System.Collections.Generic.KeyValuePair

### ISSUE THREAD

**Issue by yetanotherchris** [mbdavid/LiteDB#251]
I'm trying to save a `List<KeyValuePair<K,V>>` in a class, but noticed that it doesn't seem to be saving the values, or it maybe isn't reading them back - I'm not sure which direction the problem is but I'm getting null keys and values.

This is with RC2 of version 2. Does the serializer support KeyValuePairs, or is there a setting I'm missing?

Thanks

**Comment by yetanotherchris** [comment]
Also `TimeSpan` doesn't serialize/deserialize. Is there a place I can add support for this to?

**Comment by yetanotherchris** [comment]
I guess this solves the Timespan issue:

            BsonMapper.Global.RegisterType<TimeSpan>
            (
                serialize: (timeSpan) => timeSpan.ToString(),
                deserialize: (stringValue) => TimeSpan.Parse(stringValue)
            );

For KeyValuePair I've used a custom class instead - should it support the type?

**Comment by mbdavid** [comment]
Hi @yetanotherchris, there is no build-in `KeyValuePair` or `Timespan` implemented. But this classes are very common, so I will add a custom mapper for both. Will be avaiable in next release
