### ISSUE TITLE
[QUESTION] Save :memory: to disk?

### ISSUE THREAD

**Issue by lxman** [mbdavid/LiteDB#2516]
My desire is to use LiteDB as an in-memory DB so that I may have the advantage in performance. However when my app shuts down I would like to save. Then when the app starts, reload from disk and operate in memory from there.

I am using the latest v5.

I feel like there is a simple way to do this. I just can't seem to find an explicit example.

Could you provide some guidance on how to achieve this?

**Comment by JKamsker** [comment]
You can use memorystream and save that to disk.

**Comment by lxman** [comment]
Thank you! That works.
