### ISSUE TITLE
diskdump command raises exception

### ISSUE THREAD

**Issue by falahati** [mbdavid/LiteDB#253]
Hey,

Well I don't know about the version 1.x but in version 2.0 when trying to use LiteDatabase.Run("diskdump"), it raises a "System.NullReferenceException" exception at PageBase.ReadPage() method.

I believe that return value of this command should be a string that can be used to be imported later on. Am I right? I mean for migration, etc.

**Comment by falahati** [comment]
seems similar to #249

**Comment by mbdavid** [comment]
Hi @falahati, can be a bug on diskdump. But, diskdump are for for export/import data. DiskDump are dump data pages do output, it's just to debug/analyse datafile. To DUMP you must use LiteShell, a tool included in github/releases

**Comment by falahati** [comment]
I see; well then I need to browse the source code of main shell. Nonetheless, I believe this is still a bug.

**Comment by falahati** [comment]
Should be closed
