### ISSUE TITLE
[BUG] iterating over an  IEnumerable<LiteFileInfo<TFileId>> errors out on the second element if the DB is opened in shared mode

### ISSUE THREAD

**Issue by ssteiner** [mbdavid/LiteDB#2534]
For a test, I changed the connection mode for LiteDb from exclusive to shared. And then, operations on files started erroring out.

the code I'm using looks like this:

```
var fs = db.GetStorage<string>("audioFiles");
var files = fs.Find(u => u.Id.StartsWith(path));
foreach (var file in files)
{ // do something with file
}
```

this works fine if the connection mode is direct. If you then change the connection mode to shared, It fails when there's multiple files (at least two) - the first iteration works, on the second iteration gets you a `LiteException `with message 

> This engine instance already disposed

If you get a List instead of an Enumerable (`var files = fs.Find(u => u.Id.StartsWith(path)).ToList();`) it works even in shared mode.

I would expect the iteration to work in shared mode, too.

LiteDB version is 5.0.21 on .NET 8.0.7 on W11 Pro 2023H2

**Comment by dethknite** [comment]
This does not seem like a bug. In the example, the code is iterating through a files collection in the foreach that can be modified during iteration (especially in shared mode where other instances can write to the db). Anytime one wishes to iterate through a collection, it should be cast to an innumerable that will not be modified (such as a list or array).

It is not guaranteed to work in direct mode without casting either (though less likely to hit the collection was modified exception). Shared mode has a lot of async plumbing.

A way to see it clearer perhaps is this
```
var fs = db.GetStorage<string>("audioFiles");
foreach (var file in fs.Find(u => u.Id.StartsWith(path))
{ 
// 1st iteration there could be 30 files...
// ....
// 10th iteration it could have changed to 32 files... the loop processing is now in no man's land
}
```

You are correct in your solution.

**Comment by Joy-less** [comment]
I can confirm, this is a really intriguing issue.

The following code gives you an error:
```cs
using LiteDatabase Database = new(new ConnectionString() {
    Filename = "Database.db",
    Connection = ConnectionType.Shared,
});
ILiteCollection<BsonDocument> Accounts = Database.GetCollection("Accounts");
foreach (BsonDocument Document in Accounts.FindAll()) {
    Accounts.Update(Document);
}
GD.Print("done");
```
```
void LiteDB.Engine.EngineState.Validate(): LiteDB.LiteException: This engine instance already disposed.
```

But you can remove the error by doing any of the following:
- Replace `Accounts.FindAll()` with `Accounts.FindAll().ToList()`
- Replace `Connection = ConnectionType.Shared` with `Connection = ConnectionType.Direct`
- Remove `Accounts.Update(Document);`
