### ISSUE TITLE
[QUESTION] - Starting a new project using LiteDB

### ISSUE THREAD

**Issue by rmszc81** [mbdavid/LiteDB#2539]
Hello @mbdavid,

It's been some years that I had some interesting talks with you. Last time, you shared to me about faturin, remember? Well, maybe not, you're a very busy guy and this was quite long ago, but it's ok, understandable.

Still, I'm coming back to you for one very important question:

"I'm planning to start a new project of my own (again), using LiteDB (again). What do you say about that?"

I'm asking this for one reason: you mentioned that the future of LiteDB is uncertain AND you're not sure if LiteDB will be maintained in the long term.

Please advise!

(Enquanto isso, vamos vivendo, eu continuo morando no Vietnã, como estão as coisas aí no Brasil?)

Best!
@rmszc

**Comment by marss72** [comment]
LiteDB got some new maintainers, including @JKamsker and @pictos. This does not mean @mbdavid stopped maintaining this project (I hope so). This is a great project and will probably not be discontinued without any severe reason.

_If it ever gets discontinued, I'm sure someone will fork this repository and continue maintaining this project, making at least security updates and bug fixes._

**Comment by rmszc81** [comment]
hello @marss72, @JKamsker, @pictos, @mbdavid,

Ok, I got the point, but still, the idea is to start a new commercial project.

My concern is that, after some months, LiteDB will just become one of the many archived projects in github.

That's all.

Thanks for quick response.

Best!

**Comment by pictos** [comment]
@rmszc81 we don't have plans to archive this project... In fact our plans is to move it to a org, right now the project is under Mauricio's personal account, and expand to have tools and extensions on this org.

Keep in mind that we do it for free, so things will not be at the speed that users want. Right now, I know that Mauricios is busy with some personal and work tasks, so it will take a while until the public can see our progress.

That said, you can use Litedb on your project!

**Comment by rmszc81** [comment]
Hello (boa tarde) @pictos,
Thank you very much for making it clear.
(obrigado por esclarecer).

Best!
(Forte abraço!)
@rmszc81

**Comment by pictos** [comment]
No worries @rmszc81, glad that I could help (:
