### ISSUE TITLE
Support for non-public entity types

### ISSUE THREAD

**Issue by baSSiLL** [mbdavid/LiteDB#254]
Sometimes it is not convenient to have a public entity type. Maybe this was discussed before and there is a strong reason for not providing that option. Or I simply do not see an existing straightforward way to accomplish this. But I could not find any discussion on this topic.

Of course, this problem can be solved with custom mapping. However, it's quite a bit of unnecessary work to write a full code of (de)serialization for an entity. Especially, given that **BsonMapper** does not contain public methods for running the standard (de)serialization pipeline for arbitrary values, only for documents.

What I suggest as a more elegant solution is to provide some way to pass a factory function for creating an instance of non-public type on deserialization. That function could be used instead of instantiation via dynamic compilation.

Possible implementation is to add method **RegisterTypeFactory< T >(Func< T > factory)** to **BsonMapper**. Or an overload of **RegisterType** to make clear these are two alternatives - either full (de)serialization, or standard (de)serialization with custom instantiation.

**Comment by mbdavid** [comment]
Hi @baSSiLL, LiteDB support Factory for class intances. If you are using .NET 3.5 version of LiteDB you are using EmitReflectionHandler. This Emit I doesnt not support (as I know) internal classes. You can try ExpressionReflectionHandler as factory. I assume that this factory as not fast as Emit, but more flexible.

You must implement a custom ILitePlatform (take a look on https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Platform/LitePlatformFullDotNet.cs)

**Comment by baSSiLL** [comment]
Thanks, I'll look into this. I suppose I'll make that closer to my suggestion - by registering factory methods for specific types in my custom implementation of **IReflectionHandler**.
