### ISSUE TITLE
[QUESTION] Connect to LiteDB over the internet

### ISSUE THREAD

**Issue by mubarakalmehairbi** [mbdavid/LiteDB#2547]
Is there a way to allow a user to connect to a LiteDB file stored in the cloud?
```csharp
var db = new LiteDatabase("{{MY_URL}}");
```

**Comment by JKamsker** [comment]
Yes but i would strongly advise you to use something that is made for working across the internet. 
Like [ravendb](https://ravendb.net/) or [MongoDB](https://www.mongodb.com/docs/drivers/csharp/current/)
LiteDB excels at storing data from a single application, as a single process.


If, for whatever reason you still want to use LiteDB: You can pass the constructor a stream, which in your case should be a networkstream.

**Comment by mubarakalmehairbi** [comment]
Thanks @JKamsker. I didnt know about the networkstream. I will keep the issue open for a little while just in case other people also had other ideas, then I will close it

**Comment by Joy-less** [comment]
I don't know what your use case is, but I found the most success by making a simple TCP server that accepts requests (like `GetAccountInfo`) and queries a local database.

**Comment by mubarakalmehairbi** [comment]
For now, I am creating a HTTP server that queries the database instead of query the database directly.
