### ISSUE TITLE
BsonValue: implicit cast and constructor produce different results for null strings

### ISSUE THREAD

**Issue by baSSiLL** [mbdavid/LiteDB#255]
**BsonValue** created with constructor from **null** string has BSON type **Null**. When converting **null** string to **BsonValue** with implicit cast operator, the result is of type **String** with **RawValue** set to **null**. The latter value is not handled properly by serialization code resulting in **ArgumentNullException** in **Encoding.GetBytes**, because there is no check for **null** in **RawValue**.

I was surprised by this distinction of implementations of constructor and cast operator. I supposed they should produce equivalent results. Is there any point in providing own implementations for cast operators rather than simply calling the constructor with corresponding parameter type?

**Comment by mbdavid** [comment]
Hi @baSSiLL, you right, is missing null check in all implicit constructors. It's here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Document/BsonValue.cs#L358

I will fix this using some constructor in operator.

**Comment by mbdavid** [comment]
Fixed
