### ISSUE TITLE
Auto id after deleting a document

### ISSUE THREAD

**Issue by emrys90** [mbdavid/LiteDB#256]
It seems that if you delete a document, the next auto id is the id of the deleted document. This can lead to issues if there's a place you forget to delete a linked document based on id.

**Comment by mbdavid** [comment]
Hi @emrys90, sorry for delay. This happends because I didn't store last ID used. So, the easy wasy is get from _id index last ID and +1. But, you can implement you own AutoId function (storing last used ID) or (more recommended) is use ObjectId
