### ISSUE TITLE
Migration is impossible for now

### ISSUE THREAD

**Issue by falahati** [mbdavid/LiteDB#258]
Hey again,

Well after some tries I ended up with the conclusion that currently there is no reliable and up to date way to convert database files from v1.0.4 and specially 2.0.0-rc2

I tried released v2.0.0 final version, compiled v2.0.0rc2, released v2.0.0rc, released v2.0.0beta and even released final v1.0.4.

Only successful story was with LiteDBv2.0.0rc binaries and a LiteDB v1.0.4 database.
All others failed,
- v2.0.0beta nags about the pageType of 1.0.4 database file (#229?) and understandably cant make sense out of v2.0.0rc2 database file. 
- v2.0.0rc Shows no error what so ever, and is able to extract the information out of 1.0.4 database file. No luck with v2.0.0rc2 database file tho.
- v2.0.0rc2 also nags about the pageType of 1.0.4 database file (#229?) and surprisingly can't dump the database file created by it-self. Error message is "Object reference not set to an instance of an object." (#253?).
- v2.0.0 final believes that the 1.0.4 database file is not even a database (#257?) and as expected by wiki, can't dump the v2.0.0rc2 database file either, indicating "Invalid database version: 5".

![litedb](https://cloud.githubusercontent.com/assets/2479372/17466448/8a594e4a-5d25-11e6-87d6-afab2caba6d1.jpg)

**Comment by mbdavid** [comment]
Hi @falahati, I made a big mistake when change file version position between versions. To be honest, I thouth no one are using and dont care about new version if you app are running with a old version.

To check file version, you must get string "** This is a LiteDB file **" that are in all version in different positions and then get next 1 byte to get file version.

About dumping problem, I will take a look.

**Comment by mbdavid** [comment]
Is in my list, for v3, be "auto-update" from v2 and v1 to new v3.

**Comment by scordonnier** [comment]
@mbdavid When will LiteDB v3 be released with auto-update ?

I'm looking to use your library into a mobile project (iOS and Android) but it's a "show-stopper" to not have this feature (by the way, it should be an asynchronous process) if we can't update the datafile in the future.

**Comment by mbdavid** [comment]
Hi @scordonnier, yes, I know that auto-update is important mobile apps, it's not possible convert using dump process.

Update will be avaiable soon and will be 2 ways to do that: open database with "auto update=true" in connection string (that always check if needs be updated) or call an explicit method like `LiteEngine.UpdateDatafile`. About be async, will be not possible because LiteDB is net35, but you could run this update in `Task`.
