### ISSUE TITLE
Unexpected exceptions raised when working with a protected database but without password

### ISSUE THREAD

**Issue by falahati** [mbdavid/LiteDB#259]
Well this is more or less a bug, but can be categorized at a feature request as well.
Problem is that we can detect if the provided password is incorrect for a database, but there is no way to detect if a database is protected in first place or not.

I strongly believe that the `LiteDatabase` constructor or its methods (or at least header loader or page reader) (in case of lazy loading) should raise a `LiteException` with `LiteException.DATABASE_WRONG_PASSWORD` as the exception code.

Currently, if you open a protected database with no password, all you get is a database that seems OK but may or may not raise unrelated exception (like not implemented exception, Bad pageType exception, etc) in unrelated and unexpected places.

**Comment by mbdavid** [comment]
Uhm... I will do a check in DiskFile in datafile has password... so I can throw "Wrong password"

**Comment by falahati** [comment]
Can be closed now then,
