### ISSUE TITLE
collection.Sum(predicate)

### ISSUE THREAD

**Issue by henon** [mbdavid/LiteDB#268]
How difficult is it to implement a Sum implementation on BSON document level for summing up numeric fields?

**Comment by mbdavid** [comment]
It´s not too hard. 

LiteCollection must have a `FindKey(Query)` that returns an `IEnumerable<BsonValue>` from indexes keys. With this you can run any aggregation function.

**Comment by henon** [comment]
nice, that is even better

**Comment by mbdavid** [comment]
Merging with #269
