### ISSUE TITLE
Feature Request: Add a method to fetch value from index

### ISSUE THREAD

**Issue by sun1991** [mbdavid/LiteDB#269]
See code:

```
var lines = new List<PosLine>(){
    new PosLine{Name="John", Address="dummy1", Tstamp=DateTime.Now},
    new PosLine{Name="Jane", Address="dummy2", Tstamp=DateTime.Now}
};

using(var db = new LiteDatabase(@"test.db"))
{
    var posLines = db.GetCollection<PosLine>("POS");
    foreach(var line in lines)
    {
        var id = posLines.Insert(line);
        Console.WriteLine("id=" + id.ToString());
    }

    var names = posLines.FindAll().Select(p => p.Name).ToList();
    foreach(var name in names)
    {
        Console.WriteLine("name=" + name);
    }
}
```

Line `var names = posLines.FindAll().Select(p => p.Name).ToList();` did a full table scan in order to get a list of Name. It's not ideal, it's better if we can build an index on p.Name then fetch all or part of indexed values from it directly. 

In SQL term, it called "Covering Index",  I think it is a useful feature.

**Comment by mbdavid** [comment]
Hi @sun1991, yesterday an issue was opened with same propose: #268  - I will merge both in a sigle issue

**Comment by mbdavid** [comment]
Yes, it's done. `FindIndex` in v3-beta
