### ISSUE TITLE
Object not being serialized or deserialized correctly?

### ISSUE THREAD

**Issue by sherry-ummen** [mbdavid/LiteDB#27]
Hi David,

 I was playing around with LiteDb by changing the max size of doc to be ~16Mb

```
public const int MAX_DOCUMENT_SIZE = 4079 * BasePage.PAGE_AVAILABLE_BYTES;
```

And here is my test code: http://1drv.ms/1GyVN8v

I checked in the inspect window and found that values for property records (in my example) was not coming correctly.

Image attached of it:
![why](https://cloud.githubusercontent.com/assets/2572380/7414329/9ee01932-ef5a-11e4-9be6-af3fa0a90745.png)

I did not investigate further assuming you know whats going wrong.

**Comment by mbdavid** [comment]
Hi @sherry-ummen, the problem is: you are serializing an `Object` (in this case, a `List<Object>`).

LiteDB serialize/deserialize objects using object type to know where put a field data. To serialize is a problem, but when you try to deserialize it´s not possible because there are no destination type to match all document (`BsonDocument`).

**Comment by sherry-ummen** [comment]
Thanks David.

Is it possible to improve this? Since the same code for MongoDb works pretty nicely.

Sent from my Windows Phone
________________________________

**Comment by mbdavid** [comment]
I will made some tests with MongoDB driver to know how they store a document from an `Object`. I will add to my todo list and try to be avaiable in next version

**Comment by sherry-ummen** [comment]
Great thanks David.

**Comment by mbdavid** [comment]
There is a new version on Nuget/Github Release: 1.0.1 fixing this problem.

**Comment by sherry-ummen** [comment]
hi,
 I tested it but still my issue was not fixed with the changes. So I quickly had a look at whats wrong and did some small changes to get it working with my code. Here is the commit
https://github.com/sherry-ummen/LiteDB/commit/121fbf0473b407107b0cd084db3b8d36fe9b6a90

All the unit tests pass.

**Comment by mbdavid** [comment]
Hi @sherry-ummen, thanks for your feedback. I will test your code and join this issue with #31 that is same problem. Now I do more tests before release new version.

**Comment by mbdavid** [comment]
Hi @sherry-ummen, I use part of your code to create implement deserialize to `IList<>` and `IDictionary<,>`. Can you test `master` branch in your app? Thanks

**Comment by sherry-ummen** [comment]
thanks @mbdavid ur fix works like charm :smiley:

**Comment by sherry-ummen** [comment]
oops hold on seems one case still not working. I will let you know soon. Sorry for being joyous too early :)

**Comment by sherry-ummen** [comment]
Sorry for late reply as I was on vacation. So the case which did not work was when you put the property value to be Enummerable.Range(1,9999) then it failes with exception index out of bound.

You/me can create a seperate issue if you like for this.

it works in mongodb.

**Comment by sherry-ummen** [comment]
Hi David,


I want to ask one thing.


Can we somehow make a mechanism to avoid this overhead of Start and End transaction. I just want to write it without that and just leave rest to the underlying API to write.


I tried a simple test that where I am doing random read and write and for that I always have to Start and End transaction for write which slows down the process.


Any solution or suggestion?


Thanks






Sent from Windows Mail





From: Mauricio David
Sent: ‎Sunday‎, ‎May‎ ‎24‎, ‎2015 ‎12‎:‎54‎ ‎AM
To: mbdavid/LiteDB
Cc: Sherry Ummen





Closed #27.

**Comment by mbdavid** [comment]
Hi @sherry-ummen, I open a new issue for this bug: #38 

About start/end transaction: I use transaction to avoid concurrency writes. Transaction lock datafile so there is no 2 users writing at same time.

It´s quite ease to "remove" this, if you want more performance and less overhead.

I´m planning to v.1.1 create a Stream layer to control this - so you can use MemoryStream, assembly resource stream or even FileStream without transactions, locks and journal writes. More performance but less control - ideal do one user application.

**Comment by sherry-ummen** [comment]
Nice I eagerly wait for that.


Could you also provide a property or some configuration parameter to the LiteDB so that we can set the max BsonDocument size also? I can always compile it by myself also but thought that 1 Mb is still quite low and can easily shoot up in case heavy geometry app.




I am planning to test this in a real heavy write and read in an intense desktop application.





Sent from Windows Mail





From: Mauricio David
Sent: ‎Thursday‎, ‎May‎ ‎28‎, ‎2015 ‎7‎:‎55‎ ‎PM
To: mbdavid/LiteDB
Cc: Sherry Ummen





Hi @sherry-ummen, I open a new issue for this bug: #38 

About start/end transaction: I use transaction to avoid concurrency writes. Transaction lock datafile so there is no 2 users writing at same time.

It´s quite ease to "remove" this, if you want more performance and less overhead.

I´m planning to v.1.1 create a Stream layer to control this - so you can use MemoryStream, assembly resource stream or even FileStream without transactions, locks and journal writes. More performance but less control - ideal do one user application.
