### ISSUE TITLE
Why string end with "\r\n" be trimmed?

### ISSUE THREAD

**Issue by lidanger** [mbdavid/LiteDB#270]
I found this in a project.For 2 days, I can't find the problem.
The test code:

    p = new Person
	{
		Name = "张立",
		Age = 31,
		Sex = 1,
		Description = "一个软件工程师\r\n"
	};

	Console.WriteLine("name:{0}", p.Name);
	Console.WriteLine("age:{0}", p.Age);
	Console.WriteLine("sex:{0}", p.Sex);
	Console.WriteLine("description:{0}", p.Description);

	using (var conn = new LiteDB.LiteDatabase("test3.db"))
	{
		var col = conn.GetCollection<Person>("p3");
		col.Insert(p);
	}

	using (var conn = new LiteDB.LiteDatabase("test3.db"))
	{
		var col = conn.GetCollection<Person>("p3");
		var ps = col.FindAll();
		foreach(var p1 in ps)
		{
			Console.WriteLine("name:{0}", p1.Name);
			Console.WriteLine("age:{0}", p1.Age);
			Console.WriteLine("sex:{0}", p1.Sex);
			Console.WriteLine("description:{0}", p1.Description);
		}
	}

	Console.WriteLine("------------------------------------");

**Comment by mbdavid** [comment]
Hi @lidanger, It´s a default in BsonMapper. Try:

`BsonMapper.Global.TrimWhitespace = false;`

**Comment by lidanger** [comment]
all right
