### ISSUE TITLE
query with order

### ISSUE THREAD

**Issue by henon** [mbdavid/LiteDB#271]
Hey, the documentation is really good but after having read it all I still wonder how to query  collections in a specific order efficiently. 
Limiting a query mostly only makes sense if you can specify the order. For instance I want to limit my query to get the first 100 docs or the last hundred of a collection according to a query. I can currently apply .OrderByDescending(x=>x.Id) on a query result but this would not be executed by the query engine, right?

**Comment by mbdavid** [comment]
When you query in a collection using an index, you are using an order (index order). So, this is used to limit/skip.

LiteDB implements `skip list` indexes. So you query `Query.EQ("Age", 12)` database will search using Age index, that are in order asc (or desc, if you want).

**Comment by henon** [comment]
Thanks! I got it.

**Comment by henon** [comment]
How do I configure the index order i.e. to Descending ?

**Comment by mbdavid** [comment]
Query with Desc order only when all rows are selected:

`Query.All(Query.Descending)` (desc by _id index)
`Query.All("Name", Query.Descending)` (desc by Name index)

All others cases are not supported (or even has no sense, like Equals)

**Comment by henon** [comment]
Cool. Since this was not intuitive to me, I allowed myself to extend the docu on page Queries with the following example. Correct me if I am wrong.

// find top 100 oldest persons aged between 20 and 30
var results = collection.Find(Query.And(Query.All(Query.Descending), Query.Between("Age", 20, 30)), limit:100);

**Comment by mbdavid** [comment]
Hi @henon, sorry for a long delay. This way not works. If you wants this order, you must OrderBy using linq.

`collection.Find(Query.Between("Age", 20, 30)).OrderBy(x => x.Age).Take(10);`

The "hard" query part are executed using index (finding all 20-30 yo). Linq will order and limit to 10.

**Comment by henon** [comment]
sorry to open this up again, but I did try this out before I posted, so I am curious why you say it does not work. was I lucky and got the correct result? what is wrong with the way I built the query? I just want to understand.

**Comment by mbdavid** [comment]
Hi @henon, you right. Your code is correct. Query.And use Except Linq operation. So, when you findAll using Age index, your NodeIndex returns in Age desc order.
