### ISSUE TITLE
UnauthorizedAccessException raised in 1.03 on RecoveryService.OpenExclusiveFile

### ISSUE THREAD

**Issue by tjmoore** [mbdavid/LiteDB#277]
We have had an instance of this exception occurring during construction of the LiteDatabase object. It appears to go into RecoveryService.OpenExclusiveFile but gets an access denied on the 'journal' file. It's apparently hard to reproduce (raised by our testers).

All our calls to LiteDb are based on creating an instance of LiteDatabase, performing operations and disposing the instance and all wrapped around a process mutex lock.

I can catch the exception but this is being thrown in the constructor so I fail to get the LiteDatabase instance.

Sample stack (file path is an example, but may be relevant that we store the database file under ProgramData, but there has been no access issues writing to database.db)...

> System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\MyCompany\Product\database-journal.db' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at LiteDB.RecoveryService.OpenExclusiveFile(String filename, Action`1 success)
>    at LiteDB.LiteDatabase..ctor(String connectionString)

**Comment by mbdavid** [comment]
Is journal file exists? Or LiteDB can´t check this file because there are no permissions?

**Comment by tjmoore** [comment]
Unfortunately it's only occurred the once and raised by one of our testers. The file isn't there currently and our application is operating normally. I checked the permissions for the folder and it looks okay. Our application runs as administrator anyway and has full access. As I mentioned it can access the database.db file okay.
