### ISSUE TITLE
FileStorage.Upload concurrency failures

### ISSUE THREAD

**Issue by mykemaas** [mbdavid/LiteDB#28]
I'm using the following code to upload a file using FileStorage.Upload to store a file within an ASP.NET request:

    public string UploadFile(string mimeType, string origFileName, string userName, byte[] data)
        {
            string fileName = string.Format("{0}.{1}", Guid.NewGuid(), Path.GetExtension(origFileName).Replace(" ", "").Trim(' ', '.'));
            string filePath = string.Format("$/{0}/{1}", userName, fileName);

            using (var db = new LiteDatabase(BlobDBName))
            {
                LiteFileInfo finfo = new LiteFileInfo(filePath);
                finfo.MimeType = mimeType;
                finfo.Filename = origFileName;

                using (MemoryStream ms = new MemoryStream(data))
                {
                    ms.Seek(0, SeekOrigin.Begin);
                    db.FileStorage.Upload(finfo, ms);
                }

                return fileName;

            }

        }

The web page uses a control called "DropZone" to asynchronously upload multiple files at a time by calling into a web endpoint.  My endpoint uses the above code to store the file.  When I am uploading multiple files (and also retrieving them), I'm getting a number of strange errors.  

The most common one is an access denied error against the journal file, but I also get "IOException: The Segment is already unlocked".  These are bothersome, but not fatal.  The bigger issue is that a number of files will be recorded in the _files collection with a zero length.  I've verified the associated chucks exist and are properly recorded, but the file length is never updated.  I am using the latest NuGet package (1.0).  Any idea on what may be causing this?

FYI: My retrieval code looks like this:

    public FileInformation GetFile(string userName, string fileName)
        {
            using (var db = new LiteDatabase(BlobDBName))
            {
                string filePath = string.Format("$/{0}/{1}", userName, fileName);
                var liteFileInfo = db.FileStorage.FindById(filePath);

                if (liteFileInfo == null)
                    return null;

                FileInformation ret = new FileInformation();
                ret.SizeInBytes = liteFileInfo.Length;
                ret.MimeType = liteFileInfo.MimeType;
                ret.Extension = Path.GetExtension(liteFileInfo.Filename).Trim('.');
                ret.OriginalFileName = liteFileInfo.Filename;
                ret.FileName = fileName;

                using (MemoryStream ms = new MemoryStream())
                {
                    liteFileInfo.CopyTo(ms);
                    ret.data = ms.ToArray();
                }
                return ret;
            }
        }

**Comment by mbdavid** [comment]
Hi @mykemaas, thanks for your contribuition. I will create a unit test to try to isolate this problem and fix.

**Comment by mbdavid** [comment]
Hi @mykemaas, I did some fixes on `dev` branch. Can you test? I tested in unit tests and with an dropzone example that I made. To me works now.

**Comment by mykemaas** [comment]
I just did a quick test in my application using the dev branch...  looks like it's working well!  I uploaded 20 5+ megabytes files simultaneously, and it handled it like a dream.  I'll be sure to do some more thorough testing this evening and report back.  Thank you!!!

**Comment by mbdavid** [comment]
There is a new version on Nuget/Github Release: 1.0.1 fixing this problem.
