### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by prashantkhandelwal** [mbdavid/LiteDB#280]
Is there any plan for getting this library working with .NET Core?

**Comment by goluda** [comment]
Hi I also ask for it

**Comment by mbdavid** [comment]
Hi @prashantkhandelwal and @goluda, current version do not support .NET Core, but it's on plans, like you can see here: https://github.com/mbdavid/LiteDB/issues/219

Next major version will be full netstandard 1.3 (that are .NET Core support)

**Comment by prashantkhandelwal** [comment]
Hi @mbdavid, thanks for the update. Will look forward for the next major release. :)

**Comment by ldubrois** [comment]
Hi @mbdavid, I'm also really interested in the .net core support.
We want our product to support .net core but we are using your awesome DB for one our components.

Do you have an idea of when the next major version supporting .net core will be available ?

Thanks

**Comment by mbdavid** [comment]
Hi @ldubrois, thanks for using LiteDB. Next version will be take a long time, at least 2 or 3 months. I'm currently in another project so left me little time.

**Comment by 0xFireball** [comment]
Hey @ldubrois , I temporarily forked LiteDB for a .NET Core version. I merged in the latest changes from the official repo. You might be able to use it: https://github.com/0xFireball/LiteDB.DotNetCore

**Comment by 0xFireball** [comment]
Once official support is available we can switch back. I just made some very minor modifications to make it build. It works fine for now.

You need to call:
```
//Initialize database
LitePlatform.Initialize(new LitePlatformNetCore());
```

for it to work.

**Comment by mbdavid** [comment]
Hi @0xFireball, i'm finishing next v3 version that will be netstandatd1.4 (`dev` branch). Now, I need write some examples in Xaramin iOS/Android, NetCore e UWP examples.

**Comment by ldubrois** [comment]
@0xFireball, @mbdavid, great news !!!

Thanks for the news. I'll try that next week.

**Comment by henon** [comment]
quick question: is LitePlatform.Initialize(new LitePlatformNetCore()); still necessary when using on .net core?
I tested without that line successful but am not sure if this is right.
