### ISSUE TITLE
Can't create database if the File Path contains blank space!

### ISSUE THREAD

**Issue by chithanh12** [mbdavid/LiteDB#284]
I have an issue with the connection string. If the file path contains the space we will get the error. "An unhandled exception of type 'System.ArgumentNullException' occurred in LiteDB.dll".
It is ok if the path doesn't contain blank space.

For example:
Error case:

>  using (var db = new LiteDatabase(@"C:\Temp Folder\MyData.db")) {
>                 // Get customer collection
>                 var customers = db.GetCollection<Customer>("customers");
> .....
> }

Success case: 

>  using (var db = new LiteDatabase(@"C:\Temp\MyData.db")) {
>                 // Get customer collection
>                 var customers = db.GetCollection<Customer>("customers");
> ....
> }

**Comment by mbdavid** [comment]
Maybe was last connection string commit. For now, try ("filename=c:\temp path\file.db"). I will fix this week

**Comment by icelty** [comment]
I found the same issue, and can't get rid of it unless I revert back to pre-regex commit. I tried all reg-ex commits and they all have the same problem.

**Comment by icelty** [comment]
This issue seams to have been fixed with 2.0.2

**Comment by mbdavid** [comment]
Fixed

**Comment by DanielAltamirano** [comment]
This issue still occurs in the latest version
