### ISSUE TITLE
ConnectionString documentation is out of sync

### ISSUE THREAD

**Issue by MariusVolkhart** [mbdavid/LiteDB#285]
The documentation suggests that connection strings should be built as `"Name1=Value1; Name2=Value2;"`.

I found this to be incorrect.

Given the connection string `"filename=\"path/to/file\"; password=test;"`
I get a `ConnectionString` object that has 3 entries in`_values`.

Given the connection string `"filename=\"path/to/file\"password=test;"`
I get a `ConnectionString` object that has 2 entries in`_values` as expected.

In the second version the `;` delimiter has been removed.

**Comment by MariusVolkhart** [comment]
Using version 2.0.1 on Window

**Comment by mbdavid** [comment]
Hi @MariusVolkhart, 2.0.1 had a bug that was fixed in this 2.0.2 version.

**Comment by falahati** [comment]
Hey @mbdavid, Should I investigate this problem to fix and request the regex changes again?

**Comment by mbdavid** [comment]
Hi @falahati, I'm a bit out of LiteDB last days. I'd reverted you last commit about connection string because there are some problems. I think you can try use `StringScanner` to read string connection.

**Comment by falahati** [comment]
Unfortunately, StringScanner is in LiteDB.Shell project and using it without moving it to the main project is impossible. So I wrote a simple yet short code to handle the connection string, this time without using regex. See if it works in all cases and then merge:
#306

Also. Still waiting for mentioning LiteDBViewer project in documentation and website :)
