### ISSUE TITLE
Insert into collection with multiple threads

### ISSUE THREAD

**Issue by icelty** [mbdavid/LiteDB#286]
Getting  {"Invalid transaction on top of stack"} in private void popTopTransaction(LiteTransaction trans)

There is no auto id, I generate GUID strings for each inserted element.

**Comment by icelty** [comment]
also getting {"Unable to cast object of type 'LiteDB.IndexPage' to type 'LiteDB.CollectionPage'."}

and so many exceptions, definitely going back to 1.0.4

**Comment by mbdavid** [comment]
Hi @icelty, either 1.x and 2.x are not thread safe. AutoId is present in v2.0 release, including for Guid (https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Serializer/Mapper/BsonMapper.cs#L90)

I'm updating to 2.0.2 to fix connection string parser

**Comment by mbdavid** [comment]
Only new v3 version will be thread-safe... but still in dev for a while

**Comment by icelty** [comment]
@mbdavid , thanks for the tip, it may have been that I never happen to reach a raise condition with 1.0.4, also I was instantiating LightDatabase only when needed disposing it immediately after. I happen to changed that model just recently along with the upgrade to 2.0.1 where now is a singleton :(, thanks for the information I can wait for 3.0 then!

**Comment by icelty** [comment]
For the googling eyes, the work around thread safety is to have a regular lock, what I did was, wrote a small wrapper around all queries, and lock(LiteDatabaseInstance), is not ideal but if you are in a hurry, is not a supper expensive tech debt to have.

**Comment by LiamKenneth** [comment]
@icelty do you have an example of the locking the DBInstance? I want to use this in my signalr project which uses a lot of async methods so don't want to run into the same issues. Also am I right in thinking theLiteDB just sits in my project folder and auto magically works like MongoDB?

**Comment by icelty** [comment]
Simple, I wrap LiteDatabase within a class that centralizes all IO operations, also within the class I have just a simple object field that I Lock on every operation. Not different than what we all do to make multi-threaded operations over a non thread-friendly object i.e. A cross thread shared List for example.

Sample Code (Just top of my head, not sure it will compile 100%):
`
object syncRoot = new object();
void myInsertFunction<T>(string collection, T document){
            lock (syncRoot )
            {
                Database.GetCollection<T>(collection).Insert(document);
            }
}
IEnumerable<T> myGetterFunction<T>(string collection){
            lock (syncRoot )
            {
                return Database.GetCollection<T>(collection).Insert(document).FindAll();
            }
}

`

**Comment by icelty** [comment]
FYI @mbdavid I have seen a problem with auto id (Int32) when inserting after a few deletes, not sure if this is true but it looks like Light db is re-using ids and throws an exception. ```Cannot insert duplicate key in unique index 'ChannelName'. The duplicate value is 'add channel user test'```

**Comment by mbdavid** [comment]
v3-beta was released and now support multi-thread in a single instance of LiteDatabase (uses ReadWriteLockSlim)
