### ISSUE TITLE
Feature request: PostLoadInterface for model classes

### ISSUE THREAD

**Issue by emrys90** [mbdavid/LiteDB#287]
It would be nice to have an interface that a class can implement that contains a Load method. That method would get called after all the properties are set when reading a record from the database. This lets us do any processing after a model gets created for runtime data that does not get stored in the database. Normally you would use a constructor for things like this, but we can't in this case since the properties would not be set yet.

I think you could do this by checking if the type you are instantiating is an instance of the interface, then call that method.

**Comment by mbdavid** [comment]
Hi @emrys90, serialization/deserialization from/to POCO class to BsonDocument has a lot feature request. I'm organizing source, in next version, to this operation is an "external" plugin using interfaces.

**Comment by mbdavid** [comment]
Hi @emrys90, BsonMapper change to be more flexible to support custom classes. Take a look in new version.
