### ISSUE TITLE
Why do you try and write getters only to the db?

### ISSUE THREAD

**Issue by emrys90** [mbdavid/LiteDB#289]
Just wondering what benefit there is to trying to write a property that only has a getter to the database? Usually if it's just a getter then it's probably doing some calculation/lookup that you wouldn't want saved, and since it can't set the property without a setter, just curious why it's like that?

**Comment by Discofunk** [comment]
Saving Getters is good when you would like to query against a calculated value (i.e. OrderTotal > 20.00)
