### ISSUE TITLE
Updating when using BsonId on a String returns false

### ISSUE THREAD

**Issue by francoislg** [mbdavid/LiteDB#29]
I have this class which I want to insert and update :

``` C#
public class UnitCard {
        [BsonId]
        public String name { get; set; }
        public String hp { get; set; }
}
```

I update/insert it with the following code

``` C#
if (cardsCollection.Exists(c => c.name.Equals(card.name))) {
    if (!cardsCollection.Update(card)) {
          throw new CouldNotSaveCardException();  // My own exception
    };
} else {
     cardsCollection.Insert(card);
}
```

"cardsCollection.Update(card)"  always return false.

I tried with "cardsCollection.Update(card.name, card)" with no success, and even tried with

``` C#
UnitCard found = cardsCollection.FindOne(c => c.name.Equals(card.name));
cardsCollection.Update(found.name, card);
```

without success either.

I tried using ObjectIDs and updating worked as intended, but my wanted behavior really is with [BsonID]

**Comment by mbdavid** [comment]
Hi @francoislg, are you using last version? This error is similar to #21. Try use: 
`cardsCollection.Update(found.name.ToLower(), card);` to test. I will make some unit tests for this.

**Comment by mbdavid** [comment]
Wow, now I saw: this fix is not in 1.0.0 version (NuGet)... I fix in master branch but do not create a new version.

**Comment by francoislg** [comment]
Thanks
 ``` C# 
cardsCollection.Update(found.name.ToLower(), card); 
``` 
DOES work ! Glad it's fixed on master branch :)
I'll stick to the temporary fix until it's in the new version

**Comment by mbdavid** [comment]
There is a new version on Nuget/Github Release: 1.0.1 fixing this problem.
