### ISSUE TITLE
FindOne within a transaction erases previous inserts

### ISSUE THREAD

**Issue by MariusVolkhart** [mbdavid/LiteDB#292]
# Summary

We observed a bug where calling `LiteCollection#FindOne(Query)` within a transaction causes previous insert operations to not be committed.
## Step to reproduce
1. Create a new instance of `LiteDatabase`. This can be on the file system or in-memory.
2. Begin a transaction by calling `LiteDatabase#BeginTrans()`
3. Insert a document into a collection by calling `LiteCollection#Insert(BsonDocument)`
4. Query the collection by calling `LiteCollection#FindOne(Query)`
5. Observe that all inspections of the db from this point on (within the transaction) shows no documents in the collection.
## Working example

We have a minimal program to reproduce the issue available [here](https://github.com/pkware/LiteDbIssue292)
## Version

We are using version 2.0.2 of the library.

**Comment by mbdavid** [comment]
Hi @MariusVolkhart, thanks for this detail information. I will made all tests do understand whats going wrong.

**Comment by MariusVolkhart** [comment]
I have additional information. The same bug is present when using `LiteCollection#Find(Query)`, but not `LiteCollection#FindAll()`

**Comment by MariusVolkhart** [comment]
This issue is no longer present in `3.0.0-beta2`
