### ISSUE TITLE
Xamarin ios integration build error

### ISSUE THREAD

**Issue by shahromil88** [mbdavid/LiteDB#294]
Hi,

I want to integrate LiteDB into Xamarin app containing ios & android platform. I have downloaded the source code of LiteDB and given reference of LiteDB.Core.dll into PCL library. However, when I build the source code for xamarin ios it gives below error: 

**Error	:**	
Failed to resolve "System.Int32 System.Runtime.InteropServices.Marshal::GetHRForException(System.Exception)" reference from "System.Runtime.InteropServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"	

**Configuration:**
Xamarin Version: 4.1.1.3
Xamarin iOs Version: 9.8.1.4
LiteDB.Core Version: 2.0.2.0
iOS SDK Version : 9.2

(Please note it working fine with android).

**Comment by mbdavid** [comment]
Hi @shahromil88, did you reference LiteDB.Core and specific LiteDB.Platform for iOS? LiteDB.Core is a same dll for all platforms, but need a specific LiteDB.Platform.dll that changes in each platform.

**Comment by shahromil88** [comment]
Hi @mbdavid, I think it is my mistake in assigning references to my project. It is working fine now.

Thank you for the prompt response.
