### ISSUE TITLE
[Question] Dynamic mapping with DbRef

### ISSUE THREAD

**Issue by tgiachi** [mbdavid/LiteDB#296]
Hi! 
Is possibile use attribute on Property for make automatic dbRef mapping?

Thank you!

**Comment by mbdavid** [comment]
Hi @tgiachi, unfortunately no. I tried to do this, but I had no context when using attributes. DbRef is a simple layer between data deserializer in BsonMapper. I will mark this as enchancement to try do this again in future.

**Comment by tgiachi** [comment]
thank you 😄 !

Continue develop, you did great job!,

**Comment by mbdavid** [comment]
Hi @tgiachi, now it's possible. Take a look on new v3-beta. Thanks

**Comment by tgiachi** [comment]
Hi!, Thank you for your great job!
