### ISSUE TITLE
Shrink corrupts encrypted database

### ISSUE THREAD

**Issue by baSSiLL** [mbdavid/LiteDB#297]
Shrink on encrypted database corrupts its state. Subsequent operations throw **LiteDB.LiteException: Invalid database password** with the stack:

```
at LiteDB.EncryptedDiskService.ValidatePassword(Byte[] passwordHash)
at LiteDB.FileDiskService.ReadPage(UInt32 pageID)
at LiteDB.EncryptedDiskService.ReadPage(UInt32 pageID)
at LiteDB.PageService.GetPage[T](UInt32 pageID, Boolean setDirty)
...
```

The error occurs both in the last Nuget package and sources from the master branch.

Test to reproduce:

```
    [TestMethod]
    public void Shrink_Encrypted_Test()
    {
        using (var tmp = new TempFile(connectionString: "password=test"))
        using (var db = new LiteDatabase(tmp.ConnectionString))
        {
            db.Shrink();
            // Any subsequent operation involving page read fails
            db.Shrink();
        }
    }
```

**Comment by mbdavid** [comment]
Hi @baSSiLL, thnaks. I know this bug, but I didnt fix yet. I is missing implement, in EncryptionDisk, the GetTempFile with password. I will add this in my todo.

**Comment by mdissel** [comment]
Is this issue already fixed?

**Comment by mbdavid** [comment]
In v3 this issue is fixed - but shirink must provide password to.

`db.Engine.Shrink("new-or-same-password", [TempDisk])`
