### ISSUE TITLE
UAP/Pi Compatibility

### ISSUE THREAD

**Issue by WattsC-90** [mbdavid/LiteDB#300]
Hi,
Any luck releasing a nuget package for UAP compatibility? there were some performance issues/memory leaks when szurgot made the changes in a pull request a few months ago (i think, from memory..) just wondered if it was any further along fixing/releasing it yet?

Thanks!
Chris

**Comment by mbdavid** [comment]
Hi Chris, this memory leaks is in current version? I didn´t do any change after @szurgot change UWP platform.
