### ISSUE TITLE
Index options of PK is silently ignored

### ISSUE THREAD

**Issue by nerai** [mbdavid/LiteDB#304]
I use version 2.0.2 and would like to use a PK of type `string`, case _sensitive_. I tried this:

```
[BsonId (false)]
[BsonIndex (true, false, false, false, false)]
public string Id { get; set; }
```

However, I found that the PK is still case _insensitive_. In fact, Reflection.cs has this in  line 122:

```
// if is _id field, do not accept index definition
if (name == "_id") index = null;
```

The created model differs from what the user expected. For this reason, the index should not be ignored silently, an exception should be thrown. 

However, why is the index being ignored at all? A case sensitive PK should be easier to implement than a case insensitive PK. Any chance custom index options can be supported in the future?

**Comment by mbdavid** [comment]
Hi @nerai, i'm reviewing this all day and read more in MongoDB too. In MongoDB, there is transform option like this (only now, in 3.2 supports ignoreCase). As I mention in #305, I beleave that I will remove all king of index options (keeping only unique option). Any transform can be do it using virtual field or `get only` field. How do you think?

**Comment by mbdavid** [comment]
I forgot to say that today, `_id` index is created when collection are created, so it's not ease to get any index options. See here: 

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/DbEngine/Services/CollectionService.cs#L68

**Comment by nerai** [comment]
@mbdavid What you propose sounds fine to me.
