### ISSUE TITLE
Should comparisons be strict or relaxed?

### ISSUE THREAD

**Issue by nerai** [mbdavid/LiteDB#305]
Currently, by default, comparisons on strings are very lenient:

```
public IndexOptions ()
{
    this.Unique = false;
    this.IgnoreCase = true;
    this.TrimWhitespace = true;
    this.EmptyStringToNull = true;
    this.RemoveAccents = true;
}
```

I believe it should be strict by default:

```
this.IgnoreCase = false;
this.TrimWhitespace = false;
this.EmptyStringToNull = false;
this.RemoveAccents = false;
```

I believe this is also preferable in general, [because it is _expected_ by most users](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). The reasons for this are that it is more simple ('binary' vs. 'unicode', so to speak) and simple things are more expected than complex things from computer systems.

Also, notably, is also the default for strings in C# / .NET. In the .NET framework, you practically always have to specify a flag or a custom comparator if you want case insensitive behavior.

At the same time, it does not lose flexibility: Users which need more relaxed comparisons can easily enable them manually (except for PKs, see #304).

In fact, it is probably a good idea to let the user handle sanitizing. LiteDB has no way to know how to treat the input. For instance, in the Turkish language, i and I are [two separate characters](https://en.wikipedia.org/wiki/Dotted_and_dotless_I), _not_ just different case. (I chose the Turkish example because is a well known one which has bitten many people in the past.)

I don't know if most use cases of LiteDB need relaxed comparisons, so maybe it's just my personal opinion. I'm positive this behavior came as a surprise to many people, however.

**Comment by mbdavid** [comment]
Hi @nerai, you right and I'm revision this index options. When I made this defaults, it's was my personal use and never revised again. I'm changing in dev branch, but will changed only in new major version (when I update all wiki documents).

I'm thinikng in remove all index options (keep only unique and ignore case). `TrimWhitespace` and `EmptyStringToNull` will be kepped in `BsonMapper`, so there is no need use in index too. `RemoveAccents` can't be implemented in PCL.

Removing index option, I will create option to "vitual indexed fields" in fluent api. Something like this:

```
mapper.Entity<Customer>()
    .Index("fullname", (d) => d.FirstName + " " + d.LastName)
    .Index("nameupper", (d) => d.FirstName.ToUpper())
```

**Comment by nerai** [comment]
That sounds lovely, thank you. Good solution.
