### ISSUE TITLE
No LitePlatform for CoreClr

### ISSUE THREAD

**Issue by seertenedos** [mbdavid/LiteDB#307]
When used in Asp.NET Core you can use the LiteDB.Core nuget package but can't do anything as you get an error about the LitePlatform not being initalised. There are no LitePlatforms compatible with CoreClr available to choose from. 

Using dotnet netcoreapp1.0 with version 1.0.1 of Coreclr

**Comment by sgrassie** [comment]
It's honestly not that much work to implement the necessary interfaces yourself. Also, see this pull request: #303; additionally, there are a number of closed issues regarding this already.

**Comment by seertenedos** [comment]
Thanks.  You are right it is not a lot of changes if you do it in LiteDB but if done outside it for the core version you need to duplicate a lot of the files from the Platform folder. That said now that all the needed changes are in the pull request i can just copy over all the files as it was much fewer changes than i expected.

**Comment by seertenedos** [comment]
Will it end up as part of the LiteDb.Core nuget or as a separate Nuget to add in?

**Comment by mbdavid** [comment]
For current LiteDB v2 I will use pull request for support .NET Core (that requires LiteDB.Core.dll + LiteDB.Platform.dll). For next  v3 will be only LiteDB.Core (will be only .netstandard 1.4)
