### ISSUE TITLE
How to include properties of collection items?

### ISSUE THREAD

**Issue by kisc85** [mbdavid/LiteDB#309]
I try to implement an object hierarchy where `class A` has a property of type `List<B>`, and `class B` has a property of type `class C`. I also add a `DbRef` from `B` to `C`. When I try to query a collection of type `class A` I cannot create a `LiteCollection<A>` that somehow includes the "B.C" values. The only workaround I found is querying the `class A` instances first and loading all `class C` values manually after that. I do not know if this is really not possible or I just did not find the solution.

``` C#
// Class hierarchy
class A
{
    public int Id { get; set; }
    public List<B> B { get; set; }
}
class B
{
    public int Id { get; set; }
    public C C { get; set; }
}
class C
{
    public int Id { get; set; }
    public string Value { get; set; }
}

// Add DbRef from B to C
BsonMapper.Global.Entity<B>().DbRef(x => x.C, "c");

// Problem: did not find a way to include B.C in collectionA
var collectionA = db.GetCollection<A>("a");
var collectionC = db.GetCollection<C>("C");

// Workaround: load b.C values manually
foreach (var a in collectionA.FindAll())
{
    foreach (var b in a.B)
    {
        b.C = collectionC.FindById(b.C.Id);
    }
}
```

**Comment by mbdavid** [comment]
Hi @kisc85, `DbRef` support only basic document references. In your case, there is no built-in solution with `DbRef`. I'm writing next version and I will review this LiteDB dbrefs because it's a cool feature :) I will try implement this "in list" reference and deep include too like in #149

**Comment by kisc85** [comment]
Hi @mbdavid! Thanks for the quick answer and congratulations to the LiteDB project! :)
