### ISSUE TITLE
"Sequence contains no matching element" when querying Dictionary<string, object> documents

### ISSUE THREAD

**Issue by superware** [mbdavid/LiteDB#310]
Hello,

Please consider the following simple example:

```
var filename = "catalog.db";
var guid = new Guid("9a731148-cd7a-4745-815d-7f5ea5e76af3");

if (File.Exists(filename))
    File.Delete(filename);

using (var db = new LiteDatabase(filename))
{
    var collection = db.GetCollection<Dictionary<string, object>>("items");
    var doc = new Dictionary<string, object>()
    {
        { "Guid", guid },
        { "Array", new double[] { 4, 3, 1 } },
    };
    collection.Insert(doc);

    doc = collection.FindOne(Query.EQ("Guid", guid));
}
```

Unfortunately collection.FindOne throws an InvalidOperationException "Sequence contains no matching element". Commenting out the "Array" key-value causes this example to run successfully.

Any ideas?

Thank you in advance!

**Comment by mbdavid** [comment]
Hi @superware, thats a implicit convert problem. Try use: `{ "Array", new BsonArray(4, 3, 1} }`

**Comment by superware** [comment]
Hi mbdavid,

Thank you for your prompt response.

Unfortunately, I have no control over the "document" properties, these entities know nothing about LiteDB. Why shouldn't an array map into an array of compatible type?

Thanks!

**Comment by mbdavid** [comment]
I think are missing, in BsonValue(object value) ctor, tests for array or inner dictionary. I will made some tests in my dev branch

**Comment by superware** [comment]
Ok, thanks!

**Comment by superware** [comment]
Hi mbdavid, can this be easily fixed?

**Comment by mbdavid** [comment]
Hi @superware, it's easy to fix but now I'm in vacation :) I will try to fix during next week.
