### ISSUE TITLE
Questions. Basic example Error Platform not initialized

### ISSUE THREAD

**Issue by AlexeiVasilenko** [mbdavid/LiteDB#312]
{LiteDB.PlatformNotInitializedException: LitePlatform not initialized.
   at LiteDB.LiteDatabase..ctor(String connectionString, BsonMapper mapper)

 on this line erorr -> using (var db = new LiteDatabase(@"C:\work\Solutions\MyData.db"))
                {
                    ...
                }

How can I initialize this platform?
Also I have another question, how can I get entries by second level object property? ex. {a:{b:1}} findAll(a.b == 1) and update second level object or even third level (ex. update Update(a.b, 2).

**Comment by mbdavid** [comment]
Hi @AlexeiVasilenko, take a look here for initialization

https://github.com/mbdavid/LiteDB/wiki/Portable-Version

and here for DbRef

https://github.com/mbdavid/LiteDB/wiki/DbRef

**Comment by AlexeiVasilenko** [comment]
Hi @mbdavid, thank you for the answer, but I still can't make it work on my ASP Core app, I've already downloaded master brunch, and tried to reference to LiteDb.dll, but it's possible only through the Nuget manager. Are you planning to make it available from Nuget and when? I mean realization of LitePlatformFullDotNet and etc.

**Comment by sgrassie** [comment]
@AlexeiVasilenko 2.0.2 won't work on ASP.NET Core applications. There was a pull request merged in recently which adds this support, but a release hasn't made its way onto NuGet yet.

**Comment by mbdavid** [comment]
Hi @AlexeiVasilenko and @sgrassie, I merge PR with support to core app but I didn't do all tests. I prefer made all tests before upload to nuget version to avoid errors. Next weekend I will made this

**Comment by sgrassie** [comment]
@mbdavid I totally agree it's best to ensure you are happy with the all tests etc before you upload to NuGet.

I'm impatient however, so I'm building it locally for my project, which isn't (yet) a public project 😄

**Comment by AlexeiVasilenko** [comment]
@mbdavid, Hi, have you already make liteDB works with dot net core?

**Comment by mbdavid** [comment]
Hi guys, test new v3-beta build in netstantard 1.4
