### ISSUE TITLE
Question: Does LiteDb loads everything in memory?

### ISSUE THREAD

**Issue by raizam** [mbdavid/LiteDB#313]
I couldn't find a clear answer to whether LiteDb loads everything at once.

I'm building a game which needs a database for storing game state data, which will be a big database.
Is LiteDb suited for this need?

Thanks

**Comment by mbdavid** [comment]
Hi @raizam, No. LiteDB is not a plain json file that needs load everything to memory. Documents are storaged in fragmented data pages (each page has 4096 bytes). Every page loaded are keep in memory until reach 5000 pages, when a recycle process clear pages.

And yes, you can use for gaming. LiteDB keeps working in 3.5 for Unity support. If you need better performance, try not work with big documents. Fragment you document in several collections and load gradual only when you need.

**Comment by raizam** [comment]
Thanks for the answer, this is clear to me.
I was wondering if LiteDb is more like a cache, just like Redis is.

I'll give a try then
