### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by rmszc81** [mbdavid/LiteDB#317]
Good night.

Does LiteBD offers async support?

If the answer is no, it's planned for the future releases?

Thanks a lot.

**Comment by mbdavid** [comment]
Hi @rmszc81, current version is not thread safe, so it's not possible to be async (you can read more here #124)

But, in next v3, LiteDB is converted to thread safe. Than, maybe it's possible to commit (write data to disk) can be async. It's on my README to think about.

**Comment by rmszc81** [comment]
Thanks for the quick answer my friend.

I hope that v3 come soon.

Regards,
[]
