### ISSUE TITLE
LiteCollection.Delete(Query) does not match id

### ISSUE THREAD

**Issue by CaptBrick** [mbdavid/LiteDB#318]
I expected the following two lines to do basically the same thing, yet LiteCollection.Delete(Query) does not delete anything and  LiteCollection.Delete(BsonValue) does

collection.Delete(Query.EQ("Id", @event.Id)); //nothing gets deleted
collection.Delete(@event.Id); //one item deleted, as expected

Event.Id is a Guid, event was inserted like this:

collection.Insert(@event);
collection.EnsureIndex(e => e.Id, new IndexOptions() { Unique = true });

**Comment by mbdavid** [comment]
Hi @CaptBrick, Id is a special field. So, when LiteDB convert your class to Document, your Id field (or any field marked as BsonId) use `_id`. In this case, you can use:

`collection.Delete(Query.EQ("_id", 123));`

**Comment by nerai** [comment]
I've tripped over this behavior myself in the past. I was able to solve it rather quickly, but found it pretty confusing. I believe it would be sensible to make `Id` less of a special case, and let it behave just like other fields.

**Comment by mbdavid** [comment]
@nerai, I believe in this case LiteDB will throw an duplicate key exception (in Dictionary) or override you x property with _id property (as _id field). I used `_id` to be more MongoDB like. Primary key is a special unique index. I need this index to update/delete any document.

**Comment by CaptBrick** [comment]
@nerai +1 It is really confusing
