### ISSUE TITLE
stuct is not deserialized correctly

### ISSUE THREAD

**Issue by CaptBrick** [mbdavid/LiteDB#320]
All properties of deserialized struct are null/default. The following code reproduces the issue.

```
namespace LiteDB.Tests.Tests
{
    public struct StructValue
    {
        public string Field { get; set; }
    }

    public class Container
    {
        public Guid Id { get; set; }

        public StructValue Struct { get; set; }
    }

    [TestClass]
    public class StructTest : TestBase
    {
        [TestMethod]
        public void Struct_Test()
        {
            var m = new MemoryStream();

            using (var db = new LiteDatabase(m))
            {
                var col = db.GetCollection<Container>("col1");

                var id = Guid.NewGuid();
                col.Insert(new Container() { Id = id, Struct = new StructValue() { Field = "FieldValue" } });
                var item = col.FindById(id);
                Assert.AreEqual("FieldValue", item.Struct.Field);
            }
        }
    }
}
```

**Comment by mbdavid** [comment]
Hi @CaptBrick, current version of LiteDB offers 2 ways to how create instances/get/set values. One is using Emit class (which are very fast) and one using expressions (which if more flexible). For current version 2, I will still using those both version just keep compatible.

But, I'm working on new version (v3). This new version will works only with expression to be same class used in .NET 3.5 and Portable/NetCore version.

**Comment by CaptBrick** [comment]
@mbdavid As a workaround in my project I've registered custom Serializer/Deserializer to global BsonMapper. Is there a better way to to this? How can I switch to expression get/set for a single type? Also I don't see a v3 branch on github. Is v3 the current dev?

**Comment by mbdavid** [comment]
Yes, v3 is dev branch. But, for now, it´s only avaiable LiteEngine, a new lower data access layer. This layer does not works with POCO classes (only BsonDocument).
For now, the better solution is use custom Serializer/Deserializer functions. Change Emit to Expression reflection needs create a new LitePlatform (works only with portable version).

**Comment by mbdavid** [comment]
Now works in v3-beta. If you found any problem, please re-open this issue.

**Comment by 0xFireball** [comment]
Guid and DateTime are still zeroed when objects are loaded from database:
Code:
```
public class UserSession : DatabaseObject
    {
        [JsonProperty("id")]
        public string SessionId { get; set; } = Guid.NewGuid().ToString("N");

        [JsonProperty("userAgent")]
        public string UserAgent { get; set; }

        [JsonProperty("startTime")]
        public DateTime StartTime { get; set; }
    }
```

`OpenOrCreateDefault` returns a static instance of a `LiteDatabase`.

When I load the object from the database, `Guid` and `DateTime` fields are reset.

Saving:
```
public static async Task<UserSession> GetSessionFromIdentifier(string identifier)
        {
            UserSession ret = null;

            var db = DatabaseAccessService.OpenOrCreateDefault();

            // Get logged requests collection
            var loggedRequests = db.GetCollection<UserSession>(DatabaseAccessService.LoggedRequestDataKey);
            // Log by descending timestamp

            ret = loggedRequests.FindOne(x => x.SessionId == identifier);

            return ret;
        }

        public static async Task SaveSession(UserSession session)
        {
            var db = DatabaseAccessService.OpenOrCreateDefault();
            // Get logged requests collection
            var loggedRequests = db.GetCollection<UserSession>(DatabaseAccessService.LoggedRequestDataKey);
            // Use ACID transaction
            using (var trans = db.BeginTrans())
            {
                // Insert new session into database
                loggedRequests.Insert(session);

                trans.Commit();
            }
            // Index requests by identifier
            loggedRequests.EnsureIndex(x => x.SessionId);
        }
```
