### ISSUE TITLE
Dependency Injection support?

### ISSUE THREAD

**Issue by raizam** [mbdavid/LiteDB#325]
Hi,

I'm just getting started, and I have a question about the POCO, which litedb requires a public parameterless constructor.
Would it be possible to implement a IoC/dependency injection mechanism, where I can pass a Func<T> to liteDb as a instanciation resolver?

If not possible then I'll be looking in the source where POCO are instanciated on deserialization, and I'll implement it :)

Thanks

Edit: so I've found where objects are instanciated, at [BsonMapper.Deserialize.cs L155](https://github.com/mbdavid/LiteDB/blob/d6e920efd4d5bd0e76613e1bfd98370b211777d6/LiteDB/Serializer/Mapper/BsonMapper.Deserialize.cs#L155)
I know custom serializers are availlable, but I want to use the  property mapper and at the same time resolve types with parameterized ctors

**Comment by mbdavid** [comment]
Hi @raizam, thanks for your PR, I will take a look closer. But for now, I'm working in `dev` branch for next release - this next release will change a lot from now. My plans is keep v2 as is, works only in bugfix.

Is `Emit` reflection supported in NETStandatd?

**Comment by raizam** [comment]
Hi @mbdavid, I do not know much about .NETStandard, but I'll take some time too see if the code I added works as expected.

If everything runs fine, I don't see how these addition could affect anyone else, I believe it should be fine.
The IoC support don't change any behavior, and no Api break.

The Struct property support might affect users that used public structs properties as transient data. But it should be uncommon, and I'm not sure if even it's the case, it would affect that much. But still this is indeed a behavior change, even is it's very minor. Anyway I have my own branch, so I'm fine if it's not merged :)

What will be the main changes in the next version you are working on?

**Comment by mbdavid** [comment]
Hi @raizam, the main change in next version is transforma LiteDB in a thread safe database. Also, LiteDB will support multi key index (index all values from an array document field). All this changes (an others more) are on database engine.

In portable area, my idea is convert LiteDB to NetStandard to avoid compile/initialize to many platforms. Next version will have only 2 version: .NET 3.5 and .NETStandard 1.3 compatible.

Now, I'm working on this upper layer: converting POCO entities to BsonDocument and Linq operations. Thats why this PR is important. I will merge them to my dev branch

**Comment by mbdavid** [comment]
Now I was checking your customTypeInstanciator. Isn't better to set new instance function only when nedded? Some like this:

```
BsonMapper.Global.Entity<Customer>((value) => new Customer())
    .Key(....)

or like this

BsonMapper.Global.Entity<Customer>()
    .Ctor(() => new Customer())

```
Where `value` parameter is BsonValue from document?

**Comment by raizam** [comment]
well good question. 
My plan was to use an external dependency injection library, which is LightInject. Let's say I use
`BsonMapper.Global.Entity<Customer>()
    .Ctor(() => new Customer())`

If class Customer has a constructor such as:
`public Customer(CustomerService service)`
LiteDb won't be able to resolve the service instance. That's why this should be a process external to LiteDb, how could it know how to resolve it? Dependency Injection libs are quite advanced and can be complex, so personnaly I would rather pass a global Func<Type, object> to liteDb.

Now another approach would be that LiteDb tries to resolve using the global func first, and then if it doens't provides a resolution, use Reflection.CreateInstance as fallback.

What do you think?

**Comment by raizam** [comment]
About the thread-safe database in the next version, I feel this is going to be quite a challenging feature to implement.

**Comment by mbdavid** [comment]
Hi @raizam, interesting point. In this case has much more sense to your way to initialize classes. Do you have an example with IoC in entity class?

About  thread safe: it´s 3th try about that. But now I beleave that works :) The main change now are that LiteDB open datafile in exclusive write mode, so only 1 instance can access datafile per time. It´s much faster and I re-use all memory cache. In v3, will be better keep single instance of LiteDatabase in a shared area (like an static instance) : https://github.com/mbdavid/LiteDB-Perf

**Comment by raizam** [comment]
v3 looks cool =)
Should I start using it now for a new project, or use v2 and upgrade afterwards?

Here is a basic IoC example using LightInject, but it's the same approach for most IoC containers:


    var container = new LightInject.ServiceContainer();
    container.Register<CustomerService>(new PerContainerLifetime()); //Single instance
    container.RegisterType<Customer>(factory => new Customer(factory.GetInstance<CustomerService>()));

Now that container is initialized, instance are resolved like:
      
    var customer =  container.GetInstance<Customer>();

Now that I added the typeResolver Func I can specify:

    BsonMapper(type => container.GetInstance(type))

**Comment by mbdavid** [comment]
You can use v2 for now and update after. The main change will be LiteDatabase instance - in v2 I recommed to use "open/close as soon as possible" and new version will be "keep single instance".

Yes, make all sense your code. I use a single "home-made" IoC in some projetcs, but not in entities classes. I will merge/adapt your PR to v3, sounds a good choice, thanks!
