### ISSUE TITLE
Help wanted about searching a substring in an array of strings

### ISSUE THREAD

**Issue by Boiethios** [mbdavid/LiteDB#329]
Hi,

I could not find any answer to this. Let's say we have this data structure:
```
public class Data
{
  public Data() { }

  [DataMember(Name = "Id")]
  public string Id { get; set; }

  [DataMember(Name = "Comments")]
  public List<string> Comments { get; set; }
}
```

When I want to find a substring in `Id`, I do:
```
var collection = database.GetCollection<Data>("myCollection");
var results = collection.Find(Query.Contains("_id", "my substring"));
```

But I cannot do the same in `Comments`. The following request returns nothing:
```
var collection = database.GetCollection<Data>("myCollection");
var results = collection.Find(Query.Contains("Comments", "my substring"));
```

How to search inside an array of strings?

**Comment by mbdavid** [comment]
Hi @Boiethios, in current v2 there is not index in arrays (named Multi Key Index). So, to this query works you need full collection scan: some like this:

```
collection.FindAll().Where(x => x.Comments.Any(z => z.Contains("substring"));
```

In v3 (`dev` branch under dev) multi key index was implemented. So, you can do full index scan (not best solution, but much better than full scan solution).

```
collection.Find(Query.Contains("Comments", "substring"));
// there is no Linq expression support yet
```

But, if you will have lots of documents that you need do this kind of search, I recommend to use "full text search". It's a special king of index used for this situations. LiteDB doest implement yet (I try once in `fts` branch, but did do sequence). You can take a look on Lucene.NET, a super index library.

**Comment by Boiethios** [comment]
Thank you for your help. The collection is small so I can do a full scan without problem. You have done a great job btw.
