### ISSUE TITLE
Find(x => true) throws "Not implemented Linq expression"

### ISSUE THREAD

**Issue by sergiorykov** [mbdavid/LiteDB#330]
version **2.0.2**

```
   at LiteDB.QueryVisitor`1.VisitExpression(Expression expr)
   at LiteDB.LiteCollection`1.Find(Expression`1 predicate, Int32 skip, Int32 limit)
```

**Comment by sergiorykov** [comment]
I found that `FindAll ` internally uses `Query.All(1)` and it is pretty useful. 

May be it'll be better in exception message provide a link to wiki with query customizations?

**Comment by mbdavid** [comment]
Hi @sergiorykov, it's not catch this king of error in LINQ. I update Wiki with more examples in LINQ expressions.
