### ISSUE TITLE
FileStorage.OpenWrite method

### ISSUE THREAD

**Issue by podkolzzzin** [mbdavid/LiteDB#333]
There is very useful method OpenRead in FileStorage, it would be nice to have such method for writing because now I had to load all data I want to Upload in memory

**Comment by mbdavid** [comment]
It´s done in v3 (but still in dev)

https://github.com/mbdavid/LiteDB/blob/dev/LiteDB/Storage/LiteStorage.cs#L28

**Comment by podkolzzzin** [comment]
Thanks, it's cool that you have already implemented it!
When v3 can be expected?

**Comment by mbdavid** [comment]
My plans is next month. Now only finish some last features and doing tests

**Comment by podkolzzzin** [comment]
Thanks. Looking forward to this release! Thanks for your quick response.

**Comment by mbdavid** [comment]
It's done in v3-beta in nuget! :)
