### ISSUE TITLE
field names starting with @ cannot be deserialized

### ISSUE THREAD

**Issue by vip32** [mbdavid/LiteDB#334]
JsonSerializer.Deserialize doesn't accept fields that start with a @ character
doing so throws an ArgumentException: Field '@t' has an invalid name.

is that for a special reason?

**Comment by mbdavid** [comment]
I wrote this rule (similar with variables name rules):
- must starts with letter, _ or $
- 2-N can be numbers and -

It's just to keep simple parse with Regex used in shell tool. And, by default, $ initial must be used only for internal controls (like DbRef).
