### ISSUE TITLE
Encryption support

### ISSUE THREAD

**Issue by dgodwin1175** [mbdavid/LiteDB#337]
Hi,
Does LiteDB encrypt the .db file by default?  I can't see any documentation on the support for encryption in the wiki.  Are there any examples of how it is done?  Note that I am using v2.0.

Thanks.

**Comment by mbdavid** [comment]
Hi @dgodwin1175 , no, if you want encrypt your datafile you must provide "password=" keyword in connection string.

https://github.com/mbdavid/LiteDB/wiki/How-LiteDB-Works#connection-string

**Comment by skylee91** [comment]
@mbdavid I think the URL should be updated to: <br>
 https://github.com/mbdavid/LiteDB/wiki/Connection-String
