### ISSUE TITLE
Database file compatibility

### ISSUE THREAD

**Issue by Friendship7** [mbdavid/LiteDB#338]
I have one question: Are database files (created with the same version of LiteDB) supposed to be binary compatible? Or in other words: If I create a db with a normal windows desktop application, should this db be usable by a UWP app using LiteDB.Core?

I was assuming this somehow, but first experiments showed this not to be the case. Since I couldn't finde a statement about this in the documentation, I now ask this question here.

Thanks for the great work.

Cheers, Stefan

**Comment by mbdavid** [comment]
Hi @Friendship7,

Assuming that you are using v2.x version and no database encryption, the answer is yes, must be compatible. Almost all source are the same, including file format. If you are using encryption, AES has different implementations in each platform.
If you are creating a multiplatform app, consider use only LiteDB.Core which are compatible with all platforms (LiteDB.Core.dll are PCL library)

In next v3 there is no more LiteDB.Core and LiteDB will be netstandard1.4 (no more multi-platform separate dll).

**Comment by Friendship7** [comment]
Thanks for the fast reply. It's good to know that the db files should be usable on all platforms.
