### ISSUE TITLE
 Not implemented Linq expression

### ISSUE THREAD

**Issue by VladimirHamburg** [mbdavid/LiteDB#339]
Hallo,

I isolated access to LiteDB in my code. And when I try to use lambda, as a parameter, this does not work.

```
static void test<T>(Driver driver, Func<T, bool> func)
        {
            var somethings = driver.Connection.Instance.GetCollection<GenericEntry<T>>(typeof(T).Name);
            Expression<Func<GenericEntry<T>, bool>> exp = ge => func(ge.Entry);
            var resultA = somethings.Find(exp).ToList();
        }
```

thx

**Comment by mbdavid** [comment]
Hi @VladimirHamburg, LiteDB implements only simple Linq support. `Find` method needs a Lambda expression like `x => x.Id == 1`. Can you write isolated example? I can debug QueryVisitor.cs to analyze if it's possible fix this.

**Comment by VladimirHamburg** [comment]
Hi @mbdavid . I made a example how I use LiteDB in my project. 
[Program.zip](https://github.com/mbdavid/LiteDB/files/590815/Program.zip)
It is code for a console app. I hope it can help.

**Comment by mbdavid** [comment]
Hi @VladimirHamburg, some questions:

1) Why are you using Wrapper<T> class?
2) Why method are not Expression<Func<T, bool>> ?
3) With current implementation, lambda expression doesent look like a resolvable expression. Using debug lambda expression is: `w => Invoke(value(LiteDB.Tests.Connection+<>c__DisplayClass3_0`1[LiteDB.Tests.Test]).lambda, w.Entry)` It's only an Invoke expression from an method.

**Comment by VladimirHamburg** [comment]
Hi @mbdavid .

1) I need wrapper, because my architecture is:
App -> GenericDatabaseApi -> ConcreteDatabaseConnection
My users do not know what database they are using.
I want to have something like this:
```
public void Add<T>(T something)
       {
            using (var db = new LiteDatabase(_dbpath))
            {
                var table = db.GetCollection<T>(typeof(T).Name);
                table.Insert(something);
            }
        }
```

but GetCollection need a concrete class. I can't use GetCollection<T>(typeof(T).Name).

2) I think, i have made it complicated in my code.
I have in my code something like this:

```
public List<T> GetByLambda<T>(Func<T,bool> lambda)
        {
            using (var db = new LiteDatabase(_dbpath))
            {
                var table = db.GetCollection<Wrapper<T>>(typeof(T).Name);
                var data = table.FindAll().ToList().FindAll(w => lambda(w.Entry));
                var result = new List<T>();
                foreach (var item in data)
                {
                    result.Add(item.Entry);
                }

                return result;
            }
        }
```

but i want that:

```
public List<T> GetByLambda<T>(Func<T,bool> lambda)
        {
            using (var db = new LiteDatabase(_dbpath))
            {
                 // this does not work
                var table = db.GetCollection<T>(typeof(T).Name);
                // and this does not work
                var result = table.Find(w => lambda(w.Entry)).ToList();
                return result;
            }
        }

```
thx

**Comment by mbdavid** [comment]
I removed this `new()` contraints. It's was valid a long time ago - I change all reflection lib. Need more tests but I beleave there is no problem with not using `new()` (see `dev` branch).

**Comment by VladimirHamburg** [comment]
Hi @mbdavid , it works! Thank you so much!
