### ISSUE TITLE
InvalidCastException or Could not load file or assembly 'query_yoxwar'

### ISSUE THREAD

**Issue by VinKamat** [mbdavid/LiteDB#34]
I am using litedb 1.0.1 via nuget, and when doing col.FindAll(), keep getting the following exception.

Could not load file or assembly 'query_yoxwar, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

When running the same FindAll() in Linqpad, I get..

[A]Customer cannot be cast to [B]Customer. Type A originates from 'query_yoxwar, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ...

Inserting worked just fine.

Any help is appreciated.

**Comment by mbdavid** [comment]
Hi @VinKamat, I will take a look better on this. I´m having some problens with _type definition added on 1.0.1 version. I recomend, for now, use 1.0.0 until i fix this (probably in weekend)

**Comment by VinKamat** [comment]
Figured out the issue by debuggin the litedb source.

Right now it forces that - code to insert (and the poco) and code to Find records must be from the same dll. Even if the namespaces are same, it just doesn't work. While deserializing it is visible that it expects this to happen and the type be matching and reflectively tries to load the assembly which was used to insert the records.

Hope this gets fixed soon.

Overall I love the library, great work!

**Comment by mbdavid** [comment]
Hi @VinKamat, can you test `master` branch in your app? I think the problem is in a `_type` attribute that was added when convert a poco class to `BsonDocument`.
