### ISSUE TITLE
Problem using auto generated service reference objects

### ISSUE THREAD

**Issue by MiklosPathy** [mbdavid/LiteDB#340]
Happiness unto thy souls!

We are using some data transfer objects, wich are published on WCF services. After that these are used in external utilities, by simply generate a .NET service reference.
The big idea was, using these generated reference objects with LiteDB. Of course it won't work... :(

The problem is, that Microsoft automatically generates some System.Runtime.Serialization.ExtensionDataObject ExtensionData fields in the objects. Something like this:
`
    public partial class StdCommObjectBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
`

The LiteDB serializer can serialize it, but it is unable to deserialize them. It gives the "Failed to create instance for type.... Checks if the class has a public constructor with no parameters" exception while tries to deserialize.

The auto generated code contains NonSerializedAttribute on the private field, and BrowsableAttribute(false) on the public property. Somehow Microsoft's serializer know how to handle these.

For workaround I simply inserted 
`            var ignore2 = typeof(NonSerializedAttribute);
            var ignore3 = typeof(BrowsableAttribute);
`

`                if (prop.IsDefined(ignore2, false)) continue;
                if (prop.IsDefined(ignore3, false)) continue;
`

into the LiteDB/Serializer/Mapper/Reflection.cs file, and rebuilt the LiteDB.
Now, it simply ignores these fields at serialization time, and it is capable to deserialize the objects.

Of course this hack only good for a short time, a more generic solution would be better. Some callback, or some strategy object feature here to decide what to ignore serialization time would be joyful. Any ideas?

Best Regards

**Comment by mbdavid** [comment]
Hi @MiklosPathy, `BsonMapper` are changing to be more simple create custom mappers. Next version will support override `BuildEntityMapper` and possible add some callbacks too (not yet implemented):

https://github.com/mbdavid/LiteDB/blob/dev/LiteDB/Mapper/BsonMapper.cs#L250

**Comment by mbdavid** [comment]
v3-beta released. You can write you own BsonMapper and change a simple override here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.cs#L394

You can override `GetTypeMembers` and filter members that you dont want.

**Comment by MiklosPathy** [comment]
Thank You!

The discrete charm of v3 beta, it can handle my objects out of the box, so I don't need to override anything. :)

**Comment by MiklosPathy** [comment]
Hi,

My happiness is compromised.
The problem returned with V3.0.0 stable. Until V3.0.0 Beta3 It worked fine in V3.0.0 out of the box, without any kind of BsonMapper override.

Is this planned, or just happened?
