### ISSUE TITLE
FileStorage.Upload causes duplicate index error

### ISSUE THREAD

**Issue by toxaris-** [mbdavid/LiteDB#341]
I have the following code:

      internal static void SaveImage(MemoryStream ms, string name)

      {
            using (var db = new LiteDB.LiteDatabase(@"ToxTV.db"))
             {
                  using (ms)
                  {
                        ms.Seek(0, SeekOrigin.Begin);
                        db.FileStorage.Upload(name, ms);
                  }
            }
      }

If there is already a file stored in with the same ID (in this case the name variable), I get an duplicate record exception. According to the wiki the record/file should be updated instead.

**Comment by mbdavid** [comment]
Yes, it´s a bug, wiki docs are right. I will fix this in master, thanks. Are missing a `Find` before insert. It´s already fixed in `dev` branch, new major release.

**Comment by toxaris-** [comment]
Super, thanks. I have read up today on the new v3, sounds very interesting!

**Comment by mbdavid** [comment]
v3-beta released and it's fixed there.
