### ISSUE TITLE
v3 DropCollection?

### ISSUE THREAD

**Issue by gmwilhelm** [mbdavid/LiteDB#344]
Hello,

how to drop a collection in v3?

v2 had LiteDatabase.DropCollection but to me it looks lie that is gone?

Regards,
  Dirk

**Comment by mbdavid** [comment]
I will back thsi method again to LiteDatabase. You can use db.Engine.DropCollection

**Comment by gmwilhelm** [comment]
Thanks for the answer.

Can you please explain what the difference is between LiteDatabase and LiteEngine?

What is the preferred usage of both?

Regards,
  Dirk

**Comment by mbdavid** [comment]
Hi @gmwilhelm, LiteEngine is like "the server side" of LiteDB. It´s responsable with all low layer data access. LiteDatabase use a instance of LiteEngine to access all method plus add all "mapper" things: Serialize/Deserialize, Cross References, AutoId, Linq queries and all this things. So, when you use LiteDatase, you are just using LiteEngine with support to POCO classes (LiteEngine works only with BsonDocuments)

I will add again this operations in LiteDatabase just to be compatible with v2 version, but basicly will call the same method from LiteEngine. LiteEngine is not new, exists in v2 but aren't public to user. Now, in v3, if you want works only with LiteEngine it´s possible.

I will try explain better in new wiki update.
