### ISSUE TITLE
v3 System.InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by gmwilhelm** [mbdavid/LiteDB#346]
When i try to query a collection with an index like:

`database.GetCollection<Person>("Person").Find(Query.All("FullName", Query.Ascending));`

i get this error message:

> System.InvalidCastException: Specified cast is not valid.
> at (wrapper castclass) System.Object:__castclass_with_cache (object,intptr,intptr)
> at LiteDB.PageService.GetPage[T] (System.UInt32 pageID) [0x00076] in C:\Projekte\LiteDB\LiteDB\Engine\Services\PageService.cs:48 
> at LiteDB.IndexService.GetNode (LiteDB.PageAddress address) [0x00010] in C:\Projekte\LiteDB\LiteDB\Engine\Services\IndexService.cs:326 
> at LiteDB.IndexService+<FindAll>d__13.MoveNext () [0x00023] in C:\Projekte\LiteDB\LiteDB\Engine\Services\IndexService.cs:348 
> at LiteDB.LiteEngine+<Find>d__8.MoveNext () [0x001c9] in C:\Projekte\LiteDB\LiteDB\Engine\Engine\Find.cs:32 
> at LiteDB.LiteCollection`1+<Find>d__17[T].MoveNext () [0x000a4] in C:\Projekte\LiteDB\LiteDB\Database\Collections\Find.cs:34 
> at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x0008b] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:99 
> at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00011] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:861 
> 

With a new empty database, the query works after adding some data to the collection and setting the index. But when i restart the app and then try to query the existing collection, i get the error message above.

**Comment by mbdavid** [comment]
Hi @gmwilhelm, is your database encrypted? Is for NETStandard? I will write some example to test.

**Comment by gmwilhelm** [comment]
No, the database is not encrypted.
Yes, i'm using netStandard.

**Comment by mbdavid** [comment]
Hi @gmwilhelm, I wrote some unit test but works fine. Can you post a small test about this issue?

**Comment by gmwilhelm** [comment]
Thanks for looking into it. It is working now.

I guess it was a sideeffect of #345

**Comment by alex-mazzariol** [comment]
I'm having this very issue with version 3.1.0 (which, to me, seems unrelated to #345) but only on one of my two development workstations - very weird, and thus I cannot isolate a test case. Does anybody have a clue on what I can further investigate to understand the problem? Otherwise I'll just have to look at the source code and give a try at psychic debugging...

**Comment by andrew-mi** [comment]
For the traveler, I had this issue after updating the definition of one of my classes. Both versions existed in the db at the same time and I was calling some LINQ that caused some problems.
