### ISSUE TITLE
Unity3D Support

### ISSUE THREAD

**Issue by tolstenko** [mbdavid/LiteDB#347]
Hello there! 

I imported your dll targeted to .net3.5 on unity, it inserts data to db without saying any error, but when I try to retrieve the data following the example, it fails. So I imported the code and changed a couple of C#6 expressions to a more compatible way(checking if cast is null, etc). Then I found out that the problem is the system reflection emit. Unity doesnt support it (and never will, I guess, it may open doors to interpreted code on iOS, apple rejects it most of time). Is there any version of LiteDB without emit?

[bug.txt](https://github.com/mbdavid/LiteDB/files/611237/bug.txt)

**Comment by tolstenko** [comment]
The version 2.0.4 worked for me. Just build for net3.5 . But the newest version doesnt work.

**Comment by mbdavid** [comment]
LiteDB v3 still in v3.5 just to be compatible with unity. If not working will be fixed to this (I never used Unity but has many request to be compatible with unity)

**Comment by mbdavid** [comment]
@izackp and @tolstenko, I change current compiler to C# 4 in master branch. Take a look there.

**Comment by tolstenko** [comment]
@mbdavid Just to clarify things: Unity is working to support C#5. It will be matter of time to support it, so dont prioritize this task if it means lots of efforts. Unity already updated their compiler, but it isnt integrated to editor yet. 
Unity developed a technology called IL2CPP, it means that all IL will be converted to CPP to be build using native compilers for mobile platforms and webgl. In order to work it limits the target net framework. My lucky guess is that in something around 4-6 months they will have this task done. 
So, for all means Unity suport 2.0 but it is almost feature complete for 3.5.

**Comment by mbdavid** [comment]
@tolstenko, the changes was minimal and already done. Only few points was changed to compile in C# 4 (because when I starts LiteDB doesn't exists C# 6).
