### ISSUE TITLE
FindAll and Query.All() not returning all results

### ISSUE THREAD

**Issue by bobbyg603** [mbdavid/LiteDB#348]
Hi,

I have a table with just over 10000 entries in it. I can view the table just fine with the LiteDB viewer, however when I try and get all documents in a table, I get a very small subset of the total documents.

Here's the code I'm using to get all results:

```
public static IEnumerable<TestResult> GetAllResults(IDatabaseSettingsProvider settingsProvider)    
{
    using (var db = new LiteDatabase(settingsProvider.DatabaseFilePath))
    {
        var testResults = db.GetCollection<TestResult>(settingsProvider.TableName);
        return testResults.FindAll();
    }
}
```

Am I doing something wrong? I've attached the database in question. Please help!

Thanks!
Bobby

[Database.zip](https://github.com/mbdavid/LiteDB/files/612235/Database.zip)

**Comment by mbdavid** [comment]
Hi @bobbyg603, your database are ok. I open here and has 14858 docs in shell tool. How are you calling this "GetAllResults" method?

**Comment by mbdavid** [comment]
If you problem persist, please re-open issue
