### ISSUE TITLE
Can it run in memory?

### ISSUE THREAD

**Issue by lidanger** [mbdavid/LiteDB#349]
I mean, when the app begins, LiteDB can load all data into memory, and then LiteDB synchronizes with the local file when the collection change.
Maybe it's not necessary, I only ask a question.

**Comment by mbdavid** [comment]
Yes it's possible. You can load you file to memory and initialize LiteDB using MemoryStream and when you want persist in disk, write from memory to disk. some like this:
```
var mem = new MemoryStream(File.ReadAllBytes("data.db"));

using (var db = new LiteDatabase(mem))
{
 // here, all database are in memory only
}

File.WriteAllBytes("data.db", mem.ToArray());

**Comment by lidanger** [comment]
Good.

**Comment by UweKeim** [comment]
Please note that you have to open the memory stream [this way](https://stackoverflow.com/a/20422875/107625), in order to be expandable:

```c#
using (var ms = new MemoryStream())
{
   // Do your thing, for example:
   m.Attachments[0].ContentStream.CopyTo(ms);

   return ms.ToArray(); // This gives you the byte array you want.
}
```
