### ISSUE TITLE
Open LiteDB database from .NET app resource?

### ISSUE THREAD

**Issue by win32nipuh** [mbdavid/LiteDB#35]
I have a small WCF web service. 
Now it has few web sites packed to LiteDB. 
When user requests web files it opens db and returns files and scripts.
It works ok.
I'd like to use LiteDB file (read-only) as embedded resource of this NET app
and open it when need.
One of reasons is: when it hosted in IIS sometimes it cannot open file because of permissions etc.
If it is resource no this kind of problems.

Is it possible to open LiteDB from NET resource?
From stream, memory?

**Comment by mbdavid** [comment]
Hi @win32nipuh! Now it's not possible because LiteDB needs a `FileStream` to do some operations like Lock/Unlock file/segments and create journal files. Its on my plans create a abstract layer to implement others stream inputs.

**Comment by mbdavid** [comment]
Hi @win32nipuh, just to know, current `master` branch now support generic `Stream` data source.
