### ISSUE TITLE
Xamarin Forms + prism

### ISSUE THREAD

**Issue by codemasterblackperl** [mbdavid/LiteDB#350]
When I tried to add the litedb from Nuget I am getting the following error.

Could not install package 'LiteDB 2.0.4'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by mbdavid** [comment]
Hi @codemasterblackperl, if you are running v2.x you must install `LiteDB.Core`.

But, I recommend you to use new v3-beta2 pre-release version `Install-Package LiteDB -Pre`. V3 are NetStandard in same `LiteDB` nuget (LiteDB.Core was discontinued)

**Comment by codemasterblackperl** [comment]
Thanks. I will try that. If I have any issues I will update the issue.

**Comment by codemasterblackperl** [comment]
Install-Package : Could not install package 'LiteDB 3.0.0-beta2'. You are trying to install this package into a project that targets 
'.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package LiteDB -Pre

this is the error I am getting when I tried to install

**Comment by mbdavid** [comment]
Hi @codemasterblackperl, I'm not a expert about Xamarin and portable apps. v3 uses NetStandard pattern. Maybe you need update your project, like see here:

https://xamarinhelp.com/dot-net-standard-pcl-xamarin-forms/
