### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shai-benshimol** [mbdavid/LiteDB#353]
I can't import LiteDB 3.0.0 beta in my project
Error     1          Invalid option '4' for /langversion; must be ISO-1, ISO-2, 3 or Default      LiteDB

**Comment by mbdavid** [comment]
Are using VS2015? I change this settings to be compatible with Unity3D and do not use some C# 6 features. You can change in you .csproj

**Comment by shai-benshimol** [comment]
We are using VS2010 in my work..

**Comment by shai-benshimol** [comment]
I'm using vs2010, which .csproj need to change? LiteDB or my project, and what to change?

**Comment by mbdavid** [comment]
You need change LiteDB.csproj to compile using default compiler. Take a look here

https://www.codeproject.com/tips/865579/how-to-change-targeted-csharp-version-in-visual-st

**Comment by shai-benshimol** [comment]
Thanks..
