### ISSUE TITLE
Some potential bugs

### ISSUE THREAD

**Issue by Lakritzator** [mbdavid/LiteDB#354]
Hi,

just wanted to report something I noticed by looking into your code.

I believe BsonDocument.TryGetValue is calling itself -> Stackoverflow,

I hope I misunderstood, as this would be a major bug and it would be hard to overlook the exception. :confused: 

Best wishes,
Robin

**Comment by Lakritzator** [comment]
Another potential issue I found:
LiteStorage OpenWrite has:
```
            // update metadata if passed
            if (metadata == null)
            {
                file.Metadata = metadata;
            }
```
Which probably should be:
```
            // update metadata if passed
            if (metadata != null)
            {
                file.Metadata = metadata;
            }
```

**Comment by Lakritzator** [comment]
Just to be sure you don't misunderstand me, I don't want to critisise you code!!!! I think it's a cool project, and very decent code! I just wanted to add something to improve the quality, and mistakes are made everywhere.

Besides the stuff above I found quite a lot of ArgumentNullException where the string with the name of the argument doesn't match the actual argument name. Most of the cases suggest that it was due to a refactored argument name, and the name in a string is not changed with it.

Which brings me to the question why you cannot use C# 6? I found many lines of code which can be improved, to have less maintenance and bugs, by using C# 6! I read somewhere that the reason is unity3d? Does the code of your library need to be compiled by unity 3d? Or is it just used by it? I am not familiar with that..

The next question is why you stay at .NET 3.5, maybe there is a very good reason for it... not saying you should update, but an update to 4.5 would make your code a lot smaller and easier to maintain. Probably quicker too... I wanted to add async support to your code, as I was thinking about using it from a UI, but this would not be so easy.

Another advice I can give, is wait for the new .csproj structure to be finished, it's currently very buggy, so you can have one project for multiple targets. This would simplify the solution a bit, and you will not loose any functionality.

**Comment by Lakritzator** [comment]
Some more observations:
You have multiple implementations of GetHashCode which reference a not readonly field, this could cause issues as GetHashCode is used to find an item inside collections etc. I believe they are only potential issues...

I had a look at ObjectId, upgrading to C# 6 will fix the issue, as you can make the properties "get only" which is like a readonly property... This would solve the "issue" in there.
(P.S. The Equals in ObjectId has a potential null-reference-exception)

With BsonValue the RawValue is used in the GetHashCode, you can modify the RawValue to be get only, the Type also needs it's set to be removed.

PageAddress is a struct, in pre C# 6 you will have issues... afaik with C# 6 you can also use a get only property,

**Comment by Lakritzator** [comment]
I found a lot of potential NullReferenceExceptions, you might want to do a code analysis and fix some of them.

P.S.
"Big freaking list of mime types" :smiling_imp:

**Comment by mbdavid** [comment]
Hi @Lakritzator,

First, no problem with you comments, not at all. Be free to to say what you think ;)

- About BsonDocument, fixed (BsonDocument now implement IDictionary so some methods are not tested)
- About OpenWriter, it's fixed too (it's new method too - in v3)
- Mime types list are terrible, but in .net35 there is no other option.
- I will run code analisys to check those NullReferenceExceptions

About be .NET35 and C# 4.0 - LiteDB keeps compatible with Unity3D because embedded database are great in simple/small/mobile/isolated enviorments. Full apps or web apps has many options in server databases (like Mongo/RavenDB).

I don't know how long LiteDB will be compatible with .net35. Maybe next one will be NetStandard only.

**Comment by Lakritzator** [comment]
I am not really familiar with Unity3D and fail to see what the C# version you use has to do with it being compatible. I would understand the framework version, but mostly the compiler and framework can be used separately. I used to compile Greenshot for .NET 2.0 with a C# version which was newer..

At least it should be possible to use "nameof" and some other things, to improve the flexibility of the code.
