### ISSUE TITLE
A demo for LiteDB 

### ISSUE THREAD

**Issue by ropean** [mbdavid/LiteDB#355]
Just a demo, to test the speed for insert.
But, it's too slow.
https://github.com/ropean/LiteDBDemo

**Comment by mbdavid** [comment]
Hi @ropean, you are using v2. In v2, you can't use multi-thread with a single LiteDatabase instance.

Try:
1) Update to v3-beta2 pre
2) Use a single LiteDatabase instance for all threads

This should improve, A LOT, your test performance. Take a look on this unit test concurrency/performance test:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB.Tests/Engine/ConcurrencyTest.cs
