### ISSUE TITLE
PredicateBuilder (AndAlso - OrElse)

### ISSUE THREAD

**Issue by aletfa** [mbdavid/LiteDB#356]
http://www.albahari.com/nutshell/predicatebuilder.aspx
When i use this builder to create an expression to send to LiteDB...
"Additional information: Not implemented Linq expression"
i think it depend by the usage of AndAlso and OrElse... i'm wrong?

```
if (my search parameters class contains something)
      predicate = predicate.And(x => ...)
...
int count = myLiteDBCollection.Count(predicate);
```

**Comment by mbdavid** [comment]
Hi @aletfa, I'm fixing this. The main probleam here is PredicateBuilder starts using a constant True or False. False is easy to convert, just use QueryEmpty, but True must be converted in a Query.All() so it's not good to performance (will do a full index scan in _id index).

**Comment by mbdavid** [comment]
Yes, fixed. I changed QueryAnd to not run QueryEmpty. Take a look on master branch
