### ISSUE TITLE
Maximum collection size?

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#358]
LiteDB looks great, although I'm slightly concerned about the 2GB file size limit in terms of future scalability for my application.

Am I correct in thinking that the maximum collection size on disk will be limited to 2GB? Are there any long term plans to extend this? Or is it hard limit for the foreseeable future?

Cheers

**Comment by mbdavid** [comment]
Hi @kuiperzone, 2GB file size limit is "per file in FileStorage" not per "datafile". Each physical datafile supports UInt.MaxValue * PageSize (4096) =~16 TB

**Comment by kuiperzone** [comment]
Excellent. Thanks for clarifying.
