### ISSUE TITLE
3.0.0 Beta - cannot add object without Id property

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#359]
I'm trying to add an object to a collection. It does not have an Id property and I'm getting the following error:

System.InvalidCastException : Specified cast is not valid.
   at LiteDB.BsonValue.op_Implicit(BsonValue value)

I note that this had been discussed before below and was reported fixed. Is this a bug?

https://github.com/mbdavid/LiteDB/issues/14

I'm really struggling with the design of LiteDB (or perhaps my inexperience with it) at the moment. The reason I'm trying to add object without the Id property is because I really want to call it something else but I don't seem to be allowed to do so very easily. Let me explain...

While I am aware of the [BsonId] attribute, the problem is that the data classes I have are defined elsewhere and I cannot simply re-design everything around LiteDB. I've been trying to implement a solution where I derive classes in order to provide an Id property and map it to a different one or specify [BsonId] on a different property (see below).

    public class TicketDoc : MarketTicket
    {
        [BsonId]
        public new long Timestamp
        {
            get { return base.Timestamp;  }
            set { base.Timestamp = value; }
        }
  }

But this results in a new class type which then forces me to copy data in order to convert it.

What I really need to be able to do is specify which property I want to use as the Id without having to use [BsonId] because this forces me to define a new class.

Is this possible?

**Comment by kuiperzone** [comment]
And several minutes later, I figured out it all by myself. Solution described below, but **I still want to ask about the System.InvalidCastException when there is no Id property**. I was of the understanding that one will simply be generated behind the scenes as described in issue #14. Is this no longer the case?

Solution: rather than derive a new class so that [BsonId] can be used, I discovered I can use BsonMapper as below, which is what I need.
`
            var mapper = BsonMapper.Global;
            mapper.Entity<MarketTicket>()
            .Id(x => x.Timestamp); // set your document ID

`

**Comment by mbdavid** [comment]
Hi @kuiperzone, I just add unit test about this and still working with no Id.

**Comment by kuiperzone** [comment]
Nope, I'm having a definate problem here. When I define a document with "Id", it works fine, as below:
`
    public interface IDocument
    {
        long Id { get; set; }
    }
    public class DummyDoc : IDocument
    {
        long _id = 0;
        double _dv;
        string _sv;

        public long Id
        {
            get { return _id; }
            set { _id = value; }
        }
}
`

However, if I rename "Id" to something else, then I get the error below:

1) SetUp Error : TRAL.TictocDB.Tests.SanityTest
LiteDB.LiteException : Invalid BSON data type 'Null' on field '_id'.
   at LiteDB.LiteEngine.UpdateDocument(CollectionPage col, BsonDocument doc)
   at LiteDB.LiteEngine.<>c__DisplayClass1_0.<Upsert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String colName, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Upsert(String colName, IEnumerable`1 docs)
   at LiteDB.LiteEngine.Upsert(String colName, BsonDocument doc)
   at LiteDB.LiteCollection`1.Upsert(T document)

**Comment by 0xFireball** [comment]
You can use this for an ID:
```csharp
[BsonId]
public ObjectId DatabaseId { get; set; }
```

I usually make a base class `DatabaseObject` with this property and inherit my data classes from that base class.
