### ISSUE TITLE
Why error occurs: "Invalid format: FileId"?

### ISSUE THREAD

**Issue by win32nipuh** [mbdavid/LiteDB#36]
I add file set to LiteDB.
For example: 
this file can be added successfully
F:\\monitor\\index.html

But this gives me an error about invalid fileid:
F:\\monitor\\css\\background.png

Why? When I comment this throwing exception it works ok.
How to avoid this kind of errors?

**Comment by mbdavid** [comment]
Hi @win32nipuh, can you post your code and error message?

`FileId` is not the same as full file path. `FileId` is more like a key for a file and used to as file reference. `FileId` pattern is like  a path (accept almost all chars, except `:`). Take a look on regular expression to validate:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Database/FileStorage/LiteFileInfo.cs#L19

**Comment by win32nipuh** [comment]
Hi, 
Ok, this is a piece of code, I really use file path as a file id because it seems a simplest way to generate fileid (imho)

 foreach (string f in filePaths)
 {
      string ff = f.Replace(path, path_to_keep);
      db.FileStorage.Upload(ff, f);
...

How I can generate fileid?

Regards,
Oleg

**Comment by mbdavid** [comment]
The idea to use `FileId` "like" a path are:

- Search files like search in a directory. So you can search files in that starts with "site1/css/" and you will get all files in this "folder" (I prefer use inverted slash `/`).
- Create a MVC controller to handle files as "physical" path, like:

`http://localhost/files/site1/css/default.css`

You can create a controller `FileController` that accepts a *path and get direct from LiteDB.

In this 2 options, you didn't have another collection to store more information about your file.
