### ISSUE TITLE
Big collection query throw a indexoutofrangeexception

### ISSUE THREAD

**Issue by gyn7561** [mbdavid/LiteDB#362]
I have a 4gb litedb file(v 2.0.4).

`collection.Exists(Query.EQ("_id", new BsonValue(id)))`

It throw a IndexOutOfRangeException 

break point
`return order == LiteDB.Query.Ascending ? this.Next[index] : this.Prev[index];

this.Next 's length equal 1;
this.Prev 's length equal 1;
index equal 1;

**Comment by mbdavid** [comment]
All data are in a single collection?

**Comment by gyn7561** [comment]
yes

**Comment by gyn7561** [comment]
yes

**Comment by gyn7561** [comment]
Sorry for my poor english.

This error did not happen everytime.

For example

`collection.Exists(Query.EQ("_id", new BsonValue( "0000000000a"  )))`
it return true;

`collection.Exists(Query.EQ("_id", new BsonValue( "0000000000b"  )))`
it return false;

`collection.Exists(Query.EQ("_id", new BsonValue( "0000000000c"  )))`
it throw a exception.

**Comment by mbdavid** [comment]
Can you post you document structure? I will try reproduce this.

**Comment by gyn7561** [comment]
```
    public class Model
    {
        public string Id { get; set; }
        public string Html { get; set; }
    }

```

Small database can't reproduce this exception.

I can provide my data file.

**Comment by mbdavid** [comment]
I run this test in v3

        [TestMethod]
        public void BigFile_Test()
        {
            using (var file = new TempFile())
            using (var db = new LiteEngine(file.Filename))
            {
                // create more than 4gb file
                while(file.Size < 4L * 1024 * 1024 * 1024)
                {
                    db.Insert("col", GetDocs(5000));
                } 

                // now lets read all docs
                foreach(var d in db.Find("col", Query.All()))
                {
                    // just read to check if there is any exception
                }

            }
        }

        private IEnumerable<BsonDocument> GetDocs(int count)
        {
            var rnd = new Random();

            for (var i = 0; i < count; i++)
            {
                yield return new BsonDocument
                {
                    { "_id", ObjectId.NewObjectId() },
                    { "html", TempFile.LoremIpsum(15, 50, 4, 10, 3) }
                };
            }
        }

**Comment by gyn7561** [comment]
My file is generate in v2.

https://onedrive.live.com/redir.aspx?cid=8d96eb95fb64279e&resid=8D96EB95FB64279E!3989&parId=8D96EB95FB64279E!107&authkey=!Ag3xWmMoKv25RKY&Bpub=SDX.SkyDrive&Bsrc=Share&ref=button

```
LiteDB.LiteDatabase liteDatabase = new LiteDatabase("巨灵新闻.litedb"); // Web news spider data
LiteCollection<Model> col = liteDatabase.GetCollection<Model>("col");
var isExisits = col.Exists(Query.EQ("_id", new BsonValue("0000000000000147h3")));  //It thorw a exception
```

**Comment by mbdavid** [comment]
Hi @gyn7561, I download your datafile but didnt found this _id documents. In all cases results was "false" (not exists).

Also, I upgrade your datafile to v3 and no error. Read all documents and convert them to new version

**Comment by gyn7561** [comment]
Thank you for sparing your precious time.
