### ISSUE TITLE
Shell for v3.0.0-beta2: Could not load file or assembly System.IO.FileSystem

### ISSUE THREAD

**Issue by vkocjancic** [mbdavid/LiteDB#364]
The error happens after I execute `show collections` command. Prior to that `open spm.db` command is issued which returns no error.

I have also tried running shell with filename as parameter. Problem persists.

```
Welcome to LiteDB Shell

Getting started with `help`

> open spm.db
> show collections
Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>
```

**Comment by mbdavid** [comment]
Is your LiteDB.dll is netstanard or net35? I just download from release page and works fine:

```
Welcome to LiteDB Shell

Getting started with `help`

> open app.db
> show collections
col
finish
> open app2.db
> show collections
> db.col1.insert {a:1}
{"$oid":"58488a1076849b22cce677de"}
> db.col1.find a=1
Index not found.
> db.col1.ensureindex a
true
> db.col1.find a=1
[1]: {"_id":{"$oid":"58488a1076849b22cce677de"},"a":1}
>
```

**Comment by vkocjancic** [comment]
netstandard, because I am using it in .net core project.

**Comment by mbdavid** [comment]
humm... will not work. LiteDB.Shell has referece only to LiteDB net35. If you want use netstandard you must reference NetStandard version of LiteDB
