### ISSUE TITLE
Insert with unique int Id in multithread app

### ISSUE THREAD

**Issue by qart2003** [mbdavid/LiteDB#366]
My code. Is Ok this not direct way ? (Simple and work, but how can I do it right?)
```C#
 public void InsertDoc(Doc doc)
  {
    using (var db = new LiteDatabase(m_fn))
    {
      var docs = db.GetCollection<Doc>(DALNames.docs);
      using (db.BeginTrans())
      {
        doc.Id = docs.Max(x => x.Id) + 1;
        doc.IID = doc.Id;
        docs.Insert(doc);
      }
      this.docs = docs;
    }
    if (this.docs.Find(x => x.Id == doc.Id).ToList().Count == 0)
    {
      System.Threading.Thread.Sleep(doc.Id % 5);
      InsertDoc(doc);
    }
  }
```

**Comment by mbdavid** [comment]
Current version still not supporting multithread to auto-increment Id in `int` datatype. But I'm implementing another way to get next id. This will be available in next release.

```c#
mapper.RegisterAutoId<int>(
    v => v == 0,
    (db, col) =>
    {
        var seq = "_sequence";
        db.BeginTrans();
        var next = 0;
        try
        {
            var current = db.Find(seq, Query.EQ("_id", col)).FirstOrDefault();

            if (current == null)
            {
                db.Insert(seq, new BsonDocument { { "_id", col }, { "value", 1 } });
                next = 1;
            }
            else
            {
                next = current["value"] = current["value"].AsInt32 + 1;
                db.Update(seq, current);
            }

            db.Commit();
        }
        catch (Exception)
        {
            db.Rollback();
            throw;
        }

        return next;
    }
);
```

**Comment by qart2003** [comment]
Thanks. I got 3.0 beta. What it mean threadsafe? My around are 150 users in internal workflow of company.
Probably I should using ReaderWriterLockSlim for every crud operation or no? (with 3.0 version)

**Comment by mbdavid** [comment]
Hi @qart2003, in v3 you can share same LiteDatabase instance across threads (no process). LiteDB use ReadWriterLockSlim to control lock access. Take a look in this issue thread #332

**Comment by qart2003** [comment]
Thanks, it is great

**Comment by qart2003** [comment]
Hi @mbdavid I placed in bin directory of small web app (phonebook of workers or company) dll v3.0 and got halt site. I thinking it means some errors are present in LiteDB v3.0. I reviewed error directory it has Application_error Exception in html format but not found something useful about LiteDB. (Only simple code with read collection and show it)
