### ISSUE TITLE
Serializing MongoDB ObjectId as a Dictionary Key

### ISSUE THREAD

**Issue by SeanMakins** [mbdavid/LiteDB#367]
Hey mbdavid,

Thanks so much for liteDB it really is fantastic! Quick question, I need to serialize MongoDB ObjectId's (use a mongo deployment in mLab and liteDB as a local "buffer") and I have added the following:

LiteDB.BsonMapper.Global.RegisterType<MongoDB.Bson.ObjectId>
(
    (oid) => new LiteDB.ObjectId(oid.ToByteArray()),
    (bson) => new MongoDB.Bson.ObjectId(bson.AsObjectId.ToByteArray())
);

and this works great for properties of ObjectId, however I have a property of Dictionary<ObjectId, string> and it seems to serialize it properly, but it cant deserialize it when retrieving it, I get an invalid cast exception {"Invalid cast from 'System.String' to 'MongoDB.Bson.ObjectId'."}

Any thoughts?

Thanks so much in advance!

-Sean-

**Comment by mbdavid** [comment]
Hi @SeanMakins, thanks for using LiteDB.

Basic deserialization of IDictionary must have a string as key. In this case, you can register this Dictionary<ObjectId, string>, some like this

```
mapper.RegisterType(typeof(Dictionary<ObjectId, string>), (o) => serializeCustomDict(o), (v) => deserializeCustomDict(v));
```

You can create serializeCustomDict and deserializeCustomDict based here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.Serialize.cs#L122

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.Deserialize.cs#L223

Having a fixed types (ObjectId and String) you can create your own convert key value (or you can store as a BsonArray { BsonDocument { Key = ByteArray, Value = String }).

**Comment by SeanMakins** [comment]
Thanks so much for the reply, managed to get what I need.

Cheers,

-Sean-
