### ISSUE TITLE
error 'invalid pageType' when Inserting items [3.0.0-beta2]

### ISSUE THREAD

**Issue by FroggieFrog** [mbdavid/LiteDB#370]
I'm trying to use LiteDB, but I always get an error. Hopefully you can spot the problem with help of the attached project.

[LiteDBTest.zip](https://github.com/mbdavid/LiteDB/files/642200/LiteDBTest.zip)

**Comment by mbdavid** [comment]
Hi @FroggieFrog, sorry for this long delay, I tested only now in curent 3.0.1 version and works fine. If your problem persist, please re-open. Thanks

**Comment by FroggieFrog** [comment]
I have updated to 3.0.1 and I get another error, when uisng FindAll (sorry for localized error message):
---------------------------
---------------------------
Error:

LiteDB.LiteException: Failed to create instance for type 'LiteDBTest.Model.DBViewItem' from assembly 'LiteDBTest.Model.DBViewItem, LiteDBTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Checks if the class has a public constructor with no parameters. ---> System.TypeAccessException: Fehler beim Versuch der Methode "DynamicClass._()", auf Typ "LiteDBTest.Model.DBViewItem" zuzugreifen.
   bei _()
   bei LiteDB.Reflection.CreateInstance(Type type)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei LiteDB.Reflection.CreateInstance(Type type)
   bei LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   bei LiteDB.BsonMapper.ToObject(Type type, BsonDocument doc)
   bei LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
   bei LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei LiteDBTest.Form1.button1_Click(Object sender, EventArgs e) in ...\LiteDBTest\LiteDBTest\Form1.cs:Zeile 64.
---------------------------
OK   
---------------------------

Both classes have a public, parameterless constructor. Please see attached project.
[LiteDBTest.zip](https://github.com/mbdavid/LiteDB/files/803301/LiteDBTest.zip)
