### ISSUE TITLE
No Insert(BsonValue, T) variant - v3.0.0-beta

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#373]
The Collection class has the following methods:

Upsert(BsonValue, T)
Update(BsonValue, T)

However, it lacks the equivalent for Insert(), namely:

Insert(BsonValue, T)

Is there a reason why it is missing?

This means that a document cannot be inserted (if it does not exist) with a specified Id value. The work around is to explicitly check that it does not exist and then insert it with a call to Upsert() rather than Insert().

**Comment by mbdavid** [comment]
Yes, is missing. All this ways to insert/update are just shortcuts to a `Engine.Insert` and `Engine.Update`.  I will add this in next release version.
