### ISSUE TITLE
Readonly connection is not respected - v3.0.0-beta

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#374]
It appears to be possible open a database in readonly mode and then modify it.

First off, I'm not clear from the documentation what the "readonly" keyname is. So if I've got this wrong, let me know. The document states:

**ReadOnly** (bool): Open database with only support to query (defult: false)

However, I cannot find the string literal "ReadOnly" anywhere in the LiteDB source. Instead, I find this in ConnectionString.cs :

this.ReadOnly = GetValue(values, "read only", true);

So is it "ReadOnly" or "read only"?

In any case, I run tests where I open the database with both variations as follows:

filename=E:\TRAL-2.0\SOURCE\TictocDB.NUnitTests\bin\Debug\data/dir1\dir2\readtest.0.ldb;read only=true
filename=E:\TRAL-2.0\SOURCE\TictocDB.NUnitTests\bin\Debug\data/dir1\dir2\readtest.0.ldb;ReadOnly=true

Both connection strings appear to open the database.

In both cases, however, it is possible to update an existing document in the collection with a call to Update().

When the database is closed and later re-opened, I confirm the document has been modified.

**Comment by kuiperzone** [comment]
After checking the LiteDB source futher, "read only" appears to be the correct name. Although it is case insensitive, there should be a space (correct me if I'm wrong). In any case, it doesn't work.

**Comment by mbdavid** [comment]
Yes, should be "read only" with space. But I will change this to `Mode`: `Shared`, `Exclusive` or `ReadOnly` values,
