### ISSUE TITLE
Question - Is v3 backward compatible with v2 data?

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#375]
Is v3 backward compatible with v2 data?

If I use v2 initially, could I upgrade to v3 later and will it read the data files generated by v2 seemlessly? Or would there be a migration proceedure?

**Comment by mbdavid** [comment]
LiteDB uses a new datafile structure, V7. So, will be not compatible with any older version.

But, I wrote some migration. It's possible call `LiteEngine.Upgrade` do convert V6 to V7 datafile or use `upgrade=true` on connection string

**Comment by kuiperzone** [comment]
Good stuff!
