### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by igkutikov** [mbdavid/LiteDB#376]
IndexService.GetNodeList(IndexNode node, bool includeInitial)

in go backward
the line var p = this.GetNode(next)
is mistaken
should be 
var p = this.GetNode(prev)

for now throws exception once it is the last one, and there is no next
this is probably a copy/paste error

**Comment by mbdavid** [comment]
Hi @igkutikov, thanks. Was a copy/paste error ;) It's fixed in master and I will publish new version soon.
