### ISSUE TITLE
Unity3d - Insert() Error

### ISSUE THREAD

**Issue by ttesla** [mbdavid/LiteDB#380]
I'm getting exception when I try LiteDB on Unity3d (5.4.2). The code is the example code in [getting started tutorial](https://github.com/mbdavid/LiteDB/wiki/Getting-Started). 

The exception is thrown at  "_**col.Insert(customer);**_" line. 

```
InvalidProgramException: Invalid IL code in (wrapper dynamic-method) System.Runtime.CompilerServices.ExecutionScope:lambda_method (System.Runtime.CompilerServices.ExecutionScope,object,object): IL_001b: call      0x00000007


System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, Boolean throwOnBindFailure) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Delegate.cs:268)
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Delegate.cs:276)
System.Reflection.Emit.DynamicMethod.CreateDelegate (System.Type delegateType, System.Object target) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection.Emit/DynamicMethod.cs:192)
System.Linq.Expressions.EmitContext.CreateDelegate (System.Runtime.CompilerServices.ExecutionScope scope)
System.Linq.Expressions.CompilationContext.CreateDelegate (Int32 unit, System.Runtime.CompilerServices.ExecutionScope scope)
System.Linq.Expressions.CompilationContext.CreateDelegate ()
System.Linq.Expressions.LambdaExpression.Compile ()
System.Linq.Expressions.Expression`1[LiteDB.GenericSetter].Compile ()
LiteDB.Reflection.CreateGenericSetter (System.Type type, System.Reflection.MemberInfo memberInfo)
LiteDB.BsonMapper.BuildEntityMapper (System.Type type)
LiteDB.BsonMapper.GetEntityMapper (System.Type type)
LiteDB.BsonMapper.SetAutoId (System.Object entity, LiteDB.LiteEngine engine, System.String collection)
LiteDB.LiteCollection`1[Customer].Insert (.Customer document)
LiteDBTest.DbTest () (at Assets/Scripts/LiteDBTest.cs:31)
LiteDBTest.Start () (at Assets/Scripts/LiteDBTest.cs:11)
```

**Comment by mbdavid** [comment]
Are you using v2 or v3?

**Comment by ttesla** [comment]
v3

**Comment by Ptitpopcorn** [comment]
Same code, same issue. Unity 5.5.0f3

**Comment by NatsXDLageg** [comment]
I am having the same issue.
I already added the needed dlls (before I did I was having another exception problem).
The exception is raised when I try to call the CreateCollection() method, when I call EnsureIndex().

`using UnityEngine;
using LiteDB;

public class SerializeSample : MonoBehaviour {

	private LiteDatabase db;
	private LiteCollection<Sample> collection;

	public class Sample	{
		public int id { get; set; }
		public string title { get; set; }
		public float time { get; set; }

		public Sample() {}
	}

	public void CreateDatabase() {
		this.db = new LiteDatabase (".\\Temp\\MyData.db");
	}

	public void CreateCollection() {
		this.collection = this.db.GetCollection<Sample>("samples");

		this.collection.EnsureIndex(x => x.title);
	}

	public void AddSample() {
		Sample sample = new Sample ();
		sample.id = 250;
		sample.title = "nathan";
		sample.time = 0.5f;

		this.collection.Insert(sample);
	}
}`

**Comment by xX-MLG-Xx** [comment]
how are you calling lite db from your classes in unity. remember unity is
timebased and would lead to the database failing. i suggest you add a
static instance and a queuing system + a seperate async thread which will
query the queue and then write to the db

dont do any database such via update (it will be called every 1/60 of a
second at lowest calling time/tick)

i think the database is just being locked constantly and eventual breaks
with the engine.

this can be tested write an external application which has a simple loop
which async runs the database code etc and then check the timeine between
it all and if it breaks. run this test 100 times with each test being run a
hundred times with diferent fps value or waits per second per loop

**Comment by NatsXDLageg** [comment]
@xX-MLG-Xx 
I call first the CreateDatabase() method, then the CreateCollection() one, and then the AddSample() one.
All this calls are made in a button action, sequentially; so they are not executing in loop.
If this part of my codes worked, I would call a print method to check the results of a query, using this.collection.Find(x => x.title.StartsWith("n"));

**Comment by xX-MLG-Xx** [comment]
Check LiteDBTest script tje issue is on line 11 @mbdavid

**Comment by mbdavid** [comment]
Hi guys, I change how LiteDB used getter/setter in .NET35 - remove Expression and backing to Emit. Please, try if working in Unity3D

**Comment by alexanderdean** [comment]
Nudge @xX-MLG-Xx @ttesla
