### ISSUE TITLE
How to implement nested Include in beta 3

### ISSUE THREAD

**Issue by dayus20** [mbdavid/LiteDB#381]
Hi,
To my understanding you implemented some way to nest multiple level of include (according to past issues). 
I have this situation : 

```
public ClassA {
    int id {get; set;}
    List<ClassB> myB {get; set;}
}

public ClassB {
    int idB {get; set;}
    List<ClassC> myC {get; set;}
}

public ClassC {
   int idC  {get; set;}
   ClassD myD  {get; set;}
}

public ClassD {
    int idD  {get; set;}
    string name  {get; set;}
}
```

I need to select all elements in classA but i need to get the name stored in ClassD. How would I do that?

**Comment by mbdavid** [comment]
I'm still working on this syntax on dev branch;

`col.Include(x => x.myB[0].myC[0].myD)`

**Comment by dayus20** [comment]
ok, thanks for the info. For now i'm using for loop to get my data.

**Comment by freezy** [comment]
Does `col.Include("myB.myC.myD")` currently (3.1.0) work?
