### ISSUE TITLE
upload file doesn store the binary

### ISSUE THREAD

**Issue by honfus** [mbdavid/LiteDB#383]
Hello,
I'm using the latest V3beta2 from nuGet.
Following code does store a part of the data like filename or upload but not the binary data of the jpg-file. Chunks and length got 0. Even the database file does not grow as expected and the exception is not raised.
`public LiteFileInfo uploadFile(string id, string fileName) {
            try {               
               LiteFileInfo fileInfo = db.FileStorage.Upload(id , @fileName);
               return fileInfo;                
            }catch(Exception ex) {
                return null;
            }            
        }

`
Filename is the hole path at the filesystem.
So as you see its nearly example code. Have I understood something wrong or is there a bug?

**Comment by mbdavid** [comment]
Thanks @honfus, was missing a `Flush()` in `Stream`. I'm commiting in dev branch I will merge later.

**Comment by honfus** [comment]
wow, thanks for the fast fix. I cloned the dev branch and it's working now as expected.
