### ISSUE TITLE
Support for decimal type

### ISSUE THREAD

**Issue by jozseffa** [mbdavid/LiteDB#386]
May I ask for supporting decimal .NET type?
For bson serializer I found some code that can be helpful 
https://github.com/Azure/azure-amqp/blob/master/Microsoft.Azure.Amqp/Amqp/Encoding/DecimalEncoding.cs

Thanks

**Comment by mbdavid** [comment]
Hi @jozseffa, did you mean native bson Decimal data type? By bson specification, decimal are converted to double value.

**Comment by jozseffa** [comment]
Yes, I mean native BSON Decimal128 representation. I found here more info:
https://github.com/mongodb/specifications/blob/master/source/bson-decimal128/decimal128.rst
Motivation to support decimal128:
BSON already contains support for  double  ( "\x01" ), but this type is insufficient for certain values that require strict precision and representation, such as money, where it is necessary to perform exact decimal rounding.

**Comment by mbdavid** [comment]
Wow, bson specs was updated :) I didn't know about that

http://bsonspec.org/spec.html

I will try implement this in v3. Thanks

**Comment by jozseffa** [comment]
Thank you!

**Comment by mbdavid** [comment]
I was reading about Decimal128 implemented in MongoDB and I dont undersand if is same as `decimal` C# datatype. It's safe to just implement as C# decimal?

**Comment by jozseffa** [comment]
See the reference implementation:
https://github.com/craiggwilson/mongo-csharp-driver/tree/decimal
It serializes 2 Int64, the Int64 is build up to  IEEE 754-2008 compatible representation of decimal128.
