### ISSUE TITLE
Shell needs decode a unicode character in a string

### ISSUE THREAD

**Issue by AlcoholV** [mbdavid/LiteDB#388]
When using unicode language, all of the string value is broken in shell.
The values looks like "\\u0625\\u0647\\u0644"
It looks like The Bsonvalue needs handle this.

I am using the Regex.Unescape method as a temporary.
https://github.com/AlcoholV/LiteDB/commit/d8b390aa047c35d354acacb592f27c65f4082298

I think there will be a better way. 
Cheeres!

**Comment by mbdavid** [comment]
Hi @AlcoholV, I will add this as suggestion. It's will be as option because it's better use `\u` format if you want export (spoll) data.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
