### ISSUE TITLE
Problem with big UInt64 values

### ISSUE THREAD

**Issue by jozseffa** [mbdavid/LiteDB#389]
Using big UInt64 values like UInt64.MaxValue can not be converter to/from bson Int64, an overflow exception occurs.
Possible solution is on serialization:
```
    var bytes = BitConverter.GetBytes((UInt64)obj);
    var vint64 = BitConverter.ToInt64(bytes, 0);
    return newBsonValue(vint64);

```
deserialization:
```
    Int64 vint64 = (Int64)Convert.ChangeType(value.RawValue, typeof(Int64));
    var bytes = BitConverter.GetBytes(vint64);
    var vuint64 = BitConverter.ToUInt64(bytes, 0);
    return vuint64;

```

**Comment by mbdavid** [comment]
BSON doesn't support `UInt64`, only `Int64`. It's not possible change this serialization without affect current datafiles.

It's same problem in MongoDB. Take a look here:

http://stackoverflow.com/questions/13994498/how-to-store-unsigned-long-long-uint64-t-values-in-a-mongodb-document

**Comment by jozseffa** [comment]
Sorry, I mean the BsonMapper.Serialize and BsonMapper.Deserialize, convert to/from .net type UInt64.
My quick fix:
```
		else if (obj is UInt32)
		{
			return new BsonValue(Convert.ToInt64(obj));
		}
		else if (obj is UInt64)
		{
			var bytes = BitConverter.GetBytes((UInt64)obj);
			var vint64 = BitConverter.ToInt64(bytes, 0);
			return new BsonValue(vint64);
		}
```
```
            // simple ConvertTo to basic .NET types
            else if (_basicTypes.Contains(type))
            {
			if (type == typeof(UInt64))
			{
				Int64 vint64 = (Int64)Convert.ChangeType(value.RawValue, typeof(Int64));
				var bytes = BitConverter.GetBytes(vint64);
				var vuint64 = BitConverter.ToUInt64(bytes, 0);
				return vuint64;
			}
			return Convert.ChangeType(value.RawValue, type);
            }
```

**Comment by henon** [comment]
No need to use BitConverter. Actually to convert between Int64 and UInt64 you can just cast within unchecked( ) like this:

unchecked((UInt64)((Int64)value.RawValue))

This will cast -1 to UInt64.MaxValue without throwing IntegerOverflowException.

**Comment by mbdavid** [comment]
@henon, so, it´s safe to put here?

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.Deserialize.cs#L110

**Comment by henon** [comment]
I guess so. You could do UInt32 and UInt64 conversion before that line. 

Actually, instead of converting to an from BSON supported types I'd vote for extending BSON and save all basic .Net types without any conversion allowing queries with UInt64 that are not saved as potentially negative Int64, but that is another story for another thread.
