### ISSUE TITLE
BsonIndex unique is not working

### ISSUE THREAD

**Issue by AlcoholV** [mbdavid/LiteDB#390]
I set my property as unique.
 public class UserEntity
    {
        public int Id { get; set; }
        public string Platform { get; set; }
        public string Rank { get; set; }
        [BsonIndex(true)]
        public string NickName { get; set; }
    }

but when I check indexes in shell.
the index isn't set as unique.
Am i doing something wrong?

**Comment by mbdavid** [comment]
I made an unit test to check and it's fine. 

If this index already created before you change to unique will not work, because index are not re-created. In this case, you need call `EnsureIndex`

**Comment by AlcoholV** [comment]
Thnak you. you're right.

**Comment by AlcoholV** [comment]
So the index are created after the indexed query. 
now i got it. XD
