### ISSUE TITLE
BUG: 3.0.0 Recent Dev Build - Concurrency Count - Upsert/Insert() blocking

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#392]
@mbdavid,

I've ran some concurrency tests and I think there is a problem. I'm checking on the Collection.Count property and an update made by an external process does not seem to show in an update.

I'll try to describe what I'm doing precisely. I'm testing against a recent "dev" build of 3.0.0 in which you added concurrency.

EXTERNAL PROCESS
I have an external write processes used by the unit test. On launch it does the following:

X1. Opens an existing database and collection but then does nothing for 1500ms.
X2. It adds just **one** dummy document to the collection using Collection.Upsert().
X3. It then sleep for a further 1500ms.
X4. It quits.

NB. In all my tests, there is just one Collection per LiteDatabase. I'm opening all DBs with a default (shared) connection string.

UNIT TEST
The unit test performs:

T1. It wipes the test directory of any previous file as part of a setup procedure.
T2. It creates a new database and collection and adds **one** initial dummy document.
T3. It then disposes of this database instance.

T4. It opens the database/collection (again) it has just created above. It does not attempt to read anything at this moment.

T5. It launches the EXTERNAL PROCESS and sleeps for 500ms to allow it to run and open the database itself. So at the end of this step, both the unit test and external process have the database open but nothing has been written other than the initial document added when the collection was created in T2.

T6. The unit test calls Collection.LongCount() to get the document count. At this stage, the EXTERNAL PROCESS is still in its first sleep so has not yet added a document. We expect the count to be 1, as we added an initial document in T2. Indeed, we get a result of 1 here. (NB. We have NOT opened a read-enumerator but simply called Count).

T7. The unit test now sleeps for 1800ms. This allows time for the EXTERNAL PROCESS to complete the sleep in step X1 and add a document to the collection as per step X2.

T8. The unit text calls Collection.LongCount() to read the document count again. Here, we now **expect the count to be 2**, as the EXTERNAL PROCESS should have added a new document to the initial one.

However, the test fails at T8 with a count of 1.

***
Additionally, here is some other information:

**Upsert() seems to block!!!***
When the EXTERNAL PROCESS runs, it is blocked at X2 until the unit test exits so never gets to add the new document in time. However, if I comment out step T6 (so that the test does not query the document count), then X2 runs fine and T8 is a success (test gives 2). Reading the Count in one process seems to cause adding (Upsert/Insert) in another to block (possibly indefinately).

I've tested with Insert() rather than Upsert() and Collection.Count() rather than Collection.LongCount(). Results are the same.

**Comment by mbdavid** [comment]
Hi @kuiperzone, I will review this at tonight. I will need write unit test to get where specific this error are occuring. By now, you can back to master branch (already merged from dev).

**Comment by kuiperzone** [comment]
Will test master and add update shortly. For now, here is a little more information:

Instead of calling Collection.LongCount() (or Count) in steps T6 and T8, I get an enumerator via Collection.FindAll(). In T6 I expect to MoveNext() just once, and in T8 twice. **AFTER T6 I call Dispose() on the enumerator.**

However, the result and behaviour is the same. Fails and Upsert blocks in the writer.

**Comment by kuiperzone** [comment]
Hi @mbdavid ,

Just tested against the latest master branch and **it works!!!**

Think this issue can be assigned as "not a bug".

Starting to love LiteDB. Thank you for all your support!

**Comment by mbdavid** [comment]
@kuiperzone, you're welcome. It´s great to know that more and more are using LiteDB. If any problem with this again, re-open this issue 👍
