### ISSUE TITLE
Question - serialization of readonly properties?

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#393]
Are read-only class document properties saved as Bson when inserting them to a collection?

For example, if I have a property with no "setter" as follows:

[code]
int SomeValue
{
  get{ return _val; }
}
[/code]

Is this value serialized as Bson?

The guide (link below) says that properties may be read-only, but I don't understand this when they cannot be modified.

https://github.com/mbdavid/LiteDB/wiki/Object-Mapping

**Comment by mbdavid** [comment]
Yes, read only property serialize results because can be indexed later.

```
pulibc int NameLength { get { return Name.Length; } }

// read only property can be indexed if exists on BsonDocument
var doc = col.FindOne(x => x.NameLength == 10);
```
