### ISSUE TITLE
Got an exception and I can't find the reason

### ISSUE THREAD

**Issue by lidanger** [mbdavid/LiteDB#400]
LiteDB Version : 2.04
System Version: Microsoft Windows XP Service Pack 3

Call Stack:

   System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID, Boolean setDirty)
   at LiteDB.PageService.GetFreePage[T](UInt32 startPageID, Int32 size)
   at LiteDB.DataService.Insert(CollectionPage col, Byte[] data)
   at LiteDB.DbEngine.<>c__DisplayClass21_0.<Insert>b__0(CollectionPage col)
   at LiteDB.DbEngine.WriteTransaction[T](String colName, Boolean addIfNotExists, Func`2 action)
   at LiteDB.DbEngine.Insert(String colName, IEnumerable`1 docs)
   at LiteDB.LiteCollection`1.Insert(IEnumerable`1 docs)

Model:

    public class Point
    {
        /// <summary>
        /// Gets or sets the code.
        /// </summary>
        /// <value>The code.</value>
        public string Code { get; set; }

        /// <summary>
        /// Gets or sets the time.
        /// </summary>
        /// <value>The time.</value>
        public DateTime Time { get; set; }

        /// <summary>
        /// Gets or sets the value.
        /// </summary>
        /// <value>The value.</value>
        public double Value { get; set; }

        /// <summary>
        /// Gets or sets the total.
        /// </summary>
        /// <value>The total.</value>
        public double Total { get; set; }

        /// <summary>
        /// Gets or sets the other.
        /// </summary>
        /// <value>The other.</value>
        public double Other { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="Point"/> is ok.
        /// </summary>
        /// <value><c>true</c> if ok; otherwise, <c>false</c>.</value>
        public bool OK { get; set; }

        /// <summary>
        /// 0=浓度 1=参数 2=流量
        /// </summary>
        /// <value>The type.</value>
        public int Type { get; set; }
    }

Some advice?

**Comment by lidanger** [comment]
When I remove the data file, there is no problem.
It seems a compatibility problem...

**Comment by mbdavid** [comment]
Hi @lidanger, there is no difference in datafile between 2.0 and 2.0.4. Changes in datafile are made only for v3. There are some bugs in v2.0.0 on concurrency access, but was fixed (as I know) in v2.0.4. If persist, let me know.

**Comment by lidanger** [comment]
No need maybe.I'll never change the version in the fulture in this project.
It's just a feedback now.
