### ISSUE TITLE
Shell

### ISSUE THREAD

**Issue by shai-benshimol** [mbdavid/LiteDB#401]
Hii,

How can i find all rows  between 2 dates using shell command?

**Comment by mbdavid** [comment]
Hi, to ue between:

`db.col.find age between [10, 50]`

If value is a date: `db.customers.find birthday between [{$date:"2001-01-01"}, {$date:"2010-01-01"}]`

Here are all options:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB.Shell/Commands/Collections/BaseCollection.cs#L74
