### ISSUE TITLE
From time to time some Miracles are present 

### ISSUE THREAD

**Issue by qart2003** [mbdavid/LiteDB#404]
Hi @mbdavid , I have created small web app It's phonebook of company
I have simple web page with for remove items.
The manager (not developer) sometimes kill item (user)
And after some time simetimes we will see removed users on pages
Why? protected void Page_Load(object sender, EventArgs e)
	{
		if (Request.QueryString.Count == 0)
			Response.Redirect("/");
		else
		{
			int id =  int.Parse(Request.QueryString.Get(0));
			VarStore.Space.users.Delete(x => x.IID == id);
			Response.Redirect("/");
		}

	}

**Comment by nictaylr** [comment]
You have to use transactions and `Commit` the result after modifying collections, see `v3` docs.

**Comment by mbdavid** [comment]
Hi @nictaylr, no, you dont need use transaction. When you run a simple insert, if you are not in a transaction, a new transaction are created and commit just after run the command.

@qart2003 Are you using v3? If not, remember that v1/2 are not thread safe, so you cannt share LiteDatabase across threads without locking

**Comment by qart2003** [comment]
Hi @nictaylr, @mbdavid with XMas and NY. I used V2. I have created three application on V2 and I need port it to V3. Whould you please provide to me simple code
I will run it once at global.asax in Application_Start
{
 ConvertV2ToV3(fn_db)
}
void ConvertV2ToV3(string fn_db)
{
?????????????????????????????
}

**Comment by mbdavid** [comment]
The easy way it just add "upgrade=true" on string connection and than LiteDB will auto convert to v3 if needed.

But if you want call this ugrade method, use:  `LiteEngine.Upgrade(....)` method

**Comment by qart2003** [comment]
@mbdavid Thanks, I saw it in #some_number. I dont know anything about "ConnectionString" except ConnectionString="filename"
I prefer code it means LiteEngine.Upgrade(....) method and after this will use ConnectionString="filename" but want to know about key feutures of ConnectionString cos probably will use LiteDB in average projects or big (many databases, per user database ...) 
Where can I see more examples of LiteDB
About V3 last version (cos readerwriterlockslim is inside LiteDB)
Should I use **the one** instance for write ops (created once at start app or session if db is per user)
And on every request using (new LiteDatabase***) for read ops

**Comment by mbdavid** [comment]
Hi @qart2003, documentation are not updated yet. I will first release final version before update.

Using `LiteEngine.Upgrade` are better if you know about your file and will call once. But if you will need always call update are same as add upgrade=true on connection string;

About concurrency, you can use single instance for all [read/write] (if you app are single process). If you are in a multi process, use one instance per operation.

**Comment by qart2003** [comment]
@mbdavid Thanks!
