### ISSUE TITLE
v3.0.0 - Latest - Bug with Query.LT() and Query.LTE()

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#407]
Find call with Query.LT() and Query.LTE() are not working for me (whereas GT and GTE work fine).

Here's what I'm doing:

I create a collection and insert 3 documents with _id values: 10, 20, 30

I call:

`return _liteCollection.FindOne(Query.LTE("_id", 22));`

However, **it returns document with ID of 10 (not 20).**

The same problem occurs with Find() as well as FindOne().

**Comment by mbdavid** [comment]
Using FindOne are right the result, but using Find must return both. Are not returning?

**Comment by kuiperzone** [comment]
With Find(), I was only interested in the first value on the iterator. The first one is incorrect, it is the same value returned by FindOne(). I simply tried using Find() because FindOne() wasn't giving the correct one. So it seems the same problem applies to both.

**Comment by mbdavid** [comment]
By default, query runs in asc order. So, 10 is first value found that are less than 22. If you want 20 as first value, try use desc irder in Query

**Comment by kuiperzone** [comment]
I'm wondering about the usefulness in the way you describe that LTE and LT works. What I mean is, if LTE run in ascending order and simply returns the first value is finds, then surely to is always equivalent to simply returning the first value in the entire collection?

Not sure I understand, but in any case, yes, I want to search backward and find the first value LTE and LT a given id value in descending order. I've tried the following, but it doesn't seem to work either:

```
return _liteCollection.FindOne(Query.And(
                        Query.All("_id", Query.Descending), Query.LTE("_id", id)));
```

**I sure could do with an example here of how to do it?**

**Comment by kuiperzone** [comment]
OK. Thanks for getting back to me.

But I'm wondering what useful purpose it could possibly serve?

As I say, if LT/E runs in ascending order and simply returns the first value that is LT/E to the id, then surely the result **will always be** the first value in the collection.

**Comment by kuiperzone** [comment]
In other words:

`_liteCollection.FindOne(Query.LTE("_id", ANY_VALUE)); = _liteCollection.FindById(_liteCollection.Min())`

**Comment by mbdavid** [comment]
Yes, it's the same result. But only because FindOne is just a FirstOrDefault from Find. I will do some tests in mongodb to see how they works on this.

**Comment by mbdavid** [comment]
Here some tests made with mongodb

```
> db.col1.insert ({"_id":10})
WriteResult({ "nInserted" : 1 })
> db.col1.insert ({"_id":20})
WriteResult({ "nInserted" : 1 })
> db.col1.insert ({"_id":30})
WriteResult({ "nInserted" : 1 })
> db.col1.find ({_id:{$lt:22}})
{ "_id" : 10 }
{ "_id" : 20 }
> db.col1.findOne ({_id:{$lt:22}})
{ "_id" : 10 }
> db.col1.find ({_id:{$lt:22}}).sort({_id:-1})
{ "_id" : 20 }
{ "_id" : 10 }
```

Mongo use same logic, but has sort options. In LiteDB you must use OrderBy LINQ.

**Comment by kuiperzone** [comment]
```
> db.col1.find ({_id:{$lt:22}})
{ "_id" : 10 }
{ "_id" : 20 }
```

Ahh! I understand now. I see the use of LT/E, although it's not what I expected. Sorry, I'm not familiar with MongoDB -- LiteDB is my introduction to NoSQL.

Thank you for looking into it!
