### ISSUE TITLE
A LiteDB blog

### ISSUE THREAD

**Issue by cole2295** [mbdavid/LiteDB#41]
Hi !
I am a coder from china. I have fork a blog called [MZBlog](https://github.com/qihangnet/MZBlog), and change its db to LiteDB. This is [MZlog-LiteDB](https://github.com/cole2295/MZBlog-LiteDB).

I have not used LiteDB before , therefore if there is any mistake, please point it out for me.

And I have used your FileDB.

I am eagerly looking forward to your kindly reply!

Best Regards

**Comment by mbdavid** [comment]
Hi @cole2295, nice job! I was looking your source code and here some tips when using LiteDB.

- When you open datafile, close as soon as possible (use `using`)
- When you call GetCollection<T> use a variable and reuse this variable. This method always need search collection page - it´s fast, but you can avoid that
- Prefer use `Exists()` than `Count() == 0`. Exists stop when first document found
- In your document class, if you have a `get` only property as computed property, use `BsonIgnore` attribute - it´s avoid serialization/deserialization and use less disk space

SDS

**Comment by cole2295** [comment]
After received your reply, I have edit the codes.
Thanks a lot!
