### ISSUE TITLE
journal=false does not work in 3.0-beta3

### ISSUE THREAD

**Issue by pianzide1117** [mbdavid/LiteDB#410]
journal=false does not work in 3.0-beta3,but 3.0-beta2 does

**Comment by mbdavid** [comment]
yes, you right. Thanks... I change all lock process and forgot the `if` about journal. I;m fixing

**Comment by mbdavid** [comment]
I will add some unit tests about journal, I will keep this issue opened.

**Comment by pianzide1117** [comment]
excellent
