### ISSUE TITLE
LiteDatabase / 

### ISSUE THREAD

**Issue by 2mawi2** [mbdavid/LiteDB#413]
May i ask why there is no interface implemented for LiteDatabase and the partial LiteCollection ?
It would make testing so much easier.

**Comment by xX-MLG-Xx** [comment]
What you mean nothing implemented?

**Comment by 2mawi2** [comment]
I was looking for the ILiteCollection and ILiteDatabase interfaces. But they dont have interfaces.

**Comment by xX-MLG-Xx** [comment]
They wouldn't as they are sealed classes, what are you trying to achieve?

**Comment by 2mawi2** [comment]
I was trying to mock them with moq and unit test them with my repositories. How do I fake the db calls for the tests ? LiteDb.Tests uses a TempFile, but I dont really wanna test, if the db is working. Or am I missing something ?

**Comment by xX-MLG-Xx** [comment]
Do you unit tests, create a reqular ol file to use, separate your db logic.
Put it into a library ex (barnyardDB) has (Insert/update/delete) for each
db table

By making a library you can run your unit tests etc in an isolated
independent environment. While keeping the project accessable to ude the db
system (your own library wrapper)

**Comment by xX-MLG-Xx** [comment]
Then you can put sub classes like barnyardDB.animals class
barbyardDB.equipment class

Each class takes objects in form of Insert(animal/equipment newObj)
Update(animal/equipment oldObj, animal/equipment newObject)
delete(anime/equipment oldObject)

Delete / update can be overridento allow another paramter to specify which
property of equipment/animal class to be used (ex _id) which should be of
string type....

Better oop design. Imo
this My method and it works well.

**Comment by 2mawi2** [comment]
So you basically wrote your own wrapper, subclassed it and wrote the tests on that basis.
I presumably wont get around that. Thanks xX-MLG-Xx 👍

**Comment by mbdavid** [comment]
Hi @2mawi2 and @xX-MLG-Xx, just to know, LiteDB also support in-memory database just to unit test. You can use like 

```
using(db = new LiteDatabase(new MemoryStream()))
{
   ...
}
```

**Comment by xX-MLG-Xx** [comment]
Noted, he is trying to from my understand re-implement the LiteDatabase
etc... to ensure that said methods etc can be unit tested. He was looking
for an ILiteDatabase Interface. So he could write a unit test wrapper like.

public interface ILiteDatabase {
.... methods etc ...
}

public class UnitLiteDatabase {
  ... methods etcc...
..each method contains a logging function call...
}

**Comment by 2mawi2** [comment]
Hey mbdavid,
cool I haven't seen that. So there is no need for a mocked LiteDatabase, I can just pass in a temporary MemoryStream. That makes it easier. 

Cheers
