### ISSUE TITLE
Field has an invalid name on upgrading 1.0.5 to 2.0.4

### ISSUE THREAD

**Issue by tjmoore** [mbdavid/LiteDB#414]
I'm attempting to upgrade a database from 1.0.5 to 2.0.4 but the upgrade fails.

It doesn't appear to like spaces in field names?

```
.\LiteDB.2.0.4\tools\LiteDB.Shell.exe .\database.db --upgrade .\database_v2.db --exit
Welcome to LiteDB Shell

Getting started with `help`

> open .\database.db
open "database.db" (v1.0.4)
> dump > C:\Users\Tim\AppData\Local\Temp\tmp73D3.tmp
> open .\database_v2.db
open "database_v2.db" (v2.0.4)
> dump < C:\Users\Tim\AppData\Local\Temp\tmp73D3.tmp
Field 'Transparent Dark' has an invalid name.
>
```

The upgraded database ends up with no entries in the problem collection.

Opening the old database it seems happy to dump it and I can even query the collection from the shell without upgrading.

I can't post the exact content publically, but this gives an example of a collection entry that's a problem on upgrade. There's more content in each element in reality.

```
{
    "_id": {"$oid": "57fe86100dc86c3324b1a7c1"},
    "Name": "A Name",
    "Description": "Description",
    "Themes":
    {
        "Dark":
        {
            "Name": "Dark"
        },
        "Light":
        {
            "Name": "Light"
        },
        "Transparent Dark":
        {
            "Name": "Transparent Dark"
        }
   }
}
```

**Comment by xX-MLG-Xx** [comment]
Could "$oid" becausing the issue? Such that it should be "oid" and not
"$oid"

**Comment by tjmoore** [comment]
It's the field 'Transparent Dark' it complains about.

$oid is just the default object ID entry I guess. My class defines this to expose a unique Id, and that $oid is what gets dumped out when querying the collection via the shell.

`public ObjectId Id { get; set; }`

**Comment by xX-MLG-Xx** [comment]
How are you doing this "upgrade"? Shell, Or via commands manually?

**Comment by xX-MLG-Xx** [comment]
I suggest in the meantime that you do an sql dump of the entire database
and then do the update by run the sql script in a new version. It maybe a
bug in the upgrading procedure. Because it seems that what is happen is
that the fields value is being used as the field column name by mistake.

**Comment by tjmoore** [comment]
Via the shell in one line:

`LiteDB.Shell.exe database.db --upgrade database_v2.db --exit`

as above the shell expands this out into individual shell commands:

```
open database.db
dump > C:\Users\Tim\AppData\Local\Temp\tmp73D3.tmp
open database_v2.db
dump < C:\Users\Tim\AppData\Local\Temp\tmp73D3.tmp
```

**Comment by tjmoore** [comment]
I can do a fix but it's a messy workaround. I have to run a command first to dump the DB

```LiteDB.Shell.exe database.db --exec "dump > upgrade.tmp" --exit```

Then run a regex on the upgrade.tmp file to convert the field names

Then reimport
```LiteDB.Shell.exe database_v2.db --exec "dump < upgrade.tmp" --exit```

Noting for production purposes I need to be able to run the upgrade programmatically or scripted with no interaction. There is already a released product using v1.0.5 DB in the field and upgrades must be seamless.

**Comment by xX-MLG-Xx** [comment]
I'm busy taking a look at the upgrade code
1.0.5 to 2.0.4

**Comment by xX-MLG-Xx** [comment]
The current upgrade only support's upgrade from v6 to v7
I suggest you get the other copies of she'll which allow upgrades from v5
to v6 ... and say you got v1 you will need to do upgrade to v2 then to v3
then to v4 and then to v5

Once I get my laptop I'll downloaded the report and push a new upgrade
which allows specifying upgrades from version x to version y., where x and
y are user defined / user inputable via command string example
--upgrade:v3-v7

**Comment by xX-MLG-Xx** [comment]
@todo xX-MLG-Xx extend upgrade command for shell and litedb engine

**Comment by mbdavid** [comment]
Hi guys, it's a "simple" bug in this convertion. The problem is when 1.0.4 serialize your Dictionary  there is validation in key (support any string). But, when you try deserialize in 2.x BsonDocument key must be validate from here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Document/BsonDocument.cs#L51

v3 has no upgrade from v1 yet, but it's on my plans.

For now, change this method to returns always true.
