### ISSUE TITLE
File Storage Corrupted 

### ISSUE THREAD

**Issue by johnzens** [mbdavid/LiteDB#416]
Have been using LiteDB v3 beta 3 for sometime now and all features are working well but i ran into issues with the file storage. All file operations are working well but when i attempted to upload over 400 files around 800mb in size, litedb threw a system put of memory exception. Any further attempt at accessing the file storage then throws an invalid page cast exception, thereby corrupting the database. Specifically, the error says an empty page cannot be cast to an index page. I ran tests and i figured out that this only happens when over 400 files are attempted to be uploaded in a single transaction. I believe this is a bug. 

Also, have noticed that under all conditions, adding and downloading files from the database are amazingly fast but deleting files is slow.

**Comment by xX-MLG-Xx** [comment]
@mbdavid could the file page space be reused and expanded when needed.
Similar  to fat16 but using ntfs indexing structure, or perhaps store the
file system in chuncked file next to the Db itself. Your choice.

@johnzens are you running this on 32bit or 64bit as well. Net does have
limitations regarding byte arrays as it uses 32bit indexing 800mb are
8212bytes which is still in the index limit

Perhaps you're Db file exceeds your ntfs/fat16/fat32 or others file system
file size limit

Which file system are you using
And are you on 32bit or 64bit machine?

Before you do the upload transaction what is the file size of the database
file?

Kind regards.

**Comment by johnzens** [comment]
@xX-MLG-Xx I am running the test on a 64bit Window 8 system, it's using ntfs. I don't think the problem is with the db size. I created an empty database and then added about 400 files, that's when I first noticed the problem. Then I created a new database and added about 200 files,about 400mb in size, and everything worked well,I added another set of 200 files and all was well, the database size was about 800mb then I added 400 files and the error occurred again. The database size grew to 1.6gb but it was corrupted.

**Comment by xX-MLG-Xx** [comment]
It might be a file stream issue.

@mbdavid I try and see if changing the file write to write using chunks of
the file upload's when adding the file's to the Db

It could be a. Net stream issue or just that the 400 uploads of 800mb
file's
Or the internal litedb file Storage indexing needs to be checked out and
perhaps fixed.  Sounds like either a bug with the filestream and/or the
indexing which then fails to write to disk properly.

**Comment by johnzens** [comment]
@xX-MLG-Xx @@mbdavid
Have been able to resolve this issue. The problem occurs only if commit is called on a transaction involving such large file uploads. What i simply did was to remove transaction.commit and everything worked perfectly well. Thanks a lot for the support.

**Comment by johnzens** [comment]
To add, for anyone facing a similar problem, file uploads should be done outside a transaction.

**Comment by xX-MLG-Xx** [comment]
Technically any databases change is wrapped in an original transaction by
defualt

**Comment by mbdavid** [comment]
Hi guys, I'm almost offline last days. I will try reproduce this but it's complete no recommended use transaction and files. But I dont know if file was corrupeted or only cache with wrong page types.

In next change  I will add validation to avoid try upload a file inside a transaction. Files are stores in chuncks  that are a king of transaction.

**Comment by johnzens** [comment]
@mbdavid @xX-MLG-Xx I agree about file upload prevention in transactions, i realized after conducting several tests that litedb could handle file uploads running into several hundreds of megabytes as long as it is not done within a transaction. Now i have no problems with it anymore. Adding a checker to prevent this in a transaction would certainly assist in writing a bug free code.

**Comment by mbdavid** [comment]
Hi @johnzens, now I'm back. I will add this test preventing upload new document inside a transaction.

**Comment by johnzens** [comment]
@@mbdavid it's nice to have you back. Keep up the great work.
