### ISSUE TITLE
Documents not being saved

### ISSUE THREAD

**Issue by emrys90** [mbdavid/LiteDB#417]
I'm having an issue where sometimes documents do get saved and sometimes they do not. I get no error messages, and the count returned from the insert matches the number I am trying to insert. But when I restart the app, those records are not there. This is how I am saving the database
`    public static DatabaseResult ProcessPendingTransactions()
    {
        List<Model> pendingInserts = null;
        List<Model> pendingUpdates = null;
        List<Model> pendingDeletes = null;

        if (DatabaseManager.pendingInserts.Count > 0)
        {
            pendingInserts = DatabaseManager.pendingInserts.ToList();
            DatabaseManager.pendingInserts.Clear();
        }

        if (DatabaseManager.pendingUpdates.Count > 0)
        {
            pendingUpdates = DatabaseManager.pendingUpdates.ToList();
            DatabaseManager.pendingUpdates.Clear();
        }

        if (DatabaseManager.pendingDeletes.Count > 0)
        {
            pendingDeletes = DatabaseManager.pendingDeletes.ToList();
            DatabaseManager.pendingDeletes.Clear();
        }

        DatabaseResult dbResult = new DatabaseResult();

        if (pendingInserts != null ||
            pendingUpdates != null ||
            pendingDeletes != null)
        {
            string path = DatabasePath;
            ThreadStart ts = new ThreadStart(() =>
            {
                lock (asyncLock)
                {
                    using (LiteDatabase db = new LiteDatabase(path))
                    using (db.BeginTrans())
                    {
                        if (pendingInserts != null)
                        {
                            var results = pendingInserts.GroupBy(x => GetBaseType(x.GetType()));
                            foreach (var result in results)
                            {
                                LiteCollection<Model> collection = GetCollectionByBaseType(db, result.Key);
                                int r = collection.Insert(result);
                            }
                        }

                        if (pendingUpdates != null)
                        {
                            var results = pendingUpdates.GroupBy(x => GetBaseType(x.GetType()));
                            foreach (var result in results)
                            {
                                LiteCollection<Model> collection = GetCollectionByBaseType(db, result.Key);
                                collection.Update(result);
                            }
                        }

                        if (pendingDeletes != null)
                        {
                            var results = pendingDeletes.GroupBy(x => GetBaseType(x.GetType()));
                            foreach (var result in results)
                            {
                                LiteCollection<Model> collection = GetCollectionByBaseType(db, result.Key);
                                foreach (Model model in result)
                                {
                                    collection.Delete(model.Id);
                                }
                            }
                        }
                    }
                    
                    dbResult.Finished = true;
                }
            });

            Thread thread = new Thread(ts);
            thread.Start();
        }
        else
        {
            dbResult.Finished = true;
        }

        return dbResult;
    }`

I've tried running it in the same thread instead of using ThreadStart. I've tried not using a BeginTransaction. Nothing I do seems to work. It's random as well, sometimes it saves it, sometimes it does not.

**Comment by xX-MLG-Xx** [comment]
Copy your code to sperate file then do a design using flow charts of your
program execution form this part of it then rewrite it. It looks wrong from
an oop  point of view

**Comment by emrys90** [comment]
I'm not sure what you mean. For 99% of cases this has worked. It's worked fine for months. I'm just now running into certain cases where it doesn't, and I cannot figure out why because according to the result of collection.Insert it should be inserted.

**Comment by emrys90** [comment]
I've narrowed it down further. The insert seems to be working, but returning all records does not always seem to work. This method returns an empty collection sometimes, but other times returns all the records that were previously inserted. Any thoughts?

`
    public static IEnumerable<T> GetAll<T>() where T : Model, new()
    {
        lock (asyncLock)
        {
            LiteCollection<T> collection = GetCollection<T>();
            return collection.FindAll();
        }
    }
`

**Comment by emrys90** [comment]
I FINALLY figured something out. I had commented out the portion of my code that was the actual problem, so when I finally got to trying other things I didn't realize I had finally tracked something down.

The issue that I'm having is that LiteDB does not appear to be throwing exceptions if called from a separate thread. When I put all my original code in, and ran the inserts in the main thread, I'm finally getting error messages on the inserts. Is there a way I can keep running LiteDB from a separate thread but get the error messages?

**Comment by emrys90** [comment]
I'm sorry, this turned out not to be a LiteDB issue at all. I was not aware that Unity does not display exceptions that are thrown from a separate thread. Gotta love Unity, ugh.

**Comment by xX-MLG-Xx** [comment]
Awesome you have resolved this.

@mbdavid perhaps have an option when loading a database file which allows
users to specify a file path and or a type of error logging. Which would
help this issue in the long run.

**Comment by mbdavid** [comment]
Hi, there is and log class that you can implement Write method to your own output. I use this log to undersand with all commands are running as I exceptect in shell tool.
