### ISSUE TITLE
Nuget release v3 / netstandard

### ISSUE THREAD

**Issue by ninjabear** [mbdavid/LiteDB#418]
Hey @mbdavid ! 

Is there any news on when v3 will be released officially? We're shipping a .NET standard project ([the Snowplow dot-net tracker](https://github.com/snowplow/snowplow-dotnet-tracker/tree/release/1.0.0)) that uses litedb and cannot create an official release on nuget until all our dependencies are out of pre-release. 

Thanks!

**Comment by mbdavid** [comment]
Hi @ninjabear, I a bit late about this. By now is almost done. There is only few issues to review and fix is needed. After, I release final version and then will update documentation. I beleave one or two weeks will be in nuget final version.

**Comment by ninjabear** [comment]
Awesome! Thanks for the great work!
