### ISSUE TITLE
Assembly is not signed

### ISSUE THREAD

**Issue by podkolzzzin** [mbdavid/LiteDB#419]
I have just updated LiteDB via nuget but when launch my project found out, that LIteDB.dll is not signed.
Could you please sign the assembly?

**Comment by mbdavid** [comment]
Hi @podkolzzzin, will be signed in final (next) release.

**Comment by martinrotter** [comment]
Ping.

**Comment by DmitryEkimov** [comment]
LiteDb.dll is blocked by Microsoft Defender because not signed
