### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by ambyte** [mbdavid/LiteDB#42]
When to call
using (var db = new LiteDatabase(SettingsManager.DbFilePath))

an error occurs
A first chance exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll

but despite that, everything works

**Comment by mbdavid** [comment]
Hi @ambyte? This DbFilePath is in local machine? It´s a valid path? Are directory exists? When you open a database that do not exists datafile, LiteDB creates a new data file.

**Comment by ambyte** [comment]
Hi
I understood the reason.
In the constructor LiteDatabase in line this.Recovery.TryRecovery() LiteDb try open journal file, but it is missing, and in class RecoveryService in method OpenExclusiveFile this error appears.
But i don`t disable journaling.

**Comment by blackholeearth** [comment]
in my case directories did not exist. so

            var fulldir = System.IO.Path.GetDirectoryName(dbFilePath);
            System.IO.Directory.CreateDirectory(fulldir); 
            using (var db = new LiteDatabase(dbFilePath))
           {
