### ISSUE TITLE
DateTime storing problem

### ISSUE THREAD

**Issue by podkolzzzin** [mbdavid/LiteDB#420]
As for me the line "Fail" shouldn't be ever printed.
After a bit of debugging I understood that it's because you store DateTime with the less precision.
It would be interesting for me to read why you have done like this? As for me DateTime is only 8 bytes, and you have probably saved 1 or 2, or even lose something using string.

The code is:

           DateTime dt = DateTime.Now;
            var testId = ObjectId.NewObjectId();
            using (LiteDatabase db = new LiteDatabase("file.db"))
            {
                var doc = new BsonDocument();
                doc["t"] = dt;
                doc["_id"] = testId;
                db.GetCollection("Test").Insert(doc);
            }

            using (LiteDatabase db = new LiteDatabase("file.db"))
            {
                var doc = new BsonDocument();
                doc["t"] = dt;
                var dt2 = db.GetCollection("Test").FindById(testId)["t"].AsDateTime;
                if (dt != dt2)
                {
                    Console.WriteLine("Fail");
                }
            }

**Comment by mbdavid** [comment]
Hi @podkolzzzin, LiteDB stores DateTime using BitConverter. Did you check if date diff are not about timezone?

**Comment by henon** [comment]
Yep, I can confirm that. LiteDB stores DateTime with millisecond precision and truncates the nanoseconds. I think the reason is to be compatible to JSON/BSON. That is why I chose to save the Ticks instead and convert them back to DateTime.

**Comment by podkolzzzin** [comment]
There are perfect methods ToBinary/FromBinary in DateTime structure, you could probably use them

**Comment by mbdavid** [comment]
Hi @henon, LiteDB store in ticks.

        public void Write(DateTime value)
        {
            this.Write(value.ToUniversalTime().Ticks);
        }

I didnt know about ToBinary/FromBinary methods. It's not possible change now because all datafiles will be affected.

**Comment by galakt** [comment]
@mbdavid 

#### Version Used: 
3.1.0.0

#### Steps to Reproduce:

Declare the following

```
    public class Customer
    {
        public int Id { get; set; }
        public DateTime Time { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new LiteDatabase(@"MyData.db"))
            {
                var customers = db.GetCollection<Customer>("customers");

                var customer = new Customer
                {
                    Id = 1,
                    Time = DateTime.Now
                };

                customers.Upsert(customer);

                var item = customers.FindOne(x => x.Id == 1);

                Console.WriteLine(item.Time == customer.Time);
                Console.WriteLine($"{customer.Time.Ticks} {customer.Time.ToUniversalTime().Ticks}");
                Console.WriteLine($"{item.Time.Ticks} {item.Time.ToUniversalTime().Ticks}");
                Console.ReadLine();
            }
        }
    }
```



#### Expected Behavior:

> True
>636304619445968076 636304871445968076
>636304619445968076 636304619445968076 

#### Actual Behavior:

> False
>636304619445968076 636304871445968076
>636304619445970000 636304871445970000

**Comment by dropsonic** [comment]
@mbdavid I faced the same issue.
Original DateTime (`Ticks` property): 637310234309996491
`Ticks` property after I saved and read the value from LiteDB: 637310234309990000

**Comment by lbnascimento** [comment]
@dropsonic This is a limitation in the BSON specification, which LiteDB implements: dates are stores as UTC milliseconds since the Unix epoch.

If you want to keep all the precision from `DateTime`, you should store `Ticks`.

**Comment by dropsonic** [comment]
It seems inconvenient because I'd like to use auto-serialization of POCO.
According to the answer above, LiteDB store ticks so it is quite strange that this issue exists.

**Comment by henon** [comment]
> Hi @henon, LiteDB store in ticks.
> 
> ```
>     public void Write(DateTime value)
>     {
>         this.Write(value.ToUniversalTime().Ticks);
>     }
> ```
> 

@mbdavid: As dropsonic points out above, it is a fact that DateTime precision is lost, so I guess the `.ToUniversalTime()` is the culprit?

This is a massive pitfall which everyone who stores and compares loaded DateTimes will encounter. How about keeping the current format how it is for backwards compatibility for DateTime values saved until now but save all future values **without precision loss** and denote the newly saved values accordingly so that they are not interpreted as old DateTime values?

I think this issue should be reopened.

**Comment by martin-slater** [comment]
Just a me to to this as I have been bitten by it and now need to add a hack somewhere else to work around it. It is a surprising result and just wrong.  It would seem you could add a pragma to allow users to enable correct behaviour (serializing and deserializing a DateTime with compare equals).
