### ISSUE TITLE
@ small issues in new version of beta 3

### ISSUE THREAD

**Issue by SeanMakins** [mbdavid/LiteDB#422]
Hey Mauricio!

Found 2 small issues with the latest commits of beta 3

1. if you register MongoDB Id's with this code:

 LiteDB.BsonMapper.Global.RegisterType<ObjectId>
            (
                (oid) => new LiteDB.ObjectId(oid.ToByteArray()),
                (bson) => new ObjectId(bson.AsObjectId.ToByteArray())
            );

and then you try a simple find of .FindOne(x => x.id == ID);
you get a Not implemented exception thrown. This use to work in the earlier version of beta 3

and 2, this one is a simple fix, in your Upsert 

you have:

```
foreach (var doc in docs)
{
                    // first try update document, if not found, insert
                    if (this.UpdateDocument(col, doc) == false)
                    {
                        this.InsertDocument(col, doc);
                        count++;
                    }
                    _trans.CheckPoint();
 }

```
which will only return true if it inserts... Update returns false..

if you add 

```
foreach (var doc in docs)
 {
                   // first try update document, if not found, insert
                    if (this.UpdateDocument(col, doc) == false)
                    {
                        this.InsertDocument(col, doc);
                        count++;
                    }
                    **else count++;**
                    _trans.CheckPoint();
 }

```
it will increment for every update as well, which will return true if upsert is successful 

Cheers,

-Sean-

**Comment by mbdavid** [comment]
Hi @SeanMakins, 

I will review this issue about using mongo ObjectId. Thanks

About Upsert count, the reason to count is to know how many document you inserted when you batch many document once. If I always count, you never know how many was insert and how many was updated (total - inserted). Upsert do not return true if success because always are success (or insert document or update document).

**Comment by SeanMakins** [comment]
Hey!  Any word on the issue with  registering MongoDB ObjectId's still not working as of 3.1.0
LiteDB.BsonMapper.Global.RegisterType
(
(oid) => new LiteDB.ObjectId(oid.ToByteArray()),
(bson) => new ObjectId(bson.AsObjectId.ToByteArray())
);

Cheers,

-Sean-
