### ISSUE TITLE
Fluent Mapping API like Entity Framework style

### ISSUE THREAD

**Issue by rmszc81** [mbdavid/LiteDB#423]
Good night Mauricio.

It's a pleasure to talk to u again.

I have a "good" suggestion. Well, not really a suggestion, it's a need btw. Let's see some code:

--------------------------------
On EF I can do the following:

(context)
```C#
using System.Data.Entity;

using xxxxxxxx.data_access.legacy.config.mappings;
using xxxxxxxx.domain.legacy.config.model.interfaces;

namespace xxxxxxxx.data_access.legacy.config.contexts
{
    public partial class yyyyyy_context : DbContext
    {
        static config_context()
        {
            Database.SetInitializer<yyyyyy_context>(null);
        }

        public yyyyyy_context(string str_name_or_connection_string) : base(str_name_or_connection_string) { }
        
        public DbSet<i_zzzzzz> tb_zzzzzz { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // here we add the mapping class //
            modelBuilder.Configurations.Add(new tb_zzzzzz_map());
        }
    }
}

(mapping class)
using System.Data.Entity.ModelConfiguration;

using xxxxxxxx.domain.legacy.config.model.interfaces;

namespace xxxxxxxx.data_access.legacy.config.mappings
{
    public class tb_zzzzzz_map : EntityTypeConfiguration<i_zzzzzz>
    {
        public tb_config_map()
        {
            // mapping code here //
        }
    }
}
```
--------------------------------

So, it's possible to add mappings to BsonMapper on LiteDB like that?
I have the following implementation:

(context)
```C#
using System;

namespace xxxxxxx.data_access.current.config.contexts
{
    public partial class zzzzzz_context : LiteDB.LiteDatabase
    {
        public zzzzzz_context(String str_connection_string, LiteDB.BsonMapper bm_mapper) : base(str_connection_string, bm_mapper) { }
    }
}

(mapping class)
using xxxxxxxx.domain.current.config.model.interfaces;

namespace xxxxxxxx.data_access.current.config.mappings
{
    public class c_zzzzzz_map : LiteDB.BsonMapper
    {
        public c_zzzzzz_map()
        {
            this.Entity<i_zzzzzz>()
                .DbRef(u => u.i_aaaaaaa, typeof(i_aaaaaaa).Name)
                .Id(i => i.Id)
                .Index(i => i.Id, true);
        }
    }
}
```
--------------------------------

Thank you once again for such great tool like LiteDB.

[],
Regards

**Comment by xX-MLG-Xx** [comment]
this suggestion seems unnecessary in the sense of why would it be needed?
litedb is already well defined and mapping would over complicate the
library and cause further issues, fixes etc. but i leave this to david.

but note:
you're already extending litedb and trying to handle the mapping yourself?
for what purpose.

... this is a "hackjob" ... very bad ....

if you believe this is the right way then you're doing it wrong. imo
regarding my expertise

goodluck

**Comment by rmszc81** [comment]
@xX-MLG-Xx ,

professionaly speaking, if the Entity<T> returns a new EntityBuilder<T>, why not expose a list of this? for what reason?

(I really don't like to get into this kind of thing but you forced me.)

no one is questioning @mbdavid work, he's a very skilled professional and we can see this through his source code, so, "already well defined" as you said has no place in this discussion and, as you adequaly put, it's unnecessary.

as you can see, the word "good" was said between quotes and I put that way because I read the source code first before asking. :-)

another point is that seems that you didn't read all the text from que topic. didn't you see the question: "So, it's possible to add mappings to BsonMapper on LiteDB like that?", right?

the "very bad" term is the same as "it's not right" or "it's wrong". it doesn't say anything useful to who listen to it. instead of put people down, try to provide some solutions. be kind to others please.

backing to the topic, it's a question/suggestion. when I use EF, I have my mappings on different source files and they are all added on OnModelCreating event of context. so why wouldn't LiteDB won't have the "same"?

@mbdavid will be the man who will say if it's possible, or no. if there's alternatives, or no. 

about:
"
if you believe this is the right way then you're doing it wrong. imo
regarding my expertise
goodluck
"

again, you didn't said anything useful. if you can't help, just don't annoy it.

[],
Regards,

@rmszc81

**Comment by xX-MLG-Xx** [comment]
@Szczepanski apologies for the abrupt and mean reply didnt have my coffee
yet xD

yes david is very professional.

anything is possible.

you could take the current source and make changes to it

or

"another" solution which would aid in various user specific request like
yours would be if a LiteDB plugin manager was created.

allowing for various solutions to be added without modifying the actual
database source in a form of extensions.

LiteDB could expose a LiteDB.Plugin instance which would allow LiteDB to
load extension modules.

perhaps even a module like.

Bson Mapper Extension

the LiteDB Engine could then use event callbacks and other implementations
to parse the data etc to the plugin then once plugin is done processing it
would go back to the Engine itself.

this would be extremely useful for custom extensions for data mapping,
security, data encryption and others.

this is just an idea of my own.

so you could do as follows

LiteDB.Plugins.Init(class name here)
where the class name implements the LiteDB.Plugin Interface

this would only be needed to be called once when loading the engine

their by decoupling the database from the extensions by using the
interfaces etc..

for each class of LiteDB this could be added to query the plugin manager
and do said processing then return execution to the engine itself.

it could even incorporate a unit testing as such with an extension that
implement the plugin interface.

it would be easy to manage, update and do bug fixing

and keeping the LiteDB small in terms of size etc.  by allowing extensions
to be loaded on a per needs bases

@mbdavid what do you think?

some examples:
- unit test
- bson mapper
- encryption
- the worlds your ouster.

Regards Dean.

**Comment by henon** [comment]
@xX-MLG-Xx, I love that idea. First thing I'd write would be a plugin supporting all native .NET value types ;)

**Comment by rmszc81** [comment]
@xX-MLG-Xx, now you're talking, :-)

**Comment by xX-MLG-Xx** [comment]
i will put together something together for david over the next few days;
should have it ready online on the 18th jan 2017

will post a link to my repo of the LiteDB hosting the Plugin feature
system. when completed.

will create a few base sample extensions  aswell so other devs here can
play with and/or improve on and/or create their own as well.

all one would need to create the extension is to make a .dll with 1 or many
classes which implement the plugin interface.

simply doing LiteDB.Plugins.Init("filenamepath") or
LiteDB.Plugin.Iniy(type) will load the extension

kind regards Dean.

**Comment by xX-MLG-Xx** [comment]
i've planned to create a sync extension.

it will support syncing.

it will generate reports of new items. deleted items. etc.

and a 2nd extension which will be called a LiteDbConverter (supports
converting to and from a server or other nosql db system. mysql, mssql ,
mongo to name a few)

**Comment by mbdavid** [comment]
Hi guys, nice suggestions! In v3 I tried to be more modular possible. Thats why I expose LiteEngine as an external resource. LiteEngine is the "real" database engine (data structure, indexes, queries, concurrency, documents, ...).

Another modules are like "plugins", like BsonMapper/Linq/FileStorage. Ok, it's not based on interfaces and all are in same DLL, but it's to be still small and easy to use.

@rmszc81, about your question: Yes, you can implement like this. There is no problem but don't forget to always re-use same BsonMapper instance. You you always use `new CustomMapper()` you will not use cache mapper functions.

```C#
namespace xxxxxxxx.data_access.current.config.mappings
{
    public class c_zzzzzz_map : LiteDB.BsonMapper
    {
	// always use this instance
	public static c_zzzzzz_map Instance = new c_zzzzzz_map();
	
        public c_zzzzzz_map() : base(null)
        {
            this.Entity<i_zzzzzz>()
                .DbRef(u => u.i_aaaaaaa, typeof(i_aaaaaaa).Name)
                .Id(i => i.Id)
                .Index(i => i.Id, true);
        }
    }
}
```

In v3, I change a lot of BsonMapper class to be much more flexiable to map POCO to BsonDocument. Now you can create your own Mapper overriding only few methods. You can implement, per eg, private properties, change serialization/deserialization functions, .... without re-write all BsonMapper class. BsonMapper are passed as parameter on LiteDatabase class, so it's easy.

**Comment by rmszc81** [comment]
@mbdavid, thanks for quick answer. Is not what I was looking for but, I'll try to handle another way. What I'm doing:

It's a DDD project with dynamic injection, so, that's why I "needed" to "add" the mappings to the context. In EF I let each map on a class and add the map to a list of maps.

Btw, it's just a change of concepts. As the context is called from repository super type class, I'll add all the mappings once, so, there's no need to put each map on separated class as was done with EF.

Thank u again.

[],
Regards.

@rmszc81

**Comment by rmszc81** [comment]
@mbdavid btw, I'll explain what I tried to suggest, I think I wasn't clear:

```
Entity<i_type> o_entity = new Entity<i_type>();

o_entity.DbRef(u => u.i_field, typeof(i_field).Name);
o_entity.Id(i => i.guid_id)
o_entity.Index(i => i.guid_id, true);

LiteDB.BsonMapper.Entities.Add<i_type>(o_entity);
```
[The Entities would be a IList/ICollection/IEnumerable<Entity<T>>]

That's the main idea of suggestion. Create an entity object, fill properties and add it in "Entities" collection.

Sorry for not being so clear last time, in middle of dawn, I couldn't explain properly.

Thank u.

[],
Regards,

@rmszc81

**Comment by mbdavid** [comment]
Hi @rmszc81, did you mean expose `Dictionary<Type, EntityMapper>` in BsonMapper? This dictionary contains all mapped classes from/to POCO/BsonDocument (https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.cs#L31).

When you use EntityBuilder<T> you can create modify this EntityMapper for each type <T> you choose. It's not possible create an instance of EntityBuilder without BsonMapper becasue when you get an EntityBuilder from a type, first BsonMapper create the default entity mapper and than you can modify.

**Comment by rmszc81** [comment]
Yeah, sort of.

(btw, I speak portuguese too, as I saw on the other thread your "first opportunity to speak, hehehe", lol)

So, it's an architecture concept, now I understand some "why not is possible".

Do you have an example on how can I use EntityBuilder to achieve that idea?

**Comment by xX-MLG-Xx** [comment]
he means you can but you'll be required to obtain a entitybuilder from a
bson object and then override the enititybuild that the bson object uses.

if you are willing to wait a week or so.

i'll be releasing a plugin management api that can be used with litedb as
LiteDb.Plugin

which will allow you to accomplish your mapping requirements with a lot of
easy and without any bugs ^~^

kind regards
Dean Van Greunen
Dean9000@gmail.com

**Comment by rmszc81** [comment]
@ xX-MLG-Xx, it's a personal research project, so, there's no time to complete though,

I can wait one, two, three, four or more weeks, :-)

Thank you fot the efforts, you and @mbdavid .

BTW, if you want learn portuguese, I can help too. I think japanese easier (I was married to a japanese girl many and many years).

Cheers!

**Comment by xX-MLG-Xx** [comment]
yeah that be cool. I appreciate the offer. you can get in touch with me on
the following https://www.keybase.io/DeanVanGreunen

Kind Regards.
Dean.

**Comment by SouJack** [comment]
I don't know if you can help anyone yet, but recently I came across a need.
I created a simple class that emulates this behavior:

   `public abstract class MapeamentoPadrao<T>
    {
        protected EntityBuilder<T> Mapeamento { get; }
        protected MapeamentoPadrao(BsonMapper mapper = null)
        {
            var mapa = mapper ?? LiteDB.BsonMapper.Global;
            Mapeamento = mapa.Entity<T>();
        }
    }`
    
    To use:
    `public class OrderMapper : MapeamentoPadrao<Order>
    {
        public OrderMapper() : base()
        {
            Mapeamento.Id(x => x.OrderNumber)
                      .Field(x => x.Customer, "cust")
                      .DbRef(x => x.Customer, "customers");
        }
    }`

So if you want to use a DI container to control the instance of BsonMapper, like Singleton or use BsonMapper.Global just use the constructor. I hope I can still help someone with doubts even though the post is old.
