### ISSUE TITLE
Beta 3 do not perform case insensitive search via link expression

### ISSUE THREAD

**Issue by danielcastilho** [mbdavid/LiteDB#424]
not perform case insensitive search via link expression in beta 3.0
Example of query:
Collection.Find(p => p.razaoSocialEmp.Contains(termo) || p.nomeEmp.Contains(termo))
Its work in older version (case insensitive search)

**Comment by xX-MLG-Xx** [comment]
hi there.

use linq and create a comparable lambda function and and convert both the
key name's value and your search term's value to lower or uppercase and
then do an equality check then return the result to the callee.

this is small solution implementation to aid in this problem

regards. Dean

**Comment by mbdavid** [comment]
@xX-MLG-Xx, sorry but I will anwser in portuguese :) (it's my first opportunity here)

E ae Daniel, como é bom poder explicar em português ao menos uma vez :)... tão mais facil... hehehe

Seguinte, a vesão 3 não oferece mais transformação nos indices. Ou seja, não faz trim, não faz lowercase nem nada. Até a versão 2 isso era possivel, mas resolvi descontinuar por problemas de compatibilidade e padrões.
Neste caso, tu precisa criar uma coluna nova com o dado transformado (como o Dean falou) ou criar um "Virtual Index", usando no mapeador `BsonMapper.Global.Entity<Cliente>().Index("razaoSocialIndex", x => x.razaoSocialEmp.ToLower())`. Neste caso, a query precisa rodar sem LINQ, usando `Query.Contains("razaoSocialIndex", termo)`.

**Comment by xX-MLG-Xx** [comment]
awesome David!. That is so cool. I've always wanted to learn Portuguese.
I know 21 programming languages and 3 human languages (English, Afrikaans
and Japanese)

**Comment by danielcastilho** [comment]
Muito obrigado! Tanks! Um pouco mais complicado creio.. mas é o que temos
para hoje.. Esta forma de pesquisar "insesitive" vai ser a definitiva?
Amanhã vou fazer meus testes da saua dica, Valeu Mauricio!

Em qua, 11 de jan de 2017 às 20:22, Dean Van Greunen <
notifications@github.com> escreveu:

**Comment by johnzens** [comment]
@danielcastilho @xX-MLG-Xx @mbdavid I faced the same issue recently,  i did solve it by using lower case conversion.

**Comment by mbdavid** [comment]
@danielcastilho, sim, será definitiva pois, por definição, indices não podem alterar o valor. Abraço

**Comment by danielcastilho** [comment]
Oi Mauricio, infelizmente tentei de todas as formas e não consegui
pesquisar de forma insensitive:
Ao usar:

BsonMapper.Global.Entity<Empresa>().Index<string>("razaoSocialIndex",
(x) => x.razaoSocialEmp.ToLower());

na Inicialização do código

e depois na pesquisa da seguinte forma

return Collection.Find(Query.Contains("razaoSocialIndex", termo.ToLower()))

Não retorna registros nem no case original nem na forma insensitive...

usando o código anterior:

return Collection.Find(p => p.razaoSocialEmp.Contains(termo))

carrega só que pesquisando usando o case "sensitive"

Tem algo errado Aqui?



Em qui, 12 de jan de 2017 às 08:49, Mauricio David <notifications@github.com>
escreveu:

**Comment by mbdavid** [comment]
Oi Daniel, a principio tá certo teu codigo. Vou montar um unit test para verificar o que pode estar ocorrendo.
