### ISSUE TITLE
Question - multi-thread performance

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#425]
Currently, my project is multi-process where each process is single threaded. On each collection, there is always one writer but there may be several reader processes. I create a separate LiteDatabase instance for each collection in each process, however, I know that LiteDatabase is designed to be shared amongst threads.

So my question is ...

If I were switch my project design so that readers were combined into one multi-threaded process (rather than separate processes) which shared a common LiteDatabase instance, would there be a signficant performance benefit?

(Note that the writer process would remain a separate process writing periodically to the collection, at the same time as the readers were acessing it.)

**Comment by mbdavid** [comment]
Hi @kuiperzone,

Shared some instance for all your readers are better solution. All threads using same instance will be consume same pages in cache, so will avoid all disk reading process for same page. To qualify how much better depends a lot of you use.

**Comment by kuiperzone** [comment]
Thanks that helps. Now I know it's probably worth doing. :)
