### ISSUE TITLE
NotImplementedException

### ISSUE THREAD

**Issue by honfus** [mbdavid/LiteDB#428]
Hello,
following code worked at beta2 but throws a "NotImplementedException" at the foreach-loop at beta3
` IEnumerable<DataSheet> results = dataSheetCollection.FindAll();
                foreach (DataSheet c in results) {
                    returnList.Add(c);
                }`
Detailed info:
>System.NotImplementedException wurde nicht von Benutzercode behandelt.
>HResult=-2147467263
>Message=Die Methode oder der Vorgang ist nicht implementiert.
>Source=LiteDB
>StackTrace:
>     bei LiteDB.ByteReader.ReadBsonValue(UInt16 length)
>     bei LiteDB.IndexPage.ReadContent(ByteReader reader)
>     bei LiteDB.BasePage.ReadPage(Byte[] buffer)
>     bei LiteDB.PageService.GetPage[T](UInt32 pageID)
>     bei LiteDB.IndexService.GetNode(PageAddress address)
>     bei LiteDB.IndexService.<FindAll>d__13.MoveNext()
>     bei LiteDB.LiteEngine.<Find>d__49.MoveNext()
>     bei LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
>     bei litedb_sdb.Database.LiteDBProvider.getDataSheetAll() in C:\XXX\gitMain\vad_sdb_db DB\litedb_lib\Database\litedbProvider.cs:Zeile 145.
>     ....

**Comment by mbdavid** [comment]
Hi @honfus, is your datafile came from beta2 or any other version?

**Comment by honfus** [comment]
the datafile comes from beta2.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
