### ISSUE TITLE
LiteDB.ObjectId cannot be cast to System.String

### ISSUE THREAD

**Issue by mschwehl** [mbdavid/LiteDB#43]
Hello everyone,

I have a one-to-many relationship and i want to model the relations independent so i use three collections. 

one: the one-object
second: the n-objects
third: a link-collection

furthermore i want to use Strings as primary-Key ( Guid )

Here my example, I have no idea to fix the classcast-Exception. Maybe one of you can help me ? I am out of ideas

Thank you much
Martin.

-------------------------------------------------------------------------------------------------------
<code>

using GraphDMS.Core.Model.Core;
using LiteDB;
using System;
using System.Collections.Generic;

namespace testcase
{

public class InfoElement
{
    public InfoElement() {}

        [BsonId]
        public string Id { get; set; }       // Guid.toString()
        public string Name { get; set; }

}

// many : colChildren

public class InfoElementItem
{
    public InfoElementItem() {}

        [BsonId]
        public string Id { get; set; }       // Guid.toString()
        public string Name { get; set; }

}

   public class LinkWrapper
    {
       public LinkWrapper() { }

        [BsonId]
        public string Id { get; set; }
        public string InfoElementId { get; set; }

        public List<String> FkListInfoElementItem { get; set; }
   

    }

    class Program
    {

        static void Main(string[] args)
        {

            
            // Open database (or create if not exits)
            using (var db = new LiteDatabase(@"C:\temp\test.db"))
            {

                InfoElement ie = new InfoElement();
                ie.Id = Guid.NewGuid().ToString();

                db.BeginTrans();

                var colInfoElementList = db.GetCollection<InfoElement>("InfoElementList");
                colInfoElementList.Insert(ie);

                var colInfoElementItemList = db.GetCollection<InfoElementItem>("InfoElementItemList");

                InfoElementItem uno = new InfoElementItem();
                uno.Id = Guid.NewGuid().ToString();
                colInfoElementItemList.Insert(uno);

                InfoElementItem dos = new InfoElementItem();
                dos.Id = Guid.NewGuid().ToString();
                colInfoElementItemList.Insert(dos);

                // link some kids

                var colLinkWrapper = db.GetCollection<LinkWrapper>("LinkWrapperList");

                LinkWrapper link = new LinkWrapper();
                link.InfoElementId = ie.Id;

                link.FkListInfoElementItem = new List<String>();
                link.FkListInfoElementItem.Add(uno.Id);
                link.FkListInfoElementItem.Add(dos.Id);

                colLinkWrapper.Insert(link);

                db.Commit();

  
            }

            // query 

            using (var db = new LiteDatabase(@"C:\temp\test.db"))
            {

                var colInfoElementList = db.GetCollection<InfoElement>("InfoElementList");
                var colLinkWrapper = db.GetCollection<LinkWrapper>("LinkWrapperList");

                colLinkWrapper.EnsureIndex(x => x.InfoElementId);

                foreach (InfoElement element in colInfoElementList.FindAll())
                {
                    // {"Das Objekt des Typs \"LiteDB.ObjectId\" kann nicht in Typ \"System.String\" umgewandelt werden."}
                    // LiteDB.ObjectId cannot be cast to System.String

                    foreach (var tagElement in colLinkWrapper.Find(Query.EQ("InfoElementId", element.Id)))
                    {
                        // here i want todo some stuff 
                        Console.WriteLine("I want to come here!");
                    }
                }
            }

        }

    }

}

</code>

**Comment by mbdavid** [comment]
Hi @mschwehl, I found the problem:

When you insert `LinkWrapper` you do not set `Id` value, so LiteDB creates a new `Id` using `ObjectId`.

```
LinkWrapper link = new LinkWrapper();
link.Id = Guid.NewGuid().ToString(); // Missing here!
link.InfoElementId = ie.Id;
```

I will keep this issue open to fix this. The LiteDB must throw an error when you have an entity with `Id` but you don´t initialize.

**Comment by engineering87** [comment]
Hi everyone,
got similar exception:

`Unable to cast object of type 'LiteDB.ObjectId' to type 'System.Boolean'`

I'm trying to insert this custom abstract class that adds simple the property Id:

`[BsonId]
public ObjectId Id { get; } = ObjectId.NewObjectId();`

Any ideas?

Thanks
