### ISSUE TITLE
Unable to cast object when calling function FileStorage.OpenRead

### ISSUE THREAD

**Issue by piyush-v** [mbdavid/LiteDB#430]
Hi,

There is an image which I am trying to access using FileStorage.OpenRead, I am getting unable to cast exception. the same image I am able to access through FileStorage.FindById. Screenshot attached

Message - Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,LiteDB.BsonValue]' to type 'System.String'.

![issue](https://cloud.githubusercontent.com/assets/25184773/22038504/6f99ceb2-dcc9-11e6-84b2-32a5f4e87e59.png)

**Comment by mbdavid** [comment]
Hi @piyush-v, I just released v3 version. Can you test your code on this version?
