### ISSUE TITLE
Question about primary _id - doesn't work :(

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#432]
I asked before about a struct containing a single long which could be converted implicitly to and from a long being used as the primary "_id" in a document, like so:

```
public struct Timestamp
{
...
        public static implicit operator Timestamp(long val)
        {
            return new Timestamp(val);
        }
        public static implicit operator long(Timestamp ts)
        {
            return ts._ticks;
        }
```

You said it would be OK and it would be no problem, and I updated all my code and now none of it works anymore and it's a complete mess and it's all your fault!!! :) :)

More seriously now, Bson doesn't seem to know what to do with my struct type and I appear to have no idea on how to force some kind of cast to long in Linq for "_id".

Any ideas?

**Comment by mbdavid** [comment]
Hi @kuiperzone, I still saying that possible to create. And if not, It's just change code :)

BsonSerialization just convert BsonDocument to binary. We could track this in BsonMapper class, when a POCO class are converted to BsonDocument. Did you try to use `RegisterType` in BsonMapper? In this case, you can create a custom converter to any supported bson data type. In this case, you can use long (long is a valid bson data type).
Try some like this:
```
BsonMapper.Global.RegisterType<Timestamp>
(
    serialize: (ts) => ts.Value,
    deserialize: (bson) => new Timesamp(bson.AsLong)
);
```

**Comment by kuiperzone** [comment]
Thanks for getting back to me on this on. No I didn't try RegisterType. I'm going to look into it now. Coming from a C++ background, I find Chinese calculus more amenable tha this all this Linqery stuff at the moment, but will grasp it.

Question - could I use RegisterType to force LiteDB to ignore properties with given types, like so...
```

BsonMapper.Global.RegisterType<Timestamp>
(
    serialize: (ts) => null,
    deserialize: (bson) => null
);
```

??

**Comment by henon** [comment]
On Mon, Jan 23, 2017 at 2:55 PM, Kuiper <notifications@github.com> wrote:

> Coming from a C++ background, I find Chinese calculus more amenable tha
> this all this Linqery stuff at the moment, but will grasp it.
>
I don't know about Chinese calculus but once you grasp the full might and
elegance of C#, you'll pull out your hair every time you have to go back to
C++.

**Comment by kuiperzone** [comment]
@henon I'm already having that experience with C# as it is and my hair is all gone! LMAO

**Comment by henon** [comment]
@kuiperzone LOL, think on the bright side. You don't have any hair to pull out when you finally have to go back to C++ ;)
