### ISSUE TITLE
Question - Is possible to supply a string array of properties to ignore (not serialize) to Collection?

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#433]
What I'd really like to do is supply a list of property names to a collection to ignore somehow, but keep the specification outside the database implementation and document properties code. A bit like this:

string[] ignoreProperties = {"Timestamp", "Product"};

And have these NOT serialized to the collection.

I know I can do it using:

`.Ignore(x => x.DoNotSerializeThis) `

Is there any way I can convert a string value into "x.DoNotSerializeThis"?

**Comment by mbdavid** [comment]
No, now is not possible. But I was looking in source, here: https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/EntityBuilder.cs#L15

If I expose this `_entity` as public you can easy implement a custom extention method to `EntityBuilder` using some like `.Ignore(string[] fields)`

**Comment by kuiperzone** [comment]
Thanks for getting back to me David.

Yes, Ignore(string[] fields) would be perfect. I'll explain my problem.

I'm facing a design issue. I have a set of classes which essentially form an API and have no intrinsic connection to LiteDB. However, as part of my own implementation and use of my API I expect to store them in a LiteDB database (or some other database implementation).

The normal simple solution would be to tag the class properties with BSON ignore**, howevever, I don't want to do this because it would mean putting BSON attributes in my interface and making a user link their code to LiteDB.

So I would really want a nice clean and portable way of stating which fields should not be serialized. A string list, perhaps, would do this.

** Just had an idea of how I can solve my problem by explaining it. So thanks again! :)
