### ISSUE TITLE
File concurrency.

### ISSUE THREAD

**Issue by sBoff** [mbdavid/LiteDB#435]
Hi there,

I am new to LiteDB and I would like the clarify what you mean by "file concurrency"?

I understand it is thread safe, i.e. multiple threads from the same application can use the same instance of the database safely. I am in a situation however where I need two independent processes to work on the same database file at the same time - is this long longer possible?

Regards.

**Comment by mbdavid** [comment]
Hi @sBoff, current v3 support both thread concurrency and file concurrency (multiple instances/process using same datafile) in net35 version. In my first v3 beta version I removed multiprocess access but add back in v3 release after this issue #332. Wiki are not updated yet.

If you are running in netstandard, only LiteDB must open file as exclusive access (netstandard doesn't support lock file).

**Comment by sBoff** [comment]
Fantastic, thank you very much!
