### ISSUE TITLE
Question to BsonMapper.Global.ResolvePropertyName

### ISSUE THREAD

**Issue by chris-ga** [mbdavid/LiteDB#439]
Hi,

I want to use ResolvePropertyName-Function to trim longer property-names for less storage-usage in the db-file.

Because of inheritance of a common base-class there are many (sub-)classes, that uses the same common set of property-names.

My problem is, that trimming of those property-names only works for objects of the first sub-type that is being stored.
Objects of other sub-types keep their original property-names.

Eg.:
BaseClass with a "LongNamedProperty", that shall be trimmed to "LNP"
Storage of classes of "ClassA : BaseClass" and "ClassB : BaseClass" in different LiteDB-collections leads to:
ClassA.LNP...
ClassB.LongNamedProperty...

Are property-names from the ResolvePropertyName-Function mapped to classes where they are found first and are no longer available for being used in other classes?

I'm currently using LiteDB in version 2.0.4.
Are their any changes in LiteDB v3?

Thx
Christian

**Comment by mbdavid** [comment]
Hi Cristian, I'm checking here in v3 and ResolvePropertyName will be applyed in any class that needs be serialized. Any type that needs be serialized pass here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.cs#L311
