### ISSUE TITLE
Question - Connection String v3?

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#440]
Hi there,

It would be really helpful to have an example of a connection string in the wiki, which shows the filename and some options. I know that it caused me some initial confusion and I think this is important because, if I remember correctly, LiteDB just ignores what it doesn't understand provided it gets the filename (or it least it seemed to in the past when I was trying it).

**Could you give us an example including Timeout and Mode?**

Timeout (TimeSpan): Timeout for waiting unlock operations (thread lock and locked file)
Mode (Exclusive|ReadOnly|Shared): How datafile will be open (defult: Shared in NET35 and Exclusive in NetStandard)

**What is the default for Timeout?**

How do we express, say 5 seconds or 100 milliseconds?

Cheers

**Comment by mbdavid** [comment]
Yes, its on my plans update all wiki docs to v3. But, as a good developer, i have write documentarion :)

Timeout default is 1 minute. You needs write, in query string, as Timespan.Parse, like: 00:05:00

In Mode its an string (will parse to an enum). Bit this explain will ne better in concurrency section
