### ISSUE TITLE
Question - How to change password in connection string v3?

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#441]
For the connection string, wiki says:

Password (string): Encrypt (using AES) your datafile with a password (default: null - no encryption)

If I password protected a database, put a 1 TB of data in it for good measure, how do I then change the password (or remove it)?

**Is this possible?**

If this is not possible, as way of password change, is there a straight forward to read a password protected LiteDB (given that you know that password but don't know anything about the Collections or their data), and dump the data into a new LiteDB file with a new or no password?

**Comment by mbdavid** [comment]
Yes, in v3 its possible change password in Shrink command. This operation will re-write all you data to a new datafile with a new (or no) password.

1TB datafile? Oh my... :)

**Comment by kuiperzone** [comment]
@mbdavid >1TB datafile? Oh my... :)

I like to know things scale. :)
