### ISSUE TITLE
Question - How to query array of strings

### ISSUE THREAD

**Issue by vkocjancic** [mbdavid/LiteDB#442]
Hi.

I am using LiteDB 2.0.4.
In one collection, I have array of strings. How do I query that array for one value or part of it?

I have tried Query.In, but that doesn't work. Neither does Query.Contains.

**Comment by mbdavid** [comment]
Hi, only v3 support array multikey index. Use:

Query.EQ("array", value)
Quyer.StartsWith("array", value)

**Comment by vkocjancic** [comment]
Yes, but v3 is in beta.

Query.EQ and Query.StartsWith does not seem to work on array fields in v2.

**Comment by mbdavid** [comment]
No, v3 was released last week.

In v2/1, arrays are indexed are single object, so you need search all object (all items in array). In v3, arrays are splited values and each value are an index key, so it's possible search for a individual value.

**Comment by vkocjancic** [comment]
Excellent. Will update then. Is DB file compatible?

OK, but in case of v2, Query.Contains should then find a value in array of string. It does not.

**Comment by mbdavid** [comment]
Is not how v2 works. When you are index an array, all items inside this array are indexed as a single "value" (array type). So, even Contains will not find single result inside an array.

That was I changed in v3, to index all itens inside and array. So each value can be searched.
