### ISSUE TITLE
Cast exception on EnsureIndex

### ISSUE THREAD

**Issue by tomazk8** [mbdavid/LiteDB#449]
Hi David

I too encountered casting exceptions lately. I use the version 3.0.0 from in the same application running on two platforms, .NET 4.6 and UWP. On .NET 4.6 it works without problems, but on UWP I always get the exception when opening the existing database on EnsureIndex. Existing DB doesn't need to have any data, just some collections. After it fails on EnsureIndex I then get also an error on the first query for all items, i.e. collection.FindAll().ToList(); So I guess something get screwed up after index exception. I made one UWP app (attached) that reproduces this problem.

In the main page I am creating or opening the DB and adding many collections with index on one field. The first time it works because db is being created. But the next time app is ran, I get this exception:

System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.CollectionPage'.

The most interesting thing I observed is that it always fails to ensure index at the last value of i. Not it fails at index 9, but if you delete the DB and i.e. increase the loop to 50, it will fail at 49. Maybe this is a clue where to search for the problem.

[LiteDBTest.zip](https://github.com/mbdavid/LiteDB/files/746045/LiteDBTest.zip)

Best regards
Tomaz

**Comment by mbdavid** [comment]
Hi @tomazk8, why are you using `Stream` ctor in LiteDB? If you are using an file is much better you use direct filename (are complete different implementation from generic Stream to FileStream). Dont forget to use you valid path from `ApplicationData.Current.LocalFolder`. UWP `StorageFile` uses async read/write that are not supported in LiteDB.

**Comment by tomazk8** [comment]
Hi David

I am using it because I can't use File class in UWP. If I specify a path I get an exceptiom from LiteDB:
System.IO.FileLoadException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Stack trace:
   at LiteDB.FileHelper.GetTempFile(String filename, String suffix, Boolean checkIfExists)
   at LiteDB.FileDiskService..ctor(String filename, FileOptions options)
   at LiteDB.LiteDatabase.<>c__DisplayClass10_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteDatabase.GetCollectionNames()
   at LiteDBTest.MainPage..ctor()
   at LiteDBTest.LiteDBTest_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_MainPage()
   at LiteDBTest.LiteDBTest_XamlTypeInfo.XamlUserType.ActivateInstance()

This probably means that under UWP, LiteDB can't use temporary files. Is this maybe for a journal?

And I see now that I could supply my own IDiskService. I just need to implement and I could take parts from LiteDB source and just simple use streams instead of files. Would this work or is it not that easy to implement it?

Regards

**Comment by tomazk8** [comment]
Oh, and yes, I took the path from ApplicationData.Current.LocalFolder.

**Comment by mbdavid** [comment]
Try disable journal, but I made some test before and works fine. When you pass base `Stream` class there is a very simple implementation of data persist layout - most of time used for MemoryStream tests.

I will try run your example in at home.

**Comment by tomazk8** [comment]
Ok, thanks, I will try it. How do I disable the journal?

**Comment by mbdavid** [comment]
use in connection string "filename=....;journal=false"

**Comment by tomazk8** [comment]
I just tried it now and so far it looks it works with journal disabled. Great thanks :). I cannot test much though because I have some problems transferring data with HTTP and rest protocol to server site. I am running server on Raspberry Pi.

**Comment by tomazk8** [comment]
I tested it now quite heavily and it works perfectly. I do have a question about the journal though. Now that it's disabled, will transactions work safely? because during mass data inserts I killed the application and on the next run I got an DB error. I will try to reproduce the problem.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
