### ISSUE TITLE
Issue with Collection Insert()

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#450]
First of all, let me say well done on releasing v3.0.0. And here is me saying it: Well Done! :)

Think I may have raised this before, but I have an interface issue with Insert().

Basically, both the Upsert() and Update() variants returns true on success. While Insert() has no return type and throws instead.

This is means that, if I want to have appropriate behaviour in my app (without it throwing out) I either have to wrap the Insert() call in a try catch block, or query whether the document exists before hand.

**Comment by kuiperzone** [comment]
Thinking about this, I could understand why you might not be keen to change it. It might cause an issue for apps using try-catch to detect failure.

**Comment by mbdavid** [comment]
But Upsert returns true if insert and false if update (when using single document). And Update returns true when found and update document and false if not found document.

In both cases there is no exceptions. If you compare with relation database is the same: INSERT can throw duplicate key exception but UPDATE only update founded rows, so there is no exception on this.

**Comment by mbdavid** [comment]
It's better call Insert and test duplicate exception an than Update.

or

Update first, if returns false, than Insert.

In both cases it's better inside an transaction. You can choose what you beleave that you will have most: Inserts or Updates?
