### ISSUE TITLE
Ambiguous user defined conversions 'BsonValue.implicit operator BsonValue(double)' and 'BsonValue.implicit operator BsonValue(decimal)' when converting from 'ulong' to 'BsonValue'

### ISSUE THREAD

**Issue by romanov** [mbdavid/LiteDB#453]
My project is not working after the LiteDB update.

        [BsonIndex]
        public ulong Id { get; set; }
 
var entry = users.FindById(id);

gives:

`Error	CS0457	Ambiguous user defined conversions 'BsonValue.implicit operator BsonValue(double)' and 'BsonValue.implicit operator BsonValue(decimal)' when converting from 'ulong' to 'BsonValue'`

Thanks

**Comment by mbdavid** [comment]
Hi @romanov, I create new implicit convert exclusive for ulong now. Please, test current master branch version and give me a feedback

**Comment by romanov** [comment]
Yeah, i've tested just with users.FindById((decimal)id); 
working for now)
