### ISSUE TITLE
non threadsafe code in LiteDB/LiteDB/Mapper/Reflection/Reflection.cs

### ISSUE THREAD

**Issue by alexsuh7** [mbdavid/LiteDB#455]
hi , 
In Reflection.cs , you are using Dictionary to store cached reflection results. 
We are getting An item with the same key has already been added , when attempting to read from db in several threads.
I suppose that a quick fix would be to switch to ConcurrentDictionary 
here 
https://github.com/mbdavid/LiteDB/blob/bf5dd3de8e589ca0acfb5ce64cd8eee03ad9f73e/LiteDB/Mapper/Reflection/Reflection.cs#L25

Noticed project is using .NET 3.5
Perhaps this will help
http://www.nuget.org/packages/TaskParallelLibrary

Stack trace:
: Failed to create instance for type 'XXXYYY' from assembly 'XXXYYY, ZZZ, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Checks if the class has a public constructor with no parameters. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at LiteDB.Reflection.CreateInstance(Type type)

**Comment by s-ve** [comment]
+1. I'm having the same bug when two threads are reading from the same collection at the same time.

**Comment by s-ve** [comment]
Another quickfix would be to use a [ReaderWriterLockSlim](https://msdn.microsoft.com/en-us/library/system.threading.readerwriterlockslim(v=vs.110).aspx).

see my commit here : 

[https://github.com/s-ve/LiteDB/commit/339593919f52e2dd2582c38f9c852eb87f91585c](https://github.com/s-ve/LiteDB/commit/339593919f52e2dd2582c38f9c852eb87f91585c)

**Comment by masterdidoo** [comment]
Fix #455

**Comment by masterdidoo** [comment]
Fix #488
