### ISSUE TITLE
Limitation of FileStorage ids

### ISSUE THREAD

**Issue by nmaier** [mbdavid/LiteDB#456]
`FileStorage` limits what ids you can use by running a regex against the keys. Regular `ILiteDbCollection`s do not seem to have the same restriction.

So it is not possible right now to insert data for arbitrary files based on their actual paths right now, as OS level paths are less restricted that `FileStorage` ids . My use case is to store generated cover images for media files in `FileStorage`.
This effectively requires me either encode/escape the file name somehow (e.g. uri-style escaping), or to generate some kind of id based on the file path, store that somewhere else and later do a two stage lookup (lookup the `FileStorage` id then lookup within `FileStorage`) instead of just doing a single lookup in `FileStorage`.

Since there are viable, easy enough workarounds, this isn't really a grave issue, but still in my opinion a "nice to have".

I'm now wondering why the ids are restricted that way, and if `LiteDb` can be changed so this restriction is not necessary anymore?

## STR ##
Run
```c#
static void Main(string[] args) {
  using (var db = new LiteDatabase("test.ldb")) {
    var finfo = new FileInfo("IMG_1027 (1).mp4");
    using (var ms = new MemoryStream(Encoding.UTF8.GetBytes("test"))) {
      db.FileStorage.Upload(finfo.FullName, finfo.Name, ms);
    }
  }
}
```

## Expected result ##
The data should be inserted (and subsequently retrievable)

## Actual result ##
An exception is throw: `LiteDB.LiteException: Invalid format: FileId`.

**Comment by mbdavid** [comment]
Hi @nmaier, FileStorage uses an _id string because needs 2 collections a file: 1 collection stores file description and 1 collection stores N documents with data chuncks. And this chunks are string based using `\` in _id value. Each chunk has unique _id like `string.Format("{0}\\{1:00000}", id, index)`. 

But I beleave that could be added more chars, excluding only `\`
