### ISSUE TITLE
When trying to insert a corrupt DB, only a rather non-descript exception is thrown

### ISSUE THREAD

**Issue by nmaier** [mbdavid/LiteDB#458]
Trying to e.g. insert data into a corrupt DB will throw a `System.Exception` rather than something more fine-grained, making it hard an error-prone to handle corrupt DBs in code (like informing the user properly, or just wiping out the corrupt DB and recreating it) as the exception cannot be filtered properly.

## Currently ##
E.g. `.Insert` into a corrupt DB currently throws `System.Exception: Invalid pageType`

## Suggestion ##

An exception type like this would help
- `System.Exception`
  - `LiteDB.LiteException`
     - `LiteDB.LiteCorruptDatabaseException`

So it would enable code like this
```c#
try {
  collection.Insert(someDocument);
}
catch (LiteCorruptDatabaseException ex) {
  Console.Error.WriteLine("Sorry, your database file is corrupt and cannot be recovered. Please remove the file and start anew");
}
catch (LiteException ex) |
  Console.Error.WriteLine($"Uh oh, Cannot insert into the database: {ex.Message}");
}
catch (LiteException ex) |
  Console.Error.WriteLine($"Seems I messed up this program real bad: {ex}");
}

**Comment by mbdavid** [comment]
Yes, I will review this. I made this pageType test before test header `"** This is a LiteDB file **"` string.
