### ISSUE TITLE
LiteDB 3.0 Version issue between netstandard library and .net 4.6.1 library

### ISSUE THREAD

**Issue by demeyera** [mbdavid/LiteDB#459]
I have a netstandard targeting library and a .net4.6.1 unit test library, both referencing the LiteDB 3.0 NuGet package. When I run a unit test,I get following exception:

System.IO.FileLoadException: Could not load file or assembly 'LiteDB, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by demeyera** [comment]
I have found the issue, reason is because you have signed the .net35 version with a key, but the .netstandard version not. Because of this, the publickeytoken for the netstandard version is null, but for the .net35 version is not and the assembly definitions don't match. Can you either sign them both or none so it's actually possible to reference a netstandard assembly using LiteDB in a .net35 or higher project?

**Comment by mbdavid** [comment]
Hi @demeyera, thanks! I will fix this in next release

**Comment by demeyera** [comment]
OK thanks :)

**Comment by madmaec** [comment]
Hi @mbdavid,

this problem occurs again with LiteDB 3.1.1.  I have class libraries (.NET Standard 1.4) and unit tests (.NET Framework 4.6.1). If I switch back to LiteDB 3.1.0 everything works fine.
