### ISSUE TITLE
Missing dump functionality in v3

### ISSUE THREAD

**Issue by sitofabi** [mbdavid/LiteDB#461]
Hi,

we are using the v2 of LiteDB and created some dumps of the database to have a predefined input for some unit-/component testing. During the setup of the unit test we load a `dump` file manually and call 
`liteDatabase.Run(textLine)` for all lines in the file.

Now with version 3 it seems that the dump command is no longer existing and that the Run method was removed from the LiteDatabase. Is there any other way how we can "manually" fill the database from a text
file?

Regards 
   sitofabi

**Comment by mbdavid** [comment]
Hi @sitofabi, in v3 all shell commands are removed and now are only in shell too. Now If you want fill your datafile, you can just read json file as BsonArray and insert all data collection, like this:

```
var docs = JsonSerializer.DeserializeArray(File.ReadAllText("your-file.json"));

using(var db = new LiteEngine("your-datafile.db"))
{
    db.Insert("your-collection", docs);
}
```

**Comment by mahdi-ninja** [comment]
Hey @mbdavid,

May I ask why? These shell commands are really useful in automation. Can you please bring them back?

Also if they are not going to come back, at least remove them from the "help full" in LiteDB.Shell.exe. I wasted a couple of hours trying to understand why these commands don't work then I saw this message.

**Comment by mbdavid** [comment]
Hi @mahdi-ninja, added in my backlog to evaluate. I remove just to be clear/easy to mantain core lib. Let me ask if your automation are basicly "import/export" data? Because its much easy to create command to dump/import from core lib than all shell parser/commands.

**Comment by mahdi-ninja** [comment]
@mbdavid Yes, I used it mostly for import/export, upgrading databases and changing their passwords (to use different passwords for different environments).

**Comment by jkmuka** [comment]
I also used the dump command to easily view everything in the DB, would like to see it added back.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
