### ISSUE TITLE
Removed API LiteDatabase.Run breaked LiteDBViewer

### ISSUE THREAD

**Issue by RytisLT** [mbdavid/LiteDB#462]
Since LiteDatabase.Run was removed from V3 there's no way for LiteDBViewer to easily execute a string query on a database. Would it be possible to restore this functionality in v3?

**Comment by mbdavid** [comment]
Hi @CaptBrick, now all shell commands are inside shell tool. It was better to remove from there to litedb keep simple. If you need this commands, please get from shell project.
