### ISSUE TITLE
Shrink to possible minimum size

### ISSUE THREAD

**Issue by Jack85** [mbdavid/LiteDB#463]
If you upload a file (lets say 66mb), delete file and shrink, you dont get to original size of the database without that file.  In my case from 26kb to 66mb back to 40kb.
If I open it I see still lots of null entries that could be deleted. correct?

**Comment by mbdavid** [comment]
Did you drop collection or delete all documents? Because if you only delete only you still storing collection infor (like name and indexes definitios). If you drop collection you will get minimal file size: 8k

**Comment by Jack85** [comment]
I did insert , delete file and shrink db. Drop collection on all files doesnt make sense,  you can have ot her files in db you dont want to delete. But generaly i dont know if i need any metadata of deleted records.

**Comment by mbdavid** [comment]
try drop collection to check if datafile backs to original size. Collection metadata is not too relevant because it's auto-created when you do your first insert

**Comment by Jack85** [comment]
Ok.
My point here was that it should be possible - same as when you delete files on your disk it removes exactly so many bites you added, shrink after delete  that you get to original size without dropping collections.
