### ISSUE TITLE
when insert data that contain null value, the null value will missing 

### ISSUE THREAD

**Issue by flyaim** [mbdavid/LiteDB#465]
In LiteDB 3.0
I have a class like this:
public class MyData
{
    public int Id { get; set; }
    [LiteDB.BsonIndex]
    public string MyName { get; set; }
    public Dictionary<string, List<int?>> MyDict { get; set; }
}

And I have data like this:
var data = new MyData
{
    MyName = "name"
    MyDict = new Dictionary<string, List<int?>>(){
        {"one", new List<int?>() { 1, null, 3, null, 5 } }
    }
}

When I use col.Insert(data), the null value in the List<int?> will missing.
Then I use Find method get the List<int?> value only have 1, 3, 5.

But, it didn't have this problem in LiteDB 2.0.4.

Is this a bug? What can I do to solve it?

**Comment by mbdavid** [comment]
oh yes, I found here:

https://github.com/mbdavid/LiteDB/commit/d0d55ebc37a00d4b8a737016c7cc1d249cb7f9d7

I'm fixing this
