### ISSUE TITLE
Using Lucene in LiteDB - LiteDBDirectory

### ISSUE THREAD

**Issue by mbdavid** [mbdavid/LiteDB#466]
Context about this here: https://github.com/mbdavid/LiteDB/issues/20#issuecomment-277425579

Using lucene in LiteDB:

https://github.com/sheryever/LiteDBDirectory

Hi @sheryever, that awesome. 101.000 it's a lot of documents :) We can do some improvements removing Mapper and working direct with LiteEngine and BsonDocuments too. I'm forking you code...

If you could discover how Lucene save single document will be much an much faster. Works if files are not the best solution becase all file must be write when was changed (there is no support for Seek operation).

**Comment by sheryever** [comment]
I am also working with @MahyTim and he is improving SqlServerDirectory with buffering, and has achieved 250% fast performance with that while indexing.

SimpleFSDirectory uses bufferedIndexInput to increase the performance.

I was also thinking to hold the files in array until Flush function is called and then save/update the files in the LiteDB while indexing.

I will update the code repo after the buffering. github code is old.

**Comment by sheryever** [comment]
Ok,

I have sync the github code without buffering. This code will index 101,000 documents.
