### ISSUE TITLE
Null reference on Update

### ISSUE THREAD

**Issue by rudolf-kajan** [mbdavid/LiteDB#467]
Hello, 

I have a simple class 

   [Serializable]
    public class UserProfile
    {
        [BsonIndex]
        public Guid UserId { get; set; }

        [BsonRef("devices")]
        public List<string> Devices { get; set; }
    }

which I would like to retrieve, change and save. Retrieving is OK:

`string deviceid = "123456";`
`var profiles = database.GetCollection<UserProfile>("profiles").Include(p => p.Devices);`
`var profile = profiles.Find(p => p.UserId.Equals(profileId)).FirstOrDefault();`

`if (!profile.Devices.Contains(deviceId))
   profile.Devices.Add(deviceId); `

//-- up to here everything is OK, object has a GUID and one string

`profiles.Update(profile);` // <----- this fails with a null ref exception

Why does the update fail? Thank you

**Comment by mbdavid** [comment]
You cannot use DbRef in List<string>. DbRef must be used in external collection references (complex datatyles with id).

In this example, i beleave you must use embedded document: just remove [BsonRef] attribute

**Comment by rudolf-kajan** [comment]
Thank you for the suggestion, but if I remove the [BsonRef("devices")] attribute from Lis<string> Devices I get the error: "Invalid BSON data type 'Null' on field '_id'."

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
