### ISSUE TITLE
Upgrade from V2 to V3 - 

### ISSUE THREAD

**Issue by bobmcallan** [mbdavid/LiteDB#468]
Hello, I have a simple LiteDB. The Upgrade function is throwing an error.

"The method or operation is not implemented"

[System.NotImplementedException]	{System.NotImplementedException: The method or operation is not implemented.
   at LiteDB.ByteReader.ReadBsonValue(UInt16 length)
   at LiteDB_V6.IndexPage.ReadContent(ByteReader reader)
   at LiteDB_V6.BasePage.ReadPage(Byte[] buffer)
   at LiteDB_V6.PageService.GetPage[T](UInt32 pageID)
   at LiteDB_V6.IndexService.GetNode(PageAddress address)
   at LiteDB_V6.IndexService.<FindAll>d__5.MoveNext()
   at LiteDB_V6.DbReader.<GetDocuments>d__8.MoveNext()
   at LiteDB.LinqExtensions.<Batch>d__0`1.MoveNext()
   at LiteDB.LiteEngine.Upgrade(String filename, String password, Boolean backup, Int32 batchSize)
   at Subsidium.Node.Data.LiteDb.UpgradeDatabase() in 

I have another method to update for dev, however remote clients are not possible. 

I can provide the database file if required.

Bob

**Comment by qart2003** [comment]
Hi, @mbdavid I have write small like test
  public string CheckOne<T>(List<T> items, string name) where T : BaseIdObj
  {
    foreach (var item in items)
    {
      if (items.FindAll(v => v.Id == item.Id).ToList().Count > 1)
        return name;
      if (items.FindAll(v => v.IID == item.IID).ToList().Count > 1)
        return name;
    }
    return null;
  }
  public bool Check (string fn) 
  {
    using (var db = new LiteDatabase(fn))
    {
      var users = db.GetCollection<User>(DALNames.users).FindAll().ToList();
      var firms = db.GetCollection<Company>(DALNames.firms).FindAll().ToList();
      var posts = db.GetCollection<Post>(DALNames.posts).FindAll().ToList();
      var towns = db.GetCollection<Town>(DALNames.towns).FindAll().ToList();
      var devisions = db.GetCollection<Devision>(DALNames.devisions).FindAll().ToList();
      List<string> errors = new List<string>();
      errors.Add(CheckOne(users, "users"));
      errors.Add(CheckOne(firms, "firms"));
      errors.Add(CheckOne(posts, "posts"));
      errors.Add(CheckOne(towns, "towns"));
      errors.Add(CheckOne(devisions, "divs"));
      return true;
    }
  }

Result is in errors and in debug I saw only nulls it means no items with equal Id but Upgrade doesnot work

**Comment by vlad-k4k** [comment]
Upgrade from v2 is broken as far as I can see. Attached is simple v2 DB created from sample. v3 fails to upgrade.
[test.zip](https://github.com/mbdavid/LiteDB/files/768338/test.zip)

I've debug a bit and it looks like Upgrade\v6 doesn't read data properly.
