### ISSUE TITLE
LiteDB.Shell Invalid database version: 6

### ISSUE THREAD

**Issue by RvdoAstaroth** [mbdavid/LiteDB#469]
Hello everyone!

I just downloaded LiteDB.Shell v3.0.0 for windows and I'm trying to open a LiteDB document with Open command. But I just recieve a "Invalid database version: 6" message.

What can I do to fix this? I tried to use dump < and dump > solution but I cannot perform it 'cuz I cannot  be able to open LiteDB document.

Thanks a lot for your help.

![image](https://cloud.githubusercontent.com/assets/25462062/22752047/a69f997a-edfc-11e6-9ffa-8ecb3ff73844.png)

**Comment by mbdavid** [comment]
Hi @RvdoAstaroth, try open using upgrade command: "open filename=spaces.db;upgrade=true"

**Comment by vlad-k4k** [comment]
I have the same issue when using upgrade command: "open filename=spaces.db;upgrade=true"

> "Invalid database version: 6"

**Comment by mbdavid** [comment]
Ok, I'm looking your example now.

**Comment by mbdavid** [comment]
Hi @vlad-k4k, before release final v3 I update BsonType enum and it's broke my "upgrade" command. I fix now in master branch. O will update nuget this weekend

Than, I fix some shell commands too. Now shell works as "always disconected". To upgrade your datafile using shell use:

> upgrade oldfile.db
or
> upgrade filename=oldfile.db;password=newpass
or
> open filename=oldfile.db;upgrade=true:

**Comment by vlad-k4k** [comment]
Tested the fix and upgrade worked as expected. Thanks.

**Comment by Youwannadie** [comment]
Hi, I have similar issue. I am trying upgrade data file from v2 to v3 like:
`new LiteDatabase("filename=db.db;upgrade=true");`
and exceptions occurs at line 44 in IndexPage.cs:
![litedbexception](https://cloud.githubusercontent.com/assets/25739500/22878066/836953b2-f1d8-11e6-9f7e-97de85c65093.PNG)
You can reproduce it simply. Just make database in LiteDb v 2.0.4. Store some object, then upgrade LiteDb to v 3.0.0 and try upgrade like above.

**Comment by vlad-k4k** [comment]
Just uninstall the package and install again - should get the new code with the fix.

**Comment by Youwannadie** [comment]
I tried it few minutes ago in console application, still same issue.
```
    class Program
    {
        static void Main(string[] args)
        {
            //var db = new LiteDatabase("db.db"); //for v2.0.4
            var db = new LiteDatabase("filename=db.db;upgrade=true"); //for v3.0.0
            db.GetCollection<Log>("logs").Insert(new Log { DateTime = DateTime.Now, Text = "text message" });

            Console.ReadLine();
        }
    }

    public class Log
    {
        public int Id { get; set; }
        public DateTime DateTime { get; set; }
        public string Text { get; set; }
    }
```

**Comment by vlad-k4k** [comment]
I did not the 'auto upgrade' to be honest. But LiteDB.Shell.exe -> 'upgrade oldfile.db' did the job for me.

**Comment by Youwannadie** [comment]
I downloaded master branch and it is wokring. So seems nuget package is not updated yet.

**Comment by RvdoAstaroth** [comment]
Thanks a lot @mbdavid but I still having problems with the same issue. 

I already uninstalled and installed again but I get the same results.

Thanks in advance for your help.

![image](https://cloud.githubusercontent.com/assets/25462062/22893510/7e26d994-f1db-11e6-869d-b4970b7759db.png)

**Comment by mbdavid** [comment]
Hi @RvdoAstaroth, it´s not available in nuget. For now, you need compile from Master branch. I will submit new version tonight

**Comment by juntor** [comment]
Hi @mbdavid, my db file version is v1.0.4.  how can i update to latest version in a simple way.
Thanks.

**Comment by mbdavid** [comment]
Hi @juntor, unfortunately there is not "upgrade=true" option for v1.x version. But you can write this to export/import your data:

https://github.com/mbdavid/LiteDB/issues/512#issuecomment-282732141

**Comment by juntor** [comment]
Thanks
