### ISSUE TITLE
Invalid cast from 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'

### ISSUE THREAD

**Issue by wjablonski1** [mbdavid/LiteDB#470]
Hello

I'm using the latest version of LiteDb. When I'm trying to move some data from FileStorage from one database to another one, randomly I receive the error: 
   w LiteDB.PageService.GetPage[T](UInt32 pageID)
   w LiteDB.PageService.GetFreePage[T](UInt32 startPageID, Int32 size)
   w LiteDB.DataService.Insert(CollectionPage col, Byte[] data)
   w LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc)
   w LiteDB.LiteEngine.<>c__DisplayClass58_0.<Insert>b__0(CollectionPage col)
   w LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   w LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs)
   w LiteDB.LiteEngine.Insert(String collection, BsonDocument doc)
   w LiteDB.LiteStorage.Upload(String id, String filename, Stream stream)
  
Sample code:
var fileStream = otherDb.GetFileStorage().OpenRead(fileEntry.FileId);
MemoryStream ms = new MemoryStream();
fileStream.CopyTo(ms);
var liteFileInfo = actualDb.GetFileStorage().Upload(fileNameWithoutExtension, fileEntry.FileName, ms);

Could you help me with that?

**Comment by mbdavid** [comment]
Are you running in net35 or netstandard? Can you provide some code example to reproduce this error?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
