### ISSUE TITLE
Query using multikey index (where products are an array of embedded documents)

### ISSUE THREAD

**Issue by vlad-k4k** [mbdavid/LiteDB#474]
Hello

I have an issue with embedded documents. As per below sample I'm able to index and search by embedded documents but Find returns nothing.

> // Query using multikey index (where products are an array of embedded documents)
> var results = col.Find(Query.GT("Products.Price", 100))

Here is the complete code to test:

        public class Customer
        {
            public class Phone
            {
                public string Number { get; set; }
            }
            public int Id { get; set; }
            public string Name { get; set; }
            public Phone[] Phones { get; set; }
            public bool IsActive { get; set; }
        }

        static void Main(string[] args)
        {
            // Open database (or create if doesn't exist)
            using (var db = new LiteDatabase(@"MyData.db"))
            {
                // Get a collection (or create, if doesn't exist)
                var col = db.GetCollection<Customer>("customers");

                // Create your new customer instance
                var customer = new Customer
                {
                    Name = "John Doe",
                    Phones = new Customer.Phone[] { new Customer.Phone { Number = "8000-0000" } , new Customer.Phone { Number = "9000-0000" }},
                    IsActive = true
                };

                // Insert new customer document (Id will be auto-incremented)
                col.Insert(customer);

                col.EnsureIndex("Phones.Number");

                var results = col.Find(Query.EQ("Phones.Number", "8000-0000")); // returns no documents
            }
        }

**Comment by mbdavid** [comment]
Hi @vlad-k4k, do not use nested classes. I made same example here:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LiteDB;

namespace Test474
{
    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Phone[] Phones { get; set; }
        public bool IsActive { get; set; }
    }

    public class Phone
    {
        public string Number { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            // Open database (or create if doesn't exist)
            using (var db = new LiteDatabase(@"MyData.db"))
            {
                // Get a collection (or create, if doesn't exist)
                var col = db.GetCollection<Customer>("customers");

                // Create your new customer instance
                var customer = new Customer
                {
                    Name = "John Doe",
                    Phones = new Phone[] { new Phone { Number = "8000-0000" }, new Phone { Number = "9000-0000" } },
                    IsActive = true
                };
                
                // Insert new customer document (Id will be auto-incremented)
                col.Insert(customer);

                var r1 = col.FindOne(Query.EQ("Phones.Number", "8000-0000"));

                Console.WriteLine(r1.Name);
            }
        }
    }
}
```

But I found a bug here: when using array [] it's not working Linq expression like
`col.FindOne(x => x.Phones[0].Number == "8000-000"`
(works fine with List<T>)

I'm fixing this, thanks

**Comment by vlad-k4k** [comment]
Awesome thanks. Also I didn't realize this feature in v3.x.x only
