### ISSUE TITLE
Transparent offline mode

### ISSUE THREAD

**Issue by StefanKoell** [mbdavid/LiteDB#475]
This is more a feature request or a request for guidance:

I'm new to LiteDB and I really like it, especially the ability to have multiple processes/instances work with a single file seamlessly.

In our app, we require some kind of "offline mode" in case the file is located on a network share which is sometimes offline. Is this something which could be implemented or are there any patterns/strategies with LiteDB on how to implement that?

**Comment by mbdavid** [comment]
Hi @StefanKoell, if I told you that I create LiteDB thinking in that.... but I never real do this. When I create LiteDB my "dream code" was write an Server/Client service to provide offline sync provider to PouchDB. I read CouchDB git-style sync database but never go ahead with that.

**Comment by StefanKoell** [comment]
Yeah, I think this is a common pattern and I guess everyone is solving it "somehow" ;) Would be nice to have something like that built in...
