### ISSUE TITLE
question - referetial integrity on delete?

### ISSUE THREAD

**Issue by Jack85** [mbdavid/LiteDB#476]
How is it on deleting (cascade) not existing reference? If I have following example
`
public class Post : BEntity
{

	public string Title { get; set; }
	public string Content { get; set; }
	
	public List<Category> Categories { get; set; }
	
}
public class Category : BEntity
{
	public string Name { get; set; }
	public Post post {get;set;}
}`
with mapping like this:
```
mapper.Entity<Post>()
	.Index(x => x.Title)
	.Index(x => x.Content)	
	.DbRef(x => x.Categories, "category")
	
	//dbpost
	mapper.Entity<Category>()
	.Index(x => x.Name).DbRef(x=>x.post, "post");
```

I insert two categories, 
if I insert post with those two categories, and I delete that first category , I still have non existing ID in post as ref in post collection.
How to make like cascade auto delete?

`
using (var db = new LiteDatabase(@"D:\\data.db", mapper))
	//using (var db = new LiteDatabase(path))
	{
	
		//DROP FIRST
		db.DropCollection("post");
		db.DropCollection("category");
			db.Shrink();
		// Get customer collection
		var col = db.GetCollection<Post>("post");
		var catcol = db.GetCollection<Category>("category");
	
		var Cats = new List<Category>();
		Cats.Add(new Category() { Name=".net"});
		Cats.Add(new Category() { Name = "django" });
		var posts = new List<Post>();
		
		var post = new Post
		{
			Title = "lambda tutlzl",
			Content = "some labda conent",
			Categories = Cats
		};

		catcol.Insert(Cats);

		post.ID = col.Insert(post);
catcol.Delete(x=>x.ID==1);
}
`

**Comment by mbdavid** [comment]
Hi @Jack85, LiteDB (an other nosql document database) has no referential integrity. In this case, if you delete category, Post still referes to deleted document. But, when you query using Include null will be set to your field reference,

**Comment by Jack85** [comment]
Thanks for info. 
Wouldn't be cool to have that feature support like mongoose or other frameworks do, that you make some kind of plugin to support this behavior?
http://stackoverflow.com/questions/14348516/cascade-style-delete-in-mongoose

**Comment by mbdavid** [comment]
Yes, mongoose is middleware/orm that do some like this (provide support for pre-remove event to write your own cascade).

Maybe it's possible in LiteRepository, an project that I have in mind to create a repository pattern using LiteDB.
