### ISSUE TITLE
Support readonly documents

### ISSUE THREAD

**Issue by magsoft2** [mbdavid/LiteDB#478]
[Suggestion]
Hello!

Databases often used for storing logs or some data which is added to db and do not supposed to be changed. I am storing performance data in my library, for example. 
Resulting liteDB file could be very big for may items, and it is bigger than it could be.
There is a discussion on db file size here #242 . You suggested to play with LiteDB internal settings like PAGE_AVAILABLE_BYTES.

 Could we have some option like this available in connection string or at DB initialization, or db\engine object option allowing reduce db file size? Or may be at document\collection adding? 
Or, for example, have an AddOrQueryOnly collection type or collection optimized for addonly?

Thanks.

**Comment by mbdavid** [comment]
Hi @magsoft2, I remeber this issue and after some tests comparing with SQLite, LiteDB uses almost double size file. If your document has less than 4070 datafile can be reduce crate a parameter, per collection, in DATA_RESERVED_BYTES = 400 (DataPage.cs). If your document are more than 1 page (4070 bytes) will not change too much.

I made same tests and, reduce to 400 bytes reserved bytes its possible to change file from 7500 to 5500 in LiteDB-Pref tests (https://github.com/mbdavid/LiteDB-Perf).

```
LiteDB: default - 5000 records
==============================
Insert         :  6866 ms -      728 records/second
Bulk           :   240 ms -    20828 records/second
Update         :  8270 ms -      605 records/second
CreateIndex    :   223 ms -    22420 records/second
Query          :   304 ms -    16406 records/second
Delete         :   169 ms -    29534 records/second
Drop           :    17 ms -   281246 records/second
FileLength     :  5304 kb

LiteDB: encrypted - 5000 records
================================
Insert         :  7357 ms -      680 records/second
Bulk           :   272 ms -    18361 records/second
Update         :  5632 ms -      888 records/second
CreateIndex    :   188 ms -    26484 records/second
Query          :   280 ms -    17798 records/second
Delete         :   183 ms -    27234 records/second
Drop           :    32 ms -   152650 records/second
FileLength     :  5408 kb

LiteDB: exclusive no journal - 5000 records
===========================================
Insert         :  2260 ms -     2212 records/second
Bulk           :   227 ms -    22003 records/second
Update         :  1677 ms -     2980 records/second
CreateIndex    :   183 ms -    27221 records/second
Query          :    99 ms -    50042 records/second
Delete         :   145 ms -    34418 records/second
Drop           :    10 ms -   498033 records/second
FileLength     :  5408 kb
```

**Comment by magsoft2** [comment]
Ok, thank you.
Seems I need to review my data structures than. I store as a document  {TimeStamp, float Value} which is very small ~8 bytes. Collecting 10 counters every 5 seconds, have ~ 100000 records per day.
I am refactoring now to have only one document per big timeseries, all values will be stored inside this one document as arrays. I see that it greatly diminish db file size.
