### ISSUE TITLE
MultiKey Index  on dictionary keys?

### ISSUE THREAD

**Issue by vip32** [mbdavid/LiteDB#479]
Hi @mbdavid ,
great work on the new multikey indexes. do they also work with dictionaries?

like this:
```
customers.Insert(new Customer { Name = "John", Phones = new Dictionary<string, string> { 
["1"] = "54-3533", 
["2"] = ""43-4324"
});
```

var result = customers.Query(x => x.Phones.Keys.Contains("1")); // returns first document

**Comment by mbdavid** [comment]
Hi @vip32 , It's not possible with dictionary because dictionary are "embedded" document when transformed to BSON data type. If you need index data in dictionary, try create new virtual index field, like:

```
BsonMapper.Global.Entity<Class>().Index("phones", x => new BsonArray(x.Phones.Values));
```

**Comment by vip32** [comment]
ah ok, i see i can query embedded documents now (v3) https://github.com/mbdavid/LiteDB/issues/474
that will also solve my problem.
