### ISSUE TITLE
TTL index

### ISSUE THREAD

**Issue by janstafa** [mbdavid/LiteDB#482]
Hi, 
is there any way how to create a TTL index like in MongoDb or I have to implement a logic to remove old records myself?
Thanks,,
Jan

**Comment by mbdavid** [comment]
Hi @janstafa, TTL indexes works in background process, deleting records when get defined age. But LiteDB works as an embedded document and there is no background process to be automatic.

I think you can create same extension method to collection that remove data using an conventional date index but you will need call when you want, not in automatic way.

Regards,
