### ISSUE TITLE
Import/Export

### ISSUE THREAD

**Issue by dgodwin1175** [mbdavid/LiteDB#487]
Hi,

Is there a way to import/export the contents of the database from a file?  If so, could you provide an example?
Failing this, I can write my own, but something built in to litedb would be very helpful.

Thanks.

**Comment by mbdavid** [comment]
Simple way

```
var json = JsonSerializer.Serialize(new BsonArray(db.Engine.Find("mycol")));

db.Engine.Insert("mycol", JsonSerializer.Deserialize(json).AsArray.ToArray());
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
