### ISSUE TITLE
Trying to test for large data sets and I get failures

### ISSUE THREAD

**Issue by wcmiller3** [mbdavid/LiteDB#49]
I've upped the number of records added by the demo application.  When the file size hits about 4GB, I get a failure.  Anything I should try?

**Comment by mbdavid** [comment]
Did you have error message exception? There is no 4GB limit on database size.

**Comment by wcmiller3** [comment]
I've repeated it a few times. I've set the sample customer program to add 3 million records. And I run it again. By the 3rd time, I receive a NotImplementedException during an insert.

**Comment by wcmiller3** [comment]
I'm seeing great potential but I really have a need for larger data sets. It failed much earlier with the app set to 32 bit.

**Comment by sherry-ummen** [comment]
I can confirm it happens for me too.

**Comment by mbdavid** [comment]
Hi guys! Yes, I do this test and fails to me too. I don't know why yet, but I will investigate this weekend. I guess can be something in FileStream or like that.

**Comment by mbdavid** [comment]
Hi @wcmiller3 and @sherry-ummen, bug fund! I simple `uint<->long` convert error. I will create a new release for this

**Comment by sherry-ummen** [comment]
ok I tested this. One thing is strange which I am not sure whether its a bug or some OS feature.

so my program is simple

```C#
 foreach (var index in Enumerable.Range(1, 10000)) {
                    var emp = new Employee() {
                        EmployeeID = "owsddyu" + index,
                        FirstName = "one",
                        LastName = "two",
                        Bytearray = new byte[1 * 1000 * 1000]
                    };
                         col.Insert(emp);
                  }
```

So when its running you can check in the folder that the file size is increasing but after it reached the 4Gb then the updating of the file stops and when you stop the execution then you see the final size which is more that 4Gb depending on for how much time you keep it running.

My doubt is that why after 4Gb it stops showing the file size changing? And when the program is stopped then only it updates the size. Whats going on?

Thanks

**Comment by mbdavid** [comment]
Hi @sherry-ummen, do not use `Insert` method to bulk many data. Take a look on new unit test: https://github.com/mbdavid/LiteDB/blob/master/UnitTest/BigFileTest.cs

I'm using Windows 10 x64 and updates on file explorer are normal after 4gb. In this example, grows in ~500mb each update.

**Comment by sherry-ummen** [comment]
Hi, yes I checked the unit test and actually ran that also and there it worked. About using of Insert the thing which I am trying to check here is that it may happen that there may be random read and write but there may be huge number of writes so I really cannot determine when to use Insertbulk.

Could you give a better solution then? Thanks
