### ISSUE TITLE
An item with the same key has already been added. (Different to #455)

### ISSUE THREAD

**Issue by ChrisDodgeRR** [mbdavid/LiteDB#490]
Hi,

When moving from v3.0.0-beta2 to v3.0.0 my DBs became unreadable, with the error "An item with the same key has already been added." in LiteDB.IndexPage.ReadContent() when adding a new node to the Nodes dictionary.

Working back through the commits, what's broken things is the commit on 22/12/2016 where Bson Decimal support was added to BsonTypes.cs. Instead of adding this as a new type at the end of the enumeration, it was inserted into the enumeration, shifting other enumeration values up.

As the enumeration value is used to read the correct type when reading the IndexNode.Key, it now means that the incorrect number of bytes may be read. In my case, the Bson type when reading the key was a BsonType.MaxValue (13) so no further key bytes read. After this commit, the key type is thought to be BsonType.DateTime (13) so 8 bytes are read instead. The knock-on effect is that further reading by the ByteReader is now incorrect, leading to the invalid values showing themselves with this kind of error in the title.

```
                node.Page = this;
                node.Position = new PageAddress(this.PageID, index);
                node.Slot = reader.ReadByte();
                node.PrevNode = reader.ReadPageAddress();
                node.NextNode = reader.ReadPageAddress();
                node.KeyLength = reader.ReadUInt16();
                node.Key = reader.ReadBsonValue(node.KeyLength);   // <--- Here
                node.DataBlock = reader.ReadPageAddress();

```
Is there any way to handle this? Can the KeyLength value be used to control the number of bytes read for the IndexNode.Key? Or is there a DB file version that could be used to check to know what key types are stored in that file? Or perhaps upgrade logic can be added to cope with this?

OK, maybe I shouldn't have used a beta version for an actual project, but I had anticipated that the DB file format would not become invalid between V3 beta 2 and release.

Thanks for any help...

Chris

**Comment by mbdavid** [comment]
Hi @ChrisDodgeRR, yes, I found this bug last weekend after some issues about migration after 3.0.0 release. It was little hard to detect that I changed BsonType enum values to release 3.0.0 and this crash migration.

Thanks and congrats to detect this!! Really cool !! Current 3.0.1 already fixed this using old BsonType enum values in convert.

**Comment by ChrisDodgeRR** [comment]
Hi, 

Thanks for the quick reply! I still get this error with 3.0.1 as my DBs were created with the v3 beta 2, so are I guess V7 and so the upgrade process ignores them I think.

Any other options, apart from me implementing my own v3b2 -> v3.0.x DB file upgrade logic?

BTW: Very useful DB, so thanks!

Chris

**Comment by mbdavid** [comment]
Yep, you got it. I change V7 without notice :) sorry. But to implement v8 during beta->release will too much work.

Did you have only a single datafile? You can export/import using some like this:

```
var json = JsonSerializer.Serialize(new BsonArray(db.Engine.Find("mycol")));

db.Engine.Insert("mycol", JsonSerializer.Deserialize(json).AsArray.ToArray());
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
