### ISSUE TITLE
Question: Is v3 backwards compatible?

### ISSUE THREAD

**Issue by vkocjancic** [mbdavid/LiteDB#491]
Hi.

Before upgrading from v2.0.4 to v3.0.1 (due to db file locking issue), I want to know if version 3.0.1 is compatible with db files created with v2.0.4?

Best regards

**Comment by vkocjancic** [comment]
Hi @mbdavid.
I get that backwards compatibility is difficult. But, if v3 is incompatible with v2, is there a chance we get proper file locking in v2? 
Currently it locks up every few days in real time environment with low traffic.

**Comment by vkocjancic** [comment]
@mbdavid The import example does not work in version 3.0.1. Insert demands IEnumerable of BsonDocument.

**Comment by mbdavid** [comment]
No problem, each element is a Document in this array
```
// import from JSON
db.GetCollection("mycol").Insert(JsonSerializer.Deserialize(json).AsArray.ToArray().Select(x => x.AsDocument));
```

About this locking problem in v2, v3 works complete diferent way so it's difficult to know. Is your enviorment multi process or a single process (like and website)? Are you using transactions? If you working in a single process enviroment/no transaction try works with a single instance of LiteDatabase (kepping in static var)

**Comment by vkocjancic** [comment]
Hi. 
It is a simple website with simple CMS and product catalogue. No transactions are used. The process is multithreaded though, as multiple request can come at the same time.

**Comment by mbdavid** [comment]
If is a single process (IIS) in a multithread concurrent requests, you can use single instance of LiteDatabase (that are thread safe in v3) is much faster. But, your datafile will always keep opened (in shared mode) an will close only when application pool recicle.

**Comment by vkocjancic** [comment]
Yeah, but application pool never recycles. It helps with reducing performance hits for first time users after restart.
