### ISSUE TITLE
LiteDB on Windows Phone 8 project.

### ISSUE THREAD

**Issue by axanth** [mbdavid/LiteDB#492]
Hi,

Can it be used in Windows Phone 8.1 project? I tried but i get Exception probably by the fact that the portable version targets NetStandard 1.4.

Thank you.

**Comment by mbdavid** [comment]
Hi @axanth, according this chart (https://github.com/dotnet/standard/blob/master/docs/versions.md) NetStandard 1.4 are not compatible with Windows Phone 8.

If you need Windows Phone 8 you can use v2.0.4 (that are compatible with PCL)

**Comment by axanth** [comment]
Hi David,
Thank you for your answer! Can you provide any help on which profile is compatible. 
I tried to install 2.0.4 but it outputs error : "Some packages are not compatible with .NETPortable,Version=v4.5,Profile=Profile111"
 Thank you!

**Comment by mbdavid** [comment]
Hi @axanth, for 2.0.4 you need search for "LiteDB.Core" in nuget. It's quite different from v3. Take a look in this old page in how to use:

https://github.com/mbdavid/LiteDB/wiki/Portable-Version/e937869ea526ac4a4a49f1666361e56ce91fdf30

**Comment by axanth** [comment]
Hi David, I managed to use LiteDB after your suggetions. Thank you for your help!
I am facing very slow performance in a collection of 234 objects (Products). I have to say though that each object has a lot of properties some of which are other classes (refs). I some cases I get exception of a long lock of database file (i.e ensure index). Is this normal??
