### ISSUE TITLE
EnsureIndex of Dectionary

### ISSUE THREAD

**Issue by shai-benshimol** [mbdavid/LiteDB#493]
Hello David,

Is it posibole to ensureIndex of collection dictionaty?

Dict<int,User> => ensureIndex of User.Email

**Comment by RytisLT** [comment]
What have you tried?

**Comment by mbdavid** [comment]
You always ensureindex / query using strings only, like:

`EnsureIndex("User.Email")`

`Find(Query.EQ("User.Email", "john.doe@email.com"))`

LINQ works only in strong typed classs.
