### ISSUE TITLE
Virtual index fields

### ISSUE THREAD

**Issue by vlad-k4k** [mbdavid/LiteDB#494]
Virtual index fields mentioned in v3.0.0-beta but nothing in doco. Could we have a sample?

**Comment by mbdavid** [comment]
Virtual fields are Func that you can create to create an index based on this result, like this:

```
BsonMapper.Global.Entity<Order>()
    .DbRef(x => x.Customer) // will not include customer inside order document
    .Index("CustomerName", x => x.Customer.Name); // but create a search for customer name

// and than you can:

orders.Find(Query.EQ("CustomerName", "John"))
```

**Comment by vlad-k4k** [comment]
That looking good, thanks. One more question - if I add new index to existing collection is there any way to re-index the whole collection on that index?

**Comment by mbdavid** [comment]
Hi @vlad-k4k, I miss this question... sorry. I anwser in your new issue. As I told, there is not re-index, but in virtual indexes could be an exception.... why?

Well, virtual indexes are based only in entity mapper. So, if you open your datafile in an external app (like Shell) there is no virtual mapper, and all insert/update data will not be indexed.

**Comment by vlad-k4k** [comment]
@mbdavid may I suggest to have an API function to re-index? As for new indexes for existing collection or if indexing logic changed (in case of virtual index) the index become 'corrupted' - not correlating to the actual data.

**Comment by mbdavid** [comment]
Yes @vlad-k4k, make sense... it's on my list. I marked as suggention in your other issue about this.
