### ISSUE TITLE
NRE during FindAll

### ISSUE THREAD

**Issue by podkolzzzin** [mbdavid/LiteDB#496]
I have such code:

```
    private LiteCollection<BsonDocument> Sessions {
      get {
        return GetCollection(SessionCollection);
      }
    }
...
var sessions = Sessions.FindAll().ToList();
```

And once it accidently falls with NRE:

> Stack:
>    at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log)
>    at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
>    at LiteDB.LazyLoad`1.get_Value()
>    at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

I construct LiteDatabase class using the ctor with single argument(connectionString).

I investigated your code a bit, and the only suspicious place is: https://github.com/mbdavid/LiteDB/blob/c28238e536cfc1eabbcc778696351c34c273fb46/LiteDB/Engine/LiteEngine.cs#L107

P.S. Please reopen issue #363, I tested it on the latest sources and it still reproducing. Code sample is in the issue.

**Comment by mbdavid** [comment]
Hi @podkolzzzin, I will take a look again on this. This line code that you marked is correct in this context.

**Comment by podkolzzzin** [comment]
Hi, @mbdavid, you are probably right. 
I just looked through the method and that's all.
As for me using of 'as' operator is appropriate only if null check exist, but in your case, you just use property, so probably direct cast would be more informative?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
