### ISSUE TITLE
Suggestion naming the project "NoSQLite"

### ISSUE THREAD

**Issue by mosdja** [mbdavid/LiteDB#497]
hi
May have an propaganda effect of SQLite's  popularity

**Comment by RytisLT** [comment]
SQLite folks might be upset because of that. It's not nice to ride on popularity of other. LiteDB is gaining traction on it's own. What it needs now is to get more stable.

**Comment by mbdavid** [comment]
Hi @mosdja, it´s a nice name :) If this suggestion was at begining it could be possible. But now it's a bit complicated.
