### ISSUE TITLE
Sort and filter does not work when combined with Query.And()

### ISSUE THREAD

**Issue by RytisLT** [mbdavid/LiteDB#498]
The sort gets completely ignored when it's combined with Query.And and the result is in "random" order. The following query from the LiteDB wiki does not work in v3:

`var results = col.Find(Query.And(Query.All("Age", Query.Descending), Query.Between("Age", 20, 30)));`

I've submitted a pull request which fixes (and tests) this issue.  https://github.com/mbdavid/LiteDB/pull/471

**Comment by mbdavid** [comment]
Hi @RytisLT, thanks for you PL. , I saw it but not merged yet. It's on my plans but I want made more tests before.

**Comment by RytisLT** [comment]
@mbdavid what would you like to test? Maybe I could add more tests to pull request

**Comment by mbdavid** [comment]
Hi @RytisLT, I saw your unit test in PL. I will merge this Carnival holidays...

**Comment by mbdavid** [comment]
PL merged 👍
