### ISSUE TITLE
Timeout. Database is locked for more than 00:00:00.

### ISSUE THREAD

**Issue by vlad-k4k** [mbdavid/LiteDB#499]
Having this issue in v3.0.1
Initially I had it in IIS Express but found a workaround - removed updrade=true from connection string an that fixed the problem. But when deployed to production it started again.
My connection string is: "Filename={0};Mode=Shared;Timeout=0:10:00;" just tried Mode=ReadOnly - same thing.
Same code that was working in v2 with no issues

**Comment by vlad-k4k** [comment]
This sample to reproduce locking issue with  updrade=true

[LiteDbTest.zip](https://github.com/mbdavid/LiteDB/files/795907/LiteDbTest.zip)

**Comment by RytisLT** [comment]
+1
I've seen this error too couple of times, wasn't sure how to reproduce though

**Comment by mbdavid** [comment]
Hi @vlad-k4k, I download your code and test it. The main problem here is "upgrade=true", becase there is no lock when litedb checks for if datafile needs upgrade.  Just removed "upgrade=true" and works fine (I tested with lastest LiteDB master version).

Avoid use upgrade=true in your ConnectionString for "all-times" connection. Upgrade=true is indicated only you problably has a old version datafile and you want convert it (like in a mobile/desktop app). If is possible, test once only using `LiteEngine.Upgrade`.

**Comment by mbdavid** [comment]
Ok, I got now this exception: when multi-thread try open same datafile and one instance are during journal writing. Fixed now

**Comment by wuzhenda** [comment]
it happened today in litedbv4,when mass data save to db

**Comment by mbdavid** [comment]
Hi @wuzhenda, LiteDB use a single write process, so, if you have long writing processes it´s normal to get timeout in other threads (including read threads).

I'm planning a new version of litedb that will works with version/serialziation data that will avoid this. But it's only in my future plans
