### ISSUE TITLE
能考虑支持mono和xamarin平台吗？

### ISSUE THREAD

**Issue by lable** [mbdavid/LiteDB#5]
在windows .net framework 3.5 4.0 4.5 上都能正常运行，能不能能考虑支持mono 和 xamarin?

**Comment by mbdavid** [comment]
Hi, I never works with mono or xamarin, but I have plans, in future, to be compatible with Windows Phone. Mono and xamarin will be tested too.

**Comment by lable** [comment]
Thank you!
