### ISSUE TITLE
How can I reduce the db file size?

### ISSUE THREAD

**Issue by bbolgumer** [mbdavid/LiteDB#50]
Add a large file and then file delete (using FileStorage.Delete(fileID))
But, does not decrease the size of the database file.

I want to reduce the file size. is there any options?

**Comment by mbdavid** [comment]
Hi @bbolgumer, take a look on issue #18

**Comment by mbdavid** [comment]
Hi @bbolgumer, just to know, current `master` branch version support shrinks now!
