### ISSUE TITLE
Question - How to change database password after it's creation

### ISSUE THREAD

**Issue by rmszc81** [mbdavid/LiteDB#504]
Greetings @mbdavid,

it seems that I won't give u peace soon, hehehehe.

once again, thank you for liteDB, it's a wonderful tool, it fits perfectly my research project.

I have a question this time: Is it possible to change the database password after it's creation?

Why?

Example:

Each user has it's own database. So, the database is created with user password. When user change it's password, I'd like to change the password of the database too.

Is it possible? If the answer is yes, how?

Thank u.

[].
Regards,

@rmszc81

**Comment by falahati** [comment]
LiteDatabase.LiteEngine.Shrink(newPassword);

**Comment by rmszc81** [comment]
Solved.

Thank you.
