### ISSUE TITLE
How to create database at any location in uwp

### ISSUE THREAD

**Issue by swordream** [mbdavid/LiteDB#507]
i want to visit database at any locaction in uwp,for example, d:\\abc.mb,
in v2,i can implement a uwpfilehandler to do this,but i have no idea in v3,so how to do this?

**Comment by mbdavid** [comment]
Hi @swordream, I never work with UWP so I'm the right guy to anwser. As I know, you will need special permission on other folder than you current location folder. The only "special" operation LiteDB do is works with `System.IO.FileStream`, so any documentation about open/close file (using FileStream) could be applied.

**Comment by swordream** [comment]
Can you  make basepage and headerpage public to allow third party developer implement IDiskService ?

**Comment by mbdavid** [comment]
Hi @swordream, do you need base/header page to initialize database? I thinks that this initialize could be an external class/method. @szurgot implement a custom async version of FileDiskServiceAsync.

https://github.com/szurgot/LiteDB/blob/b935f7234b83ac6909a0867c47e193aef91a950a/LiteDB/Engine/Disks/FileDiskServiceAsync.cs

If this works, It's possbile include inside LiteDB core.

**Comment by swordream** [comment]
because  in any case the following code is needed.
i am trying to implement a uwp version of IDiskService using StorageFile.              

 ```
if (password != null)
                {
                    _log.Write(Logger.DISK, "datafile encrypted");

                    header.Password = AesEncryption.HashSHA1(password);
                    header.Salt = AesEncryption.Salt();
                }

                // write bytes on page
                this.WritePage(0, header.WritePage());

                // write second page empty just to use as lock control
                this.WritePage(1, new byte[BasePage.PAGE_SIZE]);
```

**Comment by mbdavid** [comment]
Hi @swordream, i'm adding this code to static LiteEngine CreateDatafile method.

**Comment by swordream** [comment]
Thanks , I will share my code after test

**Comment by mbdavid** [comment]
Hi @swordream, added support to work in any directory in UWP. Use `async=true` inside connection string.
