### ISSUE TITLE
Rebuild index on existing collection

### ISSUE THREAD

**Issue by vlad-k4k** [mbdavid/LiteDB#509]
Let's say if I have a collection and I add new index only newly added or updated documents get indexed. Is there any simple way to re-index all the documents in collection?

**Comment by mbdavid** [comment]
No, when you create an index all existing documents will be indexed (like in any rdbms). In fact, there is no need to rebuild index. But, if you want, you must drop all indexes + ensure all indexes again (except _id primery key)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
