### ISSUE TITLE
Implement OnUpdate or OnCommit triggers

### ISSUE THREAD

**Issue by nildarar** [mbdavid/LiteDB#51]
Hi,
I wrote an application that can send updates from editor to client. i want implement an db check organism in the client that check db last modify date before install it. can i use db file modified date for this kind of work?
or How can I use global update trigger in the editor for each change like these:

    public class AppData : LiteDatabase {
        public AppData()
            : base(DataStore.ConnectionString) { }

            protected override void Commit() {
                var cl = this.GetCollection<DbInfo>("db");
                var dbi = cl.FindById(0);
                dbi.ModifiedOn = DateTime.UtcNow;
                cl.Update(area);
                base.Commit()
            }
        }

English isn’t my first language, so please excuse any mistakes.

**Comment by nildarar** [comment]
I found some properties in `db.GetDatabaseInfo()` useful for this kind of work.

    changeID
    fileLength
    lastPageID

**Comment by mbdavid** [comment]
Hi @nildarar,

I don´t think that override `Commit` method is a good ideia. Internal, this method just call `transaction.Commit()`, so this will works only with explicit `Commit` call (not implicit).

You ca use Last file modified date because only open and run queries didn´t change data file.

**Comment by mbdavid** [comment]
Yes, you can use `GetDatabaseInfo()` too, but here has no DateTime to know when was last modified.

`changeID` is a counter that increment after each commit
`fileLenth` and `lastPageID` is total size/last page used - it´s not indicate if has any changes.

**Comment by nildarar** [comment]
thanks @mbdavid.
LiteDB can have a good future, thanks for sharing it.
