### ISSUE TITLE
create seperate package of LiteDB.Shell

### ISSUE THREAD

**Issue by FroggieFrog** [mbdavid/LiteDB#511]
When trying to compile the [LiteDBViewer](https://github.com/falahati/LiteDBViewer), there is a need for the complete LiteDB.Shell-folder from this repo.
This is necessary because there is no public avaible namespce or a seperate NuGet-package for the Shell.
Maybe it is a good idea to create a seperate NuGet-package for the Shell so it can be referenced from different projects.

**Comment by mbdavid** [comment]
Hi @FroggieFrog, before v3, shell commands are inside core litedb. But, in v3 i removed all parser commands from core and add all in shell tools.

So now, shell tool is just a single exe file and I dont see how nuget package can be used for this. Maybe LiteDBviewer must add all shell source code as reference.
