### ISSUE TITLE
Unable to cast object of type 'LiteDB.HeaderPage' to type 'LiteDB.IndexPage'

### ISSUE THREAD

**Issue by Vakterman** [mbdavid/LiteDB#512]
Hello!
I had tried to migrate from LiteDb-3.0.0 beta 2 version to 3.0.1 and i had saw this exception 

Exception thrown: 'System.InvalidCastException' in LiteDB.dll
Unable to cast object of type 'LiteDB.HeaderPage' to type 'LiteDB.IndexPage'

For resolving it i set uprage flag  to true and used LiteEngine.Upgrade method without any results.
Do you have any idea?

**Comment by mbdavid** [comment]
Hi @Vakterman, sorry about that. I made some changed from beta2 to final version and I dont realize that could be a problem from beta users.

There is not upgrade process from beta to final v3. You must export your data (using v3-beta) and import again using v3. Some like that:

```
// to export, using v3-beta DLL (or any other LiteDB version)
var data = new BsonDocument();
foreach(var name in db.GetCollectionNames())
{
    data[name] = new BsonArray(db.GetCollection(name).FindAll());
}
File.WriteAllText(@"C:\Temp\dump-data.json", JsonSerializer.Serialize(data));

// to import, using v3 DLL
var data = JsonSerializer.Deserialize(File.ReadAllText(@"C:\Temp\dump-data.json")).AsDocument;
foreach(var name in data.Keys)
{
    db.GetCollection(name).Insert(data[name].AsArray.Select(x => x.AsDocument));
}
```

**Comment by Vakterman** [comment]
Thank you very much! It is very usefull.

But not applicable for my solution, because it is complex migration.
I will try to find appropriate way for resolving it in my projects.

**Comment by Vakterman** [comment]
Also one question about it. Could you explain, how to distinguish two different file format ?
I mean - how to define latest file format version and beta 2 format.
I need it for deviding it from C#   code end avoiding exceptions.

**Comment by mbdavid** [comment]
It's just a single Enum in BsonType that I added (Decimal type) + re-order (I complete forgot that this are storaged in indexes). I only detect the problem when I write Upgrade (from v2) code.
