### ISSUE TITLE
Invalid connection string when using shared mode

### ISSUE THREAD

**Issue by onurhb** [mbdavid/LiteDB#517]
Hi, 
I am trying to open the database in shared mode. However I am getting this error:
`Unhandled exception: LiteDB.LiteException: Invalid connection string value type for [mode]`  

This is how I access the database:  

```cs
using (var db = new LiteDatabase("Filename=Database.db;Mode=Shared"))
{
  ...
}
```

I am using .net core 1.1.

**Comment by onurhb** [comment]
Adding it to the dependency injection as singleton works as following:
`services.AddSingleton<IDatabaseRepository, DatabaseRepository>();`
For some reason, I was using AddTransient which creates one instance per object. This fixes my problem. Thanks for reply.

**Comment by sgrassie** [comment]
Any thoughts on this now that netstandard2.0 has been released?

**Comment by mbdavid** [comment]
@sgrassie, I'm thinking in update to v4 final release. I will remove 1.3 support to add only 2.0
