### ISSUE TITLE
"Collection  exceeded the maximum limit of indices: 16"

### ISSUE THREAD

**Issue by mattiaspalm** [mbdavid/LiteDB#518]
Don´t know why I get this error message when I try to find documents in my collection, 
I try with:
```
var results = col.Find(Query.StartsWith("FullName", "Hapa"));
var namer = col.Find(a => a.FullName.StartsWith("Hapa"));
```

when I do a col.FindAll or col.Count all data I have saved is there, 
maybe I do something wrong with the index? I tried with col.EnsureIndex(test.FullName);

**Comment by mbdavid** [comment]
Hi, every time you do run Find using different fields you are creating new index in collection. LiteDB limit in 16 indexes per collection. To see all indexes, in shell tool run `db.yourcol.indexes`. You can drop indexes using `db.yourcol.dropIndex fieldname`

**Comment by mattiaspalm** [comment]
thank you, I made new index in an iteration so I guess it was a lot more than 16
