### ISSUE TITLE
Would be great to collect/show real usage

### ISSUE THREAD

**Issue by xied75** [mbdavid/LiteDB#519]
Either in the Readme or Wiki to list Applications that was using LiteDB, for a Showcase. This would encourage the adoption for sure :)

**Comment by johnzens** [comment]
@xied75 @mbdavid I really support the idea. I have thought about it before as well. From my experience with using both relational and nosql databases, i realize that litedb is quite better than even some commercial products. A list of applications using it would be great. And i plan to put up some tutorials on litedb in a few weeks,to complement Mr David's great work.

**Comment by mbdavid** [comment]
Hi @xied75 @johnzens, thats a nice ideia. I will open an issue + add in readme about this to encourage others to tell if are using in real life applications. I only used in internal projects.

@johnzens if you produce any tutorial, video or code, please tell me to share here. Will really nice to know that someone else are using and liked this project.
