### ISSUE TITLE
Id field not discovered deterministically in LiteDB 3

### ISSUE THREAD

**Issue by szurgot** [mbdavid/LiteDB#520]
In LiteDB 3, the ID field is discovered differently from LiteDB 2. In investigating this, it is also possible that two fields could be set to _id, with the last one found winning, and any early fields are lost and not mapped.

I have a fix and will be submitting a PR shortly.

**Comment by mbdavid** [comment]
Hi @szurgot, yes, there is no check about this. But I saw your PL and you remove virtual method that check this (`IsMemberId`) and added GetIdProperty method (with get another loop into memebers). Isn't better just add some like this:

```C#
var hasId = false;

foreach (var memberInfo in this.GetTypeMembers(type))
{
    // checks [BsonIgnore]
    if (memberInfo.IsDefined(ignoreAttr, true)) continue;

    // checks field name conversion
    var name = this.ResolveFieldName(memberInfo.Name);

    // checks if is _id
    if (!hasId && this.IsMemberId(type, memberInfo))
    {
        name = "_id";
        hasId = true;
    }
    
    ...
}
```

**Comment by szurgot** [comment]
@mbdavid You fix handles the case where you can have duplicate _id mappings, but it doesn't fix the other case, which is where you can have a field named id, and field decorated with [BsonId] and it will pick the Id field instead of the explicitly labeled field.

Also, I looked at my code again, and I left an extraneous loop in getIdProperty. I'll pull it out and send a more efficient PR
