### ISSUE TITLE
InsertBulk?

### ISSUE THREAD

**Issue by adamhathcock** [mbdavid/LiteDB#522]
I saw this is missing from the current code.

I'm getting around this by just wrapping my Insert loop in a transaction (like I would with SQLite), is that correct to get the best bulk performance?

Also doing Upsert in a transaction as well.

**Comment by mbdavid** [comment]
Hi @adamhathcock, when you use `collection.Insert(IEnumerable<T> documents)` you are already using inside a transaction / bulk operation.
