### ISSUE TITLE
[Question] FileStore, Transactions and data corruption?

### ISSUE THREAD

**Issue by mkosieradzki** [mbdavid/LiteDB#523]
If I understand correctly:
1. Journal is being written only when commiting a transaction.
2. FileStore does not supports transactions

Does it mean that file store writes/deletion might lead to the db file corruption (if interrupted in the worst moment) because of lack of journaling?

Or is the page-mechanism designed the way these are safe operations? And in the worst case we will end up with some unlinked pages?

**Comment by mbdavid** [comment]
Yes, journal writes only when commiting. The steps are:

1) Write all dirty pages to journal (write original data)
2) Update all dirty pages do datafile
3) Clean journal file

If any problem occurs during step 1, next connection will just delete journal file. If any problem occurs during step 2, all journal file will be restored into datafile.

But, to do this, I need keep all dirty pages in memory (cache). So, to store files it´s complicated to store all file in memory, so I split file in chunks. Each chunk are in a transaction (each chunk has 1mb). So, to write new file inside storage, these are the steps:

1) Write file header descriptor (in _files collection) with Length = 0
2) Slipt file in chunk. Each chunk in a transaction (in _chunk collection)
3) Update header descriptor to Length = final_file_length

So, there are, at least, 3 transactions here. If any problem occurs during spliting file, you will get only part (or none) of file in chunks, but your descriptor still in 0 bytes length. You just need delete any file with FileLength = 0.
Datafile will not be corrupted, only this file will be unfinished.

**Comment by mkosieradzki** [comment]
@mbdavid Thanks a lot for clarification this is exactly as I hoped it works based on #486 ...

AFAIK chunks are 255KiB not 1mb :).

I am currently implementing an alternative API (async-friendly) for file storing based on your low level API.

BTW. Do you consider rewriting API and locking to be async-friendly inside the LiteDbEngine in the next version?

**Comment by mbdavid** [comment]
Hi @mkosieradzki, yes 256 and not 1mb (1mb it´s max document size).

Next major version (v4) will be .NET45/NetStandard 2.0 only and will works async too. Thats my goal :)

**Comment by mkosieradzki** [comment]
@mbdavid
Yeah! That's great news!
