### ISSUE TITLE
I have to reference specific dll when I want to read a collection !

### ISSUE THREAD

**Issue by pianzide1117** [mbdavid/LiteDB#528]
Can i read a collection and ignore the _type  format? in that case, I can read a collection without reference the dll witch the source type of the collection items.

**Comment by mbdavid** [comment]
Yes, you can use `GetCollection(name)` and use `BsonDocument` as your data manipulation.

**Comment by pianzide1117** [comment]
Yes, I can use AsDocument property and deserialize it as json like. Many Thanks.

**Comment by pianzide1117** [comment]
and i failed !  how can I deserialize a BsonDocument to a super class which is be in inherit by the collection item.
I insert type A into a collection and I get collection in type B.Type A inherit from type B.

**Comment by mbdavid** [comment]
If you want convert class to/from BsonDocument you always need use `BsonMapper`.

```
var m = new BsonMapper();

var doc = (your bson document)

var obj = m.ToObject<MyClassType>(doc);
```

If your document contains `_type` you can just removed from BsonDocument

**Comment by pianzide1117** [comment]
it work well ! many thanks  !
