### ISSUE TITLE
Ints seem to be matching as strings

### ISSUE THREAD

**Issue by mrpmorris** [mbdavid/LiteDB#530]
My class has the following property

            public int[] Identity { get; set; }

When I do the following
```
            IEnumerable<Pete> instances =
              collection.Find(x => x.Identity[0] == 1 && x.Identity[1] == 1);
```
It returns results where Identity[0] == 101 or 201 or 301 etc.

**Comment by mbdavid** [comment]
Hi @mrpmorris, index in arrays are not based on positions. When you create an index in an array, you can only search a value in a group of values, like:

`col.Find("Identity", 1)` will returns all documents where Identity contains an `1` element in any position.

If you need search in fixed positions, you can:

1) Find documents where has `1` in any position and than, using Linq to object, filter again, like `collection.Find("Identity", 1).Where(x => x.Identity[0] && x.Identity[1])`

2) Create virtual fields indexed, like

```
BsonMapper.Global.Entity<MyClass>()
    .Index("FirstIdentity", x => x.Identity[0])
    .Index("SecondIdentity", x=> x.Identity[1]);

collection.Find(x => x.FirstIdentity == 1 && x.SecondIdentity == 1);
```

**Comment by mrpmorris** [comment]
Is there another way of achieving this? My identities are arrays of integers, so when I search for 1 in index[0] (the most significant bits) I am going to get a massive number of 1's from the next 3 lower significant bits.

**Comment by mbdavid** [comment]
Indexes keys in array do not store positions. So if you want search using a fixed position in your array you must create an exclusive index per position (like "Identity_0", "Identity_3", ....)

**Comment by mrpmorris** [comment]
But why is it matching like string.Contains instead of a Int.Equals?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
