### ISSUE TITLE
OutOfMemoryException when using Shrink

### ISSUE THREAD

**Issue by mkosieradzki** [mbdavid/LiteDB#531]
When shrinking ~300MB database, memory usage jumps to 1GB and throws OutOfMemoryException.

**Comment by mbdavid** [comment]
Are you using 3.1 version?

**Comment by mkosieradzki** [comment]
@mbdavid Yes. I have tested on both 3.0 and 3.1 and outcome is exactly the same.

**Comment by mbdavid** [comment]
Hi @mkosieradzki, I added split insert in 5000 documents batch. This could be avoid too memory consume.

**Comment by mkosieradzki** [comment]
Hi @mbdavid , thanks I have also found that shrink by default uses StreamDiskService with MemoryStream. My suggestion would be to avoid using MemoryStream whenever possible as it introduces awful LOH fragmentation.

I can share a nice replacement for Memory Stream which uses list of arrays of bytes (possibly under the LOH size) instead underneath instead of huge, very often reallocated array.

I would also like to use FileDiskService as temp storage, but it causes an issue for which I have created a PR: #556.

I understand that the default shrink is not really safe and can lead to a database corruption (in case of power down), so it would be better to use FileDiskService instead which will leave a copy of shrunk database and allow recovery.

**Comment by mbdavid** [comment]
Hi @mkosieradzki, I used MemoryStream as default just to simplify. But the correct implementation must be same as principal database. But, to do this, I needed add more methods in IDiskService create temp disk (if you check LiteDB v2 I used that, be remove in v3).

**Comment by mkosieradzki** [comment]
@mbdavid Fair enough ;), thanks for the explanation. 

Any chances for the 3.1.1 anytime soon with the Shrink bug fixes?
