### ISSUE TITLE
Question: What's the best way to read large JSON files directly into LiteDB

### ISSUE THREAD

**Issue by godlikemouse** [mbdavid/LiteDB#532]
Here's my scenario, I need to insert around 6 million records from a flat json file into LiteDB.  First off, fantastic work on this project, very impressive.  Next, I can read directly from disc, convert into a BsonDocument and insert the records at 1000 entries per BsonDocument array.  This get's exponentially slower with each consecutive insert.  Is there a faster more optimized way to do this?  I'm able to do the same thing in MongoDB using mongoimport and the throughput appears to be substantially higher.  Any assistance here would be greatly appreciated, thanks.

**Comment by mbdavid** [comment]
Hi @godlikemouse, thanks! Import/Export features will be avaiable in next 3.2 version.

For now, try:

- Read JSON file as an array (file must be a json array). JsonSerializer support read array on deman (returning an `IEnumerable<BsonValue>`): https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Document/Json/JsonSerializer.cs#L108
- Buffer documents in batch (like 5000 documents) and then run 1 insert command without transaction (transaction will me auto-created to this 5000 documents). If is a single operation, you can also disable journal to be faster.

**Comment by godlikemouse** [comment]
Hi @mbdavid,

Thank you for the prompt response.  

I've already disabled journal.  

`LiteDatabase db = new LiteDatabase("Filename=test.db; Journal=false"`

I'll work on trying to read the values from the JSON file into an IEnumerable<BsonValue> instead of an IEnumerable<BsonDocument> and see if that speeds things up.  I can change the batch to 5000 easy enough.

**Comment by mbdavid** [comment]
Inside LiteDB there is an Batch `IEnumerable` method extensions you can use (actually, copy because is internal): https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Utils/Extensions/LinqExtensions.cs

```C#
using(var engine = new LiteEngine("...;journal=false"))

var reader = new TextReader(...);

foreach(var docs in JsonSerializer.DeserializeArray(reader).Batch(5000));
{
    engine.Insert("mycol", docs)
}
```

**Comment by godlikemouse** [comment]
Oh, very nice, let me give that a try.  Thank you.

**Comment by xied75** [comment]
Suggest adding this into Wiki/documents

**Comment by godlikemouse** [comment]
Hi @mbdavid,

I've been working to speed up the inserts based on the information you've given me using a smaller control set.  One thing I've noticed is that when I bulk insert the entries in groups of 5000, everything inserts well until around the 25000 entry range.  From that point forward the performance degradation is exponential.  Doing further experiments, I found that if I create a new collection every 25000 entries, performance remains relatively constant getting all 64495 entries in rather quickly.  However, when batching at intervals of 5000 to the same collection, these are the numbers I'm seeing:

Inserted 5000 records : 5000 total, elapsed time: 00:00:00.8136724, total elapsed time 00:00:02.1729355.
Inserted 5000 records : 10000 total, elapsed time: 00:00:01.1526203, total elapsed time 00:00:04.2712472.
Inserted 5000 records : 15000 total, elapsed time: 00:00:01.0188746, total elapsed time 00:00:06.5339195.
Inserted 5000 records : 20000 total, elapsed time: 00:00:01.3106744, total elapsed time 00:00:08.8663560.
Inserted 5000 records : 25000 total, elapsed time: 00:00:01.2519512, total elapsed time 00:00:11.1984341.
Inserted 5000 records : 30000 total, elapsed time: 00:00:01.5048521, total elapsed time 00:00:13.4588529.
Inserted 5000 records : 35000 total, elapsed time: 00:00:01.9553882, total elapsed time 00:00:16.6838628.
Inserted 5000 records : 40000 total, elapsed time: 00:00:04.7825360, total elapsed time 00:00:22.4643627.
Inserted 5000 records : 45000 total, elapsed time: 00:00:57.4881217, total elapsed time 00:01:21.0844113.
Inserted 5000 records : 50000 total, elapsed time: 00:00:35.9499825, total elapsed time 00:01:58.0451584.
Inserted 5000 records : 55000 total, elapsed time: 00:01:32.6292249, total elapsed time 00:03:31.9206959.
Inserted 5000 records : 60000 total, elapsed time: 00:01:21.0505327, total elapsed time 00:04:53.9208617.
Inserted 5000 records : 64495 total, elapsed time: 00:01:53.8559244, total elapsed time 00:06:48.5311372.
64495 total records inserted, 00:06:50.5602728 total time.

Also for reference, here is the code I'm executing

```
            Stopwatch csw = new Stopwatch();
            Stopwatch sw = new Stopwatch();

            csw.Start();

            using (JsonStream stream = new JsonStream(File.OpenRead(path)))
            {
                using (LiteDatabase db = new LiteDatabase("filename=test.db; journal=false"))
                {
                    string importName = string.Format("{0}-import", collectionName);
                    db.DropCollection(importName);
                    LiteCollection<BsonDocument> collection = db.GetCollection(importName);

                    //collection.EnsureIndex("id", true);
                    //collection.EnsureIndex("name");

                    //List<BsonDocument> docs = new List<BsonDocument>();
                    List<BsonValue> docs = new List<BsonValue>();
                    string json = null;
                    while ((json = stream.ReadLine()) != null)
                    {
                        
                        try
                        {

                            //docs.Add(JsonSerializer.Deserialize(json).AsDocument);
                            docs.Add(JsonSerializer.Deserialize(json));

                            if (++count > 0 && count % BULK_LIMIT == 0)
                            {

                                sw.Start();
                                collection.Insert(docs.Select(x => x.AsDocument));
                                sw.Stop();
                                Debug.WriteLine("Inserted {0} records : {1} total, elapsed time: {2}, total elapsed time {3}.", BULK_LIMIT, count, sw.Elapsed, csw.Elapsed);
                                sw.Reset();
                                docs.Clear();
                            }
                        }
                        catch(Exception ex)
                        {
                            Console.Error.WriteLine(ex.Message);
                        }
                    }

                    if (docs.Count > 0)
                    {
                        sw.Start();
                        collection.Insert(docs.Select(x => x.AsDocument));
                        sw.Stop();
                        Debug.WriteLine("Inserted {0} records : {1} total, elapsed time: {2}, total elapsed time {3}.", BULK_LIMIT, count, sw.Elapsed, csw.Elapsed);
                    }

                    /*
                    using(var sr = new StreamReader(filename))
                    {
                        var docs = JsonSerializer.DeserializeArray(sr);
                        
                        collection.Insert(docs.Select(x => x.AsDocument));
                    }
                    */

                    db.DropCollection(collectionName);
                    db.RenameCollection(importName, collectionName);
                }
            }
```

I tried to follow as closely as I could with the examples you've provided in combination with the source code of the LiteShell bulk import.  Could you please tell me if there's an issue with the way I'm doing things or if there's an optimization approach you could suggest?  The only real difference I see here is that instead of using the Batch() method, I'm queuing up the BsonValue elements in my own list.  Thanks in advance for your help.

**Comment by godlikemouse** [comment]
As a follow up, when I execute the following:

```
                    List<BsonDocument> docs = new List<BsonDocument>();
                    string json = null;
                    sw.Start();
                    
                    while((json = stream.ReadLine()) != null)
                    {
                        docs.Add(JsonSerializer.Deserialize(json).AsDocument);
                        count++;
                    }
                    sw.Stop();
                    Debug.WriteLine("Inserted {0} records into list, elapsed time: {1}, total elapsed time {2}.", count, sw.Elapsed, csw.Elapsed);

                    count = docs.Count();
                    collection.Insert(docs.Select(x => x.AsDocument));

                    csw.Stop();
```

The result is the following:

Inserted 64495 records into list, elapsed time: 00:00:10.8103604, total elapsed time 00:00:10.8637538.
64495 total records inserted, 00:00:34.6382347 total time.

Next, when I implement this:

```
                    using(var sr = new StreamReader(filename))
                    {
                        sw.Start();
                        var docs = JsonSerializer.DeserializeArray(sr);
                        count = docs.Count();
                        sw.Stop();
                        Debug.WriteLine("Inserted {0} records into list, elapsed time: {1}, total elapsed time {2}.", count, sw.Elapsed, csw.Elapsed);

                        collection.Insert(docs.Select(x => x.AsDocument));
                    }
```

The result is the following:

Inserted 64495 records into list, elapsed time: 00:00:05.0990274, total elapsed time 00:00:06.6898283.
64495 total records inserted, 00:00:06.7126147 total time.

It would appear that there's an optimization here that I am missing.  Any ideas what I can do to speed this up?  Also it's worth mentioning, that I can't actually use the` JsonSerializer.DeserializeArray()` in my final project because the actual JSON I will be parsing contains long values which need to be parsed and replaced with `{"$numberLong": ""}` values.  Thanks.

**Comment by mbdavid** [comment]
If you are insert "only" 64k documents you can insert as a single insert an not break into chunks. Thats problably why when you run in a single insert runs in 6s.

You code seams ok, you loose some time to double-deserialize but this is not too long to be huge difference after some inserts. Can you show 1 document to know document size/schema to reproduce. Until this, try close/open datafile in each batch insert (could be page cache memory consume).

**Comment by godlikemouse** [comment]
Certainly I'll post one of the documents as an example.  In the meantime, I pre-parsed the largest of the files to replace the long values with the $numberLong equivalents, then ran the code you originally shared:

```
using(TextReader reader = File.OpenText(path))
                    {

                        foreach (var d in JsonSerializer.DeserializeArray(reader).Batch(BULK_LIMIT))
                        {
                            sw.Start();
                            collection.Insert(d.Select(x => x.AsDocument));
                            count += d.Count();
                            sw.Stop();
                            Debug.WriteLine("Inserted {0} records into list, elapsed time: {1}, total elapsed time {2}.", count, sw.Elapsed, csw.Elapsed);
                        }

                    }
```

This approach however had the same issue, after about 35000 - 40000 records, the time began to grow exponentially:

Inserted 5000 records into list, elapsed time: 00:00:00.8403290, total elapsed time 00:00:01.5376710.
Inserted 10000 records into list, elapsed time: 00:00:01.7376893, total elapsed time 00:00:02.4404358.
Inserted 15000 records into list, elapsed time: 00:00:02.7716668, total elapsed time 00:00:03.4748621.
Inserted 20000 records into list, elapsed time: 00:00:03.9890341, total elapsed time 00:00:04.6926910.
Inserted 25000 records into list, elapsed time: 00:00:05.1933504, total elapsed time 00:00:05.8974158.
Inserted 30000 records into list, elapsed time: 00:00:06.6847656, total elapsed time 00:00:07.3892500.
Inserted 35000 records into list, elapsed time: 00:00:10.7670988, total elapsed time 00:00:11.4720142.
Inserted 40000 records into list, elapsed time: 00:00:28.0815546, total elapsed time 00:00:28.7868870.
Inserted 45000 records into list, elapsed time: 00:01:00.8765264, total elapsed time 00:01:01.5823218.
Inserted 50000 records into list, elapsed time: 00:01:49.0085502, total elapsed time 00:01:49.7147589.
Inserted 55000 records into list, elapsed time: 00:02:31.0452093, total elapsed time 00:02:31.7519024.
Inserted 60000 records into list, elapsed time: 00:03:20.4981843, total elapsed time 00:03:21.2052793.
Inserted 65000 records into list, elapsed time: 00:04:26.4099773, total elapsed time 00:04:27.1175721.
Inserted 70000 records into list, elapsed time: 00:05:27.9312605, total elapsed time 00:05:28.6392825.
Inserted 75000 records into list, elapsed time: 00:06:46.3439561, total elapsed time 00:06:47.0524274.
Inserted 80000 records into list, elapsed time: 00:08:14.2444098, total elapsed time 00:08:14.9533567.
Inserted 85000 records into list, elapsed time: 00:09:48.3997141, total elapsed time 00:09:49.1091194.
Inserted 90000 records into list, elapsed time: 00:11:29.8573649, total elapsed time 00:11:30.5671798.
Inserted 95000 records into list, elapsed time: 00:13:09.8709034, total elapsed time 00:13:10.5811210.
Inserted 100000 records into list, elapsed time: 00:15:16.4506298, total elapsed time 00:15:17.1613391.
Inserted 105000 records into list, elapsed time: 00:17:09.4155188, total elapsed time 00:17:10.1266124.
Inserted 110000 records into list, elapsed time: 00:19:27.7560402, total elapsed time 00:19:28.4675951.
Inserted 115000 records into list, elapsed time: 00:21:43.1077075, total elapsed time 00:21:43.8197227.
Inserted 120000 records into list, elapsed time: 00:23:54.8152649, total elapsed time 00:23:55.5276633.
Inserted 125000 records into list, elapsed time: 00:26:00.9206303, total elapsed time 00:26:01.6334805.
Inserted 130000 records into list, elapsed time: 00:27:59.3610854, total elapsed time 00:28:00.0743443.
Inserted 135000 records into list, elapsed time: 00:30:19.1292082, total elapsed time 00:30:19.8428843.
Inserted 140000 records into list, elapsed time: 00:32:50.3883024, total elapsed time 00:32:51.1023912.
Inserted 145000 records into list, elapsed time: 00:35:19.1582880, total elapsed time 00:35:19.8727696.
Inserted 150000 records into list, elapsed time: 00:38:06.5936198, total elapsed time 00:38:07.3084925.
Inserted 155000 records into list, elapsed time: 00:40:59.8120636, total elapsed time 00:41:00.5273436.
Inserted 160000 records into list, elapsed time: 00:43:26.8877093, total elapsed time 00:43:27.6034234.
Inserted 165000 records into list, elapsed time: 00:46:13.7403832, total elapsed time 00:46:14.4565184.
Inserted 170000 records into list, elapsed time: 00:49:17.1470592, total elapsed time 00:49:17.8636632.
Inserted 175000 records into list, elapsed time: 00:52:25.2611825, total elapsed time 00:52:25.9782587.
Inserted 180000 records into list, elapsed time: 00:55:14.3619783, total elapsed time 00:55:15.0794720.
Inserted 185000 records into list, elapsed time: 00:58:02.8347567, total elapsed time 00:58:03.5526672.
Inserted 190000 records into list, elapsed time: 01:01:04.9061189, total elapsed time 01:01:05.6244007.
Inserted 195000 records into list, elapsed time: 01:03:54.9140452, total elapsed time 01:03:55.6327840.
Inserted 200000 records into list, elapsed time: 01:06:52.2178177, total elapsed time 01:06:52.9369828.
Inserted 205000 records into list, elapsed time: 01:10:01.5741111, total elapsed time 01:10:02.2937813.
Inserted 210000 records into list, elapsed time: 01:13:31.9921117, total elapsed time 01:13:32.7121679.
Inserted 215000 records into list, elapsed time: 01:17:10.1325128, total elapsed time 01:17:10.8530487.
Inserted 220000 records into list, elapsed time: 01:20:44.3941916, total elapsed time 01:20:45.1151520.
Inserted 225000 records into list, elapsed time: 01:24:37.3879278, total elapsed time 01:24:38.1093512.
Inserted 230000 records into list, elapsed time: 01:28:06.1678372, total elapsed time 01:28:06.8897135.
Inserted 235000 records into list, elapsed time: 01:31:55.0756463, total elapsed time 01:31:55.7980041.
Inserted 240000 records into list, elapsed time: 01:35:32.8303907, total elapsed time 01:35:33.5531674.
Inserted 245000 records into list, elapsed time: 01:38:15.4338688, total elapsed time 01:38:16.1570603.
Inserted 250000 records into list, elapsed time: 01:41:03.9358269, total elapsed time 01:41:04.6594130.
Inserted 255000 records into list, elapsed time: 01:44:03.7310638, total elapsed time 01:44:04.4550818.
Inserted 260000 records into list, elapsed time: 01:47:27.4805956, total elapsed time 01:47:28.2050487.
Inserted 265000 records into list, elapsed time: 01:51:00.3374803, total elapsed time 01:51:01.0624061.
Inserted 270000 records into list, elapsed time: 01:54:06.2178364, total elapsed time 01:54:06.9431830.

I'm not sure how feasible this would be, but perhaps one possible optimization for bulk inserting documents would be to determine if the record count is greater than 40,000 and if it is, implement a system of sharding the data into separate temporary collections which could then be merged back into the intended target collection behind the scenes.  Something along the lines of:

```
//pseudo code
collection; //mycol
temporaryCollection ; //mycol_
temporaryCollection.Insert(docs); //up to 40,000 documents at 5,000 per insert
collection.Merge(temporaryCollection); //merge shard into target collection
db.Drop(temporaryCollection); //drop and continue for the next 40,000 documents
```

Just an idea :)

**Comment by godlikemouse** [comment]
Here is an exert from one of the smaller JSON files:

```
{  
    "id":5,
    "name":"Reilly Hub",
    "system_id":396,
    "updated_at":1488926146,
    "max_landing_pad_size":"L",
    "distance_to_star":171,
    "government_id":64,
    "government":"Corporate",
    "allegiance_id":3,
    "allegiance":"Federation",
    "state_id":80,
    "state":"None",
    "type_id":8,
    "type":"Orbis Starport",
    "has_blackmarket":false,
    "has_market":true,
    "has_refuel":true,
    "has_repair":true,
    "has_rearm":true,
    "has_outfitting":true,
    "has_shipyard":true,
    "has_docking":true,
    "has_commodities":true,
    "import_commodities":[  
        "Pesticides",
        "Aquaponic Systems",
        "Biowaste"
    ],
    "export_commodities":[  
        "Mineral Oil",
        "Fruit and Vegetables",
        "Grain"
    ],
    "prohibited_commodities":[  
        "Narcotics",
        "Tobacco",
        "Combat Stabilisers",
        "Imperial Slaves",
        "Slaves",
        "Personal Weapons",
        "Battle Weapons",
        "Toxic Waste",
        "Wuthielo Ku Froth",
        "Bootleg Liquor",
        "Landmines"
    ],
    "economies":[  
        "Agriculture"
    ],
    "shipyard_updated_at":1489126071,
    "outfitting_updated_at":1489126066,
    "market_updated_at":1489126065,
    "is_planetary":false,
    "selling_ships":[  
        "Adder",
        "Eagle Mk. II",
        "Hauler",
        "Sidewinder Mk. I",
        "Viper Mk III"
    ],
    "selling_modules":[  
        738,
        739,
        740,
        743,
        744,
        745,
        748,
        749,
        750,
        753,
        754,
        755,
        756,
        757,
        758,
        759,
        760,
        761,
        762,
        828,
        829,
        831,
        837,
        838,
        839,
        843,
        851,
        876,
        877,
        878,
        879,
        880,
        881,
        882,
        883,
        885,
        886,
        887,
        891,
        892,
        893,
        894,
        895,
        896,
        897,
        898,
        899,
        929,
        930,
        933,
        935,
        937,
        938,
        941,
        942,
        943,
        946,
        947,
        948,
        961,
        962,
        963,
        965,
        966,
        967,
        968,
        969,
        970,
        1000,
        1005,
        1009,
        1010,
        1011,
        1012,
        1013,
        1016,
        1017,
        1018,
        1021,
        1022,
        1023,
        1027,
        1032,
        1036,
        1037,
        1038,
        1041,
        1042,
        1043,
        1046,
        1047,
        1048,
        1066,
        1067,
        1071,
        1116,
        1119,
        1120,
        1123,
        1124,
        1125,
        1128,
        1132,
        1137,
        1138,
        1182,
        1186,
        1187,
        1191,
        1192,
        1193,
        1194,
        1195,
        1196,
        1199,
        1200,
        1201,
        1202,
        1203,
        1204,
        1207,
        1208,
        1209,
        1212,
        1213,
        1214,
        1228,
        1230,
        1231,
        1232,
        1233,
        1237,
        1239,
        1241,
        1242,
        1243,
        1245,
        1246,
        1286,
        1306,
        1307,
        1309,
        1310,
        1311,
        1312,
        1313,
        1317,
        1320,
        1326,
        1327,
        1373,
        1375,
        1377,
        1379,
        1381,
        1421,
        1425,
        1429,
        1523,
        1524,
        1525,
        1526,
        1528,
        1530,
        1531,
        1532,
        1533,
        1534,
        1535,
        1544,
        1545,
        1577,
        1579,
        1581,
        1583,
        1585
    ],
    "settlement_size_id":null,
    "settlement_size":null,
    "settlement_security_id":null,
    "settlement_security":null,
    "body_id":null,
    "controlling_minor_faction_id":13925
}
```

**Comment by godlikemouse** [comment]
Thanks again for you help on this.  Please let me know if there's anything I can do to assist.

**Comment by godlikemouse** [comment]
One last thing I'm not quite sure of.  When you said "try close/open datafile in each batch insert (could be page cache memory consume)." Are you referring to opening and closing the LiteDB data file, or the reader of the JSON file?  Thanks.

**Comment by godlikemouse** [comment]
Also just a heads up on the machine I'm testing with.  I'm using a 12 core 4.2 GHz machine with 128GB RAM and 1TB M.2 PCI-E drive.  So machine bottlenecks shouldn't be an issue here.

**Comment by xied75** [comment]
Looks like you got a database for the pan-galaxy?

**Comment by mbdavid** [comment]
@godlikemouse, try this:

```
using (JsonStream stream = new JsonStream(File.OpenRead(path)))
{
    string importName = string.Format("{0}-import", collectionName);
    
    using (var db = new LiteEngine("filename=test.db; journal=false"))
    {
        db.DropCollection(importName, docs.Select(x => x.AsDocument));
    }
    

    List<BsonValue> docs = new List<BsonValue>();
    string json = null;
    while ((json = stream.ReadLine()) != null)
    {
        
        try
        {

            docs.Add(JsonSerializer.Deserialize(json));

            if (++count > 0 && count % BULK_LIMIT == 0)
            {

                sw.Start();
                
                using (var db = new LiteEngine("filename=test.db; journal=false"))
                {
                    db.Insert(importName, docs.Select(x => x.AsDocument));
                }
                
                sw.Stop();
                Debug.WriteLine("Inserted {0} records : {1} total, elapsed time: {2}, total elapsed time {3}.", BULK_LIMIT, count, sw.Elapsed, csw.Elapsed);
                sw.Reset();
                docs.Clear();
            }
        }
        catch(Exception ex)
        {
            Console.Error.WriteLine(ex.Message);
        }
    }

    if (docs.Count > 0)
    {
        sw.Start();
        using (var db = new LiteEngine("filename=test.db; journal=false"))
        {
            db.Insert(importName, docs.Select(x => x.AsDocument));
        }
        sw.Stop();
        Debug.WriteLine("Inserted {0} records : {1} total, elapsed time: {2}, total elapsed time {3}.", BULK_LIMIT, count, sw.Elapsed, csw.Elapsed);
    }
}
```

**Comment by godlikemouse** [comment]
@xied75 It's actually from the Elite Dangerous game.

@mbdavid I've implemented the above code but changed:

`db.DropCollection(importName, docs.Select(x => x.AsDocument));`

to

`db.DropCollection(importName);`

No change result wise.  There is a dramatic increase in insert time starting around 40K records.

```
Inserted 5000 records : 5000 total, elapsed time: 00:00:00.7832291, total elapsed time 00:00:01.7742849.
Inserted 5000 records : 10000 total, elapsed time: 00:00:01.1015218, total elapsed time 00:00:03.6003434.
Inserted 5000 records : 15000 total, elapsed time: 00:00:01.0323648, total elapsed time 00:00:05.6693271.
Inserted 5000 records : 20000 total, elapsed time: 00:00:01.3664129, total elapsed time 00:00:07.8111386.
Inserted 5000 records : 25000 total, elapsed time: 00:00:01.1922187, total elapsed time 00:00:09.8823094.
Inserted 5000 records : 30000 total, elapsed time: 00:00:01.3958514, total elapsed time 00:00:11.9560483.
Inserted 5000 records : 35000 total, elapsed time: 00:00:01.8160972, total elapsed time 00:00:14.7466903.
Inserted 5000 records : 40000 total, elapsed time: 00:00:04.4946808, total elapsed time 00:00:20.0723357.
Inserted 5000 records : 45000 total, elapsed time: 00:00:46.3005596, total elapsed time 00:01:07.3992580.
Inserted 5000 records : 50000 total, elapsed time: 00:00:29.9726260, total elapsed time 00:01:38.1727240.
Inserted 5000 records : 55000 total, elapsed time: 00:01:13.8675638, total elapsed time 00:02:53.0437222.
Inserted 5000 records : 60000 total, elapsed time: 00:01:04.2471502, total elapsed time 00:03:58.1291849.
Inserted 5000 records : 64495 total, elapsed time: 00:01:37.6663914, total elapsed time 00:05:36.3745306.
```

If I had to guess, I would say that the seek to end paging during insert may need a bit of optimization for bulk inserts.  I think what we're seeing is after a bulk insert of 5000 records, the wait time is the time finding the next open page after the previous last record.  Perhaps keeping the pointer to the last insert area during a bulk operation or sharding would help speed up the inserts.  Please let me know if there is anything else I provide or help with. Thanks.

**Comment by mbdavid** [comment]
Hi @godlikemouse, i will investigate during this weekend, but thats not reason for that. LiteDB uses skip list with 32-level. Skip lists works with O^n, so to insert 64kb it´s not more than 16 step (pages) to get index position and it´s depend if datafile is open or need open again. Problem must about caching pages or something like that. I will keep you informed

**Comment by godlikemouse** [comment]
Hi @mbdavid , thanks for the update and the assistance.  Before I saw this message I downloaded the source code and began setting stopwatches in and around insert methods.  I've traced the issue down to the PageServce.AddToFreeList method so far.  I'm not sure specifically where the bottleneck is but I thought I'd let you know what I've found so far (you probably already knew this though) :)

**Comment by godlikemouse** [comment]
Hi @mbdavid , I think you're right.  I'm seeing now that the GetPage<BasePage>(nextPageID) appears to be growing in retrieval time as the inserts occur.

first 5000: 00:00:00.0000232 max
next 5000: 00:00:00.0001086 max
next 5000: 00:00:00.0080962 max
...
last 5000: 00:00:00.1492187 max

The above is simply tracking the maximum amount of time the GetPage() call takes per bulk insert.

**Comment by mbdavid** [comment]
humm, this is new to me. Maybe problem are in AddToFreeList method. But what is more strange that if you open/close datafile there is no problem on this. Just to know, AddToFreeList (that uses GetPage) like avaiable pages in a continuous list. And I know a possible bug in my implementation (that came from first version). If your used page remains bytes enouth for more data, you your next data is always bigger than this size, you will always get bigger this list (and this list is O(n) complexity). If it's the case will be a great case to try fixed this :)

**Comment by godlikemouse** [comment]
Great!  Please let me know if I can be of any assistance in providing a data set or testing for you.  Thanks again.

**Comment by mbdavid** [comment]
oh my... i got it!!! :) I changed this to test if was possible reduce datafile size and forgot to have after!

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Engine/Pages/DataPage.cs#L20

I will revert this and try

**Comment by godlikemouse** [comment]
Awesome 👍 I can't wait to check it out.  Thanks.

**Comment by godlikemouse** [comment]
That looks like that may have been it, tested using the stations.json, got the following:

```
Inserted 5000 records : 5000 total, elapsed time: 00:00:01.1685254, total elapsed time 00:00:03.9108816.
Inserted 5000 records : 10000 total, elapsed time: 00:00:00.8184333, total elapsed time 00:00:05.9691680.
Inserted 5000 records : 15000 total, elapsed time: 00:00:01.2047131, total elapsed time 00:00:08.7821987.
Inserted 5000 records : 20000 total, elapsed time: 00:00:00.9522625, total elapsed time 00:00:10.9204821.
Inserted 5000 records : 25000 total, elapsed time: 00:00:00.9803163, total elapsed time 00:00:13.3693458.
Inserted 5000 records : 30000 total, elapsed time: 00:00:00.8960723, total elapsed time 00:00:15.3639652.
Inserted 5000 records : 35000 total, elapsed time: 00:00:01.1181613, total elapsed time 00:00:18.2523672.
Inserted 5000 records : 40000 total, elapsed time: 00:00:00.9317909, total elapsed time 00:00:20.5701199.
Inserted 5000 records : 45000 total, elapsed time: 00:00:01.1261127, total elapsed time 00:00:23.2997889.
Inserted 5000 records : 50000 total, elapsed time: 00:00:00.9147380, total elapsed time 00:00:25.5833090.
Inserted 5000 records : 55000 total, elapsed time: 00:00:01.2603071, total elapsed time 00:00:28.4274433.
Inserted 5000 records : 60000 total, elapsed time: 00:00:01.3036738, total elapsed time 00:00:31.0259107.
Inserted 5000 records : 64495 total, elapsed time: 00:00:01.1868521, total elapsed time 00:00:33.3413561.
```

Next I'll test using the large data set.  Thanks again for the work so far.

**Comment by godlikemouse** [comment]
Great work @mbdavid , this fixed the issue here.  Please feel free to close this.

**Comment by mbdavid** [comment]
Hi @godlikemouse, added `InsertBulk` using same idea here

**Comment by vijaykirann** [comment]
Im Trying to read a json file and inserting into lite DB
            openLoadDef.FileName = "";
            openLoadDef.ShowDialog();
            string errordef = openLoadDef.FileName;
            using (var sr = new StreamReader(errordef))
            {
            var docs = JsonSerializer.DeserializeArray(sr);
            }
=======================
Json file content: { "name":"John", "age":31, "city":"New York" }
=======================

I'm getting the following error 

Unexpected JSON token: name
Stack Trace:    at LiteDB.JsonToken.Expect(JsonTokenType type)
   at LiteDB.JsonReader.<DeserializeArray>d__5.MoveNext()
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()

I Tried to debug the issue .. but unable to do so.. kindly help.

**Comment by xied75** [comment]
@vijaykirann People normally is not very fast on responding to a closed issue. Also your issue might not share anything with this closed one, so better create a new issue. And your code fragment is too short to figure out what's going on.

**Comment by vijaykirann** [comment]
thanks @xied75 .. I have opened a new issue.however I was trying read a jsonfile and inserting into litedb.. however the above mentioned code snippets arent working for me ..
