### ISSUE TITLE
OutOfMemoryException when Inserting

### ISSUE THREAD

**Issue by Warmcher** [mbdavid/LiteDB#533]
Hello. Found very weird thing. 1 Insert makes me lose 3gb ram and throws exception about it. 
I have already inserted 400k documents:

`
public class EndpointMatch
    {
        public int Id { get; set; }
        public string Endpoint { get; set; }
        public DateTime Timestamp { get; set; }
        public int FragLimit { get; set; }
        public int TimeLimit { get; set; }
        public double TimeElapsed { get; set; }
        public List<Scoreboard> Scoreboard { get; set; }
    }

    public class Scoreboard
    {
        public string Name { get; set; }
        public int Frags { get; set; }
        public int Kills { get; set; }
        public int Deaths { get; set; }
    }
`
All of them are equal except string Endpoint(and ID ofc). And now if i try to insert something different(even setting Scoreboard to null) causes Insert to throw OutOfMemory. 
I fixed it by switching to 3.0 from 3.1.

**Comment by mbdavid** [comment]
Hi @Warmcher, It´s not first issue about super memory consume in v3.1 (and 3.0, i guess). I think all #531 and #532 are all related.

I will investigate this during this weekend. Thanks

**Comment by mbdavid** [comment]
Hi @Warmcher, are you insert all 400k in a single insert? Normal insert will not support this because use single transaction and a transaction always are proceess in momory first.

I'm adding `InsertBulk` option to this. Let me know if working (I made 500k insert with no problem)

**Comment by Warmcher** [comment]
I get exception when inserting only 1 row! but after i inserted 4 loops of 100k. 400k of the exact same data except 1 field. Inserting something with different values resulting OutOfMemory. Ill reproduce code later, don`t have time for it now(

**Comment by Warmcher** [comment]
[Program.zip](https://github.com/mbdavid/LiteDB/files/853270/Program.zip)
Here is how i get Exception.
It will create 1.6gb file and will eat like 3gb memory.
After first run u can comment 400k insetion to better see how 1 insert takes 3gb memory.

**Comment by mbdavid** [comment]
Hi @Warmcher, I try run your test but in a single transaction insert 400k document doesnt work (always throw out of memory). Than I run this:

```C#
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using LiteDB;
using System.Diagnostics;
using System;

namespace LiteDB.Tests
{
    public class EndpointMatch
    {
        public int Id { get; set; }
        public string Endpoint { get; set; }
        public DateTime Timestamp { get; set; }
        public int FragLimit { get; set; }
        public int TimeLimit { get; set; }
        public double TimeElapsed { get; set; }
        public List<Scoreboard> Scoreboard { get; set; }
    }

    public class Scoreboard
    {
        public string Name { get; set; }
        public int Frags { get; set; }
        public int Kills { get; set; }
        public int Deaths { get; set; }
    }

    [TestClass]
    public class BigDatabaseTest
    {
        [TestMethod]
        public void BigDatabase_Test()
        {
            using (var file = new TempFile())
            {
                using (var db = new LiteDatabase(file.Filename))
                {
                    var data = db.GetCollection<EndpointMatch>("Matches");

                    data.InsertBulk(GetDocs(1, 400000)); // insert 400k 

                    GC.Collect();
                }

                using (var db = new LiteDatabase(file.Filename))
                {
                    var data = db.GetCollection<EndpointMatch>("Matches");

                    var sw = Stopwatch.StartNew();

                    data.Insert(GetDocs(400001, 400001).First()); // insert only one

                    sw.Stop();

                    // works with no problem (memoryUsed: 1Mb)

                    var memoryUsed = GC.GetTotalMemory(false) / 1024 / 1024;
                    var timeSpend = sw.ElapsedMilliseconds;
                }
            }
        }

        private IEnumerable<EndpointMatch> GetDocs(int init, int end)
        {
            var insertionData = new EndpointMatch();

            insertionData.Scoreboard = new List<Scoreboard>();

            for (int i = 0; i < 50; i++)
            {
                insertionData.Scoreboard.Add(new Scoreboard());
            }

            for (int i = id; i <= end; i++)
            {
                insertionData.Id = i;
                yield return insertionData;
            }
        }
    }
}
```

**Comment by Warmcher** [comment]
![image](https://cloud.githubusercontent.com/assets/22963433/24131541/0c287bf2-0e11-11e7-86cd-63cf6a5d9c22.png)

**Comment by Warmcher** [comment]
You forgot about the thing i mentioned, u need to change something in insertion data after u did big SAME data insert.
Changed your code a little bit:
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using LiteDB;
using System.Diagnostics;
using System;

namespace LiteDB.Tests
{
    public class EndpointMatch
    {
        public int Id { get; set; }
        public string Endpoint { get; set; }
        public DateTime Timestamp { get; set; }
        public int FragLimit { get; set; }
        public int TimeLimit { get; set; }
        public double TimeElapsed { get; set; }
        public List<Scoreboard> Scoreboard { get; set; }
    }

    public class Scoreboard
    {
        public string Name { get; set; }
        public int Frags { get; set; }
        public int Kills { get; set; }
        public int Deaths { get; set; }
    }

    [TestClass]
    public class BigDatabaseTest
    {
        [TestMethod]
        public void BigDatabase_Test()
        {
            using (var file = new TempFile())
            {
                using (var db = new LiteDatabase(file.Filename))
                {
                    var data = db.GetCollection<EndpointMatch>("Matches");

                    data.InsertBulk(GetDocs(1, 400000, false)); // insert 400k 

                    GC.Collect();
                }

                using (var db = new LiteDatabase(file.Filename))
                {
                    var data = db.GetCollection<EndpointMatch>("Matches");

                    var sw = Stopwatch.StartNew();

                    data.Insert(GetDocs(400001, 400001, true).First()); // insert only one

                    sw.Stop();

                    // works with no problem (memoryUsed: 1Mb)

                    var memoryUsed = GC.GetTotalMemory(false) / 1024 / 1024;
                    var timeSpend = sw.ElapsedMilliseconds;
                }
            }
        }

        private IEnumerable<EndpointMatch> GetDocs(int init, int end, bool newData)
        {
            var insertionData = new EndpointMatch();

            insertionData.Scoreboard = new List<Scoreboard>();

            for (int i = 0; i < 50; i++)
            {
                insertionData.Scoreboard.Add(new Scoreboard());
            }

            //Thats what rly makes it bad. It works fine V3.0
            if (newData)
            {
                insertionData.TimeElapsed = 52;
                insertionData.Endpoint = "GoodByeMemory(";
            }
            for (int i = init; i <= end; i++)
            {
                insertionData.Id = i;
                yield return insertionData;
            }
        }
    }
}

**Comment by mbdavid** [comment]
Ok, now I got it. It's same problem founded here:

https://github.com/mbdavid/LiteDB/issues/532#issuecomment-287502909

I commit this change. Thanks!

**Comment by ednsinf** [comment]
Bug not resolved. When I use LiteDatabase in memory and use bulkinsert and insert in 1k to 1k rows (using transaction our not) and shows memory erros always. Please verify thanks.
at System.IO.MemoryStream.set_Capacity(Int32 value)
at System.IO.MemoryStream.EnsureCapacity(Int32 value)
at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
at LiteDB.Engine.ConcurrentStream.Write(Byte[] buffer, Int32 offset, Int32 count)
at LiteDB.Engine.DiskService.WriteLogDisk(IEnumerable`1 pages)
at LiteDB.Engine.TransactionService.PersistDirtyPages(Boolean commit)
at LiteDB.Engine.TransactionService.Commit()
at LiteDB.Engine.LiteEngine.CommitAndReleaseTransaction(TransactionService transaction)
at LiteDB.Engine.LiteEngine.Commit()
