### ISSUE TITLE
Something is broken from v3.0.1 and v3.1 with virtual method on inherited class

### ISSUE THREAD

**Issue by jbrabant** [mbdavid/LiteDB#535]
As soon as I upgrade to v3.1 I got an issue inside a class method inherited from its base Virtual method.

I don't know how to explain all this but the issue happens in the following order.
I create an entity E that has a list<A> and within each A I have a list<B> and each B has an entity C which inherits from a base class that has a virtual method called "ConnectionString".

When code is executed, I set up a connection like this with properties from base class:

`E.A.B.add(new C(){Provider="SQLServer",Username="AAA",...});`

I save the entire E in the E collection.  
When I access E just after
`return _collection.Find(x => x.Name == name).FirstOrDefault();`

code end up in here (I put a break in C at the switch) and Provider and all other base class properties are null

`public override string Connectionstring
		{
			get
			{
				string conString = string.Empty;
				switch (Provider.ToUpper())`

Using v3.0.1, same code works fine.  Provider has the "SQLServer" in it, etc...
I wonder what is causing this?
Thanks for your help.

**Comment by mbdavid** [comment]
Hi @jbrabant, v3.1 uses now Expressions for get/set values from classes (changed from Emit to Expression in net35 version, because in netstandard always used Expression). But this change pass in all my unit tests. Can you paste an snippet about your classes structures?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
