### ISSUE TITLE
Question: Inserting document with dozens of large images as Base64Encoded string...works

### ISSUE THREAD

**Issue by dfarrNTST** [mbdavid/LiteDB#536]
The documentation for LiteDB states that each document has a limit of 1MB and we ran some initial tests with Xamarin Forms with a need to store images locally.  We were going to try the FileStorage method but went ahead and tried saving them in an object with property of List<string>, each item in the list is a 2-5MB Base64Encoded image as a string.  We know that the document is much larger than 1MB with all the encoded images in there...is that 1MB limit a hard and set rule?  It seems to work fine for us exceeding the limit.  Just want to be sure we aren't trying to do something we shouldn't be doing.

Thanks

**Comment by mbdavid** [comment]
Hi @dfarrNTST, don't ask me why, but I dont know when I removed this limit in code. BsonDocument limit definition still here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Document/BsonDocument.cs#L10

But there is not more check. This check must back to code.

Well, LiteDB has a document limit to avoid too big documents and, for each big document, read/write operation must be always in memory. So, if you have 10mb in a single document, LiteDB must read always read this all 10Mb, in any minimal change must write all 10Mb, in a foreach is worst, becase each document will consume lots an lots of memory. MongoDB has this limit to and is 16mb.

**Comment by mbdavid** [comment]
OMG, I searching about this check and was removed from v0.9 to 1.0, almost 2 years ago. Now I didn't know if I add this validation again or not....

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
