### ISSUE TITLE
OutOfMemoryException When Dropping Collection

### ISSUE THREAD

**Issue by godlikemouse** [mbdavid/LiteDB#537]
Hi @mbdavid ,

When dropping a collection containing 3,213,230 records I'm receiving the following error:

An unhandled exception of type 'System.OutOfMemoryException' occurred in LiteDB.dll

The issue can be easily reproduced by inserting 3million records, the invoking the db.DropCollection() method.

**Comment by mbdavid** [comment]
Hi @godlikemouse, it's quite complex here. There are some operation that be done in a single transaction and could not be "splited", like bulk insert. There are drop collection and ensure index. This two commands always need change all pages in memory before stating write in disk. 

In v3-beta, when file are opened only in exclusive mode, I wrote in disk dirty pages during execution command and clean from memory. Thats works fine, but must has not nobdy trying to access this file (file are not consistent). 

So, to works with this big single operation, I will need change LiteDB and add this support again, but will only work when file open on Exclusive mode.

**Comment by godlikemouse** [comment]
I'm OK with exclusive mode.  For my purposes, as long as the drop and rename executes quickly then I'm fine with it.  Is there anyway to perhaps mark the current collection as not usable or to rename it behind the scenes, then open a thread that walks that collection without having everything in memory?  That might solve the problem.  Then the rename collection immediately following a drop collection could proceed without issue.

**Comment by godlikemouse** [comment]
The only other work around I can think of would be to write each collection to a separate database.  Then I would simply remove the target database and rename using file system commands.  That might work as well.

**Comment by mbdavid** [comment]
Rename run quickly because it's very simple. But drop is not too fast, becasue need read all pages and mark all as empty page and order all in free list. 
Your second thread will open datafile in exclusive mode and than drop collection. This file will be locked until proceess are running. Work with many files could be solve your problem

**Comment by godlikemouse** [comment]
Hi @mbdavid , thanks I'll try using multiple files then for now.

**Comment by xied75** [comment]
Would MemoryMappedFiles help anything here?

**Comment by Cylindric** [comment]
I'm having this problem too. So is the recommendation for now to put "big" data in a separate file if it ever needs truncating?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
