### ISSUE TITLE
CollectionExists returning wrong value

### ISSUE THREAD

**Issue by FetzenRndy** [mbdavid/LiteDB#538]
While building an app I found a strange result,

I have a database with 1 Collection named "Patrick"
![db](https://cloud.githubusercontent.com/assets/20997737/24074781/b5d8c962-0c0f-11e7-8dca-4ffda5b409cd.PNG)

when using the following code:
![vs](https://cloud.githubusercontent.com/assets/20997737/24074839/befd7438-0c10-11e7-957c-b4053d490b6e.PNG)

( client is just a LiteDatabase retrieved by a factory method of mine)

result1 should be false, but it is true, following the documentation this method's input is case sensitive even tho it is not.

Is the error on my side or is the API not pay attention to the Case sensitivity?

**Comment by mbdavid** [comment]
Hi @FetzenRndy, collection name are case insensitive, so "it's not a bug, it's a feature" 😄

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Database/LiteDatabase.cs#L180

**Comment by FetzenRndy** [comment]
Whoops I read that they are case sensitive, thanks for clarifying 🗡 This can cause Problem's in my Programm. I create a new Collection for every user and when I, for example, want them to log in and they enter their username with the wrong capitalization the check if the collection exists will pass but when I try to get the Collection it will fail. I guess I will have to write my own case sensitive helper method for this, Anyway thanks for helping. LiteDB is awesome

**Comment by mbdavid** [comment]
Thanks man. You can hash (using MD5/SHA1/...) your username and than test this hash result (will produce diferent hash for upper/lower case).
