### ISSUE TITLE
Question: Collection names.  Length and total?

### ISSUE THREAD

**Issue by dfarrNTST** [mbdavid/LiteDB#539]
Is the 3000 bytes limit of a Collection name the total byte limit for a single collection in a single database?  Or we only have 3000 bytes total for a combination of all the names of all collections in a single database?

This basically comes to about 30 characters in length for the name.  Can we expand this significantly?  We would like to use our class names as the collection names, and they can run up to 80-100 characters in length sometimes.

If the collection name is being used for storage with individual properties or something, is it possible to allow an "alias" collection name that we can put in a large string and allow us to get the collection by that alias?

Thanks

**Comment by mbdavid** [comment]
Hi @dfarrNTST,

3000 bytes for all collection names is limited becase all collections names (and link pointer, +6 bytes) must been stored in header page (each page has 4069 bytes). So it's not possible be larger than this.

About 30 chars per collection it's just an pattern represented here: `^[\w-]{1,30}$` (CollectionPage.cs)

In v3.1, it's possible now write your own ResolveCollectionName function based on your `<T>` type. Using this, now it's possible pass `null` in collection names (in LiteDatabse or LiteRepository) to use this convention. For this, try:

`BsonMapper.Global.ResolveCollectionName = (type) => .....`

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
