### ISSUE TITLE
Not able to Retrieve back the stored C# object stored as Stream in FileStorage

### ISSUE THREAD

**Issue by sherry-ummen** [mbdavid/LiteDB#54]
Hi,
I have a small example which fails
```C#
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using LiteDB;

namespace TestLiteDb {
    class Program {

        [Serializable]
        public class Employee {
            public int EmployeeID { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
            public List<string> Objects { get; set; }
        }
        static void Main(string[] args) {
            using (var db = new LiteDatabase(@"filename=E:\Work\LiteDb\MyData.db;journal=false")) {
                // Get a collection (or create, if not exits)
                var col = db.GetCollection<Employee>("customers");

                var emp = new Employee() {
                    EmployeeID = 1,
                    FirstName = "one",
                    LastName = "two",
                };
                var listofString = Enumerable.Range(1, 100000).Select(ind => "String" + ind).ToList();
                emp.Objects = listofString;

                var s = SerializeToStream(emp);

                db.FileStorage.Upload("something", s);
                var exist = db.FileStorage.Exists("something"); // Finds correctly
                LiteFileInfo file = db.FileStorage.FindById("something"); // This one fails
                MemoryStream stream = new MemoryStream();
                file.CopyTo(stream);
                var b = (Employee)DeserializeFromStream(stream);
            }
        }

        public static MemoryStream SerializeToStream(object o) {
            MemoryStream stream = new MemoryStream();
            IFormatter formatter = new BinaryFormatter();
            formatter.Serialize(stream, o);
            return stream;
        }

        public static object DeserializeFromStream(MemoryStream stream) {
            IFormatter formatter = new BinaryFormatter();
            stream.Seek(0, SeekOrigin.Begin);
            object o = formatter.Deserialize(stream);
            return o;
        }
    }
}

```
So basically the content Length is 0.

And I see there is no unit test testing this as well.

Thanks

**Comment by mykemaas** [comment]
I was curious, so I tried your sample.  It looks like the trouble is that the SerializeToStream method does serialize the object, but leaves the stream's position at the end of the serialized object.  You'll need to add this:

    stream.Seek(0, SeekOrigin.Begin);

So, ultimately, the method looks like this:

        public static MemoryStream SerializeToStream(object o) {
            MemoryStream stream = new MemoryStream();
            IFormatter formatter = new BinaryFormatter();
            formatter.Serialize(stream, o);
            stream.Seek(0, SeekOrigin.Begin);
            return stream;
        }

This will set the stream position at the beginning, so that when it is persisted in the database, it reads the whole stream.

Hope this helps.

**Comment by sherry-ummen** [comment]
Very interesting.

How did you find about it?

Sent from my Windows Phone
________________________________

**Comment by mykemaas** [comment]
I've made the same mistake :smile: 

It's not really an issue with LiteDB...  Any library that reads from a stream always reads from the current position.  This gives you the ability to set the stream to an appropriate position before passing it in.  I've been bitten by this one before in an unrelated case, but that experience let me recognize the issue right off.

**Comment by sherry-ummen** [comment]
Very nice. I will try this in few hours as its quite late here in Finland n I shoul get some sleep. Thanks

Sent from my Windows Phone
________________________________

**Comment by mbdavid** [comment]
Hi @sherry-ummen! @mykemaas is right, LiteDB use stream from current position. But, the best solution could be implement `Write` operation in `LiteFileStream`. It's not a simple think, so I just throw a not implement exception. This custom `Stream` was a contribution from other old project `FileDB` that I wrote 5 year ago.

**Comment by sherry-ummen** [comment]
Great thanks Myke and Mauricio
