### ISSUE TITLE
Unable to load LiteDB.dll using Powershell 5.1 on Windows 10

### ISSUE THREAD

**Issue by lboening** [mbdavid/LiteDB#540]
I cloned the repository. I opened the solution in Visual Studio 2017 Community. I built the solution. Using Powershell, one is able to load assemblies (most of the time).

When loading:

Set-Location -Path "C:\code\LiteDB-3.1.0\LiteDB-3.1.0\LiteDB\bin\Release\netstandard"
Try {get-childitem"*.dll" | foreach { Write-host $_.Name; $assembly = Add-type -path $_.FullName}} catch { $error[0].Exception.LoaderExceptions}

I get this error:

`Could not load file or assembly 'System.IO.FileSystem.Primitives, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 
The system cannot find the file specified.
Could not load file or assembly 'System.IO.FileSystem.Primitives, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 
The system cannot find the file specified.`

**Comment by lboening** [comment]
The following worked. I used Powershell 5.1 Package manager and found the compiled dll at Nuget.org.

`
find-package -name litedb | install-package -Credential (get-credential -Credential luke) -scope currentuser
Set-Location -Path 'C:\Users\Luke\AppData\Local\PackageManagement\NuGet\Packages\LiteDB.3.1.0\lib\net35'

Try {get-childitem"*.dll" | foreach { Write-host $_.Name; $assembly = Add-type -path $_.FullName}} catch { $error[0].Exception.LoaderExceptions}
`

**Comment by lboening** [comment]
If this helps, I am making a bit of progress. I am able to use the LITEDB.DLL in a Visual Studio 2017 community project. I can create a DLL that I can get Powershell to load as an assembly. 

Next, I will see if "unblocking" helps. Thought I did that, however.

**Comment by mbdavid** [comment]
Hi @lboening, sorry for not helping, I never used powershell and I dont know how works. But if it's works, let's share this in LiteDB wiki pages

**Comment by wgross** [comment]
@lboening @mbdavid 
I think the reason of this is the global declaration of dependencies in the project.json. net461 doesn't need them and more importantly doesn't provide these assemblies and therefore loading fails. 

I've change the project.json (see pull request) and its working now with powershell on my machine.

**Comment by lboening** [comment]
I was able to use the LiteDB.dll from https://github.com/mbdavid/LiteDB/releases. It loaded easily.

## Try assembly
try {
    $assembly = Add-type -Path 'C:\alldata\LiteDB.dll' -PassThru
}
catch [Exception] {
    $error[0].Exception.LoaderExceptions

}

## Reference
## https://4sysops.com/archives/powershell-classes-part-1-objects/

## Create class
Class Person {

    [string]$FirstName
    [string]$LastName
    [string]$Website
}

$myp = New-Object Person
$myp.firstName = "Luke"
$myp.lastName = "Boening"
$myp.website = "www.boening.us"



$mydb = [LiteDB.LiteDatabase]::new("c:\alldata\myfile.db")

$mycoll = $mydb.GetCollection("Person");

$bsondoc = [LiteDB.BsonDocument]::new();

$bsondoc["_id"] = [LiteDB.ObjectId]::NewObjectId();
$bsondoc["Name"] = "Luke"
$bsondoc.set("Address.Street","Av. Proto Salva 123")
$bsondoc["City"] = "Saint Paul"

$mycoll.Insert($bsondoc);

$ans = $mycoll.Find([LiteDB.Query]::EQ("Name","Luke"))

$ans | % {$_ -match "Address"} | Select-object -ExpandProperty Value | select-object -Property Value

**Comment by wgross** [comment]
@lboening 
Did you used the 3.1.0 release? I can't load it on my machine with Add-Type in PS 5.1. I'm seeing the same loader exception again as you described orginally. 

But one thing i've learned from reading the travis.yml: My proposed Pull request is incomplete :-). 
It is necessary to change the NetStandard and the dotnet.Csproj files instead. Project.json seems to be a relic from the past. :-)

I hope i have some time today in the afternoon to make a second guess.

**Comment by wgross** [comment]
@lboening 
My second try fails during the travis build:
A target framework .Net461 is not available on Linux or mac, which is no surprise :-). 
I'dont know how i could fix this (exclude net461 on linux etc.) therefore I will stop trying here. 

If you want to compile a dependency free .Net 461 version of LiteDb you may have a look at the changes of the csproj file in the commit of my forked repo: 

[https://github.com/wgross/LiteDB/commit/5027ad63e8388ed21b2562903a31ac01327490a4](https://github.com/wgross/LiteDB/commit/5027ad63e8388ed21b2562903a31ac01327490a4)

If you change this locally and run all the dotnet restore/build command as specified in .travis.yml you will generate a dependency free version of the LiteDb.Dll.

**Comment by lboening** [comment]
I think I should close this. The LiteDB project targets .net 4.0. Meanwhile, I am to grab the Litedb.dll, add it as an assembly, and work with it that way.
