### ISSUE TITLE
Feauture request  - orderby literepo

### ISSUE THREAD

**Issue by Jack85** [mbdavid/LiteDB#541]
Hi, 
on a collection was possibility to call OrderByDescending
and orderBy.
If I want to use literepository I dont have those equivalents there. would be cool to have kind of same functionality there.

**Comment by mbdavid** [comment]
Use OrderByDescending in a indexed field? Or for any field?

**Comment by rmszc81** [comment]
@Jack85 ,

you can implement your own OrderBy as I did through IQueryable and IOrderedQueryable on my repository class.

Take a look on this code:

	public List<TModel> List(Expression<Func<TModel, Boolean>> Where, Expression<Func<IQueryable<TModel>, IOrderedQueryable<TModel>>> Order)
	{
		try
		{
			IQueryable<TModel> Results = Context.GetCollection<TModel>(typeof(TModel).Name).Find(Where).AsQueryable<TModel>();
			return Order.Compile()(Results).ToList<TModel>();
		}
		catch
		{
			throw;
		}
	}

And I use it like:

    List(w => w.Age >= 10, o => o.OrderByDescending(z => z.CreatedAt));

Hope it helps.

[],
Regards,

@rmszc81

**Comment by Jack85** [comment]
Thanks, 
would be also cool inside.
