### ISSUE TITLE
Error when installing from nuget in xamarin project

### ISSUE THREAD

**Issue by charleypeng** [mbdavid/LiteDB#542]
I am using vs2017 and xamarin.forms project, and this error showed when i start to install
"Could not install package 'LiteDB 3.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author"

So I assume it's the cause of vs2017? Not sure if there is future update for this version?
btw  thanks for this great db.

**Comment by mbdavid** [comment]
Hi @charleypeng, LiteDB v3.1 is was compiled in vs2017. To works with xamarin, you must reference LiteDB as a NetStandard reference.
