### ISSUE TITLE
How to do paging (limit, skip) with Find and Query LINQ code?

### ISSUE THREAD

**Issue by softwareguy74** [mbdavid/LiteDB#548]
I see that limit and skip are supported in the shell, but I could not find any documentation on how to achieve this using LINQ.  Is this possible?  If so, a sample would be greatly appreciate.  If not, any idea when this would be added?  This is a very necessary feature for us.  Thanks.

**Comment by mbdavid** [comment]
Hi @softwareguy74, you can specify Limit/Skip in `Find` method on `LiteCollection` or in `LiteQueryable`:

```
using(var db = new LiteRepository(...))
{
    db.Query<MyClass>()
        .Where(x => x.Id > 10)
        .Skip(10)
        .Limit(10)
        .ToList()
}
```

**Comment by softwareguy74** [comment]
But I think this start performing badly as the data set gets larger and larger.  Is there an alternative to using skip?  Since I'm assuming skip still requires the engine to scan over all the records.  I have read articles that MongoDB performs slowing using skip on large data sets as well.

**Comment by mbdavid** [comment]
Skip will scan not over documents, but index keys only (that why is diferent than call Skip from IEnumerable).
I didn't know any other option to do this, if you have any article about that, share here to read more about it.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
