### ISSUE TITLE
Can we start using Gitter for having a community where we can chat or query?

### ISSUE THREAD

**Issue by sherry-ummen** [mbdavid/LiteDB#55]
Hello David,

I see LiteDB is catching lot of eyes and its an excellent project. Sometimes we require some help or queries or discussion for which I sometimes personally mail you or creat an issue.

Instead of this can we start using https://gitter.im . Its an excellent tool and lot of big projects have started using it.

It woudl be nice to have the same for LiteDb we have a good growing community.

Thanks

**Comment by mbdavid** [comment]
Hi @sherry-ummen! I never use this tool. But I like github too, its simple and a centralized space for all information about project.

And thank you for all your contribuition for LiteDB project. It´s relly nice to know that project has value to others!

**Comment by sherry-ummen** [comment]
Ok I understand. When can I expect the newer version of LiteDB to be released? Thanks

**Comment by mbdavid** [comment]
Hi @sherry-ummen. New version will take a time. I'm really want re-write almost every thing (who don't want re-write all code after finish version 1). 

But for new version I have others plans witch it's difficul to implement in this code. Be more testable, be more robust solution.

**Comment by sherry-ummen** [comment]
Great!
