### ISSUE TITLE
Error:Int64 ID insert fail

### ISSUE THREAD

**Issue by suxiaojack** [mbdavid/LiteDB#550]
Sometimes, a class has a ID field that is a Int64 type, and the insertion operation would fail. Said that the duplicate index value is (null). It seems that the error appears after the EnsurceIndex ("ID", true)?only can be inserted once time, even if the ID value is simple as 1, 2, 3.

**Comment by mbdavid** [comment]
Hi @suxiaojack, there is not built-in Int64 auto-increment support. Only for Int32. If you want you can create your own. Take a look here how Int32 was implemented:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.cs#L142

**Comment by suxiaojack** [comment]
Thanks @mbdavid , sorry, I can't understand，I'm not used the autoid functional,just manually set the id value and try insert.But why, once I commented to remove the line of EnsureIndex("ID",true), it works fine.

**Comment by mbdavid** [comment]
Ok, you have no "ID" field (and if you have this property in you class it's converted to _id document field), so, when you create an unique index in this field that not exists, first index key contains "null" and in secound insert try insert another null and this throw duplicate key.

**Comment by suxiaojack** [comment]
Aha, that's why. I think the help documentation should indicate that we don't need to write EnsureIndex ("ID", true) ,EnsureIndex ("Id", true) ,EnsureIndex ("id", true) ,and so on.Because there is only one _id document field,it's easy to confuse.Thanks @mbdavid !
