### ISSUE TITLE
Reflection.IsList returns false for IEnumerable<>

### ISSUE THREAD

**Issue by alexwiese** [mbdavid/LiteDB#552]
Example:

    Reflection.IsList(typeof(ICollection<>)); // Returns true
    Reflection.IsList(typeof(IEnumerable<>)); // Returns false

Is this by design? I would have thought the intention is that any type that implements `IEnumerable<T>` including `IEnumerable<T>` itself would return true.

If the argument is that `IEnumerable<>` isn't a collection interface: the check itself isn't strict so you could do the following.

    public interface IEnumerable2<T> : IEnumerable<T>
    {
    }

And `Reflection.IsList(typeof(IEnumerable2<>));` would return true.

**Comment by alexwiese** [comment]
For further reference I came across this issue when doing the following

    public class Person
    {
        [BsonRef("Address")]
        public IEnumerable<Address> Addresses { get; set; }
    }

The `BsonMapper` calls `RegisterDbRefItem` instead of `RegisterDbRefList`. Workaround is to declare the property as something derived from `IEnumerable<>` such as `ICollection<>`.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
