### ISSUE TITLE
Remove database password

### ISSUE THREAD

**Issue by RonaldZaZ** [mbdavid/LiteDB#553]
If I try to remove the password from the database with the Shrink function, it seems it is still encrypted but with an empty string.
So the connection string still needs to contain _password=_ otherwise it can't ready anything.

**Comment by mbdavid** [comment]
Are you passing `null` in password when call `Shrink`?

**Comment by RonaldZaZ** [comment]
I tried "" and String.Empty
I will try null and let you know

**Comment by mbdavid** [comment]
Empty string is a password :) Checks here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Engine/Engine/Shrink.cs#L56

**Comment by RonaldZaZ** [comment]
Ok, thanks, I feel stupid.
It works :-)
