### ISSUE TITLE
A Simplified Chinese translation

### ISSUE THREAD

**Issue by lidanger** [mbdavid/LiteDB#555]
A Simplified Chinese translation in here
https://github.com/lidanger/LiteDB.wiki_Translation_zh-cn

Simple translation, wish it can help some ones.

**Comment by mbdavid** [comment]
Hi @lidanger, thanks for this! Chinise is 6th more visited language in LiteDB site. Thanks so much. I added you link to README me and a special thanks.

**Comment by lidanger** [comment]
No,it should be I thank you for a good  in-process nosql db.A translation is much easier.
