### ISSUE TITLE
Missing Implementation of BsonDocument.CopyTo

### ISSUE THREAD

**Issue by wgross** [mbdavid/LiteDB#557]
Just stumbled upon this in BsonDocument class
 ```
public void CopyTo(KeyValuePair<string, BsonValue>[] array, int arrayIndex)
{
    throw new NotImplementedException();
}
```
Is this an unsolved problem or just a bug?
Because it also prohibits List.AddRange I was forced into a verbose workaround :-)

`
<bson document>.Aggregate(new List<KeyValuePair<string, BsonValue>>(), (l, kv) => { l.Add(kv); return l; });`

**Comment by mbdavid** [comment]
Yes, it´s missing by "auto-implement" interface by visual studio auto. I will fix soon or if you want contribute, please make a PL :)
