### ISSUE TITLE
Lists not being mapped in the document.

### ISSUE THREAD

**Issue by RealBlazeIt** [mbdavid/LiteDB#558]
I have a model for a document defined in the following class: https://github.com/RealBlazeIt/DEA/blob/master/src/LiteDB/Models/Gang.cs

Every time I try to access the Members list of ulongs, I get this error: "Property 'Members.y' was not mapped into BsonDocument."

Here is a specific example of when this error happens: https://github.com/RealBlazeIt/DEA/blob/master/src/LiteDB/Repository/GangRepository.cs#L94

**Comment by mbdavid** [comment]
Hi @RealBlazeIt, it's a bug in linq query when convert `Any`. I will try fix, but Linq visitor is quite complex way. You can try for now use `Query` object.

`Query.And(Query.EQ("GuildId", guildId), Query.Or(Query.EQ("LeaderId", userId), Query.EQ("Members", userId))`

**Comment by RealBlazeIt** [comment]
Thanks, the query works, good luck with the fix!

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
