### ISSUE TITLE
Question: How does FileStorage differ compared to Normal insert?

### ISSUE THREAD

**Issue by sherry-ummen** [mbdavid/LiteDB#56]
Hi,

I was wondering what is the difference in Inserting as normal bson document and using FileStorage in terms of persisting the data to the disk.

Right now I have large C# object which I store it as FileStorage. I am thinking what may be the problem in that solution and is it a good idea.

Thanks

**Comment by mbdavid** [comment]
When you store a document, LiteDB convert this document to one single in-memory byte array (using BSON). This byte array are stored in a single transaction. In this case, LiteDB use as many as need RAM memory to keep document before write on disk,

When you store a file, LiteDB slipts this file in many documents (chunks) with 1Mb each. So, if you have 300Mb file, LiteDB will not consume 300MB RAM memory. There will be 300 documents, 1Mb each. No sigle transaction. After each chunck are inserted, LiteDB clears cache.

**Comment by sherry-ummen** [comment]
Thank you very much for the details.
