### ISSUE TITLE
search find complex prop - question

### ISSUE THREAD

**Issue by Jack85** [mbdavid/LiteDB#562]
Hi, 
one question:
what do i need to do in order to get find results on complex prop,
which it seems it doesn't  find it (either case sensitive or insesitive)?:

aka
> col.Find(x=>x.Categories.Any(c=>c.Name.Contains("node"))).Dump();
or
> col.Find(x=>x.Categories.Any(c=>c.Name.ToLower().Contains("node"))).Dump(); //throws exception

linqpad:
```csharp
public class BEntity
{
	public BEntity()
	{
		DateCreated = DateTime.Now;
	}
	public int ID { get; set; }
	public DateTime DateCreated { get; set; }
	public DateTime DateChanged { get; set; }
	public int Count { get; set; } //for paging
								   //  public bool Deleted { get; set; }

}
 public class Post : BEntity
    {

        public string Title { get; set; }
        public string Content { get; set; }     

        public List<Category> Categories { get; set; }
    }
   public class Category: BEntity
{
	public string Name { get; set; }
	
}
void Main()
{
var mapper = new BsonMapper();// BsonMapper.Global;
	//mapper.IncludeFields = true;
	//mapper.IncludeNonPublic = true;
	mapper.Entity<Post>().Index(x => x.Title).Index(x => x.Content)	
	.DbRef(x => x.Categories, "category");
	//dbpost	
	mapper.Entity<Category>()
	.Index(x => x.Name);
         
      string path =@"data.db";

	using (var db = new LiteDatabase(path, mapper))
	//using (var db = new LiteDatabase(path))
	{
               var col = db.GetCollection<Post>("post").Include((c)=>c.Categories).Include(s=>s.Tags);
		var catcol = db.GetCollection<Category>("category");
                 using (var dbb = new LiteRepository(path))
		{
			dbb.Query<Post>().Include(s=>s.Categories).Where(x => x.Categories.Any(c=>c.Name.Contains(".net")))
			.ToList().Dump();
                 }
		//col.FindAll().Dump();
        col.Find(x=>x.Categories.Any(c=>c.Name.Contains("node"))).Dump();
		catcol.FindAll().Dump();
     }
 }


```

**Comment by mbdavid** [comment]
Hi @Jack85, using `Find` method from `LiteCollection` the litedb engine always use an index to find document. Can be use multiple indexes to do that. When you write some Linq expression it´s converter to `Query` object.
This conversion is not simple and it´s implemented only basic instructions. If you check `QueryVisitor` class, it´s possible check this conversion.
When you query data using index it´s not possible change data inside already made index, like use `ToLower()` because inside index key, you name field are stored using normal case.
You can create your own index using `ToLower` method and than query this.
```
BsonMapper.Global.Entity<Person>()
    .Index("nameLowerCase", x => x.Name.ToLower());

col.Find(Query.Contains("nameLowerCase", myVar));
```

**Comment by Jack85** [comment]
Good,  
And when i want to do it more generic way just to filter that complex prop like ef is doin ,passing that expresion? Is there a way? 
I saw some getter func in api on index.

**Comment by mbdavid** [comment]
If you want more complex queries it will not use an index (like in sql server or any database). All data must be read to checked if pass in your filter. So, it´s just use linq to object, like:

```
col
    .Find(x => x.Age >= 40)
    .Where(x => x.Children.Count(z => z.Age < 18));
```

Inside `Find`, filter using index, inside `Where` filter using simple object compare values.

**Comment by Jack85** [comment]
So you are sayng there is no way to use index in expression like 
> X. Children. Any(y=>y. Name. Contains? 

Just to filter nice way..

**Comment by mbdavid** [comment]
No, its not possible filter this, using an index. You always need, in this case, test all documents (or already sub filtered documents).

**Comment by Jack85** [comment]
Ok, thanks. 
Then i think this could be cool feature request,  to filter like this on indexed fields for level1 props.

**Comment by Jack85** [comment]
if try those, I get value cannot be null. I hope any can be used?
```
//col.Find(x=>x.ID>0).Where(p=>p.Categories.Find(c=>c.Name.Contains("node")).Count>0).Dump();
//col.Find(x=>x.ID>0).Where(x=> x.Categories.Where(c=>c.ID==1).Count()>0).Dump();
col.Find(x=>x.ID>0).Where(x=> x.Categories.Any(c=>c.ID==1)).Dump();
```

**Comment by mbdavid** [comment]
Use `x.ID > 0` did not filer any document (will return all documents) so it's not needed. Using `FindAll()` you will get all documents an filter all of them by your `Func`. It's could be bad solution for generic way if you have lots of documents.

**Comment by Jack85** [comment]
Yes,  i would expect find to know how to do it,  this is reletively clear straghtforward seach on level1 prop where clause.
Mongo db doin stuf like
> db.coll.find({'fieldA.fieldA2': { $elemMatch:{ text:"ciao"} }})

Also knows how to do it without caling out special index, in our case it schould be expresion
