### ISSUE TITLE
Help with querys

### ISSUE THREAD

**Issue by nikoxd123** [mbdavid/LiteDB#565]
Hi, my query returns NullException. Even if there is a client with that name.
The Busqueda variable is set to {LiteDB.LiteCollection <Cliente>. <Find> d__17}

`var busqueda = db.getDB().GetCollection<Cliente>("Cliente").Find(Query.StartsWith("Nombres", nombre));
            if (!busqueda.Equals(null))
            {
                var busquedaList = busqueda.ToList<Cliente>();

                foreach(Cliente cl in busquedaList)
                {
                    Debug.WriteLine(cl.Nombres);
                }
            }`

**Comment by mbdavid** [comment]
how you `busqueda` can be null if `Find` method returns always an IEnumerable<T>, so even if there is no records you will get an empty IEnumerable.
Try:  `var myList = collection.Find(....).ToList()` - it's always must return instance of List<T>

**Comment by nikoxd123** [comment]
The Client named "Pepe" does not exist and gives error.
Now in the next test the name you searched for was "Nicolas" and that name exists and still gives error.

![cuandonohayobjeto](https://cloud.githubusercontent.com/assets/12067320/24831241/db035d8e-1c6c-11e7-930b-07b9c3a4f8c3.PNG)

**Comment by mbdavid** [comment]
Can you post a small snipplet to test this? It's seam a simple find, there is no reason to this. Did you call `Dispose` of database before call this?

**Comment by nikoxd123** [comment]
No, I have not made Dispose.
The strange thing is that with an element that exists I pull null, but I can continue to add clients without problems and are saved.

**Comment by mbdavid** [comment]
Try add LiteDB source code as a project to get where this Null reference are occuring... I never saw this.

**Comment by nikoxd123** [comment]
Sorry for the delay, I attached the files of my project:
[https://github.com/nikoxd123/Prueba/blob/master/Clases.cs](url)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
