### ISSUE TITLE
Concurrency and other issues with Xamarin.IOS

### ISSUE THREAD

**Issue by j-hayes** [mbdavid/LiteDB#567]
Hello LiteDb contributors, 

This seems like a great framework with tons of active members so I wanted to use it in a project/framework I am building using Xamarin. I want to use this on projects where I don't need the querying power of SQLite to store more simple data models. (Or if it's fast enough, just never use SQLite ever again) '

I am getting two specific errors pretty consistently. 

One is a filenotfound exception on the journal file. I have gotten around that by turning journalling off (which I would prefer to not have to do.) 

The second is more perplexing / show stopping. 

I keep getting a: 

System.IO.IOException
Sharing violation on path /Users/XXXXXXXX/Library/Developer/CoreSimulator/Devices/551B6BDD-3637-4B22-BAA1-35C2008DF71E/data/Containers/Data/Application/AAEDFBDF-4F97-4140-81EC-9B8085532731/Library/someWidgets.liteDb

When I try to really do just about anything. I have tried sharing the LiteDatabase object between threads, I have tried giving every request its own reference. All to no avail. 

I have tried disposing of the connection as well. Everything I do seems to bring up some slight variation on the same kind of problem of file access. 

It always seems to happen on the second attempt to do something with the database. 

Has anyone else had success using this framework with Xamarin and be willing to share some examples and or take a look at my code and tell me if I am doing something wrong. 

https://github.com/X-OFF/xoff/tree/litedb-halp

Thanks!

**Comment by j-hayes** [comment]
One of my suspicions is that it is because I am not disposing of the LiteDatabase reference at the right point 
and/or
I am not disposing it when the application terminates.

**Comment by mbdavid** [comment]
Hi @j-hayes how are you using LiteDatabase in concurrency? A single instance across all threads or each thread are consuming inside an `using` statment?

For mobile apps, I recommend you use single instance and no explicit transaction (do not use Begin/Commit).

**Comment by j-hayes** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using LiteDB;
using XOFF.Core;
using XOFF.Core.Repositories;

namespace XOFF.LiteDB
{
	public interface ILiteDBRepository<TModel, TIdentifier> : IRepository<TModel,TIdentifier> where TModel : class, IModel<TIdentifier>
	{
	
	}


	public class LiteDBRepository<TModel, TIdentifier> : ILiteDBRepository<TModel,TIdentifier> where TModel : class, IModel<TIdentifier>
	{
		
		readonly ILiteDbConnectionProvider _connectionProvider;

	    public LiteDBRepository(ILiteDbConnectionProvider connectionProvider)
		{
			_connectionProvider = connectionProvider;

		}

		private LiteCollection<TModel> GetCollection(LiteDatabase connection)

		{
			return connection.GetCollection<TModel>();
		}

		LiteDatabase GetConnection()
		{
			return _connectionProvider.Database;
		}

		public OperationResult<IList<TModel>> All(Expression<Func<TModel, bool>> filter = null, Func<IQueryable<TModel>, IOrderedQueryable<TModel>> orderBy = null, bool recursive = false)
		{
			try
			{
				var connection = GetConnection();
				
				IEnumerable<TModel> items = new List<TModel>();
				var collection = GetCollection(connection);
				if (filter != null)
				{
					items = collection.Find(filter);
				}
				else 
				{
					items = collection.FindAll();
				}

				//recursive is by default because this stuff is being stored as json documents 

				if (orderBy != null)
				{
					items = orderBy(items.AsQueryable()).ToList();
				}
				var results = items.ToList();
				var result = OperationResult<IList<TModel>>.CreateSuccessResult(results);
				//connection.Dispose();
				return result;

			}
			catch (Exception ex)
		    {
		        return OperationResult<IList<TModel>>.CreateFailure(ex);
		    }
		}



		public OperationResult Delete(TIdentifier id)
		{
		    try
		    {
				var connection = GetConnection();
				GetCollection(connection).Delete(x => x.Id.Equals(id));
				//connection.Dispose();
				return OperationResult.CreateSuccessResult("Success");
		    }
		    catch (Exception ex)
		    {
		        return OperationResult.CreateFailure(ex);
		    }
		}

		public OperationResult DeleteAll(Expression<Func<TModel, bool>> filter = null, bool recursive = false)
		{

            try
            {
				var connection = GetConnection();
				if (filter == null)
				{
					connection.DropCollection(typeof(TModel).Name);
				}
				else
				{
					GetCollection(connection).Delete(filter);
				}
				//connection.Dispose();
                return OperationResult.CreateSuccessResult("Success");
            }
            catch (Exception ex)
            {
                return OperationResult.CreateFailure(ex);
            }
          
		}

		public OperationResult DeleteAllInTransaction(ICollection<TModel> items, bool recursive = false)
		{

		    try
		    {
				var connection = GetConnection();
				using (var transaction = connection.BeginTrans())
				{
					try
					{
						foreach (var model in items)
						{
							GetCollection(connection).Delete(x => x.Id.Equals(model.Id));
						}
						transaction.Commit();

					}
					catch (Exception)
					{
						transaction.Rollback();
						throw;
					}
				}
				//connection.Dispose();		
                return OperationResult.CreateSuccessResult("Success");
		    }
		    catch (Exception ex)
		    {
		        return OperationResult.CreateFailure(ex);
		    }
		}

		public OperationResult<TModel> Get(TIdentifier id, bool withChildren = false, bool recursive = false)
		{
		    try
		    {
				var connection = GetConnection();
				var item = GetCollection(connection).FindById(new BsonValue(id));
				//connection.Dispose();
				return OperationResult<TModel>.CreateSuccessResult(item);

		    }
		    catch (Exception ex)
		    {
		        return OperationResult<TModel>.CreateFailure(ex);
		        throw;
		    }
		}

		public OperationResult<IList<TModel>> Get(List<TIdentifier> ids, bool withChildren = false, bool recursive = false)
		{
            try
            {
				var connection = GetConnection();
				var items = GetCollection(connection).Find(x => ids.Contains(x.Id)).ToList();
				//connection.Dispose();
				return OperationResult<IList<TModel>>.CreateSuccessResult(items);

            }
            catch (Exception ex)
            {
                return OperationResult<IList<TModel>>.CreateFailure(ex);
                throw;
            }
        }

		public void Initialize()
		{
			//nothing needed here yet
		}

		public OperationResult Upsert(ICollection<TModel> items)
        {
            try
            {	
                foreach (var model in items)
                {
					model.LastTimeSynced = DateTime.UtcNow;
                    Upsert(model);
                }
                return OperationResult.CreateSuccessResult("Success");
            }
            catch (Exception ex)
            {
                return OperationResult.CreateFailure(ex);
            }
		}



		public OperationResult Upsert(TModel entity)
		{
		    try
		    {
				var connection = GetConnection();
				var collection = GetCollection(connection);
				var exists = collection.Exists(x => x.Id.Equals(entity.Id));
				if (exists)
				{
					collection.Update(entity);
				}
				else
				{
					collection.Insert(entity);
				}
				//connection.Dispose();
                return OperationResult.CreateSuccessResult("Success");
            }
		    catch (Exception ex)
		    {
                return OperationResult.CreateFailure(ex);
            }
		}

		public OperationResult Upsert(object item)
		{
			if (!(item is TModel))
			{
				throw new InvalidOperationException($"Item is not of type {typeof(TModel).FullName}");
			}
			var model = (TModel)item;
			return Upsert(model);
		}
	}
}

------

using System;
using System.Diagnostics;
using System.IO;
using LiteDB;

namespace XOFF.LiteDB
{
	public class LiteDbConnectionProvider : ILiteDbConnectionProvider
	{
		LiteDatabase _database;

		//public LiteDbConnectionProvider(LiteDatabase database)
		//{
		//	_database = database;
		//}

		public LiteDatabase Database 
		{
			get
			{
				Debug.WriteLine(DateTime.Now);
				if (_database == null) 
				{
					var documentsPath = System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal);
					var libraryPath = Path.Combine(documentsPath, "..", "Library");
					var databasePath = Path.Combine(libraryPath, "someWidgets.liteDb");
					var connStr = new ConnectionString($"filename=\"{databasePath}\"; journal =false;");//when this is set to true, file not found exceptions get thrown 

					_database = new LiteDatabase(connStr);
				}
				return _database;

			}
		}
	}
}

**Comment by j-hayes** [comment]
Does this look right? Do I need to dispose of the LiteDabase instance at any point? 

Do you have any example code using Xamarin? 

Thanks for the quick response. Glad to help

**Comment by j-hayes** [comment]
Turns out this was an issue with the provided path. I was specifying 

```
var documentsPath = System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal);
				var libraryPath = Path.Combine(documentsPath, "..", "Library");
				var databasePath = Path.Combine(libraryPath, "someWidgets.liteDb");
				var connStr = new ConnectionString($"filename=\"{databasePath}\"; journal =false;");//when this is set to true, file not found exceptions get thrown 
```
when I should have just been putting 

```
var connStr = new ConnectionString($"filename=\"{someWidgets.liteDb}\"; journal =false;");
```

The class LitePlatform was already setting the path in the connection string. I had to crack open the source. Never got a meaningful error message from the nuget package. I actually am still unable to get the most up to do date nuget package to work but that is a separate issue. 

Closing this thread.
