### ISSUE TITLE
Bson Index allows duplicate values in LiteDB

### ISSUE THREAD

**Issue by immaruthi** [mbdavid/LiteDB#569]
This is my sample class

public class Product
    {
        public int ProductId { get; set; }

        [BsonIndex]
        public string FirstName { get; set; }

        [BsonIndex(true)]
        [BsonField("ProductAliasName")]
        public string AliasName { get; set; }
    }

I am preparing list of products with duplicate values as like below,

public IEnumerable<Product> GetProductList()
        {
            List<Product> listProduct = new List<Product>();

            listProduct.Add(new Product() { FirstName = "X-Product-09", AliasName = "Axel" });
            listProduct.Add(new Product() { FirstName = "X-Product-09", AliasName = "Axel" });

            return listProduct;
        }

now I am trying to insert this list of values to the collection

using (LiteDataBase = new LiteDatabase(DbPath + "MyData.db"))
            {
                var collection = LiteDataBase.GetCollection<Product>("Customer");
                var resp = collection.Insert(GetProductList());
            }

I have received resp value is '2'. Why it is allowing duplicate values even though that values decorated by   BSON Index.

**Comment by mbdavid** [comment]
Hi @immaruthi, there some tricky problems using BsonIndex attribute (when run with unique=true). LiteDB will only create this index first time when you run query using this field.
I will review this. For now, I recommend you call `EnsudeIndex` just after create your datafile
