### ISSUE TITLE
ISSUE) Multiple Different Exceptions While Using LiteDB

### ISSUE THREAD

**Issue by hardknoxni69a** [mbdavid/LiteDB#571]
Thanks For Looking Into This

Here Is The Code That Is Used
https://github.com/Necrobot-Private/NecroBot/blob/master/PoGo.NecroBot.Logic/State/SessionStats.cs

Here Is A Few Of The Issues And Codes Seems Worse On 3.0 To Be Honest
https://github.com/Necrobot-Private/NecroBot/issues/1390

Please Let Me Know The Fix As We Have A Ton Of Users And Is Used On A 24Hour Daily Rolling Limit So Once Exception Occurs The Database Is Ruined And Needs To Be Rebuilt So Program Is Unusable Practically Because The Database Is No Longer In Sync I Do Not Want To Change Database Code To New Program. Thank You So Much For Your Help

**Comment by mbdavid** [comment]
Hi @hardknoxni69a, try do:

- Use unique _id key in you document class, like:

        public class PokemonTimestamp
        {
            [BsonId]
            public Int64 Timestamp { get; set; }
        }

- Remove EnsureIndex (_id will be unique indexed by default)
- If you wants cheks if your _id already exists, use `Upsert` (not Exists + Insert) - If you do this, use inside an transaction
- If you have a hard multi process write access you may change the way how you use LiteDatabase instance, keeping in a single static variable using same instance in all connections (in this case, do not use transactions)
- Disable journal file (checks in connection string)
- IF you want be faster, use direct LiteEngine and BsonDocument class you avoid serialization/deserialization all times (you document is pretty simple, just a single propertty)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
