### ISSUE TITLE
PCL version of current release not supported ?

### ISSUE THREAD

**Issue by stephenhauck** [mbdavid/LiteDB#572]
The database is awesome .. unfortunately I need to use a PCL version with my Xamarin app.
It appears that you dropped support for the PCL version.

All of the NuGet packages I use are PCL's.......

As far as I know I cannot use a PCL version of NuGet packages at the same time I use the .NET Standard library versions in a single project.

So is there an option for a current release of LiteDB as a PCL ?

Thanks

**Comment by stephenhauck** [comment]
So I did a little more digging and found that you de-supported the PCL version....
https://github.com/mbdavid/LiteDB/wiki/Portable-Version

I can't be the only one who needs a PCL version .. I would be happy to make a "donation" to have a PCL version kept current ..... anyone else with me ?

**Comment by mbdavid** [comment]
Hi, netstandard cann't br used? V3 are build over new netstandard format, that are new pcl

**Comment by stephenhauck** [comment]
As far as I know you cannot mix profile 259 (PCL) and .NET Standard is 111 ....

For instance.. I am using this ...
https://www.nuget.org/packages/Acr.UserDialogs/

It supports profile 259.... as far as I know .NET Standard is profile 111 (?) and cannot be mixed ... anyone else know if this is true or not ?

**Comment by stephenhauck** [comment]
I guess the big issue is this .. I use about 25 or so  NuGet packages in any given project and they are all PCL (259) ....

I would like to use LiteDB as a 259 because the 25 or so packages I do use aren't going to be converted to .NET Standard very quickly...... if at all ?

I "wish" they were all .NET Standard but alas that is not the case :)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
