### ISSUE TITLE
Power-off is not handled properly

### ISSUE THREAD

**Issue by mkosieradzki** [mbdavid/LiteDB#574]
During tests I have found out that power-off events are not handled properly.

And my database is getting corrupted.

@mbdavid 
My **guess** is that you are not calling Flush/FlushAsync before closing the journal file. It basicaly means that JournalFile can be still in the OS Cache (and not on the physical disk yet) while you start to alter database file.

The same applies to the database file that should be flushed to the physical disk before cleaning up the journal file.

Closing the file does not mean it is physically flushed to disk.

**Comment by mkosieradzki** [comment]
Of course I mean FileStream.Flush(true).

**Comment by mkosieradzki** [comment]
@mbdavid Can you have a look, please?

**Comment by mbdavid** [comment]
Sorry @mkosieradzki, I had almost no time for LiteDB for a long time. You code seams ok, I'm merging with master. Thansk!

**Comment by mkosieradzki** [comment]
Thanks a lot @mbdavid! However, please remember this might have some performance impact, especially on non-SSD disks. In the future, I believe, that disk sync should be done asynchronously, but consistently journal+db.

**Comment by mbdavid** [comment]
Yes, I know this. But it OS doesnt hang this pending saves this could be corrupt datafile. It;s on my plans to next major version be async read/writes, but I still don't know how do it (I never work with async in c#)

**Comment by mkosieradzki** [comment]
I would be happy to help (I have a lot of experience with async-programming in c#) and if you are interested in getting some async prototype (for example for the DbEngine layer), I can try to hack something together in a separate branch for example in June/July.

**Comment by mbdavid** [comment]
@mkosieradzki will be great to get this contrib! My idea for next version will be more simple & robust as possible, so I will try focus my dev only in LiteEngine and write more tests for better concurrency support.

**Comment by mkosieradzki** [comment]
@mbdavid Good news is that I haven't noticed **any** performance degradation (on my SSD) after applying the FlushAsync patch! Just wanted to let you know :)

**Comment by mbdavid** [comment]
Thats nice to know @mkosieradzki! Thanks
