### ISSUE TITLE
issue #499 still exists when do update operation in multithreads. 

### ISSUE THREAD

**Issue by shenzhigang** [mbdavid/LiteDB#578]
version:3.1.0.
issue #499  may be fixed only in "find and insert" scene.
here is my test program: 
[LiteDbTest.zip](https://github.com/mbdavid/LiteDB/files/924933/LiteDbTest.zip)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
