### ISSUE TITLE
How can I password protect the db?

### ISSUE THREAD

**Issue by codeyu** [mbdavid/LiteDB#58]
Is it possible password protect a LiteDB  as you would do on access?

**Comment by mbdavid** [comment]
Hi @codeyu. At this point, there is not way to do that. It´s not dificult to implement using symetric Rijndael algorithm. I will add this as a feature in next release

**Comment by ambyte** [comment]
Hi,
When can we expect this functionality? This very important function.

**Comment by mbdavid** [comment]
Hi @ambyte, It´s on way. In this new v2 password part of connection string. It´s only missing a crypto/decrypto symetric without change byte array size.

**Comment by ambyte** [comment]
It`s cool!!!
Can I protect an existing DB or to create a new one?

**Comment by mbdavid** [comment]
Only create a new one. But, will be possible copy data from a plain db to protected one.

**Comment by ambyte** [comment]
Thank you! I thought as much.

**Comment by mbdavid** [comment]
Done. Just add "password=your_password" in connection string. LiteDB uses SHA1 for store/check password and Rijndael for encryption.
