### ISSUE TITLE
How should LiteDB be used in multi threaded scenarios?-v3.1.0

### ISSUE THREAD

**Issue by don59** [mbdavid/LiteDB#583]
Code:
```Csharp
public void Insert(ProductCodelModel model)
{
    using (var db = new LiteDatabase(Config.DatabaseFileName))
    {
        var products = db.GetCollection<ProductCodelModel>(TABLE_NAME);
        products.Insert(model);
    }
}

 public class ProductCodelModel
    {
        public long code { get; set; }
        public int status { get; set; }
        public DateTime time
        {
            get
            {
                return DateTime.Now;
            }
        }
    }

for (int i = 0; i < ThreadCount; i++)
{
    new TaskFactory().StartNew(() => Insert(model));
}
```

***
Errors:

>System.InvalidCastException: 无法将类型为“LiteDB.EmptyPage”的对象强制转换为类型“LiteDB.DataPage”。
   在 LiteDB.PageService.GetPage[T](UInt32 pageID)
   在 LiteDB.PageService.GetFreePage[T](UInt32 startPageID, Int32 size)
   在 LiteDB.DataService.Insert(CollectionPage col, Byte[] data)
   在 LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc)
   在 LiteDB.LiteEngine.<>c__DisplayClass61_0.<Insert>b__0(CollectionPage col)
   在 LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   在 LiteDB.LiteEngine.Insert(String collection, BsonDocument doc)
   在 LiteDB.LiteCollection`1.Insert(T document)
   在 Lottak.Tapai.Win.Client.Data.ProductCodeDal.Insert(ProductCodelModel model) 位置 D:\PorterCMS\Lottak.Tapai.Win.Client\Data\ProductCodeDal.cs:行号 26
   在 Lottak.Tapai.Win.Client.Events.GenerateCodeEvent.Generate(Int32 startNumber, Int32 count) 位置 D:\PorterCMS\Lottak.Tapai.Win.Client\Events\GenerateCodeEvent.cs:行号 57

>System.UnauthorizedAccessException: Access to path 'D:\Users\Administrator\Documents\Data\tapai-journal.db' was denied.
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 LiteDB.FileDiskService.WriteJournal(ICollection`1 pages)
   在 LiteDB.TransactionService.Commit()
   在 LiteDB.LiteEngine.Commit()
   在 LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   在 LiteDB.LiteEngine.Insert(String collection, BsonDocument doc)
   在 LiteDB.LiteCollection`1.Insert(T document)
   在 Lottak.Tapai.Win.Client.Data.ProductCodeDal.Insert(ProductCodelModel model) 位置 D:\PorterCMS\Lottak.Tapai.Win.Client\Data\ProductCodeDal.cs:行号 26
   在 Lottak.Tapai.Win.Client.Events.GenerateCodeEvent.Generate(Int32 startNumber, Int32 count) 位置 D:\PorterCMS\Lottak.Tapai.Win.Client\Events\GenerateCodeEvent.cs:行号 57

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
