### ISSUE TITLE
How to include nth level reference entity ?

### ISSUE THREAD

**Issue by DebPattanaik** [mbdavid/LiteDB#584]
I have a object "User" . Now my user class has a entity "Role" . Role class has two more sub entities "Navigation" and "Action".So while querying I can include "Role" but how to include child entities of "Role".

class User
{

> Role Role{get;set;}

}
class Role 
{

> Action Actions{get;set;}
Navigation Navigations{get;set;}

}

> _collection.Include(x => x.Roles).Include(x => x.State).Find(query);
So it only gives user and role but navigation and action both are empty.

**Comment by DebPattanaik** [comment]
I tried something below ,it's fetching all required no of records but all fields are blank only id field is populated .

> return _collection.Include(x => x.Roles).Include("Roles.Navigations").Include(x => x.State).Find(query);

**Comment by mbdavid** [comment]
Hi @DebPattanaik, LiteDB supports only first level of includes. For more leves, try use `Include(Action<T>)` as here: #561

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
