### ISSUE TITLE
Encryption issues

### ISSUE THREAD

**Issue by elyoh** [mbdavid/LiteDB#586]
An SHA1 hash of the **password** is stored in the database header page.  This is insecure because a malicious user could generate hashes for common passwords and simply compare them with the hash stored in the header page.  Further, any file with the same password will have the same password hash.

As mentioned in #581 an Encrypt-**then**-MAC should be used which provides authentication without the need for storing a hash of the password.

**Comment by ronnieoverby** [comment]
Could you point out why this is a big deal? The reason I think it's not, is that this particular SHA1 hash is not used to derive the encryption key for the database.

If a hash collision were to be found by an attacker it would only get them past the header page validation phase. Once the system began to attempt decrypting data, (which uses MS's PBKDF2 implementation to derive the key) a decryption failure would occur.

**Comment by elyoh** [comment]
In simple, it allows dictionary attacks on the database since there is a one to one mapping between plain text passwords and their associated SHA1 hash.  You could compute the SHA1 hash for a dictionary of plain text passwords very quickly.  To verify if a password is correct, one must **only** compare it with the hash stored in the file.  This is a problem because that process is computationally fast.  Once a malicious user has done this for a set of passwords, they have a reusable table of plain text passwords and their associated SHA1 hashes.  Unless you can guarantee that every instance of a LiteDB has a strong password, this gives a malicious user a very quick way to get into the data.

The use of a PBKDF2 function to derive the key has two purposes:
First it makes it computationally slow to derive a key from a password.  This time is short enough for a legitimate user generating one key when they have the correct password, but not short enough if you want to try lots of passwords.
Second, they use a salt to ensure that if a multiple users reuse the same plain text password, they key is not the same.  This renders the dictionary useless provided a different cryptographically random salt is used for each database.

In summary, hashing a password without a salt and storing it next to the database is never a good idea.

**Comment by ronnieoverby** [comment]
Herp derp. Absolutely right. Embarrassed that I didn't realize that.

**Comment by mbdavid** [comment]
For next version I´m thinking in remove this hash in Header page and validate password only by checking a new fixed page Type with know data before encrypt, like: Full a whole page with `1` and than encrypt using user password. To check if password is valid, just decrypt this fixed page and test if all bytes are `1` again.

**Comment by ronnieoverby** [comment]
The fixed page of 1s sounds like a bad idea. The knowledge of cleartext is
too informative for an attacker.

**Comment by elyoh** [comment]
To secure the library, the immediate action must be to remove the hash from the header page and remove the password verification all together.  This removes the vulnerability and ensures the data is secret without possession of the password.  The current use of a PBKDF2 function to derive the key makes it extremely unlikely that an incorrect password will lead to any intelligible plain text data.


Longer term, implementing an Encrypt then MAC approach is needed to verify the data has not been modified since it was encrypted.  Separate verification of the password is not needed in this approach; if the password supplied is incorrect or the data has been modified, this is easily detected.

[SecurityDriven.Inferno ](https://github.com/sdrapkin/SecurityDriven.Inferno) provides straightforward methods for doing this out of the box.  It is professionally audited and MIT licensed so can be used in this project.

**Comment by ronnieoverby** [comment]
Totally agree. If I get a chance I may take a swing and send PR.

**Comment by zer0x64** [comment]
Not sure if it has been mentionned yet, but there are also a bunch of issues related to the AES itself. Basically, using ECB mode is pretty bad in itself and a predictable IV is set but isn't used(because of the mode). In this case, from what I know, it seems like the best mode would be AES-XTS

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
