### ISSUE TITLE
ASP.NET Core

### ISSUE THREAD

**Issue by Ephiljp** [mbdavid/LiteDB#587]
Hello @mbdavid ,

I'm trying to do a CRUD with ASP.NET Core and when execute a command and change to list or other, it's return an exception.

 System.IO.IOException: 'The process cannot access the file 'C:\TesteCRUD\Database' because it is being used by another process.'

After start this issue I could do with the dispose command. There's another way to do this? Or this is the right way?

 public class Repositorio
    {
        public LiteDatabase Store { get; set; }

        public Repositorio()
        {
            Store = new LiteDatabase("Database");      
           
        }

        public void Cadastre(Cliente cliente)
        {
            var clientecollect = Store.GetCollection<Cliente>("cliente");

            clientecollect.Insert(cliente);

            Store.Dispose();
        }

        public List<Cliente> Liste()
        {
            var clientlist = Store.GetCollection<Cliente>("cliente");

            var lista = clientlist.FindAll().ToList();

            Store.Dispose();

            return lista;
           
        }
    }

Best regards!!!

**Comment by mbdavid** [comment]
Hi @Ephiljp, in web environment I recommend to use:

- Single instance of LiteDatabase (using in static variable) using exclusive access (see connectionString)

- or -

- Open/Close in each operation in your repository class, like (I'm using `LiteReposirory` here):

```C#
public void Cadastre(Cliente cliente)
{
    using(var db = new LiteRepository())
    {
        db.Insert(cliente);
    }
}

public List<Cliente> Liste()
{
    using(var db = new LiteDatabase())
    {
        return db.Query<Cliente>().ToList();
    }
}
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
