### ISSUE TITLE
Valid Database file

### ISSUE THREAD

**Issue by shai-benshimol** [mbdavid/LiteDB#589]
It is possible to check if file is valid?
For ex:
LiteDatabase ldb = new LiteDatabase("some_wrong_file.swf");

**Comment by mbdavid** [comment]
Hi @shai-benshimol, if you use LiteEngine ctor, datadase will be open at this time (not as lazy as LiteDatabase) and will be validate.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
