### ISSUE TITLE
How does LiteDB respond to changes to class definitions?

### ISSUE THREAD

**Issue by mludlum** [mbdavid/LiteDB#590]
I'm considering LiteDB because RDBMS upgrading is cumbersome and I want to be able to change my schema easily.   How does LiteDB handle changes to class definitions?   If a document's fields does not match the class fields in my query, does it raise an error, or just ignore?

**Comment by mbdavid** [comment]
Hi @mludlum, take a look here #524 and here #328 - LiteDB, in this aspect, works as MongoDB data structure.

**Comment by mludlum** [comment]
Thanks @mbdavid!

Summary:  New or removed fields are handled gracefully. Changing datatype of existing field can be converted in code by (e.g.) using db.Engine.UserVersion to track your db versions.  When renaming class fields, use BsonField attribute to differentiate between storage name and class field name.
