### ISSUE TITLE
Use the Array Index to Query for a Field in an Embedded Document

### ISSUE THREAD

**Issue by georglang** [mbdavid/LiteDB#594]
Hi,
is it possible with LiteDB to use an array index to query for a field in an embedded document?

In mongoDB, it´s possible to query just in all first objects of an array with "field.index."
`db.inventory.find( { 'instock.0.qty': { $lte: 20 } } )`

Thank you.

**Comment by mbdavid** [comment]
Hi @georglang, keys are not indexes with array position. So when you index a array field, all values are indexes as a multiple values only. If you want use indexed values you need use fixed position array with virtual indexes: Like here https://github.com/mbdavid/LiteDB/issues/530#issuecomment-286427325

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
