### ISSUE TITLE
Update without instance of the object

### ISSUE THREAD

**Issue by sandolkakos** [mbdavid/LiteDB#595]
Hi, first of all, thanks @mbdavid for creating and supporting LiteDB. I'm migrating my project from SQLite to LiteDB.

Is it possible to execute an Update in one field of each document of the Collection without have to get the list of objects to change the value and execute the update to persist it?

Something like that example using SQL:
```
UPDATE table_name SET status = 1;
```

**Comment by sandolkakos** [comment]
Hi @mbdavid, do you know if is there anyway to execute something like this?

**Comment by mbdavid** [comment]
Hi @sandolkakos, it´s not possible in nosql. You always need deserialize all object, change it, and serialize -> persist again. In a SQL database, tables are column fixed and it's possible read/write selected columns. But when you data is serialized, it´s not possible

**Comment by sandolkakos** [comment]
I understand. Thank you for the detailed explanations ;)
