### ISSUE TITLE
Request to make QueryVisitor public

### ISSUE THREAD

**Issue by ApolonTorq** [mbdavid/LiteDB#596]
I've just starting to use LiteDB and its been great. Thank's for creating an impressive open source embedded database library.

Would you consider making QueryVisitor public?
The reason I ask is that my existing object/entity class structure is easiest to map to directly from BsonDocument instances rather than via the inbuilt mapping functionality. Making QueryVisitor public would make it easier to create a totally custom entity mapping layer on top of LiteDB.

Thanks,
Apolon.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
