### ISSUE TITLE
Timeout. Database is locked for more than 00:00:00

### ISSUE THREAD

**Issue by podkolzzzin** [mbdavid/LiteDB#597]
We have received this exception from one of out users, so we can't exactly investigate it. Do you have any ideas why it could have happened? 

> Message: Timeout. Database is locked for more than 00:00:00.
> Source: LiteDB
> TargetSite: Void TryExec(System.Action, System.TimeSpan)
> HelpLink:
> Type: LiteDB.LiteException
> Place: 1
> Stack:
> at LiteDB.FileHelper.TryExec(Action action, TimeSpan timeout)
> at LiteDB.StreamExtensions.TryLock(FileStream stream, Int64 position, Int64 length, TimeSpan timeout)
> at LiteDB.FileDiskService.<ReadJournal>d__22.MoveNext()
> at LiteDB.TransactionService.Recovery()
> at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log)
> at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
> at LiteDB.LazyLoad`1.get_Value()
> at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
> at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
> at LiteDB.LiteCollection`1.FindById(BsonValue id)

**Comment by mcintyrg** [comment]
One thing I found working with LiteDB on multiple threads is that locks don't get released if you run a find query and don't use the enumerator to the end.

I.e. if you do something like

var iterator = m_Collection.Find(m_Query) and then just call

iterator,MoveNext();

without doing 

while (iterator.MoveNext())
{
}

in my case I only cared about one result so this can be worked round, which is how I stumbed into this gotcha

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
