### ISSUE TITLE
can't use IndexOptions in BsonIndex attribute

### ISSUE THREAD

**Issue by VoronFX** [mbdavid/LiteDB#60]
Hi! I am trying to set BsonIndex attribute with parameters, like in example but it seems that it's impossible. Compiler says "An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type".

Am I missing something obvious or this is wrong attribute implementation?

    public class Customer
    {
       public int Id { get; set; }

       [BsonIndex]
       public string Name { get; set; }

       // written below doesn't compiles 
       [BsonIndex(new IndexOptions { Unique = true, IgnoreCase = false, RemoveAccents = false })]
       public string Email { get; set; }
    }

**Comment by mbdavid** [comment]
Hi @VoronFX,thanks for find this bug. I fixed in master branch. Please, use:

```
   [BsonIndex(unique: true, ignoreCase: false, removeAccents: false)]
   public string Email { get; set; }
```

I will update nuget later.
