### ISSUE TITLE
Takes time in first run 

### ISSUE THREAD

**Issue by nkkin** [mbdavid/LiteDB#600]
I have tried realm database and it is very useful for me :
realm :
- you don't have to set a path or a database name (it is done for you) 
- Once you click insert if database is not created yet .. it is done so fast
what i hate about realm is the huge files they are using (dependencies)
LiteDb :
- what i like is : it is lightweight
- but the first run or database creation is very long (whyyyyyy)
-  why should we set a path and a name 

can you please fix that
i'm using it for xamarin android

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Comment by nkkin** [comment]
I forgot about it hhhh and u still use litedb and i've got some errors last
two days...  I've uninstalled monkey cache and problems started
