### ISSUE TITLE
EntityFramework Seeding equivalent

### ISSUE THREAD

**Issue by aletfa** [mbdavid/LiteDB#601]
Hello.
I need an event, a method registration or somethings equivalent to this
`void Seed(DBContext context)` a function responsible of the database initialization.
The function\event should be invoked only if the DB does not exists.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
