### ISSUE TITLE
BUG: LiteDatabase connection string filename can't contain multiple "." characters

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#602]
Trying to create a LiteDatabase instance with the filename "hello.world.ldb" fails with the following error when try to add data:

Message: LiteDB.LiteException : Invalid format: Collection

However, naming it "hello-world.ldb" works OK.

Period "." is a valid filename character. This should work.

**Comment by kuiperzone** [comment]
Damn! A name containing "~" fails also.

This is killing me! I need a separator character in my filenames and everything seems to fail.

The following are invalid under Windows, but other characters should be allowed:

< (less than)
> (greater than)
: (colon - sometimes works, but is actually NTFS Alternate Data Streams)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
All control codes (<= 31)

Question - does LiteDB allow Unicode filenames?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
