### ISSUE TITLE
Using LiteDb with a StorageFile UWP object

### ISSUE THREAD

**Issue by WattsC-90** [mbdavid/LiteDB#603]
I can now use LiteDb with the UWP platform for my RPi project.. yay, great work guys! 
I am trying to use an external hard drive on the PI (running windows IOT) in order to save my database on, (much better then 300GB drive than the 8GB SD). However, due to the permissions objects now used in Windows 10, I am struggling to open a database on the drive. I have been trying to use the `System.IO.Stream` constructor in order to make this happen. 

The only way that I can create a read/writeable stream with the StorageFile is to call OpenAsync:

```c#
var stream = storageProvider.StorageLocaton.OpenAsync(FileAccessMode.ReadWrite);
//where StorageLocation is a StorageFile
```

which returns a `IAsyncOperation<IRandomAccessStream>`

Also, I have looked into creating my own `DiskService`, but there is quite a bit of internal code that i would need to reference and I don't fancy copying a lot of code out just to implement an essential copy of StreamDiskService. Do you (David) or does anyone else have an idea of which way I should go here please?

**Comment by mbdavid** [comment]
Hi @WattsC-90, if you checks LiteDB v2.x PCL versions has an internal implementation of StrageFile. Take a look here:

https://github.com/mbdavid/LiteDB/blob/v2.0.4/LiteDB/Platform/FileHandlerWindowsStore.cs

If you want use windows store, try 2.0.4

**Comment by WattsC-90** [comment]
ahhh I see cool, I see what it is trying to do, I was trying to implement the wrong extension point ( I think..) I did post this question on StackOverflow and got the following code which may help someone too:

```c#
    var asyncRes = storageProvider.StorageLocaton.OpenAsync(FileAccessMode.ReadWrite);
    var randomAccessStream = asyncRes.GetResults();
    var stream = randomAccessStream.AsStream();
    _db = new LiteDatabase(stream);
```

Seems to have enabled the compile, but no chance testing yet, will report back when I can.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
