### ISSUE TITLE
DateTime rounding

### ISSUE THREAD

**Issue by galakt** [mbdavid/LiteDB#604]
#### Version Used: 
3.1.0.0

#### Steps to Reproduce:

Declare the following

```
    public class Customer
    {
        public int Id { get; set; }
        public DateTime Time { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new LiteDatabase(@"MyData.db"))
            {
                var customers = db.GetCollection<Customer>("customers");

                var customer = new Customer
                {
                    Id = 1,
                    Time = new DateTime(636304619445968076)
                };

                customers.Upsert(customer);

                var item = customers.FindOne(x => x.Id == 1);

                Console.WriteLine(item.Time == customer.Time);
                Console.WriteLine($"{customer.Time.Ticks} {customer.Time.ToUniversalTime().Ticks}");
                Console.WriteLine($"{item.Time.Ticks} {item.Time.ToUniversalTime().Ticks}");
                Console.ReadLine();
            }
        }
    }
```

#### Expected Behavior:

> True
>636304619445968076 636304619445968076 
>636304619445968076 636304619445968076 

#### Actual Behavior:

>False
>636304619445968076 636304871445968076
>636304619445970000 636304871445970000

#### Investigation

1) Look at 
    [BsonWriter](https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Document/Bson/BsonWriter.cs)
    [WriteElement](https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Document/Bson/BsonWriter.cs#L118)

    In `case BsonType.DateTime:`  
    we write `ts.TotalMilliseconds` (Double) to (Int64) and loose digits.
    > 1494890344596.8076 -> 1494890344597

2) Look at 
    [BsonReader](https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Document/Bson/BsonReader.cs)
    [ReadElement](https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Document/Bson/BsonReader.cs#L105)

    In `else if (type == 0x09) // DateTime` 
    we read (Int64) and then use AddMilliseconds(ts) that input parameter is (Double), but from AddMilliseconds documentation `Note that this value is rounded to the nearest integer.`

#### Solutions
1) That will be Breaking Change:
    Change 
    `writer.Write(Convert.ToInt64(ts.TotalMilliseconds));` to
    `writer.Write(Convert.ToInt64(ts.Ticks));`
    And
    `return BsonValue.UnixEpoch.AddMilliseconds(ts).ToLocalTime();` to
    `return BsonValue.UnixEpoch.AddTicks(ts).ToLocalTime();`

2) I am not familiar with LiteDB so i don't know how to fix it and do not break something

**Comment by galakt** [comment]
Yeah, it was done because of BSON spec =\ 
http://bsonspec.org/spec.html

Sad mismatch of precision

**Comment by galakt** [comment]
I added note about DateTime in wiki

**Comment by mbdavid** [comment]
Hi @galakt, sorry about this delay... yes, BSON round this by date. Thanks for your contrib 👍
