### ISSUE TITLE
How to select all derived

### ISSUE THREAD

**Issue by denis-ya** [mbdavid/LiteDB#605]
Is there any way to select only derived items from collection? I'm trying code below, but it does not work. As I can see it appends a property with "_type" name. Probably I should use this property?

```
class Base
{
    [BsonId]
    public int id { get; set; }
}

class Derived : Base
{
    public string foo { get; set;}
}

var fileName = @"c:\tmp\lite.db";

using(var db = new LiteRepository(fileName)) {
    db.Insert<Base>(new Base());
    db.Insert<Base>(new Derived { foo = "foo" });
}

using(var db = new LiteRepository(fileName)) {
    var d = db.Query<Base>()
        .Where(x => x.GetType() == typeof(Derived))
        .ToList();
}

```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
