### ISSUE TITLE
Problem On Wiki

### ISSUE THREAD

**Issue by aytacasan** [mbdavid/LiteDB#608]
Hello @mbdavid,

I think there is a problem on wiki. If you click -Changes from v1.0.x / v2.0.x- that under -Table of Content- section, directing to -Home Page- again. Also there is -Query- page under -Pages- section that completely empty page.

Regards,
Aytaç

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
