### ISSUE TITLE
3.2 prelease to Nuget?

### ISSUE THREAD

**Issue by FolkCoder** [mbdavid/LiteDB#609]
Is it possible to get a prerelease version pushed to NuGet? I'm considering adopting LiteDB but would like to test out the InsertBulk feature that was added back in March.

**Comment by mbdavid** [comment]
Hi @FolkCoder, next weekend I will review some code and fix some issues to release new version.

**Comment by FolkCoder** [comment]
Thank you, I appreciate it!

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
