### ISSUE TITLE
Overrideable Dispose() in LiteDatabase

### ISSUE THREAD

**Issue by RickRockhold** [mbdavid/LiteDB#610]
It would be great if LiteDatabase implemented the Dispose pattern (https://msdn.microsoft.com/en-us/library/b1yfkh5e(v=vs.110).aspx), most notably the "protected virtual void Dispose(bool)" method.

I'm implementing a subclass of LiteDatabase that creates the database using a temp file, and deletes the file on Dispose(). Without the overridable Dispose(), this gets uglier.

**Comment by mbdavid** [comment]
Hi @RickRockhold, I tried this time ago and had some problems and revert all. Take a look here:

https://github.com/mbdavid/LiteDB/commit/949ab4aa0c0bf634e6ff1a7156c8445aab6d353b

Maybe this microsoft version work better.

**Comment by RickRockhold** [comment]
What kind of problems? The only thing I see is if the object isn’t explicitly disposed and the finalizer kicks in, maybe the _dispose Action was already garbage collected.

Maybe a hybrid approach would be better—you could skip the finalizer, and still just provide an overridable Dispose(bool) method. This wouldn’t be functionally different from what you have now, and still supports inheritance.

Thanks,
Rick

**Comment by snalesso** [comment]
This might inspire you: [How to Implement IDisposable and Finalizers: 3 Easy Rules](https://blog.stephencleary.com/2009/08/how-to-implement-idisposable-and.html)

P.S. Check the left sidebar too

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
