### ISSUE TITLE
FileNotFoundException because of missing Journal

### ISSUE THREAD

**Issue by Bunhy** [mbdavid/LiteDB#611]
I have seen this issue fixed already here, but it occurs again with version 3.10. At least in my solution

I'm using the ConnectionString @"Filename=c:\test.db;Journal=true" (or just with filename, then jornal is by default true). Changing it to @"Filename=c:\test.db;Journal=false" and the exception disappears. And actually with Journal=true a -journal file isn't created and therefor missing.

Beside that Exception LiteDB is working fine, with Journal off or on. Geat Project by the way.

**Comment by mghiasi75** [comment]
I have the same issue too on the latest version available on NuGet, in an Xamarin.Android app.

**Comment by DerekSMorin** [comment]
I see the same issue, it seems to happen when I am trying to delete records.  I am saving to:  

string dbFile = Path.Combine( Path.GetTempPath(), "NUnitReflectionInfo.db" );

         using ( var db = new LiteDB.LiteDatabase( dbFile ) )
         {
            LiteCollection<NUnitTestDll> testDlls = db.GetCollection<NUnitTestDll>();
            testDlls.Delete( x => x.DllName == fullName );

**Comment by renyhp** [comment]
I am having the same issue. The journal file isn't created, and LiteDB tries to access it, resulting in FileNotFoundException being thrown.

**Comment by mbdavid** [comment]
Hi @renyhp, can you test in v4 beta? There is no more external journal file (journal now are made inside datafile)

**Comment by renyhp** [comment]
LiteDB v4 doesn't generate that exception anymore. Thanks! Looking forward to v4 being officially released... :)
