### ISSUE TITLE
Filtering by Linq, Ordering results by an index?

### ISSUE THREAD

**Issue by botne** [mbdavid/LiteDB#613]
Hi!

Thanks for great work on the LiteDB implementation.
I have used it some the last months. 
I read that you have no sorting operations - and I think I understand why.

I love to write filters based on Linq, and wonder if there is a possibility to use Linq queries and still order by index? 
I guess using  QueryVisitor directly and the append the ordering or adding an optional parameter to the Find with Linq filter?

I would love your thoughts on this!

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
