### ISSUE TITLE
Support IEnumerable<T> with DbRef

### ISSUE THREAD

**Issue by tomshane** [mbdavid/LiteDB#614]
I would like to be able to use `IEnumerable<T>` as a collection of referenced objects. `IList<T>` works fine, but it allows to add new items to the collection from the outside, which breaks the encapsulation on my domain object (DDD).

When` IEnumerable<T>` is used, `NullReferenceException` is thrown when inserting the document to the LiteDB's collection.

```
public class GearItem: Entity<GearItem>
{
  private List<GearGroup> groups = new List<GearGroup>();
  public IEnumerable<GearGroup> Groups { get => groups; private set => groups = value?.ToList(); }
}
```

**Comment by R74NN** [comment]
Do you think it is technically possible to support `IEnumerable<T>`?

**Comment by generik0** [comment]
IEnumerable and ICollection :-)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
