### ISSUE TITLE
Increasing the max of 16 indexes per collection

### ISSUE THREAD

**Issue by cardosso** [mbdavid/LiteDB#615]
Is there any technical reason for this restriction?
Because for collections with a large amount of fields that you want to dynamically filter you will hit this limit pretty easily, if this amount could be increased maybe to 32 it would make it very less likely to happen.

Right now this is my major hurdle with the library.

**Comment by cardosso** [comment]
Would it be possible to at least get some information about this limitation?

**Comment by mbdavid** [comment]
Hi @cardosso, 16 indexes are lots of index in a same colleciton. When you need add, remove or update any document database must delete/create all this indexes.

New v3.5 version support full scan search (non-index) but, when used in an AND operation, are much faster than use 2 (or more) indexes in same collection. Take a look on `dev` branch and read here #682  about this version

**Comment by cardosso** [comment]
Thanks for the reply, I understand that on a typical scenario 16 indexes might seem to be a lot, but in my case the overhead due to index creation isn't an issue since the data on those particular collections are basically static so it's read only.
MongoDB for instance allows a maximum of 64 indexes per collection which is a lot more reasonable number, 16 is just to low for many scenarios.

Is there any actual limitation that requires the amount of indexes to be set to 16 and not something higher? Just seems a bit strange to me that this limit is set to such a low value.

I've seen the v3.5 news even though I still have doubts about some of the breaking changes, full scan might definitely be interesting for some scenarios and I like the idea of reverting to it when no indexes are found, but on this particular case I'd rather still rely on indexes because the queries can be quite complex (mixing multiple AND and OR statements including nested documents) so I don't think full scans would be very efficient especially since the collections are rather large.

Essentially I'm trying to convert a system that was previously using mongoDB and make it completely portable for which LiteDB seems the perfect solution and this limitation is being my only roadblock, if the maximum index amount can't be higher I guess I will need to rethink on the migration.

**Comment by mbdavid** [comment]
Hi @cardosso, the major break api to 3.5 is about transaction that I removed after many problem with lock/concurrency. About index, it's removed auto create index on query. Now, indexes are created only by user.
All indexes in a collection are stored in a single page (CollectionPage). Current page size is fixed in 4046 bytes. This is a limitiation about how many data fit about indexes. It's possible add more indexs (like 24 or 32, I don't know yet, must have do some bytes calcs). For next major version I'm planning change page size to 8192 to have more space for this and others operations (like more collections).

**Comment by cardosso** [comment]
Does that mean that page size changes to 8192 the amount of maximum indexes will increase? If that's the case looking forward for the next version. A 24 or 32 index limit would certainly give a lot more flexibility than the current 16.
Thanks

**Comment by mbdavid** [comment]
Hi @cardosso. Today each index uses almost 77 bytes (at maximum, because field are string and can have different lengths). So, current 4096 bytes page can support 32 indexes. I will try update this in next version (3.5)

**Comment by JensSchadron** [comment]
The maximum index threshold has been increased to 32 in v5 (beta release soon). Therefor I'm closing the issue.
