### ISSUE TITLE
Why is the collection name limited to 30 charachters

### ISSUE THREAD

**Issue by j-hayes** [mbdavid/LiteDB#616]
``` csharp

    internal class CollectionPage : BasePage
    {
        /// <summary>
        /// Represent maximun bytes that all collections names can be used in header
        /// </summary>
        public const ushort MAX_COLLECTIONS_SIZE = 3000;

        public static Regex NamePattern = new Regex(@"^[\w-]{1,30}$");
.......
}
```

Why is this set to 30? could it be longer? Just a curiosity. I haven't run into a case where my class name might be 30 characters and be the same as something else, but still. Also would be helpful to add something to the error message saying what the max length is.

**Comment by mbdavid** [comment]
Hi @j-hayes, There is a limit in all collections names length, that is 3000 bytes (because it´s stored inside header page: each page are fixed in 4096 bytes). So I divide this into 30 chars each limit, so, at least, 100 collection could be used.

**Comment by j-hayes** [comment]
Thanks for the explanation! Loving litedb as a replacement for SQLite on an
iOS app I'm building right now.



Jh
