### ISSUE TITLE
Simple reference not working

### ISSUE THREAD

**Issue by juniorgasparotto** [mbdavid/LiteDB#617]
I'm trying to create a simple reference, but I'm not getting it. A **"customers"** collection is created successfully, but the **"ordes"** collection is not created.

What is wrong with this code?

```csharp
public static void Main()
{
            var mapper = BsonMapper.Global;
            mapper.Entity<Customer>()
                .DbRef(x => x.Order, "orders");

            using (var db = new LiteDatabase(@"MyData.db", mapper))
            {
                var col = db.GetCollection<Customer>("customers");

                var customer = new Customer
                {
                    Id = 1,
                    Name = "John Doe",
                    Phones = new string[] { "8000-0000", "9000-0000" },
                    Age = 39,
                    IsActive = true,
                    Order = new Order { Id = 1, Name = "My first order" }
                };
                col.Insert(customer);
            }
}
```

**Comment by NatriumDev** [comment]
I think there is nothing wrong. It just doesn't work that way.
You should first insert the order, then the customer.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
