### ISSUE TITLE
Exception about DataPage after power failure

### ISSUE THREAD

**Issue by lidanger** [mbdavid/LiteDB#619]
System ran stably for a week,then a power failure happened.When the program was restarted (for serval times), it reported an exception, and worked no logger.

OS version: Windows XP Professional SP3
.Net Framework version:4.0 full
LiteDB version:3.1.0
Threading model:Single instance

The callstack:

System.InvalidCastException: Unable to cast object of type 'LiteDB.DataPage' to type 'LiteDB.IndexPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc)
   at LiteDB.LiteEngine.<>c__DisplayClass61_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc)
   at LiteDB.LiteCollection`1.Insert(T document)

Can you give me some advice?

**Comment by mkosieradzki** [comment]
It was due to this bug: #574 (it's still not in a published version). Recovery might be very difficult if not impossible :-(. Maybe @mbdavid has some suggestions.

Basically journal file has been deleted BEFORE dirty pages had been synced to the physical medium.

**Comment by mkosieradzki** [comment]
Moreover even after fixing this on .NET < 4.5 this issue might still happen due to a buggy FlushAsync implementation.

**Comment by lidanger** [comment]
@mkosieradzki Yes,I think so.I have recreated the data file, but I ‘m afraid this will happen a few days later.

**Comment by lidanger** [comment]
@mkosieradzki @mbdavid 
Maybe the option FileOptions.WriteThrough can help though it will decrease performance.

according to 
https://stackoverflow.com/questions/4921498/whats-the-difference-between-filestream-flush-and-filestream-flushtrue

**Comment by mkosieradzki** [comment]
If you need this for .NET < 4.5 then probably the best idea would be to conditionally P/Invoke: `FlushFileBuffers` - https://msdn.microsoft.com/en-us/library/aa364439%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
in .NET 4.5 (netstandard 1.0)  it should be already fixed.

`WriteThrough` would be very painful performance-wise as it would basically sync after every page.

**Comment by lidanger** [comment]
Are you there? @mbdavid 

Just now I want to upgrade LiteDB from 3.1.4 to 4.0.0,so I test something.But it seems problem remains in the version 4.

I start 20 threads for write per second, 10 threads for query per second and 10 threads for delete per second.

1、using Journal option in connection string as:Journal=true;

When the program runs for several minutes, I power off the virtual machine.Then,I power it on and start the program again.It may lock data file untile timeout before anything can be done.

While, sometimes, it may give an exception:

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data)
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at TestLiteDB.Program.QueryThread()

2、using Journal option in connection string as:Journal=false;

When the virutal machine is power on and the program is restarted, it may give an exception:

System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.IndexPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass20_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at TestLiteDB.Program.AddThread()

It seems this will happen only when the datafile is larger than 100K.

3、When I copy the collection of corrupted datafile to another file, an exception comes.

System.Collections.Generic.KeyNotFoundException: 给定关键字不在字典中。
   在 System.ThrowHelper.ThrowKeyNotFoundException()
   在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   在 LiteDB.IndexService.<FindAll>d__13.MoveNext()
   在 LiteDB.LinqExtensions.<>c__DisplayClass2_0`2.<<DistinctBy>g___0>d.MoveNext()
   在 LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data)
   在 LiteDB.LiteEngine.<Find>d__9.MoveNext()
   在 LiteDB.LiteEngine.<Find>d__13.MoveNext()
   在 LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   在 LiteDB.LiteCollection`1.<GetBsonDocs>d__35.MoveNext()
   在 LiteDB.LinqExtensions.<Batch>d__0`1.MoveNext()
   在 LiteDB.LiteEngine.InsertBulk(String collection, IEnumerable`1 docs, Int32 batchSize, BsonType autoId)
   在 LiteDB.LiteCollection`1.InsertBulk(IEnumerable`1 docs, Int32 batchSize)
   在 TestLiteDB.Program.CopyTo()

**Comment by lidanger** [comment]
LiteDB version:4.0.0
.NET Framework version:4.0 full
OS version:Windows XP Professional SP3
The test code:

using LiteDB;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;

namespace TestLiteDB
{
    class TestItem
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
        public string Description { get; set; }

        public TestItem()
        {
            Id = Guid.NewGuid().ToString("N");
        }
    }

    class Program
    {
        static string connStr = "filename=lt.db;Journal=true;";

        static void Main(string[] args)
        {
            AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;

            Environment.CurrentDirectory = AppDomain.CurrentDomain.BaseDirectory;
            log4net.Config.XmlConfigurator.Configure(new System.IO.FileInfo("log4net.config"));

            //using (var conn = new LiteDB.LiteDatabase("lt.db"))
            //{
            //    var col = conn.GetCollection<TestItem>();
            //    col.EnsureIndex(item => item.Name);
            //    col.EnsureIndex(item => item.Value);
            //}

            //for (int i = 0; i < 20; i++)
            //{
            //    var thread = new Thread(AddThread);
            //    thread.IsBackground = true;
            //    thread.Start();
            //}

            //for (int i = 0; i < 10; i++)
            //{
            //    var thread = new Thread(QueryThread);
            //    thread.IsBackground = true;
            //    thread.Start();
            //}

            //for (int i = 0; i < 10; i++)
            //{
            //    var thread = new Thread(DeleteThread);
            //    thread.IsBackground = true;
            //    thread.Start();
            //}

            CopyTo();

            Console.ReadLine();
        }

        private static void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            System.IO.File.AppendAllText("error.log", string.Format("[0] {1}\r\n", e.ExceptionObject));
        }

        private static void CopyTo()
        {
            var logger = log4net.LogManager.GetLogger("备份");

            try
            {
                using (var conn2 = new LiteDatabase("lt2.db"))
                using (var conn = new LiteDB.LiteDatabase(connStr))
                {
                    var cols = conn.GetCollectionNames();
                    foreach (var col in cols)
                    {
                        conn2.GetCollection(col).InsertBulk(conn.GetCollection(col).FindAll());
                    }
                }
            }
            catch (Exception ex)
            {
                logger.DebugFormat("复制异常{0}", ex);
            }

            //try
            //{
            //    using (var conn = new LiteDatabase("lt2.db"))
            //    {
            //        var cols = conn.GetCollectionNames();
            //        foreach (var col in cols)
            //        {
            //            var items = conn.GetCollection(col).FindAll();
            //            foreach (var item in items)
            //            {
            //                Console.WriteLine("名称：{0} 数值：{1} 说明：{2}", item["Name"], item["Value"], item["Description"]);
            //            }
            //        }
            //    }
            //}
            //catch (Exception ex)
            //{
            //    logger.DebugFormat("查询异常{0}", ex);
            //}

            try
            {
                using (var conn = new LiteDatabase("lt2.db"))
                {
                    var col = conn.GetCollection<TestItem>();
                    var items = col.FindAll();
                    foreach (var item in items)
                    {
                        Console.WriteLine("名称：{0} 数值：{1} 说明：{2}", item.Name, item.Value, item.Description);
                    }
                }
            }
            catch (Exception ex)
            {
                logger.DebugFormat("查询异常{0}", ex);
            }
        }

        private static void AddThread()
        {
            var rand = new Random(DateTime.Now.Millisecond);
            var logger = log4net.LogManager.GetLogger("添加");

            logger.Info("添加线程启动");

            while (true)
            {
                try
                {
                    using (var conn = new LiteDB.LiteDatabase(connStr))
                    {
                        var col = conn.GetCollection<TestItem>();
                        col.Insert(new TestItem
                        {
                            Name = "fdsfdsf",
                            Description = "dsfsdf",
                            Value = rand.Next()
                        });
                    }
                }
                catch (Exception ex)
                {
                    logger.DebugFormat("添加异常{0}", ex);
                }

                Thread.Sleep(1000);
            }
        }

        private static void QueryThread()
        {
            var rand = new Random(DateTime.Now.Millisecond);
            var logger = log4net.LogManager.GetLogger("查询");

            logger.Info("查询线程启动");

            while (true)
            {
                var lst = new List<TestItem>();

                try
                {
                    using (var conn = new LiteDB.LiteDatabase(connStr))
                    {
                        var col = conn.GetCollection<TestItem>();
                        var items = col.Find(Query.GT("Value", rand.Next()));
                        lst.AddRange(items);
                    }
                }
                catch (Exception ex)
                {
                    logger.DebugFormat("查询异常{0}", ex);
                }

                foreach (var item in lst)
                {
                    Console.WriteLine("名称：{0} 数值：{1} 说明：{2}", item.Name, item.Value, item.Description);
                }

                Thread.Sleep(1000);
            }
        }

        private static void DeleteThread()
        {
            var rand = new Random(DateTime.Now.Millisecond);
            var logger = log4net.LogManager.GetLogger("删除");

            logger.Info("删除线程启动");

            while (true)
            {
                try
                {
                    using (var conn = new LiteDB.LiteDatabase(connStr))
                    {
                        var col = conn.GetCollection<TestItem>();
                        col.Delete(Query.Between("Value", rand.Next(), rand.Next()));
                    }
                }
                catch (Exception ex)
                {
                    logger.DebugFormat("删除异常{0}", ex);
                }

                Thread.Sleep(1000);
            }
        }
    }
}

**Comment by lidanger** [comment]
4.test with writethrough option
In this case,I modified the source code of LiteDB:
        private FileStream CreateFileStream(string path, System.IO.FileMode mode, FileAccess access, FileShare share)
        {
#if HAVE_SYNC_OVER_ASYNC
            if (_options.Async)
            {
                return System.Threading.Tasks.Task.Run(() => new FileStream(path, mode, access, share, BasePage.PAGE_SIZE))
                    .ConfigureAwait(false)
                    .GetAwaiter()
                    .GetResult();
            }
#endif

#if NET35||NET40
            return new FileStream(path, mode, access, share,
                BasePage.PAGE_SIZE,
                System.IO.FileOptions.RandomAccess | System.IO.FileOptions.WriteThrough);
#else
            return new FileStream(path, mode, access, share,
                BasePage.PAGE_SIZE,
                System.IO.FileOptions.RandomAccess);

#endif
        }

a.Journal=true
With 6 times of power off the vitrual machine, there is no other exception except timeout.

b.Journal=false
It seems write operation is much fast and file size do't change high and low.

When the datafile size is larger than 100K, I power off and restart, there is an exception:
System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.TransactionService.PersistDirtyPages()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonType autoId)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at TestLiteDB.Program.AddThread()

And, if I use Journal=false first until filesize is 100k,then change to Journal=true, sometimes there is also an exception:
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LiteDB.IndexService.GetNode(PageAddress address)
   at LiteDB.IndexService.<GetNodeList>d__8.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at LiteDB.LiteEngine.<>c__DisplayClass8_0.<Delete>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Delete(String collection, Query query)
   at LiteDB.LiteCollection`1.Delete(Query query)
   at TestLiteDB.Program.DeleteThread()

That's all.In the end, it seems combine System.IO.FileOptions.WriteThrough and Journal=true will be OK.I don't know why, but I think it's a good solution for now.

**Comment by mbdavid** [comment]
Hi @lidanger!! Thanks for this great tests. I will reproduce here.

Well, test power-off with journal=false will always corrupt database. And about WriteThrough option, I will reproduce if is necessary in other operation systems, like windows 7/8/10. Are you using NTFS or FAT32?

**Comment by lidanger** [comment]
NTFS, of course. 
@mbdavid

**Comment by lidanger** [comment]
Strange.On Windows 7,everything is OK.

**Comment by mbdavid** [comment]
humm... in this case, can be possible checks if OS is XP and set WriteThrough only in this case.

Theoretically, don't need use WriteThrough because NTFS handle journal segment in page level.
