### ISSUE TITLE
Question: LiteDB as Queue system

### ISSUE THREAD

**Issue by ldubrois** [mbdavid/LiteDB#620]
Hello,

First, thanks for your product. It changed our life :-)

Our solution is based on one small windows service deployed on one server of our clients.
We already changed our SQL Database (SQL Server Express) by LiteDB to simplify our deployment.
But we still have a dependency on a queue system (RabbitMQ).

We would like to remove also this dependency to simplify our deployment procedure.

I searched a LiteDB like product to handle our queues, and I did not found one.

Do you think in a way to handle efficiently our queues in LiteDB (insert, peek, delete) in a FIFO order ?

Thanks

**Comment by mbdavid** [comment]
Hi @ldubrois. thanks!! I never work with external queue system (like RabbitMQ). I always prefer my home-made implementaion (of course, always for a simple needs). I didn't know any queue system for litedb, sorry. But if you found some interesting, tell me to add in readme page;

Regards

**Comment by ROMAN5** [comment]
Hello...what about ConcurrentQueue - it represents a thread-safe FIFO collection?

**Comment by ldubrois** [comment]
Hi,

thanks for your anwsers. 

@ROMAN5 : I need it to be persistent and stored on disk. 

@mbdavid : Today we are using LiteBD to a store a few informations in it (like 1 to 10 Mo). If we try to use LiteDB as a store for the pending/failed items it will have to store in a worse case scenario about 5 Go and 400 000 items in 2 collections.
Do you think it will be reliable to use LiteDB for it ?

Thanks for your help.

**Comment by nvivo** [comment]
@ldubrois Maybe you already sorted this out, but I'm leaving as a tip for someone else.

I'm looking for LiteDb as the backend for a persistent local queue in a service. From what I have tested, this looks perfectly doable.

1. Create your queue item with a `public ObjectId Id {get;set; } ` property, so the records are sorted by insert order and you have access to a unique id to delete later
2. do a `var item = col.FindOne(x => true)` to get the first item from the collection
3. do a `col.Delete(x => x.ID = item.ID)` to remove from the queue

I'm not sure if LiteDb transactions will isolate reads, so you could do 2 and 3 in an atomic operation on multi-threaded scenarios. But you can easily control access from a single point in the kind of applications that will use LiteDb.

If there is a better way of doing it, please let me know.

**Comment by ldubrois** [comment]
HI @nvivo 

I've made some tests on several multi-threaded scenarios to view how LiteDB will perform.

I've defined a model to try to ensure an item will not be peek twice and in case of failure (crash, power failure, ...) the item will be available again.

I've encountered strange behaviors in term of performance.

On many cases, the perf is good : 

![image](https://user-images.githubusercontent.com/20680042/26977844-9294ae3e-4d29-11e7-983d-7e775b6890cd.png)

But sometimes, it does not. I did found out why :

![image](https://user-images.githubusercontent.com/20680042/26977681-09236e88-4d29-11e7-81ca-8b87321ec2a5.png)

**Comment by nvivo** [comment]
@ldubrois is this local to your dev machine or some cloud provider?

**Comment by ldubrois** [comment]
@nvivo it was on my desktop (16Go RAM + SSD)

**Comment by nvivo** [comment]
That's strange. Well, my requirements are not for so many records, only a few per second, but I'll control the inserts with Akka.NET, so there is no concurrency and you can always batch insert even if I receive individual records. Maybe that could help you.

But it's strange that different runs produce so much difference. Did you do only two tests or more? Without more details, that looks like external interference like anti virus ou windows update can severely  decrease disk performance when it decides to run at random. Since LiteDb must write to disk each commit, any IO would impact these tests.

**Comment by ldubrois** [comment]
I've run multiple tests with different injection settings. In some cases this strange beahviors occurs, and sometimes not.
I'm actually doing more tests to check wether LiteDB will support a major failure causing a large queue size (about 4000000 items) and check how it will behave.

I let you known when I'll have some results.

**Comment by nbushby** [comment]
I'm late to this party, but had similar requirements to create a queue that could substitute for MSMQ on .NET Core. LiteDB worked great for the storage mechanism, so I called it LiteQueue:
https://github.com/NomadeonSoftwareLLC/LiteQueue

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
