### ISSUE TITLE
How to update data file from v2.0.0-rc to v 3.1

### ISSUE THREAD

**Issue by vasiliy-vdovichenko** [mbdavid/LiteDB#621]
First of all thank you for this project, I think it currently the best embedded document db for .net.

I am currently using v2.0.0-rc in desktop application and want to upgrade to the last version.
But as it turned out v2.0.0-rc is not supported for automatic upgrade -  it just throws exception that db version 5 is unknown.

So I was wondering is there any other way to upgrade data file on application start (as application uses autoupdate - it downloads its last version from web).
I think about serializing collection to json and then load them to new data file, 
but I am not sure how to reference and use v2.0.0-rc and v3.1 in the same application so that serialize data in v2.0.0-rc and then recreate db and load this data.

Could you please point me to direction how to do this update.

Thank you

**Comment by mrkmg** [comment]
This is possible to do. Check this StackOverflow Entry on the topic.

https://stackoverflow.com/questions/42715564/using-2-different-versions-of-the-same-dll

**Comment by maxstoll** [comment]
could you add the upgrade from 5 to 7 in the upgradecode?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
