### ISSUE TITLE
DateTimeOffset: TZ Offset is reset to +00:00 when inserting

### ISSUE THREAD

**Issue by cemremengu** [mbdavid/LiteDB#622]
When inserting, the offset is OK, however when retrieving the document, it's resetting to +00:00

Property

```
public DateTimeOffset CreatedOn { get; set; }
```

Insert
```
user.CreatedOn = DateTimeOffset.Now; // 5/30/2017 6:05:21 PM +03:00

col.Insert(user);
col.EnsureIndex(x => x.Username);
````

Find:
```
using (var db = _liteDbConnection.Create() as LiteDatabase)
{
	var col = db.GetCollection<AuthUser>(USERS_COLLECTION);

	return col.FindOne(x => x.UserId == userId);
}
```
`user.CreatedOn` becomes
`5/30/2017 6:05:21 PM +00:00`

Am I doing something wrong ?

**Comment by galakt** [comment]
Like #604 
Because of internal use of BSON 'DateTime' and 'DateTimeOffset' are not fully supported.

Workarounds not so good: convert to different types on insert and convert back on retrieve.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
