### ISSUE TITLE
Solution for using nested references within arrays

### ISSUE THREAD

**Issue by janvdpol** [mbdavid/LiteDB#623]
Hi,

Within my solution I needed to query and the result should have some nested arrays with documents with arrays, etc. I know this is not the best design, but first I would like to convert my existing relational database to LiteDb and I'm going to optimize aftwerwards.

Unfortunatly LiteDb only supports one level of nesting when arrays are involved. After a close look at the source code, I came up with a solution which works for my case and might help others, although there might be a more performing solution.

So here is my new Include.cs file:
`using System;
using System.Linq;
using System.Linq.Expressions;

namespace LiteDB
{
    public partial class LiteCollection<T>
    {
        /// <summary>
        /// Run an include action in each document returned by Find(), FindById(), FindOne() and All() methods to load DbRef documents
        /// Returns a new Collection with this action included
        /// </summary>
        public LiteCollection<T> Include<K>(Expression<Func<T, K>> dbref)
        {
            if (dbref == null) throw new ArgumentNullException("dbref");

            var path = _visitor.GetField(dbref);

            return this.Include(path);
        }

        /// <summary>
        /// Run an include action in each document returned by Find(), FindById(), FindOne() and All() methods to load DbRef documents
        /// Returns a new Collection with this action included
        /// </summary>
        public LiteCollection<T> Include(string path)
        {
            if (string.IsNullOrEmpty(path)) throw new ArgumentNullException("path");

            Action<BsonDocument> action = bson => ResolveReferences(bson, path.Split('.'), 0);

            // cloning this collection and adding this include
            var newcol = new LiteCollection<T>(_name, _engine, _mapper, _log);

            newcol._includes.AddRange(_includes);
            newcol._includes.Add(action);

            return newcol;
        }

        /// <summary>
        /// Recursive method for resolving nested DbRef documents.
        /// </summary>
        private void ResolveReferences(BsonDocument bson, string[] pathSegments, int segmentIndex)
        {
            var path = pathSegments[segmentIndex];
            var value = bson[path];

            if (value.IsNull) return;

            // if property value is an array, populate all values
            if (value.IsArray)
            {
                var array = value.AsArray;
                if (array.Count == 0) return;

                if (pathSegments.Length == segmentIndex + 1)
                {
                    var docs = array.ToArray();
                    array.Clear();
                    foreach (var doc in docs)
                    {
                        var colRef = doc.AsDocument["$ref"];
                        var colId = doc.AsDocument["$id"];

                        if (pathSegments.Length == segmentIndex + 1 && (!colRef.IsString || colId.IsNull))
                        {
                            throw LiteException.InvalidDbRef(CreateInvalidPathMessage(pathSegments, segmentIndex));
                        }

                        var obj = _engine.Value.Find(colRef, Query.EQ("_id", colId)).FirstOrDefault();

                        // include only object that exists in external ref
                        if (obj != null)
                        {
                            array.Add(obj);
                        }
                    }
                }
                else
                {
                    foreach (var doc in array)
                    {
                        ResolveReferences(doc.AsDocument, pathSegments, segmentIndex + 1);
                    }
                }
            }
            else if (value.IsDocument)
            {
                // for BsonDocument, get property value update with full object reference
                var doc = value.AsDocument;

                if(pathSegments.Length == segmentIndex + 1 )
                {
                    var colRef = doc["$ref"];
                    var colId = doc["$id"];

                    if (!colRef.IsString || colId.IsNull)
                    {
                        throw LiteException.InvalidDbRef(CreateInvalidPathMessage(pathSegments, segmentIndex));
                    }

                    var obj = _engine.Value.Find(colRef, Query.EQ("_id", colId)).FirstOrDefault();

                    bson.Set(path, obj);
                }
                else
                {
                    ResolveReferences(doc, pathSegments, segmentIndex + 1);
                }
            }
            else
            {
                throw LiteException.InvalidDbRef(path);
            }
        }

        private static string CreateInvalidPathMessage(string[] names, int depth)
        {
            return string.Format("{0} property ('{1}') could not be resolved in path '{2}'",
                depth, names[depth], string.Join(".", names));
        }
    }
}`

And here is the new IncludeTest.cs:
`using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using LiteDB;

namespace LiteDB.Tests
{
    public class Order
    {
        public ObjectId Id { get; set; }
        public Customer Customer { get; set; }
        public Customer CustomerNull { get; set; }

        public List<Product> Products { get; set; }
        public Product[] ProductArray { get; set; }
        public ICollection<Product> ProductColl { get; set; }
        public List<Product> ProductEmpty { get; set; }
        public List<Product> ProductsNull { get; set; }
    }

    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Address MainAddress { get; set; }
    }

    public class Address
    {
        public int Id { get; set; }
        public string StreetName { get; set; }
    }

    public class Product
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public Address SupplierAddress { get; set; }
    }

    [TestClass]
    public class IncludeTest
    {
        [TestMethod]
        public void Include_Test()
        {
            var mapper = new BsonMapper();

            mapper.Entity<Order>()
                .DbRef(x => x.Products, "products")
                .DbRef(x => x.ProductArray, "products")
                .DbRef(x => x.ProductColl, "products")
                .DbRef(x => x.ProductEmpty, "products")
                .DbRef(x => x.ProductsNull, "products")
                .DbRef(x => x.Customer, "customers")
                .DbRef(x => x.CustomerNull, "customers");

            mapper.Entity<Customer>()
                .DbRef(x => x.MainAddress, "addresses");

            mapper.Entity<Product>()
                .DbRef(x => x.SupplierAddress, "addresses");

            using (var file = new TempFile())
            using (var db = new LiteDatabase(file.Filename, mapper))
            {
                var address = new Address {StreetName = "3600 S Las Vegas Blvd"};
                var customer = new Customer {Name = "John Doe", MainAddress = address};

                var product1 = new Product {Name = "TV", Price = 800, SupplierAddress = address};
                var product2 = new Product {Name = "DVD", Price = 200};

                var customers = db.GetCollection<Customer>("customers");
                var addresses = db.GetCollection<Address>("addresses");
                var products = db.GetCollection<Product>("products");
                var orders = db.GetCollection<Order>("orders");

                // insert ref documents
                addresses.Insert(address);
                customers.Insert(customer);
                products.Insert(new Product[] {product1, product2});

                var order = new Order
                {
                    Customer = customer,
                    CustomerNull = null,
                    Products = new List<Product>() {product1, product2},
                    ProductArray = new Product[] {product1},
                    ProductColl = new List<Product>() {product2},
                    ProductEmpty = new List<Product>(),
                    ProductsNull = null
                };

                orders.Insert(order);

                //var r0 = orders
                //    .Include(x => x.Products)
                //    .Include(x => x.Products[0].SupplierAddress)
                //    .FindAll()
                //    .FirstOrDefault();

                orders.EnsureIndex(x => x.Customer.Id);

                // query orders using customer $id
                // include customer data and customer address
                var r1 = orders
                    .Include(x => x.Customer)
                    .Include(x => x.Customer.MainAddress)
                    .Find(x => x.Customer.Id == 1)
                    .FirstOrDefault();

                Assert.AreEqual(order.Id, r1.Id);
                Assert.AreEqual(order.Customer.Name, r1.Customer.Name);
                Assert.AreEqual(order.Customer.MainAddress.StreetName, r1.Customer.MainAddress.StreetName);

                // include all 
                var result = orders
                    .Include(x => x.Customer)
                    .Include("Customer.MainAddress")
                    .Include(x => x.CustomerNull)
                    .Include(x => x.Products)
                    .Include(x => x.ProductArray)
                    .Include(x => x.ProductColl)
                    .Include(x => x.ProductsNull)
                    // Test for nested reference resolving
                    .Include(x => x.Products[0].SupplierAddress)
                    .FindAll()
                    .FirstOrDefault();

                Assert.AreEqual(customer.Name, result.Customer.Name);
                Assert.AreEqual(customer.MainAddress.StreetName, result.Customer.MainAddress.StreetName);
                Assert.AreEqual(result.Products.Count, 2);
                Assert.AreEqual(product1.Price, result.Products[0].Price);
                Assert.AreEqual(product2.Name, result.Products[1].Name);
                Assert.AreEqual(product1.Name, result.ProductArray[0].Name);
                Assert.AreEqual(product2.Price, result.ProductColl.ElementAt(0).Price);
                Assert.AreEqual(null, result.ProductsNull);
                Assert.AreEqual(0, result.ProductEmpty.Count);

                // Check on nested references
                Assert.AreEqual(product1.SupplierAddress.StreetName, result.Products.First().SupplierAddress.StreetName);
                Assert.AreEqual(null, result.Products[1].SupplierAddress);
            }
       }
    }
}`

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
