### ISSUE TITLE
Request for method Drop

### ISSUE THREAD

**Issue by podkolzzzin** [mbdavid/LiteDB#624]
There is a case in my project, when  I have to delete database completely including main db file and it's journal, if it exists. I implemented this logic on my side, but it would be really useful to have such a method in LiteDatabase class.

**Comment by mikaelssen** [comment]
Really thought 
`var col = liteDB.GetCollection<SolarSystem>("systems");
			col.DropIndex("systems");
`
Would do it.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
