### ISSUE TITLE
LiteDB FileStore 3.1 has huge performance slowdown.

### ISSUE THREAD

**Issue by vedun-z** [mbdavid/LiteDB#625]
I found out that FileStore in current (3.1) nuget version of LiteDB has a huge performance problem. I try to add 70 00 files to FileStore. I use SHA2 hash of a file content as a key.  Average file size is 5000 bytes. To add a file to the database I use the following code:
```
ldb.FileStorage.Upload(new string(key), null, new MemoryStream(array));
```
The first thousand files were added to the database in less than a second. However, after 20,000 adding operations, adding thousands of files took 40 seconds! If you need, I can provide a sample that reproduces this behavior. 

Btw, LiteDB 2.0.4 works fine. It always stores thousand files for a couple of seconds.

**Comment by hglee** [comment]
In my case, bottleneck was **LiteStorage.FindById** in **LiteStorage.Upload**.

If you try to upload a file in locking condition, it spends time on **LiteStorage.FindById**.

For example, **FindById** (actually ReaderWriterLockSlim.WaitOnEvent) tooks about 28% time  in multiple thread insert & upload case.

![image](https://user-images.githubusercontent.com/427595/27317803-d7e9c06c-55c3-11e7-96f0-91f097641b10.png)

**Comment by vedun-z** [comment]
@hglee  I have a different issue. 
![image](https://user-images.githubusercontent.com/1244051/27376509-10e28270-567b-11e7-9db6-1832c333f1b6.png)

It looks like ReadPage allocates too many small buffers and the slowdown is caused by garbage collection.

**Comment by mkosieradzki** [comment]
It would be definitely a good idea to use buffer pooling from System.Buffers.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
