### ISSUE TITLE
README: Answers and Updates about LiteDB

### ISSUE THREAD

**Issue by mbdavid** [mbdavid/LiteDB#626]
Hello everyone,

As you can see, I have been having trouble answering the questions here at Github, in addition to checking and correcting bugs found in the project.

I am in the middle of a great project in my work and I do not have the time to dedicate myself to this project as I would like. Answering questions requires a lot of attention and an immersion in the context of the sources, and all this requires a time that unfortunately I do not have now.

The project will stand still for a while until things improve. I want to resume with a new version with improvements and corrections in the main problems pointed out here in the issues. I still have no deadline for this, but will be informed here.

Thanks so much to all the users and your collaboration.

Best Regards,

Maurício David

**Comment by mkosieradzki** [comment]
@mbdavid Thanks for clearing this up!

However is there any chance you will release 3.2 soon? I would really like to have an official package with my PR merged (with fixed power-off handling).

**Comment by mbdavid** [comment]
Hi @mkosieradzki, if master branch are running my unit test, I can publish tonight as 3.2

**Comment by mbdavid** [comment]
Hi @mkosieradzki, done. But I publish as 3.1.1 because are only bugfixes from 3.1.

**Comment by mkosieradzki** [comment]
@mbdavid Thank you so much!

**Comment by raizam** [comment]
Hi, 
I'm starting out a project, I was planning to use LiteDB, but I feel a bit worried now.
Is LiteDB stable, production ready?

**Comment by raizam** [comment]
Ok I got it. I'll go with Sqlite + Dapper then. 
This project is nice, but too uncertain  :game_die: :game_die: :game_die:

**Comment by tcsaddul** [comment]
Try hhblaze/DBreeze

  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
hhblaze/DBreeze
 DBreeze - C# .NET MONO NOSQL ( key value store embedded ) ACID multi-paradigm database management system.  |   |

  |

  |

 

Just prepare your own JSON serializer (I use Jil). It's rock solid. 

    On Monday, June 12, 2017 3:15 AM, raizam <notifications@github.com> wrote:
 

 Ok I got it. I'll go with Sqlite + Dapper then.
This project is nice, but too uncertain 🎲 🎲 🎲 —
