### ISSUE TITLE
Sharing violation on path 

### ISSUE THREAD

**Issue by dfarrNTST** [mbdavid/LiteDB#628]
We are having an issue working with LiteDb with Xamarin Forms.  We get the error "Sharing violation on path databasename.db" very often.  Below are some details on how we are using it:

Version: 3.1.1
ConnectionString when running on Android:

`ConnectionString = $"Filename=/data/user/0/AppName.Android/files/databaseName.db;Password=aPassword;";`

We've tried this with and without Journal=false;

We interact with the repo with commands similar to the following:

```
using (var repo = new LiteRepository(localDataStorageBag.ConnectionString))
{
    var collection = repo.Database.GetCollection<AppointmentSummary>();
    collection.Insert(data);
}

```

and

```
using (var repo = new LiteRepository(localDataStorageBag.ConnectionString))
            {
                try
                {
                    var collection = repo.Database.GetCollection<AppointmentSummary>();
                    if (!string.IsNullOrWhiteSpace(inputPayload?.AppointmentDateRange?.FromDate) && !string.IsNullOrWhiteSpace(inputPayload?.AppointmentDateRange?.ToDate))
                    {
                        returnValue.SearchResults = collection.Find(w => DateTimeOffset.Parse(w.StartDate) >= DateTimeOffset.Parse(inputPayload.AppointmentDateRange.FromDate) &&
                                                                         DateTimeOffset.Parse(w.StartDate) <= DateTimeOffset.Parse(inputPayload.AppointmentDateRange.ToDate))
                                                              .OrderBy(o => o.ClientName.Last)
                                                              .ThenBy(tb => tb.ClientName.First)
                                                              .ToList();
                    }
                    else
                    {
                        var results = collection.Find(w => true)
                                                .OrderBy(o => o.ClientName.Last)
                                                .ThenBy(tb => tb.ClientName.First)
                                                .ToList();


                        returnValue.SearchResults = results;
                    }
                }
                catch (Exception ex)
                {
                    ex.HandleException(this);
                }
```

We used to surround everything with BeginTrans/Commit...but based on a another issue we saw here we took those out, but still getting the same error.  We've uninstalled the app, ensuring the database was recreated from scratch, and still get the error.

Can you think of something we are doing wrong or should be doing differently?  We do intend on access the database with multiple threads on mobile devices with Xamarin Forms.

I know you are busy with another project, but this will fully impact our ability to use LiteDb for our app...and we really like it so far.

**Comment by Xiaoliangzhang** [comment]
Hi @dfarrNTST. I had the same issue with Xamarin. I got it fixed by using a singleton pattern. The singleton return the same LiteRepository instance for the entire application.

**Comment by dfarrNTST** [comment]
Thanks X.  Doing that as well as removing transactions around every action resolved it for us as well.  Thanks!
