### ISSUE TITLE
Good for logging?

### ISSUE THREAD

**Issue by stefandevo** [mbdavid/LiteDB#633]
Hi I am currently looking for an embedded solution for logging; more specific, it would need to handle the logs of incoming mobile text messages (sms) in a Callback scenario. So whenever a person sends a message to our virtual number a post is made to an url. What then happens is further business logic, but I want to save the callback info (json object) into LiteDB. So it's insert only, and the read operations are more for diagnostics. "give me all messages between date x and date y for incoming number z". So I would need to add some indexes on number, date, etc.
So the data will only grow over time, maybe a million records per year.
Would LiteDB a good solution for this? Or should I create different tables per month for example?
Thanks for your advice!

**Comment by stefandevo** [comment]
Hi thanks for this. I just was a bit affraid of the "Few concurrent write operations" on the readme file. For logging of course they are all appends, no updates, so maybe that would OK then?

**Comment by ti24horas** [comment]
@stefandevo please take a look at serilog.sinks.litedb.
It uses a batch flushing mechanism.
I'd also sent a pull request to allow file rotation based on hour, minutes and days.

Right now, I'm looking if is feasible to create a Seq Like web app to embed in existing application.
Currently a blocker on my project is #711 as to be able to find/sort I need a number to filter and I should use Date.ToFileTime().

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
