### ISSUE TITLE
BsonValue implicit conversions not working as expected

### ISSUE THREAD

**Issue by gpauls** [mbdavid/LiteDB#634]
Consider following scenario:

`
[TestClass]
    public class NotNullTests
    {
        [TestMethod]
        public void Test()
        {
            var test1 = Test1();
            var test2 = Test2();
            var test3 = Test3();

            Assert.IsNull(test1);
            Assert.IsNull(test2);
            Assert.IsNull(test3);
        }

        public string Test1()
        {
            var document = GetDocument();
            if (document != null)
            {
                return document["token"];
            }
            else
            {
                return null;
            }
        }

        public string Test2()
        {
            var document = GetDocument();
            return document != null ? document["token"] : null;
        }

        public string Test3()
        {
            var document = GetDocument();
            return document?["token"];
        }

        private BsonDocument GetDocument()
        {
            return null;
        }
    }`

All these 3 tests do the same. They check if the document is null and return null or a token.
The problem is 2 & 3 throw a null exception.

That's quite strange at first, but actually makes sense if we check why.
`return document != null ? document["token"] : null`
actually gets translated to something like this:
`return (string) (document != null ? (BsonDocument)document["token"] : (BsonDocument)null)`

So as we see the null is of type BsonDocument and it gets converted to string.
If we look at the implicit conversion of BsonDocument (it's in BsonValue.cs:426):
`public static implicit operator String(BsonValue value)
        {
            return (String)value.RawValue;
        }`
Here the null exception gets thrown.

I don't know if it's wise to just add null checks on all implicit operators and return null / the default.

But how it's working now is definately not optimal. What do you think?

PS: Sorry for the poor formatting.

**Comment by gpauls** [comment]
Is it clear what I meant?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
