### ISSUE TITLE
Stream.CopyTo(LiteFileStream) does not work

### ISSUE THREAD

**Issue by bradselw** [mbdavid/LiteDB#635]
I'm using version 3.1.1 of the NuGet package. I would expect the following code to create a new entry in file storage and copy the contents of `testFile` into it:
```csharp
static void Main(string[] args)
{
    var testFile = new FileInfo("test.txt");
    File.WriteAllText(testFile.FullName, "This is a test.");

    using (var db = new LiteDatabase(@"MyData.db"))
    {
        using (var source = testFile.OpenRead())
        {
            Console.WriteLine("Source length: {0}", source.Length.ToString());

            using (var destination = db.FileStorage.OpenWrite("$/test.txt", testFile.FullName))
            {
                source.CopyTo(destination);

                Console.WriteLine("Destination length: {0}", destination.Length.ToString());
            }
        }
    }
}
```
Instead, nothing gets copied over:
```
Source length: 15
Destination length: 0
```
Is `CopyTo` not supported by `LiteFileStream`? [This is common pattern](https://msdn.microsoft.com/en-us/library/dd782932(v=vs.110).aspx#Examples) for copying the contents of one stream to another, so it should work IMO.

**Comment by bradselw** [comment]
I think I understand what is going on here. If I flush `destination` after the `CopyTo` operation, everything works just fine. I think other streams (e.g. `MemoryStream` and `FileStream`) flush the stream in their `Dispose` method. Looks like `LiteFileStream` doesn't override the `Dispose` method - maybe that could be an improvement to the class? I'll create a PR shortly.

**Comment by mbdavid** [comment]
Hi @bradselw, yes, make sense flush stream in Dispose method. I'm adding this... thanks!

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
