### ISSUE TITLE
Connection String "Mode" is ignoring ReadOnly

### ISSUE THREAD

**Issue by vbguyny** [mbdavid/LiteDB#636]
When trying to open the db in ReadOnly mode, it is still being opened as Shared.  By looking at the code in 3.1.1 was as able to see that in the LiteDatabase constructor where it creates the new instance of the FileOptions object, it does not set the FileMode member equal to the connectionString argument.

Here is my fix:

            var options = new FileOptions
            {
    #if !NET35
                Async = _connectionString.Async,
    #endif
                InitialSize = _connectionString.InitialSize,
                LimitSize = _connectionString.LimitSize,
                Journal = _connectionString.Journal,
                FileMode = _connectionString.Mode, /* FIX */
            };

I understand that there maybe other parts of the code that will fail if the db is opened in ReadOnly (for example, EnsureIndex call from Find will fail).  However, I think that this is a step in the right direction.

**Comment by mbdavid** [comment]
Thanks @vbguyny, fixed!

**Comment by vbguyny** [comment]
Hello, @mbdavid!
Have you done anything to the EnsureIndex routine while in ReadOnly mode?  On my end, the EnsureIndex method fails because it looks like it is trying to re-create the index when I perform a find.
Thanks.

**Comment by mbdavid** [comment]
Hi @vbguyny, in readonly mode you can't use EnsureIndex because first operation is try to lock datafile. In read only mode just call Find method.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
