### ISSUE TITLE
Insert and Update too slow after 3.1.1

### ISSUE THREAD

**Issue by ArefGihuni** [mbdavid/LiteDB#640]
Unfortunately update and insert operations are now too slow after the latest version 3.1.1 

it's fast in 3.1.0

**Comment by mbdavid** [comment]
Hi @ArefGihuni, it's because in 3.1.1 was added flush method in journal file because there are same issues about persisting in disk. If you need more speed, disable journal

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
