### ISSUE TITLE
LiteDB multi-user (One write, One reader)

### ISSUE THREAD

**Issue by nicrf** [mbdavid/LiteDB#646]
Hi,

Does LiteDB have an  locking mechanism like SQLite?

**Comment by JosefNemec** [comment]
Yes, check [Connection-String](https://github.com/mbdavid/LiteDB/wiki/Connection-String), specifically **Mode** property.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
