### ISSUE TITLE
Can't access Elements of a List

### ISSUE THREAD

**Issue by h0ch5tr4355** [mbdavid/LiteDB#647]
I have following data model:

```
        public class Customer
        {
            [BsonId]
            public int CustomerId { get; set; }
            public string Name { get; set; }
        }


        public class Order
        {
            [BsonId]
            public int OrderId { get; set; }
            [BsonRef("customers")] 
            public Customer Customer { get; set; }
        }

        public class Cart
        {
            [BsonId]
            public int CartID { get; set; }
            public List<Order> OrderList { get; set; }
        }
```

Now I want to access the customer via queries on my cart collection.
I tried something like this:
```
var result = collectionCarts.Include("OrderList.Customer").Find(x => x.OrderList[0].Customer.CustomerId == 2);
```

However, all attempts result in an empty customer object. My database, which I checked with the LiteDB-Viewer seems to be OK.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
