### ISSUE TITLE
FileDiskService in Shrink

### ISSUE THREAD

**Issue by masterdidoo** [mbdavid/LiteDB#651]
in [LiteDB/Database/LiteDatabase.cs 234](https://github.com/mbdavid/LiteDB/blob/c071b627a7b6fed6986bf8e560c05f469b346435/LiteDB/Database/LiteDatabase.cs#L234)
FileDiskService created, but not used further

```c#
   // get temp disk based on temp file
   var tempDisk = new FileDiskService(tempFile, false);
    
   var reduced = _engine.Value.Shrink(password);
    
   // delete temp file
   File.Delete(tempFile);
```

**Comment by mbdavid** [comment]
Hi @masterdidoo thanks. Was missing second parameter in Shrink method. Fixing now
