### ISSUE TITLE
Problem with TargetPlatforms and the new .NET tooling

### ISSUE THREAD

**Issue by mkosieradzki** [mbdavid/LiteDB#656]
There are two issues here - first one let me discover the second one.
Current nuget package contains to target platforms:
netstandard1.4 and net35

1st issue: In package version 3.1.1.0 net35 assembly version is 3.1.0.0 when netstandard1.4 assembly version is 3.1.1.0.

And now this made me discover the second issue:
(at least when using the latest .net standard 2.0 tooling - preview 2) net461 seems to prefer net35 assembly version over netstandard1.3) this causes tools to use wrong version of assembly (net35 which has many many features disabled).

Solution:
1. Fix build to apply versioning corectly
2. Add net40 or net45 target with basically the same code as netstandard1.4
In that case when referencing LiteDB from net461 net40 will take precedence before net35 which is not a really good package.

UPDATE: Regarding the second point I am not really convinced whether it is true or not... But using net40/net45 tfm seems like a safe way.
UPDATE2: I am positive this is the issue. Please click following link and you will see that net35 wins.
http://nugettoolsdev.azurewebsites.net/4.2.0/get-nearest-framework?project=net461&package=net35%0D%0Anetstandard1.4
My recommendation will look as follows:
http://nugettoolsdev.azurewebsites.net/4.2.0/get-nearest-framework?project=net461&package=net35%0D%0Anet40%0D%0Anetstandard1.4

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
