### ISSUE TITLE
Obtaining list of _ids

### ISSUE THREAD

**Issue by nscaife** [mbdavid/LiteDB#663]
Is there a way to get a list of `_id`s from a collection? `LiteCollection.Exists()` seems to let me query the existence of a specific document by ID, but I'd like to enumerate them without retrieving the objects.

**Comment by mbdavid** [comment]
Hi @nscaife, you can use `FindIndex` from `LiteEngine`.

`db.Engine.FindIndex("my-collection", Query.All())` to get all `_ids` without load documents.

**Comment by nscaife** [comment]
@mbdavid it looks like db.Engine.FindIndex was removed in 4.x -- is there a better way to do this now?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
