### ISSUE TITLE
Problem avoiding CS2202 violation (disposing streams)

### ISSUE THREAD

**Issue by AngusMcIntyre** [mbdavid/LiteDB#666]
I'm using LiteDB in an environment where I'm mocking my filesystem using [System.IO.Abstractions](https://github.com/tathamoddie/System.IO.Abstractions). Naturally, I am wrapping the source `Stream`, and the `LiteDatabase `instance in using statements, but this is violating [CS2202](https://msdn.microsoft.com/library/ms182334.aspx).

>**CS2202 Cause**
>  A method implementation contains code paths that could cause multiple calls to IDisposable.Dispose or a Dispose equivalent, such as a Close() method on some types, on the same object.

Violating code:
```
var stream = file.Open(System.IO.FileMode.OpenOrCreate, System.IO.FileAccess.ReadWrite);

using (stream) // <-- Code analysis does not like this at all
using (var db = new LiteDB.LiteDatabase(stream,))
{
     fileConfiguration = new FileConfiguration();
     // Add and save the configuration
     var configCollection = db.GetCollection<FileConfiguration>();
     configCollection.Insert(fileConfiguration);
}
```
To fix the code, I simply remove the first using line. However, now my database update unit tests are failing. I suspect that there will also be a production failure here as well.

I have debugged through the code and it seems that this is because `LiteDB.StreamDiskService ` does not dispose the underlying stream when it is Disposed, even though code analysis suspects it might. The workaround is to called `stream.Flush()` in my production code. This passes the test but it does not dispose the stream. I find this inconsistent with recommended usage, and the recommended fix for CS2202 to a) be overly verbose and b) not actually work.

My workaround for this behaviour is to implement my own `IDiskService` that wraps `StreamDiskService `and dispose the stream myself. I have two questions:

1. Is this the correct approach? I really appreciate being able to provide my own `IDiskService` implementation here.
2. What was it that drove the decision to never dispose the stream in `StreamDiskService`? This is a point of curiosity as I would like to understand the design philosophy.

Any feedback is greatly appreciated. Thanks.

**Comment by Gusdor** [comment]
The final implementation is very simple and does the job.

```
/// <summary>
/// Implementation of <see cref="LiteDB.IDiskService"/> that takes a stream and automatically disposes of it when the service is disposed.
/// </summary>
internal class DisposingStreamDiskService : LiteDB.StreamDiskService
{
    private System.IO.Stream stream;

    /// <summary>
    /// Initialises a new instance of the <see cref="DisposingStreamDiskService"/> class.
    /// </summary>
    /// <param name="stream">The stream from which to read and write data.</param>
    public DisposingStreamDiskService(System.IO.Stream stream)
        : base(stream)
    {
        this.stream = stream;
    }

    /// <inheritdoc/>
    public override void Dispose()
    {
        this.stream.Dispose();
        base.Dispose();
    }
}
```

**Comment by mbdavid** [comment]
Hi @Gusdor, `StreamDiskService` does not call `Dispose` because it´s this will close external stream and this could not be a good idea for who is calling. Like this

```
var m = new MemoryStream();

using(var db = new LiteEngine(m))
{
   ...
}

// here, memory stream still open
```

```

**Comment by Gusdor** [comment]
Can you describe an instance in which you would want the stream to be left open? I am struggling to think of a scenario.

This took me by surprise because the behaviour deviates from the pattern established by System.IO. StreamReader, StreamWriter, BufferedStream all close the inner stream when closed.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
