### ISSUE TITLE
Shrink, FileStorage, Encryption crashes in an UWP App

### ISSUE THREAD

**Issue by gomi42** [mbdavid/LiteDB#667]
I use LiteDb in an UWP app. Beside the fact that the initialization is a bit cumbersome (need to pass a stream to the constructor because direct file handling does not work in UWP) everything works just find. Now I found out that Shrink crashes with the following exception:

Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

It seems that Shrink tries to deal with filenames and Standard file operations which again does not work in UWP.

Michael

**Comment by gomi42** [comment]
It turned out that there is the same problem with the FileStorage methods that take a stream. They crash with the same exception as mentioned above.

**Comment by gomi42** [comment]
For UWP there seem to be even more limitations. When I set a password I get this exception:

Could not load file or assembly 'System.Security.Cryptography.Algorithms, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
