### ISSUE TITLE
Error in the exe generated with unity 2017

### ISSUE THREAD

**Issue by ghiboz** [mbdavid/LiteDB#668]
hi all! here is the error I retrieve in the `output_log.txt`

```
System.TypeInitializationException: An exception was thrown by the type initializer for LiteDB.BsonMapper ---> System.ArgumentOutOfRangeException: Argument is out of range.
Parameter name: options
  at System.Text.RegularExpressions.Regex.validate_options (RegexOptions options) [0x00000] in <filename unknown>:0 
  at System.Text.RegularExpressions.Regex..ctor (System.String pattern, RegexOptions options) [0x00000] in <filename unknown>:0 
  at LiteDB.BsonMapper..ctor (System.Func`2 customTypeInstantiator) [0x00000] in <filename unknown>:0 
  at LiteDB.BsonMapper..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at GRConfig.⁮‫⁪‬⁪‍⁯⁯‭‬⁬‍‮​‏⁯‫⁪‎‍⁯‪​⁭‪​⁮‫⁬‫‎‮‪⁮‪​‪‪‮‌‮ (System.String , LiteDB.BsonMapper ) [0x00000] in <filename unknown>:0 
  at GRConfig.loadSettings () [0x00000] in <filename unknown>:0 
```

and my code for the initalization is this:
```CSharp
try 
{
    liteDb = new LiteDatabase(liteFile);
    collectionStats = liteDb.GetCollection<dtStats>("dtStats");
}
catch (Exception ex)
{
    Debug.LogWarning("Error liteDb");
    Debug.LogWarning(ex.ToString());
}
```

thanks in advance

**Comment by cmisztur** [comment]
Which branch of LiteDB? 
What platform in Unity?

**Comment by ghiboz** [comment]
helo @cmisztur 
I used the unity branch and on unity I'm on windows exe 64 bits (the litedb project is compiled to have these settings...)
no changes on dll, with old unity3d works, with unity2017 no.. I think that the issue is due by the fact that unity2017 has some changes on .net code, allow to use framework 3.5 and other things...

thanks again

**Comment by cmisztur** [comment]
Can you try switching to .NET 4.6 in player settings.  Most errors went away for me.  If you can't, then try going from .NET 2.0 Subset to .NET 2.0 in player settings.

**Comment by ghiboz** [comment]
thanks, but with .NET 4.6 another dll doesn't work properly, I can't test it...

**Comment by cmisztur** [comment]
did you try just changing from .NET2 Subset to .NET2 ?

**Comment by ghiboz** [comment]
thanks @cmisztur 
with .net2 instead subset seems that it works... I make some detailed tests
thanks in advance!

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
