### ISSUE TITLE
Working with LiteCollection?

### ISSUE THREAD

**Issue by wilberolive** [mbdavid/LiteDB#669]
So I have two questions.

1. How do you inspect the contents of a LiteCollection when debugging in Visual Studio? I try expanding out the properties of it in the Autos window, but it just gives things like _engine, _includes, _log, _mapper, etc... I would like to be able to see how many objects is in it and what they are when my application is paused in the debugger?

2. How do I handle a collection of collections? I'm sure this has been covered somewhere but I can't find any explicit example. Every example I've looked at just show a single collection of objects. I have the following scenario and just wondering how I handle this with LiteDB?

```
public class Group
{
    public string Name { get; set; }
    public List<Item> Items { get; set; }
}

public class Item
{
    public string Name { get; set; }
    public Group ParentGroup { get; set; }
}
```

**Comment by mbdavid** [comment]
Hi @wilberolive, LiteCollection doesnt contain all you documents at debug time. Think in LiteCollection not as an `DataTable`. If you want show all documents inside a collection you must call `col.FindAll().ToArray()`. At this time, LiteDB will run query to find all your documents.

You can handle collections inside object with no problem. The easy way is work as embedded document. In you example, if you store a `Group` with many `Items`, when you restore this Group you will get all items too. Take a look in this MongoDB definitions, its the same in LiteD: https://docs.mongodb.com/manual/core/data-modeling-introduction/

**Comment by wilberolive** [comment]
Ok, so does that mean I can just store a collection of Groups as is and each Group's list of Items will be automatically stored with it?

Therefore if I make a change to an Item within a Group, I then just call DB.Update on the entire Group?

What about the reference back to the ParentGroup that each Item has? Does that also just persist and retrieve as well as is or do I need to use an Id field shown in that document?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
