### ISSUE TITLE
About memory usage

### ISSUE THREAD

**Issue by lidanger** [mbdavid/LiteDB#670]
I have a question about memory usage.

I have used ensureindex on "time" and "code" Propertites like this:

    var col = conn.GetCollection<Point>("RealConc");
    col.EnsureIndex<string>(pt => pt.Code);
    col.EnsureIndex<DateTime>(pt => pt.Time);

And there is only about 1200 data item to insert into the collection per hour, but when the program query data like this

    try
    {
        var col = conn.GetCollection<Point>("RealConc");
        var rtds = col.Find(pt => pt.Time >= dataTime.AddHours(-1) && pt.Time < dataTime);
        realConc.AddRange(rtds);
    }
    catch (Exception ex)
    {
        _logger.DebugFormat("统计小时数据时获取实时浓度数据异常{0}", ex);
    }

the memory usage of the program is about 900 MB, and the data file size is 700MB.
Where is the problem?

@mbdavid

**Comment by mbdavid** [comment]
Hi @lidanger, try use direct between query implementation (it´s more efficient that >= and <)

`col.Find(Query.Between("Time", initalDate, finalDate))`

Complex Linq queries are not optimezed in LiteDB. Your query will convert your in 2 queries (`QueryLess` and `QueryGetter`) with an `QueryAnd` using an `Except`.

**Comment by lidanger** [comment]
It's so fast when I used the modthod you have mentioned above.The cost of time is reduced to only 200 milliseconds while is costed more than 20 seconds  before, and the memory usage is nearly zero growth.
Thanks a lot!!

**Comment by mbdavid** [comment]
New v3.5 now convert your query LINQ expression into a QueryBetween in this case. QueryBetween also support open/close intervals: `x > 1 && x < 10`, `x >= 1 && x < 10`, `x >= 1 && x <= 10`, `x > 1 && x <= 10`
