### ISSUE TITLE
Qual a quantidade total de armazenamento

### ISSUE THREAD

**Issue by mhnegrao** [mbdavid/LiteDB#671]
Olá Maurício. Em primeiro lugar meus parabéns pela sua iniciativa, audácia e qualidade do seu projeto.
Já havia ouvido falar do LiteDB mas não havia utilizado e após ter contato com ele achei formidável.
Ainda não efetuei testes com grande massa de dados mas gostaria de saber qual o limite de armazenamento do banco de dados e, com grande volume de dados o banco onera o desempenho da aplicação?
O LiteDB para aplicações simples e médias pode ser a grande solução para desenvolvedores .NET, já que é 100% C#, no qual desenvolvo e nos traz o poder de manipular os dados inteiramente dentro das aplicações.

Parabéns,

Marcelo Henrique

**Comment by mbdavid** [comment]
Olá Marcelo, obrigado. E que bom poder escrever em portugues :)

Cara, não existe limitação de tamanho no LiteDB, ele se comporta bem para qualquer tamanho. Já tive relato de pessoas falando em um único arquivo de 60Gb sem nenhum problema. Se as buscas são feitas por indice, a complexiadade o O(log(n)), ou seja, mesmo que aumente muito a quantidade de registros a quantidade de passos para encontrar um registro pouco é afetada.

O grande desafio tem sido a questão da concorrência de escrita. A gestão de lock de disco e de thread tem me tirado o sono, pois é bem complexa e ainda não cheguei na solução ideal. Estou trabalhando na branch `dev` que, a principio, deve corrigir alguns problemas em relação a isso. Em breve deve pedir ajuda ao pessoas para uma bateria de testes maior (o pessoal tem muita criatividade nisso :)

Abraço,

**Comment by mhnegrao** [comment]
Muito Obrigado pela resposta Maurício!!!
Dependendo de mim, seu projeto vai longe!!!! 😉
É bom ver um brasileiro mostrando sua qualificações e ter reconhecimento internacional.
Se eu tiver mais dúvidas , lhe procuro.

Abraços!
