### ISSUE TITLE
Propriedade List não grava conteúdo no banco de dados

### ISSUE THREAD

**Issue by mhnegrao** [mbdavid/LiteDB#673]
Boa noite Maurício, eu novamente.
Efetuando alguns testes, percebi que ao gravar uma classe com uma propriedade do tipo List, ela não é enviada para o banco de dados.
Veja minhas classes e o método que faz a gravação:

```
public class ClienteEntity
    {
        public ClienteEntity()
        {
        }
        
        [LiteDB.BsonId]
        public int Id { get; set; }
        public string RazaoSocial { get; set; }
        [LiteDB.BsonIndex]
        public string NomeFantasia { get; set; }
        public string Cnpj { get; set; }
        public string Ie { get; set; }
        public string Logradouro { get; set; }
        public string NumeroLogradouro { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Cep { get; set; }
        public string Fone { get; set; }
        public string Email { get; set; }
        public string Uf { get; set; }
        public string Observacao { get; set; }
        public DateTime DataInclusao { get; set; }
        public string Tipo { get; set; }
        public string Contato { get; set; }
        [LiteDB.BsonRef("ordens_servico")]
        public List<OsEntity> OrdensServico { get; set; } = new List<OsEntity>();
        [LiteDB.BsonRef("orcamentos")]
        public List<OrcamentoEntity> Orcamentos { get; set; } = new List<OrcamentoEntity>();
        
    }

public class OsEntity
    {
        public OsEntity()
        {
        }
        [LiteDB.BsonId]
        public long Id { get; set; }
        public long IdCliente { get; set; }
        public long IdTrabalhoExecutar { get; set; }
        public long Numero { get; set; }
        public string Data { get; set; }
        public string DataPrevistaEntrega { get; set; }
        public string Descricao { get; set; }
        public string ValorOs { get; set; }
        public string ValorServicoTerceiro { get; set; }
        public string ValorMateriaPrima { get; set; }
        public string ValorImposto { get; set; }
        public string CondicaoPagamento { get; set; }
        [LiteDB.BsonRef("trabalho_executar")]
        public List<TrabalhoExecutarModel>TrabalhoExecutar  { get; set; }
    }

public class OrcamentoEntity
    {
        public OrcamentoEntity()
        {
        }
        [LiteDB.BsonId]
        public long Id { get; set; }
        public long IdCliente { get; set; }
        public long Numero { get; set; }
        public DateTime Data { get; set; }
        public string DescricaoServico { get; set; }
        public decimal Valor { get; set; }
        public DateTime DataPrevistaEntrega { get; set; }
        public string Observacao { get; set; }
        public string Contato { get; set; }
        public string Email { get; set; }
    }
```

E o método de inserção:

        public readonly LiteDatabase Db;
        public RepositoryBase()
        {
            Db = ConectLiteDB.GetContext();
        }
        /// <summary>
        /// Adiciona um registro
        /// </summary>
        /// <param name="obj"></param>
        public void Add(TEntity obj)
        {
            using (var escopo = Db.BeginTrans())
            {
                Db.GetCollection<TEntity>().Insert(obj);
                escopo.Commit();
            }
        }

    Os dados são gravados sem problemas mas ao consultar um orçamento no bd vejo este conteúdo no array:

**{
    "$id": {
        "$numberLong": "0"
    },
    "$ref": "orcamentos"
}**

Já verifiquei e os dados são enviados ao banco. Como estou iniciando com o LiteDB não sei se fiz tudo correto, pois eu segui os seus exemplos da documentação.
Onde está o erro?

Att.,

Marcelo

**Comment by mbdavid** [comment]
Marcelo, alguns pontos:

1) O atributo DbRef deve informar o nome da collection que vai entrar os dados. Se tu não usando sem nome (como no metodo Add) o nome padrão é o próprio nome da classe.

Quando tu usa `Db.GetCollection<TEntity>().Insert(obj)` para inserir um cliente o nome da collection vira ClienteEntity (porque tu não definiu). Neste caso, troca os DbRef para a refencia o nome da classe

2) Se tu quer usar AutoIncrement no Id, utiliza `int` que possui implementação (ps: isso tá mudando um pouco, mas vai estar no tutorial UPGRADE pra nova versão)

3) Se tu quer montar um repositorio de T, dá uma olhada na class LiteRepository que já tem implementado.

**Comment by mhnegrao** [comment]
Ok... até aí o nome da collection está ok pra mim, é que estou usando o padrão DDD, o meu repositório é genérico:
public class RepositoryBase<TEntity> : IRepositoryBase<TEntity> where TEntity : class

qdo declaro :
 [LiteDB.BsonRef("orcamentos")]
 public List<OrcamentoEntity> Orcamentos { get; set; } = new List<OrcamentoEntity>();

devo declarar
[LiteDB.BsonRef("OrcamentoEntity")]
 public List<OrcamentoEntity> Orcamentos { get; set; } = new List<OrcamentoEntity>();

correto?
É esta propriedade que fica vazia no bco de dados.

**Comment by mbdavid** [comment]
Cara, agora vi melhor teu modelo, tem umas questões conceituais ai que não estão certas. Coleção é diferente de tabela e por isso não faz sentido tu colocar no Cliente uma lista de Orçamento ou Ordem de Serviço. Essa relação em um banco nosql é diferente.

Se tu fizer assim, ao salvar um cliente, tu está salvando a lista de orçamento também associada ao cliente, e não é isso que tu quer fazer. Tu teria algo assim:

```
// cliente
{ 
    _id: 1,
    Orcamentos: [
        { $id: 10, $ref: "Orcamento" },
        { $id: 11, $ref: "Orcamento" },
        { $id: 12, $ref: "Orcamento" }
    ]
}
```

Gosto muito deste link do MongoDB que explica como modelar em nosql (no LiteDB a ideia é a mesma do Mongo): https://docs.mongodb.com/manual/core/data-model-design/

**Comment by mhnegrao** [comment]
Entendi...valeu pela dica e vou dar uma analisada e te retorno falando o resultado.
Abraços👍
