### ISSUE TITLE
The file version of LiteDB on Nuget is 3.1.0.0

### ISSUE THREAD

**Issue by lidanger** [mbdavid/LiteDB#674]
The file version of LiteDB on Nuget is 3.1.0.0,while the release version is 3.1.1.0.
It seems a mistake.

**Comment by mkosieradzki** [comment]
Mentioned also in #656 .

**Comment by mbdavid** [comment]
Hi guys, i'm working on `dev` branch and I will fix this with a new version (3.5 or 4.0). I will soon ask to everyone help me in write more tests (especially about concurrency).

**Comment by mkosieradzki** [comment]
@mbdavid I have noticed that you have removed transaction support in dev. Any chance for releasing "fixed" 3.1.1 package with proper dlls and no breaking changes?

**Comment by mbdavid** [comment]
Hi @mkosieradzki, no problems. I will release 3.2 fixing this number problem + some bugs that I found in locker service (with no api changes)

**Comment by mkosieradzki** [comment]
Thanks a lot!!

**Comment by lidanger** [comment]
Good,thanks.

**Comment by lidanger** [comment]
May you Add a overloading constructor with the FileOptions as parameter in LiteDatabase? I can use  FileOptions.WriteThrough in some cases.
@mbdavid

**Comment by mbdavid** [comment]
Hi @lidanger, current version are not using WriteThrough?

**Comment by lidanger** [comment]
Hi @mbdavid, no,  I don't found the option in the source code at least.I can only modify the code myself before.

**Comment by mbdavid** [comment]
@lidanger, yes, current version do not use FileOptions. Current implementation are working with Flush disk when finish - it's safe but it's lower... I will take a look if Sqlite has some options in this way to copy to LiteDB

**Comment by mkosieradzki** [comment]
@mbdavid 3.1.0.0 that is inside 3.1.1.0 and picked by compiler as described in #656 has no flush for log ( #574 ).

**Comment by mbdavid** [comment]
Hi @mkosieradzki, i merged you PL about fixing version numbers. Is safe now merge VS2017 upgrade (I would like to merge in master and dev branch)?
I will review this flush on log too for master (in dev I remove adicional journal file - use inside same datafile). Also, in master my LockService.cs are wrong using _state variable to control lock state in multi-thread enviorment - it's fixed too in dev.
