### ISSUE TITLE
Add interface to LiteRepository and LiteDatabase

### ISSUE THREAD

**Issue by vfabregat** [mbdavid/LiteDB#678]
Hi! first of all, nice product, is super simple to use.

I want to request an abstraction over LiteRepository and LiteDatabse, allow us to mocking it to do unit testing.

I see the issue #629 If you want I can do it. A simple extract interface in those clases. Seems ok? 

Regards.

**Comment by mbdavid** [comment]
Hi @vfabregat, thanks! I will take a look better on this. To mock, all main classes must be abstract in interfaces (LiteRepository, LiteDatabase, LiteCollection, LiteEngine, ....)

But you already use in-memory database in your unit testing? Like I do on LiteDB unit tests?

**Comment by vfabregat** [comment]
Hi @mbdavid , Yes at this moment I'm using in memory database, but I want to mock it, to remove that dependecy in my tests.

If you want I can send you a pull request with this change.

**Comment by Lonli-Lokli** [comment]
Hello everyone, is there any progress?
