### ISSUE TITLE
Indexing by DateTime 

### ISSUE THREAD

**Issue by MolecularDust** [mbdavid/LiteDB#684]
Here's a simple log database indexed by DateTime. When I try to delete entries by BsonValue the "Note 3" record is not deleted. From my limited knowledge that happens because internally LiteDB stores time at tick precision but BsonValue truncates it to milliseconds. This is related to [issue #604](https://github.com/mbdavid/LiteDB/issues/604). So after all I end up with a situation where LiteDB cannot find the document by the very Id it returns to the user because what it stores internally and what it returns mismatch.

```
    public class LogSample
    {
        [BsonId]
        public DateTime Time { get; set; }
        public string Notes { get; set; }

    }

          static void Main(string[] args)
        {
            using (var db = new LiteDatabase("Test.db"))
            {
                var collection = db.GetCollection<LogSample>("TestCollection");
                db.DropCollection("TestCollection");

                var now = DateTime.Now;
                collection.Insert(new LogSample { Time = new DateTime(2017, 1, 1), Notes = "Note 1" });
                collection.Insert(new LogSample { Time = DateTime.Today, Notes = "Note 2" });
                collection.Insert(new LogSample { Time = now, Notes = "Note 3" });
                collection.Insert(new LogSample { Time = new DateTime(now.Year, now.Month, now.Day, now.Hour, now.Minute, now.Second, now.Millisecond, DateTimeKind.Local), Notes = "Note 4" });
            }

            using (var db = new LiteEngine("Test.db"))
            {
                var allEntries = db.Find("TestCollection", Query.All()).ToList();
                foreach (var entry in allEntries )
                {
                    var id = entry["_id"];
                    db.Delete("TestCollection", id);
                }
            }
        }
```
I mitigate that by truncating all DateTime values to milliseconds in my class:

```
        private DateTime _time;
        [BsonId]
        public DateTime Time
        {
            get { return _time; }
            set { _time = new DateTime(value.Year, value.Month, value.Day, value.Hour, value.Minute, value.Second, value.Millisecond, DateTimeKind.Local); }
        }
```
Another idiosyncrasy is that LiteDB doesn't fully support DateTime properties syntax in queries. I expected this query to yield all records made today but it fails.

`var todayEntries = collection.Find(x => x.Time.Date == DateTime.Today);`

Instead I have to be very explicit to find what I want:

```
var today = DateTime.Today;
var tomorrow = today.AddDays(1);
var todayEntries = collection.Find(x => x.Date >= today && x.Date < tomorrow);
```
The same applies to x.Time.Year,  x.Time.Day etc. That would be nice to see these supported in the future.

**Comment by mbdavid** [comment]
Hi @MolecularDust, LiteDB store data as BSON specs:

```
// write 
var utc = (date == DateTime.MinValue || date == DateTime.MaxValue) ? date : date.ToUniversalTime();
var ts = utc - BsonValue.UnixEpoch;
writer.Write(Convert.ToInt64(ts.TotalMilliseconds));

// read
var ts = reader.ReadInt64();
return BsonValue.UnixEpoch.AddMilliseconds(ts).ToLocalTime();
```

I will try test your example to checks if why is not deleting if you are returning from database.

And about use DateTime properties, it's not possible use becase this values are not indexed. Only full date are indexed. So, when you try `x => x.Date.Year` you need in your index only YEAR stoaged (and not full date). Another databases execute this queries just not using index and running full scan on tables.
In current 3.5 beta version, LiteDB do the same: if index are not found, used full scan (it's much more slow, but will works).

**Comment by namhnz** [comment]
I have an issue with Find based on DateTime expression. This is the expression I used: `stus.Find(s => s.Birthday.Year <= 1996);`. Below is full code:
Student.cs:
```
    public class Student
    {
        public int StudentID { get; set; }
        public string Name { get; set; }
        public int Grade { get; set; }
        public DateTime Birthday { get; set; }
    }
```
Program.cs
```
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new LiteDatabase("test.db"))
            {
                LiteCollection<Student> stus = db.GetCollection<Student>("students");

                List<Student> studentList = new List<Student>()
                {
                    new Student() {Name = "Nguyen Hoang Nguyen", Birthday = new DateTime(1997, 6, 3), Grade = 8},
                    new Student() {Name = "Nguyen Anh Tuan", Birthday = new DateTime(1997, 7, 12), Grade = 8},
                    new Student() {Name = "Pham Van Hung", Birthday = new DateTime(1996, 3, 26), Grade = 9}
                };

                stus.Insert(studentList);
                stus.EnsureIndex(s => s.Birthday.Year);

                var filteredStudents = stus.Find(s => s.Birthday.Year <= 1996);

                Console.WriteLine("Student who has birth year before 1996:");
                foreach (Student filteredStudent in filteredStudents)
                {
                    Console.WriteLine($"- {filteredStudent.Name}, grade: {filteredStudent.Grade}");
                }
                
                Console.ReadKey();

                db.DropCollection("students");
            }
        }
    }
```
When I run the code, only line `"Student who has birth year before 1996:"` was printed, but I think the third student should be printed, too. So is there something I misunderstood here?

**Comment by mbdavid** [comment]
Hi @namhnz, `date.Year` is a "function" from `DateTime` and are not indexed in this case. In v4 there is no Year convert into expression. 

For now you can only search by year using this: `s.Birthday >= new DateTime(1996, 1, 1) && x. Birthday <= new DateTime(1996, 12, 31)`.

**Comment by namhnz** [comment]
@mbdavid Thank you for the clarification.
