### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by martinrotter** [mbdavid/LiteDB#685]
I plan to incorporate LiteDB into commercial software, which is used by thousands of users (attribution will be given). Yet, I have some questions beforehand:

1. Is there any size limit for objects stored into database?
2. Can I efficiently query only objects from database which instances of subclass? What I mean (pseudocode):

```
var col = new database.collection<Vehicle>();
col.insert(new Car()); // where Car is subclass of Vehicle
col.insert(new Van()) // the same

--> NOW GET ONLY CARS, HOW?
```
3. There is 1MB limit per object? Can this be altered? This is total blocker.

**Comment by mbdavid** [comment]
Hi @martinrotter,

1) There is not more document limit. It was removed but I still recommend use smaller documents as possible to keep fast to read/write on disk. Remeber, when you update a document, all document fields/data will be write to disk. So if you have more than 1Mb document and you update only a simple date field, all 1mb must be write on this.

2) In you example it's not that easy to query. It's possible, but you must remember that LiteDB is a document database, not a object database. All classes are converted to BSON (binary json) and (in your example) if collection if of Vehicle and you insert an object that is not a Vehicle (but is a subclass of) a `_type` attribute will be saved. You can index this field to query after, but it's not too intuitive.
```
db.EnsureIndex("Vehicle", "_type");
col.Find(Query.EQ("_type", "YourNamespace.Car"));
```
This way is possible to get only cars using index.

And, if you choose LiteDB. please let me know to add in "Used Projects/Products" section here.

**Comment by martinrotter** [comment]
Thank you for clarification. I managed to get better understanding of LiteDB internals. What if class of my objects which I store in collection gets changed, for example moved to another namespace? Is there anything I can do, to access all my objects, even if stored under different full class name (old namespace)?

**Comment by mbdavid** [comment]
Hi, if you change your namespace in a strong typed document, you will loose your reference and you will get an error when compiler try to create instance of you _type.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
