### ISSUE TITLE
Encryption and Password

### ISSUE THREAD

**Issue by Danielmdmu** [mbdavid/LiteDB#686]
Hey Guys,

I'm planning to use LiteDB as an Filestorage for my local Application Data.
I already tried to set an password, and everything is working fine.
But my Problem is, that I only can set one password.
One of the requirements of my Application is, one master password and one individual password per Installation.
Are there any Solutions or Workarounds?

I'm thinking of "generating" an password.
Maybe as a hash of an master password with an Individial string like sid etc.

**Comment by mbdavid** [comment]
Hi @Danielmdmu, password in litedb are used to encrypt all data pages. So, it's not possible has more than 1 password. If it's possible, you can create one database per instalation or (if not possible) you must control your users with an User/Instalation collection to control this.

**Comment by Danielmdmu** [comment]
Thanks for your Reply.
I will try to create one DB per Installation. 
@mbdavid FileStorage is a nice Feature ;-)
