### ISSUE TITLE
Can not open projects(.csproj) in VS2015

### ISSUE THREAD

**Issue by ddrrqq** [mbdavid/LiteDB#687]
Hi,
I've been using VS2015 for a long time and haven't considered upgrading to VS2017 for the time being.
I would like you to provide the compiled binary .DLL file for download.

Thanks!

**Comment by mbdavid** [comment]
Hi @ddrrqq, I tried upload dll file in github release area, but it's not possible. You can use nuget to download compiled 3.1.2 version

**Comment by ddrrqq** [comment]
OK, Thank you,
I rename nuget -> zip ,decompress and found dll files.
Thank you!
