### ISSUE TITLE
Cannot open a .net 3.5 program using litedb in scheduled task in windows 7

### ISSUE THREAD

**Issue by Almesia** [mbdavid/LiteDB#689]
Hi,
I make a program in .net 3.5 and i use the scheduled task of windows to run my program.
But the problem is here, I receive an error CLR20r3 when i run it.
I have try to just create a table in the database but that didn't work.
Do you have solutions ?

screens of the error : https://i.imgur.com/ayf4k18.png https://i.imgur.com/q9KsuY0.png

Sorry for my english and for the error screens in french xD

**Comment by mbdavid** [comment]
Hi, you must check permissions on your windows task schedule. Try mark as high privileges and se an user with permission on directory that you want save your database

**Comment by Almesia** [comment]
Thank for your help, I found the solution 🥇 We have to specify the full link for each link. Like if you want to create a file in the same folder than your .exe, you have to write c:/*path_to_exe*/*your_file*

So that was not a problem of litedb :)
