### ISSUE TITLE
When the assembly will be signed in NuGet repository?

### ISSUE THREAD

**Issue by nickun** [mbdavid/LiteDB#69]
I tried to add the NuGet package into my project but I couldn't compile that because my project is signed so all assemblies I use have to be signed.

**Comment by caverna** [comment]
Maybe you can download the source code and use the same signature...

**Comment by nickun** [comment]
I do that but this is not so easy as just to update the package. Also I should to follow the updates and recompile it all the time.

**Comment by caverna** [comment]
When I said 'download the source' I'd like to say 'insert LiteDB as a submodule to your git repository'...
That way you'll I'll be able to sign your version of LiteDB.
You will be able to update from @mbdavid 's repository whenever there is an update available but won't loose your signature...

**Comment by mbdavid** [comment]
Hi @nickun, take a look on 1.0.4 version.

**Comment by nickun** [comment]
Thank you very much @mbdavid !
@caverna, unfortunately I use Subversion for my project, so I cannot 'insert LiteDB as a submodule'
