### ISSUE TITLE
Unity branch merging

### ISSUE THREAD

**Issue by andreykalyta** [mbdavid/LiteDB#692]
Hi! Can I use master branch to use LiteDB in unity3d? If no, will be the unity3d supported and any changes from master merged to unity3d branch?

**Comment by mbdavid** [comment]
Hi @andreykalyta, i'm not unity3d expert, but I guess master branch already compatible with unit3d. This unity branch was created when master branch used `Emit`. But it´s already removed in master, so must be compatible.
If not working, do you know whats doing wrong? Where is the problem?

**Comment by andreykalyta** [comment]
After I tried, I got this error https://github.com/mbdavid/LiteDB/issues/380

**Comment by aviadmini** [comment]
Confirmed to happen on 3.1.0 to 3.1.4, 3.0.1 works fine

**Comment by mbdavid** [comment]
@aviadmini, the main difference between 3.0.x to 3.1.x is about map objects using linq Expression (and no more reflection Emit) and use Async in !NET35. Has unity any problem with this?

https://github.com/mbdavid/LiteDB/compare/v3.0.1...v3.1.0#diff-6706f2edc0c7e966f41921ac6e0d9006R345

**Comment by aviadmini** [comment]
@mbdavid Apparently it does, Unity runtime throws Invalid IL code exception on any linq DB query

**Comment by mbdavid** [comment]
@aviadmini That could be a problem in use `Expression` to build Getter/Setter. Version 3.0.x used reflection `Emit`. I will change some compiler variables to try enable this again

**Comment by aviadmini** [comment]
Thanks a lot @mbdavid
I believe it's best to enable both options (Emit and Expression) accessible so that even outdated Unity projects can use latest LiteDB

**Comment by mbdavid** [comment]
Is there any specific target framework that I can set in .csproj (VS2017) exclusive to Unity?

**Comment by aviadmini** [comment]
Nope, it's still .Net 3.5 
There's experimental support for .Net 4.6 and it works quite well but in my case I need to use .Net 3.5 runtime

**Comment by mbdavid** [comment]
Hi @aviadmini, I package new LiteDB version now with support to .NET35, .NET40 and NETSTANDARD. Now, .NET35 must work in Unity3D. Please, test to me in unity if mapping are working ok

I publish in nuget package. Add a local nuget source in you computer and install from here

https://github.com/mbdavid/LiteDB/releases/download/v.3.1.4/LiteDB.4.0.0.nupkg

**Comment by aviadmini** [comment]
Thanks a lot, I'll test tomorrow morning and report the results

**Comment by aviadmini** [comment]
@mbdavid tried the 4.0.0-beta1 just now. In Unity can't get any Linq queries to return results. Runs without errors but returns nothing

**Comment by mbdavid** [comment]
@aviadmini pls, try do query using Query static method (without linq) to test if documents are really inserted. I will try install Unity sdk in my vs2017 to debug better.

**Comment by aviadmini** [comment]
I checked the database and the data is inside. Queries fail tho. 

I'll try the static method asap

**Comment by andreykalyta** [comment]
@mbdavid Hi. I got this error in master branch:

> InvalidCastException: Cannot cast from source type to destination type.
LiteDB.PageService.GetPage[CollectionPage] (UInt32 pageID)
LiteDB.CollectionService.Get (System.String name)
LiteDB.LiteEngine.GetCollectionPage (System.String name, Boolean addIfNotExits)
LiteDB.LiteEngine.Transaction[Boolean] (System.String collection, Boolean addIfNotExists, System.Func`2 action)

But it happens when I call:
`public static string TypesCollectionName = "Types";
SaveData.Instance.Database.DropCollection (TypesCollectionName);`

**Comment by mbdavid** [comment]
Hi @andreykalyta, can you reproduce this error in a executable code? I created LiteDB.Perf to test to this error, can you fork and made change there to reproduce?

**Comment by andreykalyta** [comment]
@mbdavid thanks for reply. Seems like it happen when the application is suddenly turned off, so if I change the name of collection this bug will not be repeated even after few correct turning app off.
But I'll try to reproduse it in Perf

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
