### ISSUE TITLE
ASP.NET 5

### ISSUE THREAD

**Issue by andrewhart098** [mbdavid/LiteDB#70]
I’d like to use this project in aspnet 5 applications. 

I’ve started by trying to get everything to build in the dnx4.5.1 framework using the new project structure.  I’ll post my project.json file below. I've found it easier to start with dnx4.5.1 rather then to try to flesh out all the kinks using both dnx4.5.1 and dnxcore50 simultaneously.

I’ve replaced Microsoft.VisualStudio.TestTools.UnitTesting with Xunit.  It seems that Xunit is generally the recommended framework for testing aspnet 5 applications.  

https://github.com/aspnet/Testing
http://blogs.msdn.com/b/webdev/archive/2015/08/06/unit-testing-with-dnx-asp-net-5-projects.aspx

After everything is building on 4.5.1 using the new project structure and all tests are passing, my plan is  to add ‘ dnxcore50’ as an additional framework in the project.json file and continue to weed out the problems.  

This is my first time porting a project to aspnet 5 and would welcome advice on how best to go about this.  I'm currently stuck trying to get everything to run on dnx4.5.1..

Current project.json file:

{
    "version": "2.0.0-*",
    "description": "A .NET NoSQL Document Store in a single data file",
    "authors": [ "Maurício Davi" ],
    "tags": [ "LiteDB", "NoSQL" ],
    "projectUrl": "https://github.com/mbdavid/LiteDB",
    "dependencies": {
        "xunit": "2.1.0",
        "xunit.runner.dnx": "2.1.0-beta5a-build188"
    },
    "commands": {
        "test": "xunit.runner.dnx"
    },
    "frameworks": {
        "dnx451": { }
    }
}

**Comment by mbdavid** [comment]
#86
