### ISSUE TITLE
Temp file created but not passed in as parameter

### ISSUE THREAD

**Issue by vjacquet** [mbdavid/LiteDB#700]
Is there any reason not to pass the temp disk you just created as a parameter to the Shrink function?
https://github.com/mbdavid/LiteDB/blob/23b326ab99bac4b7e9ce447de6fd63c1621a199f/LiteDB/Database/LiteDatabase.cs#L235-L237

**Comment by mbdavid** [comment]
Hi @vjacquet, I forgot to pass... but it's already fixed in dev branch... I will release a beta version this week

**Comment by vjacquet** [comment]
👍
