### ISSUE TITLE
LiteDB.LiteException("Timeout.DataBase is locked for more than 00:01:00.")

### ISSUE THREAD

**Issue by wai2dance** [mbdavid/LiteDB#703]
LiteDB.LiteException("Timeout.DataBase is locked for more than 00:01:00.")

error image : 
http://myweb188linm-10059159.cossh.myqcloud.com/YiLePC_CSS_JS/EEEEE6.jpg

http://myweb188linm-10059159.cossh.myqcloud.com/YiLePC_CSS_JS/EEEEE77.jpg

I use ASP.NET MVC Web Roles Serach in this。

` #region  添加构造函数

        public MvcApplication()
        {
            AuthorizeRequest += new EventHandler(MvcApplication_AuthorizeRequest);
        }

        void MvcApplication_AuthorizeRequest(object sender, EventArgs e)
        {
            IIdentity identityUser = Context.User.Identity;
            if (identityUser.IsAuthenticated)
            {
                try
                {
                    IBLL.IUserBLL userBLL = BLLContainer.ContainerBLL.Resolve<IBLL.IUserBLL>();

                    List<Model.EntityModels.User> allUser = userBLL.GetAllUser();
                    Model.EntityModels.User u = allUser.Find(us => us.UserName == identityUser.Name);
                    var roles = userBLL.GetUserRoleByUserId(u.Id).ToArray();

                    Context.User = new GenericPrincipal(identityUser, roles);
                }
                catch
                {
                    var roles = new string[] { "AAA", "BBB" };
                    Context.User = new GenericPrincipal(identityUser, roles);
                }
            }
        }

        #endregion`

I am a Chinese student.My English is very poor.Can you helper me?
My Email is 2360450496@qq.com ,Please Helper me!!!!

**Comment by wai2dance** [comment]
This Code was Right Runing In SQLServer DataBase! 
I was full rewrite the code !   
In no  role state,Is run Ok.
When i  add this code !It's error!

**Comment by mbdavid** [comment]
This error always occurs? Is your `GetAllUser` are disposing database?

LiteDB 3.x has some problems in concurrency environment that I'm fixing in next version (is in `dev` branch)

**Comment by wai2dance** [comment]
always have........
I just rewrite some code 
mian code is :
`
        public List<string> GetUserRoleByUserId(string userId)
        {
            List<string> roleList = new List<string>();
           
            IEnumerable<Model.EntityModels.UserRole> userRole;
            
            try
            {
                
                UserRoleBaseDAL userRoleDAl = new UserRoleBaseDAL();
               userRole = userRoleDAl.GetAllEntityWhere(u => u.UserId == userId);

                RoleBaseDAL roleDAL = new RoleBaseDAL();
                foreach (UserRole ur in userRole)
                {
                    Model.EntityModels.Role roo = roleDAL.GetOneByWhere(r => r.Id == ur.RoleId);
                    if (roo != null)
                    {
                        roleList.Add(roo.RoleName);
                    }

                }
                return roleList;


            }
            catch
            {
                return null;
            }


           


        }`




` public class MvcApplication : System.Web.HttpApplication
    {
        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);


        }


        #region  添加构造函数

        public MvcApplication()
        {
            AuthorizeRequest += new EventHandler(MvcApplication_AuthorizeRequest);
        }

        void MvcApplication_AuthorizeRequest(object sender, EventArgs e)
        {
            IIdentity identityUser = Context.User.Identity;
            if (identityUser.IsAuthenticated)
            {
                try
                {
                    IBLL.IUserBLL userBLL = BLLContainer.ContainerBLL.Resolve<IBLL.IUserBLL>();

                    // List<Model.EntityModels.User> allUser = userBLL.GetAllUser();

                    Model.EntityModels.User u = userBLL.GetOneUserByUserName(identityUser.Name);
                    var roles = userBLL.GetUserRoleByUserId(u.Id).ToArray();

                    Context.User = new GenericPrincipal(identityUser, roles);
                }
                catch
                {
                    var roles = new string[] { "AAA", "BBB" };
                    Context.User = new GenericPrincipal(identityUser, roles);
                }
            }
        }

        #endregion
    }`





`
        public Model.EntityModels.User GetOneUserByUserName(string Username)
        {

            UserBaseDAL userDAL = new UserBaseDAL();
            return userDAL.GetOneByWhere(u => u.UserName == Username);

        }
`




` public class UserBaseDAL : Respository<User>`



`public class Respository<T> : IRepository<T> where T : class
    {

        public string conStr;
        public Respository()
        {
            conStr = LiteDBHelper.GetConString();
        }

        public bool Insert(T entity)
        {
           try
            {
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    var result = db.Upsert( entity );

                    //if( result.AsString == entity. )
                    return result;
                }

               
            }
            catch
            {
                return false;
            }
        }

        public bool Update(T entity)
        {
            try
            {
                
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    bool result = db.Update(entity);

                    return result;

                }

               
            }
            catch
            {
                return false;
            }
        }
        public bool Delete(Expression<Func<T, bool>> where)
        {
            try
            {
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    int result= db.Delete<T>( where );

                    return result > 0 ? true : false;
                }
                
            }
            catch
            {
                return false;
            }
        }

        public bool  DeleteAllEntity()
        {
            try
            {
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    int result = db.Delete<T>(Query.All());

                    return result > 0 ? true : false;
                }

            }
            catch
            {
                return false;
            }
        }


        public IEnumerable<T> GetALLEntity()
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    var result = db.Query<T>().ToEnumerable();
                    return result;

                }

                //return result > 0 ? true : false;
            }
            catch
            {
                return null;
            }
        }

        public IEnumerable<T> GetAllEntityWhere(Expression<Func<T, bool>> where)
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    var result = db.Query<T>(  ).Where(where)  .ToEnumerable();
                    return result;

                }

                //return result > 0 ? true : false;
            }
            catch
            {
                return null;
            }
        }

        public T GetOneByIndexKey(Expression<Func<T, bool>> where)
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    var result = db.Query<T>().Where(where).Single();
                    return result;

                }

                //return result > 0 ? true : false;
            }
            catch
            {
                return null;
            }
        }

        public T GetOneByWhere(Expression<Func<T, bool>> where)
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    var result = db.Query<T>().Where(where).Single();
                    return result;

                }

                //return result > 0 ? true : false;
            }
            catch
            {
                return null;
            }
        }

        public IList<T> GetPageEntities(int pageIndex, int PageSize)
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {

                    int totalCount = db.Query<T>().Count();
                    //计算页码
                    int pages = (int)Math.Ceiling((double)totalCount / (double)PageSize);

                    if (pageIndex > pages)
                        return null;
                    else
                    {
                        //Reverse 倒序排列
                       var result = db.Query<T>().ToList().Skip(  (pageIndex -1)*PageSize    ).Take(PageSize).Reverse().ToList() ;

                        // allProduct = con.FindAll()
                        //.OrderByDescending(p => p.Id)
                        //.Skip((excludedRows - 1) * pageItemSize)
                        //.Take(pageItemSize);

                        return result;
                    }
                    

                }
                
            }
            catch
            {
                return null;
            }
        }

        public IList<T> GetPageEntities( int pageIndex, int PageSize, Expression<Func<T, bool>> wheresearch)
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {

                    int totalCount = db.Query<T>().Count();
                    //计算页码
                    int pages = (int)Math.Ceiling((double)totalCount / (double)PageSize);

                    if (pageIndex > pages)
                        return null;
                    else
                    {
                        //Reverse 倒序排列
                        var result = db.Query<T>().Where(wheresearch).ToList().Skip((pageIndex - 1) * PageSize).Take(PageSize).Reverse().ToList();

                       

                        return result;
                    }


                }

            }
            catch
            {
                return null;
            }
        }

       
    }`

**Comment by wai2dance** [comment]
My LiteDB version is 3.1.4

**Comment by mbdavid** [comment]
Ok, try use `ToList()` instead  `ToEnumerable()` in query execution because your are closing datafile until get data (when use enumerable)

**Comment by wai2dance** [comment]
Thanks @mbdavid 

It seems RunOk! I will rewrite other SQLServer Code to LiteDB! Test Other Page
Thanks again!
My web image :  
http://myweb188linm-10059159.cossh.myqcloud.com/YiLePC_CSS_JS/OKSSS5.jpg

**Comment by mbdavid** [comment]
Looks nice (I didn't understand a single word 😄 ) !!

**Comment by wai2dance** [comment]
Excuse me again..
Do you have A better method of paging data??
Now ! My Method is :  


`  public List<T> GetPageEntities(int pageIndex, int PageSize)
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {

                    int totalCount = db.Query<T>().Count();
                    //计算页码
                    int pages = (int)Math.Ceiling((double)totalCount / (double)PageSize);

                    if (pageIndex > pages)
                        return null;
                    else
                    {
                        //Reverse 倒序排列
                       var result = db.Query<T>().ToList().Skip(  (pageIndex -1)*PageSize    ).Take(PageSize).Reverse().ToList() ;


                        return result;
                    }
                    

                }
                
            }
            catch
            {
                return null;
            }
        }

        //by serach
        public List<T> GetPageEntities( int pageIndex, int PageSize, Expression<Func<T, bool>> wheresearch)
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {

                    int totalCount = db.Query<T>().Count();
                    //计算页码
                    int pages = (int)Math.Ceiling((double)totalCount / (double)PageSize);

                    if (pageIndex > pages)
                        return null;
                    else
                    {
                        //Reverse 倒序排列
                        var result = db.Query<T>().Where(wheresearch).ToList().Skip((pageIndex - 1) * PageSize).Take(PageSize).Reverse().ToList();

                       

                        return result;
                    }


                }

            }
            catch
            {
                return null;
            }
        }
`

**Comment by mbdavid** [comment]
You can use Skip/Take methods from Query returns (not from ToList). IT´s much more fast.

Also, in your implementation with Where, you must pass Where in Count too.
