### ISSUE TITLE
Select file storage location

### ISSUE THREAD

**Issue by asensionacher** [mbdavid/LiteDB#704]
Is it possible to select where the files are saved?

**Comment by mbdavid** [comment]
Did you mean in `FileStorage` or database file?

**Comment by asensionacher** [comment]
Hi, thanks for your response, I mean for a database file. My issue is that i'm trying to use litedb on an Azure WebApp and it sends me this error:

> Access to the path 'D:\Windows\system32\database.db' is denied.

So I want to save the DataBase in  "~/Databases/database.db".

Is it possible?

**Comment by mbdavid** [comment]
I use

`var filename = context.Server.MapPath("~/App_Data/myfile.db");`

Look here: https://github.com/mbdavid/LiteDB-WebShell/blob/master/api.ashx#L22

**Comment by asensionacher** [comment]
Thanks a lot, I've used:
``var filename = HttpRuntime.AppDomainAppPath + dbname + ".db";

You're work is very helpful!
