### ISSUE TITLE
Support abstruct base class

### ISSUE THREAD

**Issue by a44281071** [mbdavid/LiteDB#71]
Mapper and Serialize is not support absruct base class.
```c#
public abstruct class DataBase { }
public class EduData : DataBase { }
public class ProjectData : Database { }
db.GetCollection<DataBase>("datas");
```
Data in MongoDB has a flexible schema. But C# is a strongly typed programming language. How to connect them？ The answer is inheritance.

MongoDB c# driver achieved it like this:

```c#
BsonClassMap.RegisterClassMap<EduData>();
```

**Comment by mbdavid** [comment]
Hi @a44281071, after a long time I fixed this. It's on `mater` branch.

**Comment by sergiorykov** [comment]
Hi.

Can you publish inheritance support as rc2?
