### ISSUE TITLE
Overflow when number is too long

### ISSUE THREAD

**Issue by ti24horas** [mbdavid/LiteDB#711]
https://github.com/mbdavid/LiteDB/blob/58747f76c2bb1bd5f547de2ce654ef88c202dcb5/LiteDB/Document/Json/JsonReader.cs#L72

When an object contains a number larger than int.maxValue, overflow occurs.
What I found is that although LiteDB supports storing of long, when the object contains a too long number, overflow occurs.

**Comment by mbdavid** [comment]
In this case it's because LiteDB use long data type in a special document type, like:

{ a: {$numberLong: 123456789123 } }

https://github.com/mbdavid/LiteDB/blob/58747f76c2bb1bd5f547de2ce654ef88c202dcb5/LiteDB/Document/Json/JsonReader.cs#L159

I copied this from mongodb

https://docs.mongodb.com/manual/reference/mongodb-extended-json/

**Comment by ti24horas** [comment]
OK, maybe is not a litedb problem itself.
The case is:
when Serilog.Sinks.LiteDB needs to create an log event, it creates a string file containing several key/value pairs. Then it uses LiteDB's JsonReader to tranform object back to BsonDocument. This throws an exception in the line I was referring.

When user adds a log property that's long, litedb logging do not append "$numberLong".

Long story short, when serializing a json object to litedb that contains long values:

``` json

{
    "_id" : "some doc",
    "value" : "test",
    "longValue" : { "$numberLong" :123456678901234 }
}

```

Is that correct? If so, I should create an issue to Serilog.Sinks.LiteDB and do pull request for that.

BTW, ótimo trabalho! Você é uma das poucas referências brasileiras que conheço e que possui software open source de boa qualidade. Se quiser, podemos falar um pouco mais do seu projeto (skype: rafael.net). 
Obrigado!

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
