### ISSUE TITLE
BUG: Descending Query fails in LiteDB 4 beta

### ISSUE THREAD

**Issue by kuiperzone** [mbdavid/LiteDB#715]
Hi,

I have a query which fails with LiteDB 4 but works as expected with 3.1.

I have a unit test where I have series of documents with integer _ids like so:

n
35
40
n

I run a query looking for the first record with an id of LESS THAN 40 in **reverse order**. The correct result is 35:

I have a wrapper method which abstracts the call to LiteDB and looks like:

```
public T ReadLessThan(long id)
{
                using (var emtr = _collection.Find(Query.And(Query.All("_id", Query.Descending),
                    Query.Between("_id", id - 1, long.MinValue + 1)), 0, 1).GetEnumerator())
                {
                    if (emtr.MoveNext())
                    {
                        return emtr.Current;
                    }
                }
```

Note the "id -1 " in the Query.Between call (i.e. less than).

In LiteDB 3.1, if I call this method with an id of 40, the result is a doc instance with an ID of 35. In LiteDB 4, however, the ID is 40.

Cheers

**Comment by mbdavid** [comment]
Humm... is missing Order in QueryLess/Greater to work better in this case. This solution if not the efficient.

I will review this because I change the way how query engine must return data: in v4 will only use 1 single index (in you example, Query.All()). But Query.All() is not efficient to return a single value

**Comment by kuiperzone** [comment]
>This solution if not the efficient.

Do you mean my code is not efficient? Or that the LiteDB implement is not efficient?

If you mean my code, I'd sure appreciate any suggestion to make it better?

**Comment by mbdavid** [comment]
I mean, if you want get an immediate value after another value, your code is not best solution. But, current version doesnt give you a better solution. If this core needs run in a much times, the best solution for this is: found X value (using index) and down 1 position. That's fastest way:

`db.col.Find(Query.LT(39, Query.Descending)).FirstOrDefault()`

But there is not implementation for Query.Descending in QueryLess/Greater. I will add this

**Comment by kuiperzone** [comment]
OK. Thanks for that.

I also in reverse within a range and return an enumerator. For me, performance of this is critical. What my use case represents is a series of data documents where the integer ID is actually a precision timestamp. Ideally, I need to iterate backward in order to perform data analysis. It does not work picking a past starting point and iterating forward because I don't necessarily know what this should be in advance.

```
Hence, I have wrapper abstraction methods which can handle descending results where start > end and look like:

        public IEnumerable<T> ReadRange(long start, long end, int limit)
        {
             if (start <= end)
            {
                // Forward
                return _collection.Find(Query.Between("_id", start, end), 0, limit);
            }

            // Backward
            long temp = start;
            start = end;
            end = temp;

            return _collection.Find(Query.And(Query.All("_id", Query.Descending),
                Query.Between("_id", start, end)), 0, limit);
}

```

**Does this work efficiently? Is it appropriate to implement any changes to LiteDB while you're making those described above? **

**Comment by mbdavid** [comment]
Hi @kuiperzone, it's not efficient use Query.All in this case (not in v3 neither in v4). But I think v3 already implement between as you need:

```C#
internal override IEnumerable<IndexNode> ExecuteIndex(IndexService indexer, CollectionIndex index)
{
    // define order
    var order = _start.CompareTo(_end) <= 0 ? Query.Ascending : Query.Descending;

    // find first indexNode
    var node = indexer.Find(index, _start, true, order);

    // returns (or not) equals start value
    while (node != null)
    {
        var diff = node.Key.CompareTo(_start);

        // if current value are not equals start, go out this loop
        if (diff != 0) break;

        if (_startEquals)
        {
            yield return node;
        }

        node = indexer.GetNode(node.NextPrev(0, order));
    }

    // navigate using next[0] do next node - if less or equals returns
    while (node != null)
    {
        var diff = node.Key.CompareTo(_end);

        if (_endEquals && diff == 0)
        {
            yield return node;
        }
        else if (diff == -order)
        {
            yield return node;
        }
        else
        {
            break;
        }

        node = indexer.GetNode(node.NextPrev(0, order));
    }
}
```

If end value is bigger than start value, interate will start at end value and are going back in index cursor. This line `node = indexer.GetNode(node.NextPrev(0, order))` move cursor in defined order. Try write only this:

```c#
public IEnumerable<T> ReadRange(long start, long end, int limit)
{
    return _collection.Find(Query.Between("_id", start, end), 0, limit);
}
```

**Comment by kuiperzone** [comment]
Hey thanks!

But it's not clear what you mean...

>If end value is bigger than start value, interate will start at end value and are going back in index cursor.

Surely you mean "If end value is **less than** start value ... then go backwards"?

>use Query.All in this case (not in v3 neither in v4). But I think v3 already implement between as you need:

Confused... "Not in v3 neither in v4"?

**Is it implemented in v3? (And will it implemented in v4)?**

(Will test v3 and let you know result.)

Thanks

**Comment by mbdavid** [comment]
Yep, I was sleeping... :)

The right is: **If end value is less than start value ... then go backwards".. It´s possible see here:

`var order = _start.CompareTo(_end) <= 0 ? Query.Ascending : Query.Descending;`

Query.All is not a good solution in any version. Query.All will iterate over all index keys.

The difference about v3 and v4 is that in v4 Between has support for open/close interval.

**Comment by kuiperzone** [comment]
Just done some testing. Yes, simplifying the ReadRange() function as you suggest does indeed work in reverse correctly.

I've also done some simple performance testing against LiteDB 3.1. Iterating in reverse, the simplified call is only about 4% faster in my case! I expected better.

As a side, I mentioned that I have abstraction wrapper/interface around my LiteDB calls. This allows me to swap out LiteDB and read/write data to a local MySQL server in the same way (I'm storing object data in a table field as BSON). In terms of reading, MySQL and LiteDB are similar in performance (MySQL is actually quicker). Thought this was interesting as I was really expecting LiteDB to be much faster.

Will try against LiteDB v4.

**Comment by kuiperzone** [comment]
Update, reading (backward) with version 4 is approx 4x SLOWER than both LiteDB3 and MySQL.

**Comment by mbdavid** [comment]
I excepted more difference too. Maybe is how Linq resolve `Intersect` method (used in v3). In v4 this difference must be much bigger because I use index scan (on query.all) + full scan on other side (on query.between).

About performance with MySQL, I think it´s normal mysql be faster: has a better cache control and can keep all pages in-memory. Also, can work with async disk read.

My plans to future is create a "spin-off" version of LiteDB to run as server over HTTP. With a single process, I can open file as exclusive mode, keep readed pages in memory, lock control using C# (and in File)....

**Comment by kuiperzone** [comment]
Thanks for the update?

**Are you saying that querying LiteDB will be slower in v4 than v3?**

(PS - noticed that writing to LiteDB was around 4x faster than MySQL).

**Comment by mbdavid** [comment]
4x slower using Query.all + Query.Between or just Query.Between?

**Comment by kuiperzone** [comment]
4x slower running below over 10,000s iterations:

`return _collection.Find(Query.Between("_id", start, end), 0, limit);`

where start > end (backward).

**Comment by mbdavid** [comment]
Ok, it´s something wrong. I will take a look about query performance.

It´s possible that v4 can be slower in some cases. v4 has more reads/checks in this disk to avoid concurrency problems.

If it´s possible, in your case, always choose "Exclusive" mode that avoids many checks.

**Comment by kuiperzone** [comment]
Good stuff! Will look out for the updates. Thanks for LiteDB.

**Comment by mbdavid** [comment]
Hi @kuiperzone, I made some test and yes, v4 is slower than v3. Take a look:

```
V3

Docs: 20000, Fetch: 0020, Insert: 000774ms, Asc: 000373ms, Desc: 000278ms
Docs: 20000, Fetch: 0020, Insert: 000311ms, Asc: 000267ms, Desc: 000195ms
Docs: 20000, Fetch: 0020, Insert: 000228ms, Asc: 000149ms, Desc: 000149ms

Docs: 20000, Fetch: 1000, Insert: 000224ms, Asc: 004686ms, Desc: 004794ms
Docs: 20000, Fetch: 1000, Insert: 000246ms, Asc: 005091ms, Desc: 005061ms
Docs: 20000, Fetch: 1000, Insert: 000251ms, Asc: 004813ms, Desc: 004815ms

V4

Docs: 20000, Fetch: 0020, Insert: 000672ms, Asc: 000384ms, Desc: 000310ms
Docs: 20000, Fetch: 0020, Insert: 000326ms, Asc: 000200ms, Desc: 000198ms
Docs: 20000, Fetch: 0020, Insert: 000246ms, Asc: 000195ms, Desc: 000199ms

Docs: 20000, Fetch: 1000, Insert: 000271ms, Asc: 010409ms, Desc: 010570ms
Docs: 20000, Fetch: 1000, Insert: 000252ms, Asc: 010214ms, Desc: 010167ms
Docs: 20000, Fetch: 1000, Insert: 000253ms, Asc: 009916ms, Desc: 009886ms

(Asc/Desc in 2000 loops)
```

And this happened because v4 use a complete different way to find/cache results. In v4, each 200 records are stored inside a local cache before yield return (QueryContext class), release lock.... and when fetch for more, lock datafile again, execute same query skipping already returned documents and cache next 200 documents before return. This all operations are very expensives but needed to guarantee concurrency control.

I will try take a look beter if it's possible be more optimized in v4, but will not be fast as v3. I will tell here.

**Comment by mbdavid** [comment]
I made same changes and improvements about "when need query reset", with better results: 

```
Docs: 20000, Fetch: 0020, Insert: 000742, Asc: 000418, Desc: 000345
Docs: 20000, Fetch: 0020, Insert: 000302, Asc: 000203, Desc: 000193
Docs: 20000, Fetch: 0020, Insert: 000263, Asc: 000200, Desc: 000206

Docs: 20000, Fetch: 1000, Insert: 000272, Asc: 006403, Desc: 006691
Docs: 20000, Fetch: 1000, Insert: 000312, Asc: 006933, Desc: 006877
Docs: 20000, Fetch: 1000, Insert: 000319, Asc: 006877, Desc: 006455
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
