### ISSUE TITLE
Question:  Why can't I nest more than 20 documents?

### ISSUE THREAD

**Issue by iupchris10** [mbdavid/LiteDB#716]
I see that MAX_DEPTH is a constant of 20 in BsonMapper.  Why is this? Is this an arbitrarily chosen number, or is there a technical reason we cannot override this number and set it to say, 40?

**Comment by mbdavid** [comment]
Hi @iupchris10, it´s just an arbitrarily number, can be increse to any number.... it´s just to simple way to detect circular reference.

**Comment by iupchris10** [comment]
Thanks @mbdavid. That makes sense. It would be a nice enhancement to make this a public property on BsonMapper.cs, with a default setting of 20, rather than a constant.

Keep up the good work. LiteDB is working out great for me so far as a cross-platform doc store.
