### ISSUE TITLE
AppVeyor misconfigured

### ISSUE THREAD

**Issue by mcmonkey4eva** [mbdavid/LiteDB#717]
Hello, I was looking at the commit logs and noticed every build has a "failure" note from AppVeyor (The red X). Probably just a configuration issue, not critical but it'd probably be a good idea to fix that!

Oh, by the way: Great work on the 4.0 update! Dropped it in over my 3.0 install and it works cleanly in initial testing!

**Comment by mbdavid** [comment]
Hi @mcmonkey4eva, yes, I saw this. I tried my options in AppVeyor but doesnt work, You know how to fix? I can grant access

**Comment by mbdavid** [comment]
Hi @mcmonkey4eva, yes, I saw this. I tried my options in AppVeyor but doesn't work, You know how to fix? I can grant access

**Comment by mcmonkey4eva** [comment]
I might be able to?
I've used AppVeyor a bit, though mainly through the repo-file option (as opposed to webpage options).

It looks from the error that you just need to enforce a NuGet restore.
This should be doable by adding `nuget restore LiteDB.sln` to the `before_build` section.
(Via the web tools, that'd be `Build -> Before Build Script`)

**Comment by mbdavid** [comment]
Hi @mcmonkey4eva, thanks man! Now it's working again!
