### ISSUE TITLE
How to do a Sum of a field in multiple documents?

### ISSUE THREAD

**Issue by softwareguy74** [mbdavid/LiteDB#719]
Is there an easy way to return a sum of a value from a document field based on certain criteria?  For example, let's say I have the following documents defined:

Id | Name | List | HasAttachments | AttachmentCount

I want to return a single value that represents the Sum of AttachmentCount of the above documents where List = 1 and HasAttachments = true.

Thanks!

**Comment by mbdavid** [comment]
Hi @softwareguy74, there is no internal group by function in LiteDB. In this case you need use Linq to Object to do this:

`db.Find(Query.EQ(...)).Sum(x => x["ValueToSum"].AsInt)`

**Comment by softwareguy74** [comment]
That worked like a charm, thanks!
