### ISSUE TITLE
can only the public object property be serialized?

### ISSUE THREAD

**Issue by lidanger** [mbdavid/LiteDB#72]
why not serialize all public members of the object?

**Comment by mbdavid** [comment]
Hi @lidanger, yes, LiteDB serialize all public properties. See serialization rules in "Mapping conventions":

https://github.com/mbdavid/LiteDB/wiki/Object-Mapping

**Comment by lidanger** [comment]
Yes, thank you. I see."Class fields are not converted to document"
Now I want to know why the class fields is ignored, is there some consideration?
