### ISSUE TITLE
How to get document Id at(on) Insert() method?

### ISSUE THREAD

**Issue by ddrrqq** [mbdavid/LiteDB#720]
At LiteDB 3.x, I can get a document Id after Insert()
ex. Use the .AsObjectId get the ID type of ObjectId.

Now, I used this method report to me a error, bcz it is void XD,
but XML document writen:
[- Returns document Id]
XDD

So, v4 how to just ONE insert method get the ID?

Thanks!

**Comment by mbdavid** [comment]
Hi @ddrrqq, can you paste your code?

**Comment by ddrrqq** [comment]
OK,
// Previous version
public ObjectId MyAddMethod() =>
    _Lite.SpareCollection.Insert(new Spare { MyId = ObjectId.NewObjectId() }).AsObjectId;

// Current version
public ObjectId MyAddMethod()
{
    ObjectId id = ObjectId.NewObjectId();
    _Lite.SpareCollection.Insert(new Spare { MyId = id }); // Here is void retval, but XML docment:
        //
        // Summary:
        //     Insert a new document to this collection. Document Id must be a new value in
        //     collection - Returns document Id
    return id;
}

**Comment by mbdavid** [comment]
Ok, I removed because I was changing how use autoId and forgot to add back. Now is on master branch.

**Comment by ddrrqq** [comment]
WOWOWOWWOWOWOOWWO
Thank You so much, I love you!
