### ISSUE TITLE
Auto Id. What do I wrong? (version 3.1.?)

### ISSUE THREAD

**Issue by qart2003** [mbdavid/LiteDB#721]
Hi @mbdavid , I have code
    private void bnCopy_Click(object sender, EventArgs e)
    {
      if (lbxDocs.SelectedIndex == -1)
        return;
      var docs = dbDocs.FindAll().ToList();
      var doc = docs[lbxDocs.SelectedIndex].Copy();//Extension, it works fine. Does Copy of object of any class
      doc.h1 = "Копия " + doc.h1;//"Копия" means "Copy of "
      dbDocs.Insert(doc);//got error, the Id is duplicate (probably internal property BsonId has been duplicated, But why? I thinkin Insert should add new object into collection with next Id?)
      ShowDocs();
    }

**Comment by mbdavid** [comment]
Hi @qart2003,

AutoId works only if you pass an "empty" Id value. Empty has different values for each data type (0 for int, Guid.Empty for Guid or ObjectId.Empty to ObjectId). If you pass a valid value, LiteDB will try insert using this valid Id.

**Comment by qart2003** [comment]
@mbdavid , my hands did something wrong :) 
thanks!
