### ISSUE TITLE
Tests failing on clone (?)

### ISSUE THREAD

**Issue by botne** [mbdavid/LiteDB#722]
Hi @mbdavid!
Great project!

I am struggeling with count/query in the beta on nuget so thought I should check out a build from codebase. 

Did a clone, build is ok - but 6+ of the tests fail.
Is this expected in the current state of the code, or should it work?

**Comment by mbdavid** [comment]
Hi @botne, it´s possible current master branch are not running all tests. I made some changes and didn´t check yet. I will release next beta version soon.

**Comment by botne** [comment]
Thanks for the prompt reply, @mbdavid.
Will look more at the code - hope to help with the project at some point.

Keep up the good work!

**Comment by JensSchadron** [comment]
At last, all tests on master are green once again since a week.
