### ISSUE TITLE
Concurrent async inserts can fail

### ISSUE THREAD

**Issue by faxedhead** [mbdavid/LiteDB#73]
Using LiteDB to insert a DTO to a LiteDatabase using the following code hosted in an OWIN self-hosted web server:

            return await Task.Run(() =>
            {
                using (var db = new LiteDatabase(DbFileName))
                {
                    var col = db.GetCollection<ProcessedDetection>("detections");
                    var result = col.Insert(detection);
                    return result.AsInt32;
                }
            });

If calls to the webserver overlap (e.g. from two different clients), I thought the file locking mechanism in LiteDB, and the fact that I'm using a new instance of LiteDatabase on every insert, would ensure that concurrent inserts would always work.  However, it is very easy to reproduce an exception:

Cannot insert duplicate key in unique index '_id'. The duplicate value is '2861'

Is my code wrong, or should the file locking handle multiple threads in this case?  Do have to use an AsyncLock on all writes to the database?

**Comment by faxedhead** [comment]
FYI I can confirm that using an async lock as follows prevents this issue from occurring, but I'd still like to know why I have to do this:

        private static readonly AsyncLock _mutex = new AsyncLock();

        internal async Task<int> Insert(ProcessedDetection detection)
        {
            using (await _mutex.LockAsync())
            {
                using (var db = new LiteDatabase(DbFileName))
                {
                    var col = db.GetCollection<ProcessedDetection>("detections");
                    var result = col.Insert(detection);
                    return result.AsInt32;
                }
            }
        }

**Comment by mbdavid** [comment]
Hi @faxedhead, how did your `_id` is made? Are you using int `AutoId`? I'm checking in source code and it's possible: AutoId is not in same transaction. To avoid that, you can you for now:

```
            using (var db = new LiteDatabase(DbFileName))
            {
                db.BeginTrans();
                var col = db.GetCollection<ProcessedDetection>("detections");
                var result = col.Insert(detection);
                db.Commit();
                return result.AsInt32;
            }
```

I'm working on v2 (`dev` branch) version and this will be fixed there (transactions are no more explicit).

**Comment by mbdavid** [comment]
No, my code doesn't work. Transactions, in v1, locks datafile only to write. For next version I'm planning implement a FindAndModify operation, thats lock results and change in a safe operation.

For now, you need use your solution.

**Comment by faxedhead** [comment]
Thanks for the update @mbdavid.  LiteDB is a really nice 'fit-for-purpose' library, I especially like the server-less design that makes this so simple to use.  Thanks for creating it.

**Comment by stojy** [comment]
I've seen the same issue in our code which was worked around by putting a lock around the entire operation.

Ditto, LiteDB is an excellent library.  Looking forward to the v2 release.

**Comment by mbdavid** [comment]
Thanks guys! In v1, locks are for write only, so when you use `AutoId` for an `Int32`, LiteDB calls `Max()` and increse +1. But it's a read operation only. So, in multi task enviorment, this problem can happend. To avoid, use `ObjectId` or `Guid` auto generation id (or a `lock` statment).
In v2 has `FindAndModify`, an operation that locks rows after read and unlock only when write operation ends,

**Comment by faxedhead** [comment]
This bug still exists on v2.0.0-beta unfortunately.

**Comment by mbdavid** [comment]
Yes, this problem still in v2 . `FindAndModify` was not implemented yet. I'm still thinik in how resolve this.
1- Implement `Max()` inside transaction?
2- Implement a `sequence` like Oracle? (with no re-use)

I not found how Mongo implement this. I think mongo has only `ObjectId`...

**Comment by faxedhead** [comment]
Implementing Max() inside transaction sounds like what is needed.  If Max() shouldn't be inside transation all the time, perhaps add an internal way to call Max() so that the Insert() method can achieve it's goal.

**Comment by suxiaojack** [comment]
Yes, I have the same problem. If a file has a duplicate id problem, it will be locked, and then can not be operated. How to fix this file to make it available again?

**Comment by adoconnection** [comment]
Hi, here is the code to reproduce "duplicate key in unique index '_id'" issue:
(2.0.0-rc)

```javascript
    class Program
    {
        static void Main(string[] args)
        {
            Thread t1 = new Thread(Write1);
            Thread t2 = new Thread(Write2);
            Thread t3 = new Thread(Read1);

            t1.Start();
            t2.Start();
            t3.Start();

            using (var db = new LiteDatabase(@"MyData1.db"))
            {

                LiteCollection<Customer> col = db.GetCollection<Customer>("customers");

                var customer = new Customer
                {
                    Name = "write1 Doe",
                    Phones = new string[] {"8000-0000", "9000-0000"},
                    IsActive = true
                };

                col.Insert(customer);
                Thread.Sleep(30);
            }

            Console.WriteLine("----------");
            Console.ReadKey();
        }

        static void Write1()
        {
            using (var db = new LiteDatabase(@"MyData1.db"))
            {

                LiteCollection<Customer> col = db.GetCollection<Customer>("customers");

                var customer = new Customer
                {
                    Name = "write1 Doe",
                    Phones = new string[] {"8000-0000", "9000-0000"},
                    IsActive = true
                };

                col.Insert(customer);
                Thread.Sleep(30);
            }
        }

        static void Write2()
        {
            using (var db = new LiteDatabase(@"MyData1.db"))
            {

                LiteCollection<Customer> col = db.GetCollection<Customer>("customers");

                var customer = new Customer
                {
                    Name = "write2 Doe",
                    Phones = new string[] {"8000-0000", "9000-0000"},
                    IsActive = true
                };

                col.Insert(customer);
                Thread.Sleep(30);
            }
        }


        static void Read1()
        {
            using (var db = new LiteDatabase(@"H:\ConsoleApplication85\ConsoleApplication85\bin\Debug\MyData1.db"))
            {

                LiteCollection<Customer> col = db.GetCollection<Customer>("customers");

                Console.WriteLine(string.Join(", ", col.FindAll().Select(c => c.Id)));
            }
        }
    }
```
