### ISSUE TITLE
Question. Best way to make query.

### ISSUE THREAD

**Issue by Warmcher** [mbdavid/LiteDB#730]
Hi.
My LINQ looks like this.
var entries = GlobalRating.FindAll()
                .OrderByDescending(x => x.Rating)
                .Select((entry, index) => new {entry, index})
                .Skip(start - 1)
                .Take(end - start + 1)
It takes entries from Start to End in ordered by rating result;
Is it possible to make much better option with GlobalRating.Find()?

**Comment by mbdavid** [comment]
Try this:

`GlobalRating.Find(Query.All("Rating", Descending), start - 1, end - start + 1)`
