### ISSUE TITLE
How a Collection DbRef to FileStorage

### ISSUE THREAD

**Issue by kentplaza** [mbdavid/LiteDB#731]
Can a Collection DbRef to FileStorage?
example I have a collection and a File Storage with the surrogate key as docId.

Collection:
========
docId
author
publisher

File Storage:
==========
_id
docId
filename
mimeType
length
chunkc

**Comment by mbdavid** [comment]
Hi @kentplaza, sorry about long delay, I was in vacation. `LiteFileInfo` has no default ctor. I recommend you to add an method in your class to get file when you need get the file (passing LiteDatabase/LiteEngine as parameter)

**Comment by kentplaza** [comment]
got it.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
