### ISSUE TITLE
[Question] Is there any way to know the ID right after Upsert(obj)?

### ISSUE THREAD

**Issue by gabrielsalmeida** [mbdavid/LiteDB#732]
Hello,
I'm trying to create some library to allow me to use Firebase Realtime Database, and for that I'm using LiteDB to store the objects.
I want to pass the Id generated to another function, the main problem is that the obj in my library is a generic type object, so I can't figure a way to catch the Id from this generic object.

By the way! Nice work with LiteDB!

**Comment by mbdavid** [comment]
Oi Gabriel, tens como postar um pedaco do teu codigo? Nao entendi bem o que tu precisa com o Upsert. Chegou a verificar a implementacao do upsert?

**Comment by gabrielsalmeida** [comment]
Olá, desculpa a demora.

Hoje estou fazendo isso. Eu vi a implementação do upsert.
public async Task<StatusEnum> UpsertAsync(T obj)
        {
            
                collection.Upsert(obj);                
                var mobj = BsonMapper.Global.ToDocument<T>(obj);
                HttpClient client = new HttpClient();
                var response = await client.PutAsync(firebaseDatabase.DatabaseURL + "/" + mobj["_id"].AsString+".json", new StringContent(JsonConvert.SerializeObject(obj), Encoding.UTF8, "application/json")).ConfigureAwait(false);
                if (response.IsSuccessStatusCode)
                {
                    return StatusEnum.ALLSUCCESS;
                }
                else
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                    {
                        return StatusEnum.LOCALSAVED;
                    }
                    return StatusEnum.LOCALSAVED;

                }
            
        }

**Comment by mbdavid** [comment]
Oi Gabriel, estava de férias e voltei somente hoje. Se tu não conseguiu resolver isso, acho que a solução pode ser utilizar direto a classe de engine.

```
var mobj = BsonMapper.Global.ToDocument<T>(obj);

db.Engine.Upset("collectionName", mobj);
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
