### ISSUE TITLE
.NET Standard 2.0 Support?

### ISSUE THREAD

**Issue by timnev** [mbdavid/LiteDB#733]
.Net Standard 2.0 has been finalized and available in VS 2017 with the last update. Any plans to release this great little DB with it for all platforms?

**Comment by marufbd** [comment]
4.0.0 beta on nuget seems to be compatible with .Net standard. But plain Insert(object) gives exception that Bson Id cannot be null, I am using Insert(Guid.New(), myObject) that works fine.

**Comment by mbdavid** [comment]
Hi guys, v4 is NetStandard 1.3 compatible, but I will change to 2.0 before release final version. In NETStandard v2 `FileStream.Lock` is supported and it's much better than 1.3

**Comment by Tirraon** [comment]
@mbdavid Hi!
Please notice, that .Net Standard 2.0 is not supported in UWP min. target version older than 16299.
Is it possible to support 1.3 (or 1.4) with minimal functional for it?

**Comment by mbdavid** [comment]
LiteDB current v4 version works fine with netstandard 1.3 and 2.0.

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/LiteDB.csproj#L60

Only v5 will need netstandard2
