### ISSUE TITLE
Concurrency not working

### ISSUE THREAD

**Issue by RomikB** [mbdavid/LiteDB#735]
```
public class DbWorker
{
        private LiteDatabase db = new LiteDatabase("data.db");
        public IEnumerable<Db.TelegramUser> GetUsers()
        {
            var col = db.GetCollection<Db.TelegramUser>("users");
            return col.FindAll();
        }
        public IEnumerable<Db.CommandSave> GetCommandSaves(string username)
        {
            var col = db.GetCollection<Db.CommandSave>("saves");
            return col.Find(a => a.Username == username);
        }
}

foreach (var user in dbWorker.GetUsers())
{
  Task.Run(() => {
    var username = user.username;
    foreach (var save in GetCommandSaves(username))
    {
      somecode;
    }
  });
```

I have two users, one with empty saves, second with saves. When i exec this code "somecode" not executed, litedb returns empty results.
When I delete first user than somecode is executed (litedb returns saves).

.Net Core 1.x project, windows 10, litedb 3.1.4 from nuget

**Comment by andreykalyta** [comment]
according to my issuses #729 and #734 try a => a.Username.ToString() == username

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
