### ISSUE TITLE
 KeyNotFoundException when performing FindAll() on collection

### ISSUE THREAD

**Issue by g1ga** [mbdavid/LiteDB#737]
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
   in System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   in LiteDB.LiteEngine.<Find>d__9.MoveNext()
   in LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   in MbsCrm.Data.RepositoryClienti.GetAllCustomers() in C:\RepositoryClienti.cs:riga 35

**Comment by g1ga** [comment]
I've narrowed down to this: for some reason blockAddress.PageID has value "28" while the dictionary has only 4 entries
class DataService, method GetBlock (row 139)
![screenshot_2](https://user-images.githubusercontent.com/1528645/31073450-2a8b2dde-a76c-11e7-8cc5-d4fc592583e0.png)

**Comment by mbdavid** [comment]
Sorry @g1ga, I pass this issue. Did you try this in v4 or are you using v3?

**Comment by mbdavid** [comment]
Also, if you are using in v3, it´s a concurrency access (it's happen every time?) If yes, try v4 beta version (i'm releasing final version soon)

**Comment by alex-erygin** [comment]
I have same issue in 4.0.0.

Stack trace: 
   в System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   в LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data)
   в LiteDB.LiteEngine.<Find>d__9.MoveNext()
   в LiteDB.LiteEngine.<Find>d__13.MoveNext()
   в LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   в System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   в System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   в ManagementConsole.Data.DeviceRepository.DoGetDevices(Pagination pagination) ...

Broken database attached to issue.

[broken.zip](https://github.com/mbdavid/LiteDB/files/1480197/broken.zip)

**Comment by mbdavid** [comment]
Hi @alex-erygin, is your datafile was created in v4? It's possible to reproduce this data file creation?

**Comment by alex-erygin** [comment]
This datafile is v4, but i can`t reproduce this file creation.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
