### ISSUE TITLE
Compound Unique Index

### ISSUE THREAD

**Issue by alberk8** [mbdavid/LiteDB#739]
Hi,

Would like to know if it possible to have compound unique index an a document/table?  Thank you.

**Comment by mbdavid** [comment]
Hi @alberk8, LiteDB has no compound index. If you need, you can convert into a single field and add an index in this field using Expressions:

```
db.EnsureIndex("col", "myindex", true, "JSON('{a:' + $.field1 + ',b:' + $.field2 + '}')
```

**Comment by dburner** [comment]
@mbdavid could you please explain your answer a bit more please? I can not find any overload that suits your example. 

Thanks

**Comment by mbdavid** [comment]
Hi @dburner, as I mention, there is no compound index in LiteDB, so you can compose an index with more than one field. But, in v4 you can use expression in index, so you can combine 2 field in a single BsonDocument and create an unique index on it. Let's see it:

if you have this document:

    {
        _id: 1,
        a: 2,
        b: 3
    }

and now you create an index to ensure (an query) that you will not have fields "a" and "b" with duplicated values inside your collection. You can create an index using an expression to get this indexed value. In this expression, you can create new `BsonDocument` (or a `BsonArray`) with both values, like this:

Creating an BsonDocument to be indexed: 

`engine.EnsureIndex("mycol", "unique_a_and_b", "{fieldA:$.a, fieldB:$.b}", true)`

Or using an BsonArray

`engine.EnsureIndex("mycol", "unique_a_and_b", "[$.a, $.b]", true)`

Or you can use an ugly string concat

`engine.EnsureIndex("mycol", "unique_a_and_b", "$.a +';' + $.b", true)`

Now you have an "virtual" field that are both values indexed for all documents. If you try insert any duplicate, an exception will be thrown.

You can also search with this index, like:

`db.Query("mycol", Query.EQ("unique_a_and_b", new BsonDocument { ["fieldA"] =2, ["fieldB"] = 3 }))`
`db.Query("mycol", Query.EQ("unique_a_and_b", new BsonArray { 2, 3 }))`
`db.Query("mycol", Query.EQ("unique_a_and_b", "2;3"))`

(ps: in both examples I'm using current master branch version, with support for document/array syntax `{}` and `[]`. If you are using 4.0.0, you need use JSON method that parse string into json (like my first example)).

**Comment by dburner** [comment]
Thank you 😄  Would you like me to document this functionality in the wiki? Also for best performance what would be the best option make something like an ObjectID + email unique, json, array or string concat?

**Comment by mbdavid** [comment]
Hi @dburner, I will update wiki soon.

And about performance, to be honest, string concat is the fast way (not big difference, but a serializa a single value is faster than serialize 2 values).

**Comment by maxhamulyak** [comment]
Would it be possible to delete the _id index? Lets say I have the following document structure
`
{
   "Id": 1,
   "Version": 1
}
`
I would like the combination to be unique. So I can track revisions of a document.
Current alternatives are:
- Storing history / Current in the document
- Adding an extra Id for the unique constraint, so that each document version had its own primary key, but we can recycle the document id. (and enforce uniqueness with the version)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
