### ISSUE TITLE
Index not found error

### ISSUE THREAD

**Issue by alexandredutra** [mbdavid/LiteDB#740]
This is a simple doubt about the database. My Application is working fine. Im open the lite db console then run a update on a Collection. The update works fines and return the affected collections. On the db console the find command works fine. But when a return and open the application again this broke with index not found _id. I´m back to console open the collection and consult the collections indexes and a _id index is listed. can anyone help me. sorry about my beginner doubt...

**Comment by mbdavid** [comment]
Oi Alexandre, tens como adicionar teu banco de dados aqui para que eu possa dar uma olhada e copiar o teu codigo para que eu possa analisar? Que versão do banco está usando?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
