### ISSUE TITLE
Can I create a composite primary key?

### ISSUE THREAD

**Issue by softwareguy74** [mbdavid/LiteDB#741]
I have a situation where I need to insert records in which the primary key (Id) has to be made up of two fields.  For example, "ListId" and "ItemId".  This is because ItemId is only unique per ListId, so I can't use ItemId as the "Id" field.  I also don't want to just make "ListId" and "ItemId" regular indexed fields because I want to take advantage of the db.Upsert() method to update existing items based on the composite primary key.  

Is this possible?  If so, can you provide a quick example of how to specify the "ListId" and "ItemId" as the primary key?  Thanks!

**Comment by mbdavid** [comment]
Hi @softwareguy74, there is no composite primary key in LiteDB (not only pk, but any other index support for multiple keys).

In `_chuncks` collection (in FileStorage) I used a string concatenation with FileId and SequenceNumber (like "myphoto/00001"). You can use some like that too. Or, you can create another key object like:

```
public class MyKey {
    public int ListId { get; set; }
    public int ItemId { get; set; }
}

public class YourClass {
    public MyKey YourClassId { get; set; }
    .....
}
```

**Comment by eocron** [comment]
How one supposed to search by such composite key? Tried

`      col.FindOne(x=> x.MyKey == key); `

with no success.

**Comment by mbdavid** [comment]
Hi @eocron, can you paste your entity class + id class?

**Comment by eocron** [comment]
```
    public class EntryHashKey
    {
        public byte[] Md5 { get; set; }
        public string Storage { get; set; }
    }

    public class EntryObject 
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<string> Tags { get; set; }
        public long Size { get; set; }
        public long SizeInStorage { get; set; }
        public EntryHashKey HashKey { get; set; }
     }
```

Currently solve it like this:

```
        private EntryObject InternalGetByHash(IScope scope, byte[] md5, string storage)
        {
            var query = Query.EQ(nameof(EntryObject.HashKey),
                BsonMapper.Global.ToDocument(new EntryHashKey() {Md5 = md5, Storage = storage}));
            var obj = scope.Context.Entries.FindOne(query);
            return obj;
        }
```

**Comment by mbdavid** [comment]
Ok, now I got it. In v4, LINQ expression only evaluate to BsonValue ctor (that accept only basic data types). I think it's solved in next v5 because LinqExpression are converted into BsonExpression... I will add this in unit tests

**Comment by mbdavid** [comment]
Hi @eocron, take a look on this new example, for new v5.

https://github.com/mbdavid/LiteDB/blob/v5/LiteDB.Tests/Mapper/LinqBsonExpression_Tests.cs#L298

I implemented linq visitor for member initialize. This means: you can write linq expression for search.

```C#
// single field search
var q = col.FindOne(x => x.HashKey = new EntryHashKey {Md5 = md5, Storage = storage});

// double field search
var q = col.FindOne(x => x.HashKey.Md5 = Md5 && x.HashKey.Storage = storage);
```

The main difference between this 2 ways:
- If you create one index in `HashKey`, you first query will run over this index.
- In second example, to use index, you must create index inside only 1 field (eg: HashKey.Md5). Index will be not as good as first example but will be more flexible to query (you can query without Storage field)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
