### ISSUE TITLE
How to create an index on IDictionary<string, int> keys?

### ISSUE THREAD

**Issue by DMGambone** [mbdavid/LiteDB#743]
I have a POCO that has the list of users and their access level stored as a `IDictionary<string, int>`  Here's a sample of that POCO:
```json
{
	"Id": 100,
	"Name": "My Name",
	"Description": "A sample document",
	"CreatedBy": "test@test.com",
	"CreatedDateTime": "2016-10-03T21:13:24.897347-04:00",
	"Metadata": 
	{
		"property": "value"
	},
	"ParentId": null,
	"Users": {
		"someone-else@test.com": 3,
		"test@test.com": 4
	}
}
```

As part of the code, we want to find all documents in that `Users.ContainsKey("somone-else@test.com")`.  How do I create an index on the User dictionary keys to optimize this call?  

Note, this dictionary could contain dozens, if not hundreds, of keys.

**Comment by mbdavid** [comment]
Hi @DMGambone, by default, it's not possible create index in "key" items. But, in v4, it's possible create indexes using Expressions. But (again), there is not available function that returns all keys. I will add this issue as suggestion to implement this function, so you can do this:

```
db.EnsureIndex("mycol", "mykeys", "KEYS($.Users)");

var r = db.Find("mycol", Query.EQ("mykeys", "name@email.com"));
```

**Comment by DMGambone** [comment]
Thank you for the response.  I worked around it by creating a helper class.
```C#
private class UserPermissions
{
	public string Name { get; set; }

	public int AccessLevel { get; set; }
}
```
Then I using using `Mapper.RegisterType<IDictionary<string, int>>` to serialize/deserialize the `IDictionary<string, int>` into a BsonArray of `UserPermissions`.

My index was then defined as `collection.EnsureIndex("Users.Name", false);`.  I then query using the Query `Query.EQ("Users.Name", "some@name")`.

The output is what I'm looking for.  I just can't tell if it's using an index or not.

What do you think?

**Comment by mbdavid** [comment]
Yes, it's a great solution too. And yes, your query use index. The only problem here is if you have another class with `IDictionary<string, int>` will convert as same structure.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
