### ISSUE TITLE
How can I patch DB (some collection, add new fields)

### ISSUE THREAD

**Issue by qart2003** [mbdavid/LiteDB#744]
Hi @mbdavid , what is best way for patch? I can create new collection with modified version of type, cope data to it, drop old collection (in  DAL some changes) But what is best way?

**Comment by mbdavid** [comment]
Hi @qart2003, I suggest you use new shell tool (v4) and update your documents inside your collection. You can do things like:

```
db.mycol.update mycol = $.oldcol + 1, names = ARRAY($.items[*].name)
```

If you are using old version, you need create a simple app to copy from-to old collection to new collection and do your transformation (use BsonDocument collection to manage your non strong schema collection).

**Comment by qart2003** [comment]
Thanks. I want move to 4.* version from 3.0. How can I do it? Is it stable? I have near 10 db in solution with DAL for each sure...

**Comment by mbdavid** [comment]
Hi @qart2003, LiteDB v4 use same file structure, so there is no problem to upgrade to v4 because will be only the dll file.
I'm not released yet because I just waiting community report problem. Some minor bugs was found and fixed.... so I beleave it's safe to upgrade.

**Comment by qart2003** [comment]
Thanks, I will waiting but very believe in project! (I'm just developer)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
