### ISSUE TITLE
Serialize/deserialize IReadOnlyList

### ISSUE THREAD

**Issue by Tyrrrz** [mbdavid/LiteDB#745]
I'm not sure what are the limitations here, but why is IList and array valid types for serialization but IReadOnlyList isn't? Worst case scenario, you can just cast an array to it.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
