### ISSUE TITLE
Query to string

### ISSUE THREAD

**Issue by maybalat** [mbdavid/LiteDB#748]
Good day! I tried to look for a better place to post this but yeah.

Ok so noobie question here.

I successfully made a .db file that has.
      customer
                     [ID]  [name] [nameID]

I want to get the **[nameID] if [name] is = James**
whenever I try to use **var result = customer.find(query.eq** etc. etc.
and try to make it into string and show it on **console.write(result);**
it shows up something like **System.Collections.Generic.List`1[thePlugin+ThePlayers]**

I apologise, I've been trying test codes and looking for answers for a long while now.
Again, what I want to happen is to show nameID of name if name = James

     Customer
                 [Id] [Name] [NameID]
                   1    James     1123
                   2    Gian        2238

Thanks in advance.

**Comment by mbdavid** [comment]
Hi @maybalat, if you want a single result, try use FirstOrDefault()

`var result = customer.Find(Query.EQ("name", "James")).FirstOrDefault()`

**Comment by maybalat** [comment]
Thanks for your reply David! I am really grateful to you for liteDB.

I was able to get the value by using

var result = customer.FindOne(Query.EQ("name", "James")).nameID;

I will try what you have told me and I am starting to understand how to use this.
If its alright may I ask, is there other ways to update the nameID of name, James ?
Because with the code that I have, I can't seem to update nameID. 

Thanks again!!

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
