### ISSUE TITLE
Querying collections with dynamic structure is not possible

### ISSUE THREAD

**Issue by inosik** [mbdavid/LiteDB#75]
Consider this simple collection:
![Initial database][initial]

Now if I want to query it, I get this result:
![Current state][before]
This happens because the second object doesn't have a `name.first` property, as I found out.

I have a very simple fix, which would allow us to execute the first query successfully. This is the result:
![Proposed change][after]

I'm asking because I want to use LiteDB as a sink for [Serilog](http://serilog.net) events. The saved documents have only a defined top-level structure, such as `Timestamp` or `MessageTemplate` properties. But we also have a `Properties` property, which is a dynamic object. I ran into this issue while testing.

What branch should I send a PR to?

[initial]: https://cloud.githubusercontent.com/assets/11393003/11071185/b6561f9e-87df-11e5-97ca-f4f249af5564.png
[before]: https://cloud.githubusercontent.com/assets/11393003/11071188/b8dcb5b6-87df-11e5-82c9-1f802533bd1f.png
[after]: https://cloud.githubusercontent.com/assets/11393003/11071191/bab411f4-87df-11e5-98a0-d911ba275a20.png

**Comment by mbdavid** [comment]
Hi @inosik, thanks for find this bug. Please, send me PR to merge with master.

But remeber that `contains` method do not use index. It's usable in shell only. In .NET code it's better call `FindAll()` and use Linq to Object to query.

A question: this screenshots are in osx? Did you are using LiteDB in vNext?

**Comment by inosik** [comment]
No, I'm using mono on OS X. But the app we are building, which will use LiteDB, is a .NET 4.5 WPF app. I didn't look into vNext yet.

**Comment by vip32** [comment]
hi @inosik, is this serilog sink available somewhere? very interested

**Comment by inosik** [comment]
It currently isn't, and I'm not in my company for the next two weeks. But it's very simple and actually based on the [MongoDB sink](https://github.com/serilog/serilog-sinks-mongodb).

It simply converts the incoming log events to JSON with a custom `JsonFormatter`, then to BSON with `JsonSerializer.Deserialize` and adds them to a collection in the database.

**Comment by vip32** [comment]
@inosik, that sounds interesting. my actual goal is to build some kind of web dashboard which works on the litedb stored logevents (html+rest). probably some provider abstraction will allow other stores (sqlserver) to be used but for now litedb seems the easiest to start with. if you can make your sink available that would be a great kickstart and appreciated :)
