### ISSUE TITLE
Do it work with Xamarin Forms?  Is there a sync support?

### ISSUE THREAD

**Issue by biapar** [mbdavid/LiteDB#750]
Do it work with Xamarin Forms?  Is there a sync support?

**Comment by Szymaniuk** [comment]
Yes, it's working with XF - I'm using it with NETStandard 1.4.
+ I'm using custom synchronization (with my API) implementation - don't think, that there is anything OOTB.

**Comment by DamienDoumer** [comment]
Yes of course it works like a charm on Xamarin Forms. 
Check this detailed tutorial on how to use LiteDB on XAmarin Forms as an alternative to SQLite https://doumer.me/litedb-on-xamarin-forms-alternative-to-sqlite/

**Comment by biapar** [comment]
Thx
