### ISSUE TITLE
Field name constraints different in LiteDB and MongoDB

### ISSUE THREAD

**Issue by kdawg14** [mbdavid/LiteDB#753]
Hi, mbdavid,

First off, thanks for your work on LiteDB.  It's proven very useful for me.

I have a question about the `IsValidFieldName` function at https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Document/BsonDocument.cs#L46:  According to that source, LiteDB only allows field names matching the regex `[\w$]+[\w-]*`, but MongoDB allows " any (UTF8) character in the field name which aren't special (contains ".", or starts with "$")." according to this [MongoDB ticket](https://jira.mongodb.org/browse/SERVER-3229?focusedCommentId=36821&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-36821).  

This is causing me an issue because I'm trying to use LiteDB as a tool for backing up/exporting/manipulating a subset of some MongoDB databases, which is occasionally failing because one or more documents in the MongoDB databases contain a field name that can't come across into LiteDB. 

I can of course fork it and change to allow different field names, but before doing that, I thought I'd check and see why you chose those field name constraints in the first place, and see if you think there would be more far-reaching ramifications if they were changed to match the same constraints that MongoDB has.

Thanks!

**Comment by mbdavid** [comment]
Hi @kdawg14, thanks for using LiteDB 😄

It's a very old restriction I add in ealy 0.5 version to "avoid naming problems in future". But as code was growing, I used this restriction for some regular expressions shell parser and now, in v4, for parse expression. With this restriction, it's easy to separate field name from other parts of expressions, like: 

`db.EnsureIndex("Total", "SUM($.Items[*].Price * 5)")`

It's easy to detect `Items` and `Price` as field names.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
