### ISSUE TITLE
shell find by _id

### ISSUE THREAD

**Issue by laurenti** [mbdavid/LiteDB#754]
if _id is type of ObjectId, in shell console, the next command returns no result :

`db.mycol.find _id = "blablabla"`

if I'm wrong, which would be the right command in shell to find by _id

edit : I use a collection created in shell, like :

```
db.mycol.insert { name:"John 1", age: 37 }
db.mycol.insert { name:"John 2", age: 11 }
db.mycol.insert { name:"John 3", age: 22 }
```

without ID, which is automatically created as ObjectId
so third registration is : {"_id":{"$oid":"59d4fab2c99d5d102c1f87eb"},"name":"John 3","age":22}
no result for : 

`db.mycol.find _id = "59d4fab2c99d5d102c1f87eb"`

**Comment by mbdavid** [comment]
Hi @laurenti, you must use object id json ex:

`db.mycol.find _id = {"$oid":"59d4fab2c99d5d102c1f87eb"}`

**Comment by laurenti** [comment]
work, thank you
