### ISSUE TITLE
Tree Structure

### ISSUE THREAD

**Issue by windischb** [mbdavid/LiteDB#755]
Hi!

I would like to store a tree structure in LiteDB.
Before i have used Postgres for this.
In Postgres exists the Data Type "ltree", which allows to query a path and/or his childs very easy.
https://www.postgresql.org/docs/9.6/static/ltree.html
Its possible to query for all Childlevels or only for a few Childlevels.

Is there anything in LiteDB which works nearly the same?
Or maybe is there a better solution for this?

**Comment by mbdavid** [comment]
Hi @windischb, nice data structure, I never saw anything like that. There is no direct way in LiteDB. If this structure is a string data you can only use query as normal string (=, >, <, like, contains, ....).

In v4 its possible use some expression functions to split this string and query better using index. But is not that powerfull as `ltree` datatype in Postgres

**Comment by windischb** [comment]
Ok, thanks!
I'll try to find another efficent way for Tree Structures...

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
