### ISSUE TITLE
[4.0.0-beta2] Thread.get_CurrentThread in UWP

### ISSUE THREAD

**Issue by Tirraon** [mbdavid/LiteDB#756]
Hi!
I found some bug in 4.0.0-beta2 from master https://github.com/mbdavid/LiteDB/commit/c0904d371d20735d73b985a2ed165f905e450d08
When I use LiteDB with UWP (10240 min.target), it throws exception:
```
System.Exception: Method 'Thread.get_CurrentThread()' was not included in compilation, but was referenced in LockService.Read(). There may have been a missing assembly.
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection<LiteDB.BsonDocument>.<Find>d__17.MoveNext()
   at FSClient!<BaseAddress>+0xc5988d
   at FSClient.Shared.Repositories.FavoritesRepository.ToDictionary()
   at FSClient!<BaseAddress>+0x1007830
```

After some google I found, that Thread.CurrentThread in some reason is not available in UWP, and we have to use Task.CurrentId.
But we can't use Task in Net3.5.

So, next code works well (in UWP at least)
```C#
#if !NET35
using System.Threading.Tasks;
#endif
```
```C#
#if NET35
_log.Write(Logger.LOCK, "exited read lock mode in thread #{0}", Thread.CurrentThread.ManagedThreadId);
#else
_log.Write(Logger.LOCK, "exited read lock mode in thread #{0}", Task.CurrentId);
#endif
```

I not sure, is it the best solution.
But I desired to write about issue.

**Comment by mbdavid** [comment]
Hi @Tirraon, thanks! I'm fixing this now. For final v4 release, I will remove .net 3.5 support because there are too much differences.
