### ISSUE TITLE
Testing in CI build

### ISSUE THREAD

**Issue by drjonnicholson** [mbdavid/LiteDB#759]
Hi,

I just made a pull request, wanted to see the report from AppVeyor. At the bottom of AppVeyor output it reports:

```
Starting test execution, please wait...
Warning: No test is available in C:\projects\litedb\LiteDB.Tests\bin\Debug\netcoreapp1.1\LiteDB.Tests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.

Information: Additionally, you can try specifying '/UseVsixExtensions' command if the test discoverer & executor is installed on the machine as vsix extensions and your installation supports vsix extensions. Example: vstest.console.exe myTests.dll /UseVsixExtensions:true
```

Looks like tests aren't being run?

**Comment by mbdavid** [comment]
Hi, I had this problem before too, than I changed LiteDB.Tests.csproj and this problem was fixed. Current version works fine (master branch). If this problem return in AppVeyor, I will take a look again.

**Comment by drjonnicholson** [comment]
It is what's returned in AppVeyor. Tests from master run ok locally.
