### ISSUE TITLE
Out of memory then Key not found issue

### ISSUE THREAD

**Issue by tripathv** [mbdavid/LiteDB#761]
Hi,
I am getting the same issue. I am using v4 beta 2 but still having the same issue.
"   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at LiteDB.IndexService.<FindAll>d__13.MoveNext()\r\n   at LiteDB.LinqExtensions.<>c__DisplayClass2_0`2.<<DistinctBy>g___0>d.MoveNext()\r\n   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data)\r\n   at LiteDB.LiteEngine.<Find>d__9.MoveNext()\r\n   at LiteDB.LiteEngine.<Find>d__13.MoveNext()\r\n   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()\r\n   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()\r\n   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()"

I am getting an issue where I started getting this error when adding an item, since then, reading is throwing the above issue

f1ab0a9e-a309-46cd-944c-59686fbd55df | 10/10/2017 12:56:22 AM | EXCEPTION: Exception of type 'System.OutOfMemoryException' was thrown.,    at LiteDB.BasePage.WritePage()    at LiteDB.TransactionService.Commit()    at LiteDB.LiteEngine.Commit()    at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)    at LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs)    at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc)    at LiteDB.LiteCollection`1.Insert(T document)   

I have just upgraded from 3.1 to 4 beta 2 hoping it will fix the issue...

What am I missing?

Please help

Vinay

**Comment by mbdavid** [comment]
It´s like your another issue: a problem in you datafile from v3 (your datafile are corrupted by some concurrency problem in v3). Can you reproduce this in v4 (from datafile creation to error)?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
