### ISSUE TITLE
collection.Max() on uint field

### ISSUE THREAD

**Issue by Xeenych** [mbdavid/LiteDB#762]
Hello.

I have a collection of 
class test {
 string address;
 uint value;
}

collection.Max(o=>o.value).AsInt32
returns 0

**Comment by mbdavid** [comment]
Hi @Xeenych, and what your max value in this collection? If bigger than an int32?

**Comment by Xeenych** [comment]
No.
It is about 4300000

**Comment by mbdavid** [comment]
Check this unit test... are you using fields?

**Comment by Xeenych** [comment]
My mistake. 
But today I tested this:
class test {
uint number = 0xFFFFFFFe;
}

collection.Max(o=>o.value).AsInt32 - throws exception
collection.Max(o=>o.value).AsInt64 - results in 0xFFFFFFFF

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
