### ISSUE TITLE
Querying objects with referenced resource

### ISSUE THREAD

**Issue by ReiSchneider** [mbdavid/LiteDB#765]
I have a model

```
public class QueueObject : IQueue
    {
        [BsonId]
        public int QueueID { get; set; }

        [BsonIgnore]
        public IUserInfo Sender { get; set; }

        [BsonRef("userInfo")]
        public IUserInfo Recipient { get; set; }

        public bool IsProcessing { get; set; }
        public bool IsCompleted { get; set; }

        public string Message { get; set; }

        public int QueueNumber { get; set; }
        public string ClientName { get; set; }
        public string QueueType { get; set; }
    }

```

Which references

```
public class UserInfoObject : IUserInfo
    {
        [BsonId]
        public int ID { get; set; }

        public string Name { get; set; }
        public string Username { get; set; }

        public string IPAddress { get; set; }

    }
```

When I run queries

`                var count = queueCollection.Include(x => x.Recipient).Count(x => x.Recipient.ID == 1);`

It does not return a result even when I successfully store the queue object on the database collection and can successfully print out all content using FindAll()

**Comment by ReiSchneider** [comment]
up

**Comment by mbdavid** [comment]
Hi @ReiSchneider, are running in v4? Are you created index in `x.Recipient.ID` before?

**Comment by ReiSchneider** [comment]
I'm using 3.1.4 as it is the only available in the NuGet.

I have a separate process for adding a user in the database and I make sure that i used EnsureIndex on the UserInfo ID

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
