### ISSUE TITLE
Does not support id as 'long' with auto-incremented when insert object.

### ISSUE THREAD

**Issue by vamone** [mbdavid/LiteDB#766]
First insertion creates object with Id  = 0, next attempt throws exception about duplicate key.

**Comment by mbdavid** [comment]
Hi @vamone, in v4 `long` already supported. If you running in v3, you must register a custom `AutoId` to `long` in `BsonMapper.Global`

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
