### ISSUE TITLE
String comparison in query not working as expected.

### ISSUE THREAD

**Issue by helusoft** [mbdavid/LiteDB#767]
var query = col.Find(p => p.Name.StartsWith("m", StringComparison.OrdinalIgnoreCase));

returns nothing, if the value (p.Name) starts with an uppercase.

**Comment by mbdavid** [comment]
Hi @helusoft, there is no conversion from this paramter (`StringComparison`) linq operation to internal query. If you want create an ignore case index, try:

`col.EnsureIndex("Name", false, "UPPER($.Name)")` and then always search using string in uppercase.

**Comment by helusoft** [comment]
Hi, and thanks for your quick response.

It solved the problem, but the syntax is in V.4.0.0 stable:

col.EnsureIndex("Name", "UPPER($.Name)", false)

**Comment by mbdavid** [comment]
Hi @helusoft, yes, sorry. I changed syntax for final version to be more clear.
