### ISSUE TITLE
Null Reference on Insert

### ISSUE THREAD

**Issue by ReiSchneider** [mbdavid/LiteDB#768]
I  ran into this problem where in I get a null reference exception on insert.

I have two object Models UserInfo and UserConfig. On the first trial, UserConfig references a UserInfo instance

```
public class UserConfigObject : IUserConfig
    {
        BsonRef("userInfo")]
        public IUserInfo UserInfo { get; set; }

        public string AssignedJob { get; set; }

        public string[] QueueItems { get; set; }

    }
```

```
public class UserInfoObject : IUserInfo
    {
        [BsonId]
        public int ID { get; set; }

        public string Name { get; set; }
        public string Username { get; set; }

        public string IPAddress { get; set; }
    }
```

And a method to insert the data into the database

```
public void AddUser(IUserConfig user)
        {
            var uconCollection = DatabaseInstance.GetCollection<IUserConfig>("userConfig");
            var uinCollection = DatabaseInstance.GetCollection<IUserInfo>("userInfo");

            uinCollection.Insert(user.UserInfo);
            uconCollection.Insert(user);

        }
```

This set up works fine but when I try to change the reference to UserInfo references UserConfig

```
public class UserInfoObject : IUserInfo
    {
        [BsonId]
        public int ID { get; set; }

        public string Name { get; set; }
        public string Username { get; set; }

        public string IPAddress { get; set; }

        [BsonRef("userConfig")]
        public IUserConfig UserConfig { get; set; }
    }
```

```
public class UserConfigObject : IUserConfig
    {
        [BsonRef("userInfo")]
        public IUserInfo UserInfo { get; set; }

        [BsonId(true)]
        public int ConfigID { get; set; }

        public string AssignedJob { get; set; }

        public string[] QueueItems { get; set; }

    }
```

With a method call for

```
public void AddUser(IUserInfo user)
        {
            var uconCollection = DatabaseInstance.GetCollection<IUserConfig>("userConfig");
            var uinCollection = DatabaseInstance.GetCollection<IUserInfo>("userInfo");

            uconCollection.Insert(user.UserConfig);
            uinCollection.Insert(user);
        }
```

It no longer works, it throws an System.NullReferenceException: 'Object reference not set to an instance of an object.' on uinCollection.Insert(user);

Either v3 or v4, it doesn't work with the latter set up

**Comment by mbdavid** [comment]
Hi @ReiSchneider, finaly I found your problem: It's about interface with dbref. When you create a DbRef, current code use same declaration in your class `IUserConfig`, which are not same used instance. For your example it´s possible to fix, but another problem was found: if you are using DbRef in a List... it´s not possible to detect your concrete class before cross document.

I will try fix, but if not possible I will only write a better error message when using interfaces with dbref

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
