### ISSUE TITLE
List<T> vs. IList<T>

### ISSUE THREAD

**Issue by PavelVonBahnhof** [mbdavid/LiteDB#77]
Hi,
you have a misleading info in your documentation or a bug at https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Serializer/Mapper/BsonMapper.Serialize.cs
line 97:
else if (obj is IList || type.IsArray) 
96             { 
97                 var itemType = type.IsArray ? type.GetElementType() : type.GetGenericArguments()[0]; 
98 
 
99                 return this.SerializeArray(itemType, obj as IEnumerable, depth); 
100             } 

Your documentation states that you support IList of T, which is not true.
You should not mix up IList of T and IList, because IList of T does not extend IList.
Furthermore, you should not expect the "non-array" type to have a generic argument (what about derived classes, or at least implementors like class MyList : "IList of MyClass"?).
The source code seems to be tailored for the use of List of T, which is too restrictive in many cases.

Anyway, thanks for LiteDB!
Pavel

**Comment by PavelVonBahnhof** [comment]
Sorry, there was "IList of T", which I wrote normally using the sharp brackets (and it was taken away as a markup...)

**Comment by mbdavid** [comment]
Hi @PavelVonBahnhof, thanks for that. Yes, IList of T doesnt extend IList. Bet. I guess that's better use IEnumerable for that.

But, the problem it's the same: how detect which "collection item type" is?  Did you have any idea with how I can implement that?

**Comment by PavelVonBahnhof** [comment]
Hi David,
there are basically two problems (at least I think so):
1) I don't know whether you are ready for polymorphism (ItemType might possibly be an abstract class and in reality there are concrete objects derived from this class that are to be stored in the database)
So, the ItemType of IList and IEnumerable... (non-generic versions) is System.Object (of course). But you hardly ever store System.Object instance in ArrayList, for example.
 
2) problems connected to generics (which in fact was what I personally missed in LiteDB)
Let's say you want to support IEnumerable<T> only, nothing more - thus you have to iterate through all implemented interfaces to look for it... - something like that:
 
foreach (var i in type.GetInterfaces())
{
    if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IEnumerable<>))
    {
        return type.GetGenericArguments()[0];
    }
}
 
But again - the ItemType might be the type of an abstract class and not the type of the real concrete class... (the same problem as for 1) ).
 
That's it.
Thank you for your response.
If you need any other help/assistance, do not hesitate to ask.
 
Pavel
 
 
______________________________________________________________
> Od: Mauricio David <notifications@github.com>
> Komu: "mbdavid/LiteDB" <LiteDB@noreply.github.com>
> Datum: 13.11.2015 16:41
> Předmět: Re: [LiteDB] List<T> vs. IList<T> (#77)
>
Hi @PavelVonBahnhof <https://github.com/PavelVonBahnhof>, thanks for that. Yes, IList of T doesnt extend IList. Bet. I guess that's better use IEnumerable for that.
But, the problem it's the same: how detect which "collection item type" is? Did you have any idea with how I can implement that?

**Comment by mbdavid** [comment]
I need get item type of a List just to compare with each instance of object. If are diferent, I add in BsonDocument an field called _type with full name of concrete object type.

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Serializer/Mapper/BsonMapper.Serialize.cs#L151)

I will take a look how MongoDB/Json.NET implements that.

Thanks for your help

**Comment by PavelVonBahnhof** [comment]
Sorry, there was a typo in my answer ("type" -> "i") :(
I've corrected it...
Pavel
