### ISSUE TITLE
Suggestion/Question - Multiple includes at only one call or dynamic

### ISSUE THREAD

**Issue by rmszc81** [mbdavid/LiteDB#772]
Hello again @mbdavid,

it's always a pleasure to talk to you.

I have a doubt (or a suggestion/question) about including multiple dbref dynamically.

for example, instead of

`.Include<Class>(c => c.Class)`

would be possible to do:

`
List<Expression<Func<Class, K>> dbRefList;
.Include(dbRefList)
`

The main idea is to add the includes dynamically by demand.

Thanks a lot.

Regards,

[],

@rmszc81

**Comment by mbdavid** [comment]
Hi @rmszc81, welcome again.

Do you have a list of includes that you always use? Thats why needs this List as argument? This could be added as extension methods?

**Comment by rmszc81** [comment]
So, no, it's not always the same list, sometimes I need to include only one
"table" and other times "many", it depends of given scenario.

I think it could be added as extension methods but, the idea is to have
another overload on the include. Today there are a string and an
extension<func.

So, any suggestions?

Thanks a lot.

Regards,

@rmszc81

**Comment by rmszc81** [comment]
hi @mbdavid ,

is there any answer of possibility for this scenario?

if it's not, it's ok, it's just a question for awhile.

thank you.

**Comment by mbdavid** [comment]
Hi @rmszc81, you mean this code? I can review this to be added in all `Include` methods, like LiteRepository, LiteDatabase and LiteEngine

```C#
    /// <summary>
    /// Run an include action in each document returned by Find(), FindById(), FindOne() and All() methods to load DbRef documents
    /// Returns a new Collection with this action included
    /// </summary>
    public LiteCollection<T> Include<K>(IEnumerable<Expression<Func<T, K>>> paths)
    {
        if (paths == null) throw new ArgumentNullException(nameof(paths));

        var result = this;

        foreach (var path in paths)
        {
            result = this.Include(path);
        }

        return result;
    }
```

**Comment by rmszc81** [comment]
hi @mbdavid,

yes, just like that so, we can add by demand.

thank you very much.

you can close the issue now.

regards,

[],

@rmszc81

**Comment by rmszc81** [comment]
hi @mbdavid, thanks for all explanations. I'm closing this thread now.
