### ISSUE TITLE
How to store reference to parent.

### ISSUE THREAD

**Issue by wilberolive** [mbdavid/LiteDB#773]
I have a class structure like this, in VB.Net.
```
Public Class Group
    Public Property Id As ObjectId
    Public Property Name As String
    Public Property Items As List(Of Item)
End Class

Public Class Item
    Public Property Id As ObjectId
    Public Property Name As String
    Public Property Group As Group
End Class
```
I then try to add a group and item to a collection like this.
```
Using Database As New LiteDatabase("Test.db4")
    Dim Collection as LiteCollection = Database.GetCollection(Of Group)
    Dim G As New Group With {
        .Name = "My Group"
    }
    Collection.Insert(G)
    Dim I As New Item With {
        .Name= "My Item",
        .Group = G
    }
    G.Items.Add(I)
    Collection.Update(G)
End Using
```
However, I get an exception; "Document has more than 20 nested documents in 'Group'. Check for circular references (use DbRef)." I'm assuming this is being caused by the fact that the item has a reference back to its parent group, so it is trying to nest the documents.

So I'm wondering how to handle this situation. My application requires that items have direct references to their parent groups, so I can't just store an Id of the group as that doesn't give me a direct reference. How do I go about this with LiteDB?

**Comment by mbdavid** [comment]
Hi @wilberolive, in this case, you should use `[BsonIgnore]` to avoid this circular reference. And then, when you get a document, add this reference manual.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
