### ISSUE TITLE
Logging not working at all?

### ISSUE THREAD

**Issue by Szymaniuk** [mbdavid/LiteDB#776]
I've just tried to introduce LitDB logging of my Xamarin Forms app, based on this https://github.com/mbdavid/LiteDB/wiki/Connection-String
I.e.:

`new LiteRepository("filename=/data/user/0/com.mycompany.myapp/files/LocalDb/DB_1.0_Logged_User.db;log=255;journal=false")`

255 is based on `Logger.FULL`

However I didn't see completelly no logs, during selecting/insering/updating objects in LiteDB.

Any idea?

**Comment by mbdavid** [comment]
Hi @Szymaniuk, how are you capture this logs messages?

Did you try this?

`repo.Database.Log.Logging += (s) => Console.WriteLine(s);`

**Comment by Szymaniuk** [comment]
I thought it would magically appear in logs xD. Thanks, it's working fine, on listening on this event.

**Comment by parabola949** [comment]
so, a note on this, quite possibly a bug, or just very misleading.
I originally tried to create my instance as such:

```cs
Db = new LiteDatabase(dbPath, null, new Logger(Logger.FULL, (s) => { Log(s); }));
```
No log.  Nothing.

So, I saw this issue post, and tried like this:

```cs
Db = new LiteDatabase(dbPath, null, new Logger(Logger.FULL));
Db.Log.Logging += Log;
```

Still nothing.  So finally I tried this:

```cs
Db = new LiteDatabase(dbPath);
Db.Log.Level = Logger.FULL;
Db.Log.Logging += Log;
```

And bam, it started working.  So, while the constructor allows you to pass a `Logger` to it.... it appears to completely ignore it.
