### ISSUE TITLE
LiteRepository.Query returns an empty list?

### ISSUE THREAD

**Issue by wilberolive** [mbdavid/LiteDB#779]
When I create a list from a LiteCollection, it works fine and I get the whole list of items, like this.
```
Dim Items As LiteDB.LiteCollection(Of ClassItem) = Repository.Database.GetCollection(Of ClassItem)("Items")
Dim ItemList As List(Of ClassItem) = Items.FindAll.ToList
```
However, when I try to do this same thing with a LiteRepository, it doesn't work, like this.
```
Dim ItemList As List(Of ClassItem) = Repository.Query(Of ClassItem).ToList
```
So I guess I'm doing something wrong with Repository.Query?

**Comment by mbdavid** [comment]
Hi @wilberolive, LiteRepository use a default conversion name for collections: same name as you class. So, when you run `repo.Query<ClassItem>()` you are looking for a collection named `ClassItem`. As you example above, your collection name is "Items", so you need explicit change change: `repo.Query<ClassItem>("Items")`

**Comment by wilberolive** [comment]
Ah ha! Makes sense. Thanks.
