### ISSUE TITLE
File Storage - File searches

### ISSUE THREAD

**Issue by Brown3246** [mbdavid/LiteDB#782]
I am very new to this so please bear with me!

I want to use LiteDb as a document store. I can upload etc fine, but I need to give the user the option to search all files stored in the Db.

I have used the Find function and put it into an array to populate a list box, but it is only giving me 

LiteDb.LiteFileInfo for each entry.

How do I obtain File info such as Name, created date etc?

Kind regards

Adrian

**Comment by mbdavid** [comment]
Hi Adrian,

`LiteFileInfo` is an equivalent to `System.IO.FileInfo`. This class contains all information about file that are stores (its a special collection named `_files`).

Each `LiteFileInfo` contains all information you need:

    public string Id { get; private set; } // Unique file id
    public string Filename { get; private set; } // Filename only (with extension)
    public string MimeType { get; private set; } // Mimetype
    public long Length { get; internal set; } // File Size
    public int Chunks { get; internal set; } // Number of file pices
    public DateTime UploadDate { get; internal set; } // same as CreateDate
    public BsonDocument Metadata { get; set; }  // Any extend data you want add in your uploaded file

**Comment by Brown3246** [comment]
Many thanks - all sorted now!
