### ISSUE TITLE
DbRef not working with CustomType

### ISSUE THREAD

**Issue by lilasquared** [mbdavid/LiteDB#783]
Consider the following model:
```csharp
public class EmployeeId
{
    private readonly String _id;

    public EmployeeId(String id)
    {
        _id = id.ToUpperInvariant();
    }

    public static implicit operator String(EmployeeId id)
    {
        return id.ToString();
    }

    public override String ToString()
    {
        return _id;
    }
}

public class Employee
{
    public EmployeeId Id { get; set; }
    public String Firstname { get; set; }
    public String Lastname { get; set; }
    public Employee Manager { get; set; }
}
```
I can use the `RegisterType` method to register my custom `EmployeeId` type like so:
```csharp
BsonMapper.Global.RegisterType
(
    id => id?.ToString(),
    bson => new EmployeeId(bson.AsString)
);
```
And I have my model mapped using the fluent API:
```csharp
BsonMapper.Global.Entity<Employee>()
    .Id(x => x.Id)
    .Field(x => x.Firstname, nameof(Employee.Firstname))
    .Field(x => x.Lastname, nameof(Employee.Lastname))
    .DbRef(x => x.Manager, "Employee");
```
However when i try to insert a new employee with a manager I get the following error.
```
System.InvalidCastException: 'Value is not a valid BSON data type - Use Mapper.ToDocument for more complex types converts'
```
I thought I was doing something wrong but I did some digging - 
```csharp
member.Serialize = (obj, m) =>
{
    var idField = entity.Id;

    // #768 if using DbRef with interface with no ID mapped
    if (idField == null) throw new LiteException("There is no _id field mapped in your type: " + member.DataType.FullName);

    var id = idField.Getter(obj);

    return new BsonDocument
    {
        { "$id", new BsonValue(id) },
        //{ "$id", m.Serialize(id.GetType(), id, 0) },
        { "$ref", collection }
    };
};
```
the code above shows how the `BsonMapper` class sets up the serialization inside of `RegisterDbRefItem`.  The commented line shows the change I made which resolved the above exception.  Is this a bug for custom types or am I doing something wrong?  Thanks in advance!

**Comment by mbdavid** [comment]
Hi @lilasquared, thanks! Yes, it´s not supported because use `new BsonValue(..)`. Is your change resolve this problem? If works, please, create an PR (line 440 must be changed too)

**Comment by lilasquared** [comment]
@mbdavid it did resolve the problem for me but I don't know if there are any negative side effects of this change.  I can definitely create a PR though.

**Comment by mbdavid** [comment]
Hi @lilasquared, I think there is no problem. I will run unit tests on this, but it's safe use Serialize. Thanks!

**Comment by xavave** [comment]
[https://github.com/mbdavid/LiteDB/issues/2243](url)
