### ISSUE TITLE
Property not mapped to a bson document

### ISSUE THREAD

**Issue by ReiSchneider** [mbdavid/LiteDB#786]
I have two objects, ObjectA and ObjectB

```
class ObjectA{
       public int Id {get; set;}
       public string name {get; set;}
       ....
}

class ObjectB{
      public int Id {get; set;}
      [BsonRef("objectA")]
      public ObjectA objA {get; set;}
}
```

collection of ObjectA values is already created by another module and I want new values of ObjectB to reference it. Insertion of new ObjectB works but when I try to retrieve values using

`objectBCollection.include(x => x.objA).findAll();
`
it throws and error saying Property 'objA' not mapped to a BsonDocument

**Comment by mbdavid** [comment]
Hi @ReiSchneider, sorry, but I don't undersand your case. You have 2 collections, your ObjectB class contains a reference for a self ObjectB but uses ObjectA as collection... 

Can you create an running example using a fork version? There are a `LiteDB.Demo` project you can use remove all code and create your own test.

**Comment by ReiSchneider** [comment]
Sorry, I updated it, I mistyped, supposed to be ObjectB referencing ObjectA

**Comment by ReiSchneider** [comment]
Nevermind, I solved it. Thanks
