### ISSUE TITLE
v4 - question - ensure index

### ISSUE THREAD

**Issue by rmszc81** [mbdavid/LiteDB#789]
hello @mbdavid ,

in the documentation for v4 is said:

"There is no more auto index creation. You always run EnsureIndex in your database initialization."

by initialization you mean when the database is created?

and do I need to call it EnsureIndex at every write operation?

Thanks.

@rmszc81

**Comment by wilberolive** [comment]
I'm wondering the same thing. When exactly do you call EnsureIndex?

Do you just use it the first time you add a new collection to a database to set up the indexes, or do you need to use it every time after calling GetCollection for example? The docs aren't very clear on this.

**Comment by mbdavid** [comment]
Hi,

Database initialization means "when datafile is created". In my code, I use some like that:

```C#
public static LiteDatbase OpenDB()
{
    var db = new LiteDatabase("....");
    var engine = db.Engine;

    // database initialize
    if (engine.UserVerion == 0)
    {
        engine.EnsureIndex("users", "Username", "LOWER($.Username)", true);
        engine.EnsureIndex("users", "Email", true);
        ...
        
        engine.UserVersion = 1;
    }
    
    // if you release new app version and need update datafile
    if (engine.UserVersion == 1)
    {
        engine.DropCollection("old_collection");
        
        // run shell commands
        engine.Run("db.users.update Email = LOWER($.Username) + '@gmail.com' where _id > 0");
        
        engine.UserVersion = 2;
    }
    
    
    return db;
}


using(var db = OpenDB)
{
    // ...
}
```

@wilberolive, you need call `EnsureIndex` before run a query to database create index IF NEEDED. If index already created (using same EnsureIndex), EnsureIndex will do nothing. So, to be pratic, be best place to create all your indexes are in database initialization (like you do when you create a new relation database running sql scripts).

**Comment by rmszc81** [comment]
hi @mbdavid,

thanks for the explanation.

pretty useful and now I understand why.

regards,

[].

@rmszc81

**Comment by rmszc81** [comment]
hi @mbdavid.

to tell you the truth, now I realized what you really mean by removing the index method on mapping.

for me, it was a good thing, although I had to made some changes in code but allowed me to rethink my indexes and the result is really better than before.

thanks a lot.

I'm closing this thread now.

Regards,

[].

@rmszc81
