### ISSUE TITLE
Request: Put in option to allow > 1MB documents in a collection

### ISSUE THREAD

**Issue by dfarrNTST** [mbdavid/LiteDB#790]
Was wondering if it would be possible to allow > 1MB documents to be inserted into a collection?  We occassionally have objects that exceed that and we have to flip over to file storage for those, but we'd much rather use them as collections so we get all the features that come with that.  Is there a way we can override a collection's limitation or a repo's limitation for that?

**Comment by mbdavid** [comment]
Hi @dfarrNTST, there is no more this limitation in v4. There are only a recommendation to keep documents small as possible to be faster read/write and use more than one document (in different collections) to access only what you need at time.

**Comment by dfarrNTST** [comment]
Awesome...thanks!
