### ISSUE TITLE
Transaction Propose

### ISSUE THREAD

**Issue by mbdavid** [mbdavid/LiteDB#791]
Hello everyone! In v4, transactions are removed to avoid keep datafile locked between commands. It was a hard decision, but was important to fix some v3 concurrency problems.

But transaction are awesome in some applications are really important. So I'm working on another way to implement "transaction-like" operation. My ideia is implement something like Entity Framework do: operate with objects in memory and, when call "SaveChanges", save all changes in a single datafile operation (and if any error occurs, rollback everything).

So, here my propose:

```C#
using(var db = new LiteDatabase("..."))
{
    var customers = db.GetCollection<Customer>("customers");
    var orders = db.GetCollection<Order>("orders");
    
    var cust1 = new Customer { Name = "John" };
    var order1 = new Order { Date = DateTime.Now, Customer = cust1 };
    
    customers.Add(cust1);
    orders.Add(order1);
    
    // no datafile operation until here
    // all entities are in memory (as a List<Entity> Changes)
    // so, "customers.FindById(1) == null"
    
    db.SaveChanges(); 
    // now, in a single datafile operation:
    // - "cust1" will be serialized, inserted and setted "CustomerId"
    // - "order1" will be serialized (and will get reference from cust1), inserted and setted "OrderId"
    
    // "Updating"
    
    var cust2 = customers.FindById(2);
    
    cust2.Name = "Newton";
    
    customers.Set(cust2);
    
    // to avoid track all return objects (from Find), you will need use "Set" to be updated later
    
    db.SaveChanges();
    
    // also, will be avaiable
    // customers.Save(entity) - works as Upsert()
    // customers.Remove(entity) - works as Delete()
    
}
```

- This 4 methods will works with a change list (`List<Entity>`) that will be execute in order as included in this list when `SaveChanges` are called
- Current `Insert(), Update(), Delete()` method will work as excepted
- Until `SaveChanges()` all added/updated/deleted entities are not reflected in `Find` operations

Leave your comments, ideas and considerations  👍

**Comment by rmszc81** [comment]
It would be a very interesting option because there's some scenarios that we must be certain that all data was written to ensure business rules integrity.

And how about creating a disposable class named transaction like EF? 

Something like:

using (LiteTransaction transaction = new engine.Transaction())
{
    ...
    transaction.Complete();
}

**Comment by ovule** [comment]
Hi there,

I found this page through https://github.com/mbdavid/LiteDB/issues/723.  I was looking into this because I was considering this library however cross data type transactions are absolutely necessary for my requirements.

For me personally I could live with your proposal, i.e. create a plan in memory and then send this to the DB as a single operation.

If you were to implement this how long do you think it would be before it's ready?

It doesn't look like you implement write-ahead-logging and I guess this is the reason you removed transaction support with the v4 release (you said on page I linked to above that full transactions were removed because of locking issues)?  Do you have any plans to implement WAL?

Thanks

**Comment by mbdavid** [comment]
Hi @ovule, problems with concurrency was not about using rollback journal, but way I implemented locks. Yes, using rollback journal needs lock file in write mode and lock readers too. I read about WAL long time ago and don't was interested... until now. Reading in sqlite, WAL can be very useful to avoid writer lock reader... I will try this... thanks!

**Comment by mbdavid** [comment]
Hi @rmszc81, when use transaction in EF you are adding data direct inside database and transaction are database-transaction. When you use only "SaveChanges" all is about memory (there is no database change and no rollback). That's I think about this api. Also, LiteEngine will support this same operation:

`db.Engine.SaveChanges(List<Entry> changes)`

**Comment by rmszc81** [comment]
hi @mbdavid, oh, I got it now.

I think it's ok, a good idea. Can be very useful to some scenarios.

**Comment by Itaros** [comment]
Will it perform some optimizations to Add(...)(grouping into, like, InsertBulk) ahead of time or take its sweet time like Insert(...) does when inserting one-by-one?
On other hand it is a really nice proposition, except, will it not complicate the API? I wonder if having some other type of Collection(or LiteDatabase) class with the same methods(Insert, Update, Delete), but which require SaveData(...) call would be a better solution to keep things simple and not unnecessarily overloaded with features.

**Comment by kstef** [comment]
Sounds extremely interesting and useful.  Any news on the topic?

**Comment by masilver99** [comment]
Won't you still have the same set of problems if the add orders.Add(order1) fails while inserting into the database from memory?  You'd have to back out customers.Add(cust1);

**Comment by mbdavid** [comment]
Hi @masilver99, no. LiteDB has internal transactions (even in v4) but not expose to user to avoid keep opened. So, if engine has a fixed list of items to insert/update/delete, all operations can be done in a single transaction.

But, my "problem" now is that I read and understand more about WAL (Write Ahead Logging). All major databases implement this technique (SQL server, Postgres, Sqlite, MongoDB, ...) and are great to work with transactions. WAL support multiple write threads and implement atomicity and durability So, I'm implementing WAL in LiteDB and `BeginTrans()` will be back in next major version.

**Comment by digitalkirkley** [comment]
Hello. Is there an approximate release date for LiteDB with transaction (WAL) support?

**Comment by mbdavid** [comment]
hi @digitalkirkley, there is no release date yet because WAL support be only in v5 (WAL already developed in v5, but has a long way to finish this version).

**Comment by ArquiMestre** [comment]
I have a question. I am using the latest LiteDB version. I am starting to use it, i like it a lot. For what i see transactions are still private, thus, i would like to know if there is still no way to use them, when writting several collections?

**Comment by konrad-kruczynski** [comment]
@mbdavid What if we could have a visitor-like transaction model. IOW:
```
db.InTransaction(x =>
{
    var collection = db.GetCollection(...);
    var someDocument = collection.Query(...);
    someDocument.SomeProperty++;
    collection.Update(someDocument);
};
```
So we would have a delegate that is wholly executed in one transaction.
