### ISSUE TITLE
Search by meta data

### ISSUE THREAD

**Issue by Brown3246** [mbdavid/LiteDB#792]
Is it possible to use db.FileStorage.Find to search by meta data? I have several documents which are stored, each with unique meta data and I want to search for them.

**Comment by mbdavid** [comment]
Hi @Brown3246, using current api it's possible search only by _id. But, FileStorage are a normal collection called `_files`, so you can search direct (using index or full scan). Like

```c#
// create an index on "tags" array inside metadata
db.Engine.EnsureIndex("_files", "tags", "$.metadata.tags[*]");

// searching
var result = db.Engine.Find("_files", Query.EQ("tags", "tag1")).ToList();
```

**Comment by Jack85** [comment]
this one also working for me:
```
db.Engine.Find("_files", 
                Query.EQ("metadata.hash", "hash")).FirstOrDefault()
```
doesnt work, are you sure index needs $?

**Comment by mbdavid** [comment]
Hi guys, I also recommend to create an index to fast search (if you have lot of files)

`db.Engine.EnsureIndex("_files", "hash", "$.metadata.hash", true)` (unique index)

an then search using

`db.Engine.Find("_files", Query.EQ("hash", "123....890"))`

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
