### ISSUE TITLE
Error on indexer

### ISSUE THREAD

**Issue by BenTMatthews** [mbdavid/LiteDB#795]
> ArgumentException: Incorrect number of arguments supplied for call to method 'Project.Interfaces.Contentget_Item(System.String)'
> Parameter name: property

The Class being stored is defined as followed:

> public int Id { get; set; }
>         public Dictionary<string, ContentItem> Items { get; set; } = new Dictionary<string, ContentItem>();
>         public bool Active { get; set; } = true;
>         public DateTime Created { get; } = DateTime.Now;
>         public String Name { get; set; }

And the ContentItem class:

> public Guid Id { get; set; }
>         public string Value { get; set; }
>         public bool Active { get; set; } = true;
>         public DateTime BeginDate { get; set; } = DateTime.MinValue;
>         public DateTime EndDate { get; set; } = DateTime.MaxValue;
>         public DateTime Created { get; } = DateTime.Now;
>         public String Name { get; set; }
>         public int Priority { get; set; } = 0;
> 
>         public ContentItem()
>         {
>             Id = Guid.NewGuid();
>         }
> 
>         public ContentItem(string name)
>         {
>             Id = Guid.NewGuid();
>             Name = name;
>         }

The only change I make that will break this is when I add an index to get a content item by name:

>         public ContentItem this[string itemName]
>         {
>             get
>             {
>                 return GetItem(itemName);
>             }
>             set
>             {
>                 SetItem(itemName, value);
>             }
>         }

Leaving that function in causes the error, taking it out resolves it. 

Any clues?

**Comment by mbdavid** [comment]
Hi @BenTMatthews, there is no support for indexed property in BsonMapper class, but its strange because that error could not happend. Try add `[BsonIgnore]` attribute. I will review the code to prevent this.

**Comment by BenTMatthews** [comment]
Thanks for addressing this, really appreciate all the hard work.
