### ISSUE TITLE
How to auto-generate _id?

### ISSUE THREAD

**Issue by qqgg231** [mbdavid/LiteDB#796]
I wanted to use example from [this answer](https://stackoverflow.com/questions/46697553/impossible-to-save-collection-of-strings-to-litedb?answertab=votes#tab-top), but it throws:

```
LiteDB.LiteException
  HResult=0x80131500
  Message=Invalid BSON data type 'Null' on field '_id'.
  Source=LiteDB
```

I thought that LiteDB will auto-generate '_id'. I don't mind it.  In this example there is no '_id' in BsonDocument, so I assume it is somehow auto-generated.

Any clues?

**Edit:**

I now see that this feature is removed from LiteDB 4.0. So how could I substitute it?

**Comment by mbdavid** [comment]
Hi @qqgg231, thanks! It´s a bug, need work (AutoId was removed in v4 custom types only). I'm fixing...

**Comment by qqgg231** [comment]
Btw what do you mean by custom types? POCO classes or something else? BsonDocument is not custom?

**Comment by mbdavid** [comment]
Custom types for used in `Id` property (like create autoid for `string` Id).

I just commit to fixed this.

**Comment by qqgg231** [comment]
> There is no more auto index creation. 
https://github.com/mbdavid/LiteDB/wiki/Indexes#changes-in-v4

So should this be changed by adding "for custom types" ?

**Comment by mbdavid** [comment]
Hi @qqgg231, "auto index" is not the same "auto id".

Auto index is create an index based on query execution (when you just run a query and database create an index if need). This feature was removed because now LiteDB supports full scan search too (search with no index).

Auto Id is like "Auto Increment" in sql server. This was removed in `LiteDatabase` level (any POCO class) and was implemented in `LiteEngine` level (BsonDocument only).

(sometimes is not too clear for anyone but me 😄)

**Comment by qqgg231** [comment]
Thank you for explanation  :smirk:

**Comment by FelschR** [comment]
So what's the status on this?
I am getting the _id Null error with LiteDatabase as well as LiteRepository.

I don't really want to use LiteEngine because it doesn't integrate object mapping.
Any other way to use auto id?

**Comment by FelschR** [comment]
Oh, I found the reason:
https://github.com/mbdavid/LiteDB/blob/0bf2c327e2ebb91c5b8448c77df1652b921c81d2/LiteDB.Tests/Database/AutoId_Tests.cs#L82

**Comment by mbdavid** [comment]
Hi @FelschR, now only possible AutoId types are implemented. If you want use `string` data type you need set your `_id`

**Comment by JohnnyDeeee** [comment]
How come that i get a `LiteDB.LiteException: 'Cannot insert duplicate key in unique index '_id'. The duplicate value is '0'.'` with the following code?

It looks like the AutoId doesn't work in this scenario, or am i missing something?

```
    public class Test {
        public int id { get; set; }
        public string text { get; set; }
    }

    static class Program
    {
        static void Main()
        {
            using (var db = new LiteDatabase("database.db")) {
                LiteCollection<object> collection = db.GetCollection<object>("testCollection");

                collection.Insert(new Test { text = "aaa" });
                collection.Insert(new Test { text = "bbb" });
            }
        }
    }
```
