### ISSUE TITLE
AutoId reusing values when using int type

### ISSUE THREAD

**Issue by JosefNemec** [mbdavid/LiteDB#797]
I Have following class
```
public class Emulator
{
    [BsonId]
    public int Id
    {
        get; set;
    }
}
```

Let's say that I add two of those into new collection. Two new objects are created and they have autoid properly set to `1` and `2`. The problem is that if I remove those and insert two new ones, they will also have ids `1` and `2`, when I would expect them to have `3` and `4`.

Is this intended behavior? If so, is there a way to ensure that old ids are not being reused?
(tested with 3.1.1 and 4.0)

**Comment by mbdavid** [comment]
Hi @JosefNemec, in v3 AutoId used `Max()` index value so this duplication can occurs. But in v4 no, collections has an internal counter that should not happen. I made this example:

    // using strong type
    using (var db = new LiteDatabase(new MemoryStream()))
    {
        var col = db.GetCollection<EntityInt>("col1");

        col.EnsureIndex(x => x.Name);

        col.Insert(new EntityInt { Name = "One" });
        col.Insert(new EntityInt { Name = "Two" });

        var one = col.FindOne(x => x.Name == "One");
        var two = col.FindOne(x => x.Name == "Two");

        Assert.AreEqual(1, one.Id);
        Assert.AreEqual(2, two.Id);

        // now delete first 2 rows
        col.Delete(one.Id);
        col.Delete(two.Id);

        // and insert new documents
        col.Insert(new EntityInt { Name = "Three" });
        col.Insert(new EntityInt { Name = "Four" });

        var three = col.FindOne(x => x.Name == "Three");
        var four = col.FindOne(x => x.Name == "Four");

        Assert.AreEqual(3, three.Id);
        Assert.AreEqual(4, four.Id);
    }

    // using bsondocument/engine
    using (var db = new LiteEngine(new MemoryStream()))
    {
        db.EnsureIndex("col", "Name");

        db.Insert("col", new BsonDocument { ["Name"] = "One" }, BsonType.Int32);
        db.Insert("col", new BsonDocument { ["Name"] = "Two" }, BsonType.Int32);

        var one = db.FindOne("col", Query.EQ("Name", "One"));
        var two = db.FindOne("col", Query.EQ("Name", "Two"));

        Assert.AreEqual(1, one["_id"].AsInt32);
        Assert.AreEqual(2, two["_id"].AsInt32);

        // now delete first 2 rows
        db.Delete("col", one["_id"].AsInt32);
        db.Delete("col", two["_id"].AsInt32);

        // and insert new documents
        db.Insert("col", new BsonDocument { ["Name"] = "Three" }, BsonType.Int32);
        db.Insert("col", new BsonDocument { ["Name"] = "Four" }, BsonType.Int32);

        var three = db.FindOne("col", Query.EQ("Name", "Three"));
        var four = db.FindOne("col", Query.EQ("Name", "Four"));

        Assert.AreEqual(3, three["_id"].AsInt32);
        Assert.AreEqual(4, four["_id"].AsInt32);
    }

**Comment by JosefNemec** [comment]
After some testing I found that it only works in 4.0 if I call `EnsureIndex` on collection. Is that how it should work (I don't really read items from that collection so I didn't find it necessary to create indexes there)?

**Comment by mbdavid** [comment]
Can you paste your example? I made another test and still working as expected.

            using (var db = new LiteDatabase(new MemoryStream()))
            {
                var col = db.GetCollection<EntityInt>("col1");

                var one = new EntityInt { Name = "One" };
                var two = new EntityInt { Name = "Two" };
                var three = new EntityInt { Name = "Three" };
                var four = new EntityInt { Name = "Four" };

                // insert
                col.Insert(one);
                col.Insert(two);

                Assert.AreEqual(1, one.Id);
                Assert.AreEqual(2, two.Id);

                // now delete first 2 rows
                col.Delete(one.Id);
                col.Delete(two.Id);

                // and insert new documents
                col.Insert(new EntityInt[] { three, four });

                Assert.AreEqual(3, three.Id);
                Assert.AreEqual(4, four.Id);
            }

            // using bsondocument/engine
            using (var db = new LiteEngine(new MemoryStream()))
            {
                var one = new BsonDocument { ["Name"] = "One" };
                var two = new BsonDocument { ["Name"] = "Two" };
                var three = new BsonDocument { ["Name"] = "Three" };
                var four = new BsonDocument { ["Name"] = "Four" };

                db.Insert("col", one, BsonType.Int32);
                db.Insert("col", two, BsonType.Int32);

                Assert.AreEqual(1, one["_id"].AsInt32);
                Assert.AreEqual(2, two["_id"].AsInt32);

                // now delete first 2 rows
                db.Delete("col", one["_id"].AsInt32);
                db.Delete("col", two["_id"].AsInt32);

                // and insert new documents
                db.Insert("col", new BsonDocument[] { three, four }, BsonType.Int32);

                Assert.AreEqual(3, three["_id"].AsInt32);
                Assert.AreEqual(4, four["_id"].AsInt32);
            }

**Comment by JosefNemec** [comment]
I don't know what I did wrong, but it now works properly in 4.0 even without EnsureIndex. Thanks for help.
