### ISSUE TITLE
Migration 0.9 -> 1.0.4 problem

### ISSUE THREAD

**Issue by win32nipuh** [mbdavid/LiteDB#80]
I worked with version 0.9 and all was ok.
Then I packed files with v1.0.4, replaced LiteDB.dll and changed call in my WCF RESTFul service:
               //using (var db = new LiteEngine(hdb))
                using (var db = new LiteDatabase(hdb))
                {
                    string strResource = String.Format(@"{0}{1}.{2}", strVirtualDirectory, resource, extension);
                    
                    //Console.WriteLine(@"Requested: {0}", strResource);
                    var files = db.FileStorage.Find(strResource);
                    foreach (var fi in files)
                    {
                        //Console.WriteLine(@"{0}:{1}:{2}", fi.Filename, fi.MimeType, fi.Length);
                        var stream = fi.OpenRead();
                        return stream;
                    }
                }

Now it does not work. I.e. file index.html is found in db, stream is returned but:
1. this method called 2 times with the same file. Usually it occurs when stream returns incorrect content.
2. browser shows url rewritten: instead of 
localhost:8082/mysvc/monitor/index.html 
it shows
www.localhost.com:8082/mysvc/monitor/index.html 
and error Server not found.

Ok, it is my details. The question is:

May be file format was changed and now stream is returned incorrectly?

How I can migrate from 0.9 ->1.0.4? 

I have attached these 2 LiteDB files.
Thank you.

[monitor_1.0.4.hdb.txt](https://github.com/mbdavid/LiteDB/files/36927/monitor_1.0.4.hdb.txt)
[monitor_0.9.hdb.txt](https://github.com/mbdavid/LiteDB/files/36928/monitor_0.9.hdb.txt)

**Comment by mbdavid** [comment]
Hi @win32nipuh, yes, v1.x has a new file format. To use v1.0.4 you will need new datafile - there is no migration tool. I recommend you to keep in v.0.9 with it´s working fine to you.
If you really want upgrade, I recommend you wait more one or two week when I release v.2beta - will be a much better LiteDB version...

**Comment by win32nipuh** [comment]
Thank you very much.
Some details: I created the new LiteDB file (as attached) and changed the code but it does not work.
I mean probably the format of internally stored files was changed and stream (see my code) cannot be used as in 0.9.

Naturally, i want to upgrade to the latest version to use all advantages.
But ok, I will work with 0.9 and wait the new version.
Thank you.

**Comment by mbdavid** [comment]
Hi @win32nipuh, now you can try this:

Open LiteDB.Shell.exe (from `master` branch):
```
open my_old_datafile.db  -- will open in version v1.0.4/v0.9.0
dump > my_dump_file.dmp`

open my_new_datafile.db  -- will create a new datafile in v.2.0.0
dump < my_dump_file.dmp
```

**Comment by win32nipuh** [comment]
Thank you, great, will test
