### ISSUE TITLE
litedb v4 FindById gets null value.

### ISSUE THREAD

**Issue by GitOffice** [mbdavid/LiteDB#802]
Model class:   
```
 [BsonId]
 public Guid Id { get; set; }
```
Insert Data：
`collection.EnsureIndex(x => x.Id);`

`var result = collection.FindById(new BsonValue("000c315e-a1e7-4de2-a9fb-09d98eac6f35"));`

result is null .  But FindAll() function is working.

thanks for helping.

**Comment by mbdavid** [comment]
Hi @GitOffice,

You dont need create index for `Id` key, it's your PK.

This `new BsonValue("000c315e-a1e7-4de2-a9fb-09d98eac6f35")` is an string, not a `Guid`. Try:

`new BsonValue(new Guid("000c315e-a1e7-4de2-a9fb-09d98eac6f35"))`

**Comment by GitOffice** [comment]
@mbdavid  Great！ thanks for saving my a lot of time.
