### ISSUE TITLE
Busy Release

### ISSUE THREAD

**Issue by alanier-laventer** [mbdavid/LiteDB#803]
I’m having multiple users connect to the database for a scheduling software. The database becomes locked while in use. Is there a ‘database.IsBusy’ or something similar that doesn’t have caveats (e.g. like ‘filewatcher.Changed’ event which detects multiple possible triggers) so that I can know when the database is completely free to be written to.
Also, if that’s not possible, is there a way to have 50 users access the same database?

**Comment by mbdavid** [comment]
Hi @alanier-laventer, are using in a web environment? There is no `IsBusy` because when datafile is write lock an you try open another instance, LiteDB keeps tring until timeout (can be defined in connection string).

The best way to manage concurreny is keep re-using same instance of LiteDatabase (or LiteRepository). It´s thread-safe and fast than create new database instance.

**Comment by alanier-laventer** [comment]
Yes,
It is used in a network environment. I am having multiple users connect to the same database. The issue I’m having is that it’s returning an exception because of the file being locked when trying to access it by several users at the same time. Is the timeout customizable?

**Comment by alanier-laventer** [comment]
This is the code that I came up with to wait for the database. Are there any caveats to this?
‘
while(dB.Engine.Locker.State != LockState.Unlocked)
{
Console.Writeline(“Waiting to be Unlocked”);
}
‘

**Comment by mbdavid** [comment]
Hi @alanier-laventer, let me ask you: are using LiteDB for .NET 3.5/4 or NetStandard 1.3/2? When are you getting this error? Is when you create new instance of LiteDatabase?

Timeout can be setted on connection string: https://github.com/mbdavid/LiteDB/wiki/Connection-String

**Comment by alanier-laventer** [comment]
I’m using one of the earlier versions- 1.3 I believe. I had started developing with it, upgraded to 4 and suddenly had errors, so I downgraded. Yes, it is when I’m creating a new instance I believe. A user will access the database to download a configuration file when a new user is added. All users have a watchfolder event that triggers when the database has a change. If there are more than 3 triggering a file download, it throws an error.
If I upgrade to 4, what are the caveats? Can I get away with 1.3 somehow?

**Comment by mbdavid** [comment]
Error to upgrade from 3.1 to 4? I didn't know about that. Both versions use same datafile structure and must be compatible (has minimal api changes).

There are some problems with concurrency in v3, so I really recommend you to upgrade. If you have any bug, open an issue so I can fix.

In v4, concurrency are more strong and simple. Datafile is always open at same mode and concurrency are made only with File locks using a special segment for this.

**Comment by alanier-laventer** [comment]
OK, I’ll make a backup and go with the newer version.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
