### ISSUE TITLE
Hierarchy Structures e.g      Org. Structures & Graphs, change notifications/subscribers

### ISSUE THREAD

**Issue by weedkiller** [mbdavid/LiteDB#806]
Hello, this is a really nice DB.

1.  Is there a **native built in way to persist hierarchies** or trees/Organization structures 
![image](https://user-images.githubusercontent.com/21086190/33158615-94d231d4-cfd9-11e7-94fc-2e69ccd531d4.png)
![image](https://user-images.githubusercontent.com/21086190/33158626-a6abf700-cfd9-11e7-8024-011e70fafdf8.png)

2.  Is it **native to the LiteDb to implement change notifications / subscribers on objects**
![image](https://user-images.githubusercontent.com/21086190/33158673-f74e4e56-cfd9-11e7-9e84-b49b684b2e5d.png)

thanks

**Comment by mbdavid** [comment]
Hi @weedkiller, sorry but there is no built in for both cases. You must implement your self a hierarchical structure using POCO classes or BsonDocument. And about pub/sub structure, you also can implement in your data layer using a single LiteDatabase instance.

**Comment by weedkiller** [comment]
Hi @mbdavid how can I detect changes saved to the POCO objects on disk.

I can do it inside the POCO object at the middleware layer, by implementing an event, but can you give me a suggestion to get it as service/registration from when the DB changes.

thanks - will close it out...

**Comment by mbdavid** [comment]
If you are using a single processes, your can do everything in memory if a class that track this changes.

If you are using multi process solution, you can save your changes in a different database (like a log database) and all process are file watch this changes.

**Comment by weedkiller** [comment]
thanks @mbdavid  any chance you can add support for change notification, it would be a great advantage over other db's
