### ISSUE TITLE
Your datafile did not terminate properly during the writing process. Reopen the file.

### ISSUE THREAD

**Issue by ghost** [mbdavid/LiteDB#809]
I use LiteDb v4 for my project and I get while application starts first time and try to upload data to LiteDb.

>   at LiteDB.LockService.DetectDatabaseChanges () [0x0008e] in <504bf0c68a324e1fafe234c36a385f58>:0 
>   at LiteDB.LockService.Write () [0x000b4] in <504bf0c68a324e1fafe234c36a385f58>:0 
>   at LiteDB.LiteEngine.Transaction[T] (System.String collection, System.Boolean addIfNotExists, System.Func`2[T,TResult] action) [0x00000] in <504bf0c68a324e1fafe234c36a385f58>:0 
>   at LiteDB.LiteEngine.Update (System.String collection, System.Collections.Generic.IEnumerable`1[T] docs) [0x0003a] in <504bf0c68a324e1fafe234c36a385f58>:0 
>   at LiteDB.LiteEngine.Update (System.String collection, LiteDB.BsonDocument doc) [0x00014] in <504bf0c68a324e1fafe234c36a385f58>:0 
>   at LiteDB.LiteFileStream.Flush () [0x0003d] in <504bf0c68a324e1fafe234c36a385f58>:0 
>   at LiteDB.LiteFileStream.Dispose (System.Boolean disposing) [0x00017] in <504bf0c68a324e1fafe234c36a385f58>:0 
>   at System.IO.Stream.Close () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.IO.Stream.Dispose () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at LiteDB.LiteStorage.Upload (System.String id, System.String filenam e, System.IO.Stream stream) [0x00058] in <504bf0c68a324e1fafe234c36a385f58>:0 
>   at BattleSpeak.Services.Data.PackagesData.SaveFile (System.IO.Stream stream) [0x0002f] in /Users/vadimkhadyka/Projects/battlespeak_xamarin_210717/BattleSpeak.Services.Data/PackagesData.cs:89 
>   at BattleSpeak.Pages.HomePage.HomePageModel+<ProcessItemDownload>d__113.MoveNext () [0x00628] in /Users/vadimkhadyka/Projects/battlespeak_xamarin_210717/BattleSpeak/BattleSpeak/Pages/HomePage/HomePageModel.cs:715 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at BattleSpeak.Pages.HomePage.HomePageModel+<DownloadDefaultPackages>d__17.MoveNext () [0x000f5] in /Users/vadimkhadyka/Projects/battlespeak_xamarin_210717/BattleSpeak/BattleSpeak/Pages/HomePage/HomePageModel.cs:195 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
>   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 

And the second issue:

> at LiteDB.LockService.DetectDatabaseChanges () [0x0008e] in <504bf0c68a324e1fafe234c36a385f58>:0
>   at LiteDB.LockService.Write () [0x000b4] in <504bf0c68a324e1fafe234c36a385f58>:0
>   at LiteDB.LiteEngine.Transaction[T] (System.String collection, System.Boolean addIfNotExists, System.Func`2[T,TResult] action) [0x00000] in <504bf0c68a324e1fafe234c36a385f58>:0
>   at LiteDB.LiteEngine.Insert (System.String collection, System.Collections.Generic.IEnumerable`1[T] docs, LiteDB.BsonType autoId) [0x00041] in <504bf0c68a324e1fafe234c36a385f58>:0
>   at LiteDB.LiteEngine.Insert (System.String collection, LiteDB.BsonDocument doc, LiteDB.BsonType autoId) [0x00014] in <504bf0c68a324e1fafe234c36a385f58>:0
>   at LiteDB.LiteStorage.Upload (System.String id, System.String filename, System.IO.Stream stream) [0x0003d] in <504bf0c68a324e1fafe234c36a385f58>:0
>   at BattleSpeak.Services.Data.PackagesData.SaveFile (System.IO.Stream stream) [0x0002f] in D:\Develop\BattleSpeak\BattleSpeak_210717_edited\BattleSpeak.Services.Data\PackagesData.cs:89
>   at BattleSpeak.Pages.HomePage.HomePageModel+<ProcessItemDownload>d__113.MoveNext () [0x00628] in D:\Develop\BattleSpeak\BattleSpeak_210717_edited\BattleSpeak\BattleSpeak\Pages\HomePage\HomePageModel.cs:713
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
>   at BattleSpeak.Pages.HomePage.HomePageModel+<DownloadDefaultPackages>d__17.MoveNext () [0x000f5] in D:\Develop\BattleSpeak\BattleSpeak_210717_edited\BattleSpeak\BattleSpeak\Pages\HomePage\HomePageModel.cs:196
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
>   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
>   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
>   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
>   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
>   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <896ad1d315ca4ba7b117efb8dacaedcf>:0
>   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0

**Comment by mbdavid** [comment]
Hi @Asseks, are you using in xamarin, right? This could be some delay about closing file in a thread while another thread are opening. LiteDB uses `FileStream.Lock` that are some different implementation in devices.
But if your datafile run in a single process, try use datafile in exclusive mode and sharing your LiteDatabase (or LiteRepository) across threads. It's much faster and do not use file lock to control this.

**Comment by Asseks** [comment]
@mbdavid yeah. I'm using Xamarin.Forms.
I use async methods for which works with LiteDb. All LiteDb connections called inside using construction. 

```
 using (var db = new LiteDatabase(ProfileConnection))
  {
           ...
   }
```

I don't use any additional options while I create ConnectionString instance expect Async = true;

`new ConnectionString(AppConstants.ProfileDatabaseName) {Async = true }  ;`

Could it be related with async threads?

**Comment by mbdavid** [comment]
Yes, this async could be a problem in concurrency environment.... but I don't know how test it. Current version are sync only and this async is like a "workaround". I recommend your open a single connection only, in exclusive mode, and share in your application this instance. Close this instance when your app closes. This will avoid open/close datafile every time your need use.

**Comment by Asseks** [comment]
@mbdavid thanks for your support. Will try and write you feedback.

**Comment by Asseks** [comment]
@mbdavid if I will use single connection in exclusive mode will I experience problems with multiply delete from LiteDb and FileStorage?
When I used to v3.1 LiteDb threw "sharing violating access exception" when I tried delete a few records from db.

**Comment by mbdavid** [comment]
Hi, v3.x has some not-fixed problems with concurrency in both thread/process. It was not possible fix in v3 so I write v4 for that. This single instance could be works in your case. If you have problem, please, copy a snippet code so I can test it.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
