### ISSUE TITLE
Exception: call "FileStorage. OpenRead" method 

### ISSUE THREAD

**Issue by gaoshang212** [mbdavid/LiteDB#81]
Sorry, my  English is very poor.

Exception in LiteDB.BsonValue.op_Implicit(BsonValue value) 

File LiteFileStorage.cs 
![qq 20151119170312](https://cloud.githubusercontent.com/assets/7921785/11266443/86c43ab6-8edf-11e5-8d0c-b23a9e4b79d2.png)

the "byId" is a collection, but there is a string paramter in the LiteFileInfo's Constructor.

**Comment by mbdavid** [comment]
Hi @gaoshang212, what value are you passing to `OpenRead`?

`FinById` excpect a `BsonValue` that has a implicit converter from `string`.

**Comment by gaoshang212** [comment]
Now,
I use
var info = db.FileStorage.FindById(fileId);
info.OpenRead();
this is right.

but  i use 
db.FileStorage.OpenRead(fileId)  
this is Exception.

the fileId is same when call FileStorage.Upload.
when i FileStorage.Upload , the paramter of stream is a MemoryStream.

**Comment by gaoshang212** [comment]
when I change the code 
![image](https://cloud.githubusercontent.com/assets/7921785/11296356/9154a790-8fac-11e5-9e62-ee7d383d9596.png)
to
return this.OpenRead(new LiteFileInfo(this.Database,doc));

this is right.

**Comment by mbdavid** [comment]
Yes, you right! To open stream, LiteFileInfo need LiteDatabase instance. I will fix this, thanks @gaoshang212

**Comment by snives** [comment]
I ran into this issue as well.  I've checked out from master, but have not seen the fix.
