### ISSUE TITLE
Cannot insert duplicate key in unique index '_id'.The duplicate value is '228'.

### ISSUE THREAD

**Issue by lingdingding** [mbdavid/LiteDB#812]
In my Application,I used to use the lietDB.dll file which is  the version of 2.0.2.0 ,but there was some promblem about process security,then i changed the version of the file to 4.0.0.0 my problem solved.
I also upgarde my database file by the tool which is called "litedbshell".but today I find a bug about upgrating database File. In the upgraded File ,There's an id of 228.，I create other objects by my application，It is an error，the  message of error is "Cannot insert duplicate key in unique index '_id'.The duplicate value is '228'. then i find in the objects I created there is one object and its id is 228. The old datas's id in database file which made by version 2.0.2.0 litedb.dll and upgraded later  doesn't seem to be in management  of version 4.0.0.0 litedb.dll.
Was the problem due to the improper use of litedb?Or other reasons?what should I do ?
Please forgive me for my poor English expression.
thank you!

**Comment by lingdingding** [comment]
The first use of this feature, where there are inappropriate places to point out.Thank you.

**Comment by mbdavid** [comment]
Hi @lingdingding,

How do you migrate your data file? Your database has password? If your data is not private, I can try migrate here do check if there is any problem in migration operation.

**Comment by lingdingding** [comment]
my database file don't have paassword，but the file is in the computer of my company， the file  is encrypted，and I'm out of the office after work now.Can you just make a use case and upgrade the database file  as I descripted？

**Comment by lingdingding** [comment]
thank you for your answer.

**Comment by Jack85** [comment]
same issue after upgrade from 3.1 to 4.1.1
it takes the lowest possible id, that was meanwhile deleted although there are other record with higher ids..

**Comment by mbdavid** [comment]
Hi @Jack85, in all verions below v4, AutoId was implemented in POCO serialization layer. In v4, this feature moved to LiteEngine and now it's possible has auto-id direct in BsonDocument. To do this, v4 now was an "Sequence" variable, per colleciton, that store this counter. It always increment in each insert. When you migrate from v3 this sequence are created using Max command:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Engine/Engine/Insert.cs#L68

**Comment by Jack85** [comment]
hmm, if look with litedbviewer it says engine database version 0, could that be that this code is not called in my case? I did upgrade=true

**Comment by mbdavid** [comment]
There is no "ugrade=true" from v3 to v4 (upgrade=true is needed only for v2 to v3/4).  v3 and v4 used same file version with few differences that are transparent to user. This database version 0 could be "User Database Version" (this version number are for user).

**Comment by Jack85** [comment]
I had to add
    ```
 var col = db.GetCollection<TEntity>();
                int i = col.Max("_id").AsInt32;
ID = i+1;
```
that solvest it on geeric method, but I dont know why in my case not caaling your max.

**Comment by Jack85** [comment]
Interesting one, after implementing this extra max and adding one record, it works on that collection again if I comment it.
But same problem stays on other collections if try to insert old way.(without my max id)

**Comment by tmpreston** [comment]
Is it possible you called Shrink() at some point?
Your error is probably related to https://github.com/mbdavid/LiteDB/issues/899 which is now fixed.

**Comment by Jack85** [comment]
I do shrink, after every file delete. So its possible.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
