### ISSUE TITLE
Generics with the same name as non-generics sometimes fail to deserialize.

### ISSUE THREAD

**Issue by Dessix** [mbdavid/LiteDB#82]
Sometimes, when dealing with classes named similarly to a generic class, the deserializer will choose to unpack to the non-generic variant. When I was using these definitions in my tests, I ran into this issue once in every ~15 or so executions:

```
		private class TestPair {
			public static TestPair<TK, TV> Create<TK, TV>(TK key, TV value) => new TestPair<TK, TV>(key, value);
		}

		public class TestPair<TK, TV> {
			public TK Key { get; set; }
			public TV Value { get; set; }
			public TestPair() { }
			public TestPair(TK key, TV value) {
				this.Key = key;
				this.Value = value;
			}
			public static implicit operator KeyValuePair<TK, TV>(TestPair<TK, TV> pair) => new KeyValuePair<TK, TV>(pair.Key, pair.Value);
			public static implicit operator TestPair<TK, TV>(KeyValuePair<TK, TV> pair) => new TestPair<TK, TV>(pair.Key, pair.Value);
		}
```

Select operations upon a collection of these items would sometimes fail with the issue that TestPair doesn't have a 0-parameter constructor, despite the fact that TestPair is not the class that was serialized, nor being worked with, but TestPair&lt;string, string&gt; was.

**Comment by mbdavid** [comment]
Hi @Dessix . This occurs only if you have two class with same name? Can you fork `master` and add unit test about this? This can be a problem in reflection emit.

**Comment by Dessix** [comment]
I'll do so as soon as I can, then reference the fork here.

**Comment by Dessix** [comment]
I apologise, it appears as if this is actually issue #78 surfacing again elsewhere. I attempted to write up a test for it, but could not replicate unless it was running simultaneously, wherein it seems to fail with the `Failed to create instance for type ... checks if has a public constructor with no parameters` in `Reflection.CreateInstance` while multiple simultaneous databases were open, but not overlapping in writes to the drive with each other... Maybe some odd reflection caching issue?

My full stack trace from [MPM's source code](https://github.com/DSTech/MPM/blob/master/MPMTest/ProfileTests.cs#L14):
```
Test Name:	MPMTest.ProfileTests.ProfileSaving
Test FullName:	MPMTest.ProfileTests.ProfileSaving
Test Source:	C:\Code\MPM\MPMTest\ProfileTests.cs : line 14
Test Outcome:	Failed
Test Duration:	0:00:00.206

Result StackTrace:	
at LiteDB.Reflection.CreateInstance(Type type)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
   at LiteDB.LiteCollection`1.<Find>d__9.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at LiteDB.LiteCollection`1.FindById(BsonValue id)
   at MPM.Core.Profiles.LiteDbProfileManager.Fetch(Guid profileId) in C:\Code\MPM\MPM\Core\Profiles\LiteDbProfileManager.cs:line 27
   at MPMTest.ProfileTests.ProfileSaving() in C:\Code\MPM\MPMTest\ProfileTests.cs:line 24
Result Message:	LiteDB.LiteException : Failed to create instance for type 'MPM.Core.Profiles.MutableProfile' from assembly 'MPM.Core.Profiles.MutableProfile, MPM, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Checks if has a public constructor with no parameters
```

Note that `MutableProfile` in the above is most definitely in possession of a 0-parameter constructor. Also note that this test succeeds 95+% of the time, but can fail if many tests utilizing LiteDB are occurring simultaneously in a non-appdomain-isolated system.

**Comment by mbdavid** [comment]
Hi @Dessix, I didn't test your code, but you can test it on v2? This new version ir more robust for concurrency and threading. Maybe works fine. Thanks,

**Comment by Dessix** [comment]
I have no particular test for it, but I have run into the issue again, this
time without a similarly named generic class to accompany the issue. The
reason I have no test is that it seems to only occur when all 15 of my unit
tests are running simultaneously.
The class was simple, just two strings, one marked as an index and both
marked as fields. It seems to be some issue with types being registered
into the global mapper through usage in each database instance?

**Comment by mbdavid** [comment]
BsonMapper has a static instance for cache type maps. In v2, I add a `lock` statment when getting type for first time, so I think this problem gone.

**Comment by Dessix** [comment]
This occurred, last night, in v2.

**Comment by faxedhead** [comment]
Yes I can also confirm this is still a problem in v2 as per my update on issue #78.

**Comment by Dessix** [comment]
Was this closed due to being fixed?

**Comment by mbdavid** [comment]
BsonMapper had a lot of changes in this last release `v2.0.0-rc2`. I tried to simulate but didnt catch this problem. If this problem persist to you, please re-open this issue and attach some code to test.
