### ISSUE TITLE
Search by references types

### ISSUE THREAD

**Issue by stravinci** [mbdavid/LiteDB#820]
Is there any way to Find document using referenced type?
Example which return empty list:
    `var searchDb = db.Query<Order>()
    .Include(x => x.Customer)
    .Include(x => x.Products)
    .Where(x => x.Customer.Age > 18)
    .ToList();`

Example which return proper list:
`var searchLocally = db.Query<Order>()
    .Include(x => x.Customer)
    .Include(x => x.Products)
    .ToList()
    .Where(x => x.Customer.Age > 18);`

**Comment by mbdavid** [comment]
Hi @stravinci, it's not possible because `Includes` runs only on results (after apply filter). There is no join like sql. And than works in your second example because it´s a simple Linq-To-Object filter and occurs after you deserialize all documents

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
