### ISSUE TITLE
Using Dictionaries where the key value is an item from a collection?

### ISSUE THREAD

**Issue by yoshisman8** [mbdavid/LiteDB#823]
Im trying to set up a class where i have a property of the `Dictionary<BaseItem, Int>` type. and `BaseItem` is an item from a collection. 
Does LiteDB support just adding a [BsonRef("Items")] on top of that dictionary and it will automatically fill in the data for that key value?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
