### ISSUE TITLE
LiteDB.dll picked up on ClamAV scan

### ISSUE THREAD

**Issue by tccloudz** [mbdavid/LiteDB#824]
I included the LiteDB.dll in a mono project and happen to run a scan on my machine using ClamAV and it detected the file as ransomeware. I deleted the original file and re-downloaded and re-scanned the file specifically and the result was the same. Could be a false positive, but wanted to open an issue just in case. I am running Lubuntu 17.10.

/home/XXX/Downloads/LiteDB.dll: Win.Ransomware.Generic3-6369615-1 FOUND

**Comment by mbdavid** [comment]
Hi @adviceforcedev, that's strange...is this version are from nuget?

**Comment by adviceforcedev** [comment]
@mbdavid , I downloaded the file from this page: https://github.com/mbdavid/LiteDB/releases.

The specific url to the file is: https://github.com/mbdavid/LiteDB/releases/download/v4.0.0/LiteDB.dll

**Comment by mbdavid** [comment]
Hi @adviceforcedev, do not use from this url. I provide only .NET 4.0 assemlby there (for windows only). If you are using linux, you must use "net standard 2.0" version. In this case you must use nuget version. In nuget all versions are available.
