### ISSUE TITLE
LiteStorage.Upload takes 3 arguments when using a stream, but Wiki only shows 2

### ISSUE THREAD

**Issue by OrellBuehler** [mbdavid/LiteDB#825]
The FileStorage.Upload takes 3 arguments when using a stream to upload. But in the Wiki/Documentation it only shows 2. 

Upload(string id, string filename, Stream stream) vs. Upload(string id, Stream stream)

**Comment by mbdavid** [comment]
Hi @OrellBuehler, I update this method in last version and forgot to update wiki... Thanks

**Comment by OrellBuehler** [comment]
@mbdavid great work 👍
