### ISSUE TITLE
Return codes from insert and update

### ISSUE THREAD

**Issue by excepticons** [mbdavid/LiteDB#827]
Hello.
Pleasem how can I get a return value for:

```
collection.Insert(...);

collection.Update(...);
```

I need to know if Insert and Update really run when info exists.

Thanks.

**Comment by mbdavid** [comment]
Hi, if insert has any problem to run, an exception will be throw. Also, insert method returns _id value. And update returns true/false with document exists (or not).

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
