### ISSUE TITLE
Searching arrays does not work in LiteDB 4.0

### ISSUE THREAD

**Issue by michaelelleby** [mbdavid/LiteDB#829]
[ConsoleApp8.zip](https://github.com/mbdavid/LiteDB/files/1547985/ConsoleApp8.zip)

It works with 3.1.4, but upgrading to LiteDB 4.0 breaks the code.
I'm using an in-memory database, so it is re-created on each run and therefore the problem cannob be related to the database being created by version 3.1.4.

I've attached a small sample app which demonstrates the issue.

**Comment by mbdavid** [comment]
Hi @ongobongo, that because you need create index on your array item using ensureindex (v3 auto-create this index, bu in v4 you must manually create). Try:

```C#
collection.EnsureIndex(x => x.Channels);

collection.Find(Query.EQ("Channels", "VALUE")).ToList();
```

**Comment by ongobongo** [comment]
Added that code, still returns 0 results.
```collection.Upsert(documents);

collection.EnsureIndex(x => x.Channels);

var rows = collection
	.Find(Query.EQ(nameof(MyDocument.Channels), BsonValue("TEST CHANNEL")))
	.ToList();```

**Comment by mbdavid** [comment]
Ok, try use expression:

```
collection.EnsureIndex(x => x.Channels, "$.Channels[*]");
```

**Comment by ongobongo** [comment]
That fixed it
```collection.Upsert(documents);

collection.EnsureIndex(x => x.Channels, "$.Channels[*]");

var rows = collection
	.Find(Query.In(nameof(MyDocument.Channels), "TEST CHANNEL"))
	.ToList();```

Maybe there's a bug in the index handling.

**Comment by mbdavid** [comment]
It's because IEnumerable are not mapping to `$.Channels[*]` expression (are mapping to `$.Channels` only)... if you change to `List<T>` will works without expressions. I will investigate why IEnumerable are not mapping as expected.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
