### ISSUE TITLE
JDBC Support 

### ISSUE THREAD

**Issue by IdanWo** [mbdavid/LiteDB#830]
Hey,
I'm really thrilled using this DB. However, I have to make sure it supports JDBC driver for connecting through logstash.

**Comment by mbdavid** [comment]
Hi, @IdanWo, JDBC is not "Java Database Connector" (some similar to ODBC)? As I know it's used for SQL relational databases and server based. It's not for LiteDB, which run under same client process.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
