### ISSUE TITLE
Suggestions on how to maintain compatibility with v2.X database version??

### ISSUE THREAD

**Issue by shemp11** [mbdavid/LiteDB#832]
I have litedb files shared between multiple applications. Is there any method/approach I can use to allow an application to access litedb files with different database versions? I'd like to update to the current version of the litedb library for new apps (and new releases of existing apps), but I don't want to automatically update the database as it would break the old apps.

**Comment by mbdavid** [comment]
Hi @shemp11, unfortunately it is not possible to maintain compatibility between these two versions. LiteDB v3/4 use new datafile version 7, when LiteDB v2 uses old datafile v6.

If you want, you can create an proxy class that filter/select version and use specified version of each LiteDB. Take a look on this old shell version that I made that support multi datafile version

https://github.com/mbdavid/LiteDB/tree/v2.0.4/LiteDB.Shell

I added old LiteDB dll version into resource folder and call based on datafile version.
