### ISSUE TITLE
Strange exception when comparing in exists clause

### ISSUE THREAD

**Issue by a-a-k** [mbdavid/LiteDB#837]
```
 public static void AddItems(long chatId, List<Items> itemsList)
        {
            using (var db = new LiteDB.LiteDatabase("MyDb"))
            {
                var items = db.GetCollection<Items>("Items");
                var users = db.GetCollection<Users>("Users");
                var clients = db.GetCollection<Clients>("Clients");
                var clientId = clients.FindOne(c => c.UserId == users.FindOne(u => u.ChatId == chatId).Id).Id;
                if (items.Exists(i => i.IdClient == clientId && itemsList.Any(l => l.Name == i.Name)))
                {
                    return;
                }
```
I get an InvalidOperationException error with that message

> variable 'i' of type 'Models.Items' referenced from scope '', but it is not defined

and stack trace

>    at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
>    at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
>    at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
>    at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
>    at System.Linq.Expressions.Compiler.VariableBinder.VisitUnary(UnaryExpression node)
>    at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
>    at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
>    at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
>    at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
>    at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
>    at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
>    at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
>    at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
>    at LiteDB.QueryVisitor`1.VisitValue(Expression expr, Expression left)
>    at LiteDB.QueryVisitor`1.VisitValue(Expression expr, Expression left)
>    at LiteDB.QueryVisitor`1.VisitExpression(Expression expr, String prefix)
>    at LiteDB.QueryVisitor`1.ParseEnumerableExpression(MethodCallExpression expr)
>    at LiteDB.QueryVisitor`1.VisitExpression(Expression expr, String prefix)
>    at LiteDB.QueryVisitor`1.VisitExpression(Expression expr, String prefix)
>    at LiteDB.LiteCollection`1.Exists(Expression`1 predicate)

**UPD**

Now I've tried to change the second conditional expression and that works! 
`if (items.Exists(i => i.IdClient == clientId && itemsList.Select(l => l.Name).Contains(i.Name)))`

**Comment by mbdavid** [comment]
Hi @a-a-k, it´s quite hard to translate Linq expression to `Query` class. So, there is no no complete LINQ implementation. Its possible check QueryVisitor to see what are implemented. There are a special case no IEnumerable contains tests.

Also, I recommend you do create indexes to your query (if not exists).
