### ISSUE TITLE
Query para ordenação aparentemente não esta funcionando

### ISSUE THREAD

**Issue by MarceloDMC** [mbdavid/LiteDB#842]
Olá! 

Continuando meu trabalho com o LiteDB estou utilizando `Query` para realizar filtros nas minhas coleções. Na parte de filtragem tudo esta funcionando perfeitamente. No entanto estou encontrando dificuldades em realizar a ordenação dos mesmos.

A listagem de elementos retornados após o uso de uma  `Query` para ordenar continua na mesma ordem da inserção:

```csharp
/// <summary>
/// Classe com letras do alfatabeto
/// </summary>
public class Letters
{
	[BsonId(true)]
	public long ID { get; set; }

	/// <summary>
	/// Letra
	/// </summary>
	public string Letter { get; set; }

	public Letters(string letter = "")
	{
		this.Letter = letter;
	}

	public Letters() { }
}

/// <summary>
/// The main entry point for the application.
/// </summary>
static void Main(params string[] args)
{
	// Abre conexão com o banco
	using (LiteDatabase litedb = new LiteDatabase(Path.Combine(Base.ApplicationData, "letters.db")))
	{
		// Inicializa coleção
		LiteCollection<Letters> lcoll = litedb.GetCollection<Letters>();

		// Insere letras
		lcoll.Insert(new Letters("C")); lcoll.Insert(new Letters("D"));
		lcoll.Insert(new Letters("F")); lcoll.Insert(new Letters("A"));
		lcoll.Insert(new Letters("G")); lcoll.Insert(new Letters("Z"));
		lcoll.Insert(new Letters("C")); lcoll.Insert(new Letters("N"));
		lcoll.Insert(new Letters("Z")); lcoll.Insert(new Letters("B"));

		// Texto com o output
		TextWriter tw = new StreamWriter("D:\\teste\\ORDER.txt");

		// Recupera todos os elementos na ordem inserida
		IEnumerable<Letters> insertedorder = lcoll.FindAll();

		// Grava elementos no arquivo
		tw.Write("Inserted   Order: ");
		foreach (Letters letter in insertedorder) tw.Write(letter.Letter + " ");
		tw.WriteLine(); tw.WriteLine("- - - ");

		// Faz ordenação crescente
		IEnumerable<Letters> ascendingorder = lcoll.Find(Query.All("Letter", Query.Ascending));

		// Grava elementos ordenados no arquivo
		tw.Write("Ascending  Order: ");
		foreach (Letters letter in ascendingorder) tw.Write(letter.Letter + " ");
		tw.WriteLine(); tw.WriteLine("- - - ");

		// Faz ordenação descrescente
		IEnumerable<Letters> descendingorder = lcoll.Find(Query.All("Letter", Query.Descending));

		// Grava elementos ordenados no arquivo
		tw.Write("Descending Order: ");
		foreach (Letters letter in descendingorder) tw.Write(letter.Letter + " ");
		tw.WriteLine(); tw.WriteLine("- - - ");

		// Procura elemento
		IEnumerable<Letters> foundletters = lcoll.Find(Query.Contains("Letter", "Z"));

		// Grava elementos encontrados
		tw.Write("Found    Letters: ");
		foreach (Letters letter in foundletters)
			tw.Write("{ID: " + letter.ID + ", Letter: " + letter.Letter + "} ");

		tw.Dispose();

		// Abre arquivo
		Process.Start("D:\\teste\\ORDER.txt");
	}
}
```
Informações gravadas no arquivo: 
```
Inserted   Order: C D F A G Z C N Z B 
- - - 
Ascending  Order: C D F A G Z C N Z B 
- - - 
Descending Order: C D F A G Z C N Z B 
- - - 
Found    Letters: {ID: 6, Letter: Z} {ID: 9, Letter: Z} 
```

As queries estão funcionando como pode ser visto no exemplo de busca que fiz ao final. Porém a ordenção nao funciona. Estou fazendo algo de errado?

**Comment by mbdavid** [comment]
Oi Marcelo,

O que acontece neste caso é que tu não está criando nenhum índice para a busca, e por isso a busca é ordenada apenas pelo ID (neste caso).

Utilize `lcoll.EnsureIndex(x => x.Letter)` para que seja criado um índice nesta coluna. Dai sim, ao fazer a busca (usando o Query.All("Letter")) vai funcionar como esperado.

Lembrando, essa ordenação não é, obrigatoriamente do resultado, e sim do indice que está sendo utilizado. Neste teu caso vai funcionar como esperado, mas para pesquisar mais complexas pode te dar resultados diferentes. Por vezes aconselho a utilizar o `.OrderBy()` do LINQ depois de executar o metodo `Find()`.

Na versão 4.1 lancei como experimental o ordenação internamente dentro do banco de dados (pode ser uma boa caso tu tenha um volume grande de dados a ordenar em uma paginação). Olha o projeto LiteDB.Demo dentro dos fontes que ali tem um exemplo. A implementação está apenas no nivel de `BsonDocument`, se tu quiser converter para classe vai precisar usar o mapeador (`BsonMapper.Global.ToObject`)

**Comment by MarceloDMC** [comment]
Olá!

Utilizando `EnsureIndex` ao se inicializar minha coleção a ordenação passou a funcionar.

O meu problema agora é que devido ao tipo de informação que estou trabalhando, esbarrei no limite de 16 "índices" que posso criar 😄. Acima disso da erro.

Esse limite é por alguma questão de performance? Tentei procurar se existia alguma maneira de altera-lo mas não consegui. Terei que dar uma repensada nas minhas informações para deixar tudo facilmente ordenavel.

Vou dar uma olhada na ordenação interna do banco de dados que você comentou.

Muito obrigado!

**Comment by mbdavid** [comment]
Sim, o limite é por uma questão de performance de insert/update/delete. Mas veja, tu não é obrigado e ter índice em todas as colunas para pesquisar em todas elas. O indice deve ser criado nas colunas que fazem sentido ter indice e que, com o uso do indice, vai reduzir o tempo de consulta. Penso em aumentar isso numa próxima versão para 32 indices, mas fico preocupado com a questão de quão caro vai custar inserir um novo registro.

Pelos meus testes, cada índice custa o mesmo que a inclusão do dado em si. Ou seja, a inclusão de 1 registro somente com o indice PK (sobre o Id, que é criado automaticamente) leva tempo 1 U.T. Cada novo indice o tempo aumenta em 0.5 U.T. Ou seja, num documento de 16 indices, o tempo leva 8,5 U.T.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
