### ISSUE TITLE
Cannot insert a record with id value 0

### ISSUE THREAD

**Issue by ftamminga** [mbdavid/LiteDB#843]
When adding a record with an Id that has a value of 0 (zero), LiteDb will set the Id to '1'.
This is unexpected and undesired behavior. I have a fixed database table that I want to cache locally using LiteDb.

**Comment by mbdavid** [comment]
Hi @ftamminga, that' because, by default, `0` means `default(int)` and auto-id are enabled by default. If you disable auto-id, you can use:

```C#
// class decorate
public class Customer
{
    [BsonId(false)]
    public int Id { get; set; }
}

// or via fluent-api
BsonMapper.Global.Entity<Customer>()
    .Id(x => x.Id, false);
```

**Comment by ftamminga** [comment]
Thanks!
The fluent-api setting was just what It needed, since my model is code generated.

**Comment by bluekuen** [comment]
Thanks! I was also wondering!

**Comment by JensSchadron** [comment]
@ftamminga I'm closing the issue as it looks like this one resolves your issue. Feel free to reopen if it wasn't the case.
