### ISSUE TITLE
.NET Framework version

### ISSUE THREAD

**Issue by dvladimirovich** [mbdavid/LiteDB#845]
Does it support .NET Framework 4.5 or higher?

**Comment by mbdavid** [comment]
Hi @dvladimirovich, yes. For .NET Framework 4.5 (4.6 or 4.7) you can use .NET40 version. Using nuget you get right version to your project target framework.

**Comment by dvladimirovich** [comment]
Ok, thanks for such a fast response! And one more question about speed test. For example, I have a db with few tables (connected via foreign key) and with over 100k records. What about speed of performing select data, with where clauses etc?

**Comment by mbdavid** [comment]
There is no problem with this data volume. In current master branch, I made an example with 100k (simple document, only 3 fields) with insert/query tests performance (with Sqlite compare).

LiteDB uses index to speed up select data. In this code example, LiteDB also paging data with order support in about 10ms (I'm using SSD here).

You can also check this compare (with v3):

https://github.com/mbdavid/LiteDB-Perf

**Comment by dvladimirovich** [comment]
Could you, please, provide a link to 100k example? And does this example uses some join clauses?

**Comment by mbdavid** [comment]
Demo version are inside master branch, in `LiteDB.Demo` project inside solution.

For include examples, you can see here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB.Tests/Database/DbRef_Include_Tests.cs

**Comment by dvladimirovich** [comment]
Ok, thanks

**Comment by weedkiller** [comment]
@dvladimirovich @mbdavid its much faster with the [latest 4.71 release ] because of GC improvements (https://blogs.msdn.microsoft.com/dotnet/2017/10/17/announcing-the-net-framework-4-7-1/)

![image](https://user-images.githubusercontent.com/21086190/34276585-1a11bc82-e670-11e7-9984-2652ffbd4e32.png)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
