### ISSUE TITLE
BsonMapper.ToObject deserialize incorrect properties with VS2015

### ISSUE THREAD

**Issue by jemmun** [mbdavid/LiteDB#846]
Any one find this issue? 
I running same code under VS2015, object properties are incorrect, but VS2017 can be correct. 
Is this a bug or my fault?

```C#
static void Main(string[] args)
{
    string path = "C:\\SQLite\\test.db";
    Sec_1D sec = new Sec_1D();
    using(var db = new LiteDatabase(path))
    {
        var col = db.GetCollection("Sec1D");
        var value = col.FindById(2);
        value["Size"] = new BsonArray { 9.0, 8.7, 7.2, 4.3 };
        value["Mod"] = new BsonArray {4.3,5.4,7.6,5.6,2.4,4.5,7.9,10.2 };
        col.Update(value);
        BsonMapper bm = new BsonMapper();                
        sec4 = bm.ToObject<Sec_1D>(value);
        Console.WriteLine(value.ToString());
        Console.WriteLine(sec.Mod[1]);
    }            
    Console.ReadKey();
}
```
many thanks.

**Comment by mbdavid** [comment]
Hi @jemmun,

Can you paste your `Sec_1D` class? There are some mixes between POCO classes vs BsonArray/Value.

**Comment by jemmun** [comment]
@mbdavid  many thanks for you reply.

sure, below FYI. Please ignore the Chinese.

In VS2015, if print sec.Size that will be show the value of sec.Mod, and sec.Mod still keep default value. BsonDocument object value.ToString is correct.

public class Sec_1D
    {
        private int _id;
        private string _name;
        
        private int _type = 1; 
        
        private double[] _size = new double[4]{ 0,0,0,0};
        
        private double[] _mod = new double[8]{ 1,1,1,1,1,1,1,1};

        public int Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }

        }

        public string Name
        {
            get
            {
                return _name;
            }

            set
            {
                _name = value;
            }
        }
        /// <summary>
        /// int类型type,可以使用typeToString取回string类型type
        /// </summary>
        public int Type
        {
            get
            {
                return _type;
            }

            set
            {
                _type = value;
            }
        }
        /// <summary>
        /// double数组长度为4，默认值为(0,0,0,0)
        /// </summary>
        /// <exception cref="IndexOutOfRangeException"></exception>
        public double[] Size
        {
            get
            {
                return _size;
            }

            set
            {
                if(value.Length != 4)
                {
                    throw (new IndexOutOfRangeException("Length of value should be 4"));
                }else
                {
                    _size = value;
                }
                
            }
        }
        /// <summary>
        /// Length of value is 8,默认值为（1，1，1，1，1，1，1，1）
        /// </summary>
        /// <exception cref="IndexOutOfRangeException"></exception>
        public double[] Mod
        {
            get
            {
                return _mod;
            }

            set
            {
                if (value.Length != 8)
                {
                    throw (new IndexOutOfRangeException("Length of value should be 8"));
                }
                else
                {
                    _size = value;
                }
            }
        }

        /*
        public Sec_1D()
        {
            _id = Guid.NewGuid();
        }
        */

        /// <summary>
        /// 1-矩形；2-圆形；3-工字形；4-圆管；5-方管
        /// </summary>
        /// <returns>string</returns>
        public string typeToString()
        {
            string type;
            int id = this.Type;
            switch (id)
            {
                default:
                    type = "rectangle";
                    break;
                case 2:
                    type = "circular";
                    break;
                case 3:
                    type = "I-shaped";
                    break;
                case 4:
                    type = "circular tube";
                    break;
                case 5:
                    type = "Square tube";
                    break;
            }
            return type;
        }
    }

**Comment by jemmun** [comment]
Hi @mbdavid 
I have to say that, that may be caused by “if” in my setter.  i remove if code, mapper is working.
thanks.

**Comment by mbdavid** [comment]
Hi @jemmun, that could be because version of Reflection are you using. LiteDB has 2 ways to set value and it's depend your version. Maybe expression works and direct reflection dont. Here the code:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/Reflection/Reflection.Expression.cs#L43

**Comment by jemmun** [comment]
Hi @mbdavid 

many thanks for your help, it's very useful.
