### ISSUE TITLE
Support to clear cache would be good

### ISSUE THREAD

**Issue by gatapia** [mbdavid/LiteDB#848]
I currently have unit tests that are failing due to the LiteDB cache.  I delete the DB file on TestInit and TestDispose but when I create a new LiteDatabase next time it still has stale data in the cache (from prev test).

Ideally I would like to do something like this:
```
[TestInitialize, TestCleanup] public void CleanUp() {
  if (File.Exists(filename)) File.Delete(filename);
  using (var db = new LiteDatabase(filename)) {
    db.Engine.Cache.ClearPages();  // but the _cache is not accessible
  }
}
```

**Comment by mbdavid** [comment]
Are you reusing same `LiteDatabase` instance for your all tests? Because each `LiteDatabase` instance contains a own cache pages.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
