### ISSUE TITLE
Query.In not working for Id

### ISSUE THREAD

**Issue by deerchao** [mbdavid/LiteDB#859]
Using LiteDB 4.1 via Nuget.

	void Main()
	{
		var db = new LiteDatabase(@"d:\temp\lite.db");
		var foo = db.GetCollection<Model>();
		foo.Insert(new Model { Name = "foo" });
		foo.Insert(new Model { Name = "bar" });

		// foo
		Console.WriteLine(foo.FindById(1).Name);
		
		// 0
		Console.WriteLine(foo.Find(Query.In("Id", 1, 2)).Count());

		// 2
		Console.WriteLine(foo.Find(Query.In("Name", "foo", "bar")).Count());
	}

	class Model
	{
		public int Id {get;set;}
		public string Name{get;set;}
	}

**Comment by mbdavid** [comment]
Hi @deerchao, `Id` class property (or any other mapped as BsonId) are converted in `_id` document field. So, try: 
```
Console.WriteLine(foo.Find(Query.In("_id", 1, 2)).Count());
```

**Comment by deerchao** [comment]
Thanks, now it's working.
