### ISSUE TITLE
Can LiteDB work in universal app of Windows10 ?

### ISSUE THREAD

**Issue by synontanaka** [mbdavid/LiteDB#86]
We are implementing a universal app of Windows10.
I looking for NoSQL database library which supports universal app.
I know LiteDB is "100% C# code for .NET". but I don't know LiteDB is supported universal app or not.

If LiteDB is supported universal app, it is good for us.

**Comment by mbdavid** [comment]
Hi @synontanaka, LiteDB is 100% C# but it not yet runnable in universal app. To be honest, I'm new in this new multi-target .NET projects. I´m using Json.Net/EntityFramework for studing how they did. I have plan to implement for all (or almost all) plataforms for .NET, including .NET Core 5.

**Comment by synontanaka** [comment]
Hi @mbdavid 
Thank you for your comment.

**Comment by nohwnd** [comment]
Hello,
there is a tool called [ApiPort](https://github.com/Microsoft/dotnet-apiport/releases) that you can use to analyze your library and get recommended solutions.

![image](https://cloud.githubusercontent.com/assets/5735905/13652028/4f839bd8-e64a-11e5-8b5f-e30fb9383b6b.png)

This is the summary of the tool. In the details you can see that the Emit and Cryptography stuff are the two main pain points. 

Cryptography might not make that much sense for mobile apps, as the devices tend to be already encrypted, and doing the encryption twice does not make much sense. So moving that to a different library that is available only on some versions of your db might solve it for you. 

The Emit stuff I sadly don't know much about, but there is no chance that it will be permitted on AOT devices. ;/

If there is anything I can help with, let me know.

**Comment by mbdavid** [comment]
Hi @nohwnd. Nice tool, I will check it. Remove emit was implemented in a pull request (witch is open) but i didnt see/test yet.

**Comment by nohwnd** [comment]
@mbdavid I was able to make it build as a PCL librabrary for UWP and .NET core. But I had to take some shortcuts. Please have a look on my branch [pcl3](https://github.com/nohwnd/LiteDB/tree/pcl3) there is a new project that contains all the changes. I did not want to make a PR because it's very rough, but I think you'll be able to see that not that much needed to change.

**Comment by mbdavid** [comment]
After a long time it's now possible. `master` branch support UWP and PCL

**Comment by nohwnd** [comment]
Awesome!
