### ISSUE TITLE
Threat Detected by ClamAV

### ISSUE THREAD

**Issue by devcanute** [mbdavid/LiteDB#862]
20180104 18:00 UTC
When I downloaded LiteDB.dll v4.1.0 and v4.0 release TotalVirus ClamAV reported a threat.

TotalVirus  LiteDB.dll  v4.1.0
ClamAV detected Win.Ransomware.Generic3-6369615-1 

01/04/2018  10:50 AM    <DIR>          .
01/04/2018  10:50 AM    <DIR>          ..
01/04/2018  10:39 AM         1,051,622 LiteDB-4.1.0.tar.gz
01/04/2018  10:39 AM         1,179,690 LiteDB-4.1.0.zip
01/04/2018  10:39 AM           347,136 LiteDB.dll
01/04/2018  10:39 AM            25,088 LiteDB.Shell.exe

same threat reportedd with v4.0 release

01/04/2018  10:53 AM           149,385 LiteDB-4.0.0.tar.gz
01/04/2018  10:53 AM           269,795 LiteDB-4.0.0.zip
01/04/2018  10:52 AM           298,496 LiteDB.dll
01/04/2018  10:52 AM            28,672 LiteDB.Shell.exe

v4.0.0-beta2  was clean so I used it.

**Comment by devcanute** [comment]
The url I used to download V4.1.0 which reported the threat was 
https://github.com/mbdavid/LiteDB/releases

Next I downloaded 4.1.0 from nuget and TotalVirus ClamAV reported everrything OK.

SHA-256 | 25af1b3187551576733a86db0d563d55bda0e092f5976fe1c8c752c48febf784
-- | --
litedb.4.1.0.nupkg
639.33 KB
2018-01-04 19:30:17 UTC

Then I unzipped the nupkg and scanned LIteDB.dll from bin\lib\net40
Again ClamAV reported the Ransomware threat.

SHA-256 | 6f82f1730ae505e19e40a9ee22e10b20f20c31b4966958833f8f294fee0c798f
-- | --
LiteDB.dll
339 KB
2017-12-30 19:03:54 UTC

**Comment by mbdavid** [comment]
Hi @devcanute, could you test compile source code in your machine? I have no ideia how is possible this dll be a ransomware threat

**Comment by mbdavid** [comment]
I just try with 4.1.1 and get same result:


Antivirus | Result | Update
-- | -- | --
ClamAV | Win.Ransomware.Generic3-6369615-1 | 20180108

But, using LiteDB.Shell.exe there no problem, all clean.

**Comment by timleader** [comment]
We managed to get around this issue, by simply not signing the assembly, 

This is an acceptable solution for us though I understand this may not be an appropriate solution for everyone.

**Comment by yuxin5156** [comment]
there is no problem on my machine

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
