### ISSUE TITLE
System.InvalidCastException: 无法将类型为“System.Int32”的对象强制转换为类型“System.String”

### ISSUE THREAD

**Issue by lidanger** [mbdavid/LiteDB#864]
Sometimes, I got an exception like this:

System.InvalidCastException: 无法将类型为“System.Int32”的对象强制转换为类型“System.String”。
   在 lambda_method(Closure , Object , Object )
   在 LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value)
   在 LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   在 LiteDB.BsonMapper.ToObject(Type type, BsonDocument doc)
   在 LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
   在 LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   在 System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)

And the entity class is :

    public class Point
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>The identifier.</value>
        public LiteDB.ObjectId Id { get; set; }

        /// <summary>
        /// Gets or sets the code.
        /// </summary>
        /// <value>The code.</value>
        public string Code { get; set; }

        /// <summary>
        /// Gets or sets the time.
        /// </summary>
        /// <value>The time.</value>
        public DateTime Time { get; set; }

        /// <summary>
        /// 统一单位 浓度废水mg/l，废气mg/m3 流量废水l/s，废气m3/s.
        /// </summary>
        /// <value>The value.</value>
        public double Value { get; set; }

        /// <summary>
        /// Gets or sets the string value.
        /// </summary>
        /// <value>The string value.</value>
        public string StringValue { get; set; }

        /// <summary>
        /// Gets or sets the total.
        /// </summary>
        /// <value>The total.</value>
        public double Total { get; set; }

        /// <summary>
        /// Gets or sets the other.
        /// </summary>
        /// <value>The other.</value>
        public double Other { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="Point"/> is ok.
        /// </summary>
        /// <value><c>true</c> if ok; otherwise, <c>false</c>.</value>
        public bool OK { get; set; }

        /// <summary>
        /// 0=浓度 1=参数 2=流量
        /// </summary>
        /// <value>The type.</value>
        public int Type { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Point"/> class.
        /// </summary>
        public Point()
        {
            Id = LiteDB.ObjectId.NewObjectId();
        }
    }

So, where is the problem and how can I resolve this?
 @mbdavid

**Comment by mbdavid** [comment]
Hi @lidanger, when you got this error? I just release a new version that fix a bug on deserialization bson in concurrency environment.

**Comment by lidanger** [comment]
The version is 4.1.0.0
@mbdavid
