### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by ahmedflix25** [mbdavid/LiteDB#867]
1- Can I make id type long (int64) with auto increment?
2- Can I make id and name both unique or more and how ?
3- What is the best way to upload/save a file with a insert or update then select it?

**Comment by mbdavid** [comment]
Hi,

1- Yes, Auto-Id is supported in Int32, Int64, Guid, ObjectId and DateTime
2- Yes, but you need create an sub-document on index definition, like this:
`db.EnsureIndex("col", "idx_name", "{id: $._id, Name: $.Name}", true)`
In this case, you `idx_name` contains a new document based on your `_id` and `Name` field (field are case sensitive)
3- To work with files you always use FileStorage class that simplify your file split insert (there is no file update, only insert/delete). FileStorage use 2 internal classes, _files and _chunks that you can use find to select.

Try use shell tool no check your database collections and see how better works for you

**Comment by ahmedflix25** [comment]
thanks
