### ISSUE TITLE
How to delete a record?

### ISSUE THREAD

**Issue by Skysper** [mbdavid/LiteDB#87]
It seems there is little document about how to delete a record!

            string key = DbHelper.GetCollectionName(typeof(T).FullName);//here to delete the . in name
            using (var liteDb = new LiteDB.LiteDatabase(AppBase.AppContext.Current.DbName))
            {
                var op = liteDb.GetCollection<T>(key);
                var value=new LiteDB.BsonValue(id);//id is an int parameter passed in
                return op.Delete(value);
            }
I used it like this and it return a false value.
and I don't know why it fails.
So please give me some help.
Thanks.

**Comment by mbdavid** [comment]
Hi @Skysper, your code are correct. To delete is call `col.Delete(id)`. Did you try test before is record exists (using `col.Exists(Query.EQ("_id", id))`)? Can you write a small unit test code to reproduce the problem?

**Comment by Skysper** [comment]
There is something wrong with my code.I do the test,It's OK now.Thanks very much. @mbdavid
