### ISSUE TITLE
Database property

### ISSUE THREAD

**Issue by v2kiran** [mbdavid/LiteDB#870]
Hi Mauricio

i am wrapping litedb in PowerShell :).
Wondering if there is a way to determine the database that has been opened by a connection. Asking because when we work with multiple litedb databases it will be difficult to distinguish which connection belongs to which db.

**Comment by mbdavid** [comment]
Hi @v2kiran, hummm I think there is no external proprerty do tell you about this. In LiteDatabase class, there are ConnectionString instance (that contains filename), but it's only private. Exposing this will help you?

**Comment by DeanVanGreunen** [comment]
Hi @v2kiran 

try the following 👍 

1. Using OpenFiles:
You should be able to use the [openfiles command](http://technet.microsoft.com/en-us/library/cc732490(WS.10).aspx) from either the regular command line or from PowerShell.The openfiles built-in tool can be used for file shares or for local files. For local files, you must turn on the tool and restart the machine (again, just for first time use).
I believe the command to turn this feature on is: `openfiles /local on`
For example (works on Windows Vista x64): `openfiles /query \| find "chrome.exe"`
That successfully returns file handles associated with Chrome. You can also pass in a file name to see the process currently accessing that file.

**Comment by v2kiran** [comment]
@mbdavid  - I saw the ConnectionString class and I am using this to open the connection but yeah like you mentioned there isn't a way to see what has already been set by a connection. 
Ideally it would be best if the database property was visible in the db instance like so:

![image](https://user-images.githubusercontent.com/7691373/35042458-1406b350-fb89-11e7-8d7c-211f28b16b02.png)

the above is easy to do in powershell but since the cmdlet is being written in c# it would be great if the database property was natively visible in the "$db"(LiteDatabase) instance . if an in-memory database is being used the property can just read "Database" : "Memory"

@DeanVanGreunen  - thank you for the suggestion about openfiles. It feels a little hacky :) to be doing it this way but good to know about the tool

**Comment by mbdavid** [comment]
@v2kiran, as SQLite do, I'm implementing 2 new "types" of datafiles: ":memory:" to use only MemoryStream and ":temp:", an special implement of Stream that, can be use memory only or temp disk (accoding file size). But this will be available only in next major version.

**Comment by v2kiran** [comment]
@mbdavid  - thx...look forward to the new version...between heads up...you will see more posts from me as i make this powershell module :)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
