### ISSUE TITLE
Does LiteDB support circular references?

### ISSUE THREAD

**Issue by darkskygit** [mbdavid/LiteDB#871]
for example:

```
    [BsonField("UserInfo")]
    public class Table_UserInfo
    {
        [BsonId(true)] public uint ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }

        // borrowed book list
        [BsonRef("BorrowInfo")] public List<Table_BorrowInfo> BorrowInfoList { get; set; }
        // borrow info create by user
        [BsonRef("BorrowInfo")] public List<Table_BorrowInfo> CreatedList_BorrowInfo { get; set; }
    }

    [BsonField("BorrowInfo")]
    public class Table_BorrowInfo
    {
        [BsonId(true)] public uint ID { get; set; }
        public DateTime Borrow { get; set; }
        public DateTime Return { get; set; }

        // who borrowed the book
        [BsonRef("UserInfo")] public Table_UserInfo User { get; set; }
        // who create the info
        [BsonRef("UserInfo")] public Table_UserInfo CreatorUser { get; set; }
    }
```

**Comment by mbdavid** [comment]
Hi @darkskygit, there is no circular reference in LiteDB. But, references in document store database are not some as normal table join (and mapped in both classes, like EF). DbRef are real persist fields. In your example, I don't see `BorrowInfo` be a separate collection from UserInfo. There is no `BorrowInfo` without `UserInfo`. You can just represent `BorrowInfo` as a list of subdocuments - and removing `User` attribute and keeping only `CreatorUser` as DbRef (in this case make sense you keep as reference).

When mapper convert your class into document, you will get some like this:

```
{
    _id: 1
    UserName: "John",
    Password: "123",
    BorrowInfoList: [
        { Borrow: "2018-01-01", Return: "2018-01-02", CreatorUser: { $id: 3, $ref: "Table_UserInfo" } }
    ]
}
```

Also, `[BsonField]` attribute are not valid to class, only for properties.

**Comment by darkskygit** [comment]
Thanks for your suggestions and reminders, I realized some differences between LiteDB and regular databases :+1: 
I think I need to refactor my database table :)
