### ISSUE TITLE
Broken examples on LiteDb homepage

### ISSUE THREAD

**Issue by jmoral4** [mbdavid/LiteDB#872]
Seems to be a problem with the sample code on the homepage. For instance, the crossRef example code does not compile in a stock .Net 4.6 environment. I converted the "new List()" calls to "List<Product>" but ran into further problems. 
The line "customers.Insert(john);" breaks with "cannot convert from Customer to LiteDB.BsonDocument.  The same occurs on the lines inserting products and orders. 

Am I missing a ref or something? Should I ignore the homepage and go straight to the docs? 

Thanks, otherwise looks like a great product that I'm eager to jump into using!

**Comment by mbdavid** [comment]
Hi @jmoral4, thanks! This crossRef example I update recently to fix some syntax error, but now must work. This particular example are in my Unit Tests:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB.Tests/Engine/Site_Examples_Tests.cs

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
