### ISSUE TITLE
asp.net core dependency injection support

### ISSUE THREAD

**Issue by OneCyrus** [mbdavid/LiteDB#873]
we use litedb in a asp.net core backend webservice. it works quite well so far. but as the application grows we would like to use some central services which are already used with dependency injection throughout the application. it looks like there's no way to use DI with our litedb documents. did i miss something or is there a way to use it with the current version? if not, would it be possible to have this feature in the future?

**Comment by mbdavid** [comment]
Hi @OneCyrus, thanks for using LiteDB :) It's nice to know! There is no interfaces for dependency injection because, as I understand, has no sense implement, inside LiteDB assembly, all interfaces to access same data. Take a look on this PR conversation. 

https://github.com/mbdavid/LiteDB/pull/800

**Comment by OneCyrus** [comment]
i'm not sure we are talking about the same. i've a simplified example:

```
public class ImacModel
{
        DbPlatformImacs = db.GetCollection<ImacPlatform>("ImacPlatform");
        public ImacModel()
        {
            var db = new LiteDatabase(@".\App_Data\ImacData_New.db");
            DbPlatformImacs = db.GetCollection<ImacPlatform>("ImacPlatform");
        }
}

public class ImacPlatform
{
        private readonly ILogger _logger;
        public ImacModel(ILogger logger) // dependency injection in this litedb document
        {
             this._logger = logger;
        }
}
```

what we would like to do is having DI working in a document. In this example the ILogger.

**Comment by mbdavid** [comment]
Oh, `BsonMapper` supports simple IoC in ctor.

```C#
// keep this mapper instance as static variable to cache class mapper
var mapper = new BsonMapper(type => container.GetInstance(type));

using(var db = new LiteDatabase("filename.db", mapper))
{
...
}
```
This type instantiator is `Func<Type, object>` . Default implementation is `Reflection.CreateInstance` that you can see here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/Reflection/Reflection.cs#L32

`var createInstance = Expression.Lambda<CreateObject>(Expression.New(type)).Compile();`

There are an old discussion and creator of this initializer parameter:

https://github.com/mbdavid/LiteDB/issues/325#issuecomment-256195913

**Comment by OneCyrus** [comment]
thanks, that did it!
