### ISSUE TITLE
Field name

### ISSUE THREAD

**Issue by pazicb** [mbdavid/LiteDB#874]
Hello,
I have this problem. I create this object:

```C#
public class Course
{
   public int _id { get; set; }
   public string courseId { get; set; }
}

using (var db = new LiteDatabase(@"test.db"))
{
    var col = db.GetCollection<Course>("course");
    var course = new Course
    { 
        courseId = "Test", 
    };
    col.Insert(course);
}
```

If the class name is included in the field name, the field is not saved. For example, courseId not saved and only _id is saved.

**Comment by mbdavid** [comment]
Try use `Id` property insted `_id` property. When your class convert to `BsonDocument` you `Id` property will be `_id` field.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
