### ISSUE TITLE
Best way to Query a string in an array

### ISSUE THREAD

**Issue by v2kiran** [mbdavid/LiteDB#876]
is the following the best way to query a string contained in an array of strings?

Query.And(Query.Contains("Tags","tagvalue1"),Query.Contains("Tags","tagvalue2"))

or

Query.And(Query.In("Tags","tagvalue1"),Query.In("Tags","tagvalue2"))

Is there a way to construct a query dynamically for say tag values of 3 or more?

**Comment by mbdavid** [comment]
Hi @v2kiran, 

If you use index you can use EQ operator.

```C#
engine.EnsureIndex("idx_tags", "$.Tags[*]")

var list = new List<Query>();

list.Add(Query.EQ("idx_tags", "tag1"));
list.Add(Query.EQ("idx_tags", "tag2"));
list.Add(Query.EQ("idx_tags", "tag3"));

var query = Query.AND(list.ToArray()); // or Query.OR

```

**Comment by v2kiran** [comment]
Hi Mauricio,
exactly what I needed thx 👍 
yup I am using the index just like how you suggested above but didn't know I could use "EQ".

**Comment by mbdavid** [comment]
Yes, `Equals` are not too clear to understand when used with array because confuse with `Contains` in .NET array. Index in array are just a multiple index keys for same document.

So, you can use any kind of operation, like `EQ`, `StartsWith`, `Contains` (as substring), `>` `<`, ...

**Comment by v2kiran** [comment]
**Index in array are just a multiple index keys for same document.** - this makes things pretty clear :)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
