### ISSUE TITLE
FileStream and Irrklang

### ISSUE THREAD

**Issue by christopherpross** [mbdavid/LiteDB#877]
Hey,
I use LiteDB for store game content and want now to use the OpenRead methode with irrklang.
Irrklang allows me to impliment a interface and to use it to load files.
Now when I use this and return a liteDBFileString, it throws me an message:
unsupported file format

Some user has this problem with c++ and with a custom fileformat, but he only has a wrong seek method.
When I read out the file with download and play it normaly with irrklang, all is working. It is also working, when I use copyTo to copy it in a MemoryStream, but this is not wat i want to do.
I want to use the Stream from the database directly.
Do you have an idea, how to fix that?

best regards,
Christopher

**Comment by mbdavid** [comment]
Hi @christopherpross,

If it's possible play using `MemoryStream` after read all from database, there is no problem with our data inside database. Now, it's important to know how Irrklang use this `Stream` access, because there are some method not supported in `LiteFileStream`, like `Seek` method.

But, are you are keeping `LiteDatabase` (or `LiteEngine`) instance opened during use of stream?

**Comment by christopherpross** [comment]
@mbdavid:
Thank you for the quick answer.
Yes, well I store the Database in a globals class (static) and it is opened.
I will try to find out, how Irrklang use the stream, maybe I find something. Because I need your Database. :-)
When I find something I will comment it here.

**Comment by christopherpross** [comment]
Ok, irrklang use Seek alot, here the output out of theier own demos:

irrKlang sound library version 1.5.0
Loaded plugin: ikpflac.dll
Loaded plugin: ikpmp3.dll
Using DirectSound8 driver

Demonstrating file access overriding.
Press any key to play some sound, press ESCAPE to quit.
MyFileStream seeked to: 0
MyFileStream read bytes: 2048
MyFileStream read bytes: 2048
MyFileStream read bytes: 2048
MyFileStream read bytes: 2048
MyFileStream read bytes: 2048
MyFileStream seeked to: 464460
MyFileStream seeked to: 398924
MyFileStream read bytes: 2048
...
MyFileStream read bytes: 2048
MyFileStream seeked to: 3888
MyFileStream read bytes: 16
MyFileStream seeked to: 0
MyFileStream seeked to: 12
MyFileStream read bytes: 4
MyFileStream read bytes: 4
MyFileStream seeked to: 16
MyFileStream read bytes: 4
MyFileStream read bytes: 4
MyFileStream seeked to: 4
MyFileStream read bytes: 4
MyFileStream read bytes: 4
MyFileStream read bytes: 64898
MyFileStream read bytes: 2048
MyFileStream read bytes: 2048
...

and so on.
Well, ok... Is there any way to use the LiteDBStream or some efficent way?
Do you have any idea?

**Comment by mbdavid** [comment]
Maybe `BufferedStream`? This class buffer another `Stream` for read/write. By I don't know if this BufferdStream do not use Seek too. 
Another way is implement another Stream layer that mix `MemoryStream` with `LiteFileStream` (read from LiteFileStream in sequence and write into MemoryStream, that support seek).

**Comment by christopherpross** [comment]
@mbdavid:
hm BufferedStream canSeek returns false, but in the documentation, microsoft says, that the BufferedStream supports seek
What do you mean, mix memorystream, how I could support seek? write bytes in the memorystream until the endposition of the seek is reached?
Or what do you mean?

**Comment by mbdavid** [comment]
It's possible that BufferedStream support seek only in internal stream support too.

Ok, forgot mixing MemoryStream.... will be same result, at end, as load all you strem into an MemoryStream.

If you wan avoid load all you will need implement your own Seekable stream.  Something like this (I didn't test this)

```C#

public class SeekStream : Stream
{
    private Func<Stream> _fatory;
    private Stream _stream;
    private long _position;
    private bool _disposed = false;
    
    public SeekStream(Func<Stream> factory)
    {
        _factory = factory;
        _stream = _factory();
        _position = 0
    }
    
    public override long Length => _stream.Length;

    public override bool CanRead => true;

    public override bool CanWrite => false;

    public override bool CanSeek => true

    public override long Position
    {
        get => _position;
        set => this.Seek(value, SeekOrigin.Begin);
    }

    public override long Seek(long offset, SeekOrigin origin)
    {
        // must do some calcs if origin is not Begin
        var pos = origin == 
            SeekOrigin.Begin ? offset : 
            SeekOrigin.Current ? _position + offset : this.Length - offset;
            
        // if need go back, must reset stream
        if (_position > pos)
        {
            _stream.Dispose();
            _stream = _factory();
            _position = 0;
        }
        
        var size = pos - _position;
        
        this.Read(new byte[size], 0, size);
        _position = pos;
    }
    
    public override int Read(byte[] buffer, int offset, int count)
    {
        _stream.Read(buffer, offset, count);
    }    

    public override void SetLength(long value)
    {
        throw new NotSupportedException();
    }

    public override void Flush()
    {
        throw new NotSupportedException();
    }

    public override void Write(byte[] buffer, int offset, int count)
    {
        throw new NotSupportedException();
    }    
    
    ~SeekStream()
    {
        Dispose(false);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!_disposed)
        {
            _stream.Dispose();
            _disposed = true;
        }
    }
}
```

You must initialize with a `Func` to create your Stream.

**Comment by christopherpross** [comment]
@mbdavid:
really nice, I implemented this, now it exist only one issue, I don't know why, but irrklang tries to seek on a position, which is out of the stream length, here is the stream length 27216078 and the offset -436359331.
How I can handle this? set the offset to 0?

**Comment by mbdavid** [comment]
This seek method use which SeekOrigin value? Begin? But, this number are too long... did you try with MemoryStream (as your first example) and, after this long number, see `Position` value?

**Comment by christopherpross** [comment]
@mbdavid:
omg, ok...
I have now written a complite debug seekstream and memorystream.
By the memroystream, the strange offset is not queried by irrklang. 
Output:
`Memorystream, with copyto:
copyto stream started
copyto ended
seek: offset: 0, seekorigin: Begin, current position: 27216078
Read: offset: 0, count: 4, current position: 0
Read: offset: 0, count: 4, current position: 4
Read: offset: 0, count: 4, current position: 8
Read: offset: 0, count: 4, current position: 12
Read: offset: 0, count: 4, current position: 16
Read: offset: 0, count: 16, current position: 20
seek: offset: 0, seekorigin: Current, current position: 36
seek: offset: 12, seekorigin: Begin, current position: 36
Read: offset: 0, count: 4, current position: 12
Read: offset: 0, count: 4, current position: 16
seek: offset: 16, seekorigin: Current, current position: 20
Read: offset: 0, count: 4, current position: 36
Read: offset: 0, count: 4, current position: 40
Read: offset: 0, count: 264600, current position: 44
Read: offset: 0, count: 8136, current position: 264644
Read: offset: 0, count: 15876, current position: 272780
Read: offset: 0, count: 13230, current position: 288656
Read: offset: 0, count: 13230, current position: 301886
Read: offset: 0, count: 13230, current position: 315116
Read: offset: 0, count: 15876, current position: 328346
...

`

After that I set debug messages in the seekStream, in all methods.  Then I saw it, it exist a problem, in the Read-method, there was the problem, that the _position, are not refreshed from the liteFileStream.
Output:
`with SeekStream:
SeekStream new instance
read: offset: 0, count: 4, current position: 0
read: offset: 0, count: 4, current position: 0
read: offset: 0, count: 4, current position: 0
read: offset: 0, count: 4, current position: 0
read: offset: 0, count: 4, current position: 0
read: offset: 0, count: 16, current position: 0
seek: offset: 0, origin: Current, current position: 0
seek: size of readbuffer: 0
read: offset: 0, count: 0, current position: 0
seek: offset: 12, origin: Begin, current position: 0
seek: size of readbuffer: 12
read: offset: 0, count: 12, current position: 0
read: offset: 0, count: 4, current position: 12
read: offset: 0, count: 4, current position: 12
seek: offset: 5394434, origin: Current, current position: 12
seek: size of readbuffer: 5394434
read: offset: 0, count: 5394434, current position: 12
read: offset: 0, count: 4, current position: 5394446
read: offset: 0, count: 4, current position: 5394446
seek: offset: -436359331, origin: Current, current position: 5394446
seek: size of readbuffer: -430964885

exception: "System.OverflowException" in Edalaria I.exe
`

Write 2 lines of code, now it is working perfectly with the SeekStream.
output:
`SeekStream new instance
read: offset: 0, count: 4, current position: 0
read: offset: 0, count: 4, current position: 4
read: offset: 0, count: 4, current position: 8
read: offset: 0, count: 4, current position: 12
read: offset: 0, count: 4, current position: 16
read: offset: 0, count: 16, current position: 20
seek: offset: 0, origin: Current, current position: 36
seek: size of readbuffer: 0
read: offset: 0, count: 0, current position: 36
seek: afterread current position: 36
seek: offset: 12, origin: Begin, current position: 36
seek: size of readbuffer: 12
read: offset: 0, count: 12, current position: 0
seek: afterread current position: 12
read: offset: 0, count: 4, current position: 12
read: offset: 0, count: 4, current position: 16
seek: offset: 16, origin: Current, current position: 20
seek: size of readbuffer: 16
read: offset: 0, count: 16, current position: 20
seek: afterread current position: 36
read: offset: 0, count: 4, current position: 36
read: offset: 0, count: 4, current position: 40
...
`

I will post the SeekStream in the next comment. When someone have the same problem, well only look for the code in the next comment.
Thank you David for the help, keep up the good work.

**Comment by christopherpross** [comment]
Here the final code, it should work. 
Globals is a static class, where I store some global objects. So I hope that will help someone.
In first ile:
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LiteDB;
using IrrKlang;
using System.Diagnostics;

public class SeekStream : Stream
{
    private Func<Stream> _factory;
    private Stream _stream;
    private long _position;
    private bool _disposed = false;

    public SeekStream(Func<Stream> factory)
    {
        _factory = factory;
        _stream = _factory();
        _position = 0;
    }

    public override long Length => _stream.Length;
    public override bool CanRead => true;
    public override bool CanWrite => false;
    public override bool CanSeek => true;
    public override long Position
    {
        get => _position;
        set => this.Seek(value, SeekOrigin.Begin);
    }

    public override long Seek(long offset, SeekOrigin origin)
    {
        // must do some calcs if origin is not Begin
        var pos = origin ==
            SeekOrigin.Begin ? offset :
            origin == SeekOrigin.Current ? _position + offset : this.Length - offset;

        // if need go back, must reset stream
        if (_position > pos)
        {
            _stream.Dispose();
            _stream = _factory();
            _position = 0;
        }

        long size = pos - _position;
        this.Read(new byte[size], 0, (int)size);
        _position = pos;
        return pos;
    }

    public override int Read(byte[] buffer, int offset, int count)
    {
        int result;
        result = _stream.Read(buffer, offset, count);
        _position = _stream.Position;
        return result;
    }

    public override void SetLength(long value)
    {
        throw new NotSupportedException();
    }

    public override void Flush()
    {
        throw new NotSupportedException();
    }

    public override void Write(byte[] buffer, int offset, int count)
    {
        throw new NotSupportedException();
    }

    ~SeekStream()
    {
        Dispose(false);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!_disposed)
        {
            _stream.Dispose();
            _disposed = true;
        }
    }
}

    
class LiteDBFileFactory : IrrKlang.IFileFactory
{
    public LiteDBFileFactory()
    {
        // constructor
    }

    public Stream openFile(String filename)
    {
        SeekStream result = null;
            
        try
        {
            
            if (!Globals.soundContainer.FileStorage.Exists(filename))
            {
                // do something here, throw exception, or loo it ...
            }
            result = new SeekStream(delegate()
                {
                    return Globals.soundContainer.FileStorage.OpenRead(filename);
                }
            );
        }
        catch (Exception e)
        {
            // do something here
        }
            
        return result;
    }
}

In an other file:

try
{
    Globals.soundContainer = new LiteDB.LiteDatabase("sounds.dat");
} catch(Exception e)
{
    // do something here
}   
try
{
    Globals.soundEngine = new ISoundEngine();
    Globals.soundEngine.AddFileFactory(new LiteDBFileFactory());
} catch (Exception e)
{
    // do something here
}

**Comment by mbdavid** [comment]
oh yes, I forgot update `_position` on read.... I didn't test my code (I made too early in the morning :)

Nice code!

**Comment by christopherpross** [comment]
@mbdavid:
Nice Library! :-)
no problem, now its working.
Damn timeshift, for me it is lunch time now. :-)

So, I will close this issue now and thank you.
