### ISSUE TITLE
How To Query a string in an array  use  Respository 

### ISSUE THREAD

**Issue by wai2dance** [mbdavid/LiteDB#878]
How To Query a string in an array  use  Respository ?

Show My Code.

` public interface IRepository  <T> where T : class
    {
        /// <summary>
        /// IRespository保存接口
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        bool Insert(T entity);

        /// <summary>
        /// IRespository修改接口
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        bool Update(T entity);

        /// <summary>
        /// IRespository删除
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        bool Delete( Expression<Func<T, bool>> where);

        bool DeleteAllEntity();

        /// <summary>
        /// 根据主键id查询
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        T GetOneByIndexKey(Expression<Func<T, bool>> where);

        /// <summary>
        /// 带条件查询
        /// </summary>
        /// <param name="where"></param>
        /// <returns></returns>
        T GetOneByWhere(Expression<Func<T, bool>> where);

        /// <summary>
        /// 查询所有
        /// </summary>
        /// <returns></returns>
        List<T> GetALLEntity();

        /// <summary>
        /// 这里也可以用IEnumerable类型，带条件查询所有
        /// </summary>
        /// <param name="where"></param>
        /// <returns></returns>
        List<T> GetAllEntityWhere(Expression<Func<T, bool>> where);

        /// <summary>
        /// 分页
        /// </summary>
        /// <param name="pageIndex"></param>
        /// <param name="PageSize"></param>
        /// <returns></returns>
        List<T> GetPageEntities( int pageIndex, int PageSize);

        /// <summary>
        /// 分页带查询条件
        /// </summary>
        /// <param name="pageIndex"></param>
        /// <param name="PageSize"></param>
        /// <param name="where"></param>
        /// <returns></returns>
        List<T> GetPageEntities( int pageIndex, int PageSize, Expression<Func<T, bool>> wheresearch);

    }`

-------------------------------

`public class Respository<T> : IRepository<T> where T : class
    {

        public string conStr;
        public Respository()
        {
            conStr = LiteDBHelper.GetConString();
        }

        public bool Insert(T entity)
        {
           try
            {
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    var result = db.Upsert( entity );

                    //if( result.AsString == entity. )
                    return result;
                }

               
            }
            catch(Exception e)
            {
                string mes = e.Message;
                return false;
            }
        }

        public bool Update(T entity)
        {
            try
            {
                
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    bool result = db.Update(entity);

                    return result;

                }

               
            }
            catch
            {
                return false;
            }
        }
        public bool Delete(Expression<Func<T, bool>> where)
        {
            try
            {
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    int result= db.Delete<T>( where );

                    return result > 0 ? true : false;
                }
                
            }
            catch
            {
                return false;
            }
        }

        public bool  DeleteAllEntity()
        {
            try
            {
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    int result = db.Delete<T>(Query.All());

                    return result > 0 ? true : false;
                }

            }
            catch
            {
                return false;
            }
        }

        public List<T> GetALLEntity()
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    var result = db.Query<T>().ToList();
                    return result;

                }

                //return result > 0 ? true : false;
            }
            catch
            {
                return null;
            }
        }

        public List<T> GetAllEntityWhere(Expression<Func<T, bool>> where)
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    var result = db.Query<T>(  ).Where(where)  .ToList();
                    return result;

                }

                //return result > 0 ? true : false;
            }
            catch
            {
                return null;
            }
        }

        public T GetOneByIndexKey(Expression<Func<T, bool>> where)
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    var result = db.Query<T>().Where(where).Single();
                    return result;

                }

                //return result > 0 ? true : false;
            }
            catch
            {
                return null;
            }
        }

        public T GetOneByWhere(Expression<Func<T, bool>> where)
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                    var result = db.Query<T>().Where(where).Single();
                    return result;

                }

                //return result > 0 ? true : false;
            }
            catch
            {
                return null;
            }
        }

        public List<T> GetPageEntities(int pageIndex, int PageSize)
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {

                    int totalCount = db.Query<T>().Count();
                    //计算页码
                    int pages = (int)Math.Ceiling((double)totalCount / (double)PageSize);

                    if (pageIndex > pages)
                        return null;
                    else
                    {
                        //Reverse 倒序排列
                        // var result = db.Query<T>().ToList().Skip(  (pageIndex -1)*PageSize    ).Take(PageSize).Reverse().ToList() ;

                        // var result = db.Query<T>().Skip((pageIndex - 1) * PageSize).ToList().Take(PageSize).Reverse().ToList();
                        var result = db.Query<T>().Skip((pageIndex - 1) * PageSize).ToList().Take(PageSize).ToList();

                        return result;
                    }
                    

                }
                
            }
            catch
            {
                return null;
            }
        }

        //by serach
        public List<T> GetPageEntities( int pageIndex, int PageSize, Expression<Func<T, bool>> wheresearch)
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {

                    int totalCount = db.Query<T>().Count();
                    //计算页码
                    int pages = (int)Math.Ceiling((double)totalCount / (double)PageSize);

                    if (pageIndex > pages)
                        return null;
                    else
                    {
                        //Reverse 倒序排列
                        //var result = db.Query<T>().Where(wheresearch).ToList().Skip((pageIndex - 1) * PageSize).Take(PageSize).Reverse().ToList();

                        var result = db.Query<T>().Where(wheresearch).Skip((pageIndex - 1) * PageSize).ToList().Take(PageSize).ToList();

                        return result;
                    }

                }

            }
            catch
            {
                return null;
            }
        }

       
    }`

-----------------------------------------------------------

` public class BaseDAL<T> : Respository<T> where T : class
    {
      
        

    }`

---------------------------------------------------------

`
 public class  OldFuPinPersonDAL :BaseDAL< OldFuPinPerson>
{

          public new bool Insert(OldFuPinPerson m)
        {

            List<OldFuPinPerson> allItem = base.GetALLEntity().ToList();
            try
            {
                using (var db = new LiteRepository(conStr))
                {
                    //村庄索引
                    db.Engine.EnsureIndex("OldFuPinPerson", "CUNId");
                    //户口编号索引
                    db.Engine.EnsureIndex("OldFuPinPerson", "HuId");
                    //人口编号索引
                    db.Engine.EnsureIndex("OldFuPinPerson", "RenId");
                    //姓名编号索引
                    db.Engine.EnsureIndex("OldFuPinPerson", "PName");
                    //身份证编号索引
                    db.Engine.EnsureIndex("OldFuPinPerson", "ShenFenID");
                    //人口对应直接关系索引
                    db.Engine.EnsureIndex("OldFuPinPerson", "Relationship");
                    //脱贫属性索引
                    db.Engine.EnsureIndex("OldFuPinPerson", "TuoPinState");
                    
                    var result = db.Upsert(m);

                    //if( result.AsString == entity. )
                    return result;
                }

            }
            catch (Exception e)
            {
                string mes = e.Message;
                return false;
            }

            
        }

        public int GetAllDataCount()
        {
            try
            {
                //int result;
                using (var db = new LiteRepository(conStr))
                {
                    // simple access to Insert/Update/Upsert/Delete
                   
                    return db.Query<OldFuPinPerson>().Count();

                }

                //return result > 0 ? true : false;
            }
            catch
            {
                return 0;
            }
        }
        

}
`
------------------------------------------------------------------------

` public class  OldFuPinPersonService  
    {
           
         public  OldFuPinPersonDAL modelDAL;

         public OldFuPinPersonService(){
               modelDAL = new OldFuPinPersonDAL();

          }

        

	
        public bool Insert(OldFuPinPerson model)
		{
		      return  modelDAL.Insert(model);
		}

        public bool DeleteByWhere(Expression<Func<   OldFuPinPerson, bool>> whereCondition)
		{
		       return modelDAL.Delete(whereCondition);         
 
		}

        public int GetAllDataCount()
        {
            return modelDAL.GetAllDataCount();
        }

            public bool Update(OldFuPinPerson model){
		     return modelDAL.Update(model);

		}

        public List< OldFuPinPerson> GetAll(){
		  return modelDAL.GetALLEntity();
		}

        public List<OldFuPinPerson> GetOldFuPinPersonBySize_Page(int pageItemSize, int excludedRows)
		{
		   
           return  modelDAL.GetPageEntities(excludedRows, pageItemSize);   
		}

        
        public  OldFuPinPerson GetOneByWhere(Expression<Func< OldFuPinPerson, bool>> whereCondition)
		{
		     
             return  modelDAL.GetOneByWhere(whereCondition);
		 }

        public List<OldFuPinPerson> GetAllByWhere(Expression<Func<   OldFuPinPerson, bool>> whereCondition){
		     
                  return  modelDAL.GetAllEntityWhere(whereCondition);
		}

        public List<OldFuPinPerson> GetAllByWhereBySize_Page(Expression<Func<    OldFuPinPerson, bool>> whereCondition,int pageItemSize, int excludedRows)

		{
		       return modelDAL.GetPageEntities(excludedRows, pageItemSize, whereCondition );
		}

    }`

------------------------------------------------------------------

------------------------------------------------------------------

The problem -----------The problem-----The problem

-------------------------------------------------------------------

`  public class  OldFuPinPersonController : Controller
    {
           
         public  OldFuPinPersonService      OldFuPinPersonservice;

         public OldFuPinPersonController(){
               OldFuPinPersonservice = new OldFuPinPersonService();

         }

       

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAll(int limit, int offset, string searchName, string searchShenFenZheng,string searchCun,string searchTuoPinShuXing )
        {
            //offset默认，，10的增长,,,20 ,,30,,
            //需要转换为页面数量
            //计算页码
           
           // if (pageIndex > pages)

                //总页码

            List<OldFuPinPerson> lstRes = new List<OldFuPinPerson>();
            int total ;

            if (searchName == "" && searchShenFenZheng=="无" 
                && searchCun!= "全部" && searchTuoPinShuXing != "全部" 
                )
            {
               
               SearchHelperModel<OldFuPinPerson> res =  SearchOlePinKunPerson(limit, offset, searchName, searchShenFenZheng, searchCun, searchTuoPinShuXing);

                total = res.TotalCount ;
                lstRes = res.allResult;
            }
            else if (searchName == "无" && searchShenFenZheng == ""
              && searchCun != "全部" && searchTuoPinShuXing != "全部"
              )
            {

                SearchHelperModel<OldFuPinPerson> res = SearchOlePinKunPerson(limit, offset, searchName, searchShenFenZheng, searchCun, searchTuoPinShuXing);

                total = res.TotalCount;
                
                lstRes = res.allResult;
            }
            else if (searchName == "无" && searchShenFenZheng != ""
             )
            {

                SearchHelperModel<OldFuPinPerson> res = SearchOlePinKunPerson(limit, offset, searchName, searchShenFenZheng, searchCun, searchTuoPinShuXing);

                total = res.TotalCount;

                lstRes = res.allResult;
            }

            else if (searchShenFenZheng == "无" && searchName != ""
             )
            {

                SearchHelperModel<OldFuPinPerson> res = SearchOlePinKunPerson(limit, offset, searchName, searchShenFenZheng, searchCun, searchTuoPinShuXing);

                total = res.TotalCount;

                lstRes = res.allResult;
            }

            else
            {
                int pageIndexKey = (int)Math.Ceiling((double)(offset + limit) / (double)limit);

                lstRes = OldFuPinPersonservice.GetOldFuPinPersonBySize_Page(limit, pageIndexKey);
                total = OldFuPinPersonservice.GetAllDataCount();

            }

            var rows = lstRes; //lstRes.Skip(offset).Take(limit).ToList();
            return Json(new { total = total, rows = rows }, JsonRequestBehavior.AllowGet);

        }

		[Authorize]
        [HttpPost]
        public JsonResult Edit(OldFuPinPerson model)
        {
           
           
            bool result =  OldFuPinPersonservice.Update(model);
            string Message = result == true ? "OK" : "Wrong";
            return Json(new { Message }, JsonRequestBehavior.AllowGet);
        }
        [Authorize]
        [HttpPost]
        public JsonResult Insert(OldFuPinPerson model)
        {
            
            //model.CID = Guid.NewGuid().ToString("N");
           
            bool result = OldFuPinPersonservice.Insert(model);
            string Message = result == true ? "OK" : "Wrong";
            return Json(new { Message }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        public JsonResult Delete(OldFuPinPerson model)
        {
            
            //model.ID = Guid.NewGuid().ToString("N");
           
            bool result = OldFuPinPersonservice.DeleteByWhere(m=>m.CID == model.CID);
            string Message = result == true ? "OK" : "Wrong";
            return Json(new { Message }, JsonRequestBehavior.AllowGet);
        }

        private SearchHelperModel<OldFuPinPerson> SearchOlePinKunPerson(int limit, int offset, string searchName, string searchShenFenZheng, string searchCun, string searchTuoPinShuXing)
        {

            SearchHelperModel<OldFuPinPerson> result = new SearchHelperModel<OldFuPinPerson>();
            result.allResult = new List<OldFuPinPerson>();

            //姓名为空，，身份证号为无， 两个全部  ，，那么查询全部
            //int i = 0;
            //A  姓名 ，
            //1,姓名为两个分号，身份证号码为无，  默认全部
            //2,姓名不为空  
            searchName = searchName == "无" ?  "" : searchName;

            searchShenFenZheng  = searchShenFenZheng == "无" ?  "" : searchShenFenZheng;

            searchCun = searchCun == "全部" ?  "" : searchCun;

            searchTuoPinShuXing = searchTuoPinShuXing == "全部" ?  "" : searchTuoPinShuXing;

           

            //int Totalpages = (int)Math.Ceiling((double)total / (double)limit);
            //传递的是 从20开始，，往后取10条数据
            //   offset                 limit
            int pageIndexKey = (int)Math.Ceiling((double)(offset + limit) / (double)limit);

            Expression<Func<OldFuPinPerson, bool>> serachExp = GetExpressionByStage(searchName, searchShenFenZheng, searchCun, searchTuoPinShuXing);

          
            result.allResult = OldFuPinPersonservice.GetAllByWhereBySize_Page(serachExp

                                                      , limit, pageIndexKey);

            if (result.allResult != null)
            {
                

                result.TotalCount = OldFuPinPersonservice.GetAllByWhere(serachExp).Count;
                //如果只查到了一个人。。。判定是不是户主，，不是，，还要显示出户主来......

                if(result.TotalCount>=1 && result.TotalCount <= 5)
                {
                    List<OldFuPinPerson> allHuPerson = new List<OldFuPinPerson>();
                    //继续查找 出户主和家庭成员
                    foreach( OldFuPinPerson  phu  in  result.allResult)
                    {
                        allHuPerson.AddRange( OldFuPinPersonservice.GetAllByWhere(p => p.HuId == phu.HuId));

                    }
                    //删除相同的数据
                    RemoveSomeItem(allHuPerson);

                    result.allResult = null;
                    result.allResult = allHuPerson;
                    result.TotalCount = allHuPerson.Count;

                }

            }

            return result;

        }

        private Expression<Func<OldFuPinPerson, bool>> GetExpressionByStage(string searchName, string searchShenFenZheng, string searchCun, string searchTuoPinShuXing)
        {

            if (searchCun == "" && searchTuoPinShuXing == "" && searchShenFenZheng== "")
            {
                //说明是 只查姓名，，其余都是全部的
                Expression<Func<OldFuPinPerson, bool>> whereCondition = (p => p.PName.Contains(searchName)  );

                return whereCondition;
            }
            else if (searchCun != "" && searchTuoPinShuXing == "" && searchShenFenZheng == "")
            {
                //查姓名，，单独带，村的属性
                Expression<Func<OldFuPinPerson, bool>> whereCondition = (
                    p => p.PName.Contains(searchName)
                    && p.CUNId.Contains(searchCun)
                );

                return whereCondition;
            }
            else if (searchCun == "" && searchTuoPinShuXing != "" && searchShenFenZheng == "")
            {
                //查姓名，，单独带，脱贫状态的属性
                Expression<Func<OldFuPinPerson, bool>> whereCondition = (
                    p => p.PName.Contains(searchName)
                    && p.TuoPinState.Contains(searchTuoPinShuXing)
                );

                return whereCondition;
            }
            else if (searchCun == "" && searchTuoPinShuXing != "" && searchShenFenZheng == "")
            {
                //查姓名，，带，村和脱贫状态的属性
                Expression<Func<OldFuPinPerson, bool>> whereCondition = (
                    p => p.PName.Contains(searchName)
                      && p.CUNId.Contains(searchCun)
                    && p.TuoPinState.Contains(searchTuoPinShuXing)
                );

                return whereCondition;
            }

            else if(searchCun == "" && searchTuoPinShuXing == "" && searchName == "")
            {
                //只查身份证，，其余都是全部
                Expression<Func<OldFuPinPerson, bool>> whereCondition = (p => p.ShenFenID.Contains(searchShenFenZheng));

                return whereCondition;
            }
            else if (searchCun != "" && searchTuoPinShuXing == "" && searchName == "")
            {
                //查身份证，，单独带，村的属性
                Expression<Func<OldFuPinPerson, bool>> whereCondition = (
                    p => p.ShenFenID.Contains(searchShenFenZheng)
                    && p.CUNId.Contains(searchCun)
                );

                return whereCondition;
            }
            else if (searchCun == "" && searchTuoPinShuXing != "" && searchName == "")
            {
                //查身份证，，单独带，脱贫状态的属性
                Expression<Func<OldFuPinPerson, bool>> whereCondition = (
                    p => p.ShenFenID.Contains(searchShenFenZheng)
                    && p.TuoPinState.Contains(searchTuoPinShuXing)
                );

                return whereCondition;
            }
            else if (searchCun != "" && searchTuoPinShuXing != "" && searchName == "")
            {
                //查身份证，，带，村类别，脱贫状态的属性
                Expression<Func<OldFuPinPerson, bool>> whereCondition = (
                    p => p.ShenFenID.Contains(searchShenFenZheng)
                    && p.TuoPinState.Contains(searchTuoPinShuXing)
                     && p.CUNId.Contains(searchCun)
                );

                return whereCondition;
            }
            else if (searchCun != "" && searchTuoPinShuXing == "" && searchName == "" && searchShenFenZheng == "")
            {
                //身份证和姓名都为空，，，，，只查某个村类别，
                Expression<Func<OldFuPinPerson, bool>> whereCondition = (
                    p =>  p.CUNId.Contains(searchCun)
                );

                return whereCondition;
            }

            else if (searchCun == "" && searchTuoPinShuXing != "" && searchName == "" && searchShenFenZheng == "")
            {
                //身份证和姓名都为空，，，，，只查某个脱贫属性类别，
                Expression<Func<OldFuPinPerson, bool>> whereCondition = (
                    p => p.TuoPinState.Contains(searchTuoPinShuXing)
                );

                return whereCondition;
            }
            else  //if (searchCun != "" && searchTuoPinShuXing != "" && searchName == "" && searchShenFenZheng == "")
            {
                //身份证和姓名都为空，，，，，查某个村和某个脱贫属性类别，
                Expression<Func<OldFuPinPerson, bool>> whereCondition = (
                    p => p.TuoPinState.Contains(searchTuoPinShuXing)
                    &&  p.CUNId.Contains(searchCun)
                );

                return whereCondition;
            }

        }

        private void RemoveSomeItem(List<OldFuPinPerson> list)
        {
            for (int i = 0; i < list.Count; i++)  //外循环是循环的次数
            {
                for (int j = list.Count - 1; j > i; j--)  //内循环是 外循环一次比较的次数
                {

                    if (list[i] == list[j])
                    {
                        list.RemoveAt(j);
                    }

                }
            }
            //根据cid数字ID重新排序,,从小到大
            list.OrderBy(p => p.CID);

        }

    }`

--------------------------------------------------------------------------

**Comment by wai2dance** [comment]
There is 4 search field.
【string searchName, string searchShenFenZheng,string searchCun,string searchTuoPinShuXing 】
May cross search. (Web Use   Post  data)

Some time will  searchOne field.
I make a function 【 private Expression<Func<OldFuPinPerson, bool>> GetExpressionByStage 】

I feel very bad feeling. Can you give me some advice.

My Web HTML like this .
http://ogiw0i9ef.bkt.clouddn.com/ssss3.png

**Comment by mbdavid** [comment]
Hi @wai2dance, if I understand what you need, you want convert your query into and LINQ Expression. Try read this and use this Dynamic lib

https://weblogs.asp.net/scottgu/dynamic-linq-part-1-using-the-linq-dynamic-query-library

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
