### ISSUE TITLE
Feature request - simple data visualizer as VS extension or standalone

### ISSUE THREAD

**Issue by a-a-k** [mbdavid/LiteDB#881]
Excuse me if same issue already exists but I don't find. 
So this is necessary feature, definitely. Sometimes I need to check some values in my data (especially while debugging) but I should to write some stuff for that everytime. Very uncomfortable, you know :)

**Comment by mbdavid** [comment]
Hi, there are some LiteDB data viewer, like here: https://github.com/falahati/LiteDBViewer or https://github.com/JosefNemec/LiteDbExplorer or shell tool.

But I know that is not same as VS extensions (very practical) or SQL Managment Tool (very powerful).

**Comment by mbdavid** [comment]
BTW, is in my plans to next v5 version a Web admin UI for server version.

**Comment by a-a-k** [comment]
Many thanks, @mbdavid. Will try both.

> in my plans to next v5 version a Web admin UI for server version

Huh! Waiting for it! But what does it mean - "server version"?

**Comment by mbdavid** [comment]
Next version will support embedded and server version (LiteDB.Server.exe). This server will be used for multi concurrency processes with REST-API support and non .NET language (to be used as a normal server database).

**Comment by a-a-k** [comment]
Wow, sounds great! :) Will server version be commercial?

**Comment by mbdavid** [comment]
No.... all free, all open source... 

But I think to provide some hosted database in azure/aws to be access via REST/API direct in client application (like javascript). This service may be paid, because azure/aws are payed services.

**Comment by dengxufan** [comment]
Sounds amazing, when will be the next version published? :-)

**Comment by mbdavid** [comment]
Hi @dengxufan, not so soon. v5 is a big new version and I need implement and test lot of code. My idea is launch on end of 2018

**Comment by a-a-k** [comment]
Hi David!
Sorry if I missed it but is it released?

**Comment by JensSchadron** [comment]
The upcoming release v5 has a standalone Windows application called LiteDB.Studio which is the successor of the Lite.Shell.
Next version will be released shortly.
