### ISSUE TITLE
BsonDocumentCollection

### ISSUE THREAD

**Issue by pazicb** [mbdavid/LiteDB#889]
Hello,
how to convert BsonDocumentCollection to LiteDB.LiteCollection<class>

Thank you.

**Comment by mbdavid** [comment]
Hi @pazicb, can you write your code? I dont understand your problem

**Comment by pazicb** [comment]
Hello,
I use LINQPad 5 and driver litedbpad, which returns BsonDocumentCollection, I have a class and I would like to convert BsonDocumentCollection to LiteDB.LiteCollection.
So I would not have to write AllCustomers.OrderBy (x => x["name"]) but AllCustomers.OrderBy (x => x.name).

**Comment by pazicb** [comment]
Hello,
I would simply need a function
LiteCollection=Function<class>(BsonDocumentCollection)

**Comment by mbdavid** [comment]
Sorry @pazicb, I never used LINQPad. I think (based only in your example) that LINQPad driver uses only BsonDocument (an generic way to represent an document) and not final POCO class (that your program use). LiteDB convert POCO classes into BsonDocument using BsonMapper class, but I don't know if LINQPad driver use this mapper.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
