### ISSUE TITLE
Upgrade from 1.0 to 2.0

### ISSUE THREAD

**Issue by ambyte** [mbdavid/LiteDB#89]
When I start my App with the new version LiteDb (2.0.0) I get the error "Invalid pageType", data file was created by LiteDb 1.0.4

What should I do?

thank you

**Comment by mbdavid** [comment]
Hi @ambyte! At this point has no migration tool avaialble. It´s on plans that shell tool convert old versions (v.9.x and v.1.x) to 2.0. This tool will be avaiable at RC version (it´s my first item on todo list)

**Comment by ambyte** [comment]
Ok, thank`s

When approximately will the RC version?

**Comment by mbdavid** [comment]
For RC release is 31-dec. But this migration will be came before, maybe in a week.

**Comment by mbdavid** [comment]
For upgrade database version:

Open LiteDB.Shell.exe (from `master` branch):
```
open my_old_datafile.db  -- will open in version v1.0.4/v0.9.0
dump > my_dump_file.dmp`

open my_new_datafile.db  -- will create a new datafile in v.2.0.0
dump < my_dump_file.dmp
```

**Comment by ambyte** [comment]
Hi,
After upgrade DB file, non ANSI the characters became unreadable, like this CfCeD1CcCeD2D0C8Cc CaC0Ca CbD3D7D8C5

**Comment by mbdavid** [comment]
Hi ambyte, there are a bug on JSON string decode. I fix it in current `master` branch.

About upgrade as part of api it's a little bit complicated. Was needed add old versions of LiteDB inside shell assembly. Maybe as shell command line, like `LiteDB.Shell c:\path\to\old_version.db --upgrade`?

**Comment by ambyte** [comment]
Hi,

Yes, it`s would be great

**Comment by mbdavid** [comment]
Hi @ambyte, shell update. Now shell support command lines like:

        /// <summary>
        /// Opens console shell app. Usage:
        /// LiteDB.Shell [myfile.db] --param1 value1 --params2 "value 2"
        /// Parameters:
        /// --exec "command"   : Execute an shell command (can be multiples --exec)
        /// --run script.txt   : Run script commands file 
        /// --pretty           : Show JSON in multiline + idented
        /// --upgrade newdb.db : Upgrade database to lastest version
        /// --exit             : Exit after last command
        /// </summary>
        LiteDB.Shell.exe myold.db --upgrade newdb.db --exit
