### ISSUE TITLE
Field name with '$' chars

### ISSUE THREAD

**Issue by jozseffa** [mbdavid/LiteDB#893]
The pull #714 changed the IsValidFieldName method in BsocDocument.cs to allow $ only on the beginning of a field name. I'm using $ chars in some field names not only as the first char. Now I tried to use the latest LiteDB version, but I can't read / write this fields anymore.
Is there a special reason to allow $ chars only at the first position?
As I can see in the docs, JSON would allow nearly any Unicode char.

Is there a workaround?

**Comment by mbdavid** [comment]
Hi @jozseffa, here same question: #828 

But I'm reviewing this... I'm writing a better Expression parser to avoid this problem.... I will update later.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
