### ISSUE TITLE
Id Not auto incrementing as expected

### ISSUE THREAD

**Issue by Brown3246** [mbdavid/LiteDB#894]
I am using the latest version of LiteDb on a .Net project. 
A user can fill in a form and create a person. The class for this is;
```C#
public class Witness
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string First_Name { get; set; }
        public string Surname { get; set; }
        public string DOB { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        public string Postcode { get; set; }
        public DateTime Update { get; set; }
        public string URN { get; set; }
        public string Email { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string MobilePhone { get; set; }
        public string Occupation { get; set; }
        public string PlaceOfBirth { get; set; }
        public string[] Investigations { get; set; }
        public bool IsActive { get; set; }
    }
```

The winform calls a method to create the person as follows;

```C#
public static int CreateWitness(string Title, string FirstName, string SurName,string DOB,string Address,string Postcode, string Email,
            string Mobile, string Home, string Work, string Occupation, string POB, int Age,string[] Investigations)
        {
           
            //try
            //{
                using (var db = new LiteDatabase(WitnessDb))
                {                  
                    var witnesses = db.GetCollection<Classes.Witness>("Witness");
                    var witness = new Classes.Witness
                    {
                        Title = Title,
                        First_Name = FirstName,
                        Surname = SurName,
                        DOB = DOB,
                        Address = Address,
                        Postcode = Postcode,
                        Email = Email,
                        MobilePhone = Mobile,
                        WorkPhone = Work,
                        HomePhone = Home,
                        Occupation = Occupation,
                        Update = DateTime.UtcNow,
                         URN = SurName + DateTime.UtcNow.ToString("ddMMHHmmssfffffff"),
                        // Investigations = new string[]{""}
                        PlaceOfBirth = POB,
                        Age = Age,
                        Investigations = Investigations
                        
                    };

                    witnesses.Insert(witness);
                    return witness.Id;
                   }
```

This initially worked fine I think (wasn't thoroughly tested). However, the user can add and delete people and now it throws an exception for a duplicate Id.

So if I create 3 people (Id's 1,2 & 3) and then delete person 2 (Id 2) and then try to create a new person - it throws an exception for a duplicate Id (duplicate being 3). I would expect it to create Id 4 and so on.

I have deleted my Db and tried again but no joy. I have tried indexing and shrinking the Db also.

Where am i going wrong?

**Comment by mbdavid** [comment]
In `Int32` AutoId your Id property must be 0 to engine get new sequence number. If you insert a fixed Id (any number > 0) this will not used and no auto-id will be generated - in this case you will get an buble in "Sequence" internal variable and this can be causes duplicate id. Try always use auto-id (insert Id = 0) or never use with autoId (>-0).... if you mix, you can get this error

**Comment by Brown3246** [comment]
So - when creating the person to insert - I should specify Id = 0....as below?

`   {
                        Id=0,
                        Title = Title,
                        First_Name = FirstName,
                        Surname = SurName,
                        DOB = DOB,
                        Address = Address,
                        Postcode = Postcode,
                        Email = Email,
                        MobilePhone = Mobile,
                        WorkPhone = Work,
                        HomePhone = Home,
                        Occupation = Occupation,
                        Update = DateTime.UtcNow,
                         URN = SurName + DateTime.UtcNow.ToString("ddMMHHmmssfffffff"),
                        // Investigations = new string[]{""}
                        PlaceOfBirth = POB,
                        Age = Age,
                        Investigations = Investigations
                        
                    };

                    witnesses.Insert(witness);`

**Comment by mbdavid** [comment]
`Int32` default already 0. The question is if you don't set this Id before run Insert method

**Comment by Brown3246** [comment]
Sorry I might be getting confused - I never specify a value for the Id. I don't pass any value for Id to the method. So I do not set a fixed Id at any time and rely entirely on auto increment. This appears to be intermittent as I have not made any code changes, but deleted all entries in my Db and tried again and it is working again?

**Comment by Brown3246** [comment]
Although it is now failing again....

**Comment by mbdavid** [comment]
If you use fixed Id any time can be a problem. Try "drop" (not delete) you collection and this sequence will be reseted.

**Comment by Brown3246** [comment]
I am not using fixed Id's - I want auto Id numbers. But if I create 10 people in a collection (and the auto Id's are 1-10) and then I delete say Id 5, it throws an exception when trying to add a new person to the collection.

**Comment by mbdavid** [comment]
Ok, how are you deleting this Person? Can you paste your code?

**Comment by Brown3246** [comment]
With no value ever passed to Id - 

LiteDB.LiteException
  HResult=0x80131500
  Message=Cannot insert duplicate key in unique index '_id'. The duplicate value is '11'.
  Source=LiteDB
  StackTrace:
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonType autoId)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at DWS_VC.Classes.dB_Work.CreateWitness(String Title, String FirstName, String SurName, String DOB, String Address, String Postcode, String Email, String Mobile, String Home, String Work, String Occupation, String POB, Int32 Age, String[] Investigations) in C:\Users\a_bro012\source\repos\DWS_VC\DWS_VC\Classes\dB_Work.cs:line 181
   at DWS_VC.new_Contact.create_Witness_Btn_Click(Object sender, EventArgs e) in C:\Users\a_bro012\source\repos\DWS_VC\DWS_VC\new_Contact.cs:line 327
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at DWS_VC.Program.Main() in C:\Users\a_bro012\source\repos\DWS_VC\DWS_VC\Program.cs:line 20

**Comment by Brown3246** [comment]
` public static bool DbDeleteWitness(int ID)
        {
            using (var db = new LiteDatabase(WitnessDb))
            {
                bool success;
                // Get customer collection
                var witness = db.GetCollection<Witness>("Witness");
                //var results = witness.Find(x => x.First_Name.StartsWith(search_FName.Text)).ToArray();
                var results = witness.FindById(ID);
                witness.Delete(results.Id);
                success = true;
                return success;
            }
        }

Where the ID is an INT32 value passed by the calling method.`

**Comment by mbdavid** [comment]
Try "drop" (not delete) your collection and try again... because I'm not userstand how your `Sequence` are 11 and you you already have _id=11 on collection

**Comment by Brown3246** [comment]
Can you give an example as I can't find Drop?

**Comment by mbdavid** [comment]
`db.DropCollection("Witness");`

**Comment by Brown3246** [comment]
That deletes the whole collection and all the witnesses inside it - so I loose all the records.
The Witness collection contains all the individual people I have created. i just want to delete one of those people and for auto increment to work. Sorry for being a pain!

**Comment by Brown3246** [comment]
Further info - If I run the app, create and delete people and then recreate it seems fine. Auto increment is working.
Come out of the app and back in, it seems to loose count and that is where the exception is thrown when  creating a new person

**Comment by mbdavid** [comment]
I'm thinking this is an dev database. If you cann't loose your data, open shell too:

``` 
> open youdata.db
> db.Witness.rename Witness_Old
> db.Witness_Old.select $ into Witness id:int
```

This may fix your sequence. After your tests you can drop Witness_Old collection

**Comment by mbdavid** [comment]
(please, do a backup before 😄 )

**Comment by Brown3246** [comment]
You're right - this is a dev database with only a few test entries. But I have deleted the Db and started a new one and the error comes back after a few document creations/deletions

**Comment by mbdavid** [comment]
Ok, i will try create unit test to reproduce your problem...

**Comment by Brown3246** [comment]
When is Id incremented? Is it at the creation of the new witness object (` var witness = new Classes.Witness`) or at the  `witnesses.Insert(witness)` bit?

I ask as this may all be caused by separate exceptions the program throws. So if my app crashes for an unrelated process (say I have failed to pass a proper Int for the Age variable) it will crash before   `witnesses.Insert(witness)`; but after New Witness. So if the LiteDb has already incremented the Id but the document not entered into the collection, it may be the cause of the problem when trying to add the next entry.

I will keep testing to see if this can be replicated.

**Comment by Brown3246** [comment]
Disregard the above - error occurs regardless of separate application exceptions.

**Comment by mbdavid** [comment]
AutoId is created in "Insert" method. In an atomic "transaction", engine get sequence number, increment, and set as _id field (on BsonDocument). After insert into datafile, set this id value into you class instance. No auto_id are setted in `new Witness()` declaration.
About 2 different processes, no problems if you are working with same class structure.

**Comment by mbdavid** [comment]
Hi @Brown3246, I was creating your test and found this one:

**Comment by nrudkovskiy** [comment]
Hi mbdavid, sorry for my English..
I have the same problem. I use long type as primary key and auto id. When I delete several entries, I can not insert a new record after that. The operation ends with a message about the duplication id error. Сollection contains ~ 5000 - 10000 entries. This test https://github.com/mbdavid/LiteDB/blob/master/LiteDB.Tests/Database/AutoId_Tests.cs#L209 work fine.
The problem was solved by replacing long type to ObjectId. 
Now I'm trying to reproduce an error in the debugger.

Thank you.

**Comment by mbdavid** [comment]
Hi @Brown3246, @nrudkovskiy found a bug in `shrink` method about sequence number as #899. I fix this bug in current branch and will be available in this weekend release. Check if is your case too.

**Comment by Brown3246** [comment]
Thanks @mbdavid I'll give it a go tomorrow. Is there a new dll or just I use the upgraded cs? (I referenced the dll from the litedb.org site in my project).

**Comment by mbdavid** [comment]
You can download from master branch and compile (if you have vs2017) - otherwise, I will publish in this holiday a new version on nuget/github release

**Comment by Brown3246** [comment]
Confirmed the fix appears to work. I employ Shrink when the app opens so that would explain why the problem occurs after an application restart. Many thanks for the quick fix - and for LiteDb!
