### ISSUE TITLE
Weird nuget dependencies

### ISSUE THREAD

**Issue by xied75** [mbdavid/LiteDB#898]
This is the current Dependencies for LiteDB v4.1.1:

![image](https://user-images.githubusercontent.com/1682456/36042041-7900cf3e-0dc2-11e8-94a0-78548ef0f5bc.png)

But the only place to use e.g. Thread is here:
![image](https://user-images.githubusercontent.com/1682456/36042074-90f69768-0dc2-11e8-850c-86e8f215a607.png)

Means for netstandard1.3 and netstandard2.0, we don't actually need to use System.Threading.Thread, thus no need of the dependency.

I wonder if this is an error on the conditions here?
![image](https://user-images.githubusercontent.com/1682456/36042135-bf369f06-0dc2-11e8-85d6-6c8ee365e4bf.png)

Best regards,

**Comment by mbdavid** [comment]
Hi @xied75, this dependency was made for some contributor and I didn't check is all packages are needed. Using only this works fine:

```XML
<ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.3' OR '$(TargetFramework)' == 'netstandard2.0'">
  <PackageReference Include="System.Reflection" Version="4.3.0" />
  <PackageReference Include="System.Reflection.TypeExtensions" Version="4.3.0" />
</ItemGroup>
```

I will upgrade csproj reference

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
