### ISSUE TITLE
BUG autoId & Shrink

### ISSUE THREAD

**Issue by nrudkovskiy** [mbdavid/LiteDB#899]
Hi mbdavid, I reproduce bug with auto id and Shrink.
`public class EntityInt
{
    public int Id {get; set;}   
    public string Name {get; set;} 
}
`
;
File.Delete("E:\\Temp\\Test.db");

    var db = new LiteDatabase("E:\\Temp\\Test.db")
    var col = db.GetCollection<EntityInt>("col1");
    for(int i =0; i<50; i++)
        col.Upsert(new EntityInt {Name = i.ToString()});
    
    for(int i =0; i<10; i++)
        col.Delete(i);
    
    db.Shrink();

    for (int i = 0; i < 5; i++)
        col.Upsert(new EntityInt { Name = i.ToString() }); //Cannot insert duplicate key in unique index '_id'. The duplicate value is '42'.
`

**Comment by mbdavid** [comment]
Hi @nrudkovskiy, thanks! Yes, now I got why this occurs in some cases.. but no one tell me about shrink.. I forgot to override Sequence counter when shrink. I'm fixing...

Plans to release new version 4.1.2 in this carnival holiday.

**Comment by mbdavid** [comment]
Fixed. Just update sequence number :) Thanks!

**Comment by mukeshpiplai** [comment]
Hi mbdavid, I am facing same issue in LiteDB Studio (v1.0.2.0). During opening a LiteDB database, it says Cannot Insert duplicate key in unique index '_id'. The duplicate value is '{"guide":961...............
