### ISSUE TITLE
Does Litedb support Inmemory storage?

### ISSUE THREAD

**Issue by FutureTD** [mbdavid/LiteDB#900]
I need a fast Inmemory only db with indexes and was looking at LiteDb. 

Does Litedb support a Inmemory only mode?

**Comment by maikebing** [comment]
LiteDatabase(Stream stream, BsonMapper mapper = null, string password = null, bool disposeStream = false);

**Comment by mbdavid** [comment]
Hi @FutureTD, as @maikebing say, it´s possible use LiteDB with any Stream - so, MemoryStream are supported. Current version also support "Temp" stream: use MemorySteam until 10Mb, if pass this limit, store in temp windows directory... and auto delete when close.

**Comment by Deilan** [comment]
@mbdavid 
> Current version also support "Temp" stream

Could you provide an example for that?

**Comment by mbdavid** [comment]
Hi @Deilan, was my bad - this implementation is for v5. You can use same `TempStream` in v4, but is not available inside v4 version (v4 has another temp disk implementation, but used only for sorting temp area).

https://github.com/mbdavid/LiteDB/blob/v5/LiteDB/Engine/Streams/TempStream.cs

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
