### ISSUE TITLE
[ SUGGESTION ] Add an "IncludeAll" method

### ISSUE THREAD

**Issue by Auhmaan** [mbdavid/LiteDB#901]
I've been fiddleling with the code, and managed to do a basic `IncludeAll` method, like so:

### Include.cs

    public LiteCollection<T> Include( string path )
    {
        //
        // Moved the code to a method, so it could be used by the `IncludeAll`
        //
        return Include( new List<String>() { path } );
    }
    public LiteCollection<T> Include( List<string> paths )
    {
        if( paths == null )
        {
            throw new ArgumentNullException( nameof( paths ) );
        }

        // cloning this collection and adding this include
        var newcol = new LiteCollection<T>( _name, _engine, _mapper, _log );

        newcol._includes.AddRange( _includes );

        //
        // Add all paths that are no null nor empty due to your previous check
        //
        newcol._includes.AddRange( paths.Where( query => !String.IsNullOrEmpty( query ) ) );

        return newcol;
    }

    public LiteCollection<T> IncludeAll() {
        //
        // Get the `EntityMapper` of `T` to get all classes in the database
        //
        IEnumerable<MemberMapper>
            memberMappers = _mapper.GetEntityMapper( typeof( T ) )
                .Members
                .Where( query => query.IsDbRef );

        List<string>
            fields = new List<string>();

        //
        // Cycle through each `MemberMapper` and get the field name,
        //   simulating `LiteCollection<T> Include<K>( Expression<Func<T, K>> path )`.
        //
        foreach( MemberMapper memberMapper in memberMappers ) {
            bool isdbref = false;

            string field = _visitor.GetField( memberMapper, true, ref isdbref );

            fields.Add( $"$.{field}" );
        }

        //
        // Include the fields
        //
        return Include( fields );
    }

### QueryVisitor.cs

    public string GetField( Expression expr, string prefix = "", bool showArrayItems = false )
    {
        var property = prefix + expr.GetPath();
        var parts = property.Split('.');
        var fields = new string[ parts.Length ];
        var type = _type;
        var isdbref = false;

        // loop "first.second.last"
        for( var i = 0; i < parts.Length; i++ )
        {
            var entity = _mapper.GetEntityMapper( type );
            var part = parts[ i ];
            var prop = entity.Members.Find( x => x.MemberName == part );

            //
            // Moved the code to a method, so it could be used by the `IncludeAll`
            //
            string field = GetField( prop, showArrayItems, ref isdbref );

            if( field == null )
            {
                throw new NotSupportedException( property + " not mapped in " + type.Name );
            }
        }

        return string.Join( ".", fields );
    }
    public string GetField( MemberMapper memberMapper, Boolean showArrayItems, ref Boolean isdbref )
    {
        if( memberMapper == null )
        {
            return null;
        }

        // if property is an IEnumerable, gets underlying type (otherwise, gets PropertyType)
        Type type = memberMapper.UnderlyingType;

        string field = memberMapper.FieldName;

        if( showArrayItems && memberMapper.IsList )
        {
            field += "[*]";
        }

        if( memberMapper.FieldName == "_id" && isdbref)
        {
            isdbref = false;
            field = "$id";
        }

        // if this property is DbRef, so if next property is _id, change to $id
        if( memberMapper.IsDbRef )
        {
            isdbref = true;
        }

        return field;
    }

What do you think about implementing a similiar feature in the main project?

**Comment by mbdavid** [comment]
Hi @Auhmaan, thanks. Nice option. Do you want propose a PR? With PR it's easy to compare changes in existing methods

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
