### ISSUE TITLE
Getting StackOverflowException Whenver trying to pull an item from a collection.

### ISSUE THREAD

**Issue by yoshisman8** [mbdavid/LiteDB#902]
Just what it says on the tin, whenever i try to access an element of a collection (Find/Findall/Findone/FindbyID) i get a StackOverflowException and the app crashes. 

The class being stored is rather complex/large, so i'll link its .cs file [here](https://pastebin.com/uQkjw3JY).

The class has no recursive references so that wouldn't be the reason. If anyone can give me a hand i'd be really grateful.

**Comment by mbdavid** [comment]
Is not here your problem?

```C#
    public class Statblock{
        public int MGT {get;set;} = 0;
        public int AGI {get;set;} = 0;
        public int CON {get;set;} = 0;
        public int PER {get;set;} = 0;
        public int MAG {get;set;} = 0;
        public int LCK {get;set;} = 0;
        public int Fort {
            get {
                return Convert.ToInt32(Math.Floor(Convert.ToDouble(MAG/4)));
            }
            set{
                **Fort = value;**
                }
        }
        public int Prot {get;set;} = 0;
 
    }
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
