### ISSUE TITLE
Do it work on Xamarin and Xamarin Forms?

### ISSUE THREAD

**Issue by biapar** [mbdavid/LiteDB#905]
Do it work on Xamarin and Xamarin Forms?

**Comment by yuxin5156** [comment]
Not Yet

**Comment by mbdavid** [comment]
Hi @biapar, LiteDB are fully netstandard 2.0 compatible - so yes, you can use in Xamarin. If you want store you datafile in non-user directory, use "async=true" in connection string.

**Comment by kormemis** [comment]
hello @mbdavid  is that works on PCL xamarin forms ?

**Comment by DamienDoumer** [comment]
@biapar  @kormemis  It works on Xamarin Forms, I recently used it and [here is a blog post ](https://doumer.me/litedb-on-xamarin-forms-alternative-to-sqlite/)which will guide you through using it on XAmarin Forms :

**Comment by JensSchadron** [comment]
It works very well on Xamarin. Using it currently in a Xamarin.Android project and already used it in several Xamarin.Forms projects. But I'll close this question as I'm cleaning up the issue list 🙂
