### ISSUE TITLE
LiteQueryable as IQueryable<T> interface

### ISSUE THREAD

**Issue by digitalkirkley** [mbdavid/LiteDB#906]
Existing frameworks provide abstraction from persistence and provide an interface for code sharing between platforms E.g. Xamarin and server side etc.  It would be ideal if the LiteQuerable was an IQueryable<T> interface that prevented LiteDB reference leakage.

**Comment by digitalkirkley** [comment]
I have used the LiteCollection<T> LINQ enabled expression members for the time being.

**Comment by mbdavid** [comment]
Hi @digitalkirkley, take a look on this issue #853

**Comment by digitalkirkley** [comment]
Ah thank you. ;-)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
