### ISSUE TITLE
What is exactly? Database or Interface

### ISSUE THREAD

**Issue by ghost** [mbdavid/LiteDB#907]
i have a question 
What is lite db exactly? Database or Interface
what is point to design this? 
run into any device? but this is C# and is Microsoft slogan
create a stand alone database? but where can use? clients or servers
so i suggest to see SQLLite https://www.sqlite.org/whentouse.html

i don't say Lite db bad designed but its not based software industry
so i confused when i want to develop that interface because light db don't sparest that 
tnx if fix it

**Comment by mbdavid** [comment]
Hi @miladsadeghi72, LiteDB is a full functional embedded database for .NET. Run under .NETStantard, so must run in any platform that are compatible with net standard (.net full, .net core, mono, ....) You can use LiteDB in web app, desktop app, services, mobile.... 
NoSQL databases has no interface in ADO.NET like SQLite/MS SQL server or Oracle... Each database implement an own API.... LiteDB api was inspired on MongoDB API for C#

**Comment by miladsadeghi72** [comment]
yes u right also about ADO.NET :+1: 
tnx fow answers :)
