### ISSUE TITLE
i want to working like this 

### ISSUE THREAD

**Issue by ghost** [mbdavid/LiteDB#909]
hi david and excuse me for talking much but i want to show you how realy componis working
excuse me but this is war of software industri
see :1st_place_medal: https://github.com/miladsadeghi72/InterNationalDataWorks

**Comment by mbdavid** [comment]
Hi @miladsadeghi72, I saw your code. Its a very simple solution to store object in file disk, for small volume of data is a nice solution... but it cannot grow because you have no index to search data.

**Comment by miladsadeghi72** [comment]
yes there is index on file names
i don't agree about small volume of data
do you have big data on your hard disk?
its file system and controls that like ntfs or fat/fs

this is new our project but this very is simple vesion
our problem is not big data, our problem is pattern on information and action smart to data
other recent problem is index based other tables, its new
tnx for answer :100:
