### ISSUE TITLE
OnVersionUpdate called before Mapper Initialized from ctor

### ISSUE THREAD

**Issue by techrising** [mbdavid/LiteDB#91]
When Using OnVersionUpdate we need to register custom type one more time.
OnVersionUpdate is called from base(connectionString), before myDb ctor.
It's not that easy to solve...
I don't mind calling UpdateDatabaseVersion() manually or override a method where I can init the mapper only once.
```C#
public myDb(string connectionString) : base(connectionString)
{
//Called Second
    Mapper.RegisterType(TimeSpanToBson, BsonToTimeSpan);
}
 protected override void OnVersionUpdate(int newVersion)
    {
// Called First
        Mapper.RegisterType(TimeSpanToBson, BsonToTimeSpan);
        switch (newVersion)
        {
            case 1:
            [...]
        }
    }
```

**Comment by mbdavid** [comment]
Hi @techrising, are you using lastest version? In v2 use `OnModelCreating` override method to register custom mappings. Get lastest version from `master` branch.

**Comment by techrising** [comment]
Switched to the v2 RC and it works.
Thanks,
