### ISSUE TITLE
Does V5 include such features as custom tokenizer string and full text search for fields of document?

### ISSUE THREAD

**Issue by GitOffice** [mbdavid/LiteDB#910]
Does v5 version include such features as custom tokenizer  and full text search for specific field of document?

**Comment by mbdavid** [comment]
Hi @GitOffice, I haven't plans yet to implement full text search. I already create (long time ago) a branch for this fts, but I left to focus in another features.

In v5 version will be possible create your own tokenizer function and add as an expression method call. You can write something like:

```
public IEnumerable<BsonValue> FTS(string content)
{
    return Regex.Split(content, "\W"); // write here your own function
}
```

And then:

`BsonExpression.Register("FTS", typeof(FullTextSearch).GetMethod("FTS"))`

and index your columns with this function:

```
db.EnsureIndex("mycol", "full_text", "FTS(email.body)");
```

**Comment by GitOffice** [comment]
Great.Let me try now.

**Comment by Jack85** [comment]
Couldnt you just include this simple extendable fulltext version of fulltext index in v5?
something like ` db.EnsureFullTxtIndex(..-`  making it possible for fields longer than 512 bytes

**Comment by mbdavid** [comment]
Hi @Jack85, I'm curious about why you need more than 512 bytes in index key? In v5 this size are lower: 255 bytes (because will use only 1 byte to length). But, for full text search, you need tokenizer your text into terms,,, and index this terms. This will be possible using a user custom function in engine.

**Comment by Jack85** [comment]
Just to have some default full text index functionality in place like you have on any db system, so that everybody doesnt have to make tokenizers on their own right away.

**Comment by GitOffice** [comment]
@mbdavid   Is FullTxtIndex feature  included in V5 beta which will be released August 2019?

**Comment by mbdavid** [comment]
Hi @GitOffice, not yet, but are on plans to be implemented a simple full text search in v5

**Comment by GitOffice** [comment]
It is official feature to expect. Thanks.

**Comment by vickyrathee** [comment]
@mbdavid  Does v5 has full text search now?
