### ISSUE TITLE
Test Results In LiteDB

### ISSUE THREAD

**Issue by ghost** [mbdavid/LiteDB#914]
hi @mbdavid 
this is Test on LiteDB
test contains 100,000 Inserts and Update Via 100 Thread
every thread run 1000 inserts and update
Result:
liteDB Actions Completed Time For 100000 Items : RunTime 00:04:06.81
average cpu usage 72%

we have same test on directory table (international data works)
Result:
DirectoyTable Actions Completed Time For 100000 Items : RunTime 00:10:43.86
 average cpu usage 95%

congratulation David Great Work :+1: 
LiteDB is so Optimum

**Comment by mbdavid** [comment]
Hi @miladsadeghi72, thanks! If you avoid open/close/re-open file in filestream you can save lots of time.
