### ISSUE TITLE
Find by nested object property

### ISSUE THREAD

**Issue by falahati** [mbdavid/LiteDB#915]
Hey David,

Please take a look at the following example:

```C#
    internal class VideoFile
    {
        public string Address { get; set; }
        public long Length { get; set; }
    }

    internal class Video
    {
        [BsonId]
        public int Id { get; set; }
        public VideoFile[] Files { get; set; }
        public string Title { get; set; }
    }
```

And this piece of code:

```C#
    var fileInfo = new FileInfo("some video file");
    var videos =
        DataStore.Videos.Find(v => v.Files.Any(f => f.Length == fileInfo.Length))
            .ToArray();
```

This code supposed to find videos having a file with same `Length` as the file specified. However, it always return an empty result. Same code works if I replace `Find` with `FindAll` and then apply the `Where` Linq method. But there are thousands of videos and this is very cpu and memory intensive.

What is your advice?

**Comment by mbdavid** [comment]
Hi @falahati, nice to see you again here. I think your problem can be with linq expression "Any". Try do:

- First, create an index:
`DataSote.Videos.EnsureIndex("idx_length", "$.Files[*].Length");`
- Now, search using index:
`DataStore.Videos.Find(Query.EQ("idx_length", fileInfo.Length));`

If you want still using LINQ expression, try:

`DataStore.Videos.Find(x => x.Files[0].Length == fileInfo.Length)`

Remember: using 0 index doesn't mean search only in first index (0) but it´s simple way to access child array. This linq expression will be translated into `$.Files[*].Length`

**Comment by falahati** [comment]
This worked David, Thanks
The code is now a little harder to read and understand but the difference in performance was significant.

**Comment by mbdavid** [comment]
Yep, I not "natural" as expected. That's why I'm changing this for v5: Now `LiteEngine` will work fully with `BsonExpression` (string expressions) and LINQ will be converted into `BsonExpression`. That's will be much more transparent to user.

**Comment by falahati** [comment]
We should be able to do something about indexes too. Now I had to "ensure" them inside my singleton class. But it would be great to be able to define them somewhere inside the model class. We had an attribute for that but I think it is now marked as deprecated.
