### ISSUE TITLE
Store Bitmap

### ISSUE THREAD

**Issue by Kn1fe** [mbdavid/LiteDB#919]
I'm using this to add image 
`CacheDB.GetCollection<Bitmap>("Icons").Insert(path, data);`
Then im trying to get this bitmap and im getting error from System.Drawing
`Bitmap image = CacheDB.GetCollection<Bitmap>("Icons").Find(Query.Contains("_id", path))?.First();`
Error:
> System.ArgumentException
>   HResult=0x80070057
>   Message = Invalid parameter.
>   Source = System.Drawing
>   Stack trace:
>    in System.Drawing.Image._SetColorPalette(ColorPalette palette)
>    in System.Drawing.Image.set_Palette(ColorPalette value)
>    in LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value)
>    in LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
>    in LiteDB.BsonMapper.ToObject(Type type, BsonDocument doc)
>    in LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
>    in LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
>    in System.Linq.Enumerable.First[TSource](IEnumerable`1 source)

**Comment by mbdavid** [comment]
Hi @Kn1fe, I never work with `Bitmap` class, but i think it's a complex class that need custom serialization process. You can create your own serialize/deserialize function using `BsonMaper.Global.RegisterCutomType`.. see some examples here:

https://github.com/mbdavid/LiteDB/wiki/Object-Mapping#register-a-custom-type

**Comment by Kn1fe** [comment]
`            BsonMapper.Global.RegisterType<Bitmap>
            (
                serialize: (img) => (byte[])new ImageConverter().ConvertTo(img, typeof(byte[])),
                deserialize: (bson) => Image.FromStream(new MemoryStream(bson.AsBinary)) as Bitmap
            );`
Crash on insert

>    in LiteDB.BsonMapper.ToDocument[T](T entity)
>   in LiteDB.LiteCollection`1.Insert(BsonValue id, T document)

**Comment by miladsadeghi72** [comment]
try to convert bitmap to byte array
then insert that bytes
so you dont need declare serialize

**Comment by tyeth** [comment]
Yeah I had problems with this and ended up with this:
`if (collection == null) InitialiseDb();
            var ms = new MemoryStream();
            trainedFace.Bitmap.Save(ms, ImageFormat.Bmp);
            await ms.FlushAsync();
            ms.Seek(0, SeekOrigin.Begin);
            var filename = Path.GetDirectoryName(Application.ExecutablePath) + "/TrainedFaces/face" + TrainingImages.Count + ".bmp";
            await collection.InsertOneAsync(new FacialCroppedMatch
            {
                ImageBytes = ms.ToArray(),
                Name = filename,
                Person = text
            });`

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!

**Comment by matelich** [comment]
Thanks all for the approximate code, this seems to be working for me put all together.
```
         mapper.RegisterType(
            serialize: bitmap =>
            {
               var ms = new MemoryStream();
               bitmap.Save(ms, ImageFormat.Bmp);
               ms.Flush();
               ms.Seek(0, SeekOrigin.Begin);
               var val = new BsonValue();
               val = ms.ToArray();
               return val;
            },
            deserialize: value =>
            {
               return Image.FromStream(new MemoryStream(value.AsBinary)) as Bitmap;
            }
         );
```
I'd love to see some list of common mappings people have made.
