### ISSUE TITLE
How to install this on Unity?

### ISSUE THREAD

**Issue by MihailTrajkovski** [mbdavid/LiteDB#922]
First I would say sorry if this was already answered somewhere.

I wanted to ask how do you install this on Unity? I've tried putting the dll from 4.0.0 beta(the one that said it supports unity) and sadly my dll is not recognized in Unity( I get the error Type or namespace name LiteDB could not be found). 

As i see there is a unity3d branch but i dont really use Visual Studio so i can build it as a dll, so my question precisely is do i need to install VS in order to build a dll or is there a dll that i can use already?

I understand that Unity isn't officially supported on all their platforms, but I wanted to ask you are most of the features of LiteDB supported on PC, iOS, Android and the consoles(although the consoles aren't really that important to me)? I understand if some of the features won't work as expected but if most of the features work than this is really a great asset!

**Comment by MihailTrajkovski** [comment]
I did build the project in mono(the unity3d branch), and it works. Still would like an answer to my final question, of course if you are able to provide that info( no worries if you can't this is still a really good package and I will use it extensively in my upcoming project).

**Comment by mbdavid** [comment]
Hi @MihailTrajkovski! I tried (hard) to understand and code in Unity but it's not for me :) - If you see this #734 issue about unity, I found some "bugs" in unity and that's why my last versions are not working. But, I get no response from this issue. I was waiting more help from someone who know well unity for fix this.

And, last week, I found in "Unity Assets Store" some one selling LiteDB for $15 that works in Unity (v3). This interesting in LiteDB is very nice, but I expected this kind of work still free... because I've never earned a dollar with LiteDB in more than 3 years of development.

**Comment by MihailTrajkovski** [comment]
Hey, 
Thank you for your response.
No worries if Unity seems hard, all the magic you do with this package seems hard for Unity users too :smile:. I am also not an expert unity user so sadly i can't help you really with the issue. 
Also yeah i know how it feels, you do all the hard work and someone swoops in and tries to get money just by doing some small modifications. But as I read Unity is planning to fully support Net 4.6 in the coming months so maybe then everyone would be able to use LiteDB without any problems.
Also i will look in to the thread you posted and test the package for unity from there.

**Comment by stefanrichings** [comment]
@MihailTrajkovski - just as an FYI, i've been using LiteDB in a project in Unity 2017.3 with .NET 4.6 Experimental enabled and it's working perfectly fine. Pretty sure i'm using v4.1.1 DLL. 

I did have issues with previous versions of Unity, so wouldn't recommend and version earlier than 2017.3. As of 2018.1 .NET 4.6 will be fully supported as well so future versions will be fine.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
