### ISSUE TITLE
Using index as sorting

### ISSUE THREAD

**Issue by ghost** [mbdavid/LiteDB#932]
hi @mbdavid 
i want to use index for sorting
this is because i must store sorting for maximum performance
example:

Dim db = New LiteDB.LiteDatabase(Application.StartupPath + "/ldb")

Dim person = db.GetCollection(Of Person)()

person.EnsureIndex(Function(c) c.Acode)
person.EnsureIndex(Function(c) c.Bcode)

        person.Insert(New Person With {
                       .acode = 5,
                       .bcode = 1})

        person.Insert(New Person With {
                       .acode = 4,
                       .bcode = 2})

        person.Insert(New Person With {
                       .acode = 3,
                       .bcode = 3})

        person.Insert(New Person With {
                       .acode = 2,
                       .bcode = 4})

        person.Insert(New Person With {
                       .acode = 1,
                       .bcode = 5})

        Dim a = person.Find(Function(c) c.acode > 0).ToArray()
        Dim b = person.Find(Function(c) c.bcode > 0).ToArray()

now how can use sorted items with out querying on that

**Comment by mbdavid** [comment]
Hi @miladsadeghi72, when you run a query using an index, all result are sorted according this index key, because index are organized in ASC order (or DESC). For now is the only way to get sorted using index. You can also try FindSort method in Engine class, that implement inline index for sort results.

**Comment by miladsadeghi72** [comment]
thanks for quick response 
i try

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
