### ISSUE TITLE
Password ConnectString Bug 4.1.2

### ISSUE THREAD

**Issue by Goepfie** [mbdavid/LiteDB#934]
nice library! Been fiddeling arround with it for a few days. Just wanted to let you know, that I ran into a weird bug with a specific password. I had it created by a randomization tool:

```
private const string Key = "$[3xM%7?MXuZ2s[;";
...
            connection = new ConnectionString
                             {
                                 Filename = file.ToString(),
                                 Password = Key
                             };

```
does initialize & save a database with out any issues, but if you try to reopen it with the same connection string/password it won't be able to read the database any more. You will get a false-positive on an wrong password exception. Tried it with my code as well as with LiteDBExplorer.

Removing the last semicolon, so the password reads `$[3xM%7?MXuZ2s[` does work as expected.

**Comment by mbdavid** [comment]
Hi @Goepfie, thanks!
Semicolon `;` is used in connection string as key/value separator. So, it's not possible have `;` in your password. I don't know in another databases, but I didn't implement any escape char for this (only in filename key you can use `"` as string separator)

**Comment by Goepfie** [comment]
Thanks for clearing that up.
Thought something in this direction, but did not want to assume things. Maybe an exception or a remark somewhere would be nice :)

**Comment by tdinucci** [comment]
I have created a pull request which allows for passwords within connection strings to be defined as string literals, which allows for passwords to contain previously unavailable characters.

The main point with the pull request though is that it introduces meaningful exception messages at the time a connection string is parsed.

[https://github.com/mbdavid/LiteDB/pull/944](https://github.com/mbdavid/LiteDB/pull/944)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
