### ISSUE TITLE
ArgumentNullException in EntityBuilder

### ISSUE THREAD

**Issue by pylnik** [mbdavid/LiteDB#936]
Hello.
Recently I faced the following issue. If I use BsonMapper.Global and call Ignore twice for the same entity, I get an ArgumentNullException.
I've not found info in wiki, whether this is a featue or bug.
Please find an attached example. I used v.4.1.2.

[Example program](https://github.com/mbdavid/LiteDB/files/1810336/Program.zip)

**Comment by mbdavid** [comment]
Hi @pylnik, yes, `Ignore` method remove from member collection, so when you call twice return no property found.

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/EntityBuilder.cs#L30

**Comment by pylnik** [comment]
Hi @mbdavid !
Thanks for the fast answer.

Does it mean that I should avoid multiple call of mapping for same entity? Is it possible to control if the entity has been already mapped?

I understand that possible workaround would be avoiding BsonMapper.Global and creating own mapper for every instance of LiteDB.

**Comment by mbdavid** [comment]
Hi @pylnik, I was looking in code if is possible check this but only member that contain this mapping are private because use internal classes. In this case, I always recommend use a single LiteDatabase instance for all multi-thread uses, to ensure better file/cache manager. You can map your database just before open datafile.

**Comment by pylnik** [comment]
Ok. The idea with one LiteDB instance is clear (I do use it). Because of business logic I have multiple database files and create multiple instances of LiteDatabase at one time. 
I will try to use local instances of BsonMapper for each LiteDatabase.
