### ISSUE TITLE
Mode=Exclusive connection string ignored with LiteDatabase.Shrink()

### ISSUE THREAD

**Issue by RoyGoode** [mbdavid/LiteDB#938]
When using .Shrink() on the database, it causes an exception when Mode=shared is not available. Adding "mode=Exclusive" in the connection string does not solve the issue, because the Shrink() method ignores the "mode" element of the connection string.

**Comment by mbdavid** [comment]
Thanks @RoyGoode, I will take a look better on this.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
