### ISSUE TITLE
[v5] Performance Improvement -  .Net Core 2.1 

### ISSUE THREAD

**Issue by PascalSenn** [mbdavid/LiteDB#939]
Hi @mbdavid 

Have you seen the new .Net 2.1 features  `Span<T>, Memory<T>`
https://blogs.msdn.microsoft.com/dotnet/2018/02/02/net-core-2-1-roadmap/

> We are on the verge of introducing a new set of types for using arrays and other types of memory that is much more efficient. Today, if you want to pass the first 1000 elements of a 10,000 element array, you need to make a copy of those 1000 elements and pass that copy to your caller. That operation is expensive in both time and space. The new Span<T> type enables you to provide a virtual view of that array without the time or space cost. It’s also a struct, which means that there is no allocation cost either.

That could be really interesting for low level APIs as in the Engine. I saw that there will be a new implementation of Stream.  
https://github.com/dotnet/coreclr/blob/release/2.1/src/mscorlib/src/System/IO/Stream.cs#L752

**Comment by mbdavid** [comment]
Hi @PascalSenn, I didn't know about this classes. That will be awsome for performance. I writing, right now, an `ChunckStream` to create an stream deserializer document and `Span` can fit perfect for that. I will take a look beter on that and will use in v5. For database, performance and memory consume are everything!

Thanks a lot!

**Comment by PascalSenn** [comment]
Alright 👍
Anyway LiteDB is great! Good job, thanks a lot. We use LiteDB in multiple production environments.
Looking forward to v5!
Gonna close this.
