### ISSUE TITLE
database files on a fileshare

### ISSUE THREAD

**Issue by OneCyrus** [mbdavid/LiteDB#941]
we are looking into containerizing an application which uses litedb. currently the application saves the data on a local disk. to be able to use stateless containers we would like to put the files on a fileshare (SMB). our first try ended up with having the collections in the database-file but no data was added to the file. is there something specific in litedb which fails when using fileshares?

**Comment by mbdavid** [comment]
Hi @OneCyrus, it's possible a permission problem? Did you try write a simple `File.WriteAllBytes` to test access?

BTW, It's not too recommended use shared files if you will have concurrent access. LiteDB must use FileStream.Lock file to control lock and this can cause some problems. I saw this same recommendation for Sqlite

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
