### ISSUE TITLE
How to create a wrapper class for LiteDB?

### ISSUE THREAD

**Issue by Rajeshpaulchamy** [mbdavid/LiteDB#942]
@mbdavid , hi I am trying to create a wrapper class for LiteDB, so that I can re-use my business logic for other databases. I have created wrapper APIs to create, delete, insert and find by id.  The below wrapper APIs may be useful for others. Also please review and let me know, if there are any critical issues.

`

	public class DbManager
	{
		private string _dbName;

		public void CreateDB(string dbName)
		{
			_dbName = dbName;

			// Open database (or create if doesn't exist)
			using (var db = new LiteDatabase(_dbName))
			{
				Console.Out.WriteLine("DB Created at the location: " + dbName);
			}
		}

		public void CreateTable<T>(Dictionary<string,bool> indexedItems = null)
		{
			using (var db = new LiteDatabase(_dbName))
			{
				var collection = db.GetCollection<T>(typeof(T).Name);

				// create index
				if(indexedItems != null)
				{
					foreach (var item in indexedItems)
					{
						collection.EnsureIndex(item.Key, item.Value);
					}
				}			
			}
		}

		public void DeleteTable<T>()
		{
			using (var db = new LiteDatabase(_dbName))
			{
				db.DropCollection(typeof(T).Name);
			}
		}

		public BsonValue InsertRow<T>(T item)
		{
			using (var db = new LiteDatabase(_dbName))
			{
				var collection = db.GetCollection<T>(typeof(T).Name);

				if(item != null)
				{
					return collection.Insert(item);					
				}		
			}

			return null;
		}

		public void DeleteRow<T>(BsonValue objectId)
		{
			using (var db = new LiteDatabase(_dbName))
			{
				var collection = db.GetCollection<T>(typeof(T).Name);
				if (objectId != null)
				{
					collection.Delete(objectId);
				}
			}
		}

		public T FindRowById<T>(ObjectId id)
		{
			using (var db = new LiteDatabase(_dbName))
			{
				var collection = db.GetCollection<T>(typeof(T).Name);
				return collection.FindById(id);				
			}
		}
`

But I am not able to create the wrapper API for the LiteDB API "Find()". Please help me on this.

**Comment by Rajeshpaulchamy** [comment]
@mbdavid, thanks for your help and support. 
I understand your answer, I have used '.ToList()' for return, please find below my code for a specific use case.

`

		public IEnumerable<T> FindByAttribute<T>(string attributeName, string attributeValue)
		{
			using (var db = new LiteDatabase(_dbName))
			{
				var collection = db.GetCollection<T>(typeof(T).Name);
				return collection.Find(Query.EQ(attributeName, attributeValue)).ToList();
			}
		}

`

However I am not able to figure out how to wrap the 'LiteDB.Query' object.
Please let me know your comments.

**Comment by mbdavid** [comment]
If you want wrap all `Query` functions in you own class, you must re-write all `Query` static methods in another class.

```C#
public class YourQuery
{
    internal LiteDB.Query _query;
    
    private YourQuery(LiteDB.Query query)
    {
        _query = query;
    }
    
    public static YourQuery EQ(string field, object value)
    {
        return new YourClass(LiteDB.Query.EQ(field, value));
    }

    public static YourQuery LT(string field, object value)
    {
        return new YourClass(LiteDB.Query.LT(field, value));
    }
    
    // ...
}

public IEnumerable<T> Find<T>(YourQuery query)
{
    using (var db = new LiteDatabase(_dbName))
    {
        var collection = db.GetCollection<T>(typeof(T).Name);
        return collection.Find(query._query).ToList();
    }
}
```

Another way is use `Expression`, like this:

```C#
public IEnumerable<T> Find<T>(Expression<Func<T, bool>> expr)
{
    using (var db = new LiteDatabase(_dbName))
    {
        var collection = db.GetCollection<T>(typeof(T).Name);
        return collection.Find(expr).ToList();
    }
}
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
