### ISSUE TITLE
Can not get data in many table

### ISSUE THREAD

**Issue by 2Red** [mbdavid/LiteDB#945]
`public class Customer
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }

        public class Product
        {
            public int Id { get; set; }
            public string Description { get; set; }
            public double Price { get; set; }
        }

        // DbRef to cross references
        public class Order
        {
            public int Id { get; set; }
            public DateTime OrderDate { get; set; }
            public Customer Customer { get; set; }
            public List<Product> Products { get; set; }
        }

        static void Main(string[] args)
        {
            // Re-use mapper from global instance
            var mapper = BsonMapper.Global;

            // Produts and Customer are other collections (not embedded document)
            // you can use [BsonRef("colname")] attribute
            mapper.Entity<Order>()
                .DbRef(x => x.Products, "products")
                .DbRef(x => x.Customer, "customers");

            // Open database (or create if not exits)
            using (var db = new LiteDatabase(@"D:\\An.db"))
            {
                // Get collection
                var customers = db.GetCollection<Customer>("customers");
                var products = db.GetCollection<Product>("products");
                var orders = db.GetCollection<Order>("orders");

                // create examples
                var an = new Customer { Name = "An Nguyen" };
                var thanh = new Customer { Name = "Thanh Ngoc" };
                var tv = new Product { Description = "TV Sony 4K\"", Price = 799 };
                var iphone = new Product { Description = "iPhone X", Price = 999 };
                var order1 = new Order { OrderDate = new DateTime(2018, 03, 30), Customer = an, Products = new List<Product>() { iphone, tv } };
                var order2 = new Order { OrderDate = new DateTime(2017, 03, 30), Customer = thanh, Products = new List<Product>() { iphone } };

                // insert into collections
                customers.Insert(an);
                customers.Insert(thanh);
                products.Insert(new Product[] { tv, iphone });
                orders.Insert(new Order[] { order1, order2 });

                // create index in OrderDate
                // orders.EnsureIndex(x => x.OrderDate);
                // orders.EnsureIndex(x => x.Customer.Name);
                // customers.EnsureIndex(x => x.Name);

                // When query Order, includes references
                var result = orders
                    .Include(x => x.Customer)
                    .Include(x => x.Products)
                    .Find(x=>x.Customer.Name == "An Nguyen");

                // Each instance of Order will load Customer/Products references
                foreach (var c in result)
                {
                    Console.WriteLine("#{0} - {1}", c.Id, c.Customer.Name);

                    foreach (var p in c.Products)
                    {
                        Console.WriteLine(" > {0} - {1:c}", p.Description, p.Price);
                    }
                }
                Console.ReadLine();
            }
        }`
This is my code. Please help. I can not get data by Customer.Name. Thank you.

**Comment by mbdavid** [comment]
Take a look here: https://github.com/mbdavid/LiteDB/issues/937

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
