### ISSUE TITLE
NullReferenceException when calling Insert

### ISSUE THREAD

**Issue by amouzigh** [mbdavid/LiteDB#947]
Hello,
I'm using LiteDB. It seems to be great. Thanks.

However I'm facing an issue when calling Insert. I have a NullReferenceException.

                using (var db = new LiteDB.LiteDatabase("FileName=simple.db;Password=mypassword;Timeout=00:00:15"))
                {
                    var dcsCollection = db.GetCollection<IChannelItem>("data");
                    try
                    {
                        dcsCollection.Insert(channelItem);
                    }
                    catch (NullReferenceException)
                    {
                        // To be fixed. NullReferenceException throwed when inserting
                    }
                }

However, file data is well created.
Thanks for your support

**Comment by mbdavid** [comment]
Hi @amouzigh, try not use an interface as collection model definition. CAn you paste your interface and class structure?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
