### ISSUE TITLE
IndexOutOfBoundsException when serializing class based on Dictionary<k,v>

### ISSUE THREAD

**Issue by RobFone** [mbdavid/LiteDB#948]
When the object being inserted to a collection contains a member that is a type based on Dictionary<k,v>, an IndexOutOfBoundsException if thrown from BsonMapper.Serialize(Type, Object, Int). The source of the exception is the [following line](https://github.com/mbdavid/LiteDB/blob/5c596cbc34ce91de83acc52d85603c342830e588/LiteDB/Mapper/BsonMapper.Serialize.cs#L105):

    var itemType = type.GetTypeInfo().GetGenericArguments()[1]

This code reproduces the issue:

    public class Program
    {
        static void Main(string[] args)
        {
            using (var db = new LiteDatabase("MyDocs"))
            {
                var docs = db.GetCollection<MyDocument>();
                docs.Insert(new MyDocument
                {
                    Id = 1,
                    Title = "My Document",
                    Chapters = new MyDictionary()
                });
            }
            Console.WriteLine("Press a key to exit");
            Console.ReadKey();
        }
    }

    public class MyDocument
    {
        [BsonId]
        public int Id { get; set; }
        public string Title { get; set; }
        public MyDictionary Chapters { get; set; }
    }

    public class MyDictionary : Dictionary<string, string>
    { }

**Comment by lvemil** [comment]
Facing the same issue.

`d[VectorSpaceFieldName] = BsonMapper.Global.ToDocument<SparsedNumericVector>(nv);`
...
`public class SparsedNumericVector: Dictionary<int, double>
 {    }`

**Comment by lvemil** [comment]
I changed 

`public class SparsedNumericVector: Dictionary<int, double> { }`

for
 
`public class SparsedNumericVector
    {
        public Dictionary<int, double> Components { get; set; }
    }`

and now it works.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
