### ISSUE TITLE
.NET Core DI Multiple Tasks Currency 

### ISSUE THREAD

**Issue by mitchellmaler** [mbdavid/LiteDB#949]
Hello, 

I am writing an application that can have 1 or many workers of the same method that will work off a collection as a queue. I am using .Net Core (2) Dependency Injection creating a Singleton.
```
services.AddSingleton(new LiteDatabase("Filename="+configuation.QueueConfig.QueueFileLocation+";Mode=Exclusive"));".
```
The issue is I am not 100% sure how to use your application with locking so a queue item can be pop without all the tasks/threads grabbing the same item. I tested using the lock statement which seems to do the trick but it slowed down the processing. I know the caveats of multi-treading which is why it slowed down and wanted to make sure I wasn't missing anything in your library that would help or maybe a queue example.

**Comment by mitchellmaler** [comment]
Is the library supposed to lock the collection or read and writes or is there something I am supposed to call before doing a read and write to lock then unlock it. Right now my method runs as a task I start up a few times but the tasks read the same top record at the same time. I am trying to get it to work more like a queue so I read the top record then update a field status saying it's locked.

**Comment by mbdavid** [comment]
Hi @michael-baker, LiteDB uses a single locker (for read/write) for all database. You can check this in LockerService class that manage thread lock (using ReaderWriterLockSlim class) and process lock (using FileStream.Lock/Unlock method).

But, as I understand your case, you want "read and remove" data (POP). This work in 2 separate methods and has no internal lock for this. For now, you best solution will be use simple "lock" (or Monitor.Enter/Exit) lock.

Future v5 will support read/write lock per collection, full transaction (so you can read/update or delete) and also "SELECT FOR UPDATE"-like operation (all this already implemented). But this version still in dev and will take a time for this.
