### ISSUE TITLE
Question - In memory support

### ISSUE THREAD

**Issue by rmszc81** [mbdavid/LiteDB#953]
Hello again @mbdavid,

I was wondering if LiteDB is capable of having "in memory" databases? I mean, without writing anything on disk, something like a memory cache?

Real example: I want to keep some tokens in memory and they're transient, should die after some X time.

Is it possible to do such a thing in LiteDB?

Once again, thank you.

Regards,

@rmszc81

**Comment by mbdavid** [comment]
Hi @rmszc81, LiteDB support "any" `Stream` as data source. You can use `MemoryStream` to store.... 
In next version will be available `TempStream` that uses `MemoryStream` under X bytes and a temp physical file excedded this limit (this file is deleted on `Dispose`).

**Comment by mbdavid** [comment]
https://github.com/mbdavid/LiteDB/blob/master/LiteDB.Tests/Database/DbRef_Interface_Tests.cs#L45

**Comment by rmszc81** [comment]
Fucking awesome!

Thanks again!

Closing the ticket!
