### ISSUE TITLE
Insert class with generic.

### ISSUE THREAD

**Issue by ldbenoit** [mbdavid/LiteDB#957]
Hey, I'm not sure if I'm doing something wrong but I am getting an error when trying to insert an object with generic type. Is this possible or am I doing something wrong?
```
LiteDB.LiteException: Invalid format: Channel`1
   at LiteDB.CollectionService.Add(String name)
   at LiteDB.LiteEngine.GetCollectionPage(String name, Boolean addIfNotExits)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
```

```
public class Channel<TUser>
{
    public int ChannelId { get; set; }
    public IList<TUser> Users { get; set; }
}

public class User
{
    public int Userid { get; set; }
}

using(var db = new LiteRepository("config.db"))
{
    var channel = new Channel<User>{ChannelId = 1, Users = new List<User>{new User{Userid = 1}}};
    db.Insert(channel);
}

```

**Comment by PascalSenn** [comment]
My best guess ist that you'd have to sepcify the collection name manually
Because of https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.cs#L102
Try this:
https://github.com/mbdavid/LiteDB/wiki/Object-Mapping

**Comment by PascalSenn** [comment]
It basically takes the name of the type. If it's a generic class it would be something like ```
GenericType`1
```
So there could be multiple matches. 
It would be pretty easy to fix, I guess.

**Comment by ldbenoit** [comment]
Yea, I read that collection names are limited to 30 bits or so and there is also a limit to total size of collections. I ended up using a hash of Type.FullName.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
