### ISSUE TITLE
Support for protected setters

### ISSUE THREAD

**Issue by emrys90** [mbdavid/LiteDB#958]
It would be nice to be able to support protected setter properties so you can ensure proper OOP if you have a property you do not want outside access to be able to modify.

**Comment by PascalSenn** [comment]
So if it's not accessible from outside, how are you gonna set it? 
JamesNK: Not supported
https://github.com/JamesNK/Newtonsoft.Json/issues/703

**Comment by emrys90** [comment]
The class itself would handle setting the value through appropriate methods. If you mean LiteDB, reflection has the ability to set private/protected fields.

**Comment by PascalSenn** [comment]
Uh , my mistake. Just checked. I was expecting LiteDB to use Newtonsoft.
I am well aware of those features. I just guess it's rather an edge case. 
Anyways, this might help:
https://github.com/mbdavid/LiteDB/wiki/Object-Mapping
Register your types and set/get the values by your own. I guess this could work. 

Also. If there are methods to set the protected/private field defined on the class itself. Then they are not really private/protected anymore? So the only proper way would be reflection.

**Comment by mbdavid** [comment]
It´s possible create your own class derived from BsonMapper and change here:

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.cs#L346

This method returns all fields/properties that will converted into BsonDocument.

**Comment by emrys90** [comment]
Could I not just change IncludeNonPublic to true?

**Comment by mbdavid** [comment]
@emrys90, to be honest, I never tested with `protected`. But can work...

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
