### ISSUE TITLE
Index on DbRef's Id

### ISSUE THREAD

**Issue by alex-mazzariol** [mbdavid/LiteDB#96]
LiteDB Version 1.0.4 here; my data model has a one-to-many relationship but I need to have both collections as stand-alone items.

I've been using DbRef<>s to map the many "children" to their "parents", but now I cannot use the parent Id (in the DbRef object) to quickly find the children. Example of the model:
```csharp
class Patient {
    public int Id {get; set;}
    public string Name {get; set;}
    public string Code {get; set;}
    public DbRef<Ward> Ward {get;set;}
}

class Ward {
    public int Id {get;set;}
    public int Name {get; set;}
}
```

Now when I call EnsureIndex() on the Patient collection I do:
```csharp
    collection.EnsureIndex(p => p.Code);
    collection.EnsureIndex(p => p.Ward.Id);
```
albeit naively, hoping that it would work. Anyway, when I try to search like this from the Patients collection, I get an "Invalid Format: IndexField" LiteException
```csharp
    collection.Find(p => p.Ward.Id == WardId);
```

Should I expect it to work? Should I not? I think it would be very convenient to be able to index by DbRef's identity fields; however this would move towards the behavior of SQL DBMSs.

**Comment by mbdavid** [comment]
Hi @alex-mazzariol, In v.1.x LiteDB uses DbRef<> implementation for cross reference, but indexes in this fields doesnt work.

In v.2 need works, but are not working yet (I tested now and has some problems). The main problem is on reflection and some logic to map your class to corrent index. I'm working on it now. I will update as soon as ready.
