### ISSUE TITLE
InsertBulk performance: IEnumerable vs List

### ISSUE THREAD

**Issue by cduvall** [mbdavid/LiteDB#961]
Consider the following:
```
public class UniqueValueModel
{
	public int Id { get; set; }
	public string Value { get; set; }
}
```

```
var collection = _db.GetCollection<UniqueValueModel>("strings");
IEnumerable<UniqueValueModel> unique = strings
	.Where(x => !collection.Exists(s => s.Value == x.Value));
collection.InsertBulk(unique.ToList());	
```
With some instrumentation (10,000 random guid inserts):
`[InsertBulk] Process completed in [4385.6923ms / 4.3856923s / 0.0730948716666667m]`

The same process, without first converting the unique enumerable to a list:
```
var collection = _db.GetCollection<UniqueValueModel>("strings");
IEnumerable<UniqueValueModel> unique = strings
	.Where(x => !collection.Exists(s => s.Value == x.Value));
collection.InsertBulk(unique);	
```
Results:
`[InsertBulk] Process completed in [57736.9491ms / 57.7369491s / 0.962282485m]`

I haven't had the time to pull down the source and examine it, but I imagine it could be operating one record at a time, executing the predicate & actualization.

**Comment by mbdavid** [comment]
Hi @cduvall, the main difference is because there in first example, all tests (read operations) are done before any write operation. In you must read/write for each item.

For better performance, try create unique index in Value field.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
