### ISSUE TITLE
Find method slow using index over large database

### ISSUE THREAD

**Issue by vbguyny** [mbdavid/LiteDB#962]
Hello, I have a NoSql database of around 120 MB and it contains an index with 7 different fields.  When I attempt to find records using this index which do not exist, it takes roughly 10 seconds to return that it didn't find anything.  This is creating a bottleneck for my application and would like to cut this time to less than a second.  Is there a best practice for how to create/use indexes?  Please keep in mind that the database is being used in a shared/multiprocess environment.  Thanks.

**Comment by mbdavid** [comment]
@vbguyny it's important to know that LiteDB do not support multi-column index. You can use only a single field (or expression) per index. This expression can return a document with multiple fields, but you must query over all fields.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
