### ISSUE TITLE
DbRef<T> clarification

### ISSUE THREAD

**Issue by StarkillerObl** [mbdavid/LiteDB#963]
Let's say we have a type DataBatchDTO and type BatchMetadataDTO

```
public class DataBatchDTO
{
    public int BatchId {get; set;}
    public IEnumerable<int> Data {get; set;}
    public BatchMetadataDTO Metadata {get; set; }
}

public class BatchMetadataDTO
{
    public int BatchId {get; set; }
    public int Min {get; set; }
    public int Max {get; set; }
    public int Amount {get; set;}
}
```

Mappings are done like this:

```
var mapper = new BsonMapper();

mapper.Entity<BatchMetadataDTO>()
            .Id(x => x.BatchId)
            .Field(x => x.Min, "min")
            .Field(x => x.Max, "max")
            .Field(x => x.Amount, "amount");

mapper.Entity<DataBatchDTO>()
                  .Id(x => x.BatchId)
                  .Field(x => x.Data, "data")
                  .DbRef(x => x.Metadata, "Metadata");

```

Database
`var db = new LiteDatabase("sample.db", mapper);`
And finally "Data" collection
`var dataCollection = db.GetCollection<DataBatchDTO>("Data");`

Now I would expect that if I do something like:

`dataCollection.Insert(someData);`

i will end up inserting into "Data" collection AND "Metadata" collection, however that is not the case.
If this is the expected behavior then I have to take care of inserting into "Metadata" collection manually which is a little bit inconvenient because I have to take care of data consistency manually.

**Comment by mbdavid** [comment]
Hi @StarkillerObl, 

There is only 1 inserts in your operation `dataCollection.Insert(someData);`. If you are working with `DbRef` you must first store your `BatchMetadataDTO` document.

```C#
var dataCollection = db.GetCollection<DataBatchDTO>("Data");
var metaCollection = db.GetCollection<BatchMetadataDTO>("Metadata");

metaCollection.Insert(someData.Metadata);
dataCollection.Insert(someData);
```

There are some feature request for this "auto" Insert (and delete) using references, but I didn't study more to check if is possible cover all cases (like re-use same document).

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
