### ISSUE TITLE
Is it possible to index the properties of a collection in LiteDb

### ISSUE THREAD

**Issue by evation** [mbdavid/LiteDB#964]
I have a result object in litedb with a collection property, as below:

```
public class Result
{
    public int Id { get; set; }
    public ICollection<Entity> ExtractedEntities { get; set; }
}

```
```
public class Entity
{
    public string Value { get; set; }
    public int Id { get; set; }
}
```
Is it possible to index the properties of the entity class so that I can do something like:

`collection.Find(r => r.ExtractedEntities.Any(ee => ee.Id == 1));`

I have tried the following
`                collection.EnsureIndex("ExtractedEntities.Id");`
`                collection.EnsureIndex(e => e.ExtractedEntities);
`

Thanks

**Comment by mbdavid** [comment]
There is a trick here: in you subdocument you are using "Id" named field. By default, LiteDB convert this in `_id` name, so you index must be:

```
collection.EnsureIndex("ExtractedEntities", "$.ExtractedEntities[*]._id");
```

If is possible, I recommend do not use Id in your subdocument (only with DbRef). You can check "auto-detect" rules here (`Id` or `Id<className>`):

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Mapper/BsonMapper.cs#L331

You can write your own mapper to avoid this too (overwriting this method)

**Comment by evation** [comment]
Hi, thanks for the feedback, I thought it might be something to do with the property name, so I actually changed it to EntityId to ensure that wasn't the bit causing me issues. Are they any other gotchas that might be causing me problems that you can think of? Is the "Any()" method problematic inside a find?

**Comment by mbdavid** [comment]
If you want use LINQ expression to find inside an array, I recommend you use "array syntax" for that. Like this:

`collection.Find(r => r.ExtractedEntities[0].Id == 1);`

(`0` here is not only first element, it´s just simples way to access item child)

This LINQ will be converted into:

`collection.Find(Query.EQ("$.ExtractedEntities[*].Id", 1)`

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
