### ISSUE TITLE
Multi Index Search

### ISSUE THREAD

**Issue by PascalSenn** [mbdavid/LiteDB#965]
We do have a lot data in a collection and use indexes on certain fields to break them down. We could break a list of thousands of records down to a few dozens with filtering the list by three fields. 
What's the best way of filtering by multiple fields?

**Comment by mbdavid** [comment]
Hi @PascalSenn, sorry for this delay, I was out few days from LiteDB working on new project.

LiteDB doesn't work with multiple fields indexes, like MongoDB (or any relation database). The only way to work with this is create sub documents/array in index using expressions. Like this:

`db.EnsureIndex("mycol", "idx_2", "[$.name, $.age]")`

And then, find using both fields:

`db.Find("mycol", Query.EQ("idx_2", new BsonArray { "John", 22 })`

But here you have a problem: you must find searching in both fields using same operand. You can't use "=" in `Name` and `>=` in `Age`.

You can also use some string concatenation. It's and ugly solution but works. Theoretically, multi field indexes are concatenation....

`db.EnsureIndex("mycol", "idx_c", "$.Name + '_' + LPAD($.Age, 5))`

In this case, you can work with `=` in first and `>` in second field

`db.Find("mycol", Query.GT("idx_c", "JOHN_00001")`

**Comment by PascalSenn** [comment]
Ah, no worries. Not really a production breaking point. I was just wondering. 

Alright. Good to know. In that case I'd need to rebuild my queries because currently you can query one or many fields.  What means creating indexes for all field combinations. Can work with that.
Thanks a lot for that response!
