### ISSUE TITLE
data not shown after insert new collection

### ISSUE THREAD

**Issue by davidtromin** [mbdavid/LiteDB#966]
I am writing a c# system using LiteDB.4.1.1
in DB.cs I calling saveField with new field data from API.
code as in below: 

        public bool saveField(field _c)
        {
            using (var db = new LiteDB.LiteDatabase(@"MyData.db"))
            {
                var col = db.GetCollection<field>("field");
                var ans = col.Find(x => x.name == _c.name);
                int c = ans.Count();
                if (c == 0)
                {
                    col.Insert(_c);
                    return true;
                }
                else
                {
                    return false;
                }
            }
        }
it return true and I tested from other script to verify:
code as in below: 

        public IList<field> listFields()
            {
                using (var db = new LiteDB.LiteDatabase(@"MyData.db"))
                {
                    //List<coacher> list = new List<coacher>();
                    List<field> list = new List<field>();
                    var col = db.GetCollection<field>("field");
                    var ans = col.FindAll();
                    foreach (var item in ans)
                    {
                        list.Add(item);
                    }
                    return list;
                }
            }
it did return right list.

The only issue is when I open the db from liteDBExplorer, there is no adding item in field collection.
Is there any miss-put?
Thanks in advance.
David

**Comment by mbdavid** [comment]
Hi David, did you test in shell tool? I didn't use LiteExplorer to know about this results. Try this in shell:
`> db.field.find limit 10`

**Comment by davidtromin** [comment]
Hi David,

Thanks for your soonest reply. 
I found that there is another MyData.db. in bin/debug folder, and the date result is updated in this one.

So in my project there are two MyDATA.db, one direct under project folder is not updated.
Is it normal....sorry I spent my 20 years life in UI design but a newbie to coding world.
David

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
