### ISSUE TITLE
File write performance 

### ISSUE THREAD

**Issue by christopherpross** [mbdavid/LiteDB#967]
Hello,
I have a short question, do you know a way how to optimice the performance of a file write on a database? At the moment I use openWrite to write a file, to display a progressbar etc. I work here with huge data and many files in total size of 1.5 gb, need in total more than one hour. Is there a way to do this quicker? Threads or push up the cache size? Because I know that my ssd can write quicker. :-) Maybe you have some hints for me.

best regards,
Christopher Proß

**Comment by mbdavid** [comment]
Hi, are you talking about write data in LiteDB, right? Or in in generic FileStream?

**Comment by christopherpross** [comment]
hm, I mean the filestorage from litedb. Or what do you mean? I have to store some files in litedb, the read performance is very good and now I search for ways to optimise the writing of files. Because I think that the write time of 1.5 hour is very long for "only" 1.6 gb on a ssd disk. I hope you know what I mean.

**Comment by mbdavid** [comment]
are you using v4? FileStorage can write 1.6gb in ssd in seconds. Take this example:

```C#
var file = @"c:\temp\filestore.db";
var iso = @"C:\Users\David\Downloads\release_Remix_OS_for_PC_Android_M_64bit_B2016112101.zip"; // 1Gb
var sw = new Stopwatch();

using (var db = new LiteDatabase(file))
{
    sw.Start();

    db.FileStorage.Upload("my-iso", iso);

    MessageBox.Show("Total: " + sw.Elapsed.TotalSeconds);
}
```

Here runs in 13 seconds.... and if you disable journal runs in 10 secods

**Comment by christopherpross** [comment]
Strange. I written now a test with upload and a single large file with 1.6 gb, on my ssd it is written in 71 seconds. My program which have to pack many files and all files to getter are 1.6 gb in size. Is this coursing the performance lag? I use in my program which takes so long for writing the openWrite method,  is this version slower then the upload one?

**Comment by mbdavid** [comment]
Open a single file is much more fast than thousand files.... but not 1 hour to 1.6. How many files are you saving? What size (in average) are you storing?

**Comment by christopherpross** [comment]
Hi,
ok I write a program to answer your question, here is the output:
```
path: d:\%x%sounds
found 618 files
total filesize: 1,76GB
minimal filesize: 3,98KB
average filesize: 2,91MB
maximal filesize: 35,88MB
```

please note, the comma is there, because I work on a german System.
So, replace , to .

**Comment by mbdavid** [comment]
Ok, I will try write some code to test write speed of files, using this average file size. But 618 is quite easy to write in disk.... even in HDD format... never this need more than hour to execute. 

German comma system is same as Portuguese... much easy to understand :)

**Comment by christopherpross** [comment]
Ok, tomorow I will post a little code snipped from my pack program, maybe you can find a huge mistake or bug, which course this lag

**Comment by elyoh** [comment]
There are two bottle necks:

LiteFileStream.Write.Flush() has 
_engine.Update(LiteStorage.FILES, _file.AsDocument);
Lots of small files will require **many** calls to update which is slow.
Caching files and updating them in bulk significantly increases throughput.

LiteFileStream.WriteChunks() has
_engine.Insert(LiteStorage.CHUNKS, chunk);
This is called once per chunk.
1GB file upload requires **many** chunks so many calls to Insert for just one file.
Caching chunks and inserting them in bulk significantly increases throughput.

Neither is supported in the current release.

In our use case, we had 100000 of small text files, which could be easily be uploaded in batches.  The operation was taking several minutes.  Careful use of a caching and reduced the Insert and Update calls reducing the operation down to a few seconds.

**Comment by christopherpross** [comment]
@mbdavid:
what do you say to the comment from elyoh?
Maybe that is the solution?

**Comment by mbdavid** [comment]
Hi @christopherpross, @elyoh are right... but his case is about 100000 small fils (not 618 as yours). And this make all difference.

When you have lot of small files operations are much more slow than 1 large file. Even if you test copy files in your disk. Every file has some overhead that has difference with size. In LiteDB, every file must write twice `_file` document to keep begin/finish processes. In a single large file, this twice operation has no difference, but in 100000 has a large difference.

In next version i'm change how database will write data in disk. v5 uses an async queue list of dirty pages, so this will speed up all disk write operation.

**Comment by elyoh** [comment]
OK but the LiteFileStream.WriteChunks() will still break the 1.6 GB file into ~6500 chunks.  This means 6500+ calls to update just to write one file.   This is a still **very** expensive.

Simply batching the chunks in memory (say 1000 chunks at a time) makes this much more efficient:

```
        private void WriteChunks()
        {
            var chunkCache = new List<BsonDocument>(1000);

            var buffer = new byte[MAX_CHUNK_SIZE];
            int read;
            _buffer.Seek(0, SeekOrigin.Begin);

            while ((read = _buffer.Read(buffer, 0, MAX_CHUNK_SIZE)) > 0)
            {
                var chunk = new BsonDocument
                {
                    { "_id", GetChunckId(_file.Id, _file.Chunks++) } // index zero based
                };

                // get chunk byte array part
                if (read != MAX_CHUNK_SIZE)
                {
                    var bytes = new byte[read];
                    Buffer.BlockCopy(buffer, 0, bytes, 0, read);
                    chunk["data"] = bytes;
                }
                else
                {
                    chunk["data"] = buffer;
                }
                    // Add the chunk to the local cache and add the chunks
                    // in bulk once the whole file has been chunked
                    chunkCache.Add(chunk);

                 // TODO: keep a count of chunks added and persist cache if it gets larger than 1000 to avoid
                 // OutOfMemoryException and having to copy the entire chunkCache to a new List of larger capacity
            }

            _engine.Insert(LiteStorage.CHUNKS, chunkCache);
            chunkCache.Clear();

            _buffer = new MemoryStream();
        }
    }
```

In the case of a 1.6 GB file, the chunk cache needs persisting more regularly to avoid possible OutOfMemoryException.  This is a relatively simple modification for existing users hitting this issue.

**Comment by christopherpross** [comment]
@mbdavid:
hm, ok but how I can speetup the write of 618 files? Because I need in the next days some inprovements in the performance. Any hints or ideas?

**Comment by mbdavid** [comment]
Hi @christopherpross, I will write a test for your case: generate 618 files with random sizes from 3 MB to 36 MB... and after this upload all this files into LiteDB datafile to check this so difference..

**Comment by mbdavid** [comment]
@christopherpross, here my example:

```C#
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SmallFilesLiteDB
{
    class Program
    {
        static int N = 618;
        static string _path = @"C:\Temp\SmallFiles\";

        static void Main(string[] args)
        {
            Directory.CreateDirectory(_path);

            var sw = new Stopwatch();

            sw.Start();

            CreateFiles();

            Console.WriteLine($"Create files: {sw.Elapsed.TotalSeconds} seconds.");

            sw.Restart();

            CreateDatabase();

            Console.WriteLine($"Upload to LiteDB: {sw.Elapsed.TotalSeconds} seconds.");

            Console.ReadKey();

        }

        static void CreateFiles()
        {
            var rnd = new Random();

            for(var i = 1; i <= N; i++)
            {
                File.WriteAllBytes(_path + i.ToString().PadLeft(3, '0') + ".bin", new byte[rnd.Next(4 * 1024, 5 * 1024 * 1024)]);
            }
        }

        static void CreateDatabase()
        {
            using (var db = new LiteDB.LiteDatabase(_path + "test.db"))
            {
                foreach(var file in Directory.GetFiles(_path, "*.bin"))
                {
                    db.FileStorage.Upload(Path.GetFileNameWithoutExtension(file), file);
                }
            }
        }
    }
}
```

My results was: 4 seconds to create files and 18 seconds to store inside LiteDB (my computer is a dell i7 + 16gb + ssd). Run this test to see if you get similar time.  Maybe your problem can be with how you get this files (are inside same machine?)

**Comment by christopherpross** [comment]
Hey,
very big sorry for this delay, it was all my fault, I had used a very ineffiziently code to upload.
I close this now.
sorry for that.

**Comment by samjett247** [comment]
Is there any plan for getting some control of chunking in LiteDB? The FileStorage.Upload() operation is taking ~400 ms for a 3 MB file on my machine, and I have ~20 files to upload in our SW. The "cached chunking" option provided by @elyoh above is very nice, and accelerates the operation down to about 80 ms. I can fork the repo and make the change but was wondering if there was any chance this might get added into the main source code. Would be great to have control over the chunking from the FileStorage.Upload() function, IMO.
