### ISSUE TITLE
Passing the wrong field to a query during a delete operation causes unhandled exception and process termination

### ISSUE THREAD

**Issue by ccicchitelli** [mbdavid/LiteDB#968]
Hello! One of the four daily DB cleanup tasks we were running were causing the app to crash. Turns out we were passing in the wrong field, one that didn't exist on that collection. Here is the result:

```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException
   at LiteDB.PageService.GetPage[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](UInt32)
   at LiteDB.LiteEngine+<>c__DisplayClass8_0.<Delete>b__0(LiteDB.CollectionPage)
   at LiteDB.LiteEngine.Transaction[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, Boolean, System.Func2<LiteDB.CollectionPage,Int32>)
```

This is the (sanitized) code:

        public static void CleanLog(int days)
        {
            var col = xApp.Database.GetCollection<DbLogItem>("EventLog");
            col.Delete(LiteDB.Query.LT("EventTime", DateTime.Now.AddDays(-days)));
        }

Obvious solution on our end is to add a try/catch, but wanted to make you aware. 

Thank you!

**Comment by mbdavid** [comment]
Hi @ccicchitelli, are you using LiteDB v4? This error occurs in some cases in v3 on concurrent environment... but I didn't get in v4 yet.

**Comment by ccicchitelli** [comment]
4.1.2, I'm pulling it from NuGet.

**Comment by ccicchitelli** [comment]
It seems the same method call with the wrong field name will also generate this error, or least has in the past:

`Exception Info: LiteDB.LiteException
   at LiteDB.LockService.Write()
   at LiteDB.LiteEngine.Transaction[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, Boolean, System.Func`2<LiteDB.CollectionPage,Int32>)`

**Comment by mbdavid** [comment]
Hi @ccicchitelli, creating a simple example I didn't get this error (with or without index):

```
var initial = new DateTime(2000, 01, 01);

using (var db = new LiteEngine(file.Filename))
{
    for(var i = 0; i < 5000; i++)
    {
        db.Insert("col", new BsonDocument { { "dt", initial.AddDays(i) } });
    }

    db.EnsureIndex("col", "dt");

    Assert.AreEqual(5000, db.Count("col"));

    Assert.AreEqual(4999, db.Count("col", Query.GT("dt", initial)));

    var del = db.Delete("col", Query.GT("dt", initial));

    Assert.AreEqual(4999, del);

    Assert.AreEqual(0, db.Count("col", Query.GT("dt", initial)));
}
```

This error always occurs? There is another variable that can be analyzed to detect when this happening? Are running, in another thread, any different command? It's possible write snippet code here to reproduce?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
