### ISSUE TITLE
Performance: Repeated FindOne is faster than Find with Where

### ISSUE THREAD

**Issue by LennardF1989** [mbdavid/LiteDB#969]
Just wanted to share this, as I went through a lot of optimization to get to this point.

I have a LiteDb file with price information of a webshop which acts as a cache for a VERY slow webservice. I'm used to using Lucene for these kind of problems, but I wanted to try something new.

Consider the following call:
```
        public IEnumerable<GetPriceResponse> Get(int debtorNumber, List<string> productSkus)
        {
            var keys = productSkus.Select(x => debtorNumber + "_" + x).ToList();

            var result = _liteCollection.Find(
                /*Query.And(
                    Query.EQ("DebtorNumber", debtorNumber),
                    Query.Where("ProductSku", value => productSkus.Contains(value.AsString))
                )*/
                Query.Where("Key", value => keys.Contains(value.AsString))
            );

            return result.Select(x => x.ServiceResponse);
        }
```

The commented out was initially a LINQ statement. On a set of 500 SKU's, the LINQ query took almost 300ms, not "slow", but also not really fast.

I then experimented using `Query`, and the commented part then ended up taking about 200ms for 500 SKUs.

Then I figured I could just as well combine the two into one string. Using the single Where-query, this got it down to 100ms.

Obviously MUCH faster than what I originally had, however, still not fast enough. I noticed that doing a single FindOne for the same situation (using a `Query.EQ`) took less than 0.1ms... Doing to math, 0.1 * 500 = 50ms, so even faster!

I ended up doing this:
```
            var response = new List<GetPriceResponse>();
            productSkus.ForEach(x => response.Add(ServiceLocator.PriceCache.Get(debtorNumber, x)));
```

This takes about 25ms for 500 SKUs every time!

Is there anything I might have missed to speed this particular situation up even further? More than willing to try different things to push it to the limits! My ultimate target would be to get it down to the performance of a MemoryCache using the same combined key (have no precise number on that yet, but should be around 10ms). 

I like LiteDB for the fact I can persist it, and reload it, but if that's all it gives me and in this particular case a MemoryCache is faster, then I can't keep this running in a production environment :S I reckon the whole LiteDb is in-memory all the time, so the more entries, the more memory it uses?

**Comment by mbdavid** [comment]
Hi @LennardF1989, thanks for share this. When we talk about query performance, the most important think is: has a good index to be used! Good indexes are based in how distinct keys they have. If this combination of debtorNumber + productSkus are unique: perfect. Create an index on this and use `Query.In`, like this:

```C#
public IEnumerable<GetPriceResponse> Get(int debtorNumber, List<string> productSkus)
{
    var keys = productSkus.Select(x => debtorNumber + "_" + x)
        .Select(x => new BsonValue(x))
        .ToList();
    
    // prefer use this "EnsureIndex" in you database open (to avoid checking this index in all query)
    // if you do not have this "Key" field in your class, you can create an expression:
    // I'm create as unique (set false if not possible)
    _liteCollection.EnsureIndex("Key", "$.DebtorNumber + '_' + $.ProductSku", true);
    
    // now, use Query.In
    var result = _liteCollection.Find(Query.In("Key", keys));

    return result.Select(x => x.ServiceResponse);
}
```

In v4, this should be fastest way to get this data. Check this and let me know how was the result.

**Comment by LennardF1989** [comment]
@mbdavid Thanks! I did not notice the Query.In and turning the keys into a BsonValue beforehand is not something that crossed my mind. I'll try this out and see how it performs :) Hoping it outperforms the ForEach FindOne, because that just seems counter intuitive :P

**Comment by LennardF1989** [comment]
I got it down to about 8ms in this way, so great succes. I'm still going to see how it measures against a Lucene index and a MemoryCache.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
