### ISSUE TITLE
maybe the litedb should provide a method on LiteDatabase named clearDB

### ISSUE THREAD

**Issue by Lovecxgood** [mbdavid/LiteDB#970]
maybe the litedb can provide two quick way methods on LiteDatabase named clearDb and clearDbData,
clearDb:  delete all the Collections and datas in the db;
clearDbData: delete all the  Collections datas in the db but reserve all the Collections ;

**Comment by mbdavid** [comment]
I think that first option "clearDB" is same as delete datafile. Deleting file is much better than normal Delete with Query.All().
ClearDbData is also better delete datafile and "re-create" collections with indexes definition. 

Delete data inside database is always the last option to used. Increase fragmentation and slow down new insert/query documents.

**Comment by PascalSenn** [comment]
We use this for unit tests. 
You could just wrap it with as extension method. 
```csharp
        /// <summary>
        /// Deletes all Data!
        /// </summary>
        public void Purge()
        {
            foreach (var name in DB.GetCollectionNames())
            {
                DB.DropCollection(name);
            }
        }
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
