### ISSUE TITLE
Change the password

### ISSUE THREAD

**Issue by BigPacket** [mbdavid/LiteDB#971]
Love the database, it's great.

I was able to add a password to the database, but is there a way to change the password in C#? Also, is there a way to use secure string C#?

One of the biggest problems I see is that there is a lack of program examples for us new to LiteDB. Any plans to create better documentation?

Thanks

**Comment by mbdavid** [comment]
Hi @BigPacket, to change password you must use `Shrink` method - this operation will re-write all database pages (encryption are made on page level).

Yes, documentation are not as I except, but I will try write a better version in next release. Also, everyone are welcome to contribute with this :)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
