### ISSUE TITLE
Find by params does not work

### ISSUE THREAD

**Issue by YouCanKeepSilence** [mbdavid/LiteDB#972]
Hello. I want to use LiteDB in my Unity project. Insert and FindAll, and FindById works fine, but when i'm trying to Find something by name or another parameter of my class, i always get empty result. 
in Awake function you can see example, which always return empty result. After 'Debug.Log("Test:");'
Can you help me with this problem? 

Here is my code file:
    using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using LiteDB;
using UnityEditor;
using UnityEngine;

public class Database : MonoBehaviour {
    public string DatabaseFolder;

    // Тут имеется в виду имя файлов БД
    public string ItemsFileName;
    public string DialogsFileName;

    private void CheckCorrectLaunch() {
        if (this.DatabaseFolder.Length == 0) {
            print("Init database folder to default path");
            this.DatabaseFolder = Application.dataPath + "/Sources/";
        }

        print("Database folder is: " + this.DatabaseFolder);

        if (this.ItemsFileName.Length == 0) {
            this.ItemsFileName = "items.db";
        }

        if (this.DialogsFileName.Length == 0) {
            this.DialogsFileName = "dialogs.db";
        }
    }

    void Awake() {
        this.CheckCorrectLaunch();
        InsertTestItems();
        print("Items in db: ");
        PrintAllItems();
        Debug.Log("Test:");
        var res = GetItemsByName("Б");
        foreach (var item in res) {
            print(item);
        }
        
    }

    public Item GetItemById(int id = -1) {
        if (id == -1) {
            print("Error in getItemById, did not pass id");
        }

        using (var db = new LiteDatabase(this.DatabaseFolder + this.ItemsFileName)) {
            var items = db.GetCollection<Item>("items");
            return items.FindById(id);
        }
    }

    
    public Item[] GetItemsWithRare(Rarity rarity) {
        using (var db = new LiteDatabase(this.DatabaseFolder + this.ItemsFileName)) {
            var items = db.GetCollection<Item>("items");
            print(rarity.ToString());
            return items.Find(item => item.Rare == rarity).ToArray();
        }
    }

    public Item[] GetItemsByCost(int cost) {
        using (var db = new LiteDatabase(this.DatabaseFolder + this.ItemsFileName)) {
            var items = db.GetCollection<Item>("items");
            return items.Find(Query.GTE("Cost", cost)).ToArray();
        }
    }

    public Item[] GetItemsByName(string title) {
        using (var db = new LiteDatabase(this.DatabaseFolder + this.ItemsFileName)) {
            var items = db.GetCollection<Item>("items");
            items.EnsureIndex(x => x.Title);
            var res = items.Find(Query.Contains("Title", title));
            return res.ToArray();
//            return items.Find(item => item.Title.Contains(title)).ToArray();
        }
    }
    public void PrintAllItems() {
        using (var db = new LiteDatabase(this.DatabaseFolder + this.ItemsFileName)) {
            var items = db.GetCollection<Item>("items");
            var result = items.FindAll().ToArray();

            foreach (var item in result) {
                print(item);
            }
        }
    }

    public void InsertTestItems() {
        using (var db = new LiteDatabase(this.DatabaseFolder + this.ItemsFileName)) {
            db.DropCollection("items");
            var items = db.GetCollection<Item>("items");
            List<Item> list = new List<Item>();
            list.Add(new Item() {
                Cost = 5,
                Title = "Баранка",
                Description = "Мучная баранка, средней вкусности",
                MaxCount = 20,
                Level = 1,
                Rare = Rarity.Common,
                Type = TypeOfItem.UsefulItem,
                AttackDamage = 0,
                Endurance = 0,
                Wisdom = 0,
                Charisma = 0,
                Intelligence = 0,
                Adaptibility = 0,
                NameOfIcon = "baranka.png",
            });

            list.Add(new Item() {
                Cost = 100,
                Title = "Дорогая баранка",
                Description = "Уже не мучная, а золотая баранка, абсолютно не вкунсая, но красивая",
                MaxCount = 2,
                Level = 1,
                Rare = Rarity.Uncommon,
                Type = TypeOfItem.UsefulItem,
                AttackDamage = 0,
                Endurance = 0,
                Wisdom = 0,
                Charisma = 0,
                Intelligence = 0,
                Adaptibility = 0,
                NameOfIcon = "baranka_golden.png",
            });
            
            list.Add(new Item() {
                Cost = 666,
                Title = "Кровавая луна",
                Description = "Легендарный топор, принадлежащий Громмашу Адскому Крику",
                MaxCount = 1,
                Level = 10,
                Rare = Rarity.Artifact,
                Type = TypeOfItem.Weapon,
                AttackDamage = 100,
                Endurance = 10,
                Wisdom = 2,
                Charisma = 0,
                Intelligence = 0,
                Adaptibility = 10,
                NameOfIcon = "bloodmoon.png",
            });
            items.Insert(list);
        }
    }
}

public class Item {
    [BsonId] public int Id { get; set; }
    public int Cost { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public int MaxCount { get; set; }
    public int Level { get; set; }
    public int AttackDamage { get; set; }

    public Rarity Rare { get; set; }
    public TypeOfItem Type { get; set; }

    public int Endurance { get; set; }
    public int Wisdom { get; set; }
    public int Charisma { get; set; }
    public int Intelligence { get; set; }
    public int Adaptibility { get; set; }

    public string NameOfIcon { get; set; }
    public Sprite Icon { get; set; }

    public Item() {  }

    public override string ToString() {
        return String.Format("Предмет с id: {0} \n" +
                             "Имя: {1} \n" +
                             "Стоимость: {2} \n" +
                             "Описание: {3} \n" +
                             "Максимальное количество: {4} \n" +
                             "Уровень: {5} \n" +
                             "Редкость {6} \n" + 
                             "Тип: {7} \n" + 
                             "Урон: {8} \n" +
                             "Выносливость {9} \n" +
                             "Мудрость {10} \n" +
                             "Харизма {11} \n" +
                             "Интеллект {12} \n" +
                             "Адаптивность {13} \n" +
                             "Имя иконки {14} \n"
            , Id, Title, Cost, Description, MaxCount, Level, Rare, 
            Type, AttackDamage, Endurance, Wisdom, Charisma, Intelligence, 
            Adaptibility, NameOfIcon);
    }

}

public enum Rarity {
    Common,
    Uncommon,
    Rare,
    Epic,
    Artifact
}

public enum TypeOfItem {
    Amulet,
    Helment,
    Ring,
    Gloves,
    Armor,
    Weapon,
    Belt,
    Boots,
    Trash,
    QuestItem,
    ComponentForCraft,
    UsefulItem
}

**Comment by mbdavid** [comment]
Hi, there are some differences in .NET for unity.... I made an branch exclusive to work with unity.

**Comment by YouCanKeepSilence** [comment]
Can i find it on NuGet or only compile from sources?

**Comment by YouCanKeepSilence** [comment]
Thanks for answer! Good luck)
