### ISSUE TITLE
GeoJSON and GeoSpatial Queries?

### ISSUE THREAD

**Issue by itech4ever** [mbdavid/LiteDB#973]
Dear all, I am wondering if LiteDB supports GeoJSON and GeoSpatial queries? Thanks a lot!

**Comment by mbdavid** [comment]
Hi @itech4ever, Is GeoJSON/GeoSpatial only data structure representations? Or there is any operation about this?

**Comment by itech4ever** [comment]
Yes, I am planning to perform some geo queries like $near on those data. Does LiteDb support this? Thanks!

**Comment by mbdavid** [comment]
There is no support for query functions using spatial.... this type of function must be implemented using BsonExpressions. This could be a plugin for LiteDB. Have you know where I can found specs about this spatial functions?

**Comment by itech4ever** [comment]
Hi Mauricio, I actually came across this question when I compared LiteDb with MongoDB. Here is some docs around it: https://docs.mongodb.com/manual/geospatial-queries/

Thanks a lot for looking into this.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
