### ISSUE TITLE
Rename a stored file

### ISSUE THREAD

**Issue by chris-ga** [mbdavid/LiteDB#974]
Hello,
is their a way to rename a stored file?
Wether Id- nor Filename-property in LiteFileInfo is writable - and I found no suitable method in the FileStorage class, too.
Thx.

**Comment by mbdavid** [comment]
Hi, `FileStorage` just implement file chunks over 2 normal collections: `_files` and `_chunks`. 

You can't change `_id` field on `_files` collection, but you can change `Filename` field on `_files`. Just run a normal Update over this:

```
var col = db.GetCollection("_files");
var doc = col.FindById("your-file-id");
doc["filename"] = "NewFilename.txt";
db.Update(doc);
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
