### ISSUE TITLE
How to use col.Find

### ISSUE THREAD

**Issue by BigPacket** [mbdavid/LiteDB#977]
Greetings,

I'm having a heck of a time trying to get the find feature to return true or false or even the results. By the looks of it, it returns null but I still can't get it just quite right. Obviously, I'm doing something wrong here but can't see what it is.

I was trying to get the function to return false if the value is null and true otherwise. I would really like to know how to receive the results of a search? I'm using C#; a complete code example would be quite helpful.

The connection string is in place using a password for encryption.

            using (var db = new LiteDatabase(DBConn(LITEDBROOT, strDBDIME)))
            {
                var col = db.GetCollection<MyDBClass>();
                var customerName = col.Find(x => x.UserName == strUserName && x.DIME.Contains(strDIME));
                // I can see my query in the results view but don't know how to retrieve it and confirm that it is there.
                bool NullX = customerName == null; // Keeps coming up false.
                if (NullX == true)
                {
                    // Do nothing
                    //MessageBox.Show("Not Found");
                    return false;
                }
                else if (NullX == false)
                {
                    //MessageBox.Show(customerName.UserName);
                    return true;
                }
                return false;
            }

Any help will be appreciated. Thank you in advance.

**Comment by mbdavid** [comment]
Hi @BigPacket, `Find` method returns `IEnumerable` data type. Will be never null. If you only want if exists or not data, you can use `Exists` method (return a `bool`)

    using (var db = new LiteDatabase(DBConn(LITEDBROOT, strDBDIME)))
    {
        var col = db.GetCollection<MyDBClass>();
        return col.Exists(x => x.UserName == strUserName && x.DIME.Contains(strDIME));
    }

**Comment by BigPacket** [comment]
I figured I was doing something wrong. This worked well. Thanks so much!
