### ISSUE TITLE
IncludeAll functionality

### ISSUE THREAD

**Issue by SeAlwin** [mbdavid/LiteDB#979]
Hello Mauricio,

We need the IncludeAll option as in pull-request: https://github.com/mbdavid/LiteDB/pull/911

Currently I forked LiteDB and made these changes, but ideally I would like to have it in the current release (as a patch) and not build my own dll. 
Do you think this PR will be incorporated (one way or the other?)

Kind regards
Alwin

**Comment by SeAlwin** [comment]
Hi Mauricio,

Yep, will do

Alwin

On 19 May 2018, at 15:21, Mauricio David <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @SeAlwin<https://github.com/SeAlwin>, you way to implement deep includles seems more right than 911. Can you make a PR with your code? (need some unit tests too)

**Comment by SeAlwin** [comment]
Hi Mauricio,

I created PR #987 with the revised IncludeAll option.
Would be nice if you can put this into the patch release of 4.

I assume you sideload this functionality yourself into V5?

Kind regards
Alwin

**Comment by SeAlwin** [comment]
Hi Mauricio, thanx, you can close this issue now.

Kind regards
Alwin

**Comment by cryodream** [comment]
Hi, I am using the 4.1.3 version from nuget, and I cannot find the **IncludeAll()** method on the LiteCollection class. What am I doing wrong?

As you can see, the only choice is **Include()**

![2018-06-03_05-44-04__devenv](https://user-images.githubusercontent.com/844036/40885270-4bdda274-66f1-11e8-9635-08f73857c924.png)
