### ISSUE TITLE
Question: storing strong named type which are registered in GAC

### ISSUE THREAD

**Issue by vxmark** [mbdavid/LiteDB#980]
https://github.com/mbdavid/LiteDB/blob/5c596cbc34ce91de83acc52d85603c342830e588/LiteDB/Mapper/BsonMapper.Serialize.cs#L157

Is it for a special reason that the code line linked above doesn't use the "AssemblyQualifiedName" property of the type but instead uses "Assembly.GetName().Name" ?

I am running into problems if I am trying to store and after that read an object of a strongly named type. LiteDB rises "InvalidTypedName" Exception:
https://github.com/mbdavid/LiteDB/blob/5c596cbc34ce91de83acc52d85603c342830e588/LiteDB/Utils/LiteException.cs#L196

The name of the assembly only gets stored with (from my point of view) insufficient type information. But that might be by intention? Maybe somebody could clarify,

**Comment by mbdavid** [comment]
Hi @vxmark, I use `Assembly.GetName().Name` because works fine for non GAC assemblies. And I don't remember now, but I think I copy this from MongoDB C# driver.... I will check it.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
