### ISSUE TITLE
Need for "Flush" option?

### ISSUE THREAD

**Issue by resnickj** [mbdavid/LiteDB#981]
One of the options in the connection string is "flush", which says "Write data direct to disk avoiding OS cache".  I'm trying to understand why this option exists?  Is the implication that if flush=false, then there is no guarantee that your data is actually written to disk (may just be sitting in the OS cache)? Would this not break the durability guarantee?

**Comment by mbdavid** [comment]
Hi @resnickj, a normal `Write` operation do not store immediate on disk - store in OS cache to be save later. If you this parameter, LiteDB uses Flush(true) option after write on disk.

https://msdn.microsoft.com/pt-br/library/ee474552(v=vs.110).aspx

The difference is: if flush = false and power off occurs AFTER database commit - this last transaction can be lost (but you program received OK for this transaction). So yes, you can lost this last transaction. If flush = true, LiteDB will wait real write on this before say OK to your transaction. This second way are quite slow.

**Comment by resnickj** [comment]
@mbdavid Thanks for the explanation - this is what I figured, but I wanted to be sure I understood. In my opinion, you might want to draw more attention to this setting. It is not uncommon to have an application that cannot afford to lose any transactions. In my experience, databases usually default to the most conservative and safe options. By making Flush=false the default for LiteDB, you are taking the opposite approach, and your users may not be aware of this.

Great work btw - very useful database library!
