### ISSUE TITLE
Best way to find and update a single item?

### ISSUE THREAD

**Issue by kombasltd** [mbdavid/LiteDB#983]
Hi, 

I am new to in memory databases and like to code a login tracking database via a REST API (Web API).

This is my "Token" object per user:
```
resultUserLicense.UserToken = new Classes.UserToken();
resultUserLicense.UserToken.Serial = license.Serial;
resultUserLicense.UserToken.Login = DateTime.Now;
resultUserLicense.UserToken.UserID = Guid.NewGuid().ToString().ToUpper();
```
which I store in the LiteDB like this and which works well so far:
```
var col = Helper.licenseDB.dbcontext.GetCollection<Classes.UserToken>("usertoken");
col.Insert(LiteDB.ObjectId.NewObjectId(), resultUserLicense.UserToken);
```
I learned that I need to add a unique Id to store the object because I haven't found an auto-ID or something like that.

Now I like to update the Datetime value every 5 Minutes from the client. For that I created an "alive" endpoint in the Web API. And here is my question:

What is the best way to get one item from the DB which is "unique" by the UserID and update the "Login" value with the actual time?

I tried it with
```
var col = Helper.licenseDB.dbcontext.GetCollection<Classes.UserToken>("usertoken");
Classes.UserToken _userToken = col.FindOne(x => x.UserID == userToken.UserID);
```
but now I have no clue how to update the fetched _userToken in the DB again.

**Comment by kombasltd** [comment]
Fixed it. Seems that you need to have an "Id" property within your objects to make autoincrement identifier possible.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
