### ISSUE TITLE
Add Time issue with date data

### ISSUE THREAD

**Issue by kombasltd** [mbdavid/LiteDB#985]
Hi,

after some playing with your database I am very happy with it, thanks a lot!

Maybe I found a bug related to date values (I know they are treated special):

`var oldUsers = col.Delete(x => x.Login.AddMinutes(5) < DateTime.Now);`

**this works**, but it throws a "System.NotSupportedException" in LiteDB.dll. Cause is the AddMinutes.

**Comment by mbdavid** [comment]
Hi @kombasltd, it not a bug, it a feature 😄 LOL

Find/Delete/Exists/Count has no opeation converted from LINQ to index or full scan execution. So, here is no LINQ visitor for AddMinutes. In v4, left side must by a key only and right side must be a value only. In you example you can just do:

`var oldUsers = col.Delete(x => x.Login < DateTime.Now.AddMinutes(-5));`

Now, left side are just simple field and right side are only a constant value.

Also, you can create an index in "Login" field be more efficient: 

`col.EnsureIndex(x => x.Login)`

**Comment by kombasltd** [comment]
Got it, thanks!
