### ISSUE TITLE
Character length or greater than zero

### ISSUE THREAD

**Issue by BigPacket** [mbdavid/LiteDB#986]
Greetings,

I need to make a choice based on if there is text located in a cell of the database. For example, checking to see if there are no character length or greater than zero.

I tried things like: var b = `"col.Find(x=> x.TrashInHouse.Length > 0);"`  but to no avail.

Is there a way to check if a cell has string length greater than zero?

Thanks

**Comment by mbdavid** [comment]
Hi @BigPacket, you can use an index for that:

`col.EnsureIndex("idx_trash_len", "LENGTH($.TrashInHouse)");`

and use:

`col.Find(Query.GT("idx_trash_len", 0))`

**Comment by BigPacket** [comment]
Thank you for the fast reply mbddavid.

I get a "Method LENGTH not exist or invalid parameter count" at `col.EnsureIndex("idx_trash_len", "LENGTH($.TrashInHouse)");`.

**Comment by mbdavid** [comment]
Oh, you right, there is no length method in expression. Must be added here... 

https://github.com/mbdavid/LiteDB/blob/master/LiteDB/Document/Expression/Methods/String.cs

I will review this tonight..

**Comment by BigPacket** [comment]
Hi mbdavid ,

I was just trying to load the project in VS 2015, but got the following errors:

The default XML namespace of the project must be the MSBuild XML namespace. C:\Users\UserName\Documents\Visual Studio 2015\Projects\LiteDB-master\LiteDB\LiteDB.csproj

and 

The attribute "Version" in element <PackageReference> is unrecognized.

Did you get a chance to review for length method?

I thank you for all of your assistance.

**Comment by mbdavid** [comment]
Hi @BigPacket, sorry, but LiteDB works only in VS2017 to support netStandard and multi target.

I will release new version this weekend (tomorrow).

**Comment by BigPacket** [comment]
Cool, thank you.

**Comment by BigPacket** [comment]
While I'm waiting for the newly compiled dll. I'm trying to understand the use of 'col.EnsureIndex("idx_trash_len", "LENGTH($.TrashInHouse)");' and 'col.Find(Query.GT("idx_trash_len", 0))'. 

I understand that "$.TrashInHouse)" would be the column header but I don't know what "idx_trash_len" is. Because, the results from what I'm seeing would always result in zero even if there is content in the cell underneath the heading TrashInHouse.

I'm trying to get the information this way `List<StoreIt.StoreProgram> query = new List<StoreIt.StoreProgram>();
                //query = col.Find(Query.Contains(Query.EQ("uN17X3NQ", ""))).ToList(); // Don't work.
                col.EnsureIndex("idx_trash_len", "LENGTH($.uN17X3NQ)");
                query = col.Find(Query.GT("idx_trash_len", `0)).ToList();`

Probably doing that wrong as well. Can you show me a more complete example of how to read tree the text length and if no length "string.empty" return zero.

Thank you

**Comment by mbdavid** [comment]
Hi @BigPacket, `idx_trash_len` are an index created based on an expression `LENGTH($.TrashInHouse)`. This index contains only the length of TrashInHouse. When you run a query like `col.Find(Query.GT("idx_trash_len", 0))` you are searching only documents, in this index, that has this index key > 0. Is like an "virtual property" on your document, like this:

```C#
public class Customer
{
    public string Name { get; set; }
    public int NameLength => this.Name?.Length ?? 0;
}
```

And then you create an index and search using "NameLength" property.

I'm releasing 4.1.3 now and you can test it. If not work, fork my code and write some example in "LiteDB.Demo" code.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
