### ISSUE TITLE
Two webservices on the same liteDB?

### ISSUE THREAD

**Issue by kombasltd** [mbdavid/LiteDB#991]
Hi,

I have two webservices (admin service and user service) and I like to use the same liteDB database on both services. Is this possible in terms of data consistency?

**Comment by xied75** [comment]
I think LiteDB can make sure each Ops done perfectly. The question is on your side: SvcA write to record 1, done, SvcB then write again on record 1, done, do you want the A or B result? Synchronization is needed on your app level.

**Comment by kombasltd** [comment]
There will be no concurrent operations on the same data item, only on the same table.

At the moment I am not really sure yet, if and how I will use liteDB. For my main data I use a MySql database. I evaluate liteDB to use it as a central configuration storage for my services / Tasks.

**Comment by xied75** [comment]
Then it should be fine, it's easy to test, just use Task to spin lots insert and update.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
