### ISSUE TITLE
Unable to cast object of type 'LiteDB.CollectionPage' to type 'LiteDB.ExtendPage'.

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [mbdavid/LiteDB#992]
Hello,
I have this problem when i do query in my existing database,I'm using last version of LiteDB (from Git master pull)

pls check my uploaded database and tell me how can i fix this, my customer data is lost.
http://uploadboy.me/3zu2nzvggwy2/AgrinClientDatabase.db.html

check test code:

```csharp
using (var db = new LiteDatabase("AgrinClientDatabase.db"))
                {
                    var names = db.GetCollectionNames().ToArray();
                    foreach (var item in names)
                    {
                        var query = db.GetCollection(item);
                        try
                        {
                            var all = query.FindAll().ToList();
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine(ex);
                        }
                    }
                }
```

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
