### ISSUE TITLE
OutOfMemoryException when using Shrink (litedb 4.1.2)

### ISSUE THREAD

**Issue by mrhieu84** [mbdavid/LiteDB#993]
I worked with  big files using FileStorage. When shrinking ~ 2,5 GB database, litedb throws OutOfMemoryException. (version 4.1.2) 
![image](https://user-images.githubusercontent.com/39661601/40581755-570218d6-618a-11e8-9db7-6ecf06bb93b4.png)

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
