### ISSUE TITLE
Question of "LiteFileStream Dispose" 

### ISSUE THREAD

**Issue by mck0225** [mbdavid/LiteDB#995]
https://github.com/mbdavid/LiteDB/blob/373c5e56cca061af4fd9362ad92f728f889f7bfe/LiteDB/Storage/LiteFileStream.cs#L82-L105

Should not you change it like this?

        #region Dispose

        ~LiteFileStream()
        {
            Dispose(false);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (disposing)
            {
                if (this.CanWrite)
                {
                    this.Flush();
                }
            }
        }

        #endregion

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
