### ISSUE TITLE
Any way to get all keys quickly?

### ISSUE THREAD

**Issue by wizicer** [mbdavid/LiteDB#997]
In my case, I need retrieve all keys during application loading stage to have memory mapping for quick action. 
Currently, I'm using following method to retrieve all keys, found it not quick enough, the performance is similar to query all keys and their data.
```
        public IEnumerable<string> RetrieveKeys(string category)
        {
            var col = this.dbConnection.GetCollection<CollectionType>(category);
            return col.FindAll()
                .Select(_ => _.Key);
        }
```

Could you give me any suggestion?

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
