### ISSUE TITLE
Possible fix for AOT platforms?

### ISSUE THREAD

**Issue by mnarimani** [mbdavid/LiteDB#999]
As I noticed, This library has problems with AOT compilation (as others who provide expressions for doing queries). But I came across something recently. I'm not sure if this fixes the problem or not.
Here is a link to documentation:
[Microsoft documentation for Compile method](https://msdn.microsoft.com/en-us/library/dd268054(v=vs.110).aspx)

A new overload of LambdaExpression.Compile has been added to the .Net that takes a boolean as parameter.

> true to indicate that the expression should be compiled to an interpreted form, if it's available; otherwise, false.

I don't know what that means but it seems good. lol.
Can this possibly solve AOT compilation problems?

**Comment by xied75** [comment]
AOT as in CoreRT? I use LiteDB in my UWP app and it compiles fine.

**Comment by sorencoder** [comment]
@xied75 I use AOT compilation in Unity3d Game Engine and it "compiles" fine, but it doesn't "run" fine. I can open database and insert stuff. But it throws errors and complains about Reflection.Emit when I try to use Linq Expressions to query the database.

**Comment by jganser** [comment]
Same Problem here. Since IL2CPP will be the only supported build option in the future it is quite a problem that it doesn't allow to use System.Reflection.Emit.

**Comment by lbnascimento** [comment]
Hi! With the objective of organizing our issues, we are closing old unsolved issues. Please check the latest version of LiteDB and open a new issue if your problem/question/suggestion still applies. Thanks!
